### ISSUE TITLE
libspatialindex-dev on mac

### ISSUE THREAD

**Issue by AlexLee** [mikedh/trimesh#10]
how do you install libspatialindex-dev on a mac? I only saw windows builds here  
https://libspatialindex.github.io/
In order to run convexhull.py, I need rtree which in turn needs libspatialindex-dev

**Comment by mikedh** [comment]
You may be able to build it using cmake as they suggest on their webpage. 

Also note that it is the 'clean' option which requires libspatialindex, if you don't mind backwards faces you can do:

     c = trimesh.convex.convex_hull(mesh, clean=False)

I'm going to close this as it relates more to libspatialindex than trimesh.
