### ISSUE TITLE
Validate a STL

### ISSUE THREAD

**Issue by JPFrancoia** [mikedh/trimesh#100]
Hello,

I came across trimesh yesterday, and it might be exactly what I'm looking for. I'm writing a software that will generate stl files. I need to check that these stl are valid (i.e.: no inverted normals, no duplicate faces, etc).

For now I do it manually with Freecad and its mesh analysis feature (Mesh > Analyse > evaluate and repair):

![screen](https://user-images.githubusercontent.com/2399090/32486041-5b2b1358-c39d-11e7-9a01-02c934ad4616.png)

I found ```mesh.is_watertight``` in trimesh. It returns True if there is non-manifold surfaces in the mesh, right ?

Is there a way to get booleans for the presence of duplicated faces, folds on the surface, degenerated faces, etc ?

Cheers

**Comment by mikedh** [comment]
Hey, yeah `is_watertight` is True if every edge appears exactly twice, as they should in a well constructed watertight mesh. The other property that might be relevant:

```

In [4]: mesh.is_winding_consistent?

Type:        property
String form: <property object at 0x000002815FA8EF48>
Docstring:
Does the mesh have consistent winding or not.
A mesh with consistent winding has each shared edge
going in an opposite direction from the other in the pair.

Returns
--------
consistent: bool, if winding is consistent or not
```

**Comment by JPFrancoia** [comment]
Hey, thanks for your answer. I'm not an native english speaker, so could you explain to me what winding means for a CAD object please ?

Also, is it enough to check only ```is_watertight``` and ```is_winding``` to make sure a STL is valid ?

**Comment by mikedh** [comment]
So winding is just the order of the vertices in a triangle, this article is pretty good: http://cmichel.io/understanding-front-faces-winding-order-and-normals/

Re: a mesh being valid, that's a great question. To the best of my knowledge, if a mesh has every edge included by exactly two triangles, and each edge is reversed in those two triangles it means that the surface is correctly defined. 

If EVERY triangle has winding which implies a normal facing in rather than out, it could also be an invalid volume. In that case you can check mesh.volume, which will then be negative. 

I think the check you want is:
```
valid_volume = mesh.is_winding_consistent and mesh.is_watertight and mesh.volume > 0
```

**Comment by JPFrancoia** [comment]
Ok, thanks for the link.

However I'm not sure that I want to check winding. Here is a sample stl file:

[test.stl.txt](https://github.com/mikedh/trimesh/files/1467048/test.stl.txt)

I checked it with FreeCAD, and no warning was raised. So I want to consider it valid. But trimesh says the winding is not consistent.

Is there a way to check for other defects ? Duplicate faces, degenerated faces, folds on the surface ?

**Comment by mikedh** [comment]
Hey, actually the mesh you sent over looks ok to me- both `mesh.is_volume` and `mesh.is_winding_consistent` are True on my machine. What platform are you on? It could be a precision issue.

So if you're looking for additional checks, what all of these are basically doing is checking to see if each edge occurs exactly twice, and the two instances of the edge are reversed. `is_volume` which I added recently in response to this issue also checks to make sure *every* triangle isn't reversed which will result in a negative volume. 

As for this mesh, if you pull the latest trimesh with a `pip install -U trimesh` you can inspect a little more with `trimesh.repair.broken_faces`:

```
In [1]: import trimesh

In [2]: m = trimesh.load('test.stl')

In [3]: m.is_volume
Out[3]: True

In [4]: m.is_watertight
Out[4]: True

In [5]: m.is_winding_consistent
Out[5]: True

# break the mesh by deleting the first face 
In [6]: m.faces = m.faces[1:]

In [7]: m.is_volume
Out[7]: False

# color faces which are broken red
In [8]: trimesh.repair.broken_faces(m, color=[255,0,0,255])
Out[8]: array([3, 0, 5])

# suppress smoothing to see faces clearly
In [9]: m.show(smooth=False)
Out[9]: <trimesh.scene.scene.Scene at 0x7f021aa96fd0>
```

**Comment by JPFrancoia** [comment]
@mikedh :

> Hey, actually the mesh you sent over looks ok to me- both mesh.is_volume and mesh.is_winding_consistent are True on my machine. What platform are you on? It could be a precision issue.

Ok I found the problem, try:

```python
print(m.is_winding_consistent is True)
```

It will print False. But:

```python
print(m.is_winding_consistent)
```

Prints True.

I sent this stl file because my uni tests crash on assert ```m.is_winding_consistent is True```.

It's weird, it shouldn't be like that. The type of ```m.is_winding_consistent``` is ```<class 'numpy.bool_'>```, could it be why ?

Also thanks for your modifications to trimesh, they are greatly appreciated and make my work easier.

**Comment by mikedh** [comment]
Ah, that is interesting. Yeah numpy comparisons return a numpy bool and the exact `x is True` is checking against the python True object. See: https://stackoverflow.com/questions/34950451/why-is-comparison-to-true-false-using-the-is-operator-bad

I would recommend doing the check like:

```
if not mesh.is_volume:
     raise ValueError('operation requires a watertight volume!')
```

That being said I just wrapped all the `is_volume/is_whatever` functions with a bool() call anyway, no need to return the numpy bool, I'll push in a little while.

No problem- thanks for the feedback!

**Comment by JPFrancoia** [comment]
Thank you for the link, you're right my code wasn't perfect. I think these three tests will be enough for my use case.

Thank you again.

**Comment by ynotstartups** [comment]
Thanks for changing numpy bool to bool, it gave me headache for trying to json.dumps it. 

https://github.com/mikedh/trimesh/commit/cbb0e7eb3ef3a58cfb9092f68887205ec5e7c933
