### ISSUE TITLE
Find Farthest Point in Point Cloud along a Direction

### ISSUE THREAD

**Issue by dhirajsuvarna** [mikedh/trimesh#1003]
Hi,

I need to find the farthest point in a given set of point cloud along the direction.

One of the approach is to project the points on the given direction and sort all the points in that direction.

I went through the docs to implement this but am stuck. Can you guide me on this?

**Comment by mikedh** [comment]
Hey, I think you just want the dot product of the points with the vector:
```
In [1]: import numpy as np

In [2]: points = np.random.random((1000, 3))

In [3]: direction = np.array([0,1,1], dtype=np.float64)

In [4]: direction /= np.linalg.norm(direction)

In [5]: direction
Out[5]: array([0.        , 0.70710678, 0.70710678])

In [6]: projection = np.dot(points, direction)

In [7]: projection
Out[7]: 
array([0.70088448, 0.65949939, 1.18006079, 0.13080423, 0.16275799,
       0.8610082 , 0.87336078, 0.29556105, 1.1413954 , 0.83225346,
      ...
       0.36990099, 0.83421947, 0.29362766, 0.19289792, 1.01728976,
       0.89257825, 1.01178599, 1.0110758 , 0.69608609, 0.60927195])

In [8]: furthest = points[direction.argmax()]

In [9]: furthest
Out[9]: array([5.54723451e-01, 7.69153639e-04, 9.31903824e-01])

```

**Comment by paulmelnikow** [comment]
Can confirm this implementation looks good. ([This is the one I use.](https://vgpy.readthedocs.io/en/latest/_modules/vg/core.html#apex))

FWIW you don't need to normalize `direction` since the max is still the max.

**Comment by dhirajsuvarna** [comment]
@mikedh 

I think there is a typo here - 
> In [8]: furthest = points[direction.argmax()]

Should be 
> In [8]: furthest = points[projection.argmax()]

**Comment by mikedh** [comment]
Ah yeah that's a typo, `projection.argmax()` is correct.
