### ISSUE TITLE
[Beginner Question] How to generate a trimesh from adjacency matrix?

### ISSUE THREAD

**Issue by ucalyptus** [mikedh/trimesh#1006]
@mikedh Thanks for the software.
I have a N*N adj matrix and I am a beginner in compu. geometry.

**Comment by ucalyptus** [comment]
Also , it would help to know if computing the dual of a mesh is possible using trimesh.

**Comment by mikedh** [comment]
Hey, I think marching cubes is probably what you want. Trimesh has a helper function here: https://github.com/mikedh/trimesh/blob/master/trimesh/voxel/ops.py#L101

**Comment by ucalyptus** [comment]
Sure @mikedh , also can you let me know abt this?
https://github.com/mikedh/trimesh/issues/1006#issuecomment-696867664

**Comment by mikedh** [comment]
Ah the dual being:

> The dual of a 2-manifold polygonal mesh without boundary is commonly defined as another mesh with the same topology (genus) but different connectivity (vertex–face incidence), in which faces and vertices occupy complementary locations and the position of each dual vertex is computed as the center of mass (barycenter or centroid) of the vertices that support the corresponding face. 

That's tough, yeah it's not in trimesh currently. Another way of stating that is you're looking for "all the unique 3-length cycles of `mesh.face_adjacency`". You might check out networkx and scipy csgraph. Happy to take PR's too if you find a nice way to implement it!
