### ISSUE TITLE
Question on wire frame

### ISSUE THREAD

**Issue by yingzhang1109** [mikedh/trimesh#1009]
I am trying to get the wireframe of the mesh. That's what I did
frame2 = trimesh.load_path(mesh.vertices[mesh.edges_unique])
and that's what I got
![image](https://user-images.githubusercontent.com/25900394/94051752-00521800-fda6-11ea-858d-39da923bcd31.png)
However, I think that's too many lines for wireframe. I am wondering if I can get something like this
![image](https://user-images.githubusercontent.com/25900394/94051829-211a6d80-fda6-11ea-9c70-9e2b92ae6ced.png)
Any suggestion is welcomed! Thanks a lot!

**Comment by mikedh** [comment]
Hey, check out the [`outlined.py` example](https://github.com/mikedh/trimesh/blob/master/examples/outlined.py). Picking the edges that get outlined isn't super well defined but I've found the angle threshold used in that example works pretty well for mechanical parts with crisp edges. You could also do it by looking for adjacent faces with different-sign normals and then use that edge.

**Comment by yingzhang1109** [comment]
I will try it. Thank you
