### ISSUE TITLE
Merging multiple meshes into one

### ISSUE THREAD

**Issue by jsaisagar** [mikedh/trimesh#1013]
Hi,

I have a problem where I have two meshes. I need to generate one mesh by some sort of fusion.

To be more specific, I have a human body mesh and cloth mesh separately. When I superimpose both meshes I get a clothed human body. Is there a good method where I can remove vertices of human body mesh that are occluded by clothed mesh?

I need only point cloud after fusion which I can later meshify.

Thanks for any help.

**Comment by mikedh** [comment]
Hey, I would probably sample points on the surface of the mesh you want to use as the occluder (i.e. `mesh.sample` on the cloth), then use ray checks from those points and reverse face normals (i.e. onto the person) to check for triangle indexes occluded.
