### ISSUE TITLE
'Scene' object has no attribute 'area_faces'

### ISSUE THREAD

**Issue by muneebsaif** [mikedh/trimesh#1019]
i am facing this issue while using trimesh how can i overcome this issue?

**Comment by mikedh** [comment]
Hey, the mesh probably loaded as a scene format... you might try forcing it into a mesh:
`mesh = trimesh.load(file_name, force='mesh')`

**Comment by gdw666** [comment]
'Trimesh' object has no attribute 'facet_aspect_ratio'
