### ISSUE TITLE
choosing the texture file name in obj export

### ISSUE THREAD

**Issue by martinResearch** [mikedh/trimesh#1023]
Hi, 

thank you very much for this great library.
I am trying to export several obj files in the same folder, but  their texture and material files get overwritten as it seems that the obj export always uses **material0.png** as the file name for the texture. Is it possible to avoid that behavior with the existing code ? 
If not, looking at[ this line](https://github.com/mikedh/trimesh/blob/d851c6a4583c920c9c9c9924dbbfd09ad83539d6/trimesh/exchange/obj.py#L822 )
it seems that it would be possible to provide the texture name as argument to the material.to_obj function.
it would be great to have boolean argument to indicate that the texture file name should be "{name_geometry_obj_file}_material.png" for example, so that the texture files do not get overwritten when exporting several obj files in the same folder.

**Comment by mikedh** [comment]
Ah yeah being able to set the name makes sense. The fix I just pushed to a branch would let you do something like:
```
In [8]: a = trimesh.load('models/fuze.obj')

In [9]: b = trimesh.load('models/fuze.obj')

In [10]: ls -altrsh
...
8.0K drwxrwxr-x   5 mikedh mikedh 4.0K Oct  6 13:50  tests/

In [11]: a.visual.material
Out[11]: <trimesh.visual.material.SimpleMaterial at 0x7fed44dd5518>

In [12]: a.visual.material.name
Out[12]: 'material0'

In [13]: a.visual.material.name = 'bottleA'

In [14]: b.visual.material.name = 'bottleB'

In [15]: _ = a.export('a.obj')

In [16]: _ = b.export('b.obj')

In [17]: ls -altrsh
...
8.0K drwxrwxr-x   5 mikedh mikedh 4.0K Oct  6 13:50  tests/
4.0K -rw-rw-r--   1 mikedh mikedh  192 Oct  6 13:50  bottleA.mtl
 88K -rw-rw-r--   1 mikedh mikedh  86K Oct  6 13:50  bottlea.jpeg
 68K -rw-rw-r--   1 mikedh mikedh  65K Oct  6 13:50  a.obj
4.0K -rw-rw-r--   1 mikedh mikedh  192 Oct  6 13:50  bottleB.mtl
 88K -rw-rw-r--   1 mikedh mikedh  86K Oct  6 13:50  bottleb.jpeg
 68K -rw-rw-r--   1 mikedh mikedh  65K Oct  6 13:50  b.obj
 24K drwxrwxr-x  22 mikedh mikedh  20K Oct  6 13:50  ./

In [18]: 

```

**Comment by martinResearch** [comment]
you have been very quick! thank you very much for that. That is a great solution, however it requires the user to modify the material name with some extra lines of code. The solution I came with is here https://github.com/martinResearch/trimesh/commit/31fa4af4a9b426ad5d4649f2204f85b05105b669
would that also be an acceptable solution ? maybe we could support both solutions ?

**Comment by martinResearch** [comment]
@mikedh , the fix you mentioned you pushed to a branch in your reply above would be a good enough solution in my case. Do you plan to merge it into the main branch anytime soon ?

**Comment by mikedh** [comment]
Hey, I think this made it to `master`, trying right now: 
```
    trimesh.util.attach_to_log()

    a = trimesh.load('models/fuze.obj')
    b = trimesh.load('models/fuze.obj')

    a.visual.material.name = 'bottleA'
    b.visual.material.name = 'bottleB'

    a.export('a.obj')
    b.export('b.obj')
```
Creates:
```
ls -altrsh
4.0K -rw-rw-r--   1 mikedh mikedh  192 Nov 16 15:52  bottleA.mtl
 88K -rw-rw-r--   1 mikedh mikedh  86K Nov 16 15:52  bottlea.jpeg
 68K -rw-r--r--   1 mikedh mikedh  65K Nov 16 15:52  a.obj
4.0K -rw-rw-r--   1 mikedh mikedh  192 Nov 16 15:52  bottleB.mtl
 88K -rw-rw-r--   1 mikedh mikedh  86K Nov 16 15:52  bottleb.jpeg
 68K -rw-r--r--   1 mikedh mikedh  65K Nov 16 15:52  b.obj
4.0K drwxr-xr-x  22 mikedh mikedh 4.0K Nov 16 15:52  .
```

**Comment by martinResearch** [comment]
Great, thank you very much. I will close the issue then
