### ISSUE TITLE
remove texture from mesh

### ISSUE THREAD

**Issue by pvnieo** [mikedh/trimesh#1024]
Hi,

Thanks for the great library.

I don't have a issue, but a rather a question that I didn't succeed to have a response to it. In fact, I load a mesh from `.obj` that have texture embedded in it, the texture is loaded from a `.obj.mtl` file. Is there a way to remove the texture from the mesh, and save only the mesh (vertex+face), for example in `.off` format?

Thank you in advance!

**Comment by mikedh** [comment]
Hey, yeah if you just assign an empty `colorvisuals` object it'll export without texture. I may add a shortcut to this at some point but I'd give this a try:
```
In [1]: import trimesh

In [2]: m = trimesh.load('models/fuze.obj')

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(664, 3), faces.shape=(1000, 3))>

In [4]: m.visual
Out[4]: <trimesh.visual.texture.TextureVisuals at 0x7f84c484e908>

In [6]: m.visual = trimesh.visual.ColorVisuals()

In [7]: m.export('hi.obj')

```

**Comment by pvnieo** [comment]
Hi @mikedh 
Thanks for your response.

This solves this issue! Closing!
