### ISSUE TITLE
An exception is thrown if binvox is not in the PATH

### ISSUE THREAD

**Issue by amba86** [mikedh/trimesh#1026]
I think there is a bug in the `trimesh/exchange/binvox.py` file. If `binvox` executable is not in the path and the path is passed as a parameter, then an exception is thrown.
I think the [line](https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/binvox.py#L416) should have the following code:
```
if binvox_path is None:
  raise IOError(
    'No `binvox_path` provided, and no binvox executable found '
    'on PATH. \nPlease go to https://www.patrickmin.com/binvox/ and '
    'download the appropriate version.')
```
`binvox_encoder` is set in the [line](https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/binvox.py#L18) by a function that searches for the `binvox` executable in the `PATH` env that is not set!

**Comment by mikedh** [comment]
>  If binvox executable is not in the path and the path is passed as a parameter, then an exception is thrown.

Not totally sure what's going on here... would you be able to post a minimal reproducible example that raises the exception?

**Comment by amba86** [comment]
> Not totally sure what's going on here... would you be able to post a minimal reproducible example that raises the exception?

Here a minimal code snippet:
```
import trimesh.exchange.binvox as binvox

binvoxer = binvox.Binvoxer(32, binvox_path='/my/path/to/binvox/executable')
```

This code throws an exception. This happens because the binvox executable is not defined in the PATH variable, but given as function parameter.

**Comment by mikedh** [comment]
Ah yeah the logic in there does look a little gnarly. Hopefully https://github.com/mikedh/trimesh/pull/1015/commits/8d0ea3aa8edc541622dd8f6c751b433fd6e97ec5 bandaids this.

**Comment by amba86** [comment]
Thanks a lot for this! When is the next release planned?

**Comment by mikedh** [comment]
Should be released now!
