### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by aalavandhaann** [mikedh/trimesh#103]
Hello @mikedh ,

Thank you for this wonderful library. I just have a question. The trimesh library seems to use PyAssimp library. From my experience using Assimp library in the past (C++) had always resulted in problems. Because Assimp is more of a rendering framework than a modelling library. So if there is a requirement to keep the information of vertices indices, face indices, edge indices intact and same as the loaded file then Assimp kind of failed. This was my experience with Assimp C++. Does it behave the same way with the PyAssimp too?

Otherwise I really like your library to load and preview meshes quickly.

Regards,
#0K

**Comment by mikedh** [comment]
Haha thanks for the complements. I too have had decidedly mixed results with assimp- trimesh only uses it for importers, and its importers are only used if one hasn't been implemented in trimesh. Assimp [does support a lot of weird formats](http://www.assimp.org/main_features_formats.html) and it's nice to have access to them even if it is less reliable than one might hope.

Trimesh supports two bindings- pyassimp (which is the one included in assimp itself) and [cyassimp](https://anaconda.org/menpo/cyassimp) which is substantially faster.

**Comment by aalavandhaann** [comment]
@mikedh ,

Hey thanks for your quick response? I wish Github had a more integrated discussion. Would be useful to not creating issue tickets to just discuss. 

So can you let me know a few things? I am planning to use your library as the frontend of my research application. Would be happy to quote you in the acknowledgements of my paper. I currently use Blender.

1. Do these weird formats include **off** and **obj** ? My work mostly deals with these formats and cannot afford to lose the connectivity information 
2. Do you have access to the scene manager to include further interactivity? I mean if it is necessary to combine a 3d viewer with 2d form _GUIS_ **(pyqt, tkinter, wx etc.,)** will it be possible? Does *trimesh** allow itself to be embedded?
3. Also I saw a good amount of utility functions in your library. Do you think you might need some help with geodesic paths? I have a stable implementation of a state of the art geodesic library. Can perhaps offer to contribute in that area to make your library more standard. 

Regards,

#0K

**Comment by aalavandhaann** [comment]
@mikedh,

Just now read the point about docker and a container using trimesh. I guess my **2** point is related to that? Will look into it and then will ask around if there is something I dont understand. Sorry for having skipped that point in your wonderful README

Regards,

#0K
