### ISSUE TITLE
Way to calculate curvature as Trimesh2 in C++

### ISSUE THREAD

**Issue by JobAtom** [mikedh/trimesh#1032]
Is trimesh a python version of Trimesh2 in c++ or it just different with each other? I am wondering if trimesh can calculate curvature to get principal curvature direction, curvature with only one function need_curvature() in Trimesh2?

**Comment by mikedh** [comment]
Hey, `trimesh` is "it's own thing" and not related at all to `trimesh2`, but there's a few curvature functions you might take a look at: https://github.com/mikedh/trimesh/blob/master/trimesh/curvature.py
