### ISSUE TITLE
String conversion error during .obj export

### ISSUE THREAD

**Issue by pculbertson** [mikedh/trimesh#1033]
When calling `mesh.export("file_name.obj")`, `array_to_string` raises a `ValueError: ('dtype %s not convertible!', 'object')`.

I tried rolling `trimesh` back to `3.8.1`, since I saw #994 is a recent PR that changed `array_to_string`, but it did not resolve the issue.

**Comment by mikedh** [comment]
Hey, I think this may depend on the source mesh, could you send how you loaded or created the mesh? It works on some simple test data for me:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/featuretype.STL')

In [3]: _ = m.export('text.obj')
```

**Comment by pculbertson** [comment]
Great question! I'm loading the mesh w/ the `as_mesh` helper function given in #507, since the models I'm using (from the ShapeNet dataset) can contain multiple sub-meshes, which typically will load as a `trimesh.Scene`.

I'm guessing the `trimesh.util.concatenate` call in that function might be causing the export issue. Also, if I export everything as `.glb`, as you suggest in the README, it works fine.

Happy to upload a specific mesh if that would be helpful for debugging -- but this might be a non-issue due to the weird mesh loading, anyway.

**Comment by mikedh** [comment]
No worries, yeah if you can export the mesh and send me a snippet that reproduces the error on the export happy to take a look!

**Comment by pculbertson** [comment]
... now I can't reproduce it! Very weird. 

So sorry for wasting your time on this -- I think something weird is going on with that `as_mesh` function, and just using the `force` option or handling submeshes with `trimesh.Scene` is safer. I'll close the issue -- thanks for your help!

**Comment by mikedh** [comment]
No worries! I suspect one of the fields on the mesh got set to a weird datatype which killed the export.

**Comment by iamnotstone** [comment]
I met the same problem. here is my obj file:

```
# Blender v2.82 (sub 7) OBJ File: ''
# www.blender.org
mtllib box.mtl
o Cube
v 1.000000 1.000000 -1.000000
v 1.000000 -1.000000 -1.000000
v 1.000000 1.000000 1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 1.000000 -1.000000
v -1.000000 -1.000000 -1.000000
v -1.000000 1.000000 1.000000
v -1.000000 -1.000000 1.000000
vt 0.625000 0.500000
vt 0.875000 0.500000
vt 0.875000 0.750000
vt 0.625000 0.750000
vt 0.375000 0.750000
vt 0.625000 1.000000
vt 0.375000 1.000000
vt 0.375000 0.000000
vt 0.625000 0.000000
vt 0.625000 0.250000
vt 0.375000 0.250000
vt 0.125000 0.500000
vt 0.375000 0.500000
vt 0.125000 0.750000
vn 0.0000 1.0000 0.0000
vn 0.0000 0.0000 1.0000
vn -1.0000 0.0000 0.0000
vn 0.0000 -1.0000 0.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
usemtl Material
s off
f 1/1/1 5/2/1 7/3/1 3/4/1 
f 4/5/2 3/4/2 7/6/2 8/7/2 
f 8/8/3 7/9/3 5/10/3 6/11/3
f 6/12/4 2/13/4 4/5/4 8/14/4
f 2/13/5 1/1/5 3/4/5 4/5/5
f 6/11/6 5/10/6 1/1/6 2/13/6
```

and, here is how I call it:

```
>>> mesh = trimesh.load('./output/box.obj')
>>> mesh.export('./output/test.obj')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/base.py", line 2554, in export
    **kwargs)
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/exchange/export.py", line 78, in export_mesh
    export = _mesh_exporters[file_type](mesh, **kwargs)
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/exchange/obj.py", line 837, in export_obj
    digits=digits))
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/util.py", line 1151, in array_to_string
    array.dtype.name)
ValueError: ('dtype %s not convertible!', 'object')
```
