### ISSUE TITLE
Multidirectional slicer

### ISSUE THREAD

**Issue by timosmd** [mikedh/trimesh#1038]
Hello,

for an additive manufacturing related project, I need to develop a Slicer for multidirectional 3D-printing with a robot arm. As the robot arm has 6 degrees of freedom, there is no need for support structures. The coordinates of the slices should then be output in the robots program format.

Yesterday I found this repository and it looks very powerful and well implemented to me and might fit my needs. I managed to write some code to slice a test modell in z-direction by using the "section_multiplane"-method.

Now my next goal is, to implement a function to create slices of different parts of the 3d model in z OR y-direction. Based on the orientation of the specific feature.

![Bild_Testmodell](https://user-images.githubusercontent.com/56720702/96985273-f7797100-1520-11eb-82cc-169285f27ef0.PNG)

So the green features should be sliced in y-direction while the blue base should be sliced conventionally (z-direction).

I think a first step would be to create submeshes to get 3 (or 5) meshes for example: base, feature 1, feature 2

Therefore my question is: Is there already an algorithm implemented in trimesh I could somehow use for this purpose? Or generally, maybe any ideas on how to tackle this problem?

Any advice is highly appreciated.

Thanks in advance.

**Comment by mikedh** [comment]
Cool question! You might check out @nick-parker [bread](https://github.com/nick-parker/Bread) which does something similar.  One other good reference be Cura's implementation of adaptive layer heights: https://github.com/Ultimaker/Cura/pull/2868

Seems like the general idea might be: 
1) Generate an ordered series of nonplanar but curvature-constrained surfaces. The surfaces should probably have a minimum curvature radius, maximum distance from previous surface, etc. Maybe a NURBS surface with 4 control points?
2) Generate the on-surface cross section section, use a "parameterization" to move it onto a plane so you can fill it using normal polygon methods, then re-transform to curvey 3D surface.
3) Run curves in order.

**Comment by nick-parker** [comment]
Thanks for the tag Mike!

Bread isn't going to help much with this but I have a privately developed 3+2 axis slicer with support for subdividing meshes into differently oriented chunks quite nicely. It's what I use for praxismfg.com

Is this a commercial, academic, or personal project?

**Comment by mikedh** [comment]
Cool! Do you do carefully picked planar sections, or do you do the (crazy) NURBS thing I described above? Actually I wonder if doing a series of large radius sphere sections would work, which would at least make the intersections and constraints calculations easier!

**Comment by timosmd** [comment]
Thanks @mikedh for your quick response and tips! I will have a look at it next week and will most probably come back to you for further questions if that's okey.

@nick-parker That sounds interesting! Guess that's actually quite exactly what I am looking for.. The project I am working on is an academic one.

**Comment by nick-parker** [comment]
Carefully picked planar sections with some bells and whistles in the "3" axis steps to make the picking require less care. :)

@timosmd email me nick@praxismfg.com ? 

Also, are you aiming for strength improvements, surface finish, support-free printing, or what's the goal of your research?

I'm in the middle of some things right now but could plausibly offer you free access in a month or two under certain conditions.

**Comment by timosmd** [comment]
@nick-parker Our goal is to create a (for now rudimentary) slicer for a 6-Axis robot (+2 axes rotary table) to generate metal parts by using Wire Arc Additive Manufacturing (WAAM). As we do have 6 axes we would like to "print" without support - that's the reason for the multidirectional slicer :)

**Comment by mikedh** [comment]
Sounds good!

**Comment by medi05** [comment]
@timosmd Im really interrested in your project! Im working on a similar project for my Master Thesis. Maybe you have some advices for me. Im interested to know which library did you use for handling the geometries? Like extract subvolumes ( as to extract the green pipe form the blue one) Im having a hard time extracting subvolumes with round edges. And how did you manage to find the best build-direction for extracted subvolumes.
 Ill be glad if you could answer some of my questions :DDD
 Thanks
