### ISSUE TITLE
apply_translation does nothing

### ISSUE THREAD

**Issue by larrykvit** [mikedh/trimesh#104]
Hi,
I just found this library and was playing around with it. I noticed that `apply_translation` does not apply a translation, it seems to reset when `self._cache.clear` is called.
I ran this code:
`c2 = trimesh.primitives.Cylinder(sections=100)`
`print(c2.vertices[0])`
`c2.apply_translation([5, 5, 0])`
`print(c2.vertices[0])`

This prints:
> [ 0.  0. -5.]
> [ 0.  0. -5.]

If I manually add to the vertices, then it works. What is the problem here?

**Comment by vladkvit** [comment]
Try:

    c2.primitive.transform = trimesh.transformations.random_rotation_matrix()

**Comment by mikedh** [comment]
Yeah this was a result of Primitives being a subclass of Trimesh objects, albeit with immutable vertices that the default `apply_transform` was trying to change. If you add a a `trimesh.util.attach_to_log()` you'll see it complaining. 

Vlad is right, if you update the `c2.primitive.transform` it will do what you want. 

In https://github.com/mikedh/trimesh/commit/fdca5598a4eb2126dbeeaf59b596858a8c4b1b08 I added a hook to Primitives to update their stored transform which should fix `apply_translation`, `apply_transform`, and `apply_scale`.
