### ISSUE TITLE
Duplicate vertices in extrude_polygon to match face normals?

### ISSUE THREAD

**Issue by noamgat** [mikedh/trimesh#1042]
Hi,
I am using extrude_polygon to create a 3d shape from a 2d polygon. The geometry looks correct, however lighting is off when I export my generated geometry to GLB.
The reason for that, is that vertex normals are way off, and I am applying per-vertex lighting. By definition (of what extruded geometry is), the vertex normals are diagonal, while the face normals are straight - due to the 90 degree turns at the extrusion points.
In many 3d environments it is possible to duplicate vertices in order to have each vertex (and thus each vertex normal) only on one side of the extruded shape. Is there a way to do this with trimesh?

**Comment by mikedh** [comment]
If you export `mesh.smoothed` does it do the right thing? That should return a mesh with duplicated vertices so it looks OK rendered.

**Comment by noamgat** [comment]
Thanks, that looks exactly like what I was looking for!
