### ISSUE TITLE
broken save_image - trimesh 3.8.12 & pillow

### ISSUE THREAD

**Issue by chrysmun** [mikedh/trimesh#1044]
sometime since pillow 8.x the save_image function brokeas it fails with the following error message:

```
  File "/home/tmp/miniconda3/envs/tmp/lib/python3.7/site-packages/PIL/Image.py", line 62, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'fromstring'
```

since sometime between 3.7.12 and 3.8.12, the save_image function broke, 

it works in pure installed via conda install -c conda-forge trimesh networkx pyglet scipy (note, the extra 3 packages not installed automatically via conda are needed as well).

but as soon as conda install pillow 8.x is added, then the save_image breaks. with pillow=7.1.2 it still works.

```
# code to reproduce
# conda install -c conda-forge trimesh networkx pyglet scipy pillow

import trimesh  # 3.8.12

scene = trimesh.Scene()
scene.add_geometry(trimesh.creation.annulus(1, 2, 4))
png = scene.save_image(resolution=[1920, 1080])

with open("test.png", "wb") as f:
    f.write(png)
    f.close()
```

**Comment by mikedh** [comment]
Hey, yeah I've seen this too in pyglet, looks like they just merged a fix: https://github.com/pyglet/pyglet/pull/295

**Comment by mikedh** [comment]
Looks like pyglet released with the fix, closing for now although if this reappears with the latest version of pyglet feel free to re-open!
