### ISSUE TITLE
rtree not in dependencies?

### ISSUE THREAD

**Issue by amlucas** [mikedh/trimesh#1045]
Hello, I am trying to use this function:
https://trimsh.org/trimesh.proximity.html#trimesh.proximity.signed_distance

However I get the following error message:
```
  File "/usr/local/lib/python3.8/site-packages/trimesh/proximity.py", line 234, in signed_distance
    closest, distance, triangle_id = closest_point(mesh, points)
  File "/usr/local/lib/python3.8/site-packages/trimesh/proximity.py", line 140, in closest_point
    candidates = nearby_faces(mesh, points)
  File "/usr/local/lib/python3.8/site-packages/trimesh/proximity.py", line 45, in nearby_faces
    rtree = mesh.triangles_tree
  File "/usr/local/lib/python3.8/site-packages/trimesh/caching.py", line 100, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/trimesh/base.py", line 824, in triangles_tree
    tree = triangles.bounds_tree(self.triangles)
  File "/usr/local/lib/python3.8/site-packages/trimesh/triangles.py", line 344, in bounds_tree
    tree = util.bounds_tree(triangle_bounds)
  File "/usr/local/lib/python3.8/site-packages/trimesh/util.py", line 1777, in bounds_tree
    import rtree
ModuleNotFoundError: No module named 'rtree'
```
Should I install rtree manually?
Also, installing rtree via pip on my mac fails, not sure if that s the reason why it wasn t installed when installing trimesh.

Thank you!

**Comment by amlucas** [comment]
Sorry I did not read well enough the documentation, where you mention soft dependencies. I guess the problem is on the rtree side, which I can t install via pip on my system

**Comment by pengsongyou** [comment]
> Sorry I did not read well enough the documentation, where you mention soft dependencies. I guess the problem is on the rtree side, which I can t install via pip on my system

Hi @amlucas, I encountered the same problem, and I tried to install rtree by myself, but I also could not install it because of the error below. I am wondering how you solved the problem? Many thanks in advance!

>     ERROR: Command errored out with exit status 1:
>      command: /songyou/install/anaconda3/envs/imp_exp/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sreeqyro/rtree/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sreeqyro/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7_yszzlp
>          cwd: /tmp/pip-install-sreeqyro/rtree/
>     Complete output (15 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-sreeqyro/rtree/setup.py", line 3, in <module>
>         import rtree
>       File "/tmp/pip-install-sreeqyro/rtree/rtree/__init__.py", line 1, in <module>
>         from .index import Rtree
>       File "/tmp/pip-install-sreeqyro/rtree/rtree/index.py", line 6, in <module>
>         from . import core
>       File "/tmp/pip-install-sreeqyro/rtree/rtree/core.py", line 143, in <module>
>         rt.Error_GetLastErrorNum.restype = ctypes.c_int
>       File "/songyou/install/anaconda3/envs/imp_exp/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
>         func = self.__getitem__(name)
>       File "/songyou/install/anaconda3/envs/imp_exp/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
>         func = self._FuncPtr((name_or_ordinal, self))
>     AttributeError: /songyou/install/anaconda3/envs/imp_exp/bin/python3.8: undefined symbol: Error_GetLastErrorNum
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
