### ISSUE TITLE
Trimesh doesn't support loading obj quad meshes with texture coordinates

### ISSUE THREAD

**Issue by rggjan** [mikedh/trimesh#1046]
Due to the fact that here:
https://github.com/mikedh/trimesh/blob/d851c6a4583c920c9c9c9924dbbfd09ad83539d6/trimesh/exchange/obj.py#L379

for 8 column lines (which is the case for vertex + vertex texture index in quad meshes) `faces_tex` is set to `None` and not loaded...

**Comment by mikedh** [comment]
Happy to take PR's! If you do add one it would be great to also include a small model with quad texture for unit tests.

**Comment by nitinagarwal** [comment]
@mikedh Are there any plan to supporting quad meshes. This will be super helpful for the community I think.
