### ISSUE TITLE
Can't open dxf file on trimesh

### ISSUE THREAD

**Issue by nnss33** [mikedh/trimesh#1050]
When I use trimesh.exchange.load.mesh_formats() 
['dict', 'dict64', 'json', 'msgpack', 'stl', 'stl_ascii', 'ply', 'xaml', '3dxml', 'obj', 'off', 'glb', 'gltf', '3mf', 'xyz']
it doesn't include dxf format
why is this happening?

**Comment by mikedh** [comment]
Hey, what happens if you try to import it? `import trimesh.path.exchange.dxf`

**Comment by nnss33** [comment]
when i use this i get no result
```
import trimesh

file=open("solid.dxf")
mesh=trimesh.path.exchange.dxf.load_dxf(file)
```
How can I display the dxf or convert it to a mesh?

**Comment by nnss33** [comment]
When i use this i get no result
`import trimesh
file=open("solid.dxf")
trimesh.path.exchange.dxf.load_dxf(file)`

How can I display the dxf or convert it to a mesh?

**Comment by mikedh** [comment]
Oh, I misread your call. DXF is (mostly) a *path* format, not a mesh format. I'd use trimesh.load:

```
In [3]: import trimesh

In [4]: 'dxf' in trimesh.available_formats()
Out[4]: True

In [5]: trimesh.load('/home/mikedh/trimesh/models/2D/wrench.dxf')
Out[5]: <trimesh.Path2D(vertices.shape=(43, 2), len(entities)=39)>


```
