### ISSUE TITLE
How to store vertex colors in a mesh?

### ISSUE THREAD

**Issue by AZadora** [mikedh/trimesh#1052]
I would like to make a trimesh.Trimesh object from given list of vertices and list of faces. I also want to store color (or any other number) corresponding to each vertex (or face) in this mesh (like for point clouds). 

I would to have a labelled mesh with labels corresponding to each vertex or face.

How can I accomplish this? I tried to use 
`vertex_attributes `
but it seems to be not correct for this case (or maybe I am doing something wrong).

**Comment by mikedh** [comment]
Hey, if `colors` is a `(len(mesh.vertices), 4) uint8` you can just set them:

`mesh.visual.vertex_colors = colors`

Or for faces
`mesh.visual.face_colors = colors`

**Comment by AZadora** [comment]
Thank you!

> Hey, if `colors` is a `(len(mesh.vertices), 4) uint8` you can just set them:
> 
> `mesh.visual.vertex_colors = colors`
> 
> Or for faces
> `mesh.visual.face_colors = colors`

**Comment by kaimingkuang** [comment]
> Hey, if `colors` is a `(len(mesh.vertices), 4) uint8` you can just set them:
> 
> `mesh.visual.vertex_colors = colors`
> 
> Or for faces
> `mesh.visual.face_colors = colors`

Hi.
What is the fourth number in the color encoding? I played with the last number a little a found no difference no matter how I changed it:
```Python
face_colors_2 = np.array([[100, 100, 255, 255]] * mesh.faces.shape[0])
new_mesh_2 = trimesh.Trimesh(mesh.vertices, mesh.faces, face_colors=face_colors_2)
new_mesh_2.show()
```
or:
```Python
face_colors_1 = np.array([[100, 100, 255, 0]] * mesh.faces.shape[0])
face_colors_1[:, -1] = np.random.randint(0, 256, face_colors_1.shape[0])
new_mesh_1 = trimesh.Trimesh(mesh.vertices, mesh.faces, face_colors=face_colors_1)
new_mesh_1.show()
```
The visulization didn't change at all.
