### ISSUE TITLE
KHR_materials_unlit support in GLTF format?

### ISSUE THREAD

**Issue by noamgat** [mikedh/trimesh#1056]
The main README of this library goes to great lengths to recommend GLB as the go-to format for serialization, yet a common and not new extension of GLB - KHR_materials_unlit ( https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit ) which allows for unlit materials, is not supported.
I tried looking around gltf.py and couldn't find any mentions of it, nor could I find extendibility points (for example, to post process the gltf tree before serialization).
Has anyone done anything like this? Will it be added to trimesh?

**Comment by noamgat** [comment]
Created this:
https://github.com/mikedh/trimesh/pull/1065

**Comment by mikedh** [comment]
Should be released, thanks for the PR!
