### ISSUE TITLE
Obtain mesh boundary (rim and corner vertices)

### ISSUE THREAD

**Issue by ma-rv** [mikedh/trimesh#1060]
Hey, I have a mesh, which basically is a plane, and would like to obtain the vertices (x) of each corner (c) and the rim (r)...
```
crrrrrc
rxxxxxr
rxxxxxr
crrrrrc
```
... to create a mesh which only contains the boundary (iteratively obtain corners and rim to increase the size of the boundary).

How would you approach the problem? I thought it could be possible to find vertices at the corners and rim by checking the number of edges, though could not find a way to accomplish that yet. 

I am thankful for any advice & help!

**Comment by mikedh** [comment]
Hey, not sure *corner* is well defined but *rim* is basically any edge that appears only once. Check out `mesh.outline`, or a simple:

```
# an edge which occurs only once is on the boundary
unique_edges = grouping.group_rows(mesh.edges_sorted, require_count=1)
```
