### ISSUE TITLE
Resizing using Trimesh

### ISSUE THREAD

**Issue by somsubhro88** [mikedh/trimesh#1061]
Hello @mikedh . First of all, thank you for making Trimesh available for all of us to use. 

I had a question regarding the possibility of resizing a mesh. 

![image](https://user-images.githubusercontent.com/20040210/99666388-40164280-2a6b-11eb-84f0-7f688d8b3d8a.png)

An example (in the form of a 2D projection to make it easy to visualise) is shown above. I converted the STL into its 2D projection using the following command - 

`p = trimesh.path.polygons.projected(mesh, [0,0,1])`
`trimesh.load_path(p).show()`

What I would like to do is - resize the red mesh in such a way that the maximum vertical height and maximum horizontal length matches that of the black mesh. 

Why do I want to do this? - They are essentially the same thing, just that the black mesh is the real thing, whereas the red mesh is a scanned representation of the black mesh. I want to simply look at the "shaping" error due to the scanning process, rather than purely sizing errors. If both meshes have the same bounding lengths and depths, then all that remains is the (mis)representation of the curvature of the real (black) mesh.

Do you have a solution for this already in Trimesh? For the moment, even a solution that works on the 2D projection would work.

I look forward to hearing from you, or anyone else who may have a solution for this.

Thank you in advance!
Besh wishes,
Som

**Comment by mikedh** [comment]
Hey, I think what you probably want to do is find a homogeneous transformation with scale. Since you already have it nicely lined up in XY that could be as easy as: 

```
# get the XY scaling as a (2,) float
scale = candidate.extents / truth.extents

matrix = np.eye(4)
matrix[:2, :2] *= scale

mesh.apply_transform(matrix)
```

**Comment by somsubhro88** [comment]
Thank you, Michael @mikedh . This does work. I adjusted it so (as I had a 3D mesh)

```
candidate = trimesh.load_mesh('SOM/Notch_A_VAR/20201118_NOTCH_A_a4.8_2c44.16_13.STL')
truth = trimesh.load_mesh('SOM/Notch_A_VAR/20201118_NOTCH_A_a4_2c36.8_0.STL')

print(candidate.extents)
print(truth.extents)

scale = candidate.extents / truth.extents

matrix = np.eye(4)
matrix[:2, :2] /= scale[:2]

candidate.apply_transform(matrix)

print('\nafter operation\n')
print(candidate.extents)
print(truth.extents)
```
Results

```
[44.15999985  4.80000019  0.15000001]
[36.79999924  4.00000191  0.15000001]

after operation

[36.79999924  4.00000191  0.15000001]
[36.79999924  4.00000191  0.15000001]
```

One last question - you mentioned the transformation. Unfortunately, it is not clear to me how the transformation works. This happens to be a case where the meshes are perfectly aligned in the XY axis, but it won't always be the case. I would like to align them in the axis along which they have the largest dimension/extent (happens to be the X-axis in this case). Any hint on how to perform this would be very useful.

Thank you.
Best wishes,
Som

**Comment by somsubhro88** [comment]
As the primary issue is solved, I thought of closing this. If you have a response for my last question, that would be great.

Thank you for your support!!

**Comment by angeltemelko** [comment]
how can a 3d mesh scale it uniformly so that it tightly fits in a unit-sized cube?

**Comment by JulianKnodt** [comment]
For someone who randomly comes upon this thread and is asking how to transform and scale a 3D mesh into a unit [-1,1] cube:
```
  mesh = trimesh.load(mesh)
  rescale = max(mesh.extents)/2.
  tform = [
    -(mesh.bounds[1][i] + mesh.bounds[0][i])/2.
    for i in range(3)
  ]
  matrix = np.eye(4)
  matrix[:3, 3] = tform
  mesh.apply_transform(matrix)
  matrix = np.eye(4)
  matrix[:3, :3] /= rescale
  mesh.apply_transform(matrix)
```
