### ISSUE TITLE
process=True changes vertices order

### ISSUE THREAD

**Issue by pvnieo** [mikedh/trimesh#1069]
Hi,

Thanks for the great library.

I'm having a question about the process parameter in `trimesh.Trimesh`. When it is set to true, and `validate=False`, even if there is no duplicate vertices or NaNs, the order of the vertices is changed. Is this intentional?

Thank you in advance!

**Comment by mikedh** [comment]
No worries, are you loading an OBJ by chance? It's a little bit of a long story as to why it needs another kwarg, but you can pass `maintain_order` to the OBJ loader. If it's another format it really shouldn't be changing the order with just `process=False`. Snippet in OBJ loader: https://github.com/mikedh/trimesh/blob/ee075ebc9f083f125d6fcfe2ed99cf8b479ad1b1/trimesh/exchange/obj.py#L22-L28

Call with:
`trimesh.load(file_name, process=False, maintain_order=True)`

**Comment by pvnieo** [comment]
Hi @mikedh 
Thanks for the quick replay. I'm actually loading an `.off` for the disk using `trimesh.load("mesh.off")`.

Is this answer your question?

**Comment by pvnieo** [comment]
Hi @mikedh 

I tried with  `maintain_order=True`, but it's not working!

```python
>>> trimesh.load("000.off", process=True).faces[0]
TrackedArray([4615, 2076, 3458])
>>> trimesh.load("000.off", process=False).faces[0]
TrackedArray([15,  0,  1])
>>> trimesh.load("000.off", process=False, maintain_order=True).faces[0]
TrackedArray([15,  0,  1])
>>> trimesh.load("000.off", process=True, maintain_order=True).faces[0]
TrackedArray([4615, 2076, 3458])
```

**Comment by mikedh** [comment]
Hey, `maintain_order` is only for the OBJ loader... it looks like the order in that file is being maintained by the OFF loader:

```
import trimesh
import os
import numpy as np

if __name__ == '__main__':
    trimesh.util.attach_to_log()

    file_name = os.path.expanduser('~/downloads/000.off')
    m = trimesh.load(file_name, process=False)

    with open(file_name) as f:
        lines = [line.split('#', 1)[0].strip() for line in str.splitlines(f.read())]
    lines = [line.split() for line in lines if
             'OFF' not in line and len(line) > 0]

    vc, fc, _ = np.array(lines[0], dtype=np.int64)

    assert len(m.faces) == fc
    assert len(m.vertices) == vc

    assert np.allclose(m.vertices, np.array(lines[1:vc + 1], dtype=np.float64))

    faces = np.array(lines[vc + 1:], dtype=np.int64)[:, 1:]
    assert np.allclose(m.faces, faces)
```

**Comment by pvnieo** [comment]
Hi @mikedh 
Yes, this answer the last question!

However, what confused me in my case is that, when process=True, validate=False, and there is no NaNs or duplicate,  the vertices still change order (see example above), and I want to know if this intentional?

Thank you in advance!

**Comment by mikedh** [comment]
Hey, in the example above `np.allclose` is saying that every value in order of the raw file is *identical* to the loaded result in `m.vertices` and `m.faces`. In general if `process=False` the order should be preserved.

**Comment by mikedh** [comment]
Oh I didn't read the issue title. Yeah if `process=True` it will change vertex order :smile:
