### ISSUE TITLE
'Compressed' obj format loaded wrong

### ISSUE THREAD

**Issue by dvicini** [mikedh/trimesh#107]
Hi,
It seems that Trimesh does not parse OBJ files correctly if they are in the 'compressed' format. Compressed in this case means that vertices along hard edges are not duplicated. An example of this i the OBJ file representing a cube:

```
o Cube
v 1.000000 -1.000000 -1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 -1.000000 1.000000
v -1.000000 -1.000000 -1.000000
v 1.000000 1.000000 -0.999999
v 0.999999 1.000000 1.000001
v -1.000000 1.000000 1.000000
v -1.000000 1.000000 -1.000000
vn 0.0000 -1.0000 0.0000
vn 0.0000 1.0000 0.0000
vn 1.0000 -0.0000 0.0000
vn 0.0000 -0.0000 1.0000
vn -1.0000 -0.0000 -0.0000
vn 0.0000 0.0000 -1.0000
s off
f 2//1 4//1 1//1
f 8//2 6//2 5//2
f 5//3 2//3 1//3
f 6//4 3//4 2//4
f 3//5 8//5 4//5
f 1//6 8//6 5//6
f 2//1 3//1 4//1
f 8//2 7//2 6//2
f 5//3 6//3 2//3
f 6//4 7//4 3//4
f 3//5 7//5 8//5
f 1//6 4//6 8//6
```
If I load this file using Trimesh, the loaded mesh does not have the correct normals from the file. Instead, it recomputes vertex normals as average face normals, which is not what we want here. For reference, the loaded 'vertex_normals' then are:
```
[[-0.40824829 -0.81649658 -0.40824829]
 [-0.66666672 -0.33333344  0.66666656]
 [-0.57735012  0.57735041 -0.57735027]
 [-0.57735046  0.57735017  0.57735017]
 [ 0.40824849 -0.40824809 -0.81649658]
 [ 0.66666663 -0.66666663  0.33333348]
 [ 0.81649658  0.4082486  -0.40824798]
 [ 0.33333315  0.66666663  0.6666668 ]]
```
The problem seems to be that the OBJ format allows a vertex position to be used with different normals in different faces. To replicate this correctly inside Trimesh, Trimesh should probably just duplicate these vertices when loading such a file.

Thanks
Delio

**Comment by mikedh** [comment]
Hey, I think this should be fixed by Pyry's PR which was just merged, if you load OBJ files without processing:
`mesh = trimesh.load(file_name, process=False)`

Thanks for the report!
