### ISSUE TITLE
Is that possible to put a trimesh window into PyQt?

### ISSUE THREAD

**Issue by Nexround** [mikedh/trimesh#1077]
I have a project that i'm thinking about how to show model in a QT application.
I found that there is a QPygletWidget class and this can contain pyglet in QT,but i didnt found way to use trimesh in QT.So are there any way to make it work?

**Comment by mikedh** [comment]
Hey not sure about `qt`, but [the widget.py example](https://github.com/mikedh/trimesh/blob/master/examples/widget.py) might be along the lines of this (which uses [glooey](https://github.com/kxgames/glooey))

**Comment by mikedh** [comment]
You can also copy the `trimesh.viewer.windowed` code into `QPygletWidget` which should probably work OK, or use `trimesh.rendering` to create the arguments for the pygelt IndexedVertexList constructor.

**Comment by MasterixSoftware** [comment]
Hi MediosZ, I am working with PyQt and I also need to display a mesh in QtApplication using Trimesh. Can you explain to me how you did it please? Thank you very much.

**Comment by Ponti23** [comment]
Hi guys, did you ever found a solution for this? Any help would be nice.
