### ISSUE TITLE
Showed scene cannot be closed appropriately

### ISSUE THREAD

**Issue by RolandZhu** [mikedh/trimesh#1078]
Hello, Trimesh is a fascinating library for mesh operations! Thanks for your work.

I'm now using Trimesh to view a scene with multiple objects. After initiating the scene instance and adding geometries, I view the scene with the `show()` function. However, I cannot close the pyglet window appropriately. The code seems to stuck inside `show()` and is not executing the following code. Any idea what argument should I add or how can I close the window?

**Comment by mikedh** [comment]
Hey, yeah the `scene.show()` call is blocking as it then enters the `pyglet` event loop. When you close the window the rest of the code should execute. You'd have to implement a non-blocking viewer (or maybe update/fix the Ipython one to live-update using something like [meshcat](https://github.com/rdeits/meshcat) :smile:
