### ISSUE TITLE
Mesh loading should not delete duplicate vertices

### ISSUE THREAD

**Issue by dvicini** [mikedh/trimesh#108]
Hi,
It seems that when the mesh is loaded, duplicate vertices are automatically removed. I know that this can be disabled by setting 'process=False'. I would argue that this should be the default and the geometry loading should not delete any vertices. If some operations require the mesh to be 'processed', they can still check if this is the case and require the user to call the Trimesh.process function.

It is very counterintuitive to suddenly have fewer vertices after loading the mesh. Also note that duplicate vertices play an important role in allowing the mesh to have hard edges, even if shading normals are computed automatically.

Delio

**Comment by mikedh** [comment]
Hey Delio, this behavior is mostly a reflection of the fact that my use case is primarily dealing with watertight volumes, and trimesh is designed around that.

So if you want to avoid trimesh trying to do any magic to work easily on watertight meshes, you'd load the mesh as you say like:
`In [1]: m = trimesh.load('cube_compressed.obj', process=False, validate_faces=False)`

There are two camps on this (the "don't touch the input until I ask you", and the "try to make it work as a watertight volume magically") and it seems like no matter what one of those two camps has to pass some boolean flags or add a bunch of boilerplate to their code. 

I agree trimesh should definitely _support_ not altering the input until asked, but I'm not convinced that should be the default behavior.

**Comment by dvicini** [comment]
Hey,
Okay, I didn't know that this is your primary use case. In that case the behavior makes perfect sense. Nevertheless, maybe it would be worth adding a note to the documentation? I had to dig through the code quite a bit to find it (also since the load_mesh function just takes kwarg arguments, and therefore some of this behavior is quite hidden)

Feel free to close this issue :)

Delio

**Comment by mikedh** [comment]
No worries, and thanks for understanding! If you have suggestions or PR's to make the graphics use case easier they'd be very welcome. Yeah, I'll add a line to the readme header about the focus on watertight volumes.

Best,
Mike
