### ISSUE TITLE
Loading COLLADA models

### ISSUE THREAD

**Issue by wanweiwei07** [mikedh/trimesh#1083]
HI Mike,
I used trimesh to load the dae models (base.dae) provided by the URROS package:
https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_e_description/meshes/ur3e/visual
https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_description/meshes/ur3/visual

I compared the local axis with those loaded in Meshlab.
For the UR3E series, the model is rotating 90 around x axis.
For the UR3 series, the model is correct.
Is this a bug? I went through the code and did not find any problem though

Thank you.

**Comment by wanweiwei07** [comment]
I found the problem. The UR3E (base.dae) file has a transformation matrix, which scaled down and rotated the model. But I did not manage to fix it in the code. Right now I am doing [:[1,2]]=[:,[2,1]] [1]=-[1] , saving it, and reloading it.

**Comment by mikedh** [comment]
Just looking at it quickly yeah it looks like the meshes for `ur3e/base.dae` appear to be in mm, but the scene transform does the scaling to meters. `scene.dump` or `mesh.load(file_name, force='mesh')` might be useful to bake the transform in. After doing that it looked like the file matched meshlab (Z-up/X-right)?

```
In [20]: s = trimesh.load('ur3e.dae')

In [21]: s.geometry['eSeries_UR3e_014-mesh.0'].bounds
Out[21]: 
array([[-63.98854065,   0.        , -63.98579025],
       [ 64.00959015,  85.14537811,  63.99380875]])

In [22]: s.bounds
Out[22]: 
array([[-6.39877732e-02, -6.39930135e-02, -2.36467039e-08],
       [ 6.40087947e-02,  6.39849989e-02,  9.49487801e-02]])

In [23]: m = s.dump(concatenate=True)

In [24]: m.bounds
Out[24]: 
array([[-6.39877087e-02, -6.39929777e-02, -2.10509914e-08],
       [ 6.40087582e-02,  6.39849580e-02,  9.49487781e-02]])

In [26]: m = trimesh.load('ur3e.dae', force='mesh')
In [27]: m
Out[27]: <trimesh.Trimesh(vertices.shape=(8627, 3), faces.shape=(3306, 3))>

In [28]: m.show()
Out[28]: SceneViewer(width=1800, height=1350)

In [29]: m.bounds
Out[29]: 
array([[-6.39877087e-02, -6.39929777e-02, -2.10509914e-08],
       [ 6.40087582e-02,  6.39849580e-02,  9.49487781e-02]])

```

**Comment by wanweiwei07** [comment]
Thank you very much!
