### ISSUE TITLE
Loading Ngon

### ISSUE THREAD

**Issue by JohnG0024** [mikedh/trimesh#1085]
Hi, I'm using trimesh==2.37.20, looks like there's a problem when loading mesh with Ngons. If it has been fixed, could someone point me to the commit please?

**Comment by mikedh** [comment]
Hey, do you have a reproducible example and source file? In general arbitrary polygons are only intermittently supported;  the OBJ loader tries to tessellate them as a triangle fan, but I don't think any of the other loaders try.

**Comment by JohnG0024** [comment]
Try this. https://drive.google.com/drive/folders/19dbar3SiTJTzcTFNXDoGjm2DNm9uxr5J?usp=sharing
I load it with 
`mesh_list = trimesh.load_mesh('su33_joined.obj', process=False)`
and it gets error:
`ValueError: cannot reshape array of size 499979 into shape (3)`
It has no problem loading after I fix those Ngons myself.

**Comment by mikedh** [comment]
Oh `2.37.20` is pretty old... on the latest version that model seems to work:
```
In [1]: import trimesh

In [2]: trimesh.__version__
Out[2]: '3.8.19'

In [3]: m = trimesh.load_mesh('su33_joined.obj', process=False)
unable to load materials from: su33_joined.mtl
specified material (wheel)  not loaded!

In [4]: m
Out[4]: <trimesh.Scene(len(geometry)=24)>

In [5]: m.show()
Out[5]: SceneViewer(width=1800, height=1350)

```

**Comment by JohnG0024** [comment]
Yes that's what I thought. Do you maybe still remember the commit(s) that fixed this problem? I'd like to manually update the code to fix this without an update. (There's a project I'm testing that uses this old version, but I can't get them work if I update to latest Trimesh...)

**Comment by mikedh** [comment]
Ah not sure which commit it was, probably a series of them. You can check the diffs of version-tagged releases: https://github.com/mikedh/trimesh/tags?after=2.37.28

**Comment by JohnG0024** [comment]
Thanks, that helps. I narrowed it down to version 2.38.42-3.5.22, but the comparison is still quite big that only 250 commits are displayed. Do you know the script that has this import function?

**Comment by mikedh** [comment]
Yeah you might just try copying over the `trimesh/exchange/obj.py` file from `master`. and see if it works (there might be some other stuff that needs to be copied as well). What's the dependency issue just out of curiosity? Might be easier to solve that vs backporting.

**Comment by JohnG0024** [comment]
You're right, the dependency issues (over tensorflow/opencv/etc) is easier to solve... Thanks for your support.

**Comment by mikedh** [comment]
No problem!
