### ISSUE TITLE
used as indices must be of ProximityQuery.on_surface fails with "IndexError: arrays integer (or boolean) type" when closest vertex has degree 0

### ISSUE THREAD

**Issue by TimSchneider42** [mikedh/trimesh#1089]
Hey,

when the `process` option of trimesh.load is set to False (which I needed to do as the order of the vertices play a role in my application), vertices with degree 0 are not removed from the mesh. If such a mesh is then used in a ProximityQuery and the closest vertex to one of the queried points has degree 0, it fails with
```
IndexError: arrays used as indices must be of integer (or boolean) type
```
which is not a very meaningful error message. 

The reason this happens is because `nearby_faces` returns an empty list of faces for the respective point and `numpy.concatenate`, which is called on this list, creates an array of type float instead of int if one of the input arrays is empty.

Here is a minimal example that shows the behavior:
```python
from trimesh import Trimesh
from trimesh.proximity import ProximityQuery

query_point = [-1.0, -1.0, -1.0]
mesh = Trimesh(vertices=[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [-0.5, -0.5, -0.5]], faces=[[0, 1, 2]],
               process=False)

proximity_query = ProximityQuery(mesh)
proximity_query.on_surface([query_point])
```
I think there are two ways of tackling this issue: one could either ensure that the kdtree in `nearest_faces` is constructed using only points with a degree greater than zero or one could simply throw a meaningful error if the mesh contains vertices with degree zero.

Best,
Tim

**Comment by mikedh** [comment]
Thanks for the report! Should be fixed by #1087 which constructs the KDTree only on referenced vertices, and I added your example to unit tests.
