### ISSUE TITLE
Hashing fails after using repair.fix_face_winding

### ISSUE THREAD

**Issue by Binaryhalibut** [mikedh/trimesh#109]
`repair.fix_face_winding` makes use of `np.fliplr()`, which causes the array to become not C-contiguous in memory. This means that when the `DataStore.md5()` function is called, the call to `TrackedArray.md5()` fails on the `faces` array because `hashlib` requires the array to be C-contiguous.

Proposed fix: do exactly the same thing as in `TrackedArray.crc()`: change [this line](https://github.com/mikedh/trimesh/blob/master/trimesh/util.py#L658) to

```
            if self.flags['C_CONTIGUOUS']:
                self._hashed_md5 = md5_object(self)
            else:
                # the case where we have sliced our nice
                # contiguous array into a non- contiguous block
                # for example (note slice *after* track operation):
                # t = util.tracked_array(np.random.random(10))[::-1]
                contiguous = np.ascontiguousarray(self)
                self._hashed_md5 = md5_object(contiguous)
```

**Comment by mikedh** [comment]
Good catch! Your suggestion and a test added in https://github.com/mikedh/trimesh/commit/1a7c850ffba885ce266b2cba548c6aca91d910be

Thanks for the report!
