### ISSUE TITLE
trimesh.exchange.load.load_mesh closes passed in file objects

### ISSUE THREAD

**Issue by cc-a** [mikedh/trimesh#1091]
https://github.com/mikedh/trimesh/blob/f5ac70d1e289e262946bc908ca78053b33ad19c9/trimesh/exchange/load.py#L211-L212

In all other instances `opened` is evaluated to determine whether the file should be closed. For consistency I believe this should be:

```
        if util.is_file(file_obj) and opened:
            file_obj.close()
```

**Comment by mikedh** [comment]
Thanks for the report! Agreed, that `if util.is_file` block should just be removed as the `finally` block which will always execute is using the correct logic (`if opened`).
