### ISSUE TITLE
How to use Trimesh Lighting

### ISSUE THREAD

**Issue by jsaisagar** [mikedh/trimesh#1098]
Hi,

When I am using Trimesh lighting I am getting the following error when using scene.show()
"networkx.exception.NodeNotFound: Either source world or target light_CWD9N5 is not in G"

Please find the code below.
    scene.camera_transform = np.eye(4) # Place camera at origin
    scene.lights = trimesh.scene.lighting.autolight(scene)[0]
    print(scene.lights)

    scene.show()

May I know how to solve this?

Thanks,
Sai

**Comment by avani17101** [comment]
I am facing the same issue, @mikedh can you point if it's possible to trimesh lighting without going through py render?
