### ISSUE TITLE
[Question] decompose identifier_md5 into translation and rotation

### ISSUE THREAD

**Issue by FreakTheMighty** [mikedh/trimesh#1099]
I'm not entirely sure how to ask this question :), but here it goes. `identifier_md5` seems like a really powerful way to identify meshes that are the same even when a transform has been applied to to to the underlying data. Is there a way to extract the translation and rotation that would have been used to make the identifier invariant?

The end goal for me relates to caching expensive operations, on meshes that are effectively the same, but have been had different transformed applied to their underlying mesh data (not transforms assigned to to them in a scene graph).

**Comment by mikedh** [comment]
Hey, yeah it works surprisingly well haha. I'd also check out `mesh.identifier` which is the original float-vector form (the MD5 has hand-tuned significant figures before hashing). 

That identifier explicitly tries to remove rotation and translation, you'd have to store separate information about original rotation-translation not included in that hash. I'd look at `mesh.center_mass` and `mesh.principal_inertia_vectors` which are a little more easy to reason with than a straight transformation matrix, i.e. in a cylinder one of those vectors will be along the axis.

**Comment by FreakTheMighty** [comment]
Thank you, that's very helpful.
