### ISSUE TITLE
Calculate inner line length (Find intersection between 3d mesh and 3d line)

### ISSUE THREAD

**Issue by Sea421** [mikedh/trimesh#1113]
Hi team,

It is not a bug, I am asking for help. I am trying to find inner line length of mesh. To calculate this, I am trying to find intersecting points between 3d line and mesh.
I am using trimesh contains method. My line has starting and ending point. So, when I use contains method in original points it returns false. So I divide line as multiple small lines.
Here is my code:

``` python
import trimesh
import numpy as np


def divide_line(p0, p1, dt=0.1):
    points = np.ndarray((0, 3))
    points = np.vstack((points, p0))
    x0, y0, z0 = p0[0], p0[1], p0[2]
    x1, y1, z1 = p1[0], p1[1], p1[2]
    d = np.linalg.norm(p1 - p0)
    i = 0
    while d > dt:
        t = dt / d
        xt = (1 - t) * x0 + t * x1
        yt = (1 - t) * y0 + t * y1
        zt = (1 - t) * z0 + t * z1
        d = np.linalg.norm(np.array([x1, y1, z1]) - np.array([x0, y0, z0]))
        x0, y0, z0 = xt, yt, zt
        points = np.vstack((points, [x0, y0, z0]))
        i = i + 1
    points = np.vstack((points, p1))
    return points


def calc_length(mesh, points):
    # calculate inner line length
    contains = mesh.contains(points)
    inner_points = points[contains]
    line_length = np.linalg.norm(inner_points[0] - inner_points[-1])

    return line_length

mesh = trimesh.load_mesh('test.stl')

p0 = np.asarray([-10, 20, -10])
p1 = np.asarray([10, 30, 0])

# divide line by multiple lines
line_points1 = divide_line(p0, p1, dt=0.1)
line_points2 = divide_line(p0, p1, dt=0.01)

line_length1 = calc_length(mesh, line_points1)
line_length2 = calc_length(mesh, line_points2)


print(f"inner line length 1: {line_length1}\t2: {line_length2}")
```

Output:
`inner line length 1: 11.400360341609527	2: 11.459868995328245`

But it is depending on **dt** value. How to find real intersecting points?

Thanks,
Sea

![mesh](https://user-images.githubusercontent.com/55222313/103616051-af39ee80-4f66-11eb-87f9-338e4779f164.PNG)

**Comment by mikedh** [comment]
Hey, I think you may want to use `mesh.ray.intersects_location` rather than contains tests, which you can then get that length with just a dot product with the ray.
