### ISSUE TITLE
Best Camera distance

### ISSUE THREAD

**Issue by pvnieo** [mikedh/trimesh#1121]
Hi,

Thanks for the great library.

Is there a recommended way to determine the best camera distance so that the hole object appears in the frame? My use case is that I want to save some meshes as images to disk, and I want to do this automatically. Because my shapes have different shapes and sizes, choosing one distance for all meshes will be sometimes either too close or too far.

Thank you in advance!

**Comment by mikedh** [comment]
Hey, yeah you might take a look at `trimesh.scene.cameras.look_at`:
```

def look_at(points, fov, rotation=None, distance=None, center=None, pad=None):
    """
    Generate transform for a camera to keep a list
    of points in the camera's field of view.

    Examples
    ------------
    ```python
    points = np.array([0, 0, 0], [1, 1, 1])
    scene.camera_transform = scene.camera.look_at(points)
    ```

    Parameters
    -------------
    points : (n, 3) float
      Points in space
    fov : (2,) float
      Field of view, in DEGREES
    rotation : None, or (4, 4) float
      Rotation matrix for initial rotation
    distance : None or float
      Distance from camera to center
    center : None, or (3,) float
      Center of field of view.

    Returns
    --------------
    transform : (4, 4) float
      Transformation matrix from world to camera
    """
```
