### ISSUE TITLE
Calculating the distance between the mesh triangles and convex hull

### ISSUE THREAD

**Issue by reevesj191** [mikedh/trimesh#1123]
Hello, I am have been trying to use the nearest.on_surface function to calculate the distance between the triangles of an irregularly shaped mesh and its convex hull using the following code.

mesh = trimesh.load("irregularly_shaped_mesh")
hull = mesh.convex_hull

(closest_points, distance, triangle_ids) = mesh.nearest.on_surface(hull.vertices)

However, when I do this it only returns values of 0 for the distance. Am I using the wrong function to carry out this task?

Thank you in advance. I am new to analyzing 3D models in python.

**Comment by reevesj191** [comment]
I knew as soon as I wrote this comment that I would come to a solution. I am closing this thread.

**Comment by anikimmel** [comment]
Hi! What was your solution?
