### ISSUE TITLE
Function keyword arguments documentation error

### ISSUE THREAD

**Issue by luca-nardelli** [mikedh/trimesh#1128]
I believe that the keyword arguments `use_norm` and `use_tex` in merge_vertices are wrongly documented.
https://github.com/mikedh/trimesh/blob/90af69803958bdffee55a7fa3f43bdadfac95415/trimesh/base.py#L1105

If you look at the definition for grouping.merge_vertices (https://github.com/mikedh/trimesh/blob/90af69803958bdffee55a7fa3f43bdadfac95415/trimesh/grouping.py#L23) the actual keyword arguments are merge_norm and merge_tex (and their meaning is opposite of use_norm and use_tex).

**Comment by mikedh** [comment]
Thanks for the report!
