### ISSUE TITLE
No FCL available

### ISSUE THREAD

**Issue by Running-Chen** [mikedh/trimesh#1133]
Hello, I have successfully install trimesh,pcl-python library, however, when I load an object, I try to initialize trimesh.collision.CollisionManager()，it cause “No FCL available” error! My codes as follows:

**Comment by Running-Chen** [comment]
> Hello, I have successfully install trimesh,pcl-python library, however, when I load an object, I try to initialize trimesh.collision.CollisionManager()，it cause “No FCL available” error! My codes as follows:

**Code**
import trimesh
obj = trimesh.load('cup.obj')
collision_manager = trimesh.collision.CollisionManager()

**ERROR**
File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\collision.py", line 161, in __init__
    raise ValueError('No FCL Available!')

**Comment by pgunn** [comment]
I just managed to make this work.

If you install the python-fcl library, that can solve the problem. Right now it's a bit rough of an install (the current python-fcl depends on an older version of the underlying fcl library). I went with a version from a pull request that aims to fix the incompatibility:

https://github.com/DmitryNeverov/python-fcl

It was still a bit rough though. Give it a try! (Easier on Linux)

**Comment by mikedh** [comment]
Yeah, looks like `fcl` isn't installed correctly.

**Comment by marios-stam** [comment]
Hello I tried what @pgunn  suggested but I get this error : 
>>> import fcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marios/.local/lib/python3.8/site-packages/fcl/__init__.py", line 1, in <module>
    from .fcl import CollisionObject, CollisionGeometry, Transform, TriangleP, Box, Sphere, Ellipsoid, Capsule, Cone, Cylinder, Halfspace, Plane, BVHModel, OcTree, DynamicAABBTreeCollisionManager, collide, continuousCollide, distance, defaultCollisionCallback, defaultDistanceCallback
ImportError: /home/marios/.local/lib/python3.8/site-packages/fcl/fcl.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3fcl10BVSplitterINS_6OBBRSSEE5applyERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE

Any suggestions?

**Comment by SGeswar** [comment]
If you are using a Mac M1 or M2 versions try creating a new environment using miniconda and set the environment variable into intel config 
 - To install and run the fcl library in M1 and M2 chips:
      - Install Miniconda 
        - You can install miniconda through the link --> https://docs.conda.io/en/main/miniconda.html
          - Or by running command in terminal --> brew install --cask miniconda
            - Either way is fine as long as bash file is configured.
              - Your bash file should look like this 
                - # >>> conda initialize >>>
                  # !! Contents within this block are managed by 'conda init' !!
                  __conda_setup="$('/Users/<root directory>/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null$
                  if [ $? -eq 0 ]; then
                  eval "$__conda_setup"
                  else
                  if [ -f "/Users/<root directory>/miniconda3/etc/profile.d/conda.sh" ]; then
                    . "/Users/<root directory>/miniconda3/etc/profile.d/conda.sh"
                  else
                    export PATH="/Users/<root directory>/miniconda3/bin:$PATH"
                 fi
                  fi
                  unset __conda_setup
                # <<< conda initialize <<<
  
      - After installing Miniconda open the terminal and run --> conda create -n my_x86_env -y
      - That command creates a conda virtual environment
      - Now run --> conda activate my_x86_env
      - Now virtual environment is created and running. But we need to configure the virtual environment to OSX-64
      - So run --> conda config --env --set subdir osx-64
      - Now install python using conda command --> conda install python=3.10
      - Now  try installing python-fcl library.

**Comment by mikedh** [comment]
Hey, since this issue was posted [wheels were set up using cibuildhweel](https://pypi.org/project/python-fcl/0.7.0.5/#files) for [berkeleyautomation/python-fcl](https://github.com/BerkeleyAutomation/python-fcl) and the best way to install if your platform (python 3.6+ win/mac/linux) is: `pip install python-fcl`. 

It does look like it build arm64 wheels too but I haven't tested them.
