### ISSUE TITLE
Defining inlet and outlets of STL model 

### ISSUE THREAD

**Issue by aboukhedr** [mikedh/trimesh#1138]
Hello Michael, 

I'm trying to create inlet and outlet patches using python for an STL model seen below 
![image](https://user-images.githubusercontent.com/10777800/106780470-f12a8300-663f-11eb-948d-cedc5659c505.png)

Is it possible to use TriMesh to define the inlet patch automatically? 
MA

**Comment by mikedh** [comment]
Hey, I guess it depends a lot on how exactly you can define of "inlet," at least in that example it looks like you might be able to look at connected components thresholded by the angle of adjacent faces:

```
In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [4]: import numpy as np

In [5]: trimesh.graph.connected_component_labels(m.face_adjacency[m.face_adjacency_angles < np.radians(1.0)])
Out[5]: array([0, 1, 0, 2, 3, 1, 3, 4, 2, 4, 5, 5], dtype=int32)

```
