### ISSUE TITLE
save rendered image to memory

### ISSUE THREAD

**Issue by weikaichenusc** [mikedh/trimesh#114]
Hi!
How to save the rendered image to memory (e.g. in the format of numpy array) so that I can display the content in the other visualizer?
Thanks!

**Comment by mikedh** [comment]
Hey, assuming your talking about the `scene.save_image` function, I'd probably use NamedTemporaryFiles for this (the save_image being filenames only is a pyglet restriction). You can then put the PNG into PIL and do whatever you'd like with it:

```
In [1]: import trimesh

In [2]: import tempfile

In [3]: mesh = trimesh.primitives.Sphere()

In [4]: scene = mesh.scene()

In [5]: with tempfile.NamedTemporaryFile(suffix='.png') as file_obj:
   ...:     scene.save_image(file_obj.name, resolution=(1080,1080))
   ...:     file_obj.seek(0)
   ...:     data = file_obj.read()
   ...:     

In [6]: len(data)
Out[6]: 135509

In [7]: from PIL import Image

In [8]: Image.open?
Signature: Image.open(fp, mode='r')
Docstring:
Opens and identifies the given image file.

This is a lazy operation; this function identifies the file, but
the file remains open and the actual image data is not read from
the file until you try to process the data (or call the
:py:meth:`~PIL.Image.Image.load` method).  See
:py:func:`~PIL.Image.new`.

:param fp: A filename (string), pathlib.Path object or a file object.
   The file object must implement :py:meth:`~file.read`,
   :py:meth:`~file.seek`, and :py:meth:`~file.tell` methods,
   and be opened in binary mode.
:param mode: The mode.  If given, this argument must be "r".
:returns: An :py:class:`~PIL.Image.Image` object.
:exception IOError: If the file cannot be found, or the image cannot be
   opened and identified.
File:      ~/miniconda/lib/python3.6/site-packages/PIL/Image.py
Type:      function

In [9]: rendered = Image.open(trimesh.util.wrap_as_stream(data))

In [10]: rendered.show()

```

**Comment by weikaichenusc** [comment]
thank you! I think it helps!

**Comment by mikedh** [comment]
Cool, I'll close this one and track the save_image issue in the other open one.

**Comment by ChrisWu1997** [comment]
@mikedh It seems like the API `scene.save_image` has been changed.  How can I save the rendered image to memory now?

```python
>>> with tempfile.NamedTemporaryFile(suffix='.png') as file_obj:
...     scene.save_image(file_obj.name, resolution=(1080,1080))
...     file_obj.seek(0)
...     data = file_obj.read()
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: save_image() got multiple values for argument 'resolution'
```

**Comment by mikedh** [comment]
Hey, it by default returns the PNG image now, so you can get rid of the tempfile block and replace it with one line:
 `data = scene.save_image(resolution=(1080,1080))`

The docstring for save image:
```
Signature: s.save_image(resolution=(1024, 768), **kwargs)
Docstring:
Get a PNG image of a scene.

Parameters
-----------
resolution: (2,) int, resolution to render image
**kwargs:  passed to SceneViewer constructor

Returns
-----------
png: bytes, render of scene in PNG form

```

**Comment by ChrisWu1997** [comment]
I see, thanks. Actually my problem is how to save the rendered image on a remote server, where the graphics interface is not accessible. Now if I use `save_image`, I will get this error:
```
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```
It seems like display is needed in order to save rendered image. Is there any way that I can directly save image without the need for display/graphics interface?

**Comment by mikedh** [comment]
Hey, yeah to render you need an OpenGL context, which is what does the actual rendering. 

This is not that easy to configure headless. But the way I do it is to run inside the `trimesh` docker containers, and then add the rendering script as a `supervisord` task. Then `supervisord` will run your program as well as [xvfb configured with LLVMpipe software rasterization](https://github.com/mikedh/trimesh/blob/master/docker/config/xvfb.supervisord.conf). 

`myprogram.supervisor.conf`:
```
[supervisord]
nodaemon=true ;

[program:myprog_worker]
command=/home/user/conda/bin/python -u /home/user/myprog.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=user
environment=HOME="/home/user",USER="user"
```

In your `Dockerfile`:
```
FROM mikedh/trimesh

#### COPY YOUR STUFF HERE

# eat less output
ENV PYTHONUNBUFFERED=0

COPY myprogram.supervisor.conf /etc/supervisor/conf.d/
# run our worker scripts and xvfb using supervisord
# we've copied all our configs into /etc/supervisor/conf.d/
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
```

**Comment by ChrisWu1997** [comment]
Thanks a lot! I'll try this way.

**Comment by Zhangsihao-Yang** [comment]
> Thanks a lot! I'll try this way.

Have you solved your problem?
