### ISSUE TITLE
[contribution] dockerRender for Windows

### ISSUE THREAD

**Issue by Hafplo** [mikedh/trimesh#1140]
I made a few changes to "run.bash" in dockerRender in order to adjust it for windows users:

```
@echo on

# in this directory build the image with a tag
docker build . -t renderworker

# run the container we just built
# the -v will mount the current directory
# as /output inside the container
docker run -v %cd%:/output renderworker

```

also renamed to "run.bat"

might be trivial, but took me some time to figure it out.

* I tried to add new branch as well as a new pull request but was denied. @mikedh

**Comment by mikedh** [comment]
Looks good and it would be great to have that run on Windows! A PR would be great, you just have to fork the repo first and then PR from your fork.
