### ISSUE TITLE
Merging 3D polygons projected on a plane

### ISSUE THREAD

**Issue by deekshadesai** [mikedh/trimesh#1142]
I am working on a project that requires me to find the regression planes of the triangles of a trimesh object. After that, I have to project these triangles on the respective regression planes and then merge the projected triangles.
I could easily project the triangles but I cannot find an efficient and simple way to merge the projected triangles.

What I thought might work is creating a trimesh object of the triangles belonging to a plane and then finding the convex hull.
This does not seem to work though. 

I am now looking for ways to solve this problem! 

Thanks! :-)

**Comment by mikedh** [comment]
Hey, the convex hull of a plane in 3D has no volume, and so qhull will almost certainly be erroring. I think you want the *outline* of the triangles? Which you can do a bunch of ways, the easiest of which is probably `mesh.outline`:

```
In [3]: m = trimesh.creation.box()

In [4]: m
Out[4]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [5]: m.facets
Out[5]: 
[array([0, 2]),
 array([1, 5]),
 array([3, 8]),
 array([4, 6]),
 array([7, 9]),
 array([10, 11])]

In [6]: m.outline?
Signature: m.outline(face_ids=None, **kwargs)
Docstring:
Given a list of face indexes find the outline of those
faces and return it as a Path3D.

The outline is defined here as every edge which is only
included by a single triangle.

Note that this implies a non-watertight mesh as the
outline of a watertight mesh is an empty path.

Parameters
------------
face_ids : (n, ) int
  Indices to compute the outline of.
  If None, outline of full mesh will be computed.
**kwargs: passed to Path3D constructor

Returns
----------
path : Path3D
  Curve in 3D of the outline
File:      ~/Dropbox/robotics/trimesh/trimesh/base.py
Type:      method

In [7]: m.outline([0, 2])
Out[7]: <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>
```

**Comment by deekshadesai** [comment]
Yes, this is exactly what I needed. Thank you for a prompt reply!
