### ISSUE TITLE
'Scene' object has no attribute 'has camera'

### ISSUE THREAD

**Issue by SteveScott** [mikedh/trimesh#1143]
I am attempting to create a GBL from scene from an STL.

I create the scene thusly:
```  
my_scene = trimesh.scene.scene.Scene(geometry=mesh, camera=None)
my_scene.add_geometry(mesh)
```
I am calling export here:
```    glb = trimesh.exchange.gltf.export_glb(scene)  ```

I get the following error:
```
Traceback (most recent call last):
  File "d:/Dropbox/1programming2/special_snowflake_backend/special_snowflake_asset_pipeline/scripts/glb_main.py", line 13, in <module>   
    stl_to_glb(filename)
  File "d:\Dropbox\1programming2\special_snowflake_backend\special_snowflake_asset_pipeline\scripts\export_glb.py", line 26, in stl_to_glb
    glb = trimesh.exchange.gltf.export_glb(scene)
  File "C:\Users\steve\.conda\envs\special_snowflake_3_8\lib\site-packages\trimesh\exchange\gltf.py", line 163, in export_glb
    tree, buffer_items = _create_gltf_structure(
  File "C:\Users\steve\.conda\envs\special_snowflake_3_8\lib\site-packages\trimesh\exchange\gltf.py", line 451, in _create_gltf_structure
    if scene.has_camera:
AttributeError: 'Scene' object has no attribute 'has_camera'
(special_snowflake_3_8) PS D:\Dropbox\1programming2\special_snowflake_backend>  ```

Scene has no attribute "has_camera"?

**Comment by mikedh** [comment]
Hey, I'm not able to reproduce this, are you on the latest version? Does the same code but with a box run for you:

```
    mesh = trimesh.creation.box()

    s = trimesh.scene.scene.Scene(geometry=mesh, camera=None)
    #s.add_geometry(mesh)                                       

    glb = trimesh.exchange.gltf.export_glb(s)

```

**Comment by SteveScott** [comment]
Funny, I am not able to reproduce it either. Sorry for the trouble, it seems to be working now. 

Maybe you can clarify something:
``` glb = trimesh.exchange.gltf.export_glb(my_scene) ```
that converts my_scene into a GLB in memory? How do I export the scene to the disk? Right now I am doing ``` mesh.export(<file_path>) ``` but that will only export the mesh, not the scene? My goal is to add a material, which would not be contained in a mesh but the scene?

**Comment by mikedh** [comment]
No worries! I think you may want `trimesh.Scene(mesh).export(file_obj=file_path)` or something similar?
