### ISSUE TITLE
Find correspondending triangles and Transformation matrix

### ISSUE THREAD

**Issue by Herzdame** [mikedh/trimesh#1144]
Hello,

First of all I want to thank you for your amazing work. You are awesome. 
I would like to know if it is possible to compare two meshes and find correspondending triangles between this two and then to calculate the transformation matrix of every triangle to his correspondending triangle in the second Mesh. How could this be possible? The two meshes are minimal different from each other.

**Comment by mikedh** [comment]
Thanks! I think `trimesh.registration.mesh_other` is probably what you want, although sometimes performance can be a bit iffy as the signed distance calculations are slow.
