### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy'

### ISSUE THREAD

**Issue by hawkaa** [mikedh/trimesh#1145]
Hi,

The auto mechanism for choosing graph backend doesn't seem to work.

---

Trimesh version: 3.9.3
Python version: 3.8 and 3.9 (both tested)

Code:
```python
import trimesh

mesh = trimesh.load("apt.obj", force="mesh")
mesh.split()
```

Output:

```sh
ModuleNotFoundError: No module named 'scipy'
```

It is supposed to fall back to `networkx`, but it doesn't happen.[ It seems to use `NameError`  in the fallback mechanism](https://github.com/mikedh/trimesh/blob/master/trimesh/graph.py#L451), while the actual error thrown is `ModuleNotFoundError`. It could be that this behaviour is different across python versions, but I don't know.

Thanks!
Håkon

**Comment by hawkaa** [comment]
Thank you @mikedh !

**Comment by mikedh** [comment]
Thanks for the report! Yeah using anything other than `BaseException` for checking module imports seems kinda unreliable.
