### ISSUE TITLE
`slice_plane` does not create watertight mesh when cap=True

### ISSUE THREAD

**Issue by ShuonanChen** [mikedh/trimesh#1149]
Hi, 

I am working with [this mesh file](https://drive.google.com/file/d/1nw7fr2avt603c3TL_u3Utauqleg68ojf/view?usp=sharing), which itself is watertight.
Aim: Trying to slice it to get only the part Z<5000, and create a watertight `newmesh`.
Problem: `newmesh` created from `slice_plane` with `cap=True` is NOT watertight.

The entire code is below. I thought cap=True is to enforce the new mesh to be watertight. 

```
fn= './'
mesh = trimesh.load_mesh(fn)

plane_origin = [0,0,5000]
plane_normal = [0,0,-1]

print(mesh.is_watertight)  # True
newmesh=mesh.slice_plane(plane_origin = plane_origin,
                         plane_normal = plane_normal,
                         cap=True)
print(newmesh.is_watertight) # False
```

What am I doing wrong? Any suggestions? Thanks!

**Comment by mikedh** [comment]
Ah looks like it wasn't anything easy.. looks like there is an overlapping triangle in the result:
```
import trimesh

if __name__ == '__main__':
    
    fn= '~/downloads/mesh.stl'
    mesh = trimesh.load_mesh(fn)

   # will do expensive checks to make sure the mesh isn't inserting new vertices
    trimesh.constants.tol.strict = True
    
    # this mesh was huge... scaling to a unit box makes things sensitive to numeric issues more reliable
    scale = mesh.scale
    mesh.apply_scale(1/scale)

    plane_origin = [0,0,5000/scale]
    plane_normal = [0,0,-1]
    
    print(mesh.is_watertight)  # True
    newmesh=mesh.slice_plane(plane_origin = plane_origin,
                             plane_normal = plane_normal,
    cap=True)
    print(newmesh.is_watertight) # False


    trimesh.repair.broken_faces(newmesh, color=[255,0,0,255])
    newmesh.show(smooth=False)
    
```
![cap](https://user-images.githubusercontent.com/1403074/107961110-746aa380-6f73-11eb-9e10-b614cabd628e.png)

![cap2](https://user-images.githubusercontent.com/1403074/107961124-77659400-6f73-11eb-9e1e-a4f288ec2082.png)

If you're interested in debugging (PR's welcome!) I would recommend embedding at the end of `trimesh.intersections.slice_plane` and then poking around:
```
from IPython import embed
embed()
```
