### ISSUE TITLE
scene.save_image() doesn't work

### ISSUE THREAD

**Issue by weikaichenusc** [mikedh/trimesh#115]
Hi! 
I just tried the example in https://github.com/mikedh/trimesh/blob/master/examples/offscreen_render.py.
However, I cannot get the correct saved image. The saved image is just plain black.
BTW, the mesh viewer can display the mesh correctly, but the rotation doesn't work (the camera view is never rotated).

Could you help resolve the save_image() issue? Thanks!

**Comment by mikedh** [comment]
Hmm, what platform are you on?

I'd try forcing a visible opengl window by changing the save_image line to `scene.save_image(file_name, visible=True)`

Not sure why rotation isn't working for you- if you want to link me to the mesh I can take a look. Also might be worth making sure you have the latest version of trimesh and its dependencies with a `pip install -U trimesh[easy]`

**Comment by weikaichenusc** [comment]
I'm using Ubuntu 16.04. 
I just tried `pip install -U trimesh[easy]` and then run `scene.save_image(file_name, visible=True)`. Then I got error:

TypeError: __init__() got an unexpected keword argument 'visible"

**Comment by mikedh** [comment]
Ah, I forgot that wasn't a kwarg for SceneViewers- if [this build](https://travis-ci.org/mikedh/trimesh/builds/316186972) succeeds try the `pip -U trimesh` again and see if overriding visible works.

**Comment by weikaichenusc** [comment]
I just tried another mesh, the rotation works! But the save_image() is still not working.
BTW, how to check out the build you are referring to?

**Comment by weikaichenusc** [comment]
It works now! Thanks a lot!:-)

**Comment by weikaichenusc** [comment]
Another issue is if I try to save it to the memory using the NamedTemporaryFile as you suggested in #114 , rendered.show() still gives me a plain black image...

**Comment by weikaichenusc** [comment]
Hi Michael! 
Could you help resolve the issue of saving the rendered image into memory? As mentioned above, the rendered.show() only displays a plain black image even I added the argument `visiable=True` for the save_image() function. Thanks a lot!

**Comment by mikedh** [comment]
Hmm, could you send me the mesh this is happening on? If `scene.show` is showing a black screen `scene.save_image` will do the same, as it's just grabbing the output of the window. 

Some things that might be happening:
- something with your opengl/xserver
- the automatic camera transform is wrong/too close and burying the camera inside the mesh

Best,
Mike

**Comment by weikaichenusc** [comment]
`
import tempfile
mesh = trimesh.primitives.Sphere()
scene = mesh.scene()
with tempfile.NamedTemporaryFile(suffix='.png') as file_obj:
	scene.save_image(file_obj.name, resolution=(480,480), visible=True)
	file_obj.seek(0)
	data = file_obj.read()

scene.show()
from PIL import Image
rendered = Image.open(trimesh.util.wrap_as_stream(data))
rendered.show()
`
This is the code I tried, which is basically copying your suggestion. scene.show() can display the sphere nicely, but rendered.show() can just display a black screen...

**Comment by mikedh** [comment]
Hmm, with the minor updates in https://github.com/mikedh/trimesh/commit/05dbbc490f28b97d98f0207df767bf03d601dfe5 this works on both my Windows machine and my Ubuntu 16.04 machine. Have you done a `pip -U pyglet` lately?

```
    import tempfile
    mesh = trimesh.primitives.Sphere()
    scene = mesh.scene()
    with tempfile.TemporaryFile() as file_obj:
        scene.save_image(file_obj, visible=True, resolution=(480,480))
        file_obj.seek(0)
        data = file_obj.read()
    scene.show()
    from PIL import Image
    rendered = Image.open(trimesh.util.wrap_as_stream(data))
    rendered.show()
```

**Comment by weikaichenusc** [comment]
I just tried to update pyglet, it is already updated. And I check out the updated trimesh and your minorly changed code, scene.show() works well but the rendered.show() still displays the black screen... It is really weird ...

**Comment by weikaichenusc** [comment]
I have run the same code on another Ubuntu 16.04 machine and the same issue happens again: scene.show() works well but rendered.show() displays the black screen. I wonder if rendered.show() works well on your side?

**Comment by mikedh** [comment]
Yeah, the rendered.show() works correctly on my Ubuntu 14.04, Ubuntu 16.04, and windows 10 machines.

You might try playing around with this version of viewer which overrides the pyglet event loop:
https://gist.github.com/mikedh/efdb9b3ba11a34fc3cf770a6d318ee20

**Comment by weikaichenusc** [comment]
Thanks, Mike! I have tried the headless.py.
Now the renderer.show() no longer displays the black screen. But the saved image is different from scene.show(). renderer.show() gives me flat shading while scene.show() uses smooth shading. How to get rendered.show() to have the consistent rendered image with scene.show()?

**Comment by mikedh** [comment]
Oh it's interesting that works. Probably something to do with graphics configurations and number of executions of the event loop then. I just pushed a change to manual event loop for the scene.save_image call, so this should work:

```
    mesh = trimesh.primitives.Sphere()
    scene = mesh.scene()

    data = scene.save_image()
    # if this doesn't work, try it with a visible window:
    # data = scene.save_image(visible=True)


    from PIL import Image
    rendered = Image.open(trimesh.util.wrap_as_stream(data))
```

Does the image render correctly without a visible window on your machine?

**Comment by weikaichenusc** [comment]
oh, it finally works!! thank you so much!!

**Comment by mikedh** [comment]
Great! No problem.

**Comment by DHarshil32** [comment]
Hello @mikedh, can you tell me how I can convert the bytes returned by scene.save_image() to opencv format (RGB) ?

**Comment by mikedh** [comment]
Hey, looks like this stackoverflow post has a good explanation: https://stackoverflow.com/questions/14134892/convert-image-from-pil-to-opencv-format

**Comment by DHarshil32** [comment]
Tried these code but throws a blank image
I'm using
python =3.5
opencv = 4.0.0
trimesh = 2.36.13
```
rendered = Image.open(BytesIO(scene.save_image(resolution=(640,480),visible=True))).convert('RGB')
open_cv_image = np.array(rendered)
open_cv_image = open_cv_image[:, :, ::-1].copy()
cv2.imshow('Image',open_cv_image)
cv2.waitKey(0)
```

**Comment by DHarshil32** [comment]
Hello Mike, Installed Trimesh 2.37.27 to solve the isssue. Issue with save_image() is resolved! Can you let me know how I can get 4X4 transformations of mesh in the geometery with respect to camera?

In the version 2.36.13, I was using scene.graph.get('camera','object')[0] to achieve the same

**Comment by mikedh** [comment]
Hey, I think you want to do basically the same thing, it's just that now the node is `scene.camera.name`:
```
In [1]: import trimesh

In [2]: s = trimesh.load('models/Duck.glb')

In [3]: s
Out[3]: <trimesh.scene.scene.Scene at 0x7f3b56093940>

In [5]: s.camera
Out[5]: <trimesh.scene.cameras.Camera at 0x7f3b55f85fd0>

In [6]: s.geometry
Out[6]: OrderedDict([('LOD3spShape', <trimesh.base.Trimesh at 0x7f3b56093ba8>)])

In [7]: s.graph.nodes
Out[7]: 
array(['world', '0', '1', '2', 'LOD3spShape_0HEQMG', 'camera_YHIAIP'],
      dtype='<U18')

In [8]: s.camera.name
Out[8]: 'camera_YHIAIP'

In [9]: s.graph.nodes_geometry
Out[9]: array(['LOD3spShape_0HEQMG'], dtype='<U18')

In [10]: {node: s.graph.get(s.camera.name, node)[0] for node in s.graph.nodes_geometry}
Out[10]: 
{'LOD3spShape_0HEQMG': array([[100.00000224,   0.        ,   0.        ,  13.44070053],
        [  0.        , 100.00000224,   0.        ,  86.94968557],
        [  0.        ,   0.        , 100.00000224, 239.86868821],
        [  0.        ,   0.        ,   0.        ,   1.        ]])}

```

**Comment by nicolasugrinovic** [comment]
@mikedh thank you for the great work. I have tried the same example `offscreen_render.py` and I am interested in doing a headless rendering so I can render and save an image without a window poping-up and interrupting what I am doing. I thought that by setting the  parameter `visible` of `scene.save_image() ` to `False` would do the trick, however the saved image is all black. 

How can I do this headless render?
