### ISSUE TITLE
[GLTF] Reuse mesh buffer items

### ISSUE THREAD

**Issue by FreakTheMighty** [mikedh/trimesh#1151]
Multiple copies of the mesh data are included when with the same mesh is added to the scene multiple times. I would be nice to identify that the mesh data is already present and avoid adding it again. This will allow us to have smaller files and in some cases speed up write times.

Bellow is a simple example of a scene where we should try to have a single buffer item.

```python
from trimesh import Scene
from trimesh.creation import box
from trimesh.transformations import translation_matrix
import trimesh

scene = Scene()
box_1 = box()
box_2 = box()
print(trimesh)

scene.add_geometry(box_1, 'box_1', transform=translation_matrix((1, 1, 1)))
scene.add_geometry(box_2, 'box_2', transform=translation_matrix((-1, -1, -1)))

scene.export('boxes2.glb')
```

---

I may have a chance to tackle this myself, but wanted to capture this task here incase there were any upfront objections to adding this.

**Comment by mikedh** [comment]
Yeah sounds great! My only thought is it's probably only safe to de-duplicate multiple instances of exactly the same object (i.e. using id(mesh) or `mesh.crc`)?

```
scene = Scene()
box_1 = box()

scene.add_geometry(box_1, 'box_1', transform=translation_matrix((1, 1, 1)))
scene.add_geometry(box_1, 'box_2', transform=translation_matrix((-1, -1, -1)))

scene.export('boxes2.glb')
```

**Comment by FreakTheMighty** [comment]
@mikedh, good point, I was thinking about this but was hoping we could be more general than that. If we only support literal instances how might we support buffers that are the same, but reference other materials? In gltf this should be possible, but in Trimesh wouldn't we need a new box instance to make box 2 green, for example?

Perhaps we *can* use the md5 hash, but only share buffer items some properties:
* vertex
* face
* vertex_normals
* vertex_attributes?

At minimum we could re-use the buffer and accessort for vertex/face [here](https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/gltf.py#L569-L592)

**Comment by mikedh** [comment]
Yeah agreed, I think the safest way to do it would be to "hash late", maybe replace all the `buffer_items.append` calls with a new function that returns an index, and replace `buffer_items` with a `collections.OrderedDict`? There's also a lot of places that rely on `len(buffer_items)` to get the index, which would have to be replaced with the output of the append function: 

```
def _buffer_append(buffer_items, data):
    """                                                                                             
    Append data to an existing dict.                                                                
                                                                                                    
    Parameters                                                                                      
    ----------                                                                                      
    buffer_items : collections.OrderedDict                                                          
      Keyed like { hash : data }                                                                    
    data : bytes                                                                                    
      To be stored                                                                                  
                                                                                                    
    Returns                                                                                         
    ----------                                                                                      
    index : int                                                                                     
      Index of buffer_items stored in                                                               
    """
    # native python hashing is pretty fast
    hashed = hash(data)
    if hashed in buffer_items:
	# todo : better way of finding index in an OrderedDict?                                     
        return list(buffer_items.keys()).index(hashed)
    # not in buffer items so append and then return index
    buffer_items[hashed] = data
    return len(buffer_items) - 1
```

Just playing around briefly this *did* de-duplicate the buffers for the "two boxes one of which is green" problem.  There sure are a lot of index references to fix haha.

**Comment by FreakTheMighty** [comment]
I did a really quick pass, but it feels a little messy. You are right, all those index references make my head spin.

Let me think about your suggestion. I like that its centralizes the index generation. I'd like to de-dupe the accessors as well, but I think I could extend your function to do so.

**Comment by mikedh** [comment]
Hmm, what about the existing `merge_buffers` option? IE `scene.export(file_type='gltf', merge_buffers=True)`. It seems like it does pretty much this, maybe it should be selected by default?

```
# merge_buffers=False
len(acc): 7 len(buff): 7
# merge_buffers=True
len(acc): 7 len(buff): 1

```

**Comment by mikedh** [comment]
Ah nevermind that just combines them into one big buffer. Dedupe branch here with the hashing strategy works for meshes: https://github.com/mikedh/trimesh/tree/gltf/dedupe
