### ISSUE TITLE
Export scene to GLB?

### ISSUE THREAD

**Issue by SteveScott** [mikedh/trimesh#1154]
How do I export a scene to a GLB file?
when I look up ```scene.export(file_obj=glb_path, file_type='None')```
It says I must specify a file type "ie 'dict', 'dict64', 'stl". None of those are the formats I am looking for. Also, when I execute that command, nothing saves at all.

There is also this method:

```trimesh.exchange.gltf.export_glb(scene, extras=None, include_normals=None, tree_postprocessor=None)```
Which converts the scene into a GLB in memory. Great, but how do I write this to disk? 
Do I need to pass these bytes to another library?

**Comment by mikedh** [comment]
Hey, I think you just want `scene.export(file_obj=glb_path)` and then have it infer the export type from the file name.

**Comment by SteveScott** [comment]
@mikedh When I do this it throws an error that says file_type cannot be None, and it forces me to select something like stl. Specifically ```ValueError: file_type not specified!```
I actually solved the problem by using python to write the bytes from export_glb 
```
 f = open(glb_path, "wb")
    f.write(glb)
    f.close()
```

**Comment by mikedh** [comment]
Hmm that's odd, it shouldn't need the file type at all if the path has the correct extension:

```
mikedh@luna:tst$ ipython -i
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ls

In [2]: import trimesh

In [3]: m = trimesh.creation.box()

In [4]: m
Out[4]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [5]: _ = m.export(file_obj='from_mesh.glb')

In [6]: ls
from_mesh.glb

In [7]: s = trimesh.Scene([m])

In [8]: s
Out[8]: <trimesh.Scene(len(geometry)=1)>

In [9]: _ = s.export(file_obj='from_scene.glb')

In [10]: ls -altrsh
total 16K
4.0K drwxr-xr-x 32 mikedh mikedh 4.0K Feb 16 10:02 ../
4.0K -rw-rw-r--  1 mikedh mikedh  924 Feb 16 10:09 from_mesh.glb
4.0K -rw-rw-r--  1 mikedh mikedh  924 Feb 16 10:09 from_scene.glb
4.0K drwxrwxr-x  2 mikedh mikedh 4.0K Feb 16 10:09 ./

In [11]: _ = s.export(file_obj='from_scene', file_type='glb')

In [12]: ls -altrsh
total 20K
4.0K drwxr-xr-x 32 mikedh mikedh 4.0K Feb 16 10:02 ../
4.0K -rw-rw-r--  1 mikedh mikedh  924 Feb 16 10:09 from_mesh.glb
4.0K -rw-rw-r--  1 mikedh mikedh  924 Feb 16 10:09 from_scene.glb
4.0K -rw-rw-r--  1 mikedh mikedh 1.2K Feb 16 10:10 from_scene
4.0K drwxrwxr-x  2 mikedh mikedh 4.0K Feb 16 10:10 ./


```

**Comment by SteveScott** [comment]
I think I found the problem. I was passing in a Path value instead of a string. I am on Windows so the path uses backslashes instead of forward slashes. I added cast the path as a unix path using ```  glb_path = glb_path.as_posix() ``` and it worked for me. Thanks for your help, Mike!
