### ISSUE TITLE
Trimesh.to_dict() not working as it should

### ISSUE THREAD

**Issue by PaulDebus** [mikedh/trimesh#116]
Hey,

I was working with trimeshes and converting them back and forth. I was using the `to_dict()` function for this like in the example:

```
a = Trimesh(**other_mesh.to_dict())
```

An error occurs in this, as the constructor tries to use the passed in lists as numpy arrays. What worked for me was the following:
```
d = old_mesh.to_dict()
d['vertices'] = np.array(d['vertices'])
d['vertex_colors'] = np.array(d['vertex_colors'])
new_mesh = Trimesh(**d)
```

Regards!

**Comment by mikedh** [comment]
Ah, looks like the vertex_color setter wasn't wrapping input with a numpy.asanyarray, hopefully fixed in https://github.com/mikedh/trimesh/commit/55a808aed3ec7a598c59d04be03384c9d759c140

Thanks for the report!

**Comment by PaulDebus** [comment]
Hey,

the new version fixed it.

Thanks!
