### ISSUE TITLE
Setting face colors misses a face

### ISSUE THREAD

**Issue by KNejad** [mikedh/trimesh#1163]
I ran the example code (block 10 in https://trimsh.org/examples/quick_start.html) to set the colors of a mesh, yet the results I get aren't what I expect:

```
import numpy as np
import trimesh

box = trimesh.creation.box()

for facet in box.facets:
    box.visual.face_colors[facet] = [0, 255, 0, 255]
print(box.visual.face_colors)
```

I would expect the below to print:

```
[[  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]]
```

However, for some reason index 1 and 5 have the colors set to 102:

```
[[  0 255   0 255]
 [102 102 102 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [102 102 102 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]
 [  0 255   0 255]]
```

Interestingly, if I adjust the code to read the value, without doing anything to it after each loop iteration I get the correct values. So by changing the loop to this:

```
for facet in box.facets:
    box.visual.face_colors[facet] = [0, 255, 0, 255]
    box.visual.face_colors[facet]
```

Finally, I get the same issue (except only 1 is wrong) when I iterate over the faces instead of facets:

```
for i in range(len(mesh.visual.face_colors)):
    mesh.visual.face_colors[i] = [0, 255, 0, 255]
```

P.S. If there is a better way to set all faces to the same color please let me know because I couldn't get any other way to work from reading the docs

P.P.S Trimesh is amazing and thanks for all your work :)

**Comment by mikedh** [comment]
Hey, if you just want to set all the faces to the same color, it's probably easier to use `box.visual.face_colors = [0, 255, 0, 255]`. There is also a caching issue that this iterating through exposes, I'll push a fix shortly.

**Comment by KNejad** [comment]
@mikedh oh that worked, thanks! Much easier :)
