### ISSUE TITLE
How export subtrees in GLTF hierarchy as seperate Scenes?

### ISSUE THREAD

**Issue by Skylion007** [mikedh/trimesh#1165]
I want to export various objects in a GLTF as their own GLTFs. How can I export the GLB of these subtrees based off the GLTF hierarchies? I figured out how to get the subnodes of a node using trimesh, but exporting it is proving difficult.

I want to export the entire transform tree under a specific node. In this case, I want to export the subtree under the node of "Structure" and also export all the subtrees that are children of "Objects" under separate GLBs. However, I am having trouble constructing a new scene using these subgraphs (as shown below). I figured out how to get the subtrees using a combination of the networkx successors and subgraph functions, but I can't figure out how to prune the existing scene's subgraph or alternatively to make a new Forest from the subgraph. I tried the latter approach below, but when I look at the nodes in the new scene graph, I found it to be empty. 
 
```python
    scene = trimesh.load(...)
    transforms_tree = scene.graph.transforms
    root_children = transforms_tree[scene.graph.base_frame].keys()
    print(list(root_children))
    structure = transforms_tree['Structure']
    for node in transforms_tree.successors('Structure'):
        print(node)
    objects = scene.graph.transforms['Objects']
    print(scene.graph.to_edgelist())
    for scene_object in objects:
        sub_nodes = set(transforms_tree.successors(scene_object))
        graph = trimesh.scene.transforms.TransformForest(scene_object)
        graph.transforms = transforms_tree.subgraph(sub_nodes)
        new_graph = trimesh.scene.transforms.TransformForest(scene_object)
        new_graph.from_edgelist(graph.to_edgelist())
        object_scene = trimesh.Scene(graph=new_graph, geometry=scene.geometry, base_frame=scene_object)
        object_scene.show() # It crashes here
```
Is there an easier way to export subtrees of GLTF hierarchy from Trimesh?

**Comment by mikedh** [comment]
Hmm yeah the scene graphs aren't all that graceful, that being said I'd probably filter the edge list rather than subgraph by nodes, this works OK:

```
import trimesh
if __name__ == '__main__':
    s =	trimesh.load('models/CesiumMilkTruck.glb')

    node = '3'
    nodes = set(s.graph.transforms.successors('3'))
    nodes.add(node)

    edges = [e for e in s.graph.to_edgelist()
             if e[0] in nodes or e[1] in nodes]

    g =	trimesh.scene.transforms.TransformForest(base_frame=node)
    g.from_edgelist(edges)

    n =	trimesh.Scene(geometry=s.geometry, graph=g)

```

**Comment by Skylion007** [comment]
@mikedh So one annoying issue with this code is that the created scene isn't valid due to the detached geometry. Is there an easy utility somewhere to pruned the unused geometry from the newly created scenes?

**Comment by mikedh** [comment]
Oh it's probably easiest to prune before creating the new scene. We could probably add this as `scene.get_subscene` or something and add tests if it'd be helpful:

```
    s = trimesh.load('models/CesiumMilkTruck.glb')


    node = '3'
    nodes = set(s.graph.transforms.successors(node))
    nodes.add(node)

    edges = [e for e in s.graph.to_edgelist()
             if e[0] in nodes or e[1] in nodes]

    g = trimesh.scene.transforms.TransformForest(base_frame=node)
    g.from_edgelist(edges)

    geometry_names = set(
        [e[2]['geometry'] for e in edges if 'geometry' in e[2]])
    geometry = {k: s.geometry[k] for k in geometry_names}

    n = trimesh.Scene(geometry=geometry, graph=g)

```

**Comment by Skylion007** [comment]
Thanks, this code was super helpful.
