### ISSUE TITLE
Add a single vertex and triangulate

### ISSUE THREAD

**Issue by robclouth** [mikedh/trimesh#1169]
I need to add a single vertex to a mesh and then retriangulate to make the mesh proper again. What's the easiest way to do this? I'm trying to make two boundaries have the same vertex count so they can be stitched together.
Thanks!

**Comment by mikedh** [comment]
Hey, I'm definitely not an expert on this, but it seems like there's a few cases, two of which are pretty easy haha: 

- point on existing face
  - remove that face (by storing mask for `update_faces`), and replace with three new faces 
- point on existing edge
  - split each adjacent triangle into two (`mesh.face_adjacency_edges` is probably useful here)
- point on existing vertex
  - no-op
- point not on surface
  - not well defined?

![remesh](https://user-images.githubusercontent.com/1403074/113512826-734a0180-9534-11eb-88a2-1d3e6c7006df.png)
