### ISSUE TITLE
Overlap or intersection between two 3D meshes

### ISSUE THREAD

**Issue by anish-pratheepkumar** [mikedh/trimesh#1172]
Hi, 

Is it possible to find the volume of intersection between two 3D meshes ? 
(I found options for intersection between mesh and a plane or a line but I could not find a solution for intersection between two 3D meshes.)

**Comment by mikedh** [comment]
Hey, that's what's generally known as a boolean operation, try `trimesh.intersection` which uses either blender or openSCAD as a backend for the boolean.

**Comment by anish-pratheepkumar** [comment]
Thank you so much for your response.
I found this option while debugging and got the results.
I installed OpenBlender(2.9) for working with python 3.6.  Other blender installation options from conda and snap resulted in dependency issues in Ubuntu 18.04 (in case someone else faces the same problem in future).
This issue response also helped - [https://github.com/mikedh/trimesh/issues/333#issuecomment-657241179](url)
