### ISSUE TITLE
trimesh hangs on import

### ISSUE THREAD

**Issue by recohen** [mikedh/trimesh#1173]
python -v 
import trimesh
hangs at:
# code object from '/home/rcohen/.conda/envs/newrec3/lib/python3.6/site-packages/trimesh/exchange/__pycache__/openctm.cpython-36.pyc'

I have uninstalled and reinstalled several tgimes, using conda and pip.

**Comment by recohen** [comment]
I found a strange solution. I set 
PYTHONPATH=$HOME:$PYTHONPATH
and then trimesh imported. After that I did not need the PYTHONPATH anymore.

**Comment by mikedh** [comment]
Oh this looks like there might be a copy of `openctm` somewhere in your path with issues... this should probably be changed in trimesh to lazily import so the error happens only on use of the openctm loader.
