### ISSUE TITLE
Division by 1

### ISSUE THREAD

**Issue by jpmaterial** [mikedh/trimesh#1174]
There is a division by 1 performed at line 181 of graph.py: https://github.com/mikedh/trimesh/blob/523e421e3b18c7061994ad6c8cc663d611a1bad1/trimesh/graph.py#L181

It contradicts the comment (line 178) and seems pointless. Am I missing something?

**Comment by mikedh** [comment]
Yeah definitely wrong and or dumb haha, should be fixed by #1203. Thanks for the report!

**Comment by jpmaterial** [comment]
I guess I should have mentioned that I got correct values *with* the `/1.0`, e.g. for a cylinder of known radius. Did you test the new results?
