### ISSUE TITLE
How to dump mesh with colors to file? 

### ISSUE THREAD

**Issue by hellohawaii** [mikedh/trimesh#1175]
Hi! I am trying to dump a mesh with vertex_colors to an obj file.  I referred to [this issue](https://github.com/mikedh/trimesh/issues/526). I can visualize the mesh with color using mesh.show() as expected, However, the obj file do not have color with it(nor mtl file generated), and the ply file do not correctly set transparency as expected visualzied by meshlab/Deep Exploration.

The following are my codes:

import trimesh
import numpy as np

```
v0 = np.array([0, 0, 0])
v1 = np.array([1, 1, 1])
v2 = np.array([0, 0, 1])
v3 = np.array([1, 1, 0])
plane_mesh = trimesh.Trimesh(vertices=[v0, v1, v2, v3], faces=[[0, 1, 2], [0, 3, 1]])
plane_mesh.visual.vertex_colors = [0, 255, 0, 50]
plane_mesh.show()
plane_mesh.export("./temp_obj.obj", include_normals=False, include_color=True)
plane_mesh.export("./temp_ply.ply")
```

Do my codes use a wrong way to export mesh with colors or Do I use a improper software for visualization? Thank you for your attention!

I am using trimesh 3.9.7 installed from conda source. My platform is Windows10. I am using Python 3.8.5 in anaconda.

**Comment by mikedh** [comment]
Hey, the OBJ exporter should be exporting colors per-vertex. Sometimes in meshlab you have to select color as "from vertex" rather than "from mesh." I just checked, colors here make it into meshlab:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/machinist.XAML')

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(3002, 3), faces.shape=(2990, 3))>

In [4]: _ = m.export('models/machinist.obj')

In [5]: r = trimesh.load('models/machinist.obj')

In [6]: r
Out[6]: <trimesh.Trimesh(vertices.shape=(3002, 3), faces.shape=(2990, 3))>

In [7]: r.visual
Out[7]: <trimesh.visual.color.ColorVisuals at 0x7f4dc39d4970>

In [8]: r.visual.kind
Out[8]: 'vertex'

```
