### ISSUE TITLE
Blender boolean difference operation is nondeterministic

### ISSUE THREAD

**Issue by drknotter** [mikedh/trimesh#1176]
It appears that the trimesh.boolean.difference operator is nondeterministic when using the Blender engine. Sometimes it performs A - B, and sometimes it performs B - A. I believe this is because Blender orders its objects by filename, and not import order, which causes this line:

https://github.com/mikedh/trimesh/blob/master/trimesh/resources/blender_boolean.py.template#L45

to sometimes use a different mesh than the first one in the list (because the temporary filenames are randomized). A potentially straightforward fix would be to de-randomize the names of the temporary mesh files, but I'm not sure if that would cause naming collisions.

**Comment by drknotter** [comment]
My Trimesh version is 3.9.8, and my Blender version is 2.81a.

**Comment by mikedh** [comment]
Thanks for the report! Yeah, reproduced. I added a test (which fails, but should pass) to [this branch](https://github.com/mikedh/trimesh/tree/fix/boolorder). I tried the filename order thing, which didn't appear to fix it. I suspect some additional logic is required [here](https://github.com/mikedh/trimesh/blob/master/trimesh/resources/blender_boolean.py.template#L7-L25).

**Comment by drknotter** [comment]
Oh, didn't see your message before I made a PR: https://github.com/mikedh/trimesh/pull/1177. That PR fixes the issue for me.

**Comment by drknotter** [comment]
Ooops, really sorry, looks like I included a debug print statement in my PR...

**Comment by drknotter** [comment]
I made another PR with the print statement removed: https://github.com/mikedh/trimesh/pull/1178. Really sorry for the noise! Haven't used github in awhile either, so my PR etiquette is a little rusty; please forgive me if I'm doing it incorrectly. :D

**Comment by mikedh** [comment]
Thanks for the fix! Also bizarrely blender doesn't seem to care about the order of the file names (I tried it with prefixing with random but sorted prefixes and the new test failed). It seems like they literally just look at the leading digit in the file name and then use that as the index haha.
