### ISSUE TITLE
Possible parameter unit error in group_vectors (angle)

### ISSUE THREAD

**Issue by stefancon** [mikedh/trimesh#1186]
As explained by the documentation I tried to use group_vectors to find faces with similar normal directions to extract roof segments from a building mesh. Parameter angle is explained as follows: Group vectors closer than this angle in radians. For this I used a value of 1 rad (~57°). But this didn't work and grouped the vectors into way more groups than expected. I had to use high values (like > 10) to achieve desired results.

Am I missing something or could the parameter actually be in a different unit than radians?

**Comment by mikedh** [comment]
Sorry I started looking into this then lost "the dot"... it appears to be using radians, did you figure out what the issue was?

**Comment by stefancon** [comment]
No problem at all. Thanks for replying! I think it was somehow related to our data, but unfortunately I can't remember exactly (should have posted the OBJ model directly with it...). Anyway, I ended up using ``group_distance`` with the face normals as it gave the best results.
