### ISSUE TITLE
Export Scene not behaving as expected

### ISSUE THREAD

**Issue by Cocohop** [mikedh/trimesh#1187]
Hi, thanks for the nice library. This is my first time opening an issue so please let me know if I've done anything wrong.
I have a scene which consists of a mesh and a pointcloud. When I do scene.show() it shows me the scene as expected. However, when I try doing scene.export("file.stl") for example, it creates an empty (1kb) file that when opened shows nothing. This is also the case if I tried using trimesh.exchange.export.export_scene.
This issue also occurs even if I create a scene with only the mesh.
For reference, when I try to export a mesh using trimesh.exchange.export.export_mesh, it works fine as expected.
Thanks.

**Comment by Cocohop** [comment]
Quick update: Played around with it for a bit and found that exporting it as .glb works just fine, it's just the .stl export that causes issues!

**Comment by mikedh** [comment]
Hmm yeah STL only supports triangles no idea what would happen if you try to export a pointcloud haha. Probably the correct thing would be to drop everything except triangles; PR's with unit tests welcome!
