### ISSUE TITLE
How to detect border vertices of an open mesh 3d model?

### ISSUE THREAD

**Issue by Alsheghri** [mikedh/trimesh#1188]

**Comment by mikedh** [comment]
Hey, I think you just need the unique indices from edges (which are indexes of `mesh.vertices`) from https://github.com/mikedh/trimesh/issues/1060: 

```
In [1]: import trimesh
   ...: mesh = trimesh.creation.icosphere()
   ...: # create a one-face hole
   ...: mesh.faces = mesh.faces[1:]
   ...: 
   ...: # an edge which occurs only once is on the boundary
   ...: unique_edges = mesh.edges[trimesh.grouping.group_rows(mesh.edges_sorted, require_count=1)]

In [2]: unique_edges
Out[2]: 
array([[  0, 196],
       [532,   0],
       [196, 532]])

In [3]: import numpy as np

In [4]: boundary_vertices = np.unique(unique_edges.flatten())

In [5]: boundary_vertices
Out[5]: array([  0, 196, 532])
```

**Comment by Alsheghri** [comment]
Thank you very much Mike. This was very helpful. Is there also a quick way to get the boundary faces ?

**Comment by mikedh** [comment]
I think you want `mesh.edges_face`:

```
In [1]: import trimesh
   ...:    ...: mesh = trimesh.creation.icosphere()
   ...:    ...: # create a one-face hole
   ...:    ...: mesh.faces = mesh.faces[1:]


In [2]: index = trimesh.grouping.group_rows(mesh.edges_sorted, require_count=1)

In [4]: import numpy as np

In [5]: boundary_vertices = np.unique(mesh.edges[index].flatten())

In [6]: boundary_vertices
Out[6]: array([  0, 196, 532])

In [9]: boundary_faces = mesh.faces[mesh.edges_face[index]]

In [10]: boundary_faces
Out[10]: 
TrackedArray([[  0, 196, 162],
              [  0, 462, 532],
              [532, 534, 196]])

```

**Comment by Alsheghri** [comment]
Thank you very much Mike ! This was really helpful !

**Comment by juanZaragozaChichell** [comment]
Hello!! I am facing a rather similar problem and I am not sure how to proceed by reading the documentation. My main problem is: I've got a 3D point on my trimesh surface and I want to see if it lies on its boundary. Allow me to make it clearer:

1. The code that you provided before I use it to preprocess the surface and get what the triangles of the boundary are.
`
index_for_unique_stuff = np.sort(trimesh.grouping.group_rows(surface_trimesh.edges_sorted, require_count=1))
boundary_edges = surface_trimesh.edges[index_for_unique_stuff]
index_of_boundary_faces = surface_trimesh.edges_face[index_for_unique_stuff] # index of faces that form the boundary

`
2. The point I have is computed as a footpoint employing mesh.nearest.on_surface(), hence I know the triangle it lies on. 
`footpoint, distance, triangle = surface_trimesh.nearest.on_surface([point])`

Assuming now that *triangle* indeed is one of the boundary (it is in index_of_boundary_faces), how would I get the appropriate edge? Meaning the edge of that triangle that is actually on the boundary.

Thank you very much in advance, and sorry if I have written anything incorrectly both in English and in the form of the post.

**Comment by juanZaragozaChichell** [comment]
Hello!! I am facing a rather similar problem and I am not sure how to proceed by reading the documentation. My main problem is: I've got a 3D point on my trimesh surface and I want to see if it lies on its boundary. Allow me to make it clearer:

1. The code that you provided before I use it to preprocess the surface and get what the triangles of the boundary are.
`index_for_unique_stuff = np.sort(trimesh.grouping.group_rows(surface_trimesh.edges_sorted, require_count=1))`
`boundary_edges = surface_trimesh.edges[index_for_unique_stuff]`
`index_of_boundary_faces = surface_trimesh.edges_face[index_for_unique_stuff] # index of faces that form the boundary`
2. The point I have is computed as a footpoint employing mesh.nearest.on_surface(), hence I know the triangle it lies on.

`footpoint, distance, triangle = surface_trimesh.nearest.on_surface([point])`

Assuming now that triangle indeed is one of the boundary (it is in index_of_boundary_faces), how would I get the appropriate edge? Meaning the edge of that triangle that is actually on the boundary.

Thank you very much in advance, and sorry if I have written anything incorrectly both in English and in the form of the post.
