### ISSUE TITLE
Unable to save image - 'PIL.Image' has no attribute 'fromstring'

### ISSUE THREAD

**Issue by aerogt3** [mikedh/trimesh#1191]
I'm trying to save a screenshot as described in the [off-screen rendering example](https://github.com/mikedh/trimesh/blob/master/examples/offscreen_render.py), but I get the errors below:

>     png = scene.save_image(resolution=[300, 200],window_conf=window_conf, visible=True)
>   File "/home/tests/.local/lib/python3.6/site-packages/trimesh/scene/scene.py", line 812, in save_image
>     **kwargs)
>   File "/home/tests/.local/lib/python3.6/site-packages/trimesh/viewer/windowed.py", line 892, in render_scene
>     window.save_image(file_obj)
>   File "/home/tests/.local/lib/python3.6/site-packages/trimesh/viewer/windowed.py", line 814, in save_image
>     colorbuffer.save(file=file_obj)
>   File "/usr/local/lib/python3.6/dist-packages/pyglet/image/__init__.py", line 497, in save
>     encoder.encode(self, file, filename)
>   File "/usr/local/lib/python3.6/dist-packages/pyglet/image/codecs/pil.py", line 135, in encode
>     image_from_fn = getattr(Image, "frombytes", getattr(Image, "fromstring"))
> AttributeError: module 'PIL.Image' has no attribute 'fromstring'

I get the same errors with the method detailed in the [render example](https://github.com/mikedh/trimesh/blob/master/examples/dockerRender/render.py).
It seems the fromstring method does not exist in recent versions of PIL:

> >>> Image.__version__
> '8.0.1'
> >>> Image.from
> Image.fromarray(    Image.frombuffer(   Image.frombytes(    Image.fromqimage(   Image.fromqpixmap(  

Anyone have any ideas? :D

**Comment by mikedh** [comment]
Hey, I think this is an upstream pyglet issue they fixed a few months ago in https://github.com/pyglet/pyglet/pull/295

Do you have the latest version of pyglet installed (`pip install --upgrade pyglet`)?

**Comment by aerogt3** [comment]
Thanks for the reply! The pyglet upgrade is a step forward :-) I upgraded from 1.5.4 to 1.5.15, however now I get two odd behaviors:
--with visible=True: very quick flash of the mesh on screen, but png is a black image, bottom 10% is a band of alpha=0
--with visible=False: partial screenshot, starting from the top left corner

I'm following the offscreen example, with my ultimate goal being to run this on a headless system, but testing on a system w/ graphics.

**Comment by httpsbao** [comment]
I got the same error, but for me, the problem is that the binary mode of fromstring is deprecated, after I replace fromstring with frombytes, the error was gone, and the program is runnning normally.
