### ISSUE TITLE
Load PLY containing vertices and normals

### ISSUE THREAD

**Issue by JAzorinL** [mikedh/trimesh#1192]
Hi!
I'm trying to load a PLY containing a point cloud and normals using trimesh.load_mesh('xxxx.ply'). However, I just obtain the point cloud. I'm looking for a function to obtain also the normals contained in the PLY but I can't find it. Is there any way to load the point cloud and the normals?

Thank you very much in advance.

**Comment by mikedh** [comment]
PR's (even with just example files) welcome!
