### ISSUE TITLE
Is there a method to fill open surfaces or fill big holes ?

### ISSUE THREAD

**Issue by Alsheghri** [mikedh/trimesh#1196]
![image](https://user-images.githubusercontent.com/74009672/112343088-2dba4880-8c99-11eb-95bc-5d1655cae229.png)

As an example, I would like to fill inside this boundary

**Comment by mikedh** [comment]
Hey, yeah filling holes beyond 1-2 triangles isn't well defined so you'll have to implement something yourself. If it has a nice  boundary (i.e. every vertex on it is 2-connected) that you can turn into a polygon, you might be able to do something easily by getting that boundary, transforming/warping it to a plane through some means, running triangulation in 2D (`trimesh.creation.triangulate_polygon` for example), then warping that result back into 3D. Or I'm sure there's better/fancier methods out there, I would imagine that there is probably quite a number of academic publications on hole filling.

**Comment by Alsheghri** [comment]
Thank you very much
