### ISSUE TITLE
# link trimesh view in tkinter

### ISSUE THREAD

**Issue by akshaypatel1811** [mikedh/trimesh#1197]
Hi Michael,

I don't know if there is something available or not but I want to view my mesh in my tkinter GUI. Is there any way I can do this ?
@mikedh .

Thank you,
Akshay

**Comment by akshaypatel1811** [comment]
I was thinking something like this: 

from tkinter import *
import trimesh

root = Tk()
root.geometry("1200x700+5+5")
def trimesh1():
    # load the stl file:
    file_location = 'abt_mesh.stl'    
    mesh = trimesh.load(file_location)
    s1 = trimesh.scene.Scene(mesh)
    trimesh.viewer.SceneViewer(s1)

button = Button(root, text = " Click here!", command = trimesh1)
button.pack()

root.mainloop()

But it doesn't seems to be working
I also tried
mesh.show() instead of SceneViewers but it also doesn't work.

**Comment by mikedh** [comment]
Hey, not sure about tkinter, but you might check out the [widget example](https://github.com/mikedh/trimesh/blob/master/examples/widget.py) and [glooey](https://github.com/kxgames/glooey)

**Comment by akshaypatel1811** [comment]
Thanks @mikedh. I will try that.

**Comment by Bhavin-Patel08** [comment]
Hii 
I want to view my mesh in my tkinter GUI. please guide me.
@akshaypatel1811 

Thank you,
Bhavin Patel From Gujarat

**Comment by Bhavin-Patel08** [comment]
Hii
I want to view my mesh in my tkinter GUI. please guide me.
@trhermans 

Thank you,
Bhavin Patel From Gujarat
