### ISSUE TITLE
Voxelize STL with different pitches/voxel size in x, y and z directions

### ISSUE THREAD

**Issue by anandjebakumar** [mikedh/trimesh#1199]
Is there a way to voxelize an STL file with different pitches/voxel size in x, y and z directions? Right now, I scale the mesh and then specify an equal voxel size but figured there might be a better way.

**Comment by mikedh** [comment]
Yeah I think scaling is probably your best bet, as there are 3 voxelize methods: subdivide edges below pitch, do ray checks, use binvox. At least the subdivide method doesn't know anything about direction so in that function I would still implement variable pitch with a transform. With rays it would be easy, and I don't know about binvox. If you have a good solution PR's welcome!
