### ISSUE TITLE
How to save image by orthographic projection

### ISSUE THREAD

**Issue by bagel** [mikedh/trimesh#1200]
Hello, Mike

How to save image by orthographic projection

thanks

**Comment by mikedh** [comment]
Hey, you probably want to use something on top of trimesh to do that, something like [pyglet](https://www.meandmark.com/blog/2012/02/creating-a-custom-orthographic-projection-with-pyglet/) or [pyrender](https://github.com/mmatl/pyrender/blob/master/pyrender/camera.py#L209).
