### ISSUE TITLE
avoid window popup in scene.save_image()

### ISSUE THREAD

**Issue by akshaypatel1811** [mikedh/trimesh#1205]
Hi @mikedh,

I am using `image = scene.save_image(resolution=(640, 480),visible= True)` to save the image but every time I use this it is showing another popup window for short period of time and then disappear which is very annoying. So is there any way I can **avoid the pop up window**? I have tried `visible = False`  but it gives me blank image. I have seen #287 but I couldn't find the answer.

I am using everything latest :

Wndows 10
conda version: '4.9.2'
Python version: '3.8.5'
trimesh version: '3.9.10'
Pyglet version: '1.5.15'

Thank you,
Akshay

**Comment by mikedh** [comment]
Hey, yeah what gets rendered to an opengl context is super specific to the platform and isn't really possibly to debug on the trimesh level.
