### ISSUE TITLE
Use principal axes of inertia as a starting point for Point Cloud registration.

### ISSUE THREAD

**Issue by dihuangdh** [mikedh/trimesh#1207]
Hi, mikedh @mikedh 

Thanks for your awesome work.  : )

Could you please explain why you use the principal axes of inertia to achieve better registration? Seems few other ICP implementations use the trick. Is there any reference paper to check?

**Comment by mikedh** [comment]
Hey, yeah ICP in general has problems with local minima, and the closer the initial guess is the better the results. No reference, but PCI seemed like a logical starting point for registration given that for cylinders, long boxes, etc it will give the exactly correct initial position and ICP won't have to do anything.

**Comment by dihuangdh** [comment]
It makes sense. Thanks a lot.
