### ISSUE TITLE
How to get true face normals instead of triangle normals

### ISSUE THREAD

**Issue by richardrl** [mikedh/trimesh#1215]
Let's say we have a rectangular prism. Let's say each of the eight faces is composed of two triangles in the mesh. The trimesh face_normals function returns the normals appended to the center of the triangles (e.g. 16 normals associated with 16 triangles), not the original eight faces. 

I suppose one easy way to get the true faces is, for each point, to propagate along neighboring triangles and collapsing them if the neighboring triangles are on the same plane. But I would prefer to use a built in function if there is one. Is there?

**Comment by mikedh** [comment]
Hey, you might take a look at `mesh.facets` and `mesh.facets_normal` which are groups of coplanar adjacent triangles:
```
In [1]: import trimesh
m = t
In [2]: m = trimesh.creation.box()

In [3]: m.face_normals
Out[3]: 
array([[-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [-1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  0.,  1.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [4]: m.facets?
Type:        property
String form: <property object at 0x7fc4b2c1fcc0>
Docstring:  
Return a list of face indices for coplanar adjacent faces.

Returns
---------
facets : (n, ) sequence of (m, ) int
  Groups of indexes of self.faces

In [6]: m.facets_normal
Out[6]: 
array([[-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])

In [7]: m.facets_normal.shape
Out[7]: (6, 3)
```
