### ISSUE TITLE
I want to know if the trimesh currently supports point drawing

### ISSUE THREAD

**Issue by liqingzhaomingcheng** [mikedh/trimesh#1216]
I am currently trying to load a GLTF file using the trimesh, but because one mesh is mode 0, which means drawing with points, the program says an error of list index out of range when I use the load function. When I check the error, it should be this code that caused such an error
     

```
for j, p in enumerate(m["primitives"]):
    # if we don't have a triangular mesh continue
    # if not specified assume it is a mesh
    if "mode" in p and p["mode"] != 4:
        log.warning('skipping primitive with mode {}!'.format(p['mode']))
        continue
```

**Comment by mikedh** [comment]
Hey, this was added a few days ago in #1212, try `pip install --upgrade trimesh`

**Comment by liqingzhaomingcheng** [comment]
thank you very much! Now there is no problem with the loading, but there is still a problem with the display, I will try to solve it.

**Comment by liqingzhaomingcheng** [comment]
Now I call show function, the image displayed is a blank, but when I delete the mesh part of mode 0 in the GLTF file, it can be displayed normally again, I want to know whether it is
```
import trimesh
scene = trimesh.load('D:/mycode/python/test asset/livingroom0/scene.gltf')
scene.show('gl')
```

**Comment by mikedh** [comment]
Closing as `GL_POINTS` loading was added to gltf loader. Viewer bug may be GL_POINTS issue?
