### ISSUE TITLE
GLTF Vertex Normals are not loaded

### ISSUE THREAD

**Issue by GTO2013** [mikedh/trimesh#1218]
Hi,
thanks are lot for your hard work! I have a dataset of cars and I use a package to convert them to a SDF, which uses trimesh to open the files. The models are zipped gltf files. I have a few models which are not opened correctly:
![image](https://user-images.githubusercontent.com/9764527/115035548-f96b2e00-9ecc-11eb-8c25-daf1d3ef82e0.png)

I can open the file with online gltf viewers just fine:
![image](https://user-images.githubusercontent.com/9764527/115035790-38997f00-9ecd-11eb-9ee8-476d360d78fd.png)

The mesh has vertex colors, but those are not important. I just need correct vertex normals, but they are missing for the main body. Do you have any idea what is going on there?

I have attached the model below.
[model_processed.zip](https://github.com/mikedh/trimesh/files/6325597/model_processed.zip)

Thanks for your help! :)

**Comment by GTO2013** [comment]
Thank you for your quick update! I found the problem I think, but no final solution. The vertex order is messed up on these models, but the saved normals are correct. Loading the scene initially works correctly now thanks to your fix, but once the scene is concatenated the vertex normals are recalculated due to caching based on vertex ordering, which messes them up. Is there any workaround for this? 
![normal_problem](https://user-images.githubusercontent.com/9764527/115115577-8ed1f500-9f95-11eb-8483-7d7d05dd33df.PNG)

**Comment by deekshadesai** [comment]
Hi, I am facing the same issue with concatenate as well. After concatenation of different meshes, the vertex_normals do not have correct normals for them to be displayed properly. My testcase is a simple box which I have created by concatenating different facets as meshes. 
I would also like to know if there are any fixes for this! 

Thanks! :)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66304066/116260978-7d4bd280-a777-11eb-913c-f719cae26ec1.png">

**Comment by mikedh** [comment]
Hey, yeah concatenate definitely needs work robustly handling different cases and unit tests, PR's welcome! Unfortunately I probably can't get to it in the near term.

**Comment by deekshadesai** [comment]
Hi, thanks for the quick reply! I managed to make it work for my case. The problem usually occurs in my case when either the concatenated mesh's winding is inconsistent or it isn't watertight and of course with the recalculated vertex normals.
What worked for me was merging vertices followed by removing degenerate faces and unreferenced vertices from the individual meshes before concatenating them. 
And after the concatenation, fixing the winding. 

I'm not sure if this might help OP with their issue but here it is anyway!

**Comment by mikedh** [comment]
Sounds good, closing for now as the original (loading) issue was solved; I think there's another concatenation issue open but feel free to open another one if not!
