### ISSUE TITLE
Is there a way to save a mesh to .obj without material info

### ISSUE THREAD

**Issue by supriya-gdptl** [mikedh/trimesh#1219]
Hello,

I am using trimesh to convert between different mesh file formats.
I have a .glb file that I am reading as follows:
`mesh = trimesh.load('test.glb', force='mesh')`

and saving it to .obj file as follows:
`_ = mesh.export('test.obj')`

This process is saving a .obj file with material info. Lines in the .obj starts with
```
# https://github.com/mikedh/trimesh
mtllib material0.mtl

o not_clear_obj_0_v6
usemtl material0
v -0.09001372 0.02697348 -0.13360523
```
Is there a way to save this mesh without the material information?
Thanks,
Supriya

**Comment by mikedh** [comment]
Hey, yeah if you switch out the `TextureVisuals` for an empty `ColorVisuals` it should do that:

```
In [3]: import trimesh

In [5]: m = trimesh.load('models/fuze.obj')

In [6]: m
Out[6]: <trimesh.Trimesh(vertices.shape=(664, 3), faces.shape=(1000, 3))>

In [7]: e = m.export(file_type='obj')

In [9]: print(e[:100])
# https://github.com/mikedh/trimesh
mtllib material0.mtl
usemtl material0
v 0.02297600 -0.02802300 0

In [10]: m.visual
Out[10]: <trimesh.visual.texture.TextureVisuals at 0x7fa73b4acca0>

In [12]: m.visual = trimesh.visual.ColorVisuals()

In [13]: e = m.export(file_type='obj')

In [14]: print(e[:100])
# https://github.com/mikedh/trimesh
v 0.02297600 -0.02802300 0.07935400
v -0.03532800 -0.00313400 0.

```

**Comment by supriya-gdptl** [comment]
Great! It worked.
Thank you very much for the help.

**Comment by laion01** [comment]
it worked, but material not applied. How can I fix this?

**Comment by laion01** [comment]
@mikedh how can I fix this?

![image](https://github.com/user-attachments/assets/8cbbcd1b-2d12-411f-99b9-2a60abbbd033)
