### ISSUE TITLE
Is it really watertight ?

### ISSUE THREAD

**Issue by JPFrancoia** [mikedh/trimesh#122]
Hi,

After the issue I opened (#100 ), I still encounter some problems when I try to "validate" a STL.

Let's take this one:

[test2.stl.txt](https://github.com/mikedh/trimesh/files/1592911/test2.stl.txt)

When I test it with FreeCAD, I get 0 non-manifolds. But when I test it with trimesh, ```is_watertight``` is False. I tried to show the mesh with coloured faces, but I can't spot the faulty ones. I'm almost sure there is no non-manifolds (at least theoretically, when I build the model), so could you help me understand what's wrong here ?

Cheers

**Comment by mikedh** [comment]
![manifold](https://user-images.githubusercontent.com/1403074/34455915-75ecd954-ed57-11e7-91d1-025ebfba2072.png)

```
In [27]: trimesh.repair.broken_faces(m, color=[255,0,0,255])
```

Hey, that mesh has an edge with two faces coming off of it, so not every edge is shared by exactly two triangles. I think trimesh in this case is correct to flag it as invalid. 

You might be able to repair this case automatically by splitting the broken edges at the vertex and then replacing the now- quad face with triangles.

Best,
Mike

**Comment by JPFrancoia** [comment]
Hi, sorry for the delay, I was in holidays. How did you managed to get this wire representation ?

**Comment by mudimans** [comment]
Although this is an old post, I would like to add that according to the open3d manual:
'A watertight mesh can be defined as a mesh that is edge manifold, vertex manifold and not self intersecting.'

I guess for trimesh this is the same. So bassically a watertight mesh has all three of the properties above, but in freecad you were only testing for one.
