### ISSUE TITLE
Is there a way to sample a surface to a PointCloud with Colors?

### ISSUE THREAD

**Issue by sai-cherukumilli-enview** [mikedh/trimesh#1220]
I currently use `trimesh.sample.sample_surface` method to sample the surface and generate a PointCloud. But this PointCloud is missing the color attributes. 

Is there a way to get the surface color for these points in the PointCloud?

**Comment by mikedh** [comment]
Hey, I would get the face indices from `sample_surface`, and then either take the face colors, or do barycentric interpolation on vertex colors. `sample_surface` is already using barycentric sampling internally, you could probably add a `vertex_attributes` or `return_barycentric` argument to it pretty easily that would make this very straightforward; PR's welcome!
