### ISSUE TITLE
Is there any easy way to perform edge contraction on meshes?

### ISSUE THREAD

**Issue by granitdula** [mikedh/trimesh#1222]
Hi,
Just to clarify, by edge contraction, I mean this:
![image](https://user-images.githubusercontent.com/30119390/115558306-82f27580-a2aa-11eb-8584-8eda52e5b51d.png)
Is there any easy way to do this with Trimesh? It seems as though this process would require deleting vertices, adding a new vertex v_bar and deleting the greyed out faces and reconnecting all the outer vertices to the middle one. I'm not really sure how to easily do this with Trimesh. Would appreciate any help.

Thanks.

**Comment by granitdula** [comment]
I found out about `merge_vertices`, which seems like it can be used for this (although not sure if it handles deleting the faces?). Is there any way to get the index of the vertex v_bar after merging v1 and v2?

**Comment by mikedh** [comment]
Hey just looking quickly I think I'd probably start by trying to construct a vertex mask (which will reindex faces) and then use `remove_degenerate_faces`:
```
In [1]: import trimesh

In [2]: m = trimesh.creation.icosphere()

In [3]: m.update_vertices?
Signature: m.update_vertices(mask, inverse=None)
Docstring:
Update vertices with a mask.

Parameters
------------
vertex_mask : (len(self.vertices)) bool
  Array of which vertices to keep
inverse : (len(self.vertices)) int
  Array to reconstruct vertex references
  such as output by np.unique
File:      /media/psf/Dropbox/robotics/trimesh/trimesh/base.py
Type:      method

In [4]: m.remove_degenerate_faces?
Signature: m.remove_degenerate_faces(height=1e-08)
Docstring:
Remove degenerate faces (faces without 3 unique vertex indices)
from the current mesh.

If a height is specified, it will remove any face with a 2D oriented
bounding box with one edge shorter than that height.

If not specified, it will remove any face with a zero normal.

Parameters
------------
height : float
  If specified removes faces with an oriented bounding
  box shorter than this on one side.

Returns
-------------
nondegenerate : (len(self.faces), ) bool
  Mask used to remove faces
File:      /media/psf/Dropbox/robotics/trimesh/trimesh/base.py
Type:      method

```

**Comment by granitdula** [comment]
Thanks for getting back @mikedh.

So from what I can understand, `update_vertices` with the mask can be used to remove the vertices v1 and v2. But then how would you add v_bar into the mesh and also get its index in the list of vertices of the mesh?

**Comment by granitdula** [comment]
Hi @mikedh 

Just as an update, it seems as though `merge_vertices` does what I want, where I do 
```
mesh.vertices[v1] = mesh.vertices[v2] = v_bar
mesh.merge_vertices()
```
However, I still need to get the index of the newly merged vertex relative to the new mesh's `mesh.vertices`, which I'm not sure how to do. (Also would I still need to do `mesh.remove_degenerate_faces()` in order to actually remove those grey faces after merging the vertices?)

Thanks.

**Comment by granitdula** [comment]
Just to update, this seems to work to contract the edges and also return the index of the vertex `v_bar`. Although it isn't very elegant.
```python
def edge_contract(mesh, v1_index, v2_index, v_bar):
    i = v1_index if v1_index < v2_index else v2_index
    mesh.vertices[v1_index] = mesh.vertices[v2_index] = v_bar
    
    # Uses this to get the index of the v_bar vertex after its merged.
    unique, inverse = trimesh.grouping.unique_rows(mesh.vertices)
    v_bar_index = np.where(unique == i)[0].item()
    
    mesh.merge_vertices()
    mesh.remove_degenerate_faces()
    
    return v_bar_index
```
Hopefully this helps someone. I will close this issue.
