### ISSUE TITLE
Class constructors documentation

### ISSUE THREAD

**Issue by Grandmother** [mikedh/trimesh#1223]
Hi there. You have a good documentation in code for `__init__` methods of classes, but this documentation isn't shown on Sphinx pages.

Is it a bug or a feature?

I could try to configure Sphinx to show such documentation.

**Comment by Grandmother** [comment]
Sorry. Here is an example:
[Sphinx:trimesh.base.Trimesh](https://trimsh.org/trimesh.base.html#trimesh.base.Trimesh)
[Code:trimesh.base.Trimesh.\_\_init\_\_](https://github.com/mikedh/trimesh/blob/master/trimesh/base.py#L67-L98)

**Comment by mikedh** [comment]
Oh yeah that's interesting! Yeah PRs super welcome if you can figure out how to get Sphinx to output those!

**Comment by mikedh** [comment]
[This appears](https://github.com/mikedh/trimesh/pull/1221/commits/3f873e04de5e87d96ce4f4b3a6404fd3ef5947b9#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R113-R116) to fix this.

**Comment by Grandmother** [comment]
Well, I couldn't do better) Thanks!
