### ISSUE TITLE
Bounding box as_outline only forming one face

### ISSUE THREAD

**Issue by avivbd** [mikedh/trimesh#1226]
When plotting an outline of a bounding box only one face is being shown.
@mikedh 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/20915857/115931948-e57d7a00-a440-11eb-9fda-dc2f67c33836.png">

**Comment by mikedh** [comment]
Not sure what's going on there, it looks like it shows up the the GL viewer and GLTF export:
```
import numpy as np
import trimesh

if __name__ == '__main__':

    trimesh.util.attach_to_log()

    m = trimesh.creation.cylinder(
        radius=1, height=10).permutate.transform()
    b = m.bounding_box
    o = b.as_outline()

    trimesh.Scene([m, o]).show()

    s = trimesh.Scene()
    s.add_geometry(m)
    s.add_geometry(o)
    s.show()
```
![repro](https://user-images.githubusercontent.com/1403074/116017363-625d4f00-a60d-11eb-9574-53a45095075f.png)

If you spin the view does it persist? Could be clipping planes or something.

**Comment by avivbd** [comment]
I tried it locally and it works ok. So I'm guessing it has something to do
with the environment. I'm running on gitlab hosted on Azure.

**Comment by mikedh** [comment]
Yeah, not sure what they'd be doing differently... I suspect it's a viewing artifact? You could look at the entity and see how many points it has.
