### ISSUE TITLE
.show() Documentation?

### ISSUE THREAD

**Issue by JPLost** [mikedh/trimesh#1227]
Where can I find the documentation for the .show() function and what arguments I can use with it?

**Comment by mikedh** [comment]
Hey, `mesh.show`/`scene.show` are both calling [Scene.show](https://trimsh.org/trimesh.scene.html#trimesh.scene.Scene.show) which passes its `kwargs` through to [`viewers.windowed.SceneViewer`](https://trimsh.org/trimesh.viewer.windowed.html#trimesh.viewer.windowed.SceneViewer) (the init probably has the most relevant list of arguments).
