### ISSUE TITLE
PLY Export ignores Vertexnormals from cache

### ISSUE THREAD

**Issue by 0x23** [mikedh/trimesh#1233]
Problem: The export_ply function ignores the vertex normals of the mesh
Location:

ply.py - Function export_ply() - Line 261:
```
# only export them if they are stored in cache
 if vertex_normal is None:
      vertex_normal = 'vertex_normal' in mesh._cache
```

Reason:
   The function looks for the key 'vertex_normal' but the normals are stored in the cache under the name 'vertex_normals'.
   So there seems to be missing an 's' at the end.

Would be nice if someone could change the string accordingly :)

**Comment by mikedh** [comment]
Hopefully fixed by [#1236](https://github.com/mikedh/trimesh/pull/1236/files#diff-a3d9afdd308e5407202efdbd8a13321988672737edc4375c8aa8e62e85291e01R258). Thanks for the report!
