### ISSUE TITLE
Missing geometry nodes in .glb exported from Blender

### ISSUE THREAD

**Issue by jloganolson** [mikedh/trimesh#1235]
I'm trying to import a simple scene (three boxes in a hierarchy) built in Blender and exported to .glb - while all nodes are imported only the 'bottom'/'leaf' box has geometry. Are there any workarounds or things I could be doing differently or leads in general?

**Comment by mikedh** [comment]
Does it look alright/validate in this online viewer? https://gltf-viewer.donmccurdy.com/

If so could you post the file? Thanks!

**Comment by jloganolson** [comment]
Affirmative - screenshot from online viewer and glb attached! (glb files don't seem supported for upload so zipped it up).

[nested.zip](https://github.com/mikedh/trimesh/files/6411814/nested.zip)
![image](https://user-images.githubusercontent.com/14350126/116820514-77187600-ab2a-11eb-93f4-831e4a11b05f.png)

I should also probably note that the one piece of geometry that does load is quite glitchy (like the faces of the cube are only visible at oblique angles).

**Comment by mikedh** [comment]
Thanks for the model! Looks like the node attribute bookkeeping was unhappy, I pushed a fix. I did notice the models were still kind of messed up looking, like the cascaded scale matrices were inverting/flipping something.

**Comment by jloganolson** [comment]
Awesome! I'll open a separate issue for the model glitchiness with cleaner repro
