### ISSUE TITLE
AttributeError: module 'trimesh' has no attribute 'load'

### ISSUE THREAD

**Issue by zaki-star** [mikedh/trimesh#1239]
Hello, 

suddenly this error occurs:

  File "C:/Users/user/Desktop/Fraunhofer Arbeit/Python_Code/trimesh.py", line 13, in <module>
    mesh = trimesh.load(r'C:/Users/user/Desktop/IZFP2.STL')

AttributeError: module 'trimesh' has no attribute 'load'

trimesh.load has worked the whole time. I don't understand why this error has taken place from one moment to the other...

I already unistalled trimesh and installed it once again but this didn't work.

**Comment by mikedh** [comment]
Hey, I think since your script file is also named trimesh Python may be trying to import trimesh your script instead of trimesh the module? I might try renaming it to script.py or something and see if that works.

**Comment by zaki-star** [comment]
Yes, you are right. Thank you!
