### ISSUE TITLE
points.remove_close?

### ISSUE THREAD

**Issue by wanweiwei07** [mikedh/trimesh#1240]
Hi Mike,

Thanks for answering my last question several weeks ago.
Now I have a new problem.

I may misunderstood the usage but it seems the remove_close function removes all points that are near to some other points. The results are not even, for a bulky mutually connected section will be completely removed.

One may get something like this:
![image](https://user-images.githubusercontent.com/3246300/117111624-dc869400-adc2-11eb-9c6e-1372fc40cf2c.png)
while the real goal is something like this:
![image](https://user-images.githubusercontent.com/3246300/117111688-f1632780-adc2-11eb-9bb2-63f17254a777.png)

**Comment by mikedh** [comment]
Hey, yeah just playing with that function it looks like it's doing something somewhat sensible, removing the highest-degree node from every edge of the graph that's formed by every pair of points closer than radius. For similar problems there are definitely some nice results from various [mesh parameterization](https://www.inf.usi.ch/hormann/parameterization/index.html) works. However trimesh doesn't have a nice implementation of any of them haha. Unfortunately `trimesh.Trimesh.unwrap` which uses blender was broken by Blender's 2.9 release API change. 

However, oversampling and then carefully choosing a radius gets some decent easy results:

```
    m =	trimesh.load('models/bunny.ply')

    count = 1000
    samples = m.sample(count)

    R = (m.area ** 0.5) / (count ** 0.5)

    n = samples[trimesh.points.remove_close(samples, R)[1]]
    trimesh.Scene([m, trimesh.PointCloud(n)]).show()

```
![samples](https://user-images.githubusercontent.com/1403074/117234259-a52fdb80-adf2-11eb-827a-a997224b46a8.png)

**Comment by wanweiwei07** [comment]
I appreciate your quick reply. I guess I am understanding the algorithms more now. It seems the algorithm may remove points iteratively. i.e. a-b, b-c, c-d. a has a larger degree than b, then remove a. b has a larger degree than c, then remove b. c has a larger degree than d, then remove c. At the end, only d is left.
