### ISSUE TITLE
mesh.apply_scale can create null vertex_normals in a few cases

### ISSUE THREAD

**Issue by ClementRolinat** [mikedh/trimesh#1241]
Hello,

I use this package to process some meshes from ShapeNet.
My processing involves some random rescaling of the meshes, among other things.

in some rare case, after the rescaling some element of mesh.vertex_normals become null.

Here a minimal code that shows the error on one of the mesh (the mesh is in the zip file):
```
mesh = trimesh.load_mesh(model_path)

test_norm = np.isclose(linalg.norm(mesh.vertex_normals, axis=1), np.ones(len(mesh.vertex_normals)))
if np.any(~test_norm):
    print("normal vector not unit before rescaling")
    print("index : ", np.where(~test_norm)[0])
    print("normal components : ", mesh.vertex_normals[np.where(~test_norm)[0]])

mesh_backup = mesh.copy()
mesh.apply_scale(0.46377314288075433)
test_norm = np.isclose(linalg.norm(mesh.vertex_normals, axis=1), np.ones(len(mesh.vertex_normals)))
if np.any(~test_norm):
    print("normal vector not unit after rescaling")
    print("index: ", np.where(~test_norm)[0])
    print("normal components: ", mesh.vertex_normals[np.where(~test_norm)[0]])
    print("value of normal components before rescaling: ", mesh_backup.vertex_normals[np.where(~test_norm)[0]])
```
[model24765.zip](https://github.com/mikedh/trimesh/files/6441965/model24765.zip)

executing this code return the following:
```
normal vector not unit after rescaling
index:  [537]
normal components:  [[0.0000000e+00 0.0000000e+00 3.5942475e-27]]
value of normal components before rescaling:  [[ 0.  0. -1.]]
```

**Comment by mikedh** [comment]
Thanks for the report! After looking at it, I think what's happening here is:
- model is loaded with vertex normals
- model has degenerate faces, which lead to zero-norm vertex normals when computed from sparse matrix
- scaling was causing the loaded vertex normals to be dropped (bug) 
- regenerated vertex normals have some zero-value terms because the degenerate faces have zero-value normals

I think the main issue is the cache drop when it should have just scaled then re-unitized the normals, which should be fixed by #1236.

**Comment by ClementRolinat** [comment]
Hello, I agree with you on the fact that a rescaling should not drop the stored vertex_normals. 
However I don't think this bug appears only with model having degenerate faces.

First, for the same model, only some specific rescaling factors lead to the bug (you can try with the model and code provided with a different scaling factor, the bug disapear). So it is unlikely to be linked to the model itself, as in this case the bug would be present regardless of the scaling factor.

Moreover, I already suspected some issues with the cache. I remember deleting the cache after loading and recomputing the normals, and I think that the normals where correctly recomputed before rescaling, and still wrong after rescaling. I will re-test that tomorrow to confirm this.

**Comment by ClementRolinat** [comment]
If I understood well, you think that the bug may appear on any model that has some sort of inconsistency on its face normals. On the model that I gave as an example, the null vertex normal appears on a vertex with one adjacent face normal flipped compared to the others.

In that case, how is it possible that on this example, this vertex normal is null only when applying some specific scaling factor ? For a given model, the behavior should be the same for any scaling value. Here, this is not the case: for some scaling value this vertex normal is not null for the same model.
