### ISSUE TITLE
Problem with save_image()

### ISSUE THREAD

**Issue by Diskein** [mikedh/trimesh#125]
I wanted to use trimesh to save previews of the models. But I was faced with the fact that I can not do this without drawing a pyglet window.

I have code:

```python
import trimesh
m = trimesh.load_mesh("something.stl")
png = m.scene().save_image()
```

Scene.save_image() method returns an empty image.  This happens apparently because the opengl buffer is empty until the window is rendered. If I pass `visible = True`, the image is saved, but a window is displayed.

**Comment by mikedh** [comment]
Hey, I think this is similar to the issue they were having in https://github.com/mikedh/trimesh/issues/115

If it works with `visible = True`, it is likely that pyglet can't get an OpenGL context with a hidden window on your platform.  What OS and OS version are you on?

Best,
Mike

**Comment by Diskein** [comment]
Linux Mint 18.2 Cinnamon, linux kernel 4.8.0-53

**Comment by mikedh** [comment]
Hey, I changed the default behavior to always show a visible window- its a total crap shoot whether or not a hidden openGL window will render anything.
