### ISSUE TITLE
How to load .fbx files?

### ISSUE THREAD

**Issue by 1mol-bit** [mikedh/trimesh#1254]
Hi, thanks for excelent work. 
I want to load a .fbx model downloaded from 'https://renderpeople.com/' to mesh. I try to convert the .fbx model to a .obj model, but the .fbx model is an animation and the converted .obj model only extract the information of the first frame. So is there a way to load all the information of the whole .fbx animation using trimesh?

**Comment by mikedh** [comment]
Hey, FBX loading isn't implemented natively in trimesh, it's using [assimp](https://github.com/assimp/assimp) under the hood, which may be best used directly for more complicated things like this. Also currently trimesh doesn't have support for animations so it probably at best is going to get the first frame haha.
