### ISSUE TITLE
May I ask if there is a trimesh version that does not need to add ops

### ISSUE THREAD

**Issue by ikhblo** [mikedh/trimesh#1255]
mesh = trimesh.voxel.matrix_to_marching_cubes(
        matrix=voxelgrid,
        pitch=1.0,
        origin=(0,0,0))

origin does not know what to deal in the new ops statement.

**Comment by mikedh** [comment]
Hey, the only keyword arguments for `matrix_to_marching_cubes` are `matrix` and `pitch`, just remove the `origin` from your call:

https://trimsh.org/trimesh.voxel.ops.html#trimesh.voxel.ops.matrix_to_marching_cubes

**Comment by ikhblo** [comment]
The problem is solved, thank you very much.
