### ISSUE TITLE
computation of facets

### ISSUE THREAD

**Issue by cujhg** [mikedh/trimesh#1260]
Hi Mike,

is there any particular reason why this formula is used?

https://github.com/mikedh/trimesh/blob/5276d45ff50b3fd937e24c72f46a7ec3f0b0d777/trimesh/graph.py#L294-L295

Would something like this also work?
```
parallel = mesh.face_adjacency_angles < angle_threshold
```
Also, I think it would be great if the threshold value was a function parameter (with a default value)
In that case an angle might be more convenient to tune. 

Thanks!

**Comment by mikedh** [comment]
Hey, yeah the reason it's not just doing an angle threshold is because for very small faces precision issues can push the normal vectors past a small angle threshold and disconnect regions that should really be connected. If an angle threshold is good enough I'd probably just use this one-liner: 

```
In [1]: import trimesh

In [2]: mesh = trimesh.creation.box()

In [6]: import numpy as np

In [7]: threshold = np.radians(1.0)

In [8]: facets = trimesh.graph.connected_components(mesh.face_adjacency[mesh.face_adjacency_angles < threshold])

In [9]: facets
Out[9]: 
[array([0, 2]),
 array([1, 5]),
 array([3, 8]),
 array([4, 6]),
 array([7, 9]),
 array([10, 11])]
```

**Comment by aprath1** [comment]
Is it possible to declare two faces to be parallel if the span of the perpendicular projection of the non-shared vertices on to the shared edge is zero. Isn't it possible for the span to be non-zero and still the adjacent faces are co-planar?
