### ISSUE TITLE
Why `Trimesh.process` is not automatically applied in `Trimesh.slice_plane`?

### ISSUE THREAD

**Issue by sataset** [mikedh/trimesh#1262]
Are there any reasons to set `Trimesh.process = false`?
For example in plane slice method it is set to `false` if not specified.

As I understand Inf and NaN vertices are not needed and causing problems thus should be removed.

**Comment by mikedh** [comment]
Hey, yeah it's relying on the input mesh being cleaned first. Since `slice_plane` is doing the bookkeeping itself it shouldn't be creating bad vertices, are you seeing sliced meshes with `NaN` vertices?

**Comment by sataset** [comment]
Thank you for the answer.
I have not encountered to them yet but wondering if I need to forward `process` kwarg everytime I am slicing with plane. I assume `process=true` should be applied in any case.

**Comment by mikedh** [comment]
No worries, I wouldn't process unless necessary as it can be relatively expensive- `slice_plane` really shouldn't be screwing up the vertices haha.
