### ISSUE TITLE
Possible Moment of Inertia Discrepancy

### ISSUE THREAD

**Issue by Ahorvath94** [mikedh/trimesh#1267]
Hi all!

I have been investigating trimesh as a means of calculating the moment of inertia of a .obj file. I generated a simple 1 inch radius x 1 inch long cylinder in FreeCAD and calculated the moment of inertia as shown below using FreeCAD's built-in moment of inertia function:

![image](https://user-images.githubusercontent.com/28616478/121782443-74705e00-cb77-11eb-892b-7121509a38d6.png)

![image](https://user-images.githubusercontent.com/28616478/121782483-9f5ab200-cb77-11eb-9364-b1e34e532a0f.png)

I then exported it as a .obj file with FreeCAD export.

I then ran this code:

![image](https://user-images.githubusercontent.com/28616478/121782520-c0230780-cb77-11eb-9719-e83f1b36fb57.png)

Which gives the result:
![image](https://user-images.githubusercontent.com/28616478/121782533-d335d780-cb77-11eb-9bd6-b8bf4ef34481.png)

Notice that the Ixx, Iyy and Izz terms are relatively close between FreeCAD and trimesh, but Ixy, Iyz ... differ significantly. I am not sure which program is correct but might be good to check the calculation of this.

Here is the .obj file

v 25.400000 0.000000 0.000000
v 25.207481 3.121363 0.000000
v 25.400000 0.000000 25.400000
v 25.207481 3.121363 25.400000
v 24.632843 6.195408 0.000000
v 24.632843 6.195408 25.400000
v 23.684795 9.175538 0.000000
v 23.684795 9.175538 25.400000
v 22.377710 12.016577 0.000000
v 22.377710 12.016577 25.400000
v 20.731401 14.675455 0.000000
v 20.731401 14.675455 25.400000
v 18.770826 17.111870 0.000000
v 18.770826 17.111870 25.400000
v 16.525705 19.288885 0.000000
v 16.525705 19.288885 25.400000
v 14.030070 21.173500 0.000000
v 14.030070 21.173500 25.400000
v 11.321754 22.737148 0.000000
v 11.321754 22.737148 25.400000
v 8.441812 23.956123 0.000000
v 8.441812 23.956123 25.400000
v 5.433900 24.811947 0.000000
v 5.433900 24.811947 25.400000
v 2.343616 25.291649 0.000000
v 2.343616 25.291649 25.400000
v -0.782194 25.387953 0.000000
v -0.782194 25.387953 25.400000
v -3.896148 25.099403 0.000000
v -3.896148 25.099403 25.400000
v -6.951040 24.430372 0.000000
v -6.951040 24.430372 25.400000
v -9.900561 23.391001 0.000000
v -9.900561 23.391001 25.400000
v -12.700000 21.997046 0.000000
v -12.700000 21.997046 25.400000
v -15.306920 20.269638 0.000000
v -15.306920 20.269638 25.400000
v -17.681803 18.234962 0.000000
v -17.681803 18.234962 25.400000
v -19.788647 15.923864 0.000000
v -19.788647 15.923864 25.400000
v -21.595514 13.371377 0.000000
v -21.595514 13.371377 25.400000
v -23.075018 10.616193 0.000000
v -23.075018 10.616193 25.400000
v -24.204727 7.700078 0.000000
v -24.204727 7.700078 25.400000
v -24.967516 4.667238 0.000000
v -24.967516 4.667238 25.400000
v -25.351824 1.563647 0.000000
v -25.351824 1.563647 25.400000
v -25.351824 -1.563647 0.000000
v -25.351824 -1.563647 25.400000
v -24.967516 -4.667238 0.000000
v -24.967516 -4.667238 25.400000
v -24.204727 -7.700078 0.000000
v -24.204727 -7.700078 25.400000
v -23.075018 -10.616193 0.000000
v -23.075018 -10.616193 25.400000
v -21.595514 -13.371377 0.000000
v -21.595514 -13.371377 25.400000
v -19.788647 -15.923864 0.000000
v -19.788647 -15.923864 25.400000
v -17.681803 -18.234962 0.000000
v -17.681803 -18.234962 25.400000
v -15.306920 -20.269638 0.000000
v -15.306920 -20.269638 25.400000
v -12.700000 -21.997046 0.000000
v -12.700000 -21.997046 25.400000
v -9.900561 -23.391001 0.000000
v -9.900561 -23.391001 25.400000
v -6.951040 -24.430372 0.000000
v -6.951040 -24.430372 25.400000
v -3.896148 -25.099403 0.000000
v -3.896148 -25.099403 25.400000
v -0.782194 -25.387953 0.000000
v -0.782194 -25.387953 25.400000
v 2.343616 -25.291649 0.000000
v 2.343616 -25.291649 25.400000
v 5.433900 -24.811947 0.000000
v 5.433900 -24.811947 25.400000
v 8.441812 -23.956123 0.000000
v 8.441812 -23.956123 25.400000
v 11.321754 -22.737148 0.000000
v 11.321754 -22.737148 25.400000
v 14.030070 -21.173500 0.000000
v 14.030070 -21.173500 25.400000
v 16.525705 -19.288885 0.000000
v 16.525705 -19.288885 25.400000
v 18.770826 -17.111870 0.000000
v 18.770826 -17.111870 25.400000
v 20.731401 -14.675455 0.000000
v 20.731401 -14.675455 25.400000
v 22.377710 -12.016577 0.000000
v 22.377710 -12.016577 25.400000
v 23.684795 -9.175538 0.000000
v 23.684795 -9.175538 25.400000
v 24.632843 -6.195408 0.000000
v 24.632843 -6.195408 25.400000
v 25.207481 -3.121363 0.000000
v 25.207481 -3.121363 25.400000
vn 0.998103 0.061561 -0.000000
vn 0.998103 0.061561 0.000000
vn 0.982973 0.183749 -0.000000
vn 0.982973 0.183749 0.000000
vn 0.952942 0.303153 -0.000000
vn 0.952942 0.303153 0.000000
vn 0.908465 0.417960 -0.000000
vn 0.908465 0.417960 0.000000
vn 0.850217 0.526432 -0.000000
vn 0.850217 0.526432 0.000000
vn 0.779081 0.626924 -0.000000
vn 0.779081 0.626924 0.000000
vn 0.696134 0.717912 -0.000000
vn 0.696134 0.717912 0.000000
vn 0.602634 0.798017 -0.000000
vn 0.602634 0.798017 0.000000
vn 0.500000 0.866025 -0.000000
vn 0.500000 0.866025 0.000000
vn 0.389786 0.920906 -0.000000
vn 0.389786 0.920906 0.000000
vn 0.273663 0.961826 -0.000000
vn 0.273663 0.961826 0.000000
vn 0.153392 0.988165 -0.000000
vn 0.153392 0.988165 0.000000
vn 0.030795 0.999526 -0.000000
vn 0.030795 0.999526 0.000000
vn -0.092268 0.995734 0.000000
vn -0.092268 0.995734 0.000000
vn -0.213933 0.976848 0.000000
vn -0.213933 0.976848 0.000000
vn -0.332355 0.943154 0.000000
vn -0.332355 0.943154 0.000000
vn -0.445738 0.895163 0.000000
vn -0.445738 0.895163 0.000000
vn -0.552365 0.833602 0.000000
vn -0.552365 0.833602 0.000000
vn -0.650618 0.759405 0.000000
vn -0.650618 0.759405 0.000000
vn -0.739009 0.673696 0.000000
vn -0.739009 0.673696 0.000000
vn -0.816197 0.577774 0.000000
vn -0.816197 0.577774 0.000000
vn -0.881012 0.473094 0.000000
vn -0.881012 0.473094 0.000000
vn -0.932472 0.361242 0.000000
vn -0.932472 0.361242 0.000000
vn -0.969797 0.243913 0.000000
vn -0.969797 0.243913 0.000000
vn -0.992421 0.122888 0.000000
vn -0.992421 0.122888 0.000000
vn -1.000000 0.000000 0.000000
vn -1.000000 -0.000000 0.000000
vn -0.992421 -0.122888 0.000000
vn -0.992421 -0.122888 0.000000
vn -0.969797 -0.243913 0.000000
vn -0.969797 -0.243913 0.000000
vn -0.932472 -0.361242 0.000000
vn -0.932472 -0.361242 0.000000
vn -0.881012 -0.473094 0.000000
vn -0.881012 -0.473094 0.000000
vn -0.816197 -0.577774 0.000000
vn -0.816197 -0.577774 0.000000
vn -0.739009 -0.673696 0.000000
vn -0.739009 -0.673696 0.000000
vn -0.650618 -0.759405 0.000000
vn -0.650618 -0.759405 0.000000
vn -0.552365 -0.833602 0.000000
vn -0.552365 -0.833602 0.000000
vn -0.445738 -0.895163 0.000000
vn -0.445738 -0.895163 0.000000
vn -0.332355 -0.943154 0.000000
vn -0.332355 -0.943154 0.000000
vn -0.213933 -0.976848 0.000000
vn -0.213933 -0.976848 0.000000
vn -0.092268 -0.995734 0.000000
vn -0.092268 -0.995734 0.000000
vn 0.030795 -0.999526 0.000000
vn 0.030795 -0.999526 0.000000
vn 0.153392 -0.988165 0.000000
vn 0.153392 -0.988165 0.000000
vn 0.273663 -0.961826 0.000000
vn 0.273663 -0.961826 0.000000
vn 0.389786 -0.920906 0.000000
vn 0.389786 -0.920906 0.000000
vn 0.500000 -0.866025 0.000000
vn 0.500000 -0.866025 0.000000
vn 0.602634 -0.798017 0.000000
vn 0.602634 -0.798017 0.000000
vn 0.696134 -0.717912 0.000000
vn 0.696134 -0.717912 0.000000
vn 0.779081 -0.626924 0.000000
vn 0.779081 -0.626924 0.000000
vn 0.850217 -0.526432 0.000000
vn 0.850217 -0.526432 0.000000
vn 0.908465 -0.417960 0.000000
vn 0.908465 -0.417960 0.000000
vn 0.952942 -0.303153 0.000000
vn 0.952942 -0.303153 0.000000
vn 0.982973 -0.183749 0.000000
vn 0.982973 -0.183749 0.000000
vn 0.998103 -0.061561 0.000000
vn 0.998103 -0.061561 0.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn -0.000000 -0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn -0.000000 -0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn -0.000000 -0.000000 -1.000000
vn -0.000000 -0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 -0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
f 1//1 2//1 3//1
f 3//2 2//2 4//2
f 2//3 5//3 4//3
f 4//4 5//4 6//4
f 5//5 7//5 6//5
f 6//6 7//6 8//6
f 7//7 9//7 8//7
f 8//8 9//8 10//8
f 9//9 11//9 10//9
f 10//10 11//10 12//10
f 11//11 13//11 12//11
f 12//12 13//12 14//12
f 13//13 15//13 14//13
f 14//14 15//14 16//14
f 15//15 17//15 16//15
f 16//16 17//16 18//16
f 17//17 19//17 18//17
f 18//18 19//18 20//18
f 19//19 21//19 20//19
f 20//20 21//20 22//20
f 21//21 23//21 22//21
f 22//22 23//22 24//22
f 23//23 25//23 24//23
f 24//24 25//24 26//24
f 25//25 27//25 26//25
f 26//26 27//26 28//26
f 27//27 29//27 28//27
f 28//28 29//28 30//28
f 30//29 31//29 32//29
f 29//30 31//30 30//30
f 32//31 33//31 34//31
f 31//32 33//32 32//32
f 34//33 35//33 36//33
f 33//34 35//34 34//34
f 36//35 37//35 38//35
f 35//36 37//36 36//36
f 38//37 39//37 40//37
f 37//38 39//38 38//38
f 40//39 41//39 42//39
f 39//40 41//40 40//40
f 42//41 43//41 44//41
f 41//42 43//42 42//42
f 44//43 45//43 46//43
f 43//44 45//44 44//44
f 46//45 47//45 48//45
f 45//46 47//46 46//46
f 47//47 49//47 48//47
f 48//48 49//48 50//48
f 49//49 51//49 50//49
f 50//50 51//50 52//50
f 51//51 53//51 52//51
f 52//52 53//52 54//52
f 53//53 55//53 54//53
f 54//54 55//54 56//54
f 55//55 57//55 56//55
f 56//56 57//56 58//56
f 57//57 59//57 58//57
f 58//58 59//58 60//58
f 59//59 61//59 60//59
f 60//60 61//60 62//60
f 61//61 63//61 62//61
f 62//62 63//62 64//62
f 63//63 65//63 64//63
f 64//64 65//64 66//64
f 65//65 67//65 66//65
f 66//66 67//66 68//66
f 67//67 69//67 68//67
f 68//68 69//68 70//68
f 69//69 71//69 70//69
f 70//70 71//70 72//70
f 71//71 73//71 72//71
f 72//72 73//72 74//72
f 73//73 75//73 74//73
f 74//74 75//74 76//74
f 75//75 77//75 76//75
f 76//76 77//76 78//76
f 77//77 79//77 78//77
f 78//78 79//78 80//78
f 79//79 81//79 80//79
f 80//80 81//80 82//80
f 81//81 83//81 82//81
f 82//82 83//82 84//82
f 83//83 85//83 84//83
f 84//84 85//84 86//84
f 85//85 87//85 86//85
f 86//86 87//86 88//86
f 87//87 89//87 88//87
f 88//88 89//88 90//88
f 89//89 91//89 90//89
f 90//90 91//90 92//90
f 91//91 93//91 92//91
f 92//92 93//92 94//92
f 93//93 95//93 94//93
f 94//94 95//94 96//94
f 96//95 97//95 98//95
f 95//96 97//96 96//96
f 98//97 99//97 100//97
f 97//98 99//98 98//98
f 100//99 101//99 102//99
f 99//100 101//100 100//100
f 102//101 1//101 3//101
f 101//102 1//102 102//102
f 37//103 33//103 43//103
f 35//104 33//104 37//104
f 63//105 61//105 65//105
f 33//106 31//106 43//106
f 43//107 31//107 45//107
f 45//108 31//108 47//108
f 47//109 31//109 49//109
f 67//110 31//110 69//110
f 69//111 31//111 71//111
f 71//112 31//112 81//112
f 49//113 31//113 67//113
f 81//114 31//114 89//114
f 57//115 55//115 59//115
f 59//116 55//116 61//116
f 99//117 1//117 101//117
f 61//118 55//118 65//118
f 89//119 25//119 95//119
f 31//120 25//120 89//120
f 27//121 25//121 29//121
f 29//122 25//122 31//122
f 95//123 25//123 97//123
f 1//124 5//124 2//124
f 53//125 51//125 55//125
f 23//126 21//126 25//126
f 65//127 49//127 67//127
f 5//128 9//128 7//128
f 55//129 49//129 65//129
f 51//130 49//130 55//130
f 99//131 9//131 1//131
f 25//132 9//132 97//132
f 1//133 9//133 5//133
f 71//134 81//134 73//134
f 21//135 9//135 25//135
f 73//136 81//136 75//136
f 75//137 81//137 77//137
f 77//138 81//138 79//138
f 97//139 9//139 99//139
f 9//140 15//140 11//140
f 17//141 15//141 19//141
f 19//142 15//142 21//142
f 21//143 15//143 9//143
f 15//144 13//144 11//144
f 81//145 89//145 83//145
f 83//146 89//146 85//146
f 85//147 89//147 87//147
f 39//148 37//148 41//148
f 41//149 37//149 43//149
f 89//150 93//150 91//150
f 89//151 95//151 93//151
f 34//152 38//152 44//152
f 34//153 36//153 38//153
f 62//154 64//154 66//154
f 32//155 34//155 44//155
f 32//156 44//156 46//156
f 32//157 46//157 48//157
f 32//158 48//158 50//158
f 32//159 68//159 70//159
f 32//160 70//160 72//160
f 32//161 72//161 82//161
f 32//162 50//162 68//162
f 32//163 82//163 90//163
f 56//164 58//164 60//164
f 56//165 60//165 62//165
f 3//166 100//166 102//166
f 56//167 62//167 66//167
f 26//168 90//168 96//168
f 26//169 32//169 90//169
f 26//170 28//170 30//170
f 26//171 30//171 32//171
f 26//172 96//172 98//172
f 6//173 3//173 4//173
f 52//174 54//174 56//174
f 22//175 24//175 26//175
f 50//176 66//176 68//176
f 10//177 6//177 8//177
f 50//178 56//178 66//178
f 50//179 52//179 56//179
f 10//180 100//180 3//180
f 10//181 26//181 98//181
f 10//182 3//182 6//182
f 82//183 72//183 74//183
f 10//184 22//184 26//184
f 82//185 74//185 76//185
f 82//186 76//186 78//186
f 82//187 78//187 80//187
f 10//188 98//188 100//188
f 16//189 10//189 12//189
f 16//190 18//190 20//190
f 16//191 20//191 22//191
f 16//192 22//192 10//192
f 14//193 16//193 12//193
f 90//194 82//194 84//194
f 90//195 84//195 86//195
f 90//196 86//196 88//196
f 38//197 40//197 42//197
f 38//198 42//198 44//198
f 94//199 90//199 92//199
f 96//200 90//200 94//200

**Comment by mikedh** [comment]
Hey, it looks like the diagonal terms are pretty close (0.04%). The nondiagonal terms are *way* smaller (17 orders of magnitude) and are probably dominated by precision issues, I wouldn't expect these to match particularly well. It also looks like in FreeCAD that's an analytical cylinder it's doing the calculation on, versus the tesselated model trimesh is calculating against, which would explain the small deviation in diagonal terms. Trimesh is unit testing against [both analytical primitives and a few ground truth models](https://github.com/mikedh/trimesh/blob/51648530fac38212d8a6f791e6687539e05d33a9/tests/test_inertia.py) calculated in Solidworks. You could also compare the analytical cylinder inertia calculation from trimesh with what FreeCAD is returning:

```
In [1]: trimesh.inertia.cylinder_inertia?
Signature: trimesh.inertia.cylinder_inertia(mass, radius, height, transform=None)
Docstring:
Return the inertia tensor of a cylinder.

Parameters
------------
mass : float
  Mass of cylinder
radius : float
  Radius of cylinder
height : float
  Height of cylinder
transform : (4, 4) float
  Transformation of cylinder

Returns
------------
inertia : (3, 3) float
  Inertia tensor
File:      ~/trimesh/trimesh/inertia.py
Type:      function

```

**Comment by Ahorvath94** [comment]
Huh! That would make sense since trimesh is not analytical. 0.04% is good enough for me! Was just curious about the off-diagonal terms. Thanks for your help!
