### ISSUE TITLE
Possibility to retreive only the surface itersection of two objects.

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [mikedh/trimesh#127]
Hello,

I am very happy with trimesh but I was wondering if it was possible to add an option to retrieve only the surface intersection with the booleen transformation ?

At the moment if I run the following code:
```
import trimesh
mesh1 = trimesh.load_mesh('cube.ply')
mesh2 = trimesh.load_mesh('cylinder.ply')

mesh3 = mesh1.intersection(mesh2)
```
`mesh3` results in a cylinder when all I want to retrieve is a circle or ellipse.

Thanks for your consideration,

Anthony

**Comment by mikedh** [comment]
Hey Anthony- so if I understand correctly, you want the intersection curve between the two meshes, rather than the watertight result mesh. I think the easiest way to do that is probably to 'color' the faces that exist on one of the two meshes, and then take the boundary of that coloring:
```
b = trimesh.primitives.Box(extents=[1,1,1])
c = trimesh.primitives.Cylinder(radius=.25, height=10)

# run the intersection using SCAD, it is generally more reliable than blender
i = b.intersection(c, engine='scad')

# the distance from the result triangle center to the original mesh
distance = b.nearest.on_surface(i.triangles_center)[1]

# if it's basically zero the face on the intersection result belongs to the box
on_surface = np.abs(distance) < 1e-5

# get a Path3D object for the outline of the boundary
boundary = i.outline(face_ids=np.nonzero(on_surface)[0])

```

**Comment by Anthony-MostlyHarmless** [comment]
Great thanks, that worked :)

Small change as I wanted the surface and not the boundary I replaced:

`boundary = i.outline(face_ids=np.nonzero(on_surface)[0])`

by:

`i.faces = i.faces[on_surface]`
