### ISSUE TITLE
oriented_bounds does not return determinant one transform 

### ISSUE THREAD

**Issue by ze897c** [mikedh/trimesh#1283]
"rotation" block of "transform" from oriented_bounds has determinant == -1. this is problematic, if for no other reason than the transformed geometry would have incorrect normals. Perhaps this is the desired behavior if `ordered=True` ? If so, perhaps the docstring should state that.

```
% pip freeze | grep trimesh
trimesh==3.9.20
```

```
import numpy as np
from trimesh.bounds import oriented_bounds
from trimesh.primitives import Box

print(np.linalg.det(oriented_bounds(Box(extents=(5, 5, 5)))[0][:3, :3]))

if __name__ == '__main__':
    pass
```

**Comment by mikedh** [comment]
Good catch, that should be in unit tests. I suspect this block: https://github.com/mikedh/trimesh/blob/master/trimesh/bounds.py#L212-L228

**Comment by ze897c** [comment]
Thanks much! 

Love the lib, using all the time. Many thanks,
Matt
