### ISSUE TITLE
Add plane to scene

### ISSUE THREAD

**Issue by Kojon74** [mikedh/trimesh#1284]
How can I add a plane with specified normal and origin to a scene with a mesh?

I tried using:

```
plane = trimesh.primitives.Box(extents=[100, 100, 0], transform=[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
trimesh.Scene([mesh, plane]).show()
```

But I can't figure out how to set the origin of the box and how to set the normal?

**Comment by mikedh** [comment]
I would create the transform with `np.linalg.inv(trimesh.geometry.plane_transform(...)))`. `trimesh.path.creation.grid` might also be helpful, as it is a see-through plane indicator:

```
In [18]: import numpy as np

In [19]: T = np.linalg.inv(trimesh.geometry.plane_transform(origin=[0,0,1], normal=[0,0,1]))

In [20]: T
Out[20]: 
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [21]: trimesh.Scene([mesh, trimesh.path.creation.grid(side=2, transform=T)]).show()
```
