### ISSUE TITLE
Is there a way to concentrate sampling of points on a trimesh.base.Trimesh mesh?

### ISSUE THREAD

**Issue by hamid162** [mikedh/trimesh#1294]
Hello,

I am able to sample a trimesh.base.Trimesh mesh surface very well using trimesh.sample.sample_surface() or trimesh.sample.sample_surface_even(). However, these sample the entire surface near evenly. 

I have a mesh such as the one below, which I want to sample with points :
![coarse](https://user-images.githubusercontent.com/75090879/126529724-2a6feadb-cdf3-4337-8cc2-196cdc57feda.png)

I want to sample this surface with points very finely at the curved regions, such as the radii (areas with fine mesh in the figure) and to have less points on the flat surfaces.

In practice, my mesh looks something like this:
![fine](https://user-images.githubusercontent.com/75090879/126529975-00ac1e8a-5144-4b0b-b1c8-a6b0a05b2dc3.png)

where there are fine triangles everywhere (the first image was only shown for clarity).

Is there a way to selective sample more points where the geometry is curved, and few where the geometry is flat?

Thanks very much!

**Comment by mikedh** [comment]
Oh interesting, I think the easiest way to do that would be to add a `face_weights` field to `sample_surface` which I just added in a branch https://github.com/mikedh/trimesh/commit/1e2868a57e029096d5c3b43500026ff373ea6545. Then it seems like you could do something like:

```
n [28]: weights = np.abs(m.vertex_defects)[m.faces].sum(axis=1) ** 2

In [29]: points = m.sample(1000, face_weight=weights)

In [30]: trimesh.Scene([m, trimesh.PointCloud(points)]).show()
Out[30]: SceneViewer(width=1800, height=1350)

``` 

Although playing around with that briefly that weighing strategy looks a little screwy haha.  Might be worth giving that branch a shot! If you think that weighting functionality is useful and correct happy to merge it into master.

**Comment by hamid162** [comment]
Great, happy to give that a try. But I'm new to Github, how can I give that branch a go? I'm interested in testing it out on the geometry I showed in the 2nd figure, where the triangles are all approximately the same size (so I think the weights would be equal everywhere). It's only at highly curved areas such as radii is where I think it would be useful to sample more points

**Comment by mikedh** [comment]
No worries! [This tutorial](https://adamtheautomator.com/git-checkout-remote-branch/) might be helpful.

**Comment by coolioo62** [comment]
Hi, how exactly can I achieve a mesh with 'fine triangles everywhere' like the second pic @hamid162 posted? Tried using trimesh.sample.sample_surface_even() on my STL object but the result doesn't even come close. I'm new to coding in general, so I would really appreciate an exemplary code snippet!

**Comment by mikedh** [comment]
Hey, you might try `trimesh.remesh.subdivide_to_size`, although keep in mind that that does not maintain the correct edge topology or look nearly as good as that example haha (PR's welcome!). 

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/rabbit.obj')

In [7]: m.show()
Out[7]: SceneViewer(width=1800, height=1350)

In [8]: m.extents
Out[8]: array([2.002612 , 4.4136064, 3.14     ])

In [19]: s = m.subdivide_to_size(m.extents.min() / 4)

In [20]: s.show()
Out[20]: SceneViewer(width=1800, height=1350)
```
![Screenshot from 2024-02-15 14-55-54](https://github.com/mikedh/trimesh/assets/1403074/8d93cf53-fe02-4116-9e3a-19cbb27815fc)
After subdivision:
![Screenshot from 2024-02-15 14-57-18](https://github.com/mikedh/trimesh/assets/1403074/ef7ba030-cc31-4061-a8d4-8b3501dde595)
