### ISSUE TITLE
compatibility with python 3.3.2

### ISSUE THREAD

**Issue by AlexLee** [mikedh/trimesh#13]
@mikedh I am currently using a virtual environment for Python 3.3.2 with Anaconda on windows 7. How could I set up trimesh to be compatible with Python 3.3.2? https://docs.continuum.io/anaconda/old-pkg-lists/2.3.0/py33

I installed trimesh via pip but I wasn't able to get it to work with my Anaconda python 3.3 virtual environment

**Comment by mikedh** [comment]
Hey Alex, could you copy/paste the error you were seeing from trimesh on either installation or import?

**Comment by AlexLee** [comment]
Hi Mike, thanks for the follow up. I am using a 3D cad modeling program and simply typing `import trimesh` causes it to lock up. There is no error message. It could very well be an issue with the 3D CAD program itself since I have had issues getting other libraries to work with it. When I have more time, I would like to help port this library to Python3.

**Comment by mikedh** [comment]
Gotcha. So trimesh runs on python3, the unit tests are run on 3.3-3.5 (https://travis-ci.org/mikedh/trimesh). If its failing on import its probably a dependency issue; did you try importing numpy or networkx by themselves in this environment? I'm going to close this for now.
