### ISSUE TITLE
If rotation matrix had angle 0, then transformation will result in NaN

### ISSUE THREAD

**Issue by sataset** [mikedh/trimesh#1306]
So if rotation matrix will be constructed through trimesh method with `angle = 0`, then resulting transformation will contain NaN for point transformations.

https://github.com/mikedh/trimesh/blob/e2b5c1a1f3f3ce4b49f54d80fed35ffb8e8dc757/trimesh/transformations.py#L2097

**Comment by mikedh** [comment]
I think this happens for `direction` with a zero magnitude, not angle:

```
In [4]: trimesh.transformations.rotation_matrix?

In [5]: trimesh.transformations.rotation_matrix(angle=0, direction=[1
   ...: ,0,0])
Out[5]: 
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]: trimesh.transformations.rotation_matrix(angle=0, direction=[0 ,0,0])
/media/psf/Home/Dropbox/robotics/trimesh/trimesh/transformations.py:1828: RuntimeWarning: invalid value encountered in true_divide
  data /= math.sqrt(np.dot(data, data))
Out[6]: 
array([[nan, nan, nan,  0.],
       [nan, nan, nan,  0.],
       [nan, nan, nan,  0.],
       [ 0.,  0.,  0.,  1.]])

```
Is that what you're seeing? Yeah it probably should raise an exception rather than just printing a `RuntimeWarning`.

**Comment by sataset** [comment]
Thank you for your answer.

That is right. My mistake, I have been calculating axis of rotation using two vectors which appear to be the same (thus `angle = 0`).
