### ISSUE TITLE
Type of file readable by viewer

### ISSUE THREAD

**Issue by JPFrancoia** [mikedh/trimesh#132]
Hi,

This is not an issue with trimesh itself. I would like to use trimesh's viewer (base on pyglet) to view OpenSCAD CSG files (Constructive solid geometry). Do you think it's possible ?

If so, would it require a lot of work ?

Here is an example of CSG file:

[test.csg.txt](https://github.com/mikedh/trimesh/files/1694836/test.csg.txt)

**Comment by mikedh** [comment]
So the SCAD files would have to be evaluated by SCAD, and then the resulting mesh returned. There's already an [interface](https://github.com/mikedh/trimesh/blob/master/trimesh/interfaces/scad.py) in trimesh to call SCAD (it's one of the boolean backends) so it probably wouldn't be too hard to use that to evaluate other CSG files.

**Comment by JPFrancoia** [comment]
Thanks for your answer.

Yes I can also call OpenSCAD in CLI to evaluate a SCAD file, and get a CSG file. What I don't want to do is to call OpenSCAD to render the mesh to a STL file, it takes ages. "Rendering" to a CSG file is quite fast.

But I don't know if a CSG file can be qualified as a mesh file (and viewed in the viewer).

**Comment by mikedh** [comment]
Ah- yeah the slow part is evaluating the boolean operations to generate a mesh. You could possibly visualize the constituent primitives faster by parsing the file and assigning them to trimesh.primitive objects, but if you want the resulting geometry the only way to get it is to have SCAD or some other backend (which will probably not be faster than SCAD) evaluate the logic in the file.

**Comment by JPFrancoia** [comment]
I'm fine with visualizing (fast) !

To give you more details about what I'm trying to do: I have "complex" scripts that generate scad files. I need a viewer for these scad files that I can embed into a pyqt application (I can preview them with OpenSCAD, but I can't embed openscad in a pyqt application). And I know pyglet can be integrated with pyqt.

I can of course call openscad to render/preview an image of a scad file, and I can display this image in my pyqt application. But I'd like to be able to view my object from different angles, like in your viewer (you can rotate the object in 3D).

So do you think I could use trimesh to evaluate a CSG file to display it with pyglet ?

**Comment by mikedh** [comment]
I think its going to be a lot of work to parse that kind of file correctly even to generate a non- subtracted version of the result. You could find all the cylinder primitives with a regex and then generate a transform tree, but even that would be a ton of work. I'm not sure cutting SCAD out for this kind of file is practical- you might see if you can embed a binary, or get a meshed result some other way.

Best,
Mike

**Comment by JPFrancoia** [comment]
Sorry, I always forget to close my issues. Yeah it's not exactly what I'm looking for. I'll render the stl with openscad and embed pyglet in my app for visualization. It's slow but it will work.

I'll look at free cad to see how they deal with scad files.

Thanks for the suggestions anyway.

**Comment by mikedh** [comment]
No worries! That sounds like a pretty reasonable solution.

**Comment by JPFrancoia** [comment]
I'd like your opinion.

The problem with Openscad right now is that it's not multi-thread. So if I have a big object to render, only one thread will be used, making the rendering slow.

However, the designs I make are modular (i.e., I can get a .scad file for each of the part of a big assembly). So I can probably render a stl file for each of my module with openscad, in separate threads.

I'll then have several stl files. Do you think I can merge them into a final stl file for the big assembly, without loosing the coordinates of each module ?

**Comment by JPFrancoia** [comment]
Ok, it actually works. It's possible to merge several stl files into one without loosing coordinates. I just made openscad multi-thread. Sort of.

**Comment by mikedh** [comment]
Hahah nice, through multiprocessing?

**Comment by JPFrancoia** [comment]
Yes. My designs are made of modules that I generate programatically. These modules each generate a scad file. So I call openscad in a thread for each of the scad files, to render the stl files. And then I merge all the stl files.

It's actually quite simple, it's worth keeping it in mind if a design in openscad can be split in different files.
