### ISSUE TITLE
Creating trimesh primitive (Sphere) with a specific r and the point

### ISSUE THREAD

**Issue by bernakabadayi** [mikedh/trimesh#1323]
Hi,

when I create a primitive Sphere with a specific r and point, it always creates a sphere with r = 1 and at the origin. As a solution, I used the apply_transform function and specify a T but wondering if that init works.

```
base_sphere = trimesh.primitives.Sphere(r, (x0,y0,z0))
```

Best
Berna

**Comment by mikedh** [comment]
Yeah, you can pass the `center` kwarg:

```
In [6]: m = trimesh.primitives.Sphere(radius=1.0, center=[0,0,1])

In [7]: m.centroid
DEBUG        primitives.py:488   creating mesh for Sphere primitive
DEBUG              base.py:360   generating face normals
Out[7]: array([-0.,  0.,  1.])
```

**Comment by bernakabadayi** [comment]
realized that it was due to jupyter kernel, it worked! thanks
