### ISSUE TITLE
Question: can Trimesh handle mesh erosion by another mesh along a 3d path?

### ISSUE THREAD

**Issue by TheophileLebrun** [mikedh/trimesh#1325]
Dear all,

I am looking for a way to obtain the theoretical result of a CNC milling process and I thought of the following approach:

end result mesh / machined part = stock material mesh - cutting tool 3d geometry extruded along a 3d path.

would there be some features of Trimesh that would allow me to perform this task ? Or are there other frameworks more suitable for this task?

Best regards
Theophile

**Comment by mikedh** [comment]
Hey, yeah you could do that through mesh booleans, although they are extremely slow and unreliable. I think a voxelized approach would probably work better, you could check out `trimesh.voxel`. [opencamlib](https://github.com/aewallin/opencamlib) uses an octree approach, which allows higher resolution but is a lot more fiddly.

**Comment by TheophileLebrun** [comment]
thanks for the feedback!
I will try those approaches
