### ISSUE TITLE
Slice mesh using non-linear plane

### ISSUE THREAD

**Issue by Kojon74** [mikedh/trimesh#1326]
Hi, thanks again for this awesome library.

I'm wondering if it's possible to slice a mesh using a non-linear plane (oxymoron?).

For example, I have some non linear line, say a quadratic, and I want to extrude that line into the Z direction and use it as a plane to slice my mesh along.

Please let me know if I can clarify anything!

**Comment by mikedh** [comment]
Hey, yeah not implemented currently but would be cool! The general case would basically be a mesh boolean (which trimesh does run via blender or openSCAD), but those are indeed slow and unreliable. I think you'd have to implement it for a bunch of different surface types? e.g.:

- plane (extruded/revolved perpendicular line)
- cylinder (extruded circle/revolved parallel line)
- torroid (revolved circle)
- nurbs surface (most general; you can probably represent all the above as a nurbs patch). 

Heh that would be well on the way to implementing an actual BREP CAD kernel 😄

**Comment by Kojon74** [comment]
Thanks, I may just try and use multiple tangential planes instead to try and recreate the non-linear plane. 

Is there a way to use a finite plane instead of an infinite plane to slice meshes (eg set bounds for the plane being used to slice)?

**Comment by mikedh** [comment]
> Is there a way to use a finite plane instead of an infinite plane to slice meshes (eg set bounds for the plane being used to slice)?

Not implemented currently, this would basically require point-in-polygon checks and some handling at the boundary.
