### ISSUE TITLE
GLB texture regression since 3.9.21 release

### ISSUE THREAD

**Issue by 987123879113** [mikedh/trimesh#1329]
Between 3.9.20 and 3.9.21 something changed such that the UVs are getting trashed when exporting GLB files. Based on the release log for 3.9.21, I narrowed down the problem PR to https://github.com/mikedh/trimesh/pull/1246. The issue no longer occurs when this specific PR is reverted.

In particular, it seems the part where it's trying to update the vertices and faces is the exact point of failure (https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/gltf.py#L838-L847). I don't understand exactly what was intended with this code so I am not comfortable submitting a fix for this, but reverting it back to using `mesh.vertices` and `mesh.faces` fixes the problem from my limited testing.

Steps to reproduce:
- Load model with texture
- Export same glb file with texture again
- View newly exported glb and the UVs will be trashed

Code for reproduction:
```python
    data = trimesh.load("untitled.glb").export(file_type="glb")
    open("output.glb", "wb").write(data)
```

**Comment by mikedh** [comment]
Thanks for the report! Yeah I thought I saw something weird with this a few weeks ago, thanks for tracking it down. Seems like CI should have been howling about this, although a simple trivial example passes:

```
    m = trimesh.load('models/fuze.obj')

    r = trimesh.load(file_obj=trimesh.util.wrap_as_stream(m.export(file_type='glb')),
                     file_type='glb')
    b = next(iter(r.geometry.values()))

    # works fine
    assert np.allclose(b.visual.uv, m.visual.uv)
```

If you have a minimal test that fails that would be super helpful!

**Comment by mikedh** [comment]
Actually this fails which it really seems like it shouldn't:
```
    m = trimesh.load('models/fuze.obj')
    r = trimesh.load(
        file_obj=trimesh.util.wrap_as_stream(
            m.export(file_type='glb')),
        file_type='glb', process=False)
    b = next(iter(r.geometry.values()))

    # works
    assert np.allclose(b.visual.uv, m.visual.uv)
    # both fail
    assert np.allclose(b.vertices, m.vertices)
    assert np.allclose(b.faces, m.faces)

```

**Comment by 987123879113** [comment]
Here's a model of Suzanne with a blue to yellow gradient texture. I've also included a broken re-exported model of the same suzanne.glb using the exact command from my first post for comparison.

[suzanne.zip](https://github.com/mikedh/trimesh/files/7010977/suzanne.zip)

Good UVs:
![image](https://user-images.githubusercontent.com/63495610/129990664-39f6810a-ab17-4c1f-8485-afb047014380.png)


Bad UVs:
![image](https://user-images.githubusercontent.com/63495610/129990655-35e15baa-413c-4410-8826-f03fe375f536.png)

**Comment by mikedh** [comment]
Yeah, I think the easiest thing to do for now is to partially revert that change. To verify it doesn't happen again code blocks we can run in unit tests would be super welcome (i.e. self-contained code with statements that will automatically fail like `assert textureOk`). Not sure the best way to automate that check... maybe KDTrees on uv/face/vertices or something.  

Thanks for the report!

**Comment by mikedh** [comment]
Release should be up on pypi now, let me know if it doesn't fix this issue for you.

**Comment by 987123879113** [comment]
I tested 3.9.29 and it looks good to me now. Thanks!
