### ISSUE TITLE
Overwriting mesh COM 

### ISSUE THREAD

**Issue by shivanimall** [mikedh/trimesh#1333]
Hello @mikedh,

I loaded google scanned objects in pybullet, and It seems like the COM of these objects is not the geometric COM, instead is at the bottom of the object, which leads to wobbly behaviour such that the object never falls down after a failed grasp with a jaw gripper

1. trimesh gives access to COM of the mesh object, would overwriting it with geometric COM work to avoid the wobbliness issue?

2. Are there any known solutions to fix this issue?

**Comment by mikedh** [comment]
Hey, yeah the `mesh.center_mass` value may be unreliable if the mesh isn't watertight as it's evaluating a surface integral. `mesh.centroid` is the area-weighted average of triangle centers that is usually reasonable even on triangle soups. You could also do `mesh.convex_hull.center_mass` for the convex hull which is pretty robust except for a few edge cases (all points are the same, or on a plane).

**Comment by shivanimall** [comment]
Hi @mikedh, 
I did the following, however, the wobbliness issues persists, that is an unstable grasp is not causing the object to fall down. 
```
1. print("obj- ", pb.getAABB(objID))
2. touch_obj_mesh = trimesh.load_mesh("model.obj", process=False, force='mesh')
3. print("COM -- ", touch_obj_mesh.convex_hull.center_mass)
4. touch_obj_mesh.convex_hull.center_mass = [geometric_com_x, geometric_com_y, geometric_com_z]
```

here in line 4, I replaced the COM with geometric mean from line 1.
