### ISSUE TITLE
K- nearest neighbors of a geometry in the scene

### ISSUE THREAD

**Issue by Hassan-math** [mikedh/trimesh#1341]
Hi,

Suppose I have a set of geometries (saying all of them are spheres) in the trimesh scene. I'm going to select one of them (e.g. the first one) by ` scene.graph.nodes_geometry[0]` and find the K nearest neighbours geometries (or spheres) to the selected geometry. Is there any way to do it by trimesh?

**Comment by mikedh** [comment]
Yeah I'd recommend computing the AABB of every instance, and then using `rtree` (or just use centroids and `scipy.spatial.cKDTree`). `trimesh.scene.Scene.bounds_corners` is probably a good thing to look at to get started.
