### ISSUE TITLE
How to select polygons belonging to holes in a STL slice data?

### ISSUE THREAD

**Issue by Vysakh5391** [mikedh/trimesh#1342]
Hi!

I have an STL file for 3D printing and have sliced it. 

```
import trimesh
# load mesh
mesh = trimesh.load('test_part.stl', merge_norm=True, merge_tex=True)

# slice the mesh
slice = mesh.section_multiplane(plane_origin=[0,0,0], plane_normal=[0,0,1], heights=[0.25, 0.5])
```
I am interested in only selecting the paths that belong to holes in the slice data.

I read from another issue #11 that the `enclose_directed` attribute for each slice has this information. I am new to Python programming and would like to know if there is an easy way to use this attribute or any other approach in `trimesh` to achieve this.

To be precise, I am attaching an image of the kind of information I am looking for. The google drive link to the STL file of the part is also attached here. I am looking to extract polygons B, C <D, E>, F, G, J. The interesting part of C is that the hole region is C - (D + E).

![github_trimesh_pic](https://user-images.githubusercontent.com/47824150/132332451-5e2e539c-3a55-4ccb-ae48-bed3d064d957.png)

https://drive.google.com/file/d/1PcKYWSi_ymkVW-UT7HR_KRY5pzSIkpGk/view?usp=sharing

Looking forward to a response!

**Comment by Vysakh5391** [comment]
I did some reading and was able to find a better way to put this question.

In the figure above, contour C (which is an interior contour) contains two exterior contours D and E. My aim is to sample points inside region C that do not cover regions D and E. Up until now, I have found a way to get the interior 'ring' or path and convert it into a polygon using `shapely`. I am confused as to what would happen if the interior ring had one or more exterior rings within it.

I am tagging @mikedh due to the urgency of this issue. I would help me a great deal if there is something within ` shapely `or `trimesh `that solves this efficiently.

Thank you!

**Comment by mikedh** [comment]
I think basically what you want is `path.enclosure_directed.degree`: the root curve will have degree `0`, the first level `1`, etc. Also `path.split` is degree aware and will produce the result in your picture:

```
In [2]: p.enclosure_directed?
Type:        property
String form: <property object at 0x7f10a8e8cc20>
Docstring:  
Directed graph of polygon enclosure.

Returns
----------
enclosure_directed : networkx.DiGraph
  Directed graph: child nodes are fully
  contained by their parent node.

In [3]: p.enclosure_directed
Out[3]: <networkx.classes.digraph.DiGraph at 0x7f10a5b003a0>

In [4]: p.enclosure_directed.degree
Out[4]: DiDegreeView({0: 2, 1: 1, 4: 1, 5: 2, 7: 1, 9: 1, 6: 1, 3: 1, 2: 0, 8: 0})

In [5]: 

In [5]: 

In [5]: p.enclosure_directed.degree
Out[5]: DiDegreeView({0: 2, 1: 1, 4: 1, 5: 2, 7: 1, 9: 1, 6: 1, 3: 1, 2: 0, 8: 0})

In [6]: p.show()
DEBUG    selector_events.py:59    Using selector: InputHookSelector

In [7]: p.split()
Out[7]: 
array([<trimesh.Path2D(vertices.shape=(98, 2), len(entities)=3)>,
       <trimesh.Path2D(vertices.shape=(98, 2), len(entities)=1)>,
       <trimesh.Path2D(vertices.shape=(98, 2), len(entities)=3)>,
       <trimesh.Path2D(vertices.shape=(98, 2), len(entities)=2)>,
       <trimesh.Path2D(vertices.shape=(98, 2), len(entities)=1)>],
      dtype=object)

```

**Comment by Vysakh5391** [comment]
Oh! I will try this out and keep you posted. Thank you so much @mikedh for the response. I am fairly new to python programming and `trimesh`. I will have to read up on `networkx `documentation to make sense of the information embedded in `p.enclousure_directed`

If it is a single interior ring/contour, it is easy to sample points inside, for example, contours B and J. Problem arises when sampling points inside C because D and E are solids. All in all, I am looking to sample points inside the STL layer that does not lie on the layer but lie inside those polygons (entrapped). This is going to represent entrapped water particles in that layer, kinda like this picture, but with more dense red points.

![github_pic2](https://user-images.githubusercontent.com/47824150/132423187-b895722e-0857-4758-8950-96b2e772fed2.png)

Thanks!

**Comment by mikedh** [comment]
No worries, I think `path.split` might be the easiest way to do that: 
```
import trimesh
import numpy as np

import matplotlib.pyplot as plt

trimesh.util.attach_to_log()

if __name__ == '__main__':

    # load mesh
    mesh = trimesh.load('test_part.stl', merge_norm=True, merge_tex=True)

    # slice the mesh
    s = mesh.section_multiplane(
        plane_origin=[
            0, 0, 0], plane_normal=[
            0, 0, 1], heights=[
                0.25, 0.5])

    path = s[0]
    splits = path.split()
    for split in splits:
        poly = split.polygons_full[0]
        plt.scatter(*trimesh.path.polygons.sample(poly, count=200).T)

    path.show()
```
![islands](https://user-images.githubusercontent.com/1403074/132423822-728f3d1c-606d-4545-957e-7b3f628eaf79.png)

**Comment by Vysakh5391** [comment]
Hi! I was able to identify the inner polygons and also include the outer polygons that lie within the inner polygons.

Basically, I checked whether any outer polygon (OP) whose area is less than the current inner polygons (IP) lies inside IP using the `contains` function in shapely. I do not know any edges cases where my approach would fail. Please let me know if you can think of any.

Here is the code for sampling points inside the IP 'C' avoiding OP 'D' and 'E'. (Please refer to the image above to make sense of the contour labels.) Also, I will appreciate it if you can point out any tips for programming this more efficiently.

```
from shapely.geometry import Polygon, MultiPolygon
import trimesh
import numpy as np
import pyvista as pv

# import the stl file
mesh = trimesh.load('test_tree.stl', merge_norm=True, merge_tex=True)

# slice the stl file
s = mesh.section_multiplane(plane_origin=[0, 0, 0], plane_normal=[0, 0, 1], heights=[0.25, 0.5])
path = s[0] # take one slice for current consideration
splits = path.split() # split the slice into polygons
# '''
# the .split() command is degree aware, means it divides the slices into a set of exterior rings (polygons) with interior
# embedded within each of them
# Our task is to sample points inside the interior rings and leave out the exterior rings
# '''

# sample points inside the interior rings avoiding the exterior rings
# the .sample() command seems to sample points inside an exterior polygon leaving the interiors
# select the outer polygons

# splitting a slice into separate lists of exterior and interior polygons
exterior_poly = []
interior_poly = []
for split in splits:
    num_poly = len(split.polygons_full) # I think this will be always one; but just to be safe
    for k in range(num_poly):
        poly = split.polygons_full[k]
        exterior_poly.append(Polygon(poly.exterior))
        num_interior_poly = len(poly.interiors)
        for m in range(num_interior_poly):
            interior_poly.append(Polygon(poly.interiors[m]))
print('There are', format(len(exterior_poly)), 'exterior polygons in this slice')
print('There are', format(len(interior_poly)), 'interior polygons in this slice')

# get areas of all the exterior polygons
ext_poly_A = np.asarray([x.area for x in exterior_poly])
print(ext_poly_A)

# for an interior polygon, find the exterior polygon that lies within it
# the idea is to check using the shapely .contains() function to see if the exterior polygon lies inside the interior
# polygons
# To reduce blind checking, for an interior polygon, we will be only checking exterior polygons whose area is less
# the interior polygon in the current consideration (TODO: CAN STREAMLINE THIS SEARCH FURTHER BY USING AN RTREE TO AVOID ALL THE SMALLER AREA POLYGONS THAT LIE FAR AWAY FROM THE INTERIOR POLYGON)

# before the for loop, let's try for one interior polygon
curr_interior_poly = interior_poly[1]
# find exterior polygon indices whose area is less than the current interior polygon area
ext_poly_IDs = np.argwhere(ext_poly_A < curr_interior_poly.area).flatten()


# check if exterior polygon whose ID is shown in ext_poly_ID contains inside the curr_interior_poly
# contain_bool = []
contain_bool = np.asarray([curr_interior_poly.contains(exterior_poly[x]) for x in ext_poly_IDs]).flatten()

# if contain_bool is False, then the exterior polygon does not lie inside the interior polygon, so
# we can go ahead and sample the points
n_pow_PTS = 20000
powder_points = np.zeros((n_pow_PTS * len(interior_poly), 2), dtype=float)
new_interior_poly = []
for i in range(contain_bool.shape[0]):
    tmp_bool_val = contain_bool[i]
    if tmp_bool_val == False:
        continue
    else:
        new_interior_poly.append(exterior_poly[ext_poly_IDs[i]]) # adding outer polygons as inner polygons 

# create a Multipolygon (in Shapely)
poly_list = [curr_interior_poly]+[new_interior_poly]

poly = MultiPolygon(i for i in poly_list)
sample_points = trimesh.path.polygons.sample(poly, count=n_pow_PTS)

z_array = np.ones((sample_points.shape[0], 1)) * 0.25 # appending a z-coordinate to the 2D points

sample_points = np.hstack((sample_points, z_array))

# pyvista plotter
p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.add_points(sample_points, color='cyan')
p.show()
```

**Comment by Vysakh5391** [comment]
On the same note, I noticed that when I sample points inside the polygon, some points are sampled on the polygon edges.

Is there a way to remove such points? My eventual goal is to apply a ray tracing operation to check if the sample points intersect the stl facets. Points on the polygon will result in an incorrect analysis. I feel like there is an easy way in `trimesh `to do this. Could you please advise me on this? 

@mikedh Can thank you enough for all your suggestions!
