### ISSUE TITLE
Faster slicing operation based on `mesh.section_multiplane()`

### ISSUE THREAD

**Issue by Vysakh5391** [mikedh/trimesh#1347]
Hi!

Is there a faster/more efficient way to get mesh slices using `mesh.section_multiplane` ? Something that utilizes the GPU or other parallel processing capabilities. Since each slice is independent of the other, I would assume that it is possible.

I am required to obtain slices of a large STL mesh in minimal time. Any suggestions are highly appreciated.

Thanks in advance!

**Comment by mikedh** [comment]
Hey, always fun trying to speed things up, and PR's welcome!

- is it too slow currently? It's already decently fast given that it's pretty much 100% vectorized numpy operations
- try running your test script with [pyinstrument](https://github.com/joerick/pyinstrument]) profiling and see what's slow specifically, and then try to tune the slow calls: 
```
profiler = pyinstrument.Profiler()
with profiler:
    # do some work here...
print(profiler.output_text())
```

- if all of that fails, I'd try copy-pasting `trimesh/intersections.py` into a cython project, maybe using [triangle](https://github.com/drufat/triangle) as a starting point. 
- maybe try some accelerators like numba, dask(?), pytorch, etc? Not sure which if any of these apply here. 
- try benchmarking trimesh against other slicers? cura, slic3er, etc?

**Comment by Vysakh5391** [comment]
Hi @mikedh,

I tried benchmarking `trimesh` slicing against Cura's slicer. Cura's slicer is considerably faster than `trimesh`. Since it is mentioned on the trimesh homepage that Cura uses trimesh, is it possible for me to call Cura's slicing function within my python script? 

As for trimesh's slicing, I am using the `section_multiplane` function. I noticed that the `intersections.mesh_multiplane` is fast even for very complex geometries. The problem arises in `load_path` where it converts the lines into Path2D objects. It takes lot of time to convert complex slices to Path objects. Do you think there is a way to speed this up? Or am I missing something here?

Any help will be really appreciated! Thank you!
