### ISSUE TITLE
Update geometries' positions in the scene using 'callback'

### ISSUE THREAD

**Issue by Hassan-math** [mikedh/trimesh#1348]
Hi,

I've created some geometries (e.g. some spheres) in the scene and put them in the `scene` list.  I use `scene.show()` to visualize them. But how can I update their position in each frame to make a simple animation? I had a look at your example file `viewcallback.py`, but this code is applying transformation on the geometries. How can I manually update the geometries' positions (spheres' centers) in the scene using the `callback` function?

For example, I take a one of spheres:
`node = scene.graph.nodes_geometry[1]`
then I want to update its center using:
`scene.geometry[node].primitive.center = My_defined_postion`
`My_defined_position` is (3,) array that is being updated in each frame.

**Comment by mikedh** [comment]
Hey, yeah I think you want to just set a position using a `trimesh.transformations.translation_matrix(center)`. 

If you want to actually move the vertices

**Comment by Hassan-math** [comment]
Hey,

Thanks for your reply,
I could resolve it by using "translation matrix".

Regards,
Hassan
