### ISSUE TITLE
Documentation webpage format

### ISSUE THREAD

**Issue by Vysakh5391** [mikedh/trimesh#1349]
I think there is some issue with the `trimesh` documentation webpage. I don't know if it is my browser issue. I am using Chrome. Anyway, the usability has been adversely affected due to this. Could you please take a look at this? Thank you! 

It looks like this-

![image](https://user-images.githubusercontent.com/47824150/134185485-b14df4c5-be1e-4977-b8e5-9fc852464d7e.png)

**Comment by Vysakh5391** [comment]
I think the documentation webpage issue has been fixed. So I am closing this issue. Thank you!

**Comment by mikedh** [comment]
Yeah someone upstream (sphinx or sphinx-rtd probably) did a release that changed configuration arguments, I updated them and it looks fixed. Thanks for the report!
