### ISSUE TITLE
Texture indices not aligned to face indices

### ISSUE THREAD

**Issue by feketeimre** [mikedh/trimesh#135]
While parsing an OBJ file, the texture coordinates are indexed immediately: https://github.com/mikedh/trimesh/blob/952d3807849646595fb892d39d75ec8010c3b157/trimesh/io/wavefront.py#L87-L89
and then put in the metadata:
https://github.com/mikedh/trimesh/blob/952d3807849646595fb892d39d75ec8010c3b157/trimesh/io/wavefront.py#L44-L46
The vertex coordinates and the faces are passed to Trimesh object. Later _validate_face_normals and update_faces are called that mixes up the face indices. Due to this the face indices not match the texture indices (that has been already indexed), obviously it renders a bad texture:
![bug](https://user-images.githubusercontent.com/15861028/36079625-80949478-0f85-11e8-853b-1aca666aae6b.png)

Not sure what would be an easy way to keep the changes of the face indices the same with the texture coordinate indices. It could start by storing the texture coordinates and texture coordinate indices separately in metadata.

**Comment by mikedh** [comment]
Ah, there were some very [recent changes](https://github.com/mikedh/trimesh/issues/134) that may effect this (meshes have face validation off by default). Could you try doing a `pip install -U trimesh` and see if that helps? 

Texture is only kind of supported- probably the way this should work is meshes loaded with texture should have its `mesh.visual` object be a `TexturedVisual` rather than a `ColorVisual`, which could then support update_faces properly.

How are you rendering by the way, looks good (at least the non- mangled one 😁)?

**Comment by feketeimre** [comment]
I updated, but the problem still exits, the face indices change differently. A render of it for your viewing pleasure:
![bug2](https://user-images.githubusercontent.com/15861028/36080174-6cf21272-0f8c-11e8-965b-26fe86f2d6d5.png)

Ill take a little more time familiarizing myself with update_faces, and what really happens.

For rendering i use the [pyqtgraph ](https://github.com/pyqtgraph/pyqtgraph ) system. It doesnt support texturing either, i hacked together a simple display that does it.

**Comment by feketeimre** [comment]
whops

**Comment by mikedh** [comment]
Hey I may have time to mess with this in the next couple days- would you be able to provide a minimal working demo that shows this? If you don't want to publish it feel free to email me, my gmail is mik3dh

It's also possible the recent order- preserving changes in https://github.com/mikedh/trimesh/commit/c019a25874fec33ca6ec3094621743711a29623f fixed this.

**Comment by mikedh** [comment]
No worries, thanks for putting it together!

**Comment by feketeimre** [comment]
You can find the changes here https://github.com/feketeimre/trimesh/commit/d24a32a18b59ba5394778ff66555d866c6e9d851
Its pretty messy, not sure if it helps at all.

**Comment by mikedh** [comment]
Thanks that’s helpful!

**Comment by mikedh** [comment]
Consolidating all texture issues into #218
