### ISSUE TITLE
Mesh Intersection using Blender fails when the Blender default scene has been modified

### ISSUE THREAD

**Issue by dvicini** [mikedh/trimesh#136]
Hi,

There is a bug in the mesh intersection (trimesh.boolean.intersect). While everything works well out of the box, the mesh intersection fails with a ValueError exception when I modify the default scene in Blender (I removed the standard cube which shows when starting up Blender). This is very unexpected behaviour and was difficult to track down. I guess the error also affects other operations which use the `blender.py.template` script.

The problem seems to come from the line 17 in `blender.py.template:`
` bpy.ops.object.mode_set(mode='OBJECT')`

This line fails with an error if no geometric object is present in the scene. More precisely, it seems to be related how Blender handles deletion of objects. I.e. it fails when I delete the default cube and try to run this line right after. However, when I actively select and deselect e.g. the camera, it works. So this might be a Blender bug, but still it would be good if trimesh would have some workaround :)

Thanks,
Delio

**Comment by mikedh** [comment]
Ah, interesting- would simply wrapping the mode set in a try block work? IE:

```
  try:
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=True)
  except:
    pass
```

Best,
Mike

**Comment by dvicini** [comment]
Yes, that should do the trick I think 

Delio

**Comment by mikedh** [comment]
Looks like the build finished, let me know if that fixed the issue:
`pip install -U trimesh`

**Comment by dvicini** [comment]
It does not seem to work yet.
Could the problem be that you wrapped the two lines following the mode select?
I.e. if the mode select fails, nothing gets deleted

**Comment by mikedh** [comment]
Yeah, I assumed you didn't need to select all and delete if the `mode_set` failed. Wrapping just the `mode_set` works with an empty default scene, and the build should finish shortly.

**Comment by mikedh** [comment]
Closing for now- feel free to reopen if the fix in https://github.com/mikedh/trimesh/commit/e2042fcda8ca4dc15f502f69b39e420cc1a2eb43 didn't resolve this.
