### ISSUE TITLE
Looking for a simple example of a viewer with flags, e.g. 'wireframe'

### ISSUE THREAD

**Issue by pauljurczak** [mikedh/trimesh#1365]
I'm a Python beginner and I run into problems understanding deep nestled import tree in trimesh. I'm trying to add some flags to the basic `show()` call. I would like to have wireframe, axis, etc., but I'm stuck at not finding proper names for classes and functions, e.g. `trimesh.viewer.windowed.SceneViewer`. This code snippet:
```
import trimesh, pyglet

mesh = trimesh.creation.cylinder(1, height=1)
scene = trimesh.Scene([mesh])
viewer = trimesh.viewer.windowed.SceneViewer(scene, flags='wireframe')
viewer.show()
```
fails with:
```
  File "/home/paul/upwork/pick/code/test-trimesh.py", line 5, in <module>
    viewer = trimesh.viewer.windowed.SceneViewer(scene, flags='wireframe')
AttributeError: module 'trimesh' has no attribute 'viewer'
```
How do I import  `trimesh.viewer.windowed.SceneViewer`? Are there any examples? Is there an axis display flag?

**Comment by pauljurczak** [comment]
`modulefinder` prints `viewer.SceneViewer imported from trimesh.scene.scene`, but
```
viewer = trimesh.scene.scene.viewer.windowed.SceneViewer(scene, flags='wireframe')
```
gives me
```
AttributeError: module 'trimesh.scene.scene' has no attribute 'viewer'
```

**Comment by mikedh** [comment]
Hey, the easiest way to do that is probably to pass the kwargs to the `mesh.show` or `scene.show` call, as the kwargs to those calls get passed through to `SceneViewer.__init__`:

```
In [1]: import trimesh

In [2]: from trimesh.viewer.windowed import SceneViewer

In [3]: m = trimesh.creation.box()

In [4]: m
Out[4]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [5]: m.show(flags={'wireframe': True})
Out[5]: SceneViewer(width=1800, height=1350)

In [6]: s = trimesh.Scene([m])

In [7]: s.show(flags={'wireframe': True})
Out[7]: SceneViewer(width=1800, height=1350)

```

**Comment by pauljurczak** [comment]
Thanks a lot. Is there any way to display XYZ axis?

**Comment by mikedh** [comment]
No worries, yeah try pressing “a” in the viewer window.

**Comment by pauljurczak** [comment]
Thanks, it works. I found that `show(flags={'wireframe': True, 'axis': True})` works too. I can't find it in the documentation, though.

**Comment by HiBandan** [comment]
hello mikedh, first of all trimesh is a wonderful package and I used it a lot in my research. I was wondering is it possible to view a polygon mesh (dual graph of the triangulation) in trimesh ?
