### ISSUE TITLE
PBRMaterial hash takes only baseColor into account

### ISSUE THREAD

**Issue by andy-5** [mikedh/trimesh#1366]
I noticed that hashes for `PBRMaterial` only take the baseColor (Factor and Texture) into account.

I had a use case where multiple PBRMaterials shared the same baseColorTexture, but with different values for other attributes (e.g. name, alphaMode, etc.). During export to GLB, all of these materials were considered to be the same, and only one material was exported.

I think that the [`__hash__`](https://github.com/mikedh/trimesh/blob/00ffb55b150d37988f6113a758c50f4092a49bd1/trimesh/visual/material.py#L398) method of `PBRMaterial` should use more of its attributes (i.e. all arguments passed to `__init__`?), similar to [`SimpleMaterial.__hash__`](https://github.com/mikedh/trimesh/blob/00ffb55b150d37988f6113a758c50f4092a49bd1/trimesh/visual/material.py#L138).

For my use case, I simply patched it to include the neccessary attribute, i.e.

```python
        hashed ^= hash(self.alphaMode)
```
and that worked well. But for general use, it should probably include all other attributes as well (except maybe `name`).

**Comment by mikedh** [comment]
Yeah that makes sense, I think this is probably a result of the hash function being implemented at a different time from the de-duplication logic haha. PBRMaterial should probably store that bundle in an internal dict i.e. (`PBRMaterial._data` or something), then we could do something like:

```
In [12]: d = {'color': [0,0,0,255], 'thing': None, 'scalar': 1}

In [15]: hash(bytes().join(np.asanyarray(v).tobytes() for v in d.values() if v is not None))
Out[15]: -2167279019492765930
```

Happy to take PR's!
