### ISSUE TITLE
How to use pyembree in this example?

### ISSUE THREAD

**Issue by pauljurczak** [mikedh/trimesh#1367]
Taken from examples (https://trimsh.org/examples.ray.html?highlight=intersects_location):
```
locations, index_ray, index_tri = mesh.ray.intersects_location(
        ray_origins=ray_origins,
        ray_directions=ray_directions)
```
How to convert it to use `pyembree`?

**Comment by mikedh** [comment]
Hey, actually if embree is installed `mesh.ray` will be a `ray.ray_pyembree.RayMeshIntersector(self)` rather than a `ray.ray_triangle.RayMeshIntersector(self)` by default, you can check by looking at the ray object:
```
In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [4]: print(m.ray)
<trimesh.ray.ray_pyembree.RayMeshIntersector object at 0x7f753d743790>

```

**Comment by pauljurczak** [comment]
Thanks. That "magic" was hard to guess from the documentation. Perhaps adding a few words of explanation there would help future users.
