### ISSUE TITLE
Submesh support for `slice_mesh_plane()`

### ISSUE THREAD

**Issue by paulmelnikow** [mikedh/trimesh#1369]
Hi Mike,

I've run into a use case with the `slice_mesh_plane()` function where I need to slice through only _part_ of the mesh.

One approach would be to take the submesh, slice it, and then rejoin it to the rest of the mesh. However that gets a little messy since it requires some extra bookkeeping of the vertices and the faces. It seems like it would be better, for my application, to provide a way to specify the triangles to which the slicing operation should apply.

I propose adding a `faces_to_slice` parameter to `slice_mesh_plane()` and `.slice_plane()`, which is an optional boolean mask. When the mask is provided, the slicing operation would only apply to the specified faces, with the remaining faces preserved regardless of where they lie in relation to the slicing plane.

What do you think about adding this? Would a PR be welcome?

**Comment by mikedh** [comment]
Yeah sounds totally reasonable, PR's welcome! Only suggestion is I might rename the kwarg to `face_index=None` (where `None` defaults to previous all-face behavior) to match other places we take masks.

**Comment by paulmelnikow** [comment]
Great, I'll see what I can do!

**Comment by mikedh** [comment]
Nice, both sound great! I just released the prior change, so you can probably fork off master. Thanks for looking into this!
