### ISSUE TITLE
Rigid registration - Different results with same meshes

### ISSUE THREAD

**Issue by blunovart** [mikedh/trimesh#1377]
Hi! Wonderful library, awesome job! 🥇

I am performing a rigid registration using the trimesh.registration.mesh_other function. You can find the code below:

```
import trimesh

mesh_path = "Human_femur.ply"
mesh = trimesh.load_mesh(mesh_path, process=False, maintain_order=True)

other_path = "Human_femur_0.ply"
other = trimesh.load_mesh(other_path, process=False, maintain_order=True)

matrix = trimesh.registration.mesh_other(mesh, other, samples=500, scale=False, icp_first=10, icp_final=50)[0]
```

You can download the two PLY files [here](https://commons.wikimedia.org/wiki/File:Human_femur.stl) and [here](https://3dprint.nih.gov/discover/3dpx-000168).

If I run the code above multiple times, I will not get the same matrix. This is just because of the sampling operation, right?

Thanks!

**Comment by mikedh** [comment]
> why the principal inertia trasnform has arbitrary sign? So basically I am not understanding why doing the first ICP pass.

If I recall correctly, if the magnitude of the principal components of inertia are identical for some vectors (i.e. like a cuboid) the sign is arbitrary, although yeah you might be able to reduce the number of signs you check.

**Comment by blunovart** [comment]
Thanks for your time and explanation! 🥇
