### ISSUE TITLE
apply_transform and process have undocumented side effects

### ISSUE THREAD

**Issue by topinfrassi01** [mikedh/trimesh#1378]
Hello,

Thanks for your library it's tremendously helpful.

I noticed that the `Trimesh.apply_transform` and `Trimesh.process` both have undocumented side effects.

The documentation for the `apply_transform` will be used here as an example of what I think is a problem. The function returns a `Trimesh` object : 

```
    def apply_transform(self, matrix):
        """
        Transform mesh by a homogeneous transformation matrix.
        Does the bookkeeping to avoid recomputing things so this function
        should be used rather than directly modifying self.vertices
        if possible.
        Parameters
        ------------
        matrix : (4, 4) float
          Homogeneous transformation matrix
        """
```

However, the apply_transform function not only returns a trimesh object, it also modifies the vertices of the called mesh, which is an undocumented side effect of the function.

As such, doing this : `mesh2 = mesh1.apply_transform(matrix)` also modified `mesh1`, which I think is a code smell and would yield many head scratching results (as it happened for me).

I would propose one of the following fixes in order to solve this problem : 

- Use an `inplace` keyword that would work as in the `pandas` library. When `inplace==True`, the caller is modified and no objects are returned, when `inplace==False` the caller isn't modified and a new instance is returned with the modification. I however understand that this would be a change that would break the standards of the library as it wouldn't be found anywhere else;
- `apply_transform` returns `None`. This way, it would be clear that `apply_transform` modifies the caller. This would be a breaking change, so I don't think this is a good solution. It would also break fluent interface;
- Finally, what I think would be the easiest solution is to add documentation to the function header to modify it to something like this : 

```
    def apply_transform(self, matrix):
        """
        Transform mesh by a homogeneous transformation matrix.
        Does the bookkeeping to avoid recomputing things so this function
        should be used rather than directly modifying self.vertices
        if possible.

        Parameters
        ------------
        matrix : (4, 4) float
          Homogeneous transformation matrix

        Returns
        -------
        Trimesh
          (self) A reference to the transformed instance mesh
        """
```

This last solution doesn't break any existing code, however it makes it very clear that `mesh1` is modified in the previous scenario. In order to figure out that `self` was returned, I needed to go in the source code. I believe this should be documented somewhere.

The same could be applied to the `process` function and to any other function that returns `self`.

Thanks

**Comment by caseymjohnson** [comment]
I'm running up against a similar issue

I have a mesh, which I would like to rotate incrementally, capturing a frame at each rotation step

The following code will only apply the *first* transformation passed (e.g. n=0). Iterations for n > 1 do not apply the new transforms - every render displays the mesh in the same orientation.


`for n in range(nsteps):    
    rotMag = math.pi * n / nsteps 
    rot_matrix = trimesh.transformations.rotation_matrix(rotMag, direction, pivot)
    combined.apply_transform(rot_matrix)
    png = scene.save_image(resolution=[1000, 1000], visible=True, flags={'wireframe': shouldWireframe})`
    
however, using a temp copy of the original mesh will produce the desired incremental rotation, at the expense of the costly copying operation

`original = combined
for n in range(nsteps):    
    combined = original.copy()
    rotMag = math.pi * n / nsteps 
    rot_matrix = trimesh.transformations.rotation_matrix(rotMag, direction, pivot)
    combined.apply_transform(rot_matrix)
    png = scene.save_image(resolution=[1000, 1000], visible=True, flags={'wireframe': shouldWireframe})`
    
Am I misreading the docs on this one? or is this the result of some strange modifications behind the scene? or the bookkeeping not updating?

**Comment by mikedh** [comment]
Hey, looks like this is indeed a caching bug. `mesh.smoothed` is currently using different, broken caching logic currently. I was able to reproduce and will push a fix shortly. Thanks for the report!

**Comment by caseymjohnson** [comment]
thank you so much for the quick support @mikedh!!! very grateful for what you've built - most of my projects start with import trimesh import shapely :)
