### ISSUE TITLE
texture image name doesn't match material name

### ISSUE THREAD

**Issue by kampelmuehler** [mikedh/trimesh#1396]
If a material is named eg. `MaterialA`, then when exported as obj the mtl file will be named `MaterialA.mtl` but the corresponding image texture will be named `materiala.png`. This comes from the `.lower()` here:

https://github.com/mikedh/trimesh/blob/5c8891defc1967cfcb9fd7c0c908b4f666364091/trimesh/visual/material.py#L128

Is there a reason for using `.lower()` here? It causes some unwanted discrepancy.

**Comment by mikedh** [comment]
Hey, good point yeah there's no reason to do a `.lower` there. If anything, it should be filtering out invalid or security-escape characters for a filename (i.e. `../../hi` or `mate/e/ri/a` or something). In the meantime though yeah happy to remove the `.lower` when I get a chance or PR's welcome!

**Comment by kampelmuehler** [comment]
`.lower()` doesn't really do any filtering in that sense (or not that I'm aware of). Theoretically one could use `pathlib` and/or regex to clean up the filename.
It would be probably more elegant to check for a valid name when assigning it (so maybe during class creation or in the setter).
For now I'll create a PR for removing the `.lower()`
