### ISSUE TITLE
How to convert vertex colors to uv map? Could I use trimesh to generate uv image ?

### ISSUE THREAD

**Issue by yxdydgithub** [mikedh/trimesh#1399]
Hi! I have a 'ply' file with vertex colors. I hope to generate uv map. The result should contain two files including image and 'mtl' file. As below is a part of content in 'ply' file.
ply
format ascii 1.0
comment https://github.com/mikedh/trimesh
element vertex 96654
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 193310
property list uchar int vertex_indices
end_header
0.03932160 0.20607723 0.07971995 99 91 104 255
-0.09043968 0.06367093 -0.01851135 126 95 90 255
-0.05636096 0.15736078 0.07659208 92 89 100 255
0.14352384 0.09008317 0.01589330 98 90 105 255
-0.01441536 0.27214202 0.04375036 86 74 88 255
-0.06028544 0.37341890 0.00128445 240 71 112 255
-0.04324608 0.21187785 -0.07054192 102 96 108 255
-0.00064768 0.32201767 0.03527842 175 117 116 255
0.00721920 0.27670386 0.04388957 92 84 97 255
-0.09763584 0.04315750 -0.01030805 93 60 71 255
-0.03603200 0.10307322 -0.05912117 88 80 93 255
-0.05569024 0.40466267 0.07505921 132 116 116 255

**Comment by mikedh** [comment]
Hey, if you `pip install xatlas` and run `mesh.unwrap` it should generate UV coordinates:

```
In [5]: m.unwrap?
Signature: m.unwrap(image=None)
Docstring:
Returns a Trimesh object equivalent to the current mesh where
the vertices have been assigned uv texture coordinates. Vertices
may be split into as many as necessary by the unwrapping
algorithm, depending on how many uv maps they appear in.

Requires `pip install xatlas`

Parameters
------------
image : None or PIL.Image
  Image to assign to the material

Returns
--------
unwrapped : trimesh.Trimesh
  Mesh with unwrapped uv coordinates
File:      /media/psf/Home/Dropbox/robotics/trimesh/trimesh/base.py

```

**Comment by SunzeY** [comment]
have the same problem! could please you share the code for converting the colored vertex mesh to textured image?
