### ISSUE TITLE
Cannot remove duplicate vertices in a icosahedron.

### ISSUE THREAD

**Issue by zj2001** [mikedh/trimesh#1402]
Hi, I encounter a fatal error. Here is my code. `sphere12.ply` here is icosahedron.

import trimesh #version 3.9.35
mesh_path = ('./sphere12.ply')
mesh = trimesh.load(mesh_path, 'ply')
print(mesh.vertices)
mesh.process(True)
print(mesh.vertices)

However, the output is as follows:

[[ 0.          0.         -1.        ]
 [ 0.          0.          1.        ]
 [ 0.276393   -0.85065103  0.44721401]
 [ 0.276393    0.85065103  0.44721401]
 [-0.723607   -0.52573103  0.44721401]
 [-0.723607    0.52573103  0.44721401]
 [-0.894427   -0.         -0.44721401]
 [-0.894427   -0.         -0.44721401]
 [ 0.894427    0.          0.44721401]
 [ 0.723607   -0.52573103 -0.44721401]
 [ 0.723607    0.52573103 -0.44721401]
 [-0.276393   -0.85065103 -0.44721401]
 [-0.276393   -0.85065103 -0.44721401]
 [-0.276393    0.85065103 -0.44721401]
 [-0.276393    0.85065103 -0.44721401]]

[[ 0.          0.         -1.        ]
 [ 0.          0.          1.        ]
 [ 0.276393   -0.85065103  0.44721401]
 [ 0.276393    0.85065103  0.44721401]
 [-0.723607   -0.52573103  0.44721401]
 [-0.723607    0.52573103  0.44721401]
 [-0.894427   -0.         -0.44721401]
 [-0.894427   -0.         -0.44721401]
 [ 0.894427    0.          0.44721401]
 [ 0.723607   -0.52573103 -0.44721401]
 [ 0.723607    0.52573103 -0.44721401]
 [-0.276393   -0.85065103 -0.44721401]
 [-0.276393   -0.85065103 -0.44721401]
 [-0.276393    0.85065103 -0.44721401]
 [-0.276393    0.85065103 -0.44721401]]

They are the same and both have duplicate vertices which will lead to errors. 
I tried `merge_vertices()` and `process()`. They didn't work.
And  I changed the version back to 3.9.10, this problem is solved....

**Comment by mikedh** [comment]
Hey, hard to tell without the mesh, but I suspect the mesh has vertex normals or vertex textures defined, which if you want to merge everything regardless of vertex properties you may need to call `mesh.merge_vertices(merge_tex=True, merge_norm=True)`:
```

In [1]: import trimesh

In [2]: m = trimesh.creation.icosahedron()

In [3]: m.merge_vertices?
Signature: m.merge_vertices(**kwargs)
Docstring:
Removes duplicate vertices, grouped by position and
optionally texture coordinate and normal.

Parameters
-------------
mesh : Trimesh object
  Mesh to merge vertices on
merge_tex : bool
  If True textured meshes with UV coordinates will
  have vertices merged regardless of UV coordinates
merge_norm : bool
  If True, meshes with vertex normals will have
  vertices merged ignoring different normals
digits_vertex : None or int
  Number of digits to consider for vertex position
digits_norm : int
  Number of digits to consider for unit normals
digits_uv : int
  Number of digits to consider for UV coordinates
File:      /media/psf/Home/Dropbox/robotics/trimesh/trimesh/base.py
Type:      method

In [4]: m.merge_vertices(merge_tex=True, merge_norm=True)

```

**Comment by zj2001** [comment]
Thanks, i will try this method if i encounter the same problem~
