### ISSUE TITLE
Loaded mesh with new faces

### ISSUE THREAD

**Issue by matfcp** [mikedh/trimesh#1423]
Hi there!

When I load a mesh, sometimes the trimesh object creates new faces on my original mesh, as you can see in the pictures below. What can possibly be happening?

original mesh:
![Captura de tela 2021-12-06 194509](https://user-images.githubusercontent.com/95658882/144934832-c4ef6079-5388-4a94-9ace-6f05baf5e0ee.png)

mesh exported from trimesh:
![Captura de tela 2021-12-06 194029](https://user-images.githubusercontent.com/95658882/144934488-c8c0c31c-5d6a-4161-8bb1-a5094b1d2684.png)

mesh exported visualized inside trimesh:
![Captura de tela 2021-12-06 193140](https://user-images.githubusercontent.com/95658882/144934573-f0f70e9e-c5ed-466a-820b-e00c832586da.png)

it looks like the edges of this new face are being generated from a common point
![Captura de tela 2021-12-06 194125](https://user-images.githubusercontent.com/95658882/144934703-a01c5dc7-be89-45c1-8939-8160f20dbd45.png)

Thank you very much!

**Comment by mikedh** [comment]
Hey, what format? Can you provide the file this is happening on?

**Comment by matfcp** [comment]
sure! 

the original file is in https://drive.google.com/file/d/15AX-GbMJowqoYy4sQOhd4MpUhIc1z934/view?usp=sharing

the file exported from trimesh is in https://drive.google.com/file/d/1imO76conx1wzuPrbya9FVdmRdpVLdlmg/view?usp=sharing

**Comment by mikedh** [comment]
Oh, it's a mesh with non-convex polygon faces (i.e. the first face is triangular, the second one has a bajillion vertices):
```
f 25//25 23//23 26//26
f 27//27 28//27 29//27 30//27 31//27 32//27 33//27 34//27 35//27 36//\
27 37//27 38//27 39//27 40//27 41//27 42//27 43//27 44//27 45//27 46/\
/27 47//27 48//27 49//27 50//27 51//27 52//27 53//27 54//27 55//27 56\
//27 57//27 58//27 59//27 60//27 61//27 62//27 63//27 64//27 65//27 6\
6//27 67//27 68//27 69//27 70//27 71//27 72//27 73//27 74//27 75//27 \
76//27 77//27 78//27 79//27 80//27 81//27 82//27 83//27 84//27 85//27\
 86//27 87//27 88//27 89//27 90//27 91//27 92//27 93//27 94//27 95//2\
7 96//27 97//27 98//27 99//27 100//27 101//27 102//27 103//27 104//27\
 105//27 106//27 107//27 108//27 109//27 110//27 111//27 112//27 113/\
/27 114//27 115//27 116//27 117//27 118//27 119//27 120//27 121//27 1\
22//27 123//27 124//27 125//27 126//27 127//27 128//27 22//27 24//27 \
25//27 26//27 129//27 130//27 131//27 132//27 133//27 134//27 135//27\
 136//27 137//27 138//27 139//27 140//27 141//27 142//27 143//27 144/\
/27 145//27 146//27 147//27 148//27 149//27 150//27 151//27 152//27 1\
53//27 154//27 155//27 156//27 157//27 158//27 159//27 160//27 161//2\
7 162//27 163//27 164//27 165//27 166//27 167//27 168//27 169//27 170\
//27 171//27 172//27 173//27 174//27 175//27 176//27 177//27 178//27 \
179//27 180//27 181//27 182//27 183//27 184//27 185//27 186//27 187//\
27 188//27 189//27 190//27 191//27 192//27 193//27 194//27 195//27 19\
6//27 197//27 198//27 199//27 200//27 201//27 202//27 203//27 204//27\
 205//27 206//27 207//27 208//27 209//27 210//27 211//27 212//27 213/\
/27 214//27 215//27 216//27 217//27 218//27 219//27 220//27 221//27 2\
22//27 223//27 224//27 225//27 226//27 227//27 228//27 229//27 230//2\
7 231//27 232//27 233//27 234//27 235//27 236//27 237//27 238//27 239\
//27 240//27 241//27 242//27 243//27 244//27 245//27 246//27 247//27 \
248//27 249//27 250//27 251//27 252//27 253//27 254//27 255//27 256//\
27 257//27 258//27 259//27 260//27 261//27 262//27 263//27
```

So it's not creating *new* faces, so much as "badly triangulating a non-convex polygon." The bit that's doing it is here:
https://github.com/mikedh/trimesh/blob/de100ba92a64974c663f46a5de1d18603ca447f6/trimesh/exchange/obj.py#L469-L477

It could be "fixed" for the general case by adding "transform-to-plane-then-triangulate logic" from various places. General triangulation is kinda complicated and trimesh uses either earcut-python or Python bindings for [triangle](https://github.com/drufat/triangle):
https://github.com/mikedh/trimesh/blob/de100ba92a64974c663f46a5de1d18603ca447f6/trimesh/creation.py#L443-L456

The downside of doing that is it would add a dep for this specific case.

**Comment by matfcp** [comment]
thank you so mush for your response!

I'm using this kind of mesh in my master's research, and working with 3d mesh, specially on python, is kinda new to me. 

is there an easy way of doing that? what do I have to change in this code you left above?

**Comment by matfcp** [comment]
dear mikedh, thank you so so much for your responses and attention. 

I figured out that the issue was due to a mistake on exporting the mesh from blender. I could solve this on blender before exporting the mesh and now trimesh works fine.

I'm closing the issue for now, thank you again and big congrats for your work!
