### ISSUE TITLE
Trimesh Normals smoothing

### ISSUE THREAD

**Issue by ruslanvasylev** [mikedh/trimesh#1425]
Hi there, Cool lib!

For some reason, I don't quite understand how to recalculate normals for my objects, so when I export them to OBJ or GLTF they look smooth.

Hlep!

**Comment by mikedh** [comment]
Hey, you may want the smooth shaded option, i.e. `mesh.smoothed().export('hi.glb')`

**Comment by ruslanvasylev** [comment]
Yey!! Thank you @mikedh !
