### ISSUE TITLE
Add max_distance for 3D cross section?

### ISSUE THREAD

**Issue by sweco-sekrsv** [mikedh/trimesh#1426]
Awesome library:)
Would it be possible to add a max distance attribute to the 3D cross section?
https://trimsh.org/trimesh.html#trimesh.Trimesh.section

Something like:
`slice = mesh.section(plane_origin=mesh.centroid, plane_normal=[0,0,1], max_distance=5.0)`

I see two possible ways how this could work under the hood:
1. Collect the faces that is within 5 meters from the plane_origin and slice them and return the Path3D as before. The slicing would be potentially quicker for large meshes. This issue might need to be implemented first? https://github.com/mikedh/trimesh/issues/630
2. The full mesh is sliced but we return the Path3D object with vertices, indexes etc that is maximum 5 meters from the plane_origin. The slicing would not be quicker

If the max_distance is omitted the default value could be used. The default value should be an infinite distance to keep the current behavior.

Or do you have another idea on how to do this efficiently, possibly with already existing functions in trimesh?

**Comment by mikedh** [comment]
Hey, you can probably use `local_faces` to do something like this pretty easily:

```
In [1]: m = trimesh.load('models/featuretype.STL')
DEBUG              load.py:224   loaded <trimesh.Trimesh(vertices.shape=(1722, 3), faces.shape=(3476, 3))> using load_stl
DEBUG         constants.py:147   load_mesh executed in 0.0107 seconds.

In [2]: m
Out[2]: <trimesh.Trimesh(vertices.shape=(1722, 3), faces.shape=(3476, 3))>

In [3]: m.extents
Out[3]: array([5.   , 2.5  , 1.375])

In [4]: radius = m.extents.mean()

In [5]: radius
Out[5]: 2.9583333333333335

In [6]: origin = m.center_mass

In [7]: vertex_ok = np.linalg.norm(m.vertices - origin, axis=1) < radius

# subset to faces where ALL vertices are within the specified radius
In [8]: local_faces = vertex_ok[m.faces].all(axis=1)

In [12]: print(trimesh.intersections.mesh_plane.__doc__)

    Find a the intersections between a mesh and a plane,
    returning a set of line segments on that plane.

    Parameters
    ---------
    mesh : Trimesh object
      Source mesh to slice
    plane_normal : (3,) float
      Normal vector of plane to intersect with mesh
    plane_origin : (3,) float
      Point on plane to intersect with mesh
    return_faces : bool
      If True return face index each line is from
    local_faces : None or (m,) int
      Limit section to just these faces.
    cached_dots : (n, 3) float
      If an external function has stored dot
      products pass them here to avoid recomputing.

    Returns
    ----------
    lines :  (m, 2, 3) float
      List of 3D line segments in space.
    face_index : (m,) int
      Index of mesh.faces for each line
      Only returned if return_faces was True

```

**Comment by sweco-sekrsv** [comment]
Thanks @mikedh
