### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by DominikZians** [mikedh/trimesh#143]
I have an issue with the preview: like you see on the screenshot the area where the preview get drawn is not the size of the window.
I'm using macOS 10.13.3 on macbook pro 13" late 2013 retina display.
I guess the issue is linked to the retina display.

The python script I use:
import trimesh
mesh = trimesh.load('KingMarvin.stl')
mesh.show()

<img width="652" alt="bildschirmfoto 2018-03-18 um 01 42 37" src="https://user-images.githubusercontent.com/24372379/37561403-0fd68eec-2a4e-11e8-9b8e-82e02ad37eb3.png">

**Comment by mikedh** [comment]
I just checked on my MBP and I see this too. I'll try to look in to this next week.

**Comment by mikedh** [comment]
This is fixed for me on Mac Retina/Linux/Windows by https://github.com/mikedh/trimesh/commit/02459da5276a10c4686779f3a92cb1ff2de72d87 though feel free to re- open if you still see it.

Thanks for the report!

**Comment by DominikZians** [comment]
This is fixed for me too. Thanks!
