### ISSUE TITLE
trimesh.creation.sweep_polygon - sweep without banking?

### ISSUE THREAD

**Issue by sweco-sekrsv** [mikedh/trimesh#1430]
As I understand it, the sweep_polygon function rotates the polygon along x when it sweeps along a 3Dpath. In other software this is usually called banking when sweeping objects along a path. See here:
https://www.cadforum.cz/en/what-for-is-the-bank-option-of-the-sweep-command-tip12471

Is it possible to not rotate the polygon along X when sweeping? I would like resulting trimesh not to be banked.
Examples with a swept rectangle:
![2D](https://user-images.githubusercontent.com/10772529/145786168-3b8cdc26-7daf-4146-99c7-20937e3b1b68.png)
![banked](https://user-images.githubusercontent.com/10772529/145786180-3ec64de1-7e48-41a1-84d1-c9168dac3017.jpg)
![not_banked](https://user-images.githubusercontent.com/10772529/145786188-1392f324-a32e-49b8-8621-e5a3605bbbae.jpg)

I tried setting the angles option in trimesh.creation.sweep_polygon to a list with 0.0 values but it did not have any effect. Do I need calculate the angles for all vertices/line segments in the 3Dpath and then supply that to the angles option? Would appreciate an example if that is the case.

Thanks!

**Comment by swiss-knight** [comment]
Hello,


I'm facing the exact same issue with trimesh version 4.2.3.

Here is an MWE showing the shape's tilt along the 3D path:

```py
import numpy as np
from shapely.geometry import Polygon
from trimesh.creation import sweep_polygon

shape = Polygon([[0, 0],[2, 0], [2, 1], [0, 1], [0, 0]])
path = np.array([
    [  0,  0,  0],
    [  0, 10, 10],
    [ 10, 20, 20],
    [ 30, 20, 20]
])
mesh = sweep_polygon(shape, path)
```
![image](https://github.com/mikedh/trimesh/assets/19967599/5ce9e639-5447-43c4-8538-10e8d807a151)
