### ISSUE TITLE
Scaling trimesh primitives doesn't update metadata

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#1433]
Hi!

Following unexpected (undesired?) behavior:
```
b = trimesh.creation.uv_sphere()
print(b.metadata['radius'])    # output is '1.0'
b.apply_scale(2.0)
print(b.metadata['radius'])    # output is '1.0'
```
One way to fix this would be to modify the metadata during the apply_scale() call.  I could provide an MR for this but I'm not sure if it's the most elegant way (it would be a big if-then-else block depending on the 'shape' metadata).  Let me know what you think!

**Comment by mikedh** [comment]
Hey, you might check out `trimesh.primitives` which autogenerate the mesh when requested:

```
In [3]: p = trimesh.primitives.Sphere(radius=1)

In [4]: p.primitive
Out[4]: <trimesh.primitives._PrimitiveAttributes at 0x7f90da8d4d30>

In [5]: p.primitive.radius
Out[5]: 1.0

In [6]: p.bounds
Out[6]: 
array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [7]: p.primitive.radius = 2.0

In [8]: p.bounds
Out[8]: 
array([[-2., -2., -2.],
       [ 2.,  2.,  2.]])

```

**Comment by clemense** [comment]
Ah, perfect! Thanks!
