### ISSUE TITLE
Can't import pyrender.Mesh !!! 

### ISSUE THREAD

**Issue by alirezaahmadi** [mikedh/trimesh#1436]
any idea why am I getting this ?? 

mesh = pyrender.Mesh.from_trimesh(fuze_trimesh)
AttributeError: partially initialized module 'pyrender' has no attribute 'Mesh' (most likely due to a circular import)

thanks

**Comment by mikedh** [comment]
Hey, that's probably an issue with pyrender, you might check [their issue board.](https://github.com/mmatl/pyrender). I'd probably start by uninstalling and re-installing pyrender.
