### ISSUE TITLE
wireframe flag causes segfault

### ISSUE THREAD

**Issue by jrjbertram** [mikedh/trimesh#1438]
Hi there, 

I was looking for a way to enable wireframe mode programmatically, found https://github.com/mikedh/trimesh/issues/1365 which describes <trimesh object>.show( flags={'wireframe'=True} ).  When I use that, it generates a segfault.

Weirdly, if I just do <trimesh object>.show() I get the fully rendered object, I can hit 'w' to go into wireframe mode with no crashes.  I also see even weirder behavior if I first run a show() followed by a show(flags ... ).  Here's a minimal reproducer that exhibits the three cases I explored.

This is with trimesh==3.9.36 freshly installed from pip.  In case it's important, I'm on a mac with pyglet==1.5.21.  I updated pyglet to the latest to verify it wasn't an old version of pyglet which might have been causing the issue.

Josh

```
import numpy as np
import trimesh as tm

box = tm.creation.box()

# Set this value to 1, 2, or 3 to exercise one of the cases below
case = 2 

if case == 1:
    # This case doesn't segfault, I can hit 'w' within the viewer and get wireframe mode
    box.show( )

if case == 2:
    # This case causes a segfault at the command line
    box.show( flags={'wireframe':True} )

if case == 3:
    # In this case, if I first run a normal "show" followed by the wireframe
    # flag, I see the normal behavior on the first pyglet window that pops up..
    box.show( )

    # And after closing the first pyglet window, a second pyglet window pops up
    # during this show call.  The initial display/rendering is not wireframe,
    # but if I left-click the mouse in the window, it generates a refresh event
    # (it looks like) and the window is suddenly then in wireframe mode.
    box.show( flags={'wireframe':True} )
```

**Comment by mikedh** [comment]
Hey, yeah on Mac the viewer behavior is quite janky in general, I think they're planning on completely deprecating OpenGL at some point. That being said moving the `set-wireframe-mode` to after the GL init did fix the crash with your case-2 on my macbook.
