### ISSUE TITLE
Loaded vertices of glb files different in blender

### ISSUE THREAD

**Issue by Seasandwpy** [mikedh/trimesh#1440]
Hi,

I tried to load some glb models both in trimesh and blender,  but the loaded vertices have  different orders for y and z dimensions, and I have to swap them and use the opposite of z axis to have the same values. I would like ask what could have caused the problem?

**Comment by mikedh** [comment]
Hey, have you tried loading it with `mesh = trimesh.load('file.glb', process=False)`?

**Comment by Seasandwpy** [comment]
Hey,
I have tried to set process as False, but the result is the same. What I loaded is a scene, and I got the object vertices with: list(glb_scene.geometry.values())[0].vertices

**Comment by mikedh** [comment]
Ah, just accessing the geometry like that will discard any of the transformations defined in the GLTF scene graph. You probably want `scene.dump` which will apply the transforms:

```
In [2]: import trimesh

In [3]: m = trimesh.load('models/CesiumMilkTruck.glb')

In [4]: m
Out[4]: <trimesh.Scene(len(geometry)=4)>

In [5]: m.dump?
Signature: m.dump(concatenate=False)
Docstring:
Append all meshes in scene freezing transforms.

Parameters
------------
concatenate : bool
  If True, concatenate results into single mesh

Returns
----------
dumped : (n,) Trimesh or Trimesh
  Trimesh objects transformed to their
  location the scene.graph
File:      /media/psf/Home/Dropbox/robotics/trimesh/trimesh/scene/scene.py
Type:      method

```
