### ISSUE TITLE
Definition of Watertightness

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#145]
Hi! As always, great library, well done.

Question of definitions for you, pertaining to Watertightness of a mesh, as implemented in the `is_watertight` property/function.

In my understanding, watertightness as defined by this func is:
*"if all edges are shared by **exactly 2 faces**, then the mesh is watertight"*

Whereas in some other definitions I've seen, it's:
*"if all edges are shared by **an even number of faces**, then the mesh is watertight"*

Would it make sense to use the latter definition, and thus change the implementation, for cases like a mesh comprised of two cuboids which share a single edge (visually looks like stairs).

Currently under the former definition, that mesh would be considered not watertight, and returns such as expected from `is_watertight`.

For my use case I'm finding it useful to consider those cuboids that share a single edge as a watertight mesh, so I'm working on writing something which uses the latter definition of watertightness. Just wondering if anyone else might see value in having that available as an option in this lib. If so, what should it be called?

REFERENCES:
[1] https://www.cc.gatech.edu/~jarek/graphics/reading/meshSummary.pdf

**Comment by Marviel** [comment]
I'll check right now!

The one question to ask is I suppose, would we be okay with limiting users of Trimesh to 2 billion vertex models, or not?

**Comment by Marviel** [comment]
It looks like the first method has solved my use case :)

**Comment by mikedh** [comment]
I actually included (in https://github.com/mikedh/trimesh/commit/0bd3b4341714cce73685b51e9303a18103c85982) the bitbanging logic in `hashable_rows` after an automatic precision check which gets the speedup into other grouping functions too (including unique_rows). 


Actually getting a version of `is_watertight` that didn't break things elsewhere in trimesh was a bit tougher than I'd expected, because so many things rely on it. This version of `trimesh.graph.is_watertight` does pass all tests, but is 50% slower than the original:

```
def is_watertight(edges, edges_sorted=None):

    # passing edges_sorted is a speedup only                                                 
    if edges_sorted is None:                                                                 
        edges_sorted = np.sort(edges, axis=1)                                                
                                                                                             
    # find the unique edges and the inverse to reconstruct                                   
    unique, inverse = grouping.unique_rows(edges_sorted)                                     
                                                                                             
    # if every edge is shared by an even number of faces                                     
    watertight = (np.mod(np.bincount(inverse), 2) == 0).all()                                
                                                                                             
    if watertight:                                                                           
        # a check to see if every shared edge is reversed                                    
        # note that this is robust for edges shared by two faces                             
        # but is subject to random ordering for edges shared by 4+ faces                     
        # and will return arbitrary results                                                  
        ordered = edges[inverse.argsort()]                                                   
        winding = not bool(np.equal(ordered[0::2],                                           
                                    ordered[1::2]).all(axis=1).any())                        
    else:                                                                                    
        winding = False                                                                      
                                                                                             
    return bool(watertight), bool(winding)              
```

I'm kind of on the fence about pushing it to master as it is slower, and it kind of jankily handles the winding check on multiple shared edges.

**Comment by Marviel** [comment]
Maybe it's an alright start if this is just a convenience function for those who need it. I've made a local copy that I'm calling `is_watertight_even`

**Comment by Marviel** [comment]
I guess another question is, do those functions which rely on the current `is_watertight` need to recognize this edge case? Or would they break if they saw a multiply shared edge?

I suppose another idea is weird, but I was wondering if there would be a way to make the "merge_vertices" function recognize this case and not merge those particular vertices.

In my case I'm not dealing with a file that has this edge defined as one edge, but rather two edges which trimesh fuses together in the load operation

**Comment by mikedh** [comment]
Yeah maybe this is better suited as a utility function.

Oh, one other thought- this only happens on multibody geometry. The `mesh.split` function uses face adjacency which should be robust to these edge cases and by default returns a list of watertight single body meshes. 

Since things are a lot nicer for watertight single body meshes you might consider refactoring your application from:
```
mesh = trimesh.load(file_name)
if not mesh.is_watertight: raise ValueError('oh no')
# do stuff
```
To scene based:
```
loaded = trimesh.load(file_name)

# will create a scene, if loaded is a single mesh it will run mesh.split
# if loaded is a scene it will just return the scene
scene = trimesh.scene.split_scene(loaded)

for name, mesh in scene.geometry.items():
     # split should have given us only watertight results for a single mesh input
     assert mesh.is_watertight

     # do stuff
```

**Comment by mikedh** [comment]
I'm going to close this, and keep the current definition of watertight for now.  I think before I'd push something like this to master I'd like:
- the function to execute in comparable amounts of time to the current one
- the function to handle the winding check nicely on this edge case
