### ISSUE TITLE
Mesh to Grid Height Map

### ISSUE THREAD

**Issue by TheophileLebrun** [mikedh/trimesh#1451]
Hello,

I am creating a grid height map from a mesh but the function I came up with below is far too slow, taking around 16 seconds for a 2k faces triangle mesh on a 400 * 400 grid.

Could you kindly let me know what would need to be changed in this function to optimize it? Or should I change the approach totally?

Thanks!

```
def createMeshHeightMap(mesh, spacing,padding):



    def area(x1, y1, x2, y2, x3, y3):

        return abs((x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2)) )

    # create the grid structures

    gridX, gridY = np.mgrid[-padding:mesh.bounds[1][0] + spacing + padding :spacing,-padding:mesh.bounds[1][1] +  spacing + 
    padding * 2:spacing]

    gridZ= np.ndarray(gridX.shape)

    gridZ.fill(0)

    for i in range(mesh.triangles.shape[0]):

        # condition to only work on faces that represent the top of the mesh, assuming no undercut
        if mesh.face_normals[i][2]>0:

            triangle = mesh.triangles[i, :, :]

            #we create a rectangle around the triangle to find the grid points inside, we know that half the points do not belong there.

            minX=(np.trunc(min(triangle[:, 0])/spacing))*spacing-spacing
            maxX=(np.trunc(max(triangle[:, 0])/spacing))*spacing+spacing*2
            minY=(np.trunc(min(triangle[:, 1])/spacing))*spacing-spacing
            maxY=(np.trunc(max(triangle[:, 1])/spacing))*spacing+spacing*2

            triArea=area(triangle[0,0],triangle[0,1],triangle[1,0],triangle[1,1],triangle[2,0],triangle[2,1])

            flatTri=triangle[0,2]==triangle[1,2]==triangle[2,2]

            if triArea>0:

                for x in np.arange(minX,maxX,spacing):
                    for y in np.arange(minY,maxY,spacing):

                        a0=area(x,y,triangle[1,0],triangle[1,1],triangle[2,0],triangle[2,1])
                        a1=area(x,y,triangle[0,0],triangle[0,1],triangle[2,0],triangle[2,1])
                        a2=area(x,y,triangle[0,0],triangle[0,1],triangle[1,0],triangle[1,1])

                        #we now test if the point is in the triangle, and if yes find its z
                        if abs(triArea-a0-a1-a2)<1e-6:

                            if flatTri:
                                gridZ[(x/spacing).astype(int),(y/spacing).astype(int)]=triangle[0,2]
                            else:
                                gridZ[(x / spacing).astype(int), (y/spacing).astype(int)] = (a0*triangle[0,2]+a1*triangle[1,2]+a2*triangle[2,2])/triArea
```

**Comment by mikedh** [comment]
Sounds neat! A few quick possibly accurate thoughts:
- looping through every triangle is going to always be mega-slow in Python unfortunately
- one option is to use `m.subdivide_to_size` or `m.sample` very densely, and then convert to integer (x,y) indices. It's a little complicated because you then need the max(z) for each index (unless it's a nice surface or something), you could then reduce using `trimesh.grouping.unique_rows`. 
- if you install `embree`, probably the fastest thing to do by a huge margin would be to just do ray checks like [this example](https://github.com/mikedh/trimesh/blob/main/examples/raytrace.py) except using an orthographic camera (i.e different ray origins and all rays along the height-map-z-axis) rather than a single-origin perspective camera

**Comment by TheophileLebrun** [comment]
Thanks for the feedback!

- yes, I absolutly need to find a way to use numpy to escape the python loop
- that could be a way yes, I will try the subdivide to size but I am concerned about the loss of precision.
- embree would definitly be great to handle this issue but it seems to be a nightmare to install..


I have tried another approach: create a matplot triangulation interpolator and pass the values of the grid for interpolation.
The advantage is that I can pass the trimesh triangles in lieu of the matplotlib delaunay triangulation.

it is quite fast and works well. But the huge drawback is that the matplot interpolator will not initialize when it spots illegal input triangles. This will happen routinely when two edges exists inside of the trimesh that shares same x,y coordinates but not the same z. I do not really see a way to manipulate the mesh to prevent this situation from occuring. Furtheremore, in case of meshes with undercut, the interpolator wont initialize neither.

my code below where I seperated the flat faces from the other to be able to initialize the interpolator

`def createMeshHeightMapTri(mesh,spacing,padding):
    # grid creation

    gridX, gridY = np.mgrid[-padding:mesh.bounds[1][0] + spacing + padding:spacing,
                   -padding:mesh.bounds[1][1] + spacing + padding * 2:spacing]

    eps = 1e-6

    allInputs = None
    allValues = None

    # vertices 3d handling

    fnorm = mesh.face_normals
    flatFaceMask = (np.isclose(fnorm[:, 0], 0)) & (np.isclose(fnorm[:, 1], 0)) & (fnorm[:, 2] > 0)
    UpwardFacesMask = fnorm[:, 2] > eps

    #mesh.update_faces(np.logical_and(UpwardFacesMask,np.logical_not(flatFaceMask) ))


    triObjFlat = Triangulation(mesh.vertices[:,0], mesh.vertices[:,1],mesh.faces[flatFaceMask])

    fz_flat = LinearTriInterpolator(triObjFlat, mesh.vertices[:,2])
    Z_flat = fz_flat(np.ravel(gridX), np.ravel(gridY))
    gridZ_flat=Z_flat.filled(-1).reshape(gridX.shape)

    triObj3d = Triangulation(mesh.vertices[:, 0], mesh.vertices[:, 1],mesh.faces[np.logical_and(UpwardFacesMask, np.logical_not(flatFaceMask))])

    fz_3d = LinearTriInterpolator(triObj3d, mesh.vertices[:, 2])
    Z_3d = fz_3d(np.ravel(gridX), np.ravel(gridY))
    gridZ_3d = Z_3d.filled(-1).reshape(gridX.shape)

    gridZ=np.maximum(gridZ_flat,gridZ_3d)

    visualizeGrid(gridX,gridY,gridZ)`

**Comment by TheophileLebrun** [comment]
finally managed to get what i wanted relatively fast:

multi slice of the of the mesh on the y axis and then loop through the segments to extract the z and populate the z gride slice by slice.

then Numba should speed the latest part nicely
