### ISSUE TITLE
2D Surface Mesh

### ISSUE THREAD

**Issue by yhl48** [mikedh/trimesh#1472]
Hi, thank you for the good library. I have been using it for a while now to generate 3D meshes and their networks using ``trimesh.creation`` and ``vertex_adjacency_graph``. However, there does not seem to be a way to generate similar results on a plane surface, e.g. a 2D circle. Could you clarify if trimesh supports that, and if it does, how should it be done? Thank you.

Update: I seem to have found the solution by using a ``shapely`` ``Polygon`` object and ``trimesh.creation.triangulate_polygon``. Wondering if there are better approaches?

**Comment by mikedh** [comment]
Yeah `triangulate_polygon` is probably your best bet, or you could use [mapbox-earcut](https://github.com/skogler/mapbox_earcut_python) or [triangle](https://github.com/drufat/triangle) directly.
