### ISSUE TITLE
GLTF Extension question

### ISSUE THREAD

**Issue by MattSmillie** [mikedh/trimesh#1478]
Hi there, I just have a question on support for various extension on GLTF extensions
https://github.com/KhronosGroup/glTF/tree/main/extensions

I've come across models which use the "KHR_materials_pbrSpecularGlossiness" extension https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Archived/KHR_materials_pbrSpecularGlossiness/README.md
and also the "KHR_techniques_webgl" extension: 
https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Archived/KHR_techniques_webgl
Both of these extensions are listed as "Archived" so I don't expect them to properly be supported but is there a way to support these kinds of extensions in the library?
[Mars Curiosity Rover.zip](https://github.com/mikedh/trimesh/files/7977173/Mars.Curiosity.Rover.zip)
Here I've attached a sample which has the "KHR_materials_pbrSpecularGlossiness" extension, I didn't get any warnings when trying to load it but the materials seems to be missing.

**Comment by mikedh** [comment]
Neat model! Yeah this was pretty easy to support half-assedly by just mapping `diffuseTexture` to `baseColorTexture`, but I'd like to implement the [specular to metallic conversion function](https://github.com/KhronosGroup/glTF/blob/89427b26fcac884385a2e6d5803d917ab5d1b04f/extensions/2.0/Archived/KHR_materials_pbrSpecularGlossiness/examples/convert-between-workflows-bjs/js/babylon.pbrUtilities.js#L33-L64) before merging [this branch](https://github.com/mikedh/trimesh/tree/feat/gext). 

Would you happen to have a smaller example model (~100kb) that we could add to unit tests?

**Comment by MattSmillie** [comment]
Awesome, sadly I don't have a small model, I will try make one for the unit test. The mars rover was just pulled of the windows §D Viewer - it looks like many of the models on there use this extension.

**Comment by MattSmillie** [comment]
[pyramid_small.zip](https://github.com/mikedh/trimesh/files/8001107/pyramid_small.zip)
Ok here's a heavily modified model which can be used, hopefully it contains what you need

for reference this is how it looks in the windows 3d viewer

![image](https://user-images.githubusercontent.com/35508382/152493786-94680b36-85dd-4ac7-8610-44bcf69520a0.png)

And here it is rendered in https://gltf-viewer.donmccurdy.com/

![image](https://user-images.githubusercontent.com/35508382/152493943-f916fca2-cb3b-46f5-8272-3ae90e8e17fa.png)

Got to love those material extensions...

**Comment by mikedh** [comment]
Thanks for the example model! I added it to tests, and I'm going to release the basic material conversion with a TODO (it at least gets the texture rather than crashing) as I don't think I'm going to be able to get to the full conversion function anytime soon (PR's welcome on `trimesh.exchange.gltf.specular_to_pbr` and anywhere else 😄)
