### ISSUE TITLE
How to get the 2D shape of intersection between a mesh and a plane

### ISSUE THREAD

**Issue by mjkvaak** [mikedh/trimesh#1492]
I want to scan a 3D object in a similar manner as a CT scan is performed. Say I have the object
```python
#wget https://people.sc.fsu.edu/~jburkardt/data/obj/al.obj
import trimesh
def as_mesh(scene_or_mesh):
    if isinstance(scene_or_mesh, trimesh.Scene):
        if len(scene_or_mesh.geometry) == 0:
            mesh = None  # empty scene
        else:
            # we lose texture information here
            mesh = trimesh.util.concatenate(
                tuple(trimesh.Trimesh(vertices=g.vertices, faces=g.faces)
                    for g in scene_or_mesh.geometry.values()))
    else:
        assert(isinstance(mesh, trimesh.Trimesh))
        mesh = scene_or_mesh
    return mesh

mesh = trimesh.load('al.obj')
mesh = as_mesh(mesh)
mesh.show()
```
![image](https://user-images.githubusercontent.com/37109302/153456746-a5eb6f2f-55a2-4b7a-890f-714a977c2019.png)

I reckoned that the way to get the 2D slices from the object is via `intersections.mesh_plane`

```python
import matplotlib.pyplot as plt
isect, face_inds = trimesh.intersections.mesh_plane(
    mesh,
    plane_normal=(0,1,0),
    plane_origin=(0,-0.5,0),
    return_faces=True
)
plt.scatter(*isect[:,0,0::2].T)
plt.show()
```
![image](https://user-images.githubusercontent.com/37109302/153457150-d6a9e78d-30c7-464a-b0d3-46ec6ed600bf.png)

However, the problem now is that I only get the exterior points whereas I would want to be able to extract the enclosed area between them. Since the points are not ordered, I cannot directly make use of them as `cv2.contours`/`shapely.polygon` either. 

I believe I can track the connected points using the `face_inds` from `mesh_plane` and `mesh.faces`. My question is whether there exists a built-in function for this in the `trimesh` library? Thank you so much for your help.

**Comment by mikedh** [comment]
Hey, yeah those are actually pairs of connected points making up line segments, you might check out the section example: https://trimsh.org/examples/section.html

**Comment by mjkvaak** [comment]
Thank you for the fast response. :rocket: This was exactly what I needed.
```python
slice2d = mesh.section(
    plane_normal=plane_normal,
    plane_origin=plane_origin,

)
slice_2D, _ = slice2d.to_planar()
poly_union = shapely.geometry.MultiPolygon([poly for poly in slice_2D.polygons_full])
...
```
Note for self and others: this works only with meshes that are "watertight": `mesh.is_watertight == True`
