### ISSUE TITLE
Extend 3dxml loader to support Face triangles attribute

### ISSUE THREAD

**Issue by costerwi** [mikedh/trimesh#1493]
The current 3dxml implementation only supports the `strips` attribute (which my files unfortunately do not have). [The format](https://www.3ds.com/3ds-passport/downloads/) also allows for `triangles` and `fan` attributes to define the Face.

https://github.com/mikedh/trimesh/blob/e9c6327230b64f176e9e176f58a0f4a3d0334620/trimesh/exchange/threedxml.py#L151

Thanks!

**Comment by mikedh** [comment]
Happy to support it! Do you have a small example file that has those properties? The current loader is only tested with the outputs of Solidworks (which exports everything as text-triangle-strips). 

Mildly related question, you wouldn't happen to know anything about the `UVR` encoding some 3DXML files use? I ran into one in the wild and it looks like a totally proprietary binary blob, and that spec sheet only says "Compressed Tesselated Format" with no details.

**Comment by costerwi** [comment]
Thanks! The format is used by other Dassault software as well. I'll export a small example from Abaqus which will also include vertex colors.

Unfortunately, I don't have any additional documentation so hopefully we can figure it out.

**Comment by costerwi** [comment]
Please see this small example attached:
[cube1.zip](https://github.com/mikedh/trimesh/files/8074996/cube1.zip)
