### ISSUE TITLE
Crashes when cross-section has odd number of intersections

### ISSUE THREAD

**Issue by pwalsh0** [mikedh/trimesh#15]
Works fine for most slices, but crashes if it hits one with an odd number of intersections.   

File "/usr/share/miniconda/lib/python2.7/site-packages/trimesh/intersections.py", line 37, in mesh_plane_intersection
    return intersections.reshape(-1,2,3)
ValueError: total size of new array must be unchanged

**Comment by mikedh** [comment]
Thanks for the report, yeah this is definitely a pretty brittle implementation of slicing. Any chance you could share the mesh / code that failed so I can add it to the unit tests before trying to fix? If the mesh is gigantic no worries, I can probably replicate the bug on a unit sphere.

**Comment by pwalsh0** [comment]
Sorry I can't share the data :( 

The mesh had about 300k facets, was supposed to be a surface but had some spurious internal structure. I see in the code you try to generate line segments from the intersection points. Can't this be done with odd number of points as well? 

Say you identify intersection points 1,2,3,4,5.
Your code generates segments (1,2),(3,4)...crash. 
Can't it generate segments (1,2),(2,3),(3,4),(4,5)???

In my own code when I deal with contours I just specify them as a list of sorted vertices, thus with implicit connectivity. So each vertex is connected to previous/next item.

**Comment by mikedh** [comment]
No worries. Does d68a12130129861ba215689e52a4a4ccb77fe47e fix this for you?

**Comment by mikedh** [comment]
This should be fixed by the rewrite of cross sections in https://github.com/mikedh/trimesh/commit/8e50db009ee1335f09cb376d5148633961187a88 . Feel free to re- open if your still having problems, and thanks for the report!
