### ISSUE TITLE
Adding text to the pyglet window

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [mikedh/trimesh#151]
Hello,

I am trying to add a small enhancement to Trimesh in order to display text in the Pyglet window with information on the mesh.

My initial try was to add the following piece of code in `viewer.py` in the `on_draw()` function:

```
        label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=100,
                          color = (255,0,0,255),
                          x=self.width//2, y=self.height//2,
                          anchor_x='center', anchor_y='center')
        label.draw()
```

But unfortunately the text does not show,
Any intuition on how I could proceed ?

**Comment by mikedh** [comment]
Hmm maybe its something like: https://stackoverflow.com/questions/4269079/mixing-2d-and-3d-in-opengl-using-pyglet ?

**Comment by Anthony-MostlyHarmless** [comment]
Great, I missed that, thanks a lot.
