### ISSUE TITLE
Add viewer widget to QT application.

### ISSUE THREAD

**Issue by MediosZ** [mikedh/trimesh#1512]
Hi, I add the model viewer to QT applications as suggested in Issue #1077. 
I can submit a PR if needed.

**Comment by LFrix** [comment]
Hi MediosZ, I am also looking to embed the model viewer inside a PyQt application. Would it be possible to explain how you were able to achieve this?

**Comment by MediosZ** [comment]
Hi, @LFrix, please take a look at [this commit](https://github.com/MediosZ/trimesh/commit/3cd3c12603fb007fa5a45b770b140be80be59d18).
