### ISSUE TITLE
Scene metadata missing in scene_to_dict() result

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#1514]
Hi,

I can't find the metadata attached to the scene as a part of the dictionary created here:
https://github.com/mikedh/trimesh/blob/5c8891defc1967cfcb9fd7c0c908b4f666364091/trimesh/exchange/export.py#L148

Is this on purpose or just missing?

Thanks!

**Comment by mikedh** [comment]
Definitely not on purpose, PR's welcome!
