### ISSUE TITLE
How to rotate the mesh 

### ISSUE THREAD

**Issue by ZHLRJ** [mikedh/trimesh#1519]
I am trying to write a function to rotate mesh so every object faces me in the same direction, how to get the camera pos and object center pos in the world coordinate so I can calculate the rotation matrix for each.
Thanks for this great lib
![531647396733_ pic](https://user-images.githubusercontent.com/74697963/158503058-c87ccace-bd41-4a41-99a2-6e58bb2b1fe9.jpg)

**Comment by YuanWenqing** [comment]
Do you mean registration of point cloud?

**Comment by ZHLRJ** [comment]
@YuanWenqing I mean the separate camera view for each model otherwise all share the one, anyway thanks for the reply, I just solve it by vedo(vtk) lib, but the trimesh is a very good lib.
