### ISSUE TITLE
trimesh.path.raster.rasterize doesn't appear to render islands or nested paths/objects

### ISSUE THREAD

**Issue by johnscott4** [mikedh/trimesh#1526]
It seems like when I try and raster something with multiple nested islands the internal features will not raster/render.

By the way I love this library and would happy pay someone to fix this bug if it can get resolved quickly.

![Screen Shot 2022-03-19 at 4 44 44 pm](https://user-images.githubusercontent.com/8863368/159110706-2446bb0a-89ba-433f-a2aa-b407eb7986cb.png)

The 2D path of this looks like:

![image](https://user-images.githubusercontent.com/8863368/159110592-68f067e1-7259-4863-bce2-454027bc9b7a.png)

But the internal squares do not appear:

![Screen Shot 2022-03-19 at 4 43 06 pm](https://user-images.githubusercontent.com/8863368/159110651-c13c8537-e825-4ce3-8b5f-aaafcd634355.png)

**Comment by johnscott4** [comment]
This seems to work great! I'd like to do what I said and make a donation to this project if there's some way I can do that?

**Comment by mikedh** [comment]
No worries and thanks for the thought! I think donations are probably not possible right now, there’s no good mechanism for supporting it at the moment and the project consumes basically no money haha. Maybe someday we’ll have an OSS internship! 

Glad the fix works for you, I’ll merge and release shortly.
