### ISSUE TITLE
ValueError: File type: 3mf not supported

### ISSUE THREAD

**Issue by MarcelHeu** [mikedh/trimesh#1531]
Hello, 

if i try to use

`trimesh.load(path, force="mesh", skip_materials=True, process=False, use_embree=False, Validate_faces=False)`

with a *.3mf file it is working without any problems.

If i try to load a *.3mf file after i bundled my scripts into an application with pyinstaller, i got the following error:
**ValueError: File type: 3mf not supported**

Do you have any ideas why it is like this?

**Comment by mikedh** [comment]
Hey my first check would probably be to make sure lxml is in the bundle, if I recall correctly that is the major soft dependency 3mf relies on.
