### ISSUE TITLE
Do voxels remian axis aligned during transforms?

### ISSUE THREAD

**Issue by s0972456** [mikedh/trimesh#154]
First of all, thank you for making this library, it has been a tremendously help for my project!

I have a question regarding checking the intersection between 2 voxelized meshes, I am currently checking the intersection by testing if each center point of one mesh voxel is in another mesh by using is_filled function, and use the # of co-occupied grid *pitch^3. I am performing a lot of transforms on the meshes themselves and I understanding that the voxels will get transformed along. I wonder if the voxels remained axis aligned during the transforms? If they are axis aligned then checking for the co-occupancy is the fastest...

Also I will really appreciate it if you have any recommendations for checking the intersection between 2 meshes that is faster than the current implementation I use.

Thanks

**Comment by mikedh** [comment]
Hey, not sure about that specifically, but for checking collisions I'd recommend installing `python-fcl` and using the`trimesh.collisions` bindings- that should be quite a bit faster than doing it with voxels (at least the implementation in trimesh 😁 )

**Comment by mikedh** [comment]
Oh one other thing you could do if you didn't want to go full `python-fcl` is sample a bunch of points on the surface of mesh A, and then do a contains check from mesh B. If you have `pyembree` installed all parts of that are decently fast (sampling is vectorized, pyembree on my machine is ~600K rays/s):
```
In [2]: a = trimesh.load('models/ballA.off')
DEBUG              load.py:134   loaded mesh using load_off
DEBUG              util.py:796   is_empty was not in cache, executed in 0.000020
DEBUG         constants.py:129   load_mesh executed in 0.0172 seconds.

In [3]: b = trimesh.load('models/ballB.off')
DEBUG              load.py:134   loaded mesh using load_off
DEBUG              util.py:796   is_empty was not in cache, executed in 0.000038
DEBUG         constants.py:129   load_mesh executed in 0.0139 seconds.

In [4]: pitch = .1

In [5]: points_a = a.sample(int(a.area / (pitch ** 2)))
DEBUG              util.py:796   triangles was not in cache, executed in 0.000394
DEBUG              util.py:796   triangles_cross was not in cache, executed in 0.001286
DEBUG              util.py:796   area_faces was not in cache, executed in 0.001687
DEBUG              util.py:796   area was not in cache, executed in 0.001934

In [6]: points_a.shape
Out[6]: (60590, 3)


In [8]: b.contains?
Signature: b.contains(points)
Docstring:
Given a set of points, determine whether or not they are inside the mesh.
This raises an error if called on a non- watertight mesh.

Parameters
---------
points: (n,3) set of points in space

Returns
---------
contains: (n) boolean array, whether or not a point is inside the mesh
File:      /media/psf/Home/Dropbox (Personal)/robotics/trimesh/trimesh/base.py
Type:      method

In [9]: c = b.contains(points_a)
DEBUG              util.py:796   is_empty was not in cache, executed in 0.000024
DEBUG              util.py:796   edges was not in cache, executed in 0.000500
DEBUG              util.py:796   edges_sorted was not in cache, executed in 0.000295
DEBUG              util.py:796   is_watertight was not in cache, executed in 0.004086
DEBUG              util.py:796   triangles was not in cache, executed in 0.000379
DEBUG              util.py:796   bounds was not in cache, executed in 0.001083
DEBUG              util.py:796   extents was not in cache, executed in 0.000166
DEBUG              util.py:796   scale was not in cache, executed in 0.000618
DEBUG              base.py:312   generating face normals as shape was incorrect
DEBUG              util.py:796   triangles_cross was not in cache, executed in 0.000401
DEBUG              util.py:796   face_normals was not in cache, executed in 0.001667
DEBUG              util.py:796   _scene was not in cache, executed in 0.027240

In [10]: c.shape
Out[10]: (60590,)

In [11]: c.any()
Out[11]: True

```

Closing for now, thanks for the report!

**Comment by s0972456** [comment]
Hi Mike, thank you for your comments! I realize I wasn't clear on what I was asking...I was trying to approximate intersection volume of 2 meshes by voxelize them first and check the co-occupied voxels to get my estimated volume. I do have fcl installed and they provide fast collision checking by using BVHs but it's a boolean value only, no intersection volume is returned.

The reason why I was interested in if the voxels stay axis aligned because I was testing the co-occupancy of a voxel by checking how many center points of one voxelized model is within the other voxelized model,  and the point-within-grid test is the fastest if the voxels stay axis aligned during transforms.

Again, thank you for your advices and for making this repository!
