### ISSUE TITLE
Memory leak in proximity.signed_distance 

### ISSUE THREAD

**Issue by benoitrosa** [mikedh/trimesh#155]
Hi,

I stumbled into this problem when trying to compute signed distance between a large set of points (> 1 million in my case) and a mesh. If I call 

`trimesh.proximity.signed_distance(mesh,points)`

the program will slowly eat all the computer's memory, going all the way up to 16 GB in my case. Instead, if I do : 

`for point in points:
    trimesh.proximity.signed_distance(mesh,[point])`

The program will run smoothly, with a stable memory consumption around 150 Mb (also related to other stuff running in my script). 

I'm not sure whether the term 'memory leak' is adequate, I didn't have time to look deeply into the problem. I suspect that there might be recursive calls which loop through the mesh and create a mess in the memory. That's probably not a big problem when not having a million points to compute, but suboptimal nonetheless.

**Comment by mikedh** [comment]
Oh yeah, the performance of `signed_distance` is quite poor. I suspect this memory issue is `rtree`'s fault, but the "broad phase" part of the check (`nearby_faces`) needs some work. 

In the meantime, looping though each point has to be pretty darn slow: you might try batching the points into groups of some number (1e4 maybe?) and running the queries on those.

Thanks for the report!

**Comment by benoitrosa** [comment]
Hi,

I realized that embree and pyembree were not installed on my computer. After installing them, the memory leak does not appear anymore, and the whole thing runs considerably faster. Perhaps the problem lies in the ray_triangle implementation ?

Ben

**Comment by mikedh** [comment]
Yeah, embree/pyembree is wildly better in every way (it is an Intel😏  product after all). `ray_triangle` was an implementation I kept (with the same API) because on some platforms it is hard to install pyembree.

**Comment by mikedh** [comment]
Closing for now, though definitely open to PR's that improve `ray_triangle` performance. Thanks for the report!
