### ISSUE TITLE
Mesh volume

### ISSUE THREAD

**Issue by matfcp** [mikedh/trimesh#1566]
Hey Mike, how you doing? Hope you're well!

Please, can you give me the function or some more information (a source for example) about the *mesh.volume* method?

Thank you very much!

**Comment by mikedh** [comment]
Hey no worries, it's implemented as a surface integral from the method linked in the docstring and tested against the outputs of Solidworks:
https://github.com/mikedh/trimesh/blob/7cd0fda6641e04320320668640357a0caf7b5984/trimesh/triangles.py#L171-L199

**Comment by matfcp** [comment]
Thank you again for your quick response!

Best regards!
