### ISSUE TITLE
what is the difference between a vertex and a point of a triangle?

### ISSUE THREAD

**Issue by daqjjang** [mikedh/trimesh#1576]
model= trimesh.load(lee.obj, process=False)

A vertex value in 
model.vertices[0]
and 
model.triangle[0][0]
is different. 
Can you help me?

**Comment by pelayogmp** [comment]
Your mesh is defined by model.vertices (coordinates) and model.faces (indexes of vertices). The property triangles is constructed from them: 

```python
import numpy as np
import trimesh
model= trimesh.load(lee.obj, process=False)
# triangles is a numpy view of vertices using faces as indices 
np.alltrue(model.triangles == model.vertices[model.faces])
# and any vertex should be referenced by its index in faces
np.alltrue(m.vertices[m.faces[0,0]] == m.triangles[0,0])
```
In your model  `model.faces[0,0] != 0`

**Comment by daqjjang** [comment]
Thanks!!
