### ISSUE TITLE
Voxels only on surface but still able to use them to approximate total volume.

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [mikedh/trimesh#158]
Hello,

I have been trying out the voxelisation section of the program and there is a part I don't really understand.

In the comments it is written:
```
At the moment the voxels are not filled in and only represent 
the surface.
```
But when calculating the volume of the voxelised mesh you add-up the volume of all the independent voxels:

`volume = self.filled_count * (self.pitch**3)`

But if you do that with only the surface being voxelised how come it gives you a volume close to the mesh volume ?

I am probably misunderstanding something here,

Thanks for your help,

**Comment by mikedh** [comment]
Hey, yeah you're right that that volume should be fairly useless as it is the volume of the filled cells, but only cells on the surface of the mesh are filled. 

Not sure why it's close to the mesh volume- is the pitch of your voxelization close to the thinnest part of the mesh maybe?

Best,
Mike

**Comment by Anthony-MostlyHarmless** [comment]
Yes that seems to be it 👍 

Thanks for the answer,
