### ISSUE TITLE
Iterating over scene nodes while checking for camera node

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#1583]
Following problem:
If I do
```
s = trimesh.Scene()
s.add_geometry(geometry=trimesh.primitives.Sphere(), node_name='test', parent_node_name='world')
for node in s.graph.nodes:
    print(node)
```
it correctly prints
> world
> test

On the other hand, if I do
```
s = trimesh.Scene()
s.add_geometry(geometry=trimesh.primitives.Sphere(), node_name='test', parent_node_name='world')
for node in s.graph.nodes:
    if node == s.camera.name:
        continue
    print(node)
```
I get `RuntimeError: dictionary changed size during iteration` because I think the camera node gets only created if the scene is displayed in a viewer or if the property `camera` is accessed for the first time. This in turn will change the scene graph while iterating over it.  I'm not completely sure how to fix this properly at the moment, but it's definitely pretty hard to debug.

**Comment by mikedh** [comment]
Ah yeah this is because accessing `s.camera` actually creates the camera object (the first time). Not sure if there's an easy way to make this easier to debug, but if you change your check to `if s.has_camera and node == s.camera.name` it should avoid the case where it create the camera mid-loop.
