### ISSUE TITLE
AttributeError: 'Scene' object has no attribute 'vertices'

### ISSUE THREAD

**Issue by Aitensa** [mikedh/trimesh#1585]
The traceback is as follows,
`
File "/xxx/superquadric_parsing/learnable_primitives/mesh.py", line 364, in _normalize_points
    points = self.mesh.vertices.T
AttributeError: 'Scene' object has no attribute 'vertice
`  
This problem is really confused, can anyone help me?

**Comment by mikedh** [comment]
Hey, you probably want to load with `mesh = trimesh.load(file_name, force='mesh')`. Some formats are scene-descriptions (i.e. multiple meshes with transforms) not just straight meshes.

**Comment by Aitensa** [comment]
Thanks for suggestion, the reason is that I didn't add "force='mesh‘ ", final solved!  @mikedh 
 `
mesh = trimesh.load(file_name, force='mesh')
`
