### ISSUE TITLE
Load OBJ and MTL from variable or ZIP instead of file

### ISSUE THREAD

**Issue by USMANHEART** [mikedh/trimesh#1588]
Hi,
 I am written my own project for creating OBJ and MTL file.
Your API is very interesting and I wonder if I could export my OBJ (with MTL) directly to GLB without saving my OBJ, MTL and Textures to local.
Is there any good idea regarding this?
Or what if I merge all Textures, MTL and OBJ into a single ZIP file and your API could export it as GLB?
Kindly guide me regarding this issue

**Comment by mikedh** [comment]
You can pass a file object to loaders, and if you specify file type but not file obj to exporters they just return the export blob. E.g.:
```
glb_bytes = trimesh.load(file_obj=trimesh.util.wrap_as_stream(obj_bytes), file_type='obj').export(file_type='glb')
```
If there is an MTL and textures you'll have to also create a `trimesh.resolver.Resolver` object and pass it to load so the loader can find the referenced files.

**Comment by USMANHEART** [comment]
`tri_mesh = trimesh.load_mesh(file_obj=trimesh.util.wrap_as_stream(obj_str), file_type='obj')`

This is I am already doing. But I am facing problem with material.
How do I read all children of `tri_mesh` and assing material and texture to that children?
Can you give me small demo code for this?

**Comment by USMANHEART** [comment]
I have found the solution. It's fine now. Thanks
