### ISSUE TITLE
cross section of the mesh bug

### ISSUE THREAD

**Issue by youngstu** [mikedh/trimesh#1589]
![Screenshot from 2022-05-20 11-32-14](https://user-images.githubusercontent.com/26452514/169445127-6232fcb1-cef4-40cd-ba3c-69ed8ac2dc47.png)

slice entities bug, failed to split three entities.

**Comment by youngstu** [comment]
![Screenshot from 2022-05-20 11-34-56](https://user-images.githubusercontent.com/26452514/169445370-b44a374c-62f4-44d0-82c6-4f72fdaaa499.png)

This slice is right, succeed to split three entities.

**Comment by mikedh** [comment]
Do you have the code you used to generate them? It looks like it's been re-indexed or something.

**Comment by youngstu** [comment]
Yeah, I've solved it.

**Comment by youngstu** [comment]
> Do you have the code you used to generate them? It looks like it's been re-indexed or something.

Well, the problem is solved. Thanks.
