### ISSUE TITLE
[Minor Enhancement] Adding unique edge normals

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [mikedh/trimesh#159]
Hello,

For each element in `mesh.edges_unique` it could be useful to retrieve the 2 unitary vectors that are in the plane of the two faces they are connected with. These would be the two unitary vectors ![codecogseqn 2](https://user-images.githubusercontent.com/11192748/39021930-017b6dfa-43e8-11e8-9201-8c65f6081a1e.gif) and ![codecogseqn 3](https://user-images.githubusercontent.com/11192748/39021934-05284306-43e8-11e8-8d22-5f711ad33ac5.gif)

![capture](https://user-images.githubusercontent.com/11192748/39021763-1ea09d70-43e7-11e8-9c83-42442169256f.PNG)

Right now I am trying to do it by hand but it probably will be far from efficient and/or pretty and it might be useful for other applications.

Regards,

[Edit] Changed figure to one showing more clearly the positions of the vectors

**Comment by mikedh** [comment]
Hey, I was thinking about this, it seems like probably the nicest way to get this would be to use the shared edges in face adjacency. That avoids some of the thorny edge cases with non- watertight meshes (no adjacent face, 3+ triangles sharing an edge, etc):

```
    # the shared edges that correspond to adjacent face pairs
    # IE: len(mesh.face_adjacency_edges) == len(mesh.face_adjacency)
    edges = mesh.face_adjacency_edges

    # get a unit vector along the edges
    edge_vector = np.diff(mesh.vertices[edges],axis=1).reshape((-1,3))
    edge_vector /= np.linalg.norm(edge_vector, axis=1).reshape((-1,1))

    # cross the edge vector with the first face
    vec_A = np.cross(edge_vector,
                     m.face_normals[m.face_adjacency[:,0]])

    # cross the edge vectors with the second face
    vec_B = np.cross(edge_vector,
                     m.face_normals[m.face_adjacency[:,1]])

```

**Comment by mikedh** [comment]
Closing for now, though definitely let me know if you have a better solution than above. Thanks for the report!
