### ISSUE TITLE
How to calculate Path3D or Path2D convex hull circumference?

### ISSUE THREAD

**Issue by youngstu** [mikedh/trimesh#1590]
How to calculate Path3D or Path2D convex hull circumference? Are there some easy functions? Thanks.

**Comment by mikedh** [comment]
Hey, we could probably add a helper function but you can use the shapely polygons:

```
In [14]: p = trimesh.load('models/2D/1002_tray_bottom.DXF')

In [15]: p
Out[15]: <trimesh.Path2D(vertices.shape=(102, 2), len(entities)=46)>

In [16]: from shapely.geometry import MultiPolygon

In [17]: MultiPolygon(p.polygons_full).convex_hull.length
Out[17]: 47.74489218305155

```

**Comment by youngstu** [comment]
> Hey, we could probably add a helper function but you can use the shapely polygons:
> 
> ```
> In [14]: p = trimesh.load('models/2D/1002_tray_bottom.DXF')
> 
> In [15]: p
> Out[15]: <trimesh.Path2D(vertices.shape=(102, 2), len(entities)=46)>
> 
> In [16]: from shapely.geometry import MultiPolygon
> 
> In [17]: MultiPolygon(p.polygons_full).convex_hull.length
> Out[17]: 47.74489218305155
> ```

Very thanks for providing the example code.  It has solved my problem.
