### ISSUE TITLE
How to create a trimesh with vertices and unique edges

### ISSUE THREAD

**Issue by StipGod** [mikedh/trimesh#1591]
I currently have a problem trying to create a new mesh with a set of vertices and edges.

This is what im currently doing: 
nmesh = tm.Trimesh(vertices=V, edges_unique=E)

The new mesh is created with the vertices but the faces are not there, preventing me from viewing the mesh.

Thank you for your time and have a nice day!

**Comment by mikedh** [comment]
Hey, you'll need to construct and pass `(n, 3) int` faces from the edges and pass it to the `Trimesh` constructor.
