### ISSUE TITLE
Is there a way to sample points from a mesh at a single camera view?

### ISSUE THREAD

**Issue by kyjsj** [mikedh/trimesh#1593]
Hello!  
I have got a `Trimesh` from an `OFF` CAD file. And then, I want to sample some points from the CAD mesh at a single camera view. Would it be possible?
Thanks!

**Comment by mikedh** [comment]
Hey, you might want to check out [`examples/raytrace.py`](https://github.com/mikedh/trimesh/blob/main/examples/raytrace.py)
