### ISSUE TITLE
How MultiPolygon(path2d.polygons_full).convex_hull object add to scene viewer?

### ISSUE THREAD

**Issue by youngstu** [mikedh/trimesh#1595]
How MultiPolygon(path2d.polygons_full).convex_hull object add to scene viewer?

I want to visualize MultiPolygon.convex_hull object. Is there some easy function to use. Thanks.

**Comment by mikedh** [comment]
Hey, you can usually load `shapely.geometry.Polygon` objects into `trimesh.path.Path2D` objects using `trimesh.load_path(polygon)` and then add that to the scene. I actually don't recall if it supports MultiPolygons but you can always just do it iteratively on the multipolygon.geoms.
