### ISSUE TITLE
Is it possible to create a screenshot of a 3d object?

### ISSUE THREAD

**Issue by MecEngin** [mikedh/trimesh#1596]
Hello Community,

I imported a 3d file with trimesh.load_mesh. From this I would like to create a 2d screenshot or Snapshot and save the image file. It doesn't matter from which point of view. Is that possible?

I would be very grateful for help. Thank You

**Comment by ohseokkwon** [comment]
If the variable name is "mesh", you can use this example below.
The "opencv-python" library used in this example might be useful.

```
scene = trimesh.scene.Scene()
scene.add_geometry(mesh)

img = scene.save_image(backgound=[0,0,0,0])
cv2.imwrite('test.bmp', np.array(list(bytes(img))))
```

**Comment by mikedh** [comment]
Hey yeah as mentioned you can try to use `scene.save_image`. As a warning though it's very OS/GPU/driver dependant whether it is able to generate an image. You might try running this simple example natively: https://github.com/mikedh/trimesh/blob/main/examples/docker_render/render.py

And if it doesn't render anything try running it in docker (`run.bash`).

**Comment by MecEngin** [comment]
Thank You I will try it

**Comment by MecEngin** [comment]
Hello,

I apologize for the question. Without the "scene.camera transform = modified_camera_matrix" function, only a black image is saved for me. 
But when I paste this functoin in spyder I get the message "NameError: name 'modified_camera_matrix' is not defined". Also with the link "https://trimsh.org/trimesh.transformations.html" I didn't understand how to use this function. 

Can someone give me some more tips here? Thank You

**Comment by MecEngin** [comment]
Hello,
@mikedh This code is wonderful. Thanks a lot for this. The rendering works great but with the code
"with open('/output/output.png', 'wb') as f:
  f.write(png)" overwrites an existing image. Is it possible to create a new image?

I tried to integrate this code
"cv2.imwrite('test.bmp', np.array(list(bytes(png))))"
This creates an image, but unfortunately it's not rendered, it's black. Does anyone know how I can properly integrate this code? 

Thank You
