### ISSUE TITLE
AttributeError:  'VertexColor' object has no attribute 'material'

### ISSUE THREAD

**Issue by pedrohasselmann** [mikedh/trimesh#1600]
I'm simply trying to plot a point cloud before calculating the ConvexHull.
The script is the simplest possible:
`        cloud =  trimesh.points.PointCloud(pts)`
`         cloud.show()`

the data pts is just a 2D array, three columns.

And Yet, it returns:

>   File ".\ejecta_plume_liciacube.py", line 84, in convexhull
>     cloud.show()
>   File "\trimesh\points.py", line 635, in show
>     self.scene().show(**kwargs)
>   File "\trimesh\scene\scene.py", line 1106, in show
>     return SceneViewer(self, **kwargs)
>   File "\trimesh\viewer\windowed.py", line 191, in __init__
>     self._update_vertex_list()
>   File "\trimesh\viewer\windowed.py", line 224, in _update_vertex_list
>     self.add_geometry(name=name,
>   File "\trimesh\viewer\windowed.py", line 272, in add_geometry
>     geometry.visual.material)
> AttributeError: 'VertexColor' object has no attribute 'material'

Why visual.material would be needed to plot a point cloud ? And how do I define this property?

Same thing happens when I try plotting the trimesh.convex.convex_hull output.

**Comment by pedrohasselmann** [comment]
Trimesh was installed with conda:

> trimesh                   3.12.0             pyh6c4a22f_0    conda-forge

pts is a 2D float array with three columns:

> (94049, 3)

For now I'm ploting the pointcloud and the convex hull with Plotly, but trimesh option seems to me more elegant and clean.

**Comment by mikedh** [comment]
Hey, not totally sure why it's hitting that code path but I expanded the checks in the above PR which should hopefully fix this.
