### ISSUE TITLE
`trimesh.primitives.Sphere` has no `transform` attribute

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#1603]
Hi,
The `Sphere` seems to be the only primitive in trimesh that doesn't have a `transform` attribute. (but instead only a `center`)
Is this on purpose?

It creates a lot of if-then-else constructs when dealing with primitives.  Or is there another way to access this property in a primitive-agnostic way?

Thanks!

**Comment by mikedh** [comment]
Ah yeah I probably just did that because having a full matrix for a sphere seemed silly at the time, but the lack of consistency isn't wonderful either. Maybe `center` should be a `property/setter` and `transform` should be a required property for all primitive attributes (via `abc`?).
