### ISSUE TITLE
how can i load glb.files?

### ISSUE THREAD

**Issue by MecEngin** [mikedh/trimesh#1608]
Hello,

I have no problems loading STL or OBJ files. But since I want to load a file with color information, I tried to load OBJ files with an associated Mtl file. Since that didn't work, I tried glb.files, which is also recommended by trimesh. With both files I get the following error code: 

`AttributeError: 'Scene' object has no attribute 'scene'`

This is what my code looks like, with which I load files:
`mesh = trimesh.load_mesh('file.glb')`
`scene = mesh.scene()`

Can you help me? Thank You

**Comment by mikedh** [comment]
Hey, GLTF is a scene format, so it already loads as a scene. You can just call: `scene = trimesh.load('file.glb')`
