### ISSUE TITLE
Extruding polygon along a 3D path

### ISSUE THREAD

**Issue by anagaraj69** [mikedh/trimesh#162]
Hello Mike,
Thanks for the great work on this library!
I've been playing around with extruding polygons, and the extrude_polygon function works great. However, the sweep_polygon function (extruding a polygon along an arbitrary 3D path) seems to not behave so well - it results in a non-watertight mesh with many missing facets.
I've tried sweep_polygon with the test case, and it works as intended. So the issue must be with my input polygon (which is valid, and oriented ccw) or maybe in how I'm defining my 3D path (although the same path works with the test case polygon).
Any thoughts?
Thanks.

**Comment by mikedh** [comment]
Hey, thanks for the report. I haven't looked into it in detail, but it looks like the implementation of sweep only produces watertight outputs if the curvature of the path is less than the polygon radius. 

A mega- slow way to get the expected behavior would be to extrude each segment on the path individually, and then union all of them together.

I'll try to look in to a nicer solution at some point, and PR's are always welcome!

**Comment by anagaraj69** [comment]
Aah, I was extruding along a straight line (infinite curvature) using sweep. Sweep works along a straight line for the test case polygon, tho - will check with different sized polygons and see if there's some kind of predictable cut-off. Thanks for your suggestion regarding extruding each segment followed by union - tried that with expected mega-slow results :-) - pretty much given up on that approach.

Noted your comment regarding PRs. While I don't have anything on the current issue, I have made some kludgy changes to path.polygons etc in order to get valid polygons for my use case which don't break things downstream. Since I'm not at all familiar with GitHub's PR procedures, is it ok if I post the edited code as a new issue, which you can review and see how best to incorporate (or not!) into the master. Please let me know if you're comfortable with that.

Thanks. Closing this issue for now - will reopen if I have anything to report.

**Comment by mikedh** [comment]
Cool, no worries, and yeah `sweep_polygon` should do something differently if it isn't going to produce a watertight output. 

RE: PR, yeah that sounds good or you can just shoot me a link to a [gist](https://gist.github.com/) of your proposed changes.

Thanks for the report!

**Comment by anagaraj69** [comment]
Hi Mike,

Link to gist:
https://gist.github.com/anagaraj69/c70c37d50ac6d8ff0fabcda0e078e779

Changed paths_to_polygons in trimesh.path.polygons. Removed call to
repair_invalid in trimesh.path.path2D.polygons_full.
Notes:
1) Tolerances used are very specific to my use case - slicing stl design
files and making appropriate laser paths for 3D printing. Physical units
are mm i.e. a distance tolerance of 0.1 would be a tolerance of 100 microns.
2) If a polygon is valid, it's taken as is. If not, two options: a) if
simplification doesn't work at least-stringent tolerance, use buffering;
else, b) find most-stringent simplification tolerance (>0.1 micron) and
simplify. Keep polygons with area > 0.01 mm^2, even if invalid - will be
handled downstream.
3) Method seems to be quite robust - haven't had any floating-point,
topology or invalidity issues for 100+ designs over the last couple months.
4) Maybe this issue is better handled upstream by setting different
tolerances during path construction - I haven't looked into that. Also not
sure how these tolerances will affect other use cases.
5) Most of the issues I've had, particularly with reference to
intersections between LineString & Polygon, arise from 'valid' polygons
which have (very thin) folds in their external and/or internal contours.
I've taken to doing a default simplification (or buffer) of all
polygons_closed to avoid this. Again, not sure how this translates to other
use cases.

Best,
Ashwin Nagaraj

**Comment by mikedh** [comment]
Thanks for the gist! Yeah `repair_invalid` ends up being a bit specific to the application and scale. I wonder if the most graceful solution is to allow a user to pass a "repair function" to the loader, which by default is very conservative. Then in my application I pass in the more aggressive function, and you do the same.

**Comment by anagaraj69** [comment]
Yes, that sounds like a good way to go about it - leave the default repair behavior as conservative as possible, and let the user decide how best to repair polygons based on their application. Might have to provide an example of how to pass a repair function to the loader in the documentation, though  :-)
