### ISSUE TITLE
Support for directly setting transform of object

### ISSUE THREAD

**Issue by adamconkey** [mikedh/trimesh#1627]
The `Trimesh` objects have an `apply_transform` function, but if I call that sequentially with different transforms it composes the transformations. I think this is perfectly logical and useful. However, I was hoping there would be an alternative that lets me directly set the transform, e.g. a `set_transform` function that manually sets what the pose should be (i.e. that has the behavior of `apply_transform` on the first call to `apply_transform`, but always has that behavior no matter how many times I subsequently call it).

Is there a way to currently achieve this behavior? Or should this be added?

**Comment by mikedh** [comment]
Hey, yeah the `apply_transformation` and related methods basically "bake" the vertices. You might be interested in an instance of a mesh in a scene graph, where if you change the transform it will move the instance in the scene without changing the mesh's vertices:

```
In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [4]: m.apply_translation?
Signature: m.apply_translation(translation)
Docstring:
Translate the current mesh.

Parameters
----------
translation : (3,) float
  Translation in XYZ
File:      /media/psf/Home/Dropbox/robotics/trimesh/trimesh/parent.py
Type:      method

In [5]: m.apply_translation([0,1,1])
Out[5]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [6]: m.bounds
Out[6]: 
array([[-0.5,  0.5,  0.5],
       [ 0.5,  1.5,  1.5]])

In [7]: s = m.scene()

In [8]: s
Out[8]: <trimesh.Scene(len(geometry)=1)>

In [9]: s.graph.nodes_geometry
Out[9]: ['geometry_0']

In [10]: s.graph['geometry_0']
Out[10]: 
(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 'geometry_0')

In [11]: s.bounds
Out[11]: 
array([[-0.5,  0.5,  0.5],
       [ 0.5,  1.5,  1.5]])

In [12]: s.graph['geometry_0'] = trimesh.transformations.translation_matrix([10,10,10])

In [13]: s.bounds
Out[13]: 
array([[ 9.5, 10.5, 10.5],
       [10.5, 11.5, 11.5]])

In [14]: s.geometry['geometry_0'].bounds
Out[14]: 
array([[-0.5,  0.5,  0.5],
       [ 0.5,  1.5,  1.5]])

In [15]: s.graph['geometry_0'] = trimesh.transformations.translation_matrix([10,10,10])

In [16]: s.bounds
Out[16]: 
array([[ 9.5, 10.5, 10.5],
       [10.5, 11.5, 11.5]])

```

**Comment by adamconkey** [comment]
@mikedh Yes I think that handles what I wanted, I was unfamiliar with the `Scene` class so that's helpful to know! Thanks a lot!
