### ISSUE TITLE
Error fails to propagate starting from material.py

### ISSUE THREAD

**Issue by JDihlmann** [mikedh/trimesh#1632]
The issue started with an OBJ being loaded and texturized with my one anaconda environment but not the with the new one. There was no error thrown and the object got assigned ColorVisuals rather than with TextureVisuals.

I walked down the chain to track down the issue and finally landed in material.py where the import statement of `from ..path import packing` fails but with no error. I wrapped into a try catch statement to catch it and found out that I was missing the shapely package (would be best to install it with trimesh as co-dependency). In anyway there is an issue to propagate the error and throw an error somewhere starting from material.py up.

To reproduce: Simply construct an error somewhere in material.py and load an OBJ no error will occur

**Comment by mikedh** [comment]
Ah yeah it probably should have raised the shapely exception immediately when called, can you post a full traceback?

**Comment by JDihlmann** [comment]
Sure (manually added the statement)
<img width="1373" alt="trimesh_error" src="https://user-images.githubusercontent.com/9963865/179346969-206ae640-6187-4d5d-bfbe-5325987373ae.png">
