### ISSUE TITLE
only dump vertices from a mesh object

### ISSUE THREAD

**Issue by amiltonwong** [mikedh/trimesh#1633]
Hi, developers,

Does trimesh support dump vertices from a mesh object? e.g. save the vertices of a mesh (V,F) into *.ply file.

Thanks~

**Comment by mikedh** [comment]
Hey, the [args to the PLY exporter](https://trimsh.org/trimesh.exchange.ply.html?highlight=export_ply#trimesh.exchange.ply.export_ply) are passed through, if you want a simple ASCII ply export you might try:

`mesh.export(file_obj='example.ply', encoding='ascii', vertex_normal=False, include_attributes=False)`

**Comment by amiltonwong** [comment]
Thanks @mikedh. It works.
