### ISSUE TITLE
Rotation of scene geometry behaves different than mesh

### ISSUE THREAD

**Issue by ozancaglayan** [mikedh/trimesh#1639]
Hello,

First of all thanks for the library. I am pretty new to this, so sorry beforehands for any stupid mistake/claim =)

I have a `.gltf` file that I load with `trimesh.load()`. The file has some texture mappings, with 4 objects in overall. The problem is that, when I try rotating the scene geometry, `force=mesh` seems to give me proper results whereas with leaving `force=` out as its default, I can't achieve a stable behaviour:

```python
scene = trimesh.load('examples/photo_frame/scene.gltf', force='mesh')
scene.apply_transform(
    rotation_matrix(90 * (math.pi / 180), direction=[0, -1, 0], point=[0, 0, 0]),
)
scene.apply_transform(
    rotation_matrix(15 * (math.pi / 180), direction=[1, 0, 0], point=[0, 0, 0]),
)
scene.show()
```

yields the following, which is a photo frame parallel to the camera plane (more or less), but the textures are not rendered?

![image](https://user-images.githubusercontent.com/330946/179615882-468ac545-8512-4f0a-b8a8-0e5024d4b1f4.png)

On the other hand, running the same code but with `force=scene`, I get the following rotation:

![image](https://user-images.githubusercontent.com/330946/179616079-c05e14d2-703c-49bf-8a7f-205e9a78555d.png)

**Comment by mikedh** [comment]
Thanks for the report! The previous behavior for `scene.apply_transform` (bake a transform change into every geometry) was pretty wacky and didn't work with instances at all. I changed it to apply a transform to every child of the base frame, which has the advantage of not mutating anything other than the scene graph and being reversible.
