### ISSUE TITLE
Rigid Registration - `mesh_other` - Prevent Reflection

### ISSUE THREAD

**Issue by CristianoPizzamiglio** [mikedh/trimesh#1648]
Hi! Great work, thanks!

I am using Python 3.8.12 and `trimesh` 3.12.8

Let's consider the two input meshes `other.stl` (hyppo) and `to_register.stl` (Standford bunny) in the zip file attached. This is just a toy example.

I would like to register the `to_register.stl` mesh using the `mesh_other` of the `registration.py` module without scaling and reflecting. Regarding reflection there is currently no option to deactivate it so, locally, I have modified the `procrustes` function and set the default value for `reflection` to `False`. However, the resulting mesh `registered.stl` is reflected.

What would you suggest to do to prevent the reflection?

Here is the code:
```python
import trimesh

to_register = trimesh.load_mesh("to_register.stl", process=False, maintain_order=True)
other = trimesh.load_mesh("other.stl", process=False, maintain_order=True)

rototranslation_matrix, _ = trimesh.registration.mesh_other(to_register, other)

registered = to_register.copy()

registered.apply_transform(rototranslation_matrix)
registered.export("registered.stl")
```
Thanks!

[trimesh_icp.zip](https://github.com/mikedh/trimesh/files/9229991/trimesh_icp.zip)

**Comment by mikedh** [comment]
Thanks for the report! I added a keyword argument passthrough from `mesh_other` -> `icp` -> `procrustes`. So `mesh_other(..., reflection=False)` should hopefully do what you want when #1637 is released.

**Comment by CristianoPizzamiglio** [comment]
Thank you!
Have you tried to run my toy example? Did you get a reflected bunny even with `reflection` set to `False`?
