### ISSUE TITLE
v3.13.0 found bug

### ISSUE THREAD

**Issue by gleb-an** [mikedh/trimesh#1653]
Scene load and export this file.
When I tested it on the 3.9.1 version it worked well.
[MEP.zip](https://github.com/mikedh/trimesh/files/9292281/MEP.zip)

**Comment by mikedh** [comment]
Hey, it looks like that file loads for me, what's the issue? Are some of the materials not correct?

**Comment by gleb-an** [comment]
It lost some objects for me.

v3.9.1 ->
![Screenshot from 2022-08-10 14-39-04](https://user-images.githubusercontent.com/8939518/183894523-b8a16fd1-8346-40cc-aef7-4eb1bffd4fb0.png)

v3.13.0 ->
![Screenshot from 2022-08-10 14-39-05](https://user-images.githubusercontent.com/8939518/183894512-f2f4cb56-ce7b-4f8c-83fc-15f128ee470d.png)
