### ISSUE TITLE
error in trimesh/exchange/obj.py

### ISSUE THREAD

**Issue by 2j1ejyu** [mikedh/trimesh#1657]
I was having trouble with loading textured meshes (.obj with .mtl) and found out that there is a problem in the code. In line 323, the key is obtained in lowercase letters (ex. kd, ka...), while "mapped" in line 311 has keys with the first letters uppercase. This is causing the mesh to have default color.

**Comment by mikedh** [comment]
Thanks for the report! Yeah this was introduced in the latest release, I just pushed a hotfix which should release shortly and a test to check for this in the future.
