### ISSUE TITLE
cannot split trimesh object

### ISSUE THREAD

**Issue by gleb-an** [mikedh/trimesh#1664]
When I used trimesh 3.9.1 method split() could return a list of meshes.
But when I updated to 3.13.4 this method returned an empty array.
Should it be?
[overlapping-faces-02.zip](https://github.com/mikedh/trimesh/files/9397341/overlapping-faces-02.zip)

**Comment by mikedh** [comment]
Hey, what arguments did you call it with? Did you try `mesh.split(only_watertight=False)`?
