### ISSUE TITLE
STEP to STLs: replacing FreeCAD?

### ISSUE THREAD

**Issue by 0xCoto** [mikedh/trimesh#1665]
I wanted to ask regarding the STEP functionality. My goal is to get an input STEP file and export its underlying objects as a separate STL file for each object.

What I currently do is use FreeCAD's Python API, import the STEP file, and export the STL for each object (and as a bonus, also a single STL containing everything, i.e. the entire model). I then use trimesh to read the STL nodes in Python.

Is trimesh able to do something similar (so I can drop FreeCAD from my dependencies), or is it not built for these kinds of CAD-related purposes?

**Comment by mikedh** [comment]
Yeah this would be amazing! Unfortunately I’ve not found the OSS stuff reliable enough to use in applications which take from-the-wild files. FreeCAD is based on OpenCascade. Trimesh currently has some neglected bindings to gmsh (also OpenCascade based) which is a way to load STEP files: https://github.com/mikedh/trimesh/blob/main/trimesh/interfaces/gmsh.py

It's possible by tuning the gmsh parameters carefully you could get it to produce nice surface meshes. I got stuck getting gmsh to work reliably on larger CAD assemblies, and ended up just paying for commercial loaders. But PR's welcome!

One thing that I thought was super interesting was this project:
https://github.com/Formlabs/foxtrot

Most people just take OpenCascade, but this is the "parse and triangulate" logic done from scratch, and I wonder if building that up (i.e. find a large test corpus, make it work on the whole thing, do heavy profiling to make it not slow as heck, adding python bindings) would be a better starting point than trying to start from OpenCascade.

**Comment by mikedh** [comment]
Actually just tried this for the first time in a while, the GMSH team made their own wheels which is nice: 
`pip install gmsh`

And then this worked, albeit not all that quickly (6.4mb file in 8.2s):
```
    # all loaders return kwargs for constructors                      
    m = trimesh.Trimesh(**trimesh.interfaces.gmsh.load_gmsh('filletMSH.STEP'))
```

**Comment by 0xCoto** [comment]
@mikedh Hmm, close, but it seems like `gmsh` tries to mesh the object (for usual meshing purposes with proper refinements etc.), whereas FreeCAD tries to "export" the STEP as a very simple STL, with no advanced meshing algorithms etc. Not sure if that makes sense? I do get a different number of nodes, and the FreeCAD-exported STL is closer to what I need:

Using `trimesh.Trimesh(**trimesh.interfaces.gmsh.load_gmsh(...)`, I get `658 nodes`, but using **FreeCAD -> Import STEP -> Select all -> Export as STL** gives `504 nodes`.

**Comment by 0xCoto** [comment]
Found a new solution with CadQuery (just 2 lines of code!):
```py
result = cq.importers.importStep("data/" + step_file)
cq.exporters.export(result, "data/tmp/" + stl)
```


FreeCAD time: 0.04019427299499512 sec
CadQuery time: 0.031256914138793945 sec

**Comment by mikedh** [comment]
Nice! CadQuery is also OpenCascade based so it should be identical. Looks like they've made good progress! They do appear to be conda based at the moment so it would be a pretty rough install on vanilla pip without wheels.

**Comment by mikedh** [comment]
Actually if we were adding their STEP loaders, it might make sense to go one-upstream and implement one using their OpenCascade binding directly: https://github.com/CadQuery/OCP

**Comment by mikedh** [comment]
Added to the enhancement list, PR's welcome!

**Comment by mikedh** [comment]
I did an upstream packaging of OpenCASCADE just for STEP loading which works pretty well for my stuff, you might be interested: https://github.com/trimesh/cascadio
