### ISSUE TITLE
Has trimesh.smoothing been deprecated?

### ISSUE THREAD

**Issue by harshamarupudi56** [mikedh/trimesh#1669]
Attempting to use trimesh.smoothing.filter_mut_dif_laplacian(). This was working yesterday with no issues but I have found that in my scripts I get the error module trimesh has no attribute smooth. Has this functionality been deprecated and replaced with a different name?

**Comment by mikedh** [comment]
Hey, not as far as I know, it looks like it is still there and the tests have passed:
```
In [1]: import trimesh

In [2]: trimesh.smoothing.filter_mut_dif_laplacian
Out[2]: <function trimesh.smoothing.filter_mut_dif_laplacian(mesh, lamb=0.5, iterations=10, volume_constraint=True, laplacian_operator=None)>

In [3]: trimesh.smoothing.filter_mut_dif_laplacian

```

**Comment by harshamarupudi56** [comment]
Very strange, uninstalled trimesh with pip and reinstalled it and is no working.
