### ISSUE TITLE
smooth the border edges of mesh

### ISSUE THREAD

**Issue by SivHMA** [mikedh/trimesh#1670]
I have a mesh  with rough boundaries. whether any function that can smooth the border in trimesh?

![image](https://user-images.githubusercontent.com/29498630/186889835-e0d68494-ffa7-4fd3-815b-afb32f99f345.png)

**Comment by mikedh** [comment]
Hey, there's nothing build-in currently, though something that might work:
- you can get the curve with `mesh.outline`
- you could run `trimesh.path.simplify.resample_spline` on the boundary curve
- and then iteratively warp the vertices on the boundary towards the smoothed curve

**Comment by SivHMA** [comment]
Trimesh has an error when i use trimesh.path.simplify.resample_spline

module 'trimesh.path' has no attribute 'simplify'

**Comment by mikedh** [comment]
You may have to import it directly:

```
In [1]: from trimesh.path.simplify import resample_spline

In [2]: resample_spline
Out[2]: <function trimesh.path.simplify.resample_spline(points, smooth=0.001, count=None, degree=3)>

```
