### ISSUE TITLE
ValueError: Unable to extract class of name Trimesh

### ISSUE THREAD

**Issue by dsvilarkovic** [mikedh/trimesh#1673]
I have:
1. Box primitive: box = trimesh.primitives.Box(extents=(bound,bound,bound)).as_outline()
2. Colored pointcloud:  image_ply = trimesh.points.PointCloud(vertices=camera_points, colors=color_points)
3. Path3D object:  segs = trimesh.load_path(segs)

I can visualize them with trimesh.Scene([box, image_ply, segs ]).show(), but I would like to know is there any way I can export them together in a .ply format so I can load them elsewhere? 

I get this error "ValueError: Unable to extract class of name Trimesh" for box and segs variables when trying to export to .ply, and I assume I would need to convert them to pointcloud format first, but I don't see a function to do that.

**Comment by mikedh** [comment]
Hey, the PLY format doesn't support line segments as far as I know, although GLTF/GLB does. I think you'd have to convert the line segments to triangulated cylinders if you wanted to use PLY as the exchange format.

**Comment by dsvilarkovic** [comment]
Yeah, I understand that ply probably doesn't support primitives, but I do not know how to convert them to .ply format. Is there a quick clue where I might look for those transformations?

And thanks for the quick answer!

**Comment by mikedh** [comment]
No worries, do you need it to be `ply`? It would just work in `glb` 😄 

> quick clue where I might look for those transformations

You mean the inflating line segments? There's `trimesh.creation.sweep_path`, but it's probably not going to deal well with this specific case all that well and be slow:

https://github.com/mikedh/trimesh/blob/14ff34057ade2a55168fa511c78f721ad8a51e13/trimesh/creation.py#L206-L229

Beyond that I think you'd have to do the conversion yourself. By far the easiest way would be to call `trimesh.creation.cylinder` with the `segment` argument in a loop for every line segment, but that's gonna be pretty slow on big things:
https://github.com/mikedh/trimesh/blob/14ff34057ade2a55168fa511c78f721ad8a51e13/trimesh/creation.py#L889-L890

You could also implement it with numpy tiling, which would be fiddly but could conceivably be fast.

**Comment by dsvilarkovic** [comment]
Hmm, speed is not a problem, I have like 5 primitives used. I think I'll try the "slower" approach and see where it goes
