### ISSUE TITLE
Intersection between 2 meshes

### ISSUE THREAD

**Issue by ManuGraiph** [mikedh/trimesh#1674]
It's possible to get the intersection between two 'planar' meshes?

I have a bunch of really simple meshes (basically each one is 2 coplanar triangles making a square) with different rotations, and i'm trying to get the intersection line from pairs of them that intersect (or nothing when they don't).

Is this possible with any of the built-in methods in trimesh?

**Comment by ManuGraiph** [comment]
Any news on this?

**Comment by mikedh** [comment]
Hey, yeah nothing comes to mind inside of trimesh that would help all that much. Maybe start with an `rtree` for each separate body (or if they're all in one mesh, `mesh.triangles_tree`) and then look for pairs, and then just find the plane-plane intersection line and clip it to the AABB?

This could possibly be implemented more generally as `trimesh.intersections.mesh_mesh` that returned a list of line segments similar to `mesh_plane` but it seems like it gets a lot more complicated than the mesh-plane case.

**Comment by ManuGraiph** [comment]
Thanks Mike, but i pretty much ported the entire project to `vedo` by now.
