### ISSUE TITLE
Regarding the Error "Data not utf-8! Trying ISO-8859-1 (confidence 0.73)"

### ISSUE THREAD

**Issue by miyukin73** [mikedh/trimesh#1676]
Hi!

I would like to convert the attached [cup_stl.zip](https://github.com/mikedh/trimesh/files/9493685/cup_stl.zip) file to an obj file.

I have tried to run the program as per the answers given on [this site](https://github.com/deepmind/mujoco/discussions/357#discussioncomment-3011107).

`mesh = trimesh.load("cup.stl")`
However, when I run the above program, I get the following error ....
<img width="238" alt="image" src="https://user-images.githubusercontent.com/63595993/188558848-8b0f82ed-2f66-4e58-8a0c-36f27b60bd56.png">

What is the problem?
I would appreciate it if you could let me know.
Thank you in advance!

**Comment by mikedh** [comment]
Hey, that's not an error, it's a `log.warning` call, the file still loads OK:
```
In [1]: import trimesh

In [2]: m = trimesh.load('cup.stl')
Data not utf-8! Trying MacCyrillic (confidence 0.5119798157077455)

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(96, 3), faces.shape=(188, 3))>

In [4]: m.metadata
Out[4]: 
{'header': 'STLB ATF 11.7.0.108 COLOR=ццу€',
 'processed': True,
 'file_path': '/media/psf/Home/Downloads/cup.stl',
 'file_name': 'cup.stl'}

In [5]: m
Out[5]: <trimesh.Trimesh(vertices.shape=(96, 3), faces.shape=(188, 3))>
```

It's complaining about the file header not being UTF-8, which is true but fine to ignore.
