### ISSUE TITLE
Is OpenCTM support a planned feature?

### ISSUE THREAD

**Issue by lejafar** [mikedh/trimesh#168]
Hi!

I really like this project and I was just wondering whether support for OpenCTM is something that is on the list or is left out on purpose as it might lead to far?

Thanks!

**Comment by mikedh** [comment]
Hey, I'd never heard of OpenCTM. It looks pretty similar in design intent to [Google's Draco](https://github.com/google/draco), which trimesh will use if installed. On Linux you could install it with [this shell script](https://github.com/mikedh/trimesh/blob/master/docker/builds/draco.bash). Draco has a three.js loader and people were looking in to supporting it inside GLTF which would be cool. 

So- no plans to support OpenCTM, though PR's are always welcome.

**Comment by lejafar** [comment]
#169 :)

**Comment by mikedh** [comment]
Awesome! I'll close this and we can discuss in the PR.
