### ISSUE TITLE
Section vertices is not ordered

### ISSUE THREAD

**Issue by datased2019** [mikedh/trimesh#1680]
Hi. One question about get the vertices of slice Path2D. It seesm the vertices get from Path2D is not ordered. Any comments?
![Figure_2](https://user-images.githubusercontent.com/48910575/189268739-a9391300-1562-4a62-9c9f-b9247e0d4fd8.png)

**Comment by mikedh** [comment]
#Hey the vertices are referenced by `path.entities`. You probably want `path.discrete` which is a sequence of closed loops in `(n, 2) float` form.

**Comment by datased2019** [comment]
Thx for quick reply. It works.

**Comment by datased2019** [comment]
Thx for quick reply. It works.
