### ISSUE TITLE
ModuleNotFoundError: No module named 'mapbox_earcut'

### ISSUE THREAD

**Issue by joamatab** [mikedh/trimesh#1691]
when going from  `trimesh-3.14.1-py3-none-any.whl` to `trimesh-3.15.1-py3-none-any.whl` we get a 
```
ModuleNotFoundError: No module named 'mapbox_earcut'
```

see [sucess](https://github.com/gdsfactory/gdsfactory/actions/runs/3065479817/jobs/4949624026)

and [failed](https://github.com/gdsfactory/gdsfactory/actions/runs/3077785634/jobs/4972891238)

maybe it's missing a dependency requirement for `mapbox_earcut`

**Comment by mikedh** [comment]
Yeah this was related to https://github.com/mikedh/trimesh/pull/1683 where triangle was removed for license issues.

Probably have to merge this: https://github.com/conda-forge/trimesh-feedstock/pull/406

**Comment by mikedh** [comment]
So mapbox-earcut has wheels, but may need conda packages: https://github.com/skogler/mapbox_earcut_python

I don't know enough about conda to know whether it can just be marked as "use the wheel" or not, but PR's in the `trimesh-feedstock` repo welcome!

**Comment by mikedh** [comment]
Actually looks like they have a conda package already: https://github.com/conda-forge/trimesh-feedstock/pull/407

Hopefully this addresses this issue:
 https://github.com/conda-forge/trimesh-feedstock/pull/407

**Comment by joamatab** [comment]
perfect,

we are using pip as the main tool, but having it in conda is also great

we fixed by adding `mapbox_earcut` in `requirements.txt`

https://github.com/gdsfactory/gdsfactory/compare/v5.31.0...v5.31.1?expand=1
