### ISSUE TITLE
Saving the exported mesh `question`

### ISSUE THREAD

**Issue by Blessing92** [mikedh/trimesh#1694]
`mesh = generate(img)`
`generated_mesh = mesh.export(file_type='off')`

I have the code above implemented; it generates a mesh from an input image. I would like to know if there is a way of saving the mesh to external storage such as AWS S3 bucket instead of saving it locally. I tried to use `upload_to_s3(generated_mesh)`; but the documentation says: 
- Returns export – OFF format output
- Return type str

Therefore, can not upload a string as the 'mesh.export' returns a string. 

Thank you!

**Comment by mikedh** [comment]
Hey, I think you want something like this: https://stackoverflow.com/questions/40336918/how-to-write-a-file-or-data-to-an-s3-object-using-boto3

**Comment by Blessing92** [comment]
Thank you for your fast reply. Maybe my question wasn't clear, I try to rephrase it.
This line `generated_mesh = mesh.export(file_type='off')` does not return an object like `generated_mesh.off` instead a string which can't be save to S3.

Is there a way in trimesh documentation that the export returns the object instead of a str?

**Comment by mikedh** [comment]
If you need the exported result as a file object you can use `wrap_as_stream`:
```
In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [3]: export = m.export(file_type='off')

In [4]: type(export)
Out[4]: str

In [5]: len(export)
Out[5]: 430

In [6]: obj = trimesh.util.wrap_as_stream(export)

In [7]: obj
Out[7]: <_io.StringIO at 0x7fd17b1329e0>

```
