### ISSUE TITLE
How to set mesh root

### ISSUE THREAD

**Issue by emircetinmemis** [mikedh/trimesh#1695]
Hi,

I have been trying to figure out some solutions to my studies problems and they are actually starting with the load method of trimesh.

I was wondering if there is any way to change the root (the first vertice) of a mesh with another.

My purpose is to make the node with minimum y coordinate the root. For example, I have the x,y,z coordinates needed to be root, can I do some search on mesh, to find out the vertex id of the needed root, and create or modify the mesh with that by putting it to the first vertice.

I have tried some solutions, but they are distrubing the structure of my mesh.

**Comment by mikedh** [comment]
Hey, the order of the vertices generally only matters reletative to faces, and there isn't really a concept of a "root" vertex. That being said the easiest way to switch the order of the vertices around is with `mesh.update_vertices` using a mask:

```
In [1]: import trimesh

In [2]: m = trimesh.creation.icosphere()

In [3]: pre = m.volume

In [4]: pre
Out[4]: 4.152740817093058

In [5]: import numpy as np

In [6]: mask = np.arange(len(m.vertices))

In [7]: len(mask)
Out[7]: 642

In [8]: index = m.vertices[:,1].argmin()

In [9]: index
Out[9]: 13

In [10]: m.vertices[0]
Out[10]: TrackedArray([-0.52573111,  0.85065081,  0.        ])

In [11]: m.vertices[index]
Out[11]: TrackedArray([ 0., -1.,  0.])

In [12]: mask[0] = index

In [13]: mask[index] = 0

In [14]: m.update_vertices?
Signature: m.update_vertices(mask, inverse=None)
Docstring:
Update vertices with a mask.

Parameters
------------
vertex_mask : (len(self.vertices)) bool
  Array of which vertices to keep
inverse : (len(self.vertices)) int
  Array to reconstruct vertex references
  such as output by np.unique
File:      ~/trimesh/trimesh/base.py
Type:      method

In [15]: m.update_vertices(mask)

In [16]: np.isclose(m.volume, pre)
Out[16]: True

In [17]: m.vertices[0]
Out[17]: TrackedArray([ 0., -1.,  0.])


```
