### ISSUE TITLE
Colors no longer function.

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#17]
Example program (basically straight from README.md)

    import trimesh

    mesh = trimesh.load_mesh([PLACE_STL_FILENAME_HERE])

    # find groups of coplanar adjacent faces
    facets, facets_area = mesh.facets(return_area=True)

    # set each facet to a random color
    for facet in facets:
      mesh.visual.face_colors[facet] = trimesh.visual.random_color()

    # preview mesh in an opengl window if you installed pyglet with pip
    mesh.show()

**Comment by Marviel** [comment]
Error received is thus: 

    File "examples/color_example.py", line 10, in <module>
    mesh.visual.face_colors[facet] = trimesh.visual.random_color()
    ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (10,4)

**Comment by Marviel** [comment]
using version 1.14.5

**Comment by mikedh** [comment]
Good catch, thanks. Should be fixed in https://github.com/mikedh/trimesh/commit/0e4f6080c30c579cee7cbfdec4b780efc0caf037. Added a test which hopefully lets travis get this in the future. Definitely a symptom of the questionable data model in VisualAttributes objects :-D.

**Comment by Marviel** [comment]
Sweet thanks!

And lmao as I was looking through the code I laughed quite hard at your "dumpster fire" comment
