### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by norheim** [mikedh/trimesh#170]
There used to be extensive documentation on the API, and this has for some reason disappeared. Would appreciate if it was brought back!

**Comment by mikedh** [comment]
Yeah for some reason (probably related to `numpydoc` 🙄 ) the module reference stopped building. It's still building the basic docs on [readthedocs](https://trimesh.readthedocs.io/en/latest/index.html) but I know that's less useful. 

I'll try to poke at it in the next couple weeks, or PR's are always welcome 😄

**Comment by norheim** [comment]
That would be amazing; just having the auto generated documentation on methods to search through with readthedocs used to be great :) Might not be able to do a PR, but will keep checking back ;)

**Comment by mikedh** [comment]
Still needs some more work, but it's building and deploying to `gh-pages` via travis. I switched from readthedocs as it was pretty hard to debug their build process:
https://mikedh.github.io/trimesh

**Comment by mikedh** [comment]
Closing as docs are now building with travis and deploying to https://trimsh.org/
