### ISSUE TITLE
Loading a glb scene leads to inconsistent results

### ISSUE THREAD

**Issue by mich-sanna** [mikedh/trimesh#1700]
A randomly generated scene, saved as `glb` by trimesh itself, can be loaded differently if `force='mesh'` or otherwise.

I hope this shows what i mean? code below

<img src=https://user-images.githubusercontent.com/54891577/193264525-f6bc591a-5365-4256-8220-23695583ddbe.png width="320"/>
<img src=https://user-images.githubusercontent.com/54891577/193264555-25e85830-a832-4e79-ada8-01fa76740d07.png width="320"/>

```
import os
import tempfile

import numpy as np
import trimesh
from trimesh import creation
print('trimesh version:', trimesh.version.__version__)

show_args = {"resolution": (640, 480)}

np.random.seed(1234)

scene = trimesh.Scene()
for i in [0.1, 0.5]:
    scene.add_geometry(creation.cylinder(i, height=10),
                       transform=trimesh.transformations.random_rotation_matrix())

tmp_folder = tempfile.mkdtemp()
path = os.path.join(tmp_folder, 'mesh.glb')

scene.export(path)

mesh = trimesh.load(path)
print(type(mesh))
print(mesh.bounds)
mesh.show(**show_args)

mesh = trimesh.load(path, force='mesh')
print(type(mesh))
print(mesh.bounds)
mesh.show(**show_args)
```

output:
```
trimesh version: 3.15.2
<class 'trimesh.scene.scene.Scene'>
[[-4.44899564 -3.68903924 -3.37512489]
 [ 4.44899564  3.68903924  3.37512489]]
<class 'trimesh.base.Trimesh'>
[[-4.38691122 -3.67445082 -3.26336005]
 [ 4.38691122  3.67445082  3.26336005]]

```

**Comment by mikedh** [comment]
Yeah I think this is the scene vs mesh AABB? 

For the scene AABB with instances and transforms it's taking the corners of each mesh AABB and transforming it into the scene and taking the overall bounds of those transformed AABB's. For the dump-into-single-mesh it's checking the AABB of all vertices for an exact answer. It was done to avoid having to do a lot of computation for each instance (i.e basically to avoid having to run something like `scene.dump` which is pretty slow), seems like the options are:

- Compute the convex hull of each mesh and use these points for the scene AABB (probably exact). 
- Transform all mesh vertices for every instance to compute scene bounds (exact) 
- update scene docstring to say "it's an approximate AABB that contains all instances of geometry but may be larger than necessary"
- do something clever, somehow. 


```
In [1]: import trimesh
m
In [2]: m = trimesh.load('models/cycloidal.3DXML')

In [3]: m.bounds
Out[3]: 
array([[-76.11890971, -76.12034667, -28.275324  ],
       [ 76.11890971,  76.12034667,   3.65      ]])

In [4]: m.dump(concatenate=True).bounds
Out[4]: 
array([[-53.88605363, -53.8728736 , -28.275324  ],
       [ 53.81389379,  53.8598054 ,   3.65      ]])

```
