### ISSUE TITLE
How to enclose 3D path (non-planar) in order to make a watertight mesh?

### ISSUE THREAD

**Issue by LahkarBK** [mikedh/trimesh#1703]
I have a trimesh object, where both the ends of the object are not closed (not watertight). From the open-end boundaries, I have obtained 3D paths  with _trimesh.path.Path3D_ command. The paths are not planar (cyan in color).  Now, I want to enclose the paths in order to make a watertight mesh. This will help to calculate the volume of the object and other mass properties. 

Please help to enclose the object from both the ends. 
![Path-enclose](https://user-images.githubusercontent.com/40695512/193875840-247bdd92-d89a-4dc4-8b07-91f5901e1154.png)

**Comment by mikedh** [comment]
Hey, it's not necessarily super well defined what the cap is supposed to do, but for that mesh you might try just the convex hull (`mesh.convex_hull`) or `trimesh.repair.stitch(mesh, insert_vertices=True)`:
```
In [1]: import trimesh
tr
In [2]: trimesh.repair.stitch?
Signature: trimesh.repair.stitch(mesh, faces=None, insert_vertices=False)
Docstring:
Create a fan stitch over the boundary of the specified
faces. If the boundary is non-convex a triangle fan
is going to be extremely wonky.

Parameters
-----------
vertices : (n, 3) float
  Vertices in space.
faces : (n,) int
  Face indexes to stitch with triangle fans.
insert_vertices : bool
  Allow stitching to insert new vertices?

Returns
----------
fan : (m, 3) int
  New triangles referencing mesh.vertices.
vertices : (p, 3) float
  Inserted vertices (only returned `if insert_vertices`)
File:      ~/trimesh/trimesh/repair.py
Type:      function

```

**Comment by LahkarBK** [comment]
Hi thanks for your previous reply. 
To explain more about my problem:
I have different types of meshes of human body segments, including the hand (image below). But these meshes are not watertight as can be seen in the following image for example. I want to close the open end in order to make the hand mesh watertight. mesh.convex_hull  approximates the shape of the hand itself, which i don't need.  
I also tried using trimesh.repair.stitch with the face _ids of the boundary faces. Although, it closes the open end, but additionally it also stitches the other end of the faces, which I don't require. 

**Is there any  solution in trimesh to fill the open end, given either face ids  or  vertex coordinates at the boundary?** 

![image](https://user-images.githubusercontent.com/40695512/202712729-01754db4-be7d-4313-9b40-ceb2c25d6ce0.png)
