### ISSUE TITLE
Unable to import over 2000KB STEP file

### ISSUE THREAD

**Issue by plourr03** [mikedh/trimesh#1705]
Hello, I am trying to convert an stp file a mesh and it was working great until I try and bring in an stp file over 2000 KB. is there a size limit to what stp files we can convert? When I run the files over 2000 it just spins forever with erroring, it runs in about 5 second for any file under 2000KB. is there settings i need to change or anything? Here is the code I am using 

```trimesh.Trimesh(**trimesh.interfaces.gmsh.load_gmsh(file_name=file_location, gmsh_args = [("Mesh.Algorithm", 1),("Mesh.CharacteristicLengthFromCurvature", 35), ("General.NumThreads", 10),("Mesh.MinimumCirclePoints", 10)]))```

**Comment by mikedh** [comment]
You might try `pip install cascadio` which uses OpenCASCADE directly, and then you can just run `trimesh.load('file.step')`
