### ISSUE TITLE
Possible regression when calculating scene bounds from point clouds

### ISSUE THREAD

**Issue by manuel-koch** [mikedh/trimesh#1706]
We use the following code to calculate the aabb of a scene with lots of point clouds:

```
from trimesh import Scene as TrimeshScene
from trimesh.points import PointCloud as TrimeshPointCloud

scene = TrimeshScene()
....
for group in enabled_groups:
    for instance in group.model_instances:
        trimesh_obj = TrimeshPointCloud(vertices=instance.model.vertices)
        trimesh_obj.apply_transform(
            numpy.array(instance.transformation.transformation_matrix.T)
        )
        scene.add_geometry(trimesh_obj)
scene.apply_transform(rotation_matrix)
bounds = scene.bounds
```

This used to work as expected with `trimesh[easy]==3.12.8` but yields different results with `trimesh[easy]==3.15.3`.
I.e. the same code to build the scene ( see above ) with exactly the same data ( too much to post it here ) now yields different results, not only slightly different but considerably different, resulting in follow up errors in our code with respect to the calculated scene bounds.
E.g. the bounds using 3.12.8 are
```
[[ -776.63376945    32.50285277 -1183.45313151]
 [  916.15016295  2263.95641221   930.55045636]]
```
and for 3.15.3 they are
```
[[ -872.21620021   -25.68069214 -1248.87499273]
 [  937.30608549  2264.78514331   931.98589844]]
```

I pinned all our dependencies and it actually boils down to an upgrade of our used trimesh version.
Looking at the changes in the trimesh releases I could not identify a possible cause.

**Comment by manuel-koch** [comment]
I narrowed it down a little bit:
3.12.9 is good
3.13.0 gives different results

**Comment by manuel-koch** [comment]
Maybe this is causing problems: [trimesh/scene/scene.py](https://github.com/mikedh/trimesh/commit/826eddff1ae51c44db446f92b6bf5ef5258dd2c7#diff-ca32a0d8ba8797d75dd5b182a7a27d1443a725b244f44e31ec511d471ffa677a)

Has the use case of `apply_transform()` changed ?
```
Apply a transform to every geometry in the scene.
```
vs
```
Apply a transform to all children of the base frame
without modifying any geometry.
 ```
 I'm not sure what this doc change implies with respect to how I intend to use `apply_transform()` in my code snippet.

**Comment by mikedh** [comment]
Yeah, this was changed in https://github.com/mikedh/trimesh/pull/1637 because of very wrong results in certain cases: https://github.com/mikedh/trimesh/issues/1639

I think this is the "exact vs transformed AABB corners" issue, I enumerated the options in https://github.com/mikedh/trimesh/issues/1700
