### ISSUE TITLE
proper way to release memory

### ISSUE THREAD

**Issue by yscoffee** [mikedh/trimesh#171]
Hi,
Thanks for the wonderful library.
I am trying to do some batch processing by using trimesh and wondering is there a way to enforce trimesh to release memory?
It seems some info. are keeping in trimesh. See the examples below.
```
import trimesh
import gc
model_path = 'test.ply'
```
##### initial memory usage: 695.8 MB

```
for i in range(50):
    model = trimesh.load_mesh(model_path)
    del model
gc.collect()
```
##### current memory usage: 1.11 GB
====================================
test 2

```
import multiprocessing, random, sys, os, time
import trimesh
import gc
```
##### initial memory usage: ##695.7 MB
```

def run_test(model_path,test_times):
    for i in range(test_times):
        model = trimesh.load_mesh(model_path)
        del model
    gc.collect()

model_path =  'test.ply'

p = multiprocessing.Process(target=run_test, args=(model_path,50,))
p.start()
p.join()
print('job done')

```
##### current memory usage: ##701.9 MB (seems memory is freed)

**Comment by mikedh** [comment]
I think this is a broader Python issue. The solution I've been going with is to either use subprocess like you did, or have an application exit now and then and be restarted by something like `supervisord`.

**Comment by yscoffee** [comment]
thanks for checking this
