### ISSUE TITLE
face_adjacency_angles - its max value is lower than 10 degrees - is this supposed to be so low?

### ISSUE THREAD

**Issue by aprath1** [mikedh/trimesh#1711]
The property - **face_adjacency_angles** - when tried on some 3D meshes gives values which are less than 10 degrees (0.17 radians).  But the models have many adjascent faces that have angles more than 30 degrees. Sample object I tried is below:

<img src="https://user-images.githubusercontent.com/88531660/195124675-5e6c0276-b64f-48d5-9846-5b8511b2d5e3.jpg" width="250" />

[BLTBracket.obj.zip](https://github.com/mikedh/trimesh/files/9757196/BLTBracket.obj.zip)

So for example, if there are 2 faces which are adjacent and are lying on mutually perpendicular regions then the angle should be 90 degrees right. Is this not what **face_adjacency_angles** mean?

**Comment by aprath1** [comment]
Hi,
thanks for your reply. 
It is clear from the above example of the trimesh box about the angles between adjacent faces (I computed just now manually as well for the `trimesh.creation.box()`). 

So, for the above BLTBracket object there should be still some adjacent angles which are definitely greater than 10 degrees right? I am not getting any... is there any issue for bigger or slightly complicated meshes?


```
import trimesh
import numpy as np

mesh_path = "BLTBracket.obj"
mesh_1 = trimesh.load(mesh_path)

# check maximum vlalue of the face adjascency angles
np.degrees(mesh_1.face_adjacency_angles).max()

Out: 0.6300581


```

I have also attached '.obj' file of the BLTBracket  object above in a '.zip' format, so you can test it from your side as well. I just took the mesh from this open mesh resource -> https://www.thingiverse.com/thing:3179892

**Comment by mikedh** [comment]
> So, for the above BLTBracket object there should be still some adjacent angles which are definitely greater than 10 degrees right? I am not getting any... is there any issue for bigger or slightly complicated meshes?

I think the issue is that file has explicit vertex normals which would stop trimesh from merging vertices without identical normals, which would then make `face_adjacency` not include what you would expect. It's a little confusing but you can force it to merge vertices ignoring vertex normals:
```
In [22]: m.merge_vertices?
Signature:
m.merge_vertices(
    merge_tex=None,
    merge_norm=None,
    digits_vertex=None,
    digits_norm=None,
    digits_uv=None,
)
Docstring:
Removes duplicate vertices grouped by position and
optionally texture coordinate and normal.

Parameters
-------------
mesh : Trimesh object
  Mesh to merge vertices on
merge_tex : bool
  If True textured meshes with UV coordinates will
  have vertices merged regardless of UV coordinates
merge_norm : bool
  If True, meshes with vertex normals will have
  vertices merged ignoring different normals
digits_vertex : None or int
  Number of digits to consider for vertex position
digits_norm : int
  Number of digits to consider for unit normals
digits_uv : int
  Number of digits to consider for UV coordinates
File:      ~/trimesh/trimesh/base.py
Type:      method

In [23]: m.merge_vertices(merge_tex=True, merge_norm=True)

In [24]: np.degrees(m.face_adjacency_angles.max())
Out[24]: 148.23092684152317

```

**Comment by aprath1** [comment]
Hi,
Perfect!
I just tested it out and also did some post processing with the computed **face_adjacency_angles**, it works now as I expected. 
Thank you so much...
