### ISSUE TITLE
No module named 'networkx'

### ISSUE THREAD

**Issue by plourr03** [mikedh/trimesh#1717]
Hello when I run code to try and create a convex_hull I get the error "No module named 'networkx'". see below 

Code:
` import trimesh`
`mesh = trimesh.load_mesh("*STL FILE PATH*")`
`mesh.convex_hull`

Error:

`ModuleNotFoundError: No module named 'networkx'`

**Comment by mikedh** [comment]
I think you probably want to run `pip install trimesh[easy]` or `pip install networkx`.
