### ISSUE TITLE
conda forge package stuck due to linting issue

### ISSUE THREAD

**Issue by Krande** [mikedh/trimesh#1723]
Hey,

looking at https://github.com/conda-forge/trimesh-feedstock/pull/412#issuecomment-1291211941
it seems conda forge has some new (to me at least) linting routines, so it asks for a minimum version of python in the meta.yaml file

From linting issue brought up from the conda-forge linting bot:
```
For recipe:

noarch: python recipes are required to have a lower bound on the python version. 
Typically this means putting python >=3.6 in both host and run but you should check upstream 
for the package's Python compatibility.
```

If you want I can make a PR for this?

Best Regards
Kristoffer

**Comment by mikedh** [comment]
Thanks for the report! Hopefully this is fixed, and it looks like some combination of the bots updated the package on anaconda.org.
