### ISSUE TITLE
Object orientation when sampling and visualizing do not match

### ISSUE THREAD

**Issue by HabibSlim** [mikedh/trimesh#1739]
trimesh uses a three.js script to visualize loaded models through the ```show()``` function.
The script seems to manage the centering of the objects better than I do. When I ```show()``` the objects, here is what I get:

<img src="https://i.ibb.co/V3LkzZG/Screenshot-from-2022-11-07-02-10-07.png" style="height: 250px;" />
<img src="https://i.ibb.co/pRbDPmM/Screenshot-from-2022-11-07-02-10-03.png" style="height: 250px;" />

When I simply load the objects and **sample points from their surfaces**, this is what I get:

<img src="https://i.ibb.co/jgYy0wG/Screenshot-from-2022-11-07-02-09-48.png"
     style="height: 250px;" />

**I cannot find any info on how to find the relevant transformations to get the objects properly oriented.** It seems that the three.js script does that but it's minified.

Thanks in advance for your help

**Comment by mikedh** [comment]
Oh, you may want `scene.camera_transform` or `trimesh.scene.camera.look_at`:
```
In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [3]: s = trimesh.Scene(m)

In [4]: s
Out[4]: <trimesh.Scene(len(geometry)=1)>

In [5]: s.camera_transform
Out[5]: 
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.        ,  0.        ,  1.        ,  1.70710678],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]: print(trimesh.scene.cameras.look_at.__doc__)

    Generate transform for a camera to keep a list
    of points in the camera's field of view.

    Examples
    ------------
    ```python
    points = np.array([0, 0, 0], [1, 1, 1])
    scene.camera_transform = scene.camera.look_at(points)
    ```

    Parameters
    -------------
    points : (n, 3) float
      Points in space
    fov : (2,) float
      Field of view, in DEGREES
    rotation : None, or (4, 4) float
      Rotation matrix for initial rotation
    distance : None or float
      Distance from camera to center
    center : None, or (3,) float
      Center of field of view.

    Returns
    --------------
    transform : (4, 4) float
      Transformation matrix from world to camera
    

```

**Comment by HabibSlim** [comment]
Thank you for the prompt reply!

Unfortunately ```camera_transform``` only gives me a translation transformation, while the object is clearly rotated when I use ```sample_surface``. Here is the matrix I get:

```
array([[ 1.        ,  0.        ,  0.        ,  0.00899342],
       [ 0.        ,  1.        ,  0.        ,  0.03996095],
       [-0.        ,  0.        ,  1.        ,  0.1233544 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
```

Same thing with ```obj.camera.look_at``` using sampled points from the object (gives almost exactly the same translation).
I'm still puzzled as to why three.js seems to manage to display the object in its proper orientation (same thing in blender), while the "natural" orientation in trimesh seems to be rotated.

I can't find any rotation transformation while looking at the loaded object's properties. Do you maybe have ideas as to where I could find them?

Thanks in advance!

**Comment by HabibSlim** [comment]
You will find a minimal working example below:

```python
import trimesh
import numpy as np
import matplotlib.pyplot as plt

FILE_URL = "https://3dcompat-dataset.s3-us-west-1.amazonaws.com/GLB/0a3f7bbf-d96a-43ca-b1d1-0358927dad6e.glb"

def load_obj(force_mesh=False):
  obj = trimesh.load_remote(FILE_URL, force='mesh' if force_mesh else 'scene')
  return obj

obj = load_obj()
obj.show()
```

Result:

<img src="https://i.ibb.co/pRbDPmM/Screenshot-from-2022-11-07-02-10-03.png" style="height: 250px;" />


```python
n_points = 8096
obj = load_obj(force_mesh=True)
pc, sample_id = trimesh.sample.sample_surface(obj, count=n_points)
pc = np.array(pc).astype('float32')

def add_fig(pc, fig):
  ax = fig.add_subplot(1, 1, 1, projection='3d')
  ax.scatter(pc[:,0], pc[:,1], pc[:,2], s=2, cmap='viridis')

fig = plt.figure(figsize=(6, 6))
add_fig(pc, fig)
plt.show()
```

Result:

<img src="https://i.ibb.co/bBz0pVG/download.png" style="height: 250px;" />

Thanks for your time and sorry for the bother.

**Comment by HabibSlim** [comment]
It turns out that I just had a stupid axis problem. Thank you for your help.

**Comment by mikedh** [comment]
No worries! You can also visualize with `trimesh.Scene([mesh, trimesh.PointCloud(samples)])` if you want to see if they're aligned.
