### ISSUE TITLE
Add trimesh to conda-forge?

### ISSUE THREAD

**Issue by pauldmccarthy** [mikedh/trimesh#174]
Hi Mike,

I am in the process of adding my software libraries to conda-forge, and was wondering whether you would object to me adding a feedstock for trimesh (which my libraries are dependent, and for which I am very thankful)? I am happy to have a go at setting up the initial feedstock, and adding you as a maintainer (if you are happy with that).

As trimesh is pure-python, and its core dependencies are already on conda-forge, I can't imagine that there would be much of a barrier. Or are there some complexities that would make it difficult to get trimesh on conda-forge?

Cheers,

**Comment by mikedh** [comment]
That would be great! Conda-forge is awesome, let me know if you need help with anything. It should be very straightforward, as you say trimesh is pure python with soft dependencies on built modules. 

Best,
Mike

**Comment by pauldmccarthy** [comment]
Great! Can you just confirm that you're happy to be added as a maintainer? 

I'm new to this conda-forge stuff, but I was very pleasantly surprised to receive a PR on my [fsleyes-widgets feedstock](https://github.com/conda-forge/fsleyes-widgets-feedstock/pull/1) which had been automatically triggered by me releasing a new version to PyPi! So it seems that maintenance will be a pretty low key affair :)

**Comment by mikedh** [comment]
Yeah, definitely happy to maintain it- nice they set up a PR-bot!

**Comment by mikedh** [comment]
https://github.com/conda-forge/staged-recipes/pull/6033 merged. That `run_constrained` is pretty cool if it does what I think it does (install everything it can from the list on the current platform/python). I'll test a little bit then change the recommended install method to `conda install -c conda-forge trimesh`. 

Thanks!
