### ISSUE TITLE
Would it be possible to Color faces independent of vertex colors?

### ISSUE THREAD

**Issue by aprath1** [mikedh/trimesh#1748]
Can we take the mesh faces as an independent entity from the perspective of colors and assign color to them, independent of the vertex color?
For example, in the below case of a trimesh box I have the face 0 and 1 of the box assigned red color and the remaining all faces assigned green, but the visualization gives a mixture of red and green for faces 0 and 1 => face color is derived from vertex colors, right? So, would it be possible to Color faces independent of vertex colors?
```
import trimesh
mesh = trimesh.creation.box()
mesh.visual.face_colors = np.array([0, 255, 0, 255])  # green color to all faces
mesh.visual.face_colors[:2] = np.array([255, 0, 0, 255])  # red color to only face 0 and 1
```

<img src="https://user-images.githubusercontent.com/88531660/202150615-6884eab8-0af0-40b8-b7c7-bc4a9f1c32a0.jpg" width="250" height="250" />

**Comment by mikedh** [comment]
Oh, yeah have you tried `mesh.show(smooth=False)`:

```
In [16]: mesh = trimesh.creation.box()

In [17]: m.visual.face_colors = trimesh.visual.color.interpolate(np.arange(len(mesh.faces)))

In [19]: mesh.show()
Out[19]: SceneViewer(width=1800, height=1350)

In [20]: mesh.show(smooth=False)

```
![noblend](https://user-images.githubusercontent.com/1403074/204096715-a3327eb6-9f93-4f79-aaec-aa982bbc87d1.png)

**Comment by aprath1** [comment]
Thanks Mike! 
Well, that's my bad, I should have tried that boolean in the documentation of `trimesh.base.Trimesh.show`
