### ISSUE TITLE
extrusion fails on faces with duplicate vertices in one face

### ISSUE THREAD

**Issue by ct2034** [mikedh/trimesh#1753]
If the 2d polygon to extrude has duplicate vertices in the first face, extrusion fails because of the check in 
https://github.com/mikedh/trimesh/blob/main/trimesh/creation.py#L356.
Use this code to reproduce:
```
import numpy as np
import trimesh.creation

coords = np.array([[0, 0], [0, 0], [0, 1], [1, 0]])

mesh = trimesh.creation.extrude_triangulation(
    vertices=coords, faces=[[0, 1, 2], [0, 2, 3]], height=1
)
```
Detected in [303491c](https://github.com/mikedh/trimesh/commit/303491cbd187eeae2c6640c63988fbb89c755c47)
This leads to an error here: https://github.com/boschresearch/pcg_gazebo/actions/runs/3335964277/jobs/5520547249

**Comment by ct2034** [comment]
update: This seems to be a property of the generation of polygons:
```
import numpy as np
import trimesh.creation
from shapely.geometry import Polygon

coords = [[0, 0], [0, 1], [1, 0]]
print(len(coords))  # 3
p = Polygon(shell=coords)
print(len(p.exterior.coords))   # 4
trimesh.creation.extrude_polygon(p, height=1)
```
Which leads to the same error, because the polygon seems to automatically receive an additional vertex.

**Comment by mikedh** [comment]
Thanks for the report and test! I changed the sign check to be a little more robust to degenerate triangles which seemed to fix this case.
