### ISSUE TITLE
Convert DAE with multiple materials to OBJ

### ISSUE THREAD

**Issue by samraise** [mikedh/trimesh#1755]
Hi, I tried converting my DAE to an OBJ but the output OBJ and MTL only have one material.

`obj, mtl= trimesh.exchange.obj.export_obj(trimesh.load("forearm.dae"), include_color=True, include_texture=True, return_texture=True)
`

gives me OBJ and MTL files
```
# https://github.com/mikedh/trimesh
mtllib material_0.mtl
mtllib material_0.mtl
mtllib material_0.mtl
mtllib material_0.mtl
mtllib material_0.mtl

o shape0-mesh.0
usemtl material_0
v 0.00877374 -0.01182466 -0.05563282
v 0.00736695 0.05889075 -0.05583000
v 0.01221925 0.05889075 -0.05499798
v 0.00463438 -0.01161706 -0.05611497
v 0.01287806 -0.01216107 -0.05485183
v 0.01698356 0.05889075 -0.05375796
v -0.05786287 -0.03482002 -0.00228387
v -0.05799984 0.05889075 0.00169998
...

{'material_0.mtl': b'# https://github.com/mikedh/trimesh\nnewmtl material_0\nKa 0.40000000 0.40000000 0.40000000\nKd 0.07843137 0.07843137 0.07843137\nKs 0.40000000 0.40000000 0.40000000\nNs 1.00000000'}
```

**Comment by mikedh** [comment]
Heh yeah the multiple identical mtllibs isn't greeat, can you share the DAE that produced this?

**Comment by samraise** [comment]
Sure thing, [here's one](https://github.com/ros-industrial/universal_robot/blob/melodic-devel/ur_description/meshes/ur10/visual/forearm.dae) that produced an output like this. Thanks for the help!

**Comment by samraise** [comment]
Hey I tried the new release and it seems that even though there are no duplicate materials anymore, the OBJ file still doesn't contain the different materials in the DAE.

**Comment by mikedh** [comment]
Did this help? The OBJ/MTL it was producing from `forearm.dae` had 5 materials and Meshlab was displaying it correctly for me.

**Comment by samraise** [comment]
It did! Thank you for fixing this!

**Comment by mhubii** [comment]
not an issue, thank you for this great work @mikedh
