### ISSUE TITLE
how is the computation of face_adjacency_radius ?

### ISSUE THREAD

**Issue by aprath1** [mikedh/trimesh#1763]
Could someone help me understand or may be help me in visualizing how the computation of face_adjacency_radius is done?
The approach considers adjacent faces with zero face adjacency angle have the face_adjacency_radius = np.inf and I believe the span for these adjacent faces are taken as zero. I am not able to understand how this is possible, I guess it has to do with not getting how the circle is defined for the adjacent faces as well.

**Comment by Kiord** [comment]
I think this radius is related to the [radius of curvature](https://en.wikipedia.org/wiki/Radius_of_curvature). If a surface is very curvy on a particular point, it will have a small radius of curvature at this point. If a surface is almost flat on the observed point, then the radius of curvature will be large. If the surface is perfectly flat, the radius of curvature is infinite.

The formula used in trimesh to get the radius between to adjacent faces is :

$$
r = \frac{d}{2\sin{\frac{\theta}{2}}}
$$

Where $d$ is the span : the distance between the two opposite vertices in the direction perpendicular to the edge.

We see that :

$$
\lim\limits_{\theta→0, \theta > 0} \frac{d}{2\sin{\frac{\theta}{2}}} = +\inf
$$

**Comment by aprath1** [comment]
Thank you, really appreciate the comment!
The approach of considering radius of curvature as you mentioned above sounds good, and I think that is justifiable as well from the equations... (so closing the issue)
