### ISSUE TITLE
Error importing trimesh 3.17.1

### ISSUE THREAD

**Issue by larsgrobe** [mikedh/trimesh#1775]
Hi,
unfortunately I am not able to import trimesh any more due to the following error:

`path2DObj = trimesh.load_path(rays)`
`AttributeError: partially initialized module 'trimesh' has no attribute 'load_path' (most likely due to a circular import)`

I am not sure if this is due to an incompability with my site-packages, or a general problem of the latest version. I am on macport's python 3.10.8 in a virtual environment. I get the error if I load no other packages.
Best, Lars.

**Comment by mikedh** [comment]
Hey, I just checked a minimal install in both docker and on my mac and it looked OK. Can you try a more explicit import to see if it gets a better error message:
`from trimesh.path.exchange.load import load_path`

Working in a fresh install:
```
mikedh@orion:~$ docker run -it python:3.10-slim-bullseye /bin/bash
root@2fc0ab09659f:/# pip install trimesh
[Successfully installed numpy-1.23.5 trimesh-3.17.1

root@2fc0ab09659f:/# python
Python 3.10.8 (main, Nov 15 2022, 21:06:05) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trimesh
>>> trimesh.load_path([[0,0,0], [1,0,0]])
<trimesh.Path3D(vertices.shape=(2, 3), len(entities)=1)>
>>> 

root@2fc0ab09659f:/# pip install trimesh[easy]
Successfully installed attrs-22.1.0 certifi-2022.9.24 chardet-5.1.0 charset-normalizer-2.1.1 colorlog-6.7.0 idna-3.4 jsonschema-4.17.3 lxml-4.9.1 mapbox-earcut-1.0.1 mpmath-1.2.1 msgpack-1.0.4 networkx-2.8.8 pillow-9.3.0 pycollada-0.7.2 pyglet-1.5.27 pyrsistent-0.19.2 python-dateutil-2.8.2 requests-2.28.1 rtree-1.0.1 scipy-1.9.3 shapely-1.8.5.post1 six-1.16.0 svg.path-6.2 sympy-1.11.1 urllib3-1.26.13 xxhash-3.1.0

root@2fc0ab09659f:/# python
Python 3.10.8 (main, Nov 15 2022, 21:06:05) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trimesh
>>> trimesh.load_path([[0,0,0], [1,0,0]])
<trimesh.Path3D(vertices.shape=(2, 3), len(entities)=1)>
```

**Comment by larsgrobe** [comment]
Hi Mike, I set

`include-system-packes = false`

and re-installed shapely. However,  this does not solve the problem yet, I get the very same error (also with `from trimesh.path.exchange.load import load_path`).

I can try to uninstall all macports-provided python packages to find out if there is any collisions with other modules causing this. However, that will take me a while.

Thank you for your support! Best, Lars.

**Comment by larsgrobe** [comment]
This was a stupid mistake... I had a file "trimesh.py" in one of the directories that caused the circularity. Sorry for bringing this up! Best, Lars.
