### ISSUE TITLE
Create a mesh from a point cloud using trimesh

### ISSUE THREAD

**Issue by maurock** [mikedh/trimesh#1776]
Hi, I am sorry if this is not the right place to post this question. If so, I'll close the issue. First of all, thank you for this amazing library and for your support.

I am trying to generate a simple triangle mesh from a point cloud. I don't have face normals or the vertex ordering (*faces*). The mesh that I am trying to reconstruct is a simple curved plane, and it does not need to be watertight.

Other libraries, such as `open3D`, have a few methods to estimate normals from a point cloud and then generate a mesh. This can be done using the Ball Pivoting method, Screened Poisson Surface Reconstruction, and a few other methods.

I am looking for similar ways to reconstruct a mesh using `trimesh`. The closest approach I found reading the documentation is to use the *convex_hull* attribute of a PointCloud. However this method often fails for my use case, especially when the points lie on a plane. Thank you for any suggestions you might have.

**Comment by mikedh** [comment]
Hey, yeah `convex_hull` should work in pretty much every case except for "points are all coplanar`. Maybe check to see if the points are coplanar with `trimesh.points.plane_fit` and if so special case handle them via an "epsilon thick" extrusion or something?

**Comment by maurock** [comment]
Thank you very much @mikedh, I'll do that!
