### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [mikedh/trimesh#178]
Hi Sir @mikedh , I am a graphics designer and i want to contribute to your nice project by proposing a logo design for it. I  will do it as a gift for free, just let me know if i can start my design with your permission.
Thanks and best regards!

- [Tobaloidee](https://github.com/Tobaloidee)

**Comment by mikedh** [comment]
Yeah, that could be great! What did you have in mind?

Thanks!
Mike

**Comment by Tobaloidee** [comment]
I will post hete my initial draft Sir.thanks!

**Comment by Tobaloidee** [comment]
Hi Sir, here's what i have designed. 3 versions all based from triangular shapes with mesh lines idea. aquatic color. Please let me know if you have any idea or modifications.

version A
![trimesh-01](https://user-images.githubusercontent.com/36028424/41208419-e9c5f6de-6d55-11e8-9e7c-906987e11c63.png)

version B
![trimesh-02](https://user-images.githubusercontent.com/36028424/41208424-f0de3936-6d55-11e8-8d81-3e81552cb978.png)

version C
![trimesh-03](https://user-images.githubusercontent.com/36028424/41208429-f6c9f4e8-6d55-11e8-8826-14c375b7630b.png)

**Comment by mikedh** [comment]
Looks great! Maybe version A with `trimesh` in lower case and a few different font/color options? 

Thanks!
Mike

**Comment by Tobaloidee** [comment]
Surely Sir! Glad that you liked it .will edit it and show you here asap..thanks!

**Comment by Tobaloidee** [comment]
for the logomark color options

![logomark options-01](https://user-images.githubusercontent.com/36028424/41250783-7fd9f226-6dea-11e8-99bd-d37ba29e20a4.png)
![logomark options-02](https://user-images.githubusercontent.com/36028424/41250786-801484f4-6dea-11e8-9cb4-72e37f58a475.png)

**Comment by mikedh** [comment]
Nice! I like the purple and font color D! If you wouldn't mind, maybe a few different font style options as well? 

Also, the project is MIT licensed, can you confirm that you are OK putting the logo under that license?

Thanks!
Mike

**Comment by Tobaloidee** [comment]
Im okay with it Sir...this is yours as my gift for free..here's the font choices sir..I'll make a PR and upload the svg & png files once you have chosen already.


![font choice-04](https://user-images.githubusercontent.com/36028424/41289539-b70eeade-6e7c-11e8-818f-4f6f86000162.png)
![font choice-05](https://user-images.githubusercontent.com/36028424/41289542-bc2a50ee-6e7c-11e8-9eeb-2e7cd1c150b2.png)

**Comment by mikedh** [comment]
Looks great! Lets go with `option i`. Feel free to just send me an SVG, or if you want to PR could you add it to `docs/images/`?

Thanks!
Mike

**Comment by Tobaloidee** [comment]
I will make a PR now Sir and upload the SVG and put it in the Readme file also.. :)

**Comment by Tobaloidee** [comment]
Done with the upload of svg and updated the readme with new logo Sir in this PR #180

**Comment by mikedh** [comment]
Merged and looks great, thanks!
