### ISSUE TITLE
normals in a hollow STL-geometry

### ISSUE THREAD

**Issue by ebknudsen** [mikedh/trimesh#1789]
Hi all,
I have an issue that pops up once in a while. I have as of yet not been able to pinpoint exactly what triggers the effect.
The situation is: I generate a set stl-files from STEP-models with a set of tools. 
In my application it is common that bodies share faces, which means that their tesselated representation must conform.
The stl-representation needs to be watertight and its normalvectors need to be pointing always outwards from a body. To do this I use trimesh functions is_watertight and fix_normals, which works well most of the time.

In cases where a body has a hollow inside, it sometimes happens that the "inner" faces of the body end up pointing to the "overall" outward, instead of outward from the body. I've attached a screenshot from paraview where a cylinder is surrounded by a cylindrical shell with touching surfaces (and hence identical nodes). The normal vectors of the outer shell is shown with pink vectors, whereas the inner cylinder's are shown in yellow. The inner pink vectors should for my application point inwards.
This is however obviously not the case.
![normal_glyphs](https://user-images.githubusercontent.com/855956/209195093-73306ca0-915b-48d0-8f8b-d5f281eadc8c.png)

Does anyone have any idea of why this would happen? I've found that in this case the normal vectors are simply untouched by trimesh and fix_normals.

I suppose it has something to do with what the notion of outwards is. Will continue digging into the trimesh source to see what I can find.

cheers
Erik

**Comment by ebknudsen** [comment]
I've realized that this kind of case would not be caught by the fix_normals algorithm. It relies on the divergence theorem and figures out if the computed volume of the solid is positive. This will be the case whatever way the "inner" normals point.

**Comment by mikedh** [comment]
Thanks for the report and apologies for having no good answers. I'm going to close and combine with the newer #2082 bug report.
