### ISSUE TITLE
slice_plane removes the texture information

### ISSUE THREAD

**Issue by umariqb** [mikedh/trimesh#1798]
I am using `mesh.slice_plane()` to split the mesh, but the resulting mesh doesn't contain texture/uv information. Any suggestion?

**Comment by mikedh** [comment]
Hey, yeah it is currently not implemented to handle interpolating the new UV coordinates during slice_plane, PR's welcome! Seems like some of the options are:

- Preserve the UV coordinates (or generalized vertex attributes) for faces that weren't changed. This seems like it'd be pretty easy/fast/correct but the boundary would be a bit janky. 
- track the vertex attributes during the [slice logic](https://github.com/mikedh/trimesh/blob/25cdfda4c3c2205ca3cc5b5aa42831dfc7d63ad2/trimesh/intersections.py#L574-L594) and then do barycentric interpolation. It may have the barycentric coordinates internally somewhere already or you could use `trimesh.triangles.points_to_barycentric`. This seems like it would end up being pretty complicated but would probably give the best results?
- As a post-processing step check the vertices by-position. By far the easiest but you have to add some logic for "which of these colocated vertices was the original vertex" maybe by looking at faces:
```
    m =	trimesh.load('models/fuze.obj')
    s = m.slice_plane(plane_origin=m.centroid,
                      plane_normal=[0,0,1])
    distance, index = m.kdtree.query(s.vertices)
    s.visual = m.visual.copy()
    s.visual.uv = m.visual.uv[index].copy()

```

**Comment by umariqb** [comment]
Hi @mikedh, 

Thanks a lot. I solved the problem with the third point.
