### ISSUE TITLE
KeyError when use openscad interface

### ISSUE THREAD

**Issue by AuroraHu001** [mikedh/trimesh#1799]
KeyError when use openscad interface "trimesh.interfaces.scad.interface_scad"
***
import numpy as np
import trimesh
p1=trimesh.creation.box(extents=[5,6,2])
p2=trimesh.creation.uv_sphere(10)
meshes=[p1,p2]
pm=trimesh.interfaces.scad.interface_scad(meshes=[p1,p2],script="hull(){$mesh_0;$mesh_1;}")
pm.show()
***
Problem: KeyError: 'mesh_0'

**Comment by mikedh** [comment]
Hey, not sure but looking at the source it looks like it's looking for capitalized values, like `$MESH_0` instead of `$mesh_0`?

**Comment by DgsChen** [comment]
> Hey, not sure but looking at the source it looks like it's looking for capitalized values, like `$MESH_0` instead of `$mesh_0`?

Thank you so much. But it still not work
***
import numpy as np
import trimesh
p1=trimesh.creation.box(extents=[5,6,2])
p2=trimesh.creation.uv_sphere(10)
meshes=[p1,p2]
pm=trimesh.interfaces.scad.interface_scad(meshes=[p1,p2],script="hull(){$MESH_0;$MESH_1;}")
#pm=trimesh.interfaces.scad.interface_scad(meshes=[],script="$$fn=40;hull(){cube([10,10,10]);sphere(10);}")
pm.show()
***
6 pm=trimesh.interfaces.scad.interface_scad(meshes=[p1,p2],script="hull(){$MESH_0;$MESH_1;}")

CalledProcessError: Command '['D:\\Program', 'Files\\OpenSCAD\\openscad.COM', 'C:\\Users\\CHENDL~1\\AppData\\Local\\Temp\\tmp30e7ybgl', '-o', 'C:\\Users\\CHENDL~1\\AppData\\Local\\Temp\\tmpq_oaw8w6.off']' returned non-zero exit status 1.

**Comment by AuroraHu001** [comment]
> Hey, not sure but looking at the source it looks like it's looking for capitalized values, like `$MESH_0` instead of `$mesh_0`?

Thank you so much.But there is still a problem when using $MESH_0 or $Mesh_0 instead of $mesh_0:
***
The information of the error: Exception has occurred: CalledProcessError Command '['D:\Program', 'Files\OpenSCAD\openscad.COM', 'C:\Users\\AppData\Local\Temp\tmphs_rtrnj', '-o', 'C:\Users\\AppData\Local\Temp\tmp0m9akbag.off']' returned non-zero exit status 1. File "D:\Users**\Program\trimesh_0114.py", line 6, in pm=trimesh.interfaces.scad.interface_scad(meshes,script="hull(){$MESH_0; $MESH_1;}") subprocess.CalledProcessError: Command '['D:\Program', 'Files\OpenSCAD\openscad.COM', 'C:\Users\\AppData\Local\Temp\tmphs_rtrnj', '-o', 'C:\Users\\AppData\Local\Temp\tmp0m9akbag.off']' returned non-zero exit status 1.
***

**Comment by mikedh** [comment]
Hey, a `CalledProcessError` means openSCAD crashed, you might run it with `inteface_scad(meshes=meshes, script=..., debug=True)`

Also if you want the hull of two meshes you might find it easier to do:
```
    import trimesh
    p1 = trimesh.creation.box(extents=[5, 6, 2])
    p2 = trimesh.creation.uv_sphere(3)

    hull = trimesh.util.concatenate([p1, p2]).convex_hull
    hull.show()
```

**Comment by DgsChen** [comment]
> Hey, a `CalledProcessError` means openSCAD crashed, you might run it with `inteface_scad(meshes=meshes, script=..., debug=True)`
> 
> Also if you want the hull of two meshes you might find it easier to do:
> 
> ```
>     import trimesh
>     p1 = trimesh.creation.box(extents=[5, 6, 2])
>     p2 = trimesh.creation.uv_sphere(3)
> 
>     hull = trimesh.util.concatenate([p1, p2]).convex_hull
>     hull.show()
> ```

Hi Mike, thanks so much. Yes, the problem is from the openscad script. The following code works:

`import trimesh
p1=trimesh.creation.box(extents=[5,6,2])
p2=trimesh.creation.uv_sphere(3)
meshes=[p1,p2]
pm=trimesh.interfaces.scad.interface_scad(meshes=[p1,p2],script='hull(){import("$MESH_0");import("$MESH_1");}'
pm.show()`

**Comment by DgsChen** [comment]
> ```
>     import trimesh
>     p1 = trimesh.creation.box(extents=[5, 6, 2])
>     p2 = trimesh.creation.uv_sphere(3)
> 
>     hull = trimesh.util.concatenate([p1, p2]).convex_hull
>     hull.show()
> ```

Hi Mike, thanks so much. Yes, the problem is from the openscad script. The following code works:
***
import trimesh
p1=trimesh.creation.box(extents=[5,6,2])
p2=trimesh.creation.uv_sphere(3)
meshes=[p1,p2]
pm=trimesh.interfaces.scad.interface_scad(meshes=[p1,p2],script='hull(){import("$MESH_0");import("$MESH_1");}')
pm.show()
***

**Comment by mikedh** [comment]
Great! Yeah the `debug=True` mode should help with printing errors, and possibly should be the default.
