### ISSUE TITLE
transformations.scale_from_matrix not working properly or not being used properly

### ISSUE THREAD

**Issue by gregstarr** [mikedh/trimesh#1804]
Hello,

I try to apply a rotation transform to a primitive and it fails because it says the transform is not rigid.

I think the problem is that in `_Primitive.apply_transform`, it takes the matrix and tries to determine if the matrix has a scale factor. It uses `transformations.scale_from_matrix`. Looking at `scale_from_matrix` it seems like it is expecting specifically a scaling matrix, not a general transformation. I think the factor calculations `factor = np.trace(M33) - 2.0` or `trace(M33) / 3` only would work for scaling matrices (and translation), but not in general. Why not use determinant to get scale factor?

demonstration of the issue:
```
>>> tf.scale_from_matrix(tf.rotation_matrix(np.pi/4, [0, 0, 1]))
(0.8047378541243649, array([0., 0., 0., 1.]), None)
```
first number in output should be 1

alternatively, maybe the intended input of `scale_from_matrix` is only scale matrices and so `_Primitive.apply_transform` shouldn't use it to determine scaling.

Thanks!

**Comment by gregstarr** [comment]
good workaround is to use `to_mesh` on primitives

**Comment by mikedh** [comment]
Ah yeah that `scale_from_matrix` just got added to address another issue and it looks like I missed a rather key test case :). Hopefully switching to `det` to extract scale as suggested helps (looks like it passes the other test cases).

**Comment by gregstarr** [comment]
Thanks for the response. For now I'm happy to just switch the primitives to meshes
