### ISSUE TITLE
is there any existing method to visualize the orign x, y, z axes for the mesh?

### ISSUE THREAD

**Issue by aprath1** [mikedh/trimesh#1806]
is there any existing method to visualize the orign x, y, z axes along with the mesh? with axes I mean something like this image below so that we can get an idea about object orientation and the objects location w.r.t the world origin.
Would be curious to know if there are distinct options like object origin and world origin or if both are coincident.

<img src="https://user-images.githubusercontent.com/88531660/212838236-14ce7ec9-73d5-4225-b48f-830a8c3f069d.png" width="120" height="120">

**Comment by mikedh** [comment]
Hey, in the default visualizer if you press `a` it should toggle axis markers or you can create a marker like that with `trimesh.creation.axis` https://trimsh.org/trimesh.creation.html#trimesh.creation.axis

**Comment by aprath1** [comment]
Perfect, Works nicely!
thanks for your quick response.
