### ISSUE TITLE
Face coloring with sharp edges

### ISSUE THREAD

**Issue by chryssin** [mikedh/trimesh#1810]
Hi,

I am trying to assign a color to each of the 12 triangles of a cube like this:
```
import trimesh

mesh = trimesh.load("./files/cube.stl")
face_colors = [
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [255, 0, 0],
    [0, 255, 0],
]

mesh.visual.face_colors = face_colors
mesh.show()

glb = trimesh.exchange.gltf.export_glb(mesh)
with open("test.glb", "wb") as f:
    f.write(glb)
```

I expected to see one green triangle with sharp edges. Instead of this I see color blending as shown in the image:
![image](https://user-images.githubusercontent.com/71879192/213446359-856abe75-6883-47ed-af12-85c04671695a.png)

Is there a way to avoid this gradient coloring?
Also when I export the cube in .glb format the gradient does not happen only in the same-side triangle but also in the other neighboring triangles, like this:
![image](https://user-images.githubusercontent.com/71879192/213447241-d9678be1-f80f-46c7-9bbb-68467c6a18e5.png)

Thank you

**Comment by mikedh** [comment]
Ah I think you want `mesh=trimesh.load('file.stl', process=False)` and `mesh.show(smooth=False)`

**Comment by chryssin** [comment]
Indeed that worked. Thanks!

**Comment by gtangg11** [comment]
Nothing works

`mesh.visual.face_colors = palette[partition]
    mesh = Trimesh(mesh.vertices, mesh.faces, visual=mesh.visual, smooth=False, process=False)
    mesh.visual.kind == 'face'
    return mesh`

i export as glb and it still doesnt smooth
