### ISSUE TITLE
The 'pyglet<2' requirements causes conflicts in other packages

### ISSUE THREAD

**Issue by yurivict** [mikedh/trimesh#1812]
For example, tests can't be run in ```moderngl-window``` because trimesh requires pyglet1 and some other packages require pyglet.

**Comment by mikedh** [comment]
Yeah I'd like to drop the version range for pyglet. [Pyglet 2 was a major breaking change](https://pyglet.readthedocs.io/en/latest/programming_guide/migration.html) that requires close to a re-write of the viewer, I started in [this branch](https://github.com/mikedh/trimesh/tree/feat/p2) but probably won't be able to get it over the line all that soon. PR's and help welcome, 

- [branch](https://github.com/mikedh/trimesh/tree/feat/p2) splits viewers into `trimesh.viewer.windowed` (pyglet1) and `trimesh.viewer.shader` (pyglet2), maybe both should be renamed to `pyglet1` and `pyglet2`. 
- update `trimesh.rendering` to output kwargs vs args that hopefully work in both pyglet 1.5 and >2.
- find a decent PBR shader that's MIT licensed and on `show()` convert everything up to PBR

**Comment by mikedh** [comment]
Until [feat/p2](https://github.com/mikedh/trimesh/tree/feat/p2) is done enough to be mergeable I moved `pyglet<2` from `[easy]` to `[all]`.

**Comment by opoplawski** [comment]
It would be nice if there was an open issue tracking pyglet support status.  Is there any kind of ETA now?  Thanks.
