### ISSUE TITLE
Material / Color / Texture and OBJ from Trimesh to Blender

### ISSUE THREAD

**Issue by albertotono** [mikedh/trimesh#1816]
I can see the material with mesh.show(), but when I import the obj to Blender, I am not able to see it. 

I added both color and material? should I add also texture? 

Any quick way to fix it?

Best Regards

**Comment by mikedh** [comment]
Hey, yeah meshes can have either `ColorVisuals` or `TextureVisuals`. It sounds like you want face colors, which are the default. This should export a red box:

```
mesh = trimesh.creation.box
mesh.visual.face_colors = [255, 0, 0, 255]

mesh.export('example.obj')`
```

Note colors are RGBA and zero alpha could explain an invisible mesh.

**Comment by albertotono** [comment]
The RGBA, was a great note, moving from RGB to RGBA solved the issue, thank you so much.

**Comment by albertotono** [comment]
Not sure, why is not working anymore. Here it is red
![image](https://user-images.githubusercontent.com/11828200/214150124-38546584-06c7-40c0-8a99-d3471b7e5a81.png)
but then in the obj I see this. 


`'# [https://github.com/mikedh/trimesh\nv](https://github.com/mikedh/trimesh/nv) 11.00000000 8.00000000 4.00000000 1.00000000 0.00000000 0.00000000\nv 11.00000000 8.00000000 0.00000000 1.00000000 0.00000000 0.00000000\nv 11.00000000 4.00000000 4.00000000 1.00000000 0.00000000 0.00000000\nv 11.00000000 4.00000000 0.00000000 1.00000000 0.00000000 0.00000000\nv 5.00000000 8.00000000 4.00000000 1.00000000 0.00000000 0.00000000\nv 5.00000000 8.00000000 0.00000000 1.00000000 0.00000000 0.00000000\nv 5.00000000 4.00000000 4.00000000 1.00000000 0.00000000 0.00000000\nv 5.00000000 4.00000000 0.00000000 1.00000000 0.00000000 0.00000000\nf 7 3 1\nf 7 1 5\nf 5 1 6\nf 1 2 6\nf 6 7 5\nf 8 7 6\nf 1 3 4\nf 4 2 1\nf 3 7 4\nf 4 7 8\nf 4 6 2\nf 8 6 4'`

![image](https://user-images.githubusercontent.com/11828200/214150473-cfbb2db4-b2b0-4c2f-8f98-1e1e9d8eb524.png)

The color magically disappear. ( also in blender there is no color in the mesh)

**Comment by mikedh** [comment]
Ah does `meshlab` see them? It's exporting them as vertex colors and they look OK in that text (position + rgb float color).  There's no "spec" for OBJ and it kinda lets you do anything and what/how people implement things vary wildly. Is it possible to use GLB or PLY as an exchange format?

**Comment by albertotono** [comment]
![image](https://user-images.githubusercontent.com/11828200/214153617-44e67f29-a175-4e7f-97ea-9688f3d4e092.png)

Yes meshlab has it. 

Strange that before I was able to see it also in Blender...

Maybe I can export in glb. Like this?`mesh.export('example.glb')``
