### ISSUE TITLE
Is there a better way to test rotation symmetry by Trimesh?

### ISSUE THREAD

**Issue by DgsChen** [mikedh/trimesh#1818]
I want to test whether a mesh has symmetry when rotated with 90,180,270 degree, that is whether the mesh is same if I rotate it around a certain axis by 90, 180, or 270 degree. I used rotation and boolean operation, and measure the difference volume. But it is too slow if the shape is complex. Is ther any better method?

```
import trimesh
import numpy as np

#the slow way
def symmetry(part,alpha=90,eps=1e-3):
    alphar=alpha*np.pi/180.
    mtx=np.identity(4)
    mtx[0][0]=mtx[1][1]=np.cos(alphar)
    mtx[0][1]=-np.sin(alphar)
    mtx[1][0]=np.sin(alphar)
    mtx[0][2]=1e-5 #absolut symmetry will cause backend crash due to difference zero
    pr=part.copy().apply_transform(mtx)
    v=trimesh.boolean.difference([part,pr]).volume
    return v/part.volume<eps

p=trimesh.creation.box([10,20,10])
print(symmetry(part=p,alpha=90), symmetry(part=p,alpha=180))

```
***

**Comment by mikedh** [comment]
Yeah, boolean operations are super slow. Have you looked at [`mesh.principal_inertia_components`](https://trimsh.org/trimesh.base.html#trimesh.base.Trimesh.principal_inertia_components) or [`mesh.symmetry`](https://trimsh.org/trimesh.base.html#trimesh.base.Trimesh.symmetry)?
