### ISSUE TITLE
How can I change the face color with clear color?

### ISSUE THREAD

**Issue by Itto1992** [mikedh/trimesh#1820]
Thank you for creating such a nice repo!

I am trying to change the face color where a ray hits, to check the result.
However, the mesh color I got is really ambiguous like the following image:

<img width="616" alt="スクリーンショット 2023-01-25 17 49 56" src="https://user-images.githubusercontent.com/20178227/214519178-7e14e57b-2bad-4410-b5d2-8851148f2f74.png">

I want to visualize more clearly and sharply.
(the face is filled with vivid color.)
Is there any way to realize that?

Here is the code I used.

```python
import numpy as np
import trimesh

mesh = trimesh.load_mesh('car.obj', file_type='obj')

ray = np.array([0, 0, 1])  # camera_direction in camera coordinate

# convert ray from camera coordinate into world coordinate 
scene = trimesh.Scene(geometry=mesh)
camera_extrinsic = scene.camera_transform
R = camera_extrinsic[0:3, 0:3]
T = camera_extrinsic[3, 0:3]
R_inv = np.linalg.inv(R)
ray_direction = R @ ray

# index of the face ray hits on
idx = mesh.ray.intersects_first(T[None, :], ray_direction[None, :])

# change face color
mesh.visual = mesh.visual.to_color()
mesh.visual.face_colors[idx] = [255, 0, 0, 255]
mesh.show()
```

Thank you in advance!

**Comment by mikedh** [comment]
Hi, I think you want `mesh.show(smooth=False)`

**Comment by Itto1992** [comment]
@mikedh 
Thank you for your reply!

I tried `mesh.show(smooth=False)`. However, I got the same image as above.

Does this command depend on the environment?
I tried it in my docker environment (which is not provided in this repository) using jupyter notebook.

**Comment by Itto1992** [comment]
I found an example of what exactly I want to do [here](https://trimsh.org/examples.ray.html). After I run `mesh.unmerge_vertices()`, the color was successfully reflected on the mesh. Thank you for your time!
