### ISSUE TITLE
Texture lost when loading OBJ mesh file with multiple materials

### ISSUE THREAD

**Issue by Jieying-Li** [mikedh/trimesh#1831]
Hello there. I'm trying to use trimesh loading an OBJ file that contains multiple materials. At first I used trimesh.load, and it returned a scene object. I searched in the issues and found it can be converted to trimesh object with the help of the codes as following:
```
def as_mesh(scene_or_mesh, scale=None):
    if scale is None:
        scale = [1.0, 1.0, 1.0]
    scale = np.asarray(scale)
    if hasattr(scene_or_mesh, "bounds") and scene_or_mesh.bounds is None:
        return None
    if isinstance(scene_or_mesh, trimesh.Scene):
        mesh = trimesh.util.concatenate([
            trimesh.Trimesh(vertices=m.vertices, faces=m.faces)
            for m in scene_or_mesh.geometry.values()])
    else:
        mesh = scene_or_mesh
    assert isinstance(mesh, trimesh.Trimesh), f"Can't convert {type(scene_or_mesh)} to trimesh.Trimesh!"
    return mesh
```
But the codes cannot load the texture as well. Because the texture information is also important for my project, could you please offer some suggestions on how to keep the texture when loading the mesh file? Or is there any way that I can get the texture information? 
Thanks a lot for your help.

**Comment by Jieying-Li** [comment]
This issue can be avoided by acquiring the geometry of trimesh.Scene object and adding them to the scene to be rendered, respectively.

**Comment by yifanlu0227** [comment]
I meet the same problem, could you please explain how you did it in more details?

**Comment by Jieying-Li** [comment]
You can try this
```
`def as_mesh(scene_or_mesh, scale=None):
    if scale is None:
        scale = [1.0, 1.0, 1.0]
    scale = np.asarray(scale)
    if hasattr(scene_or_mesh, "bounds") and scene_or_mesh.bounds is None:
        return None
    if isinstance(scene_or_mesh, trimesh.Scene):
        dump = scene_or_mesh.dump()
        mesh = dump.sum()
    else:
        mesh = scene_or_mesh
    assert isinstance(mesh, trimesh.Trimesh), f"Can't convert {type(scene_or_mesh)} to trimesh.Trimesh!"
    return mesh`
```
