### ISSUE TITLE
can not load dxf files

### ISSUE THREAD

**Issue by Mambix** [mikedh/trimesh#184]
Has anything changed in new versions of this library because I can no longer load dxf files?

```Python
import trimesh
dxf = trimesh.load('my.dxf')
```

And I get error that dxf is not supported. I installed pyassimp also installed ubuntu assimp-utils with no success. I'm using python 2.7.15rc1

**Comment by mikedh** [comment]
Hey- I updated the error messages to be more informative, could you re- open with the new exception when you see this?
