### ISSUE TITLE
rtree dependency 

### ISSUE THREAD

**Issue by cedricjeanty** [mikedh/trimesh#185]
Very nice library. I am impressed!

I pip installed trimesh, then ran:
trimesh.proximity.signed_distance(mesh, points)
and got:
my_python_path/trimesh/util.py", line 1332, in bounds_tree
    import rtree
ImportError: No module named rtree

Then I pip installed rtree, which fixed the problem, but then ran into the libspatialindex system dependency:
my_python_path/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file

I realize the install documentation says the soft dependencies conditionally fail at run-time, so I can't really complain, I guess I am just noting it.

**Comment by mikedh** [comment]
Yeah, I agree the `rtree` dependency on `libspatialindex` as a shared library without including it in a wheel makes it a pain to install. The `conda-forge` install should work gracefully, but I agree it would be nicer through pip wheels. I briefly looked in to this, and I put my thoughts here: 
https://github.com/geometries/trimesh_upstream

I don't have the bandwidth to tackle it, but I would sure be happy if someone else did it 😄
