### ISSUE TITLE
How to find a face's three neighbor faces? 

### ISSUE THREAD

**Issue by XieYHccc** [mikedh/trimesh#1857]
Hi everyone,

I want to ask are there any good ways to find the three neighbor faces of a face?

**Comment by Raserino** [comment]
Hi, you can use `mesh.face_adjacency`: https://trimsh.org/trimesh.base.html#trimesh.base.Trimesh.face_adjacency

**Comment by XieYHccc** [comment]
> Hi, you can use `mesh.face_adjacency`: https://trimsh.org/trimesh.base.html#trimesh.base.Trimesh.face_adjacency

Yes, I could use this and construct a graph, then I could get each face's three neighbors, but I'm not sure if this is the best way.

**Comment by mikedh** [comment]
Hey, yeah `mesh.face_adjacency` is the easiest as far as I know. You could use a defaultdict to create the array:

```
In [14]: import collections

In [15]: import numpy as np

In [16]: m = trimesh.creation.box()

In [17]: d = defaultdict(list)

In [18]: [(d[a].append(b), d[b].append(a)) for a, b in m.face_adjacency]


In [19]: d
Out[19]: 
defaultdict(list,
            {0: [1, 2, 4],
             1: [0, 3, 5],
             2: [3, 0, 7],
             3: [2, 1, 8],
             4: [0, 6, 7],
             7: [2, 9, 4],
             5: [1, 6, 10],
             8: [3, 9, 10],
             6: [5, 4, 11],
             10: [5, 8, 11],
             9: [8, 7, 11],
             11: [10, 6, 9]})


In [21]: adjacent = np.array([d[i] for i in range(len(m.faces))])

In [22]: adjacent
Out[22]: 
array([[ 1,  2,  4],
       [ 0,  3,  5],
       [ 3,  0,  7],
       [ 2,  1,  8],
       [ 0,  6,  7],
       [ 1,  6, 10],
       [ 5,  4, 11],
       [ 2,  9,  4],
       [ 3,  9, 10],
       [ 8,  7, 11],
       [ 5,  8, 11],
       [10,  6,  9]])

```
There's probably a faster way to do this with numpy slicing, or failing that `trimesh.grouping.group_rows(mesh.edges_sorted, require_count=2)` but they don't come to mind.

**Comment by XieYHccc** [comment]
> Hey, yeah `mesh.face_adjacency` is the easiest as far as I know. You could use a defaultdict to create the array:
> 
> ```
> In [14]: import collections
> 
> In [15]: import numpy as np
> 
> In [16]: m = trimesh.creation.box()
> 
> In [17]: d = defaultdict(list)
> 
> In [18]: [(d[a].append(b), d[b].append(a)) for a, b in m.face_adjacency]
> 
> 
> In [19]: d
> Out[19]: 
> defaultdict(list,
>             {0: [1, 2, 4],
>              1: [0, 3, 5],
>              2: [3, 0, 7],
>              3: [2, 1, 8],
>              4: [0, 6, 7],
>              7: [2, 9, 4],
>              5: [1, 6, 10],
>              8: [3, 9, 10],
>              6: [5, 4, 11],
>              10: [5, 8, 11],
>              9: [8, 7, 11],
>              11: [10, 6, 9]})
> 
> 
> In [21]: adjacent = np.array([d[i] for i in range(len(m.faces))])
> 
> In [22]: adjacent
> Out[22]: 
> array([[ 1,  2,  4],
>        [ 0,  3,  5],
>        [ 3,  0,  7],
>        [ 2,  1,  8],
>        [ 0,  6,  7],
>        [ 1,  6, 10],
>        [ 5,  4, 11],
>        [ 2,  9,  4],
>        [ 3,  9, 10],
>        [ 8,  7, 11],
>        [ 5,  8, 11],
>        [10,  6,  9]])
> ```
> 
> There's probably a faster way to do this with numpy slicing, or failing that `trimesh.grouping.group_rows(mesh.edges_sorted, require_count=2)` but they don't come to mind.

Thank you Mike, appreciate the comment, this really helps.
