### ISSUE TITLE
Frame loss

### ISSUE THREAD

**Issue by wshunvx** [mikedh/trimesh#1866]
``

    length = 30
    array = '-145.096189432334,-45.0961894323427,100;-179.903810567665,-25.0000000000082,100;-220.096189432334,-25.0000000000078,100;-254.903810567666,-45.0961894323417,100;-275,-79.9038105676733,100;-275.000000000001,-120.096189432342,100;-254.903810567667,-154.903810567674,100;-220.096189432335,-175.000000000008,100;-179.903810567667,-175.000000000009,100;-145.096189432335,-154.903810567675,100;-125,-120.096189432343,100;-125,-79.9038105676745,100'

    points = array.split(';')
    if len(points) > 0:
        index = 0
        positions = np.zeros(len(points) * 2 * 3, dtype=np.float64)
        for point in points:
            point = point.split(',')
            positions[index] = float(point[0])
            index += 1
            positions[index] = float(point[1])
            index += 1
            positions[index] = float(point[2])
            index += 1

            positions[index] = float(point[0])
            index += 1
            positions[index] = float(point[1])
            index += 1
            positions[index] = float(point[2]) + length
            index += 1

        pointer = 0
        triangle = 0
        # strip = np.tile(positions, 2).reshape(-1, 3)
        # strip[len(points):, 2] += length
        strip = positions.reshape(-1, 3)
        size = len(strip)
        internals = np.zeros(int((size / 2 - 2) * 2 * 3), dtype=np.uint32) 
        indices = np.zeros(size * 3, dtype=np.uint32)
        for x in range(0, size, 2):
            mg = strip[x:x + 4]
            if len(mg) == 4:
                indices[pointer] = x
                pointer += 1
                indices[pointer] = x + 1
                pointer += 1
                indices[pointer] = x + 2
                pointer += 1

                indices[pointer] = x + 1
                pointer += 1
                indices[pointer] = x + 2
                pointer += 1
                indices[pointer] = x + 3
                pointer += 1
            else:
                indices[pointer] = 0
                pointer += 1
                indices[pointer] = x
                pointer += 1
                indices[pointer] = x + 1
                pointer += 1

                indices[pointer] = 0
                pointer += 1
                indices[pointer] = 1
                pointer += 1
                indices[pointer] = x + 1
                pointer += 1

            if (x / 2 > 1 and size - 2 > x) or size - 2 == x:
                internals[triangle] = 0
                triangle += 1
                internals[triangle] = x - 2
                triangle += 1
                internals[triangle] = x
                triangle += 1

                internals[triangle] = 1
                triangle += 1
                internals[triangle] = x - 1
                triangle += 1
                internals[triangle] = x + 1
                triangle += 1
        faces = np.concatenate([indices, internals])
        ts = trimesh.Trimesh(vertices=strip, faces=faces.reshape(-1, 3))
        # matrix = trimesh.transformations.random_rotation_matrix()
        # ts.apply_transform(matrix)
        ts.show()
``

The peripheral edges do not close.
Most of my models look like this. What's the problem?

**Comment by mikedh** [comment]
It looks like you're trying to extrude a 2D curve? It might be easier to use `trimesh.creation.extrude_polygon`:

```
    import trimesh
    import numpy as np
    from shapely.geometry import Polygon
    
    array = '-145.096189432334,-45.0961894323427,100;-179.903810567665,-25.0000000000082,100;-220.096189432334,-25.0000000000078,100;-254.903810567666,-45.0961894323417,100;-275,-79.9038105676733,100;-275.000000000001,-120.096189432342,100;-254.903810567667,-154.903810567674,100;-220.096189432335,-175.000000000008,100;-179.903810567667,-175.000000000009,100;-145.096189432335,-154.903810567675,100;-125,-120.096189432343,100;-125,-79.9038105676745,100'    

    vertices = np.fromstring(array.replace(',', ' ').replace(';', ' '),
                             sep=' ',
                             dtype=np.float64).reshape((-1, 3))
    polygon = Polygon(vertices[:,:2])

    extrude = trimesh.creation.extrude_polygon(polygon, height=30)
    extrude.apply_translation([0,0,vertices[0][2]])


```

**Comment by wshunvx** [comment]
3D points into a 3D mesh?
trimesh.points.PointCloud(vertices)
Make it equal to 30
