### ISSUE TITLE
Saved .PLY does not have color

### ISSUE THREAD

**Issue by hzhcongo** [mikedh/trimesh#187]
Hi, I am trying to save a the largest mesh from a .PLY object after splitting it up (_meshes = mesh.split(only_watertight = False_)

However, it does not save the vertex colors somehow.

I understand that a similar thread has been opened and closed at: #160 , but even when I export the .PLY into ascii and opened with WordPad, the header is missing RGB properties (as shown):

_ply
format ascii 1.0
comment github.com/mikedh/trimesh
element vertex 216572
property float x
property float y
property float z
property float nx
property float ny
property float nz
element face 431895
property list uchar int vertex_indices
end_header_

This is my initial .PLY header:
_ply
format ascii 1.0
element vertex 216656
property float x
property float y
property float z
property float value
property uchar red
property uchar green
property uchar blue
element face 432043
property list uchar int vertex_indices
end_header_

Trying to export as .STL also results in missing colors. 
I have tried different exports (pardon my poor programming as I am just starting out in Python):
_trimesh.Trimesh.export(meshes[largestMeshIndex], 'result.ply', 'ply')
trimesh.Trimesh.export(meshes[largestMeshIndex], 'result.stl', 'stl_ascii')_

I tried manually generate the data before storing them into .PLY files, but to no avail too:
_result = trimesh.io.ply.export_ply(meshes[largestMeshIndex], encoding='ascii', vertex_normal=None)
result = trimesh.io.ply.export_ply(meshes[largestMeshIndex], encoding='ascii', vertex_normal=True)_

Any help would be greatly appreciated!
Thank you!

**Comment by mikedh** [comment]
Ah- colors are only supported in the binary PLY exporter, not the ASCII one. Did you try it with the default options:
`meshes[largestMeshIndex].export('largeMesh.ply')`

Couple other things to check:
1) are the colors being loaded in the original mesh? what does `mesh.visual.kind` show
2) are the colors being maintained through the split operation? What does `meshes[largestMeshIndex].visual.kind` show?

**Comment by hzhcongo** [comment]
I see,

I tried _.export()_, and a binary .ply was generated with the following headers:
ply
format binary_little_endian 1.0
comment github.com/mikedh/trimesh
element vertex 216572
property float x
property float y
property float z
element face 431895
property list uchar int vertex_indices
property uchar red
property uchar green
property uchar blue
property uchar alpha
end_header

But it still doesn't show any colors when the headers have the color properties.

_mesh.visual.kind_ is vertex
_meshes[largestMeshIndex].visual.kind_ is face

Is this the cause for the missing colors?

**Comment by hzhcongo** [comment]
Hi,

Would it be convenient for you to explain the differences between the meshes' _visual.kind_ by any chance?
Is it suppose to change after _.split()_?

**Comment by hzhcongo** [comment]
I am viewing the mesh in web with Three.js.

For my initial models I implement the colors using:
_material = new THREE.MeshPhongMaterial({color: 0xffffff, flatShading: false, vertexColors: THREE.VertexColors});_

As such, I tried changing it to:
 _material = new THREE.MeshPhongMaterial({color: 0xffffff, flatShading: false, vertexColors: THREE.FaceColors});_ 
for the split models after much Googling, but the result still remains the same

Do you know of any viewers that can display the split meshes with it's colors shown? I tried Three.js, Blender and Mixed Reality Viewer.

**Comment by hzhcongo** [comment]
Or is it possible to chance the _mesh.visual.kind_ back to _vertex_ after splitting?

**Comment by mikedh** [comment]
Ah gotcha. At some point it would be nice if I updated `trimesh.util.submesh` to maintain the original vertex colors, even in a face split. If you explicitly set the vertex colors after the split it will treat the "core data" as vertex color:
`mesh.visual.vertex_colors = mesh.visual.vertex_colors`

**Comment by hzhcongo** [comment]
I see, but in the meantime I tried explicitly setting the colors to vertex via: 
`meshes[largestMeshIndex].visual.vertex_colors = mesh.visual.vertex_colors`

where `meshes` are the split ones, and `mesh` being the original one, but there is no change though.

Was this what you were suggesting?

**Comment by mikedh** [comment]
I think in this example it would be:
`meshes[largestMeshIndex].visual.vertex_colors = meshes[largestMeshIndex].visual.vertex_colors`

**Comment by hzhcongo** [comment]
Oh I got what you are trying to do by that after looking at the process in debugging, thank you so much!
I got `mesh.visual.kind` and `mesh.visual.vertex_colors` mixed up together.
It's in vertex colors now!

Thank you once again!

**Comment by dhirajsuvarna** [comment]
@mikedh Does `trimesh` support exporting ply in ascii format along with colors now?
