### ISSUE TITLE
loading a pyvista mesh into trimesh instance

### ISSUE THREAD

**Issue by rpc-group** [mikedh/trimesh#1878]
Hello,

May I know any available function to load a pyvista mesh into a trimesh instance?
I cannot find that one. So I have tried to extract vertices, faces, face normals from the pyvista mesh and initialize the mesh as below:
```
trsm_mesh = trimesh.Trimesh(vertices=pv_vertices, faces=pv_faces, face_normals=pv_face_normals)
```
However, I realized that the orders of vertices and faces in `trsm_mesh.vertices` and `trsm_mesh.faces` are different from the input lists `pv_vertices` and `pv_faces`, respectively. Is there any way to ensure those inputs match with the one from the obtained trimesh instance?

**Comment by mikedh** [comment]
Hey, I think you want to create the mesh with `process=False`, which merges duplicate vertices:
```
trsm_mesh = trimesh.Trimesh(vertices=pv_vertices, faces=pv_faces, face_normals=pv_face_normals, process=False)
```
