### ISSUE TITLE
Could not find libspatialindex_c library file

### ISSUE THREAD

**Issue by Mambix** [mikedh/trimesh#189]
When I run my pcode with the latest trimesh it gives me this error:

```
File "/home/rmamba/.local/lib/python2.7/site-packages/trimesh/io/load.py", line 35, in load_path
    raise _path_exception
OSError: Could not find libspatialindex_c library file
```

**Comment by Mambix** [comment]
Already had rtree installed so for ubuntu 18.04 (mine was a fresh installation)

```
git clone https://github.com/libspatialindex/libspatialindex.git
cd libspatialindex
cmake --prefix=/usr .
make
make install
```

now it's working

**Comment by mikedh** [comment]
Ah, yeah that happens if you installed `rtree` with pip, the conda-forge install doesn't do that. It would be much nicer if they bundled it in whl files ([one approach](https://github.com/geometries/trimesh_upstream)).
