### ISSUE TITLE
locations - ray_origins seems not colinear with ray_directions when using trimesh.ray.ray_triangle.RayMeshIntersector.intersects_id

### ISSUE THREAD

**Issue by ZhangCYG** [mikedh/trimesh#1898]
I try to use trimesh.ray.ray_triangle.RayMeshIntersector.intersects_id like:
ray_detector = rayt.RayMeshIntersector(mesh)
_, index_ray, locations = ray_detector.intersects_id(ray_origins=start_point, ray_directions=direction, return_locations=True, multiple_hits=False)
When I want to check the API using
np.cross(locations - start_point[index_ray], direction[index_ray], axis=1)
I find that it does not return a zero vector, which means locations - ray_origins seems not colinear with ray_directions.
This is beyond my expectation.
I wanna how to solve this problem?
My installed trimesh version is 3.21.0

**Comment by mikedh** [comment]
Hey, did you try using `mesh.ray.intersects_location`? On simple test data for me it's returning colinear results with both embree and the native checker:

```
In [1]: import trimesh

In [2]: m = trimesh.creation.icosphere()

In [3]: import numpy as np

In [4]: vectors = trimesh.unitize(np.random.random((1000, 3)) - 0.5)

In [5]: origins = (np.random.random((1000, 3)) - 0.5) * 10

In [6]: m.ray.intersects_location?
Signature: m.ray.intersects_location(ray_origins, ray_directions, multiple_hits=True)
Docstring:
Return the location of where a ray hits a surface.

Parameters
----------
ray_origins : (n, 3) float
  Origins of rays
ray_directions : (n, 3) float
  Direction (vector) of rays

Returns
---------
locations : (m) sequence of (p, 3) float
  Intersection points
index_ray : (m,) int
  Indexes of ray
index_tri : (m,) int
  Indexes of mesh.faces
File:      ~/trimesh/trimesh/ray/ray_pyembree.py
Type:      method

In [7]: locations, index_ray, index_tri = m.ray.intersects_location(ray_origins=origins, ray_directions=vectors)

In [10]: trimesh.util.diagonal_dot(trimesh.unitize(locations - origins[index_ray]), vectors[index_ray])
Out[10]: 
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [11]: np.allclose(trimesh.unitize(locations - origins[index_ray]), vectors[index_ray])
Out[11]: True

In [13]: np.cross([0,0,1], [0,0,2])
Out[13]: array([0, 0, 0])

In [15]: np.cross(locations - origins[index_ray], vectors[index_ray], axis=1)
Out[15]: 
array([[-1.21430643e-17, -5.63785130e-18,  2.08166817e-17],
       [ 5.55111512e-17,  2.77555756e-17, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.73472348e-18,  1.73472348e-18],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  0.00000000e+00,  0.00000000e+00],
       [ 2.22044605e-16,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.42861287e-17, -8.67361738e-19,  2.08166817e-17],
       [-7.37257477e-18,  3.46944695e-18,  4.85722573e-17],
       [ 5.55111512e-17,  5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 4.44089210e-16,  5.55111512e-17,  5.55111512e-17],
       [ 1.38777878e-17, -2.77555756e-17,  2.77555756e-17],
       [ 6.93889390e-18, -6.07153217e-18, -6.50521303e-18],
       [ 5.55111512e-17,  2.77555756e-17,  0.00000000e+00],
       [-1.11022302e-16, -2.77555756e-17,  1.11022302e-16],
       [ 0.00000000e+00, -4.33680869e-18, -4.33680869e-18],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  2.22044605e-16, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  2.77555756e-17, -2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  5.55111512e-17]])

In [21]: m = trimesh.creation.box(use_embree=False)

In [22]: m
Out[22]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [23]: locations, index_ray, index_tri = m.ray.intersects_location(ray_origins=origins, ray_directions=vectors)

In [24]: np.cross(locations - origins[index_ray], vectors[index_ray], axis=1)
Out[24]: 
array([[-2.22044605e-16, -8.67361738e-19,  0.00000000e+00],
       [ 0.00000000e+00, -2.22044605e-16,  2.22044605e-16],
       [-1.38777878e-17,  0.00000000e+00,  1.38777878e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.44089210e-16,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.33680869e-18,  5.20417043e-18],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11022302e-16,  0.00000000e+00],
       [ 4.44089210e-16,  0.00000000e+00, -2.22044605e-16],
       [-3.46944695e-18,  1.38777878e-17, -1.38777878e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  2.22044605e-16,  0.00000000e+00],
       [-4.44089210e-16,  0.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16, -1.11022302e-16,  0.00000000e+00],
       [ 5.55111512e-17,  0.00000000e+00, -2.22044605e-16]])   
=
```

**Comment by ZhangCYG** [comment]
My scenario lies on a ShapeNet mesh and about 2000 or more sampling points each, the code is like
`ray_detector = rayt.RayMeshIntersector(mesh)
locations, index_ray, _ = ray_detector.intersects_location(ray_origins=start_point, ray_directions=direction, multiple_hits=False)
start_intersection = start_point[index_ray]
depth_intersection = np.linalg.norm(locations - start_intersection, axis=1)
print('Dir Check: ', np.cross(locations - start_intersection, direction[index_ray], axis=1))
print('Depth Check: ', locations - start_intersection - direction[index_ray] * np.expand_dims(depth_intersection, axis=1).repeat(3, axis=1))`
The start_points is sample from a unit sphere and directions are sampled from a unit sphere, too.
But the two prints tell me that:
`Dir Check:  [[ 0.04807904  0.07479488  0.62274591]                                                                                                 [120/1890]
 [-0.24511602  0.22785856 -0.10055348]                                        
 [ 0.04469185  0.12276119  0.01067268]                                        
 ...                                  
 [ 0.0435207  -0.04406088  0.32296307]                                        
 [-0.13401493  0.02768983 -0.10736506]                                        
 [ 0.9048153   0.13845761  0.40820023]] 
Depth Check:  [[ 0.785021    0.09344614 -0.07183081]
 [-0.10133893  0.19588478  0.69091415]                                        
 [ 0.03763962 -0.05450212  0.46928794]                                        
 ...                                                                          
 [ 0.72832332 -0.91756776 -0.22332579]                                        
 [ 0.08387718  0.23148535 -0.04499605]                                        
 [ 0.74992452 -0.8922506  -1.3596374 ]]                                       
Dir Check:  [[-0.14199588  0.03065917  0.08369085]                            
 [-0.0606255  -0.04419141  0.25001582]                                        
 [ 0.02615619 -0.01805081  0.26390379]
 ...                                  
 [ 0.34721788  0.18757241 -0.07301104]                                        
 [ 0.07330192 -0.17643126 -0.47204598]                                        
 [ 0.0058738   0.16164338  0.09137593]] 
Depth Check:  [[ 0.0481742   1.02360165 -0.2932488 ]
 [-0.4560734   1.54445043  0.16239678]
 [-0.35134815  0.39483008  0.06182908]
 ...                                  
 [-0.0617295   0.36986842  0.65666133]                                        
 [-0.60075854  0.04886796 -0.11155394]                                        
 [ 0.04198183  0.32694976 -0.5810705 ]]`
That means the function returns a totally wrong location.
This instance is ShapeNet core v2 /03593526/e08d96216c6360155e7fae0bb48967f7.
And other instances remain the same problem.

**Comment by ZhangCYG** [comment]
I test with a single trimesh.creation.icosphere() and a little sampled points (about 10) and find the result is right. But in my scenario it still seems wrong.

**Comment by ZhangCYG** [comment]
I have solved my problem by finding that if i do not use trimesh.load but only read vertexes and faces, then use trimesh to calculate the face normals, the results are led to be wrong because of the wrong calculated face normals. Thanks for helping!
