### ISSUE TITLE
Bug in Trimesh.vertex_normals?

### ISSUE THREAD

**Issue by ntfrgl** [mikedh/trimesh#19]
Hello there! I have recently started using your package and find it very appealing. Thank you for sharing your work!

It seems that [`geometry.mean_vertex_normals`](https://github.com/mikedh/trimesh/blob/16cb95a7e348043ea05eaa17691e907c1ba45276/trimesh/geometry.py#L116) loses information about the normals of some incident faces, i.e. when the list of indices `faces[:,i]` contains repetitions. Instead, to create a field `G` on vertices by accumulating a field `F` on incident faces, I use:
``` python
G = np.zeros([len(self.vertices)] + list(F.shape[1:]))
for i, face in enumerate(self.faces):
    G[face] += F[i]
```
The mapping `vertex -> incident faces` could be cached as a sparse matrix, but for tasks similar to this, the necessary lookups probably wouldn't improve performance.

**Comment by mikedh** [comment]
Glad its useful! Yeah good point, mean_vertex_normals was assuming each vertex is in (only) three faces, which is just straight up wrong. I pushed a fix and a unit test in https://github.com/mikedh/trimesh/commit/0d05db0f5b18da4a4997596ecf0b448e84e0247b which uses a sparse matrix and falls back to the loop solution. Looping on large meshes is ~50x slower than the sparse matrix/dot product. Thanks for the report!

**Comment by ntfrgl** [comment]
This works like a charm, thank you! Of course, `.dot()` is much faster ;-)

It is very satisfactory to go to bed too tired to pursue a vague idea, and then wake up finding it deliberated, implemented, tested, and waiting to speed up your code after a mere `pip install . --upgrade`.
