### ISSUE TITLE
Can I visualize rays or line segments in the viewer?

### ISSUE THREAD

**Issue by paperstiger** [mikedh/trimesh#191]
I understand that I can visualize mesh and points with the viewer, but is there any way to visualize either rays or line segments in the viewer?

Thanks!

**Comment by mikedh** [comment]
Hey, yeah if you create a `Path3D` from your segments it should show up nicely in the pyglet viewer:

```
In [1]: import numpy as np

In [2]: import trimesh

In [3]: segments = np.random.random((100,2,3))

In [4]: p = trimesh.load_path(segments)

In [5]: p
Out[5]: <trimesh.path.path.Path3D at 0x7fbaa49eb240>

In [6]: p.show()

```

You can also view them with a mesh by:
```
trimesh.Scene([mesh, path]).show()
```

**Comment by paperstiger** [comment]
Amazing, this works! Thank you so much
