### ISSUE TITLE
Cannot update vertices

### ISSUE THREAD

**Issue by PetitPhoenix** [mikedh/trimesh#1915]
I'm trying to update vertices based on non-uniform deformations (wrap text around a cylinder).

I tried to extrude a SVG (https://upload.wikimedia.org/wikipedia/commons/2/2a/Rebel_Alliance_logo.svg) after cleaning the first lines of the svg about encoding which also creates an error.

```
import trimesh
from trimesh import viewer
from trimesh.viewer import windowed

with open('./test2.svg', 'r') as f:
    path = trimesh.path.exchange.svg_io.svg_to_path(f)

path2D = trimesh.path.Path2D(path['entities'], path['vertices'], False)#path['metadata'], 
path2D.show()
mesh = path2D.extrude(height=20)
mesh.is_watertight

mesh.vertices -= mesh.center_mass
```

The following returns this error in Spyder:
```
Traceback (most recent call last):

  Cell In[17], line 1
    mesh.vertices -= mesh.center_mass

  File ~\AppData\Local\anaconda3\envs\dev\Lib\site-packages\trimesh\caching.py:272 in __isub__
    return super(self.__class__, self).__isub__(

ValueError: output array is read-only
```

Even if I let my mesh at its current position, the following modifier doesn't change the vertices locations:
`mesh2.update_vertices(np.full((len(mesh2.vertices), 1), True), wrap_around(mesh1.vertices, -100, 100))
`
I performed the deformation on extracted vertices:
```
mesh1 = mesh.copy()
mesh2 = mesh.copy()
tmp1 = mesh1.vertices
tmp2 = wrap_around(tmp1, -10, 10)
```

![Figure 2023-04-25 101415](https://user-images.githubusercontent.com/62991642/234216232-cab2f25e-9f01-458c-befd-4776f66c1f29.png)

Thanks for the tips :)

**Comment by mikedh** [comment]
Hey, `Path2D`.extrude returns an `trimesh.primitives.Extrusion` object, you probably want to convert to a vanilla triangular mesh:

```
In [4]: m = trimesh.path.creation.rectangle(bounds=[[0,0], [1,1]])

In [5]: m
Out[5]: <trimesh.Path2D(vertices.shape=(4, 2), len(entities)=1)>

In [6]: m.extrude(1.0)
Out[6]: <trimesh.primitives.Extrusion>

In [7]: m.extrude(1.0).to_mesh()
Out[7]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>


```

**Comment by PetitPhoenix** [comment]
Thanks, it solved the easy translation. Need to find out how to modify the vertices as I don't use the trimesh.update_vertices properly also. If you have somewhere a guideline on how to do so, I'd appreciate it :) Thanks

I'm closing the issue.
