### ISSUE TITLE
Can I get the sliced mesh from vertices?

### ISSUE THREAD

**Issue by Norweig1an** [mikedh/trimesh#1922]
For example I have two objects:
<trimesh.Trimesh(vertices.shape=(778, 3), faces.shape=(1552, 3))>
<trimesh.Trimesh(vertices.shape=(1618, 3), faces.shape=(3240, 3))>
Now I'd like to get the contacted mesh of one object, I've calculated the contatct verteice and already get them.
`contact_pts` torch.Size([10, 3]) tensor([[-0.0353, -0.0014,  0.0189],
        [-0.0370, -0.0042,  0.0191],
        [-0.0375, -0.0037,  0.0160],
        [-0.0393, -0.0031,  0.0147],
        [-0.0412, -0.0065,  0.0175],
        [-0.0395, -0.0058,  0.0192],
        [-0.0450, -0.0033,  0.0161],
        [-0.0431, -0.0055,  0.0166],
        [-0.0422, -0.0012,  0.0148],
        [-0.0462, -0.0018,  0.0164]])
How can I get the contacted meshes from the calculated vertices `contact_pts`?
Thanks for your patience!

**Comment by Kiord** [comment]
You may search for the vertices of the mesh that are close enough to any contact point (given a threshold). 
Then you can mask the mesh to keep only these vertices.

```python
import trimesh as tm
import numpy as np

mesh = ...
contact_points = ...
threshold = ...

# Function to compute the new faces after masking  
def reindex_tris(tris, mask):
    indices = -1 * np.ones((tris.max() + 1), dtype=np.int32)
    indices[mask] = np.arange(np.count_nonzero(mask))
    new_tris = indices[tris]
    where_deleted = np.any((new_tris == -1), axis=1)
    new_tris = np.delete(new_tris, where_deleted, axis=0)
    return new_tris

to_contact_points = contact_points[None, ...] - mesh.vertices[:, None, :] # (n, p, 3)
dist_to_contact_points = np.linalg.norm(to_contact_points, axis=-1)
mask = np.any(dist_to_contact_points < threshold, axis=1)

contact_vertices = mesh.vertices[mask]
contact_faces= reindex_tris(mesh.faces, mask)
contact_mesh = tm.Trimesh(contact_vertices, contact_faces, process=False)
```

(nb : code not tested)

**Comment by Norweig1an** [comment]
Thank you for your method, I'll try it as soon as possible.
By the way, I'm new to trimesh and don't know much about it, so could you explain the robust solution for searching for contact faces? I think the close mesh of vertices may not as equal as contact meshes.

**Comment by Kiord** [comment]
If one of the meshes has big faces, it is possible for the contact points to be too far from any vertices. As a result, the contact mesh can be incomplete. 
![image](https://github.com/mikedh/trimesh/assets/79104227/0d89769b-853e-4d9d-a084-48ee78cb6e85)

You can check for nearest faces using `trimesh.proximity.closest_point` :

```python
_, _, tids = tm.proximity.closest_point(mesh, contact_points)

vids = np.unique(mesh.faces[tids])
mask = np.zeros(len(mesh.vertices), dtype=bool)
mask[vids] = True

# use this mask to crop the mesh
```

 `trimesh.proximity.closest_point` is a bit overkill since you only need the nearest face indices but it should work.
