### ISSUE TITLE
How to create watertight mesh with trimesh ?

### ISSUE THREAD

**Issue by HripsimeS** [mikedh/trimesh#1926]
@cyrilpic @hauptmech @tito @mavimo @lericson Hello

I use my extracted point clouds (attached file change the extension to **.ply**) to do create mesh and saved it as .obj below link https://drive.google.com/file/d/1dPqnw84VP-L4GQFf6MYoAEHHEKTCfEoV/view?usp=share_link

I saw trimesh library gives a possibility to convert mesh to watertight mesh. Can you please check on my object and let me know how I can make a watertight mesh with trimesh (please share a code). I look forward to hearing from you and thanks in advance!!!

[Laptop.txt](https://github.com/mikedh/trimesh/files/11488745/Laptop.txt)

**Comment by mikedh** [comment]
Hey, unfortunately there's no really easy or well defined way to make triangle soup watertight and maintain its original character. Some possible options include:

- `mesh.fill_holes` will fill in single triangle and single quad holes which sometimes helps.
- `mesh.convex_hull` will be watertight, as it is the convex hull of the input mesh
- `mesh.voxelized(pitch=0.5).marching_cubes` will be watertight as it voxelized the input mesh (requires you `pip install scikit-image` to get their implementation of marching cubes

**Comment by HripsimeS** [comment]
@mikedh Thanks for your quick reply and help! I tried all 3 options, unfortunately in case of  mesh.fill_holes I could not extract converted mesh, getting this error 'function' object has no attribute 'export'. But other 2 methods worked well, I could extract the converted watertight. In my opinion mesh.convex_hull gives better results and I will share my code below for other users.

import trimesh
mesh = trimesh.load_mesh("C:/Users/Desktop/laptop.obj")
convex_hull = mesh.convex_hull
convex_hull.export("C:/Users/Desktop/convex_hull.obj") #save the watertight mesh
mesh_convex_hull = trimesh.load_mesh("C:/Users/Desktop/convex_hull.obj") #load the watertight mesh

#check if the converted mesh is watertight
if mesh_convex_hull.is_watertight:
    print("The mesh is watertight.")
else:
    print("The mesh is not watertight.")


![image](https://github.com/mikedh/trimesh/assets/42246765/eeff48b5-7c25-4f8a-9092-1189caf58f3e)
