### ISSUE TITLE
Imported mesh from glb has wrong rotation

### ISSUE THREAD

**Issue by shheo042** [mikedh/trimesh#1938]
- Original model
![image](https://github.com/mikedh/trimesh/assets/87844470/2f9defa9-4410-4187-b452-630dd5125c1f)
- Imported with trimesh.load, then exported
![image](https://github.com/mikedh/trimesh/assets/87844470/a4641248-08bb-4a3a-85f1-799a5d9315c0)
```
mesh = trimesh.load('source.glb', force='mesh')
mesh.export('target.glb')
```

When I import and export as obj with blender, the orientation is preserved.
The source model file contains somewhat complex node structure, and might that is the problem.

[source.zip](https://github.com/mikedh/trimesh/files/11672886/source.zip)
I've also attached the original model file.

**Comment by whateverforever** [comment]
gltf and glb generally like to mess up orientations, as they have a fixed convention for what is "up". I assume trimesh is simply loading the file as it is specified, while blender applies post-import transformations.

**Comment by mikedh** [comment]
Hey, I poked around the blender importer a little bit. I couldn't quite tell exactly what they were doing, but it looked like they might be switching between Y-up and Z-up conventions and applying [this matrix?](https://github.com/KhronosGroup/glTF-Blender-IO/blob/5c52c313bcadb4703eb34ec6d5b51d1e47c60089/addons/io_scene_gltf2/blender/com/gltf2_blender_math.py#L59-L66) If in trimesh you apply that matrix or its inverse to the loaded scene it might match?

**Comment by shheo042** [comment]
```
import numpy as np
import trimesh

mesh = trimesh.load("source.glb", force="mesh")

mesh.apply_transform(np.array([[1, 0, 0, 0], [0, 0, 1, 0], [0, -1, 0, 0], [0, 0, 0, 1]]))

mesh.export("target_yup.glb")
```
I've executed above code and got the following result,

![image](https://github.com/mikedh/trimesh/assets/87844470/19496e8a-0137-4e1b-8bd2-66ad05fcc858)

Applying the matrix `[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]` to original model showed right rotation of the model.

**Comment by mikedh** [comment]
Great!! I don't think it makes sense to apply that rotation in the trimesh loader to match blender, I think they're probably doing it for internal reasons.
