### ISSUE TITLE
Wrong results for section and section_multiplane

### ISSUE THREAD

**Issue by johnnybigert** [mikedh/trimesh#1944]
Hi,

I use `section_multiplane` to create slices from a triangulated mesh. To get the results out, I'm using the `Path2D.polygons_full` function. However, in the `polygons_full` results, there are sometimes areas included that do not correspond to the inside of the original mesh. I get the exact same problems with `section` instead of `section_multiplane`, and also with `Path2D.polygons_closed` instead of `Path2D.polygons_full`. I've tracked the issue back to an polyline that is wrongly closed by trimesh (when the correct behaviour would have been to combine the polyline with other polylines to form a Polygon).

Below is an example program that reproduces the behavior using `section` and `polygons_full`. In the example, the line that (wrongly) closes the polygon is (-57.12112999884475 -66.76574065788188) to (11.55831746561118 -8.21576619650154). The image illustrates the mesh, the faulty line (red) and the rest of the polygon (green), while the X marks the test point in the example code.

<img width="740" alt="Screenshot 2023-06-13 at 13 21 09" src="https://github.com/mikedh/trimesh/assets/17929792/2bf1b5cc-22a7-4a47-a093-fb6524ec98a5">

The polygons illustrated with matplotlib:
<img width="550" alt="Screenshot 2023-06-13 at 14 15 43" src="https://github.com/mikedh/trimesh/assets/17929792/992d1857-29ca-4e5b-afcb-d85fcf2cbac6">

The mesh file for the test program (you'll need to decompress it): [mesh.off.zip](https://github.com/mikedh/trimesh/files/11734447/mesh.off.zip)

```
import trimesh
from shapely import Point


def main():
    mesh = trimesh.exchange.load.load("mesh.off")

    min_bounds = list(mesh.bounds[0])
    min_bounds[0] = 54

    slice = mesh.section(plane_origin=min_bounds, plane_normal=[1, 0, 0])

    slice_2D, to_3D = slice.to_planar()
    polys = slice_2D.polygons_full

    is_inside = polys[49].contains(Point((-40, -60)))
    if is_inside:
        print("Found faulty polygon")
        print(polys[49])


if __name__ == '__main__':
    main()
```

**Comment by johnnybigert** [comment]
@mikedh Any thoughts?

**Comment by mikedh** [comment]
Hey, yeah that mesh is not watertight (appears to be missing a bunch of triangles?) and thus has no volume, so the cross sections have no area. `polygons_full` is making an attempt to heal/connect stuff but the only thing in the section that's really going to be usable are the raw `(n, 2, 3)` line segments from `trimesh.intersections.mesh_plane`. You could try some simple tricks to recover a watertight mesh before doing the sections:

```
In [31]: m = next(iter(trimesh.load('mesh.off.zip').geometry.values()))

In [32]: m.is_watertight
Out[32]: False

In [33]: blobs = [i.convex_hull for i in m.split(only_watertight=False) if len(i.faces) > 10 and i.convex_hull.is_volume]

In [34]: c = trimesh.util.concatenate(blobs)

In [35]: c.is_watertight
Out[35]: True
```

Or you could try recovering the section info you need from the line segments (i.e. shapely linestring.buffer, etc).

**Comment by johnnybigert** [comment]
Thanks, appreciate the answer! Ok, then I know how to continue my investigations, I will give it a try.
