### ISSUE TITLE
No SCAD/Blender available!

### ISSUE THREAD

**Issue by luoey** [mikedh/trimesh#1945]
Hi,Mike,
I'm stuck in a problem that my boolean engine can't detect the SCAD or blender for a few days.I'm sure i have got these two site-packages in the env. And i tried to solve this problem by modifying the scad.py and blender.py, but with my poor coding level i can't find where to modify because the system search section does not have the Ubuntu.Please help me out! Thank you so much!

Here is my error message:
Traceback (most recent call last):
  File "/home/luoey/jzb/程序/RSV-Contact-Soft/Contact_Sim.py", line 448, in <module>
    main()
  File "/home/luoey/jzb/程序/RSV-Contact-Soft/Contact_Sim.py", line 440, in main
    PE.run()
  File "/home/luoey/jzb/程序/RSV-Contact-Soft/Contact_Sim.py", line 249, in run
    self.penetration_threshold)
  File "/home/luoey/jzb/程序/RSV-Contact-Soft/myfunction.py", line 93, in contact_simulation
    interAB = tri.boolean.intersection([self.mymesh_base,self.mymesh_move], engine='scad')
  File "/home/luoey/anaconda3/envs/test/lib/python3.7/site-packages/trimesh/boolean.py", line 64, in intersection
    result = _engines[engine](meshes, operation='intersection', **kwargs)
  File "/home/luoey/anaconda3/envs/test/lib/python3.7/site-packages/trimesh/interfaces/scad.py", line 62, in boolean
    return interface_scad(meshes, script, debug=debug, **kwargs)
  File "/home/luoey/anaconda3/envs/test/lib/python3.7/site-packages/trimesh/interfaces/scad.py", line 46, in interface_scad
    raise ValueError('No SCAD available!')
ValueError: No SCAD available!

**Comment by mikedh** [comment]
If you type `openscad` or `OpenSCAD` on a terminal is it able to open it? It's just [checking your PATH](https://github.com/mikedh/trimesh/blob/main/trimesh/interfaces/scad.py#L25).

**Comment by luoey** [comment]
> If you type `openscad` or `OpenSCAD` on a terminal is it able to open it? It's just [checking your PATH](https://github.com/mikedh/trimesh/blob/main/trimesh/interfaces/scad.py#L25).
Sorry, I've been a little busy lately and forgot to reply to the answer. I carefully reviewed my program from scratch and finally found the problem, which occurred because the file header I entered was not in the correct format. 
But the mistake of file header format unexpectedly report the fault of engine, this problem really bothers me for a long time.

**Comment by luoey** [comment]
> If you type `openscad` or `OpenSCAD` on a terminal is it able to open it? It's just [checking your PATH](https://github.com/mikedh/trimesh/blob/main/trimesh/interfaces/scad.py#L25).

Sorry, I've been a little busy lately and forgot to reply to the answer. I carefully reviewed my program from scratch and finally found the problem, which occurred because the file header I entered was not in the correct format.
But the mistake of file header format unexpectedly report the fault of engine, this problem really bothers me for a long time.
