### ISSUE TITLE
merge a collection of list objects

### ISSUE THREAD

**Issue by O-Mubarak** [mikedh/trimesh#1953]
how to merge a collection of list objects using the trimesh library and subsequently save the combined result into a single .obj file?

`

for file_path, size, translation, rotation_angle in zip(file_paths, size_data, translation_data, rotation_angles):
    obj_path = '/home/om/Project/3D-FUTURE-model/*/raw_model.obj'.replace('*', file_path)
    
    
    # Use glob to find the actual file path
    obj_files = glob.glob(obj_path)

    if len(obj_files) == 1:
        mesh = trimesh.load_mesh(obj_files[0])

        rotation_matrix = trimesh.transformations.rotation_matrix(rotation_angle, rotation_axis)
        mesh.apply_transform(rotation_matrix)

        mesh.apply_translation(translation)

        meshs.append(mesh)

merged_mesh = trimesh.util.concatenate(meshs)
merged_mesh.export(room_directory +'/merged.obj')

`

**Problem : When I display the merged file, the texture gets corrupted**

**Comment by bragilee** [comment]
Hi mikedh,

Actually I am having this issue now, I have a list of meshes of objects (beds, ..., etc.). When I export the mesh of each single object to .glb and blendering with bpy. Then look good with textures. However, after I concatenate all objects and export into a single scene mesh in .glb, when I use bpy to blender it, the textures of objects corrupted. Are there anything I need to take care of when exporting a list of meshes to a single .glb file? Thanks!

**Comment by mikedh** [comment]
Hey, you'd probably have better luck exporting as a scene (which keeps meshes separate but puts it into one GLB file) `trimesh.Scene([mesh_a, mesh_b, mesh_c]).export(file_name='scene.glb')`

Versus concatenating which is doing a UV remap, and packing all the contained textures onto a new image. That generally works but is pretty complicated, PR's with fixes and tests welcome! Do the meshes have UV's outside the range of 0.0-1.0 maybe? Here's the pack function that concatenate is using:

 https://github.com/mikedh/trimesh/blob/c880b028243fdcb128368d9dcd73fdb343fa15ac/trimesh/visual/material.py#L636-L748

**Comment by bragilee** [comment]
Hi, thanks for your quick response. I will go ahead to read and test it, and look at UV values. Sorry I am a bit new to mesh. If you donot mind, can I have one more conceptual questions? I observe if rendering using .obj file, it will completely lose textures. Why saving mesh to .obj is different from saving it to .glb.
