### ISSUE TITLE
Annotating a 3D scene with text labels

### ISSUE THREAD

**Issue by tarheels100** [mikedh/trimesh#1958]
I'm trying to add a text label to a path in a 3D scene, but I haven't had any luck.  Here is a MWE:
```python
import trimesh
import numpy as np

ray_path = trimesh.load_path([[0,0,0],[1,1,1]])
label = trimesh.path.entities.Text(origin=len(ray_path.vertices), text='hello', height=10)

ray_path.vertices = np.vstack((ray_path.vertices,
                        ray_path.vertices[-1,:]))
ray_path.entities = np.append(ray_path.entities, label)

scene = trimesh.Scene(ray_path)
scene.show()
```
Is this at all the right approach or is there an easier way to go about it?  Ultimately, I'd just like to be able to place a text label at specific coordinates in 3D space and have it visible when calling `scene.show()`.

**Comment by mikedh** [comment]
Hey, the viewer is pretty limited and more of a debug tool than a real visualizer, I might check out https://vedo.embl.es/#gallery

There are a few ways to implement this in trimesh but all of them require quite a bit of work. You could add Text entity support via pyglet, or you could implement a `path.entities.Text.discrete` method which returned a polygon of the outline.

**Comment by tarheels100** [comment]
I figured that might be the conclusion.  Trimesh has been really great, so I was looking to stick with it as much as I can.  Thanks for the recommendations, I'll give them a try!

**Comment by mikedh** [comment]
Glad it's been useful and PR's welcome!! Yeah `Text` entities need some work, they don't really have any outline defined and are missing a lot of stuff. 

You might be able to get vector outlines with [freetype-py](https://github.com/rougier/freetype-py/) and then extrude them into meshes haha.
