### ISSUE TITLE
Is it possible to compute ""add force at location" in trimesh?

### ISSUE THREAD

**Issue by paperstiger** [mikedh/trimesh#197]
Thank you for the great library, it has helped me tremendously on my project! 

I wonder with the current functionalities in trimesh, is it possible to compute a mesh transform(or no transform) after applying a directed force to a static mesh from a point on the mesh? The computation can be simplified to ignore the mass and inertia of the mesh and the magnitude of the force, but just take into account the mesh's geometry, in the simplest form, the only output can be just if the mesh will tip over or not.

If this function can not be implemented currently with trimesh, could you give me some advices on how you would approach the problem?

Thanks,
Fan

**Comment by mikedh** [comment]
Hey Fan, glad it's useful! 

Stable poses might be sort of what you're looking for: https://github.com/mikedh/trimesh/blob/master/trimesh/poses.py

For anything beyond that you probably want a real physics engine, like [bullet/pybullet](https://github.com/bulletphysics/bullet3). It looks like they officially support the Python bindings now, I might look in to a trimesh-pybullet wrapper at some point.

You could also use a simulation environment like openrave or [DART sim](https://github.com/dartsim/dart) which does this sort of thing as well.

**Comment by paperstiger** [comment]
Thank you for your advices! I have been using the compute stable poses function and it seems to be working quite well, I might need to twist it quite a bit to achieve what I want(pose change after a arbitrary force).

I also use pybullet, the python API is indeed quite convenient,  but it seems to offer more than what I want on this matter.

Regards,
Fan

**Comment by baoyufuyou** [comment]
Hi @mikedh 
Recetly I'm testing some pybullet stuff. Could I ask, did you finish trimesh-pybullet wrapper.
Thanks a lot.

Best regards,
Lei
