### ISSUE TITLE
Exported vertex_normals not considered during loading ply file

### ISSUE THREAD

**Issue by saptarshineilsinhaigd** [mikedh/trimesh#1995]
`import trimesh
import numpy as np
from pathlib import Path

    
if __name__ == '__main__':

  
    mesh_path = 'path to obj'

    mesh = trimesh.load(file_obj = trimesh.util.wrap_as_stream(mesh_path.read_bytes()), file_type='OBJ', process=False, maintain_order=True)
    print(mesh.vertex_normals)

    ply_mesh = mesh.export(None, 'PLY', vertex_normal=True, encoding='ascii')

    # print(ply_mesh.mesh.vertex_normals)

    output_file = open('./export.ply', "wb+")
    output_file.write(ply_mesh)
    output_file.close()

    mesh_path_ply= Path('/home/ssinha/dev/trimesh/trimesh/export.ply')

    mesh_ply = trimesh.load(file_obj = trimesh.util.wrap_as_stream(mesh_path_ply.read_bytes()), file_type='PLY', process=False, maintain_order=True)

    print(mesh_ply.vertex_normals)
`

**Comment by saptarshineilsinhaigd** [comment]
When the above code the vertex_normals in obj which is exported in ply is not considered during loading

**Comment by saptarshineilsinhaigd** [comment]
A possible fix could be adding the following lines :
`  if elements['vertex']['data']['nx'] is not None:
            vertex_normals = np.column_stack([elements['vertex']['data']['nx'], elements['vertex']['data']['ny'], elements['vertex']['data']['nz']])
            kwargs['vertex_normals'] = vertex_normals`

in the ply.py file in function : 

`def _elements_to_kwargs(elements,
                        fix_texture,
                        image,
                        prefer_color=None):
    """
    Given an elements data structure, extract the keyword
    arguments that a Trimesh object constructor will expect.

    Parameters
    ------------
    elements : OrderedDict object
      With fields and data loaded
    fix_texture : bool
      If True, will re- index vertices and faces
      so vertices with different UV coordinates
      are disconnected.
    image : PIL.Image
      Image to be viewed
    prefer_color : None, 'vertex', or 'face'
      Which kind of color to prefer if both defined

    Returns
    -----------
    kwargs : dict
      Keyword arguments for Trimesh constructor
    """
    # store the raw ply structure as an internal key in metadata
    kwargs = {'metadata': {'_ply_raw': elements}}

    if 'vertex' in elements and elements['vertex']['length']:
        vertices = np.column_stack(
            [elements['vertex']['data'][i]
             for i in 'xyz'])
        if elements['vertex']['data']['nx'] is not None:
            vertex_normals = np.column_stack([elements['vertex']['data']['nx'], elements['vertex']['data']['ny'], elements['vertex']['data']['nz']])
            kwargs['vertex_normals'] = vertex_normals
        if not util.is_shape(vertices, (-1, 3)):
            raise ValueError('Vertices were not (n,3)!')
    else:
        # return empty geometry if there are no vertices
        kwargs['geometry'] = {}
        return kwargs

    if 'face' in elements and elements['face']['length']:
        face_data = elements['face']['data']
    else:
        # some PLY files only include vertices
        face_data = None
        faces = None

    # what keys do in-the-wild exporters use for vertices
    index_names = ['vertex_index',
                   'vertex_indices']
    texcoord = None

    if util.is_shape(face_data, (-1, (3, 4))):
        faces = face_data
    elif isinstance(face_data, dict):
        # get vertex indexes
        for i in index_names:
            if i in face_data:
                faces = face_data[i]
                break
        # if faces have UV coordinates defined use them
        if 'texcoord' in face_data:
            texcoord = face_data['texcoord']

    elif isinstance(face_data, np.ndarray):
        face_blob = elements['face']['data']
        # some exporters set this name to 'vertex_index'
        # and some others use 'vertex_indices' but we really
        # don't care about the name unless there are multiple
        if len(face_blob.dtype.names) == 1:
            name = face_blob.dtype.names[0]
        elif len(face_blob.dtype.names) > 1:
            # loop through options
            for i in face_blob.dtype.names:
                if i in index_names:
                    name = i
                    break
        # get faces
        faces = face_blob[name]['f1']

        try:
            texcoord = face_blob['texcoord']['f1']
        except (ValueError, KeyError):
            # accessing numpy arrays with named fields
            # incorrectly is a ValueError
            pass

    if faces is not None:
        shape = np.shape(faces)
        if len(shape) != 2:
            # we may have mixed quads and triangles handle them with function
            faces = triangulate_quads(faces)

        if texcoord is None:
            # ply has no clear definition of how texture coordinates are stored,
            # unfortunately there are many common names that we need to try
            texcoord_names = [('texture_u', 'texture_v'), ('u', 'v'), ('s', 't')]
            for names in texcoord_names:
                # If texture coordinates are defined with vertices
                try:
                    t_u = elements['vertex']['data'][names[0]]
                    t_v = elements['vertex']['data'][names[1]]
                    texcoord = np.stack((
                        t_u[faces.reshape(-1)],
                        t_v[faces.reshape(-1)]), axis=-1).reshape(
                            (faces.shape[0], -1))
                    # stop trying once succeeded
                    break
                except (ValueError, KeyError):
                    # if the fields didn't exist
                    pass

        shape = np.shape(faces)

        # PLY stores texture coordinates per-face which is
        # slightly annoying, as we have to then figure out
        # which vertices have the same position but different UV
        if (texcoord is not None and
            len(shape) == 2 and
                texcoord.shape == (faces.shape[0], faces.shape[1] * 2)):

            # vertices with the same position but different
            # UV coordinates can't be merged without it
            # looking like it went through a woodchipper
            # in- the- wild PLY comes with things merged that
            # probably shouldn't be so disconnect vertices
            if fix_texture:
                # do import here
                from ..visual.texture import unmerge_faces

                # reshape to correspond with flattened faces
                uv_all = texcoord.reshape((-1, 2))
                # UV coordinates defined for every triangle have
                # duplicates which can be merged so figure out
                # which UV coordinates are the same here
                unique, inverse = grouping.unique_rows(uv_all)

                # use the indices of faces and face textures
                # to only merge vertices where the position
                # AND uv coordinate are the same
                faces, mask_v, mask_vt = unmerge_faces(
                    faces, inverse.reshape(faces.shape))
                # apply the mask to get resulting vertices
                vertices = vertices[mask_v]
                # apply the mask to get UV coordinates
                uv = uv_all[unique][mask_vt]
            else:
                # don't alter vertices, UV will look like crap
                # if it was exported with vertices merged
                uv = np.zeros((len(vertices), 2))
                uv[faces.reshape(-1)] = texcoord.reshape((-1, 2))

            # create the visuals object for the texture
            kwargs['visual'] = visual.texture.TextureVisuals(
                uv=uv, image=image)
        elif texcoord is not None:
            # create a texture with an empty material
            from ..visual.texture import TextureVisuals
            uv = np.zeros((len(vertices), 2))
            uv[faces.reshape(-1)] = texcoord.reshape((-1, 2))
            kwargs['visual'] = TextureVisuals(uv=uv)
        # faces were not none so assign them
        kwargs['faces'] = faces
    # kwargs for Trimesh or PointCloud
    kwargs['vertices'] = vertices

    # if both vertex and face color are defined pick the one
    if 'face' in elements:
        kwargs['face_colors'] = _element_colors(elements['face'])
    if 'vertex' in elements:
        kwargs['vertex_colors'] = _element_colors(elements['vertex'])

    return kwargs
`

**Comment by saptarshineilsinhaigd** [comment]
Proposed fix : saptarshineilsinhaigd-vertex_normals_ply_load

**Comment by mikedh** [comment]
Thanks for the fix!
