### ISSUE TITLE
Request: Trimesh.edges_sparse

### ISSUE THREAD

**Issue by ntfrgl** [mikedh/trimesh#20]
In complete analogy to `Trimesh.faces_sparse` from #19, I have a use case for a cached sparse matrix encoding the mapping `vertex -> edges`:
```python
edges = self.face_adjacency_edges
row = edges.reshape(-1)
col = np.tile(np.arange(len(edges)).reshape(-1, 1), (1, 2)).reshape(-1)
self.edges_sparse = sp.coo_matrix(
    (np.ones(len(col), dtype=np.bool), (row, col)),
    shape=(vertex_count, len(edges)), dtype=np.bool)
```
Then
``` python
G = np.zeros((vertex_count, 3))
for edge, f in zip(self.face_adjacency_edges, F):
    G[edge] += f
```
is equivalent to:
``` python
G = self.edges_sparse.dot(F)
```

**Comment by mikedh** [comment]
Interesting, the big question for me is which edge property would that refer to? There are a bunch:

`mesh.edges`: (n,2) raw edges from faces
`mesh.edges_face`: (n,) int corresponds to mesh.edges, for each edge, which face index was it generated from?
`mesh.face_adjacency_edges`: (m,2) corresponds to mesh.face_adjacency, and is the edge that two adjacent faces share (this should possibly be renamed to mesh.edges_face_adjacency)
`mesh.edges_unique`: (o, 2) unique edges. If the mesh is watertight is equivalent to face_adjacency_edges (aka o == m)
`mesh.edges_sorted`: (n,2) edges, but sorted along axis 1 (so if you need to find unique edges, etc)

I just committed a change which renames faces_sparse to index_sparse, and made it work on both edges and faces. It might be easiest to just add in your script:
```
edges_sparse = trimesh.geometry.index_sparse(len(mesh.vertices), mesh.edges_unique)
result = edges_sparse.dot(F)
```

Then you could pick which edge property you wanted to use depending on your use case.

**Comment by ntfrgl** [comment]
Thank you! `index_sparse` seems like a good interface.

An example is the anisotropic curvature measure defined in [Restricted Delaunay Triangulations and Normal Cycle](http://dx.doi.org/10.1145/777792.777839), where a `3x3` tensor field on the edges is accumulated at the vertices.
