### ISSUE TITLE
some unexpected color points in sample_surface

### ISSUE THREAD

**Issue by l1346792580123** [mikedh/trimesh#2002]
Thanks for the great project! I have noticed that trimesh.sample_surface now can sample color, but when I use this function, some unexpected color points appear.  I use this mesh [mesh.zip](https://github.com/mikedh/trimesh/files/12342377/mesh.zip) as example. The code is 
```
mesh = trimesh.load('mesh-f00001.obj', process=False, maintain_order=True)
sample_points, _, colors = trimesh.sample.sample_surface(mesh, 50120, sample_color=True)
np.savetxt('tmp.txt', np.concatenate([sample_points, colors[:,:3]],axis=1))
```

The result of the sampled points [tmp.txt](https://github.com/mikedh/trimesh/files/12342454/tmp.txt) looks like this
![snapshot00](https://github.com/mikedh/trimesh/assets/25956606/537f9e92-a779-4d40-bf56-b91b4d62f66f)

There are some white points on the hair and some black points on the elbow, while when I open the mesh with meshlab, the color is normal.
 
![snapshot01](https://github.com/mikedh/trimesh/assets/25956606/928ec525-d528-4493-803b-d875c7908349)

Is this a bug or something wrong with this mesh?

**Comment by l1346792580123** [comment]
I found that the result is normal after removing ```maintain_order=True```.   Is this normal or a bug?

**Comment by mikedh** [comment]
Oh that's almost certainly a bug, PR's super welcome!
