### ISSUE TITLE
Collision Manager giving wrong results?

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#201]
Hi,
Is the collision module heavily tested?
I get constantly wrong results when adding meshes and checking for collisions. My code goes something like this:
```
scene = trimesh.scene.scene.Scene()
collision_manager = trimesh.collision.CollisionManager()
for i in range(10):
  in_collision = True
  while in_collision:
    # get random transform, e.g.:
    obj_transform = trimesh.transformations.random_rotation_matrix()
    in_collision = collision_manager.in_collision_single(mesh, transform=obj_transform)

  # the mesh_id is unique
  collision_manager.add_object(mesh_id, mesh, transform=obj_transform)

  scene.add_geometry(mesh, node_name=mesh_id)
  scene.graph.update('world', mesh_id, matrix=obj_transform)
```
If I finally do `scene.show()` the meshes are clearly in collision.
Am I missing something?

**Comment by clemense** [comment]
Ok, I found my mistake. To make the transform used in the collision_mannager and in the scene graph identical, the last line should be:
```
scene.graph.update(mesh_id, 'world', matrix=obj_transform)
```

**Comment by mikedh** [comment]
Oh nice, yeah I believe @mmatl is using collision in his application so it should be decently well tested. That argument ordering is a little confusing on the scene graph for sure.
