### ISSUE TITLE
jQuery error when using search function at https://trimsh.org/

### ISSUE THREAD

**Issue by majksner** [mikedh/trimesh#2011]
Hi,

It seems there is an error in console when using search functionality at https://trimsh.org.

I have tried it in Firefox, Chrome, and Safari and all of them are affected.

```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://trimsh.org/search.html?q=apply_scale&check_keywords=yes&area=default:104
[search.html:104:7](https://trimsh.org/search.html?q=apply_scale&check_keywords=yes&area=default)
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://trimsh.org/search.html?q=apply_scale&check_keywords=yes&area=default:120
```

**Comment by mikedh** [comment]
Hey, yeah I noticed that too, for 4.0 in #2010 I switched the docs theme to [furo](https://github.com/pradyunsg/furo) which among other things fixes the search.
