### ISSUE TITLE
Streamlit support?

### ISSUE THREAD

**Issue by XinyueZ** [mikedh/trimesh#2024]

**Comment by mikedh** [comment]
No plans but PR's welcome! [trimesh.viewer.scene_to_html](https://github.com/mikedh/trimesh/blob/76f7bea2d55128986b71b3d161fae4a39cb19d3b/trimesh/viewer/notebook.py#L16-L30) might be a good place to start, and the notebook widgets in general are a little neglected. You might check out [pyvista](https://github.com/pyvista) which is much more focused on visualization that trimesh.
