### ISSUE TITLE
Regression (?): Duplicate Vertices Not Merged

### ISSUE THREAD

**Issue by whateverforever** [mikedh/trimesh#2027]
Hi there,

sorry if this is as-intended, but to me it appears as a regression. In trimesh 3.16.4, the attached cube ply was correctly processed, resulting in 8 vertices. In the latest version 3.23.5, the vertices don't get merged anymore.

```
In [1]: import trimesh

In [2]: trimesh.load("/home/<user>/code/<project>/tests/testdata/cube.ply")
Out[2]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

...
$ python3 -m pip install --upgrade trimesh
...snip...
Installing collected packages: trimesh
  Attempting uninstall: trimesh
    Found existing installation: trimesh 3.16.4
    Uninstalling trimesh-3.16.4:
      Successfully uninstalled trimesh-3.16.4
Successfully installed trimesh-3.23.5
...

In [1]: import trimesh

In [2]: trimesh.load("/home/<user>/code/<project>/tests/testdata/cube.ply")
Out[2]: <trimesh.Trimesh(vertices.shape=(24, 3), faces.shape=(12, 3))>

In [3]: 
```

It works, if I call `mesh.merge_vertices(merge_norm=True)`

[cube.ply.txt](https://github.com/mikedh/trimesh/files/12538652/cube.ply.txt)

**Comment by mikedh** [comment]
Hey, I think this is because `ply` now loads vertex normals (https://github.com/mikedh/trimesh/pull/1996). Yeah it's a little weird that if you want to deal with volumes for different file types you have to run `process(merge_tex=True, merge_norm=True)`, but the alternative as far as I can tell is to mangle meshes loaded for visual stuff (UV + normals).

**Comment by whateverforever** [comment]
Yeah, difficult to say what the desired behavior should be. Blender's edge-split modifier also works by duplicating edges that represent sharp creases. Those will be preserved under shade smooth with the new trimesh version, but would have been rounded in the older one. Just wanted to alert you to it, for my usecase, I fixed it.

**Comment by mikedh** [comment]
Sounds good, thanks for the report!
