### ISSUE TITLE
trimesh.path.entities.Bezier

### ISSUE THREAD

**Issue by jysy** [mikedh/trimesh#2028]
Hi,

Can anyone show as example of using trimesh.path.entities.Bezier to draw a bezier curve in 3D?

control_points = np.array([
    (0, 0, 0),
    (1, 2, 0),
    (3, 3, 0),
    (4, 4, 0)
])

bezier_entity = trimesh.path.entities.Bezier(control_points)
path = trimesh.path.Path3D(entities=[bezier_entity])

Its giving me 'TypeError: iteration over a 0-d array'.

Thanks in advance!

**Comment by mikedh** [comment]
Hey, entities are created by vertex index not the vertices themselves, I think you want:

```
In [1]: import trimesh

In [2]: import numpy as np

In [3]: control_points = np.array([
   ...: (0, 0, 0),
   ...: (1, 2, 0),
   ...: (3, 3, 0),
   ...: (4, 4, 0)
   ...: ], dtype=np.float64)

In [4]: path = trimesh.path.Path3D(
entities=[trimesh.path.entities.Bezier(points=np.arange(len(control_points)))],
vertices=control_points)

In [5]: path.show()
```

**Comment by jysy** [comment]
Thanks Mike. It works.
