### ISSUE TITLE
WebP extension for GLTF export

### ISSUE THREAD

**Issue by xiaoxiae** [mikedh/trimesh#2029]
I want to use `webp` as the texture format for my 3D models, since they will be displayed on the web and so it's vital for the texture size to be as small as possible. GLTF has the following extension for this: 

https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_texture_webp/README.md

Reading through it and following an extension-related PR, I've attempted to do this:

```python3
scene = trimesh.Scene()
scene.add_geometry(my_triangle_mesh)
scene.metadata.update({'gltf_extensions': {"EXT_texture_webp": {"source": 0}}})

scene.export("test.glb")
```

I understand that this is wrong, because it adds the metadata to the root of the JSON when it should be added to the `textures` node. I'm also not sure how to specify that the texture should be saved as `webp` instead of the default `png`.

Is there a way to do this?

**Comment by mikedh** [comment]
Hey, I think you'd have to hack it into `_append_image`:
https://github.com/mikedh/trimesh/blob/475f921e3497b5c360c56ff269b29c7535147f62/trimesh/exchange/gltf.py#L1769-L1775

Have you tried compressing either the GLTF folder, or the GLB bytes? That has the advantage of applying compression to the vertex/face arrays in addition to just the texture, and can be loaded pretty easily in a web context using standard stuff (there's a few nice webassembly zstandard decompressors on NPM, and probably zip as well):

```
In [1]: import trimesh

# a model with a bunch of textures
In [2]: m = trimesh.load('bigmodel/airplane/models/model_normalized.obj')

In [3]: m
Out[3]: <trimesh.Scene(len(geometry)=29)>

In [4]: e_zip = trimesh.util.compress(m.export(file_type='gltf'))

In [5]: len(e_zip)
Out[5]: 891966

In [6]: e_glb = m.export(file_type='glb')

In [7]: len(e_glb)
Out[7]: 2247540

# compression ratio, i.e. zipped is 39.6% the size of the raw GLB export
In [8]: len(e_zip) / len(e_glb)
Out[8]: 0.3968632371392723

# a non-standard library compression algorithm from FB
In [9]: from zstandard import compress

In [10]: e_zstd = compress(e_glb)

In [11]: len(e_zstd)
Out[11]: 825268

# slightly better than zip
In [12]: len(e_zstd) / len(e_glb)
Out[12]: 0.3671872358222768
```

**Comment by xiaoxiae** [comment]
Thanks for the quick response!

Sadly, using ZIP performs quite poorly for my meshes (virtually no compression), whereas converting the texture to WebP reduces the size from 7MB to ~450kB.

Would a PR to support this be welcome? It seems that PIL supports it natively so the fix should be pretty simple (although I'm quite unfamiliar with the codebase so it might not be).

**Comment by mikedh** [comment]
I looked into it briefly and it looks like PIL ships with a webp exporter which appeared to work, which makes this a lot easier as it doesn't add a dependency. PR's welcome!

If it's for web use you might also want to add a `max_texture_size: Optional[int] = None` or something which resizes the image down if any dimension is larger than a fixed value as I suspect some of the images might also be very large. 

```
In [14]: len(png)
Out[14]: 71489

In [15]: len(webp)
Out[15]: 41670

In [16]: len(webp) / len(png)
Out[16]: 0.5828868777014645
```

I'd probably approach it as:
- add a `extension_webp: bool = False` keyword argument to the exporter
- pass that through to `trimesh.exchange.gltf._append_image`
- add a test which round-trips mesh through export and import
