### ISSUE TITLE
Calculate shortest distance to mesh from all points inside the mesh

### ISSUE THREAD

**Issue by dschmitz89** [mikedh/trimesh#203]
Hi,

for my project I would like to use trimesh to calculate the smallest distance to the mesh and the corresponding closest triangle for all points inside the mesh. I have not found the function to compute the distances and I cannot find a documentation, so I would like to ask for some short advice. Also, trimesh has a kdtree functionality, can it be used to speed up the distances calculation?

Thanks in advance for your help.

**Comment by mikedh** [comment]
Hey, I think this example from the docs might be what you're looking for:
https://trimsh.org/examples/nearest.html 

Best,
Mike

**Comment by mikedh** [comment]
Closing for now- feel free to re- open!

**Comment by zy20091082** [comment]
Hi, Mike @mikedh 
I wonder how can I caculate the shortest path between arbitrary two vertex, but the path can only follow other vertex on the surface.
Thank u!

**Comment by mikedh** [comment]
Hey ZY, I added an example of how to do that here: https://github.com/mikedh/trimesh/blob/master/examples/shortest.py

**Comment by zy20091082** [comment]
So great! Thanks very much!

**Comment by zy20091082** [comment]
@mikedh By the way, what if two point on the surface, maybe not the vertex, the shortest path between them? Not along the edges, but on the surface also.

**Comment by mikedh** [comment]
No worries. Doing it exactly on the surface makes it not a graph problem and thus a lot harder. I would probably choose some distance tolerance and then subdivide the mesh until every edge was shorter than that tolerance. Then you can find the nearest vertex to your points, and use the same solution as above.

**Comment by zy20091082** [comment]
Wonderful! It's so kind of you, Mike!
