### ISSUE TITLE
inverted normals when using sweep_polygon

### ISSUE THREAD

**Issue by rlipperts** [mikedh/trimesh#2032]
I have noticed that the mesh coming out of `trimesh.creation.sweep_polygon` appears to have inverted normals. Am I setting up the polygon incorrectly or is this a bug?

Steps to reproduce:
```python
import numpy as np
import trimesh
from shapely.geometry import Point

path = np.array([[-1.0, 0.0, 0.0], [1.0, 0.0, 0.0]])
circle = Point(0, 0).buffer(5.0)
mesh = trimesh.creation.sweep_polygon(circle, path)

scene = trimesh.Scene()
scene.add_geometry(mesh, "path")
scene.export("path.stl")
```

The resulting detail view of the normals:
![trimesh_bug](https://github.com/mikedh/trimesh/assets/38458182/62ce0104-2500-453f-a413-d7157567aa38)

The normals can be easily fixed by calling `trimesh.repair.fix_inversion`, but this is more of a workaround than a solution.

**Comment by caseymjohnson** [comment]
I think I ran into this a few months ago

ensuring a counterclockwise shapely coordinate sequence seems to resolve? I tested with a number of paths, forwards and backwards

```
import numpy as np
import trimesh
from shapely.geometry import Point
from shapely import is_ccw

path = np.array([[-1.0, 0.0, 0.0], [1.0, 0.0, 0.0]])
circle = Point(0, 0).buffer(5.0)

if is_ccw(circle):
    pass
else:
    circle = circle.reverse()
    print('rotating counterclockwise')

mesh = trimesh.creation.sweep_polygon(circle, path)

scene = trimesh.Scene()
scene.add_geometry(mesh, "path")
scene.export("path.stl")
```

**Comment by rlipperts** [comment]
Yes, that appears to resolve my issue - seems as if there still is much to learn for me here. 

(sorry, kinda forgot to answer)
