### ISSUE TITLE
Faces are broken

### ISSUE THREAD

**Issue by jrunkening** [mikedh/trimesh#2040]
I have a `STL` mesh file exported from fution360:

![image](https://github.com/mikedh/trimesh/assets/115336923/f549bab9-eba3-453e-8866-8db7a1dec97c)

And I try to load the mesh as `Trimesh`:

```python
mesh = trimesh.load("ball.stl", force='mesh')
mesh.show()
```

Which works fine

But when I try to plot some face from the `Trimesh` object, I found most of the faces are broken:

```python
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
edges = mesh.vertices[mesh.edges]
for edge in edges:
    ax.plot(edge[:, 0], edge[:, 1], edge[:, 2], c="lightblue")

f = 4
face = mesh.vertices[mesh.edges[mesh.faces[f]]]
for edge in face:
    ax.plot(edge[:, 0], edge[:, 1], edge[:, 2], c="blue")
```

![image](https://github.com/mikedh/trimesh/assets/115336923/13bc7235-8c29-4efd-bae4-9fd22bdab1ec)

Some faces are ok, for example `f = 0`

![image](https://github.com/mikedh/trimesh/assets/115336923/2aa5f7f4-f194-44b1-a558-687c182643d9)

but most of the faces are broken. Did I do something wrong?

**Comment by jrunkening** [comment]
I also export `STL` file from blender, and get the same issue

**Comment by Kiord** [comment]
```mesh.faces[f]``` gives the indices `[v1, v2, v3]` of the vertices of the face of index `f`, so ```mesh.edges[mesh.faces[f]]``` does not make sense because `mesh.edges` should be indexed by edge indices, not vertex indices.

What you want is maybe the following :


```python
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
edges = mesh.vertices[mesh.edges] # E 2 3
for edge in edges:
    ax.plot(edge[:, 0], edge[:, 1], edge[:, 2], c="lightblue")

f = 4
face = mesh.vertices[mesh.faces[f]] # 3 3
rotated_face = np.roll(face, 1, axis=0)
edges = np.stack((face, rotated_face), axis=1) # 3 2 3

for edge in edges :
    ax.plot(edge[:, 0], edge[:, 1], edge[:, 2], c="blue")
```

**Comment by jrunkening** [comment]
Yes, thank you for pointing out the return values. Now I understand.
