### ISSUE TITLE
display Path3D in jupyter notebook

### ISSUE THREAD

**Issue by foobarbecue** [mikedh/trimesh#205]
It's possible to .show() a Path3D object using pyglet, but if you're in the notebook you get:

`AttributeError: 'Path3D' object has no attribute 'visual'`

Presumably this is because the path needs to be "inflated" into a mesh in order to export it to gltf? I guess doing that would be an enhancement.

In the meantime, a better error might be nice -- something that explains that 3d paths can be shown using pyglet but not in a browser.

**Comment by mikedh** [comment]
Ah yeah, a better error message on the notebook viewer would be nice and I'll look in to it. 

As an enhancement, the GLTF format supports GL geometry modes, which seems like it would be pretty easy to export Path objects as GL_LINES. However I don't think the `three.js` loader supports GL_LINES but I don't actually know. 

Another option is adding a `path.inflate` or something, which returns a `trimesh.Trimesh` object with line segments represented as roughly meshed cylinders, which the Jupyter viewer calls on Path objects before exporting to GLTF.

Thanks for the report! It's nice to hear someone is using the notebook viewer functionality 😄

**Comment by foobarbecue** [comment]
Hi mikedh, I just checked and the three.js loader does support GL_LINES. [Here's](https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/OutlinedBox) an example. I think adding notebook .show() to Path3D using GL_LINES might be a fun project for me... I'll see if I can cook up a PR today unless you tell me not to!

**Comment by mikedh** [comment]
Yeah that sounds terrific! Let me know if you need any help. 

It seems like if the three.js loader supports it, this would just require refactoring [this block](https://github.com/mikedh/trimesh/blob/master/trimesh/io/gltf.py#L270-L297) to special case Path2D and Path3D objects (maybe break that logic out into a function).

**Comment by mikedh** [comment]
Oh another thing that might be helpful, [`trimesh.rendering.path_to_vertexlist`](https://github.com/mikedh/trimesh/blob/master/trimesh/rendering.py#L107-L146) converts Path2D and Path3D objects to GL- formatted arguments, it might be an option to reuse or refactor some of that logic.
