### ISSUE TITLE
Export mesh in .msh fileformat

### ISSUE THREAD

**Issue by Walshaikhli** [mikedh/trimesh#206]
First, thank you for maintaining Trimesh, I have used it for a day so far and it's an amazing tool! I wish i knew it existed a year ago! 

I was wondering if I can export .msh files directly from Trimesh, this is the GMSH program format, and it's used in the state of the art EM solvers such as SCUFF-EM. I can use GMSH to convert to .msh but I'm hoping to use Trimesh for it. 

Here is what I'm doing:
`trimesh.io.export.export_mesh(mesh,'outputFile', file_type="msh")`

Here is the error I get:

> ValueError                                Traceback (most recent call last)
> <ipython-input-18-3d4dc592d077> in <module>()
> ----> 1 trimesh.io.export.export_mesh(mesh,'outputFile', file_type="msh")
> 
> ~\Anaconda3\lib\site-packages\trimesh\io\export.py in export_mesh(mesh, file_obj, file_type, **kwargs)
>      39 
>      40     if not (file_type in _mesh_exporters):
> ---> 41         raise ValueError('%s exporter not available!', file_type)
>      42 
>      43     log.debug('Exporting %d faces as %s', len(mesh.faces), file_type.upper())
> 
> ValueError: ('%s exporter not available!', 'msh')

**Comment by mikedh** [comment]
Hey, glad you're liking it!

Currently `msh` doesn't have any importers/exporters in `trimesh`. On the upside, the format is [very well specified](http://gmsh.info/doc/texinfo/gmsh.html#MSH-binary-file-format) and looks pretty easy to implement. If I get a chance I'll take a look at doing it, but if you're feeling energetic and want to PR here's the punch list for supporting it:

- add a <200kB test model of ASCII MSH in /models/
- add a <200kB test model of Binary MSH in /models
- add Binary/ASCII importer and Binary exporter to /trimesh/io/msh.py (either `ply.py` or `stl.py` might be good templates) that uses `np.fromstring` / `np.frombuffer` for key calls to avoid being mega slow. It might have to reject input meshes with elements other than triangles or quads. 
- Add unit tests to `test_export.py`, and also possibly check the validity of our exports using a subprocess call to `gmsh`

**Comment by mikedh** [comment]
Added to enhancements list. Thanks for the report!

**Comment by selvakarna** [comment]
Hi  mikedh ,
      I have Error while Create STL from X Y Z co-ordinates using Trimesh.

Can you share sample code for STL Creation , from X Y Z coordinates, [Faces and vertices from Trimesh]?
