### ISSUE TITLE
Boolean union output problem

### ISSUE THREAD

**Issue by aleBxrna** [mikedh/trimesh#2060]
I'm performing the boolean union of two meshes (I'm moving a single joint of a robot arm). The problem is that the parts of the robot that move are merged correctly, while for the parts that do not move I just get some surfaces as output. I think it is a vertices overlapping problem, how to solve it?

**Comment by mikedh** [comment]
Hey, I'd try this again with `manifold3d` that we just released the bindings for (`pip install --upgrade trimesh manifold3d`), it is a lot better in every way compared to previous boolean backends that were available: https://github.com/elalish/manifold

I'd also make sure your input meshes are volumes (`assert mesh.is_volume`) and possibly use the convex hulls if it's links of a robot arm (`mesh.convex_hull`)?
