### ISSUE TITLE
ray.intersects_location is not working with a single ray vector

### ISSUE THREAD

**Issue by franresquin** [mikedh/trimesh#2069]
When executing "ray.intersects_location" to find the interception between a ray in a mesh surface got the following error:

**File ~\.conda\envs\ssa\lib\site-packages\trimesh\ray\ray_triangle.py:364 in ray_bounds
    axis = np.abs(ray_directions).argmax(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1**

The issue is elicited when calling the "intersects_location" method with a single ray, the ray_directions vector has shape (3,) and therefore "argmax(axis=1)" raises the error since it does not have a second axis.

Following you can find a code example:

# test on a sphere primitive
mesh = trimesh.creation.icosphere()
# create some rays
ray_origins = np.array([0, 0, -3])
ray_directions = np.array([0, 0, 1])
locations, index_ray, index_tri = mesh.ray.intersects_location(
        ray_origins=ray_origins,
        ray_directions=ray_directions)

**Comment by Kiord** [comment]
A simple workaround consists in adding a leading dimension.  See `numpy.at_least_2d`.

**Comment by mikedh** [comment]
Yeah, for that we'd have to special-case a single ray which would also mean different return types which I think usually makes an API more confusing (and I've been trying to get away from in other functions). We should probably add a better error message, but I think you want them to just be a 1-element 2D array:

```
ray_origins = np.array([[0, 0, -3]])
ray_directions = np.array([[0, 0, 1]])
```

**Comment by franresquin** [comment]
Thank you for your reply.

I applied the same thing. I did not realize until now that the
documentation of the method says that the ray_direction must be (n,3).
