### ISSUE TITLE
Mesh color changes after loading and storing

### ISSUE THREAD

**Issue by alvaro-budria** [mikedh/trimesh#2071]
I am facing a problem with the colors of a mesh.
When I visualize a given mesh (stored in .obj format) in meshlab, I see the following mesh, with brighter colors:
![Screenshot from 2023-11-12 11-01-16](https://github.com/mikedh/trimesh/assets/48391578/e45d9de0-5e51-4684-ba1a-7d8fdbea9479)

However, when I load this mesh with
`mesh = trimesh.load_mesh(mesh_path)`
and store it with
`mesh.export(out_path)`
and then visualize it with meshlab, I see a much darker mesh:
![Screenshot from 2023-11-12 11-01-22](https://github.com/mikedh/trimesh/assets/48391578/4652ce6c-d5d2-49b3-b7f5-63eba99cef5b)

I did not modify the mesh in any way, except for loading and storing it, so I don't understand what causes the change.

I am facing this issue both in `3.18` and `4.0.4` versions.

Can you please help me keep the original mesh color?

**Comment by Kiord** [comment]
Meshlab multiplies the texture color with the vertex color (white as default). Trimesh default vertex color is grey (0.5, 0.5, 0.5) that's why the mesh appears darker on Meshlab after import/export. 
It is only a visualization issue, setting the vertex colors to white before the export will fix it.

**Comment by Kiord** [comment]
Ah yes texture visuals has no vertex color... The grey vertex colors are written automatically on the file I guess. 
Else you can set a user def color in meshlab

**Comment by alvaro-budria** [comment]
Then I understand there's no way of getting around this with Trimesh...

**Comment by Kiord** [comment]
After a check, the problem comes exclusively from Meshlab which uses the user defined color when no vertex colors are featured in the file. This default color is (0.75,0.75,0.75) and not (0.5,0.5,0.5) like I said. Sadly, its not possible to edit the default value.

**Comment by chlooooe** [comment]
Hi @alvaro-budria,
Could you solve your issue by any chance? I have the same as you.
My script is as below, but the final 3D image is too dark. I can I make the whole thing lighter?

import numpy as np
import trimesh
from PIL import Image

im = Image.open("4653_part_1.1001.jpg")
mesh = trimesh.load('4653_part_1.obj',process=False)
tex = trimesh.visual.TextureVisuals(image=im)
mesh.visual.texture = tex
mesh.show()
