### ISSUE TITLE
invalid-shift-base UndefinedBehaviorSanitizer error

### ISSUE THREAD

**Issue by omkardandekar** [mikedh/trimesh#2072]
https://github.com/mikedh/trimesh/blob/46b6aaf4de490b529d6b0d818a55fc070dd022d4/trimesh/grouping.py#L204

We use trimesh and with Python 3.10. And, during testing, UndefinedBehaviorSanitizer (UBSAN) threw an error with this operation when the contents of the `column` are negative values.  I see that this is an optimization put in place in case _"array is 2D and smallish"_, but is there a way to accomplish this efficiently while not triggering  UndefinedBehaviorSanitizer error? I would greatly appreciate and thoughts and suggestions. Thank you.

```
numpy/core/src/npymath/npy_math_internal.h.src:657:18: runtime error: left shift of negative value -2
#0 0x7f4188a47bca in npy_lshiftl numpy/core/src/npymath/npy_math_internal.h.src:657
#1 0x7f4188a7e11f in LONG_left_shift_avx2

SUMMARY: UndefinedBehaviorSanitizer: invalid-shift-base numpy/core/src/npymath/npy_math_internal.h.src:657:18 in
```

**Comment by mikedh** [comment]
Seems like we can offset to the minimum there, which I just PR'd. Looking at that function there's probably a faster way to do the grouping but this is ok for now.

How were you running the tests? It doesn't look like there's an easy way to run that behavior checker via pytest.
