### ISSUE TITLE
How to export a scene to SVG?

### ISSUE THREAD

**Issue by OpenFoam-User** [mikedh/trimesh#2074]
Hello,

Is it possible to export a Scene from STL to an SVG file? I have checked the documentation but I cannot find how to do that.

Thank you

**Comment by mikedh** [comment]
Hey, you'd have to first convert it to a Path2D, here's an example using `mesh.projected`:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/1002_tray_bottom.STL')

In [3]: m.extents
Out[3]: array([355.6  ,   3.175, 355.6  ])

In [4]: path = m.projected([0,1,0])

In [5]: path.show()
Installed tk event loop hook.

In [6]: _ = path.export('projected.svg')
```

Playing with the colors in inkscape:

![Screenshot from 2023-12-08 16-21-33](https://github.com/mikedh/trimesh/assets/1403074/1c2c72df-8d57-4357-8a12-32fd1e3c59da)

**Comment by OpenFoam-User** [comment]
@mikedh 
Many thanks for your example.

One last question: is it possible to export a **3D** view of an STL object without projecting it to a plane? I mean projecting the 3D mesh to a plane will slice it.
