### ISSUE TITLE
Colored triangular file

### ISSUE THREAD

**Issue by AmitMY** [mikedh/trimesh#208]
I created a .obj mesh file using las2tin, from a colored las file.

I ran the code in your basic installation and saw a shape similar to what I was hoping, but with random colors. I remove the colors, and now everything is grey.

Do you support colored .obj files?

**Comment by mikedh** [comment]
Do the colors look like what you expect in Meshlab? Can you send over the file? I don't believe the trimesh OBJ loader supports face colors at the moment (the PLY one does).

**Comment by mikedh** [comment]
Closing for now, though feel free to re-open!
