### ISSUE TITLE
`No FCL Available!` on Mac M3 despite python-fcl being installed

### ISSUE THREAD

**Issue by araistrick** [mikedh/trimesh#2081]
In a fresh python3.10/3.11 environment on OSX 14.1 Sonoma with a M3 MAX chip, I get the following:

```
pip install python-fcl trimesh

...
ValueError: No FCL Available! Please install the python-fcl library
```

However, if I `import fcl` before importing trimesh, I get:

```
ImportError: dlopen(/Users/araistrick/miniconda3/envs/infinigen/lib/python3.10/site-packages/fcl/fcl.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__ZNK3fcl17CollisionGeometryIdE34computeMomentofInertiaRelatedToCOMEv'
```

So I think it is likely the case that trimesh is trycatching all ImportErrors as mechanism to detect pythonfcl not being installed, and is suppressing this issue from python-fcl. 

All in all it seems to largely not be caused by trimesh, but thought this could still be informative. I investigated a bit further in my issue on their repo:
https://github.com/BerkeleyAutomation/python-fcl/issues/73

**Comment by mikedh** [comment]
Hey, I tried building the wheels with one of the suggestions in that issue, but have no way of testing them: https://github.com/BerkeleyAutomation/python-fcl/pull/74

**Comment by mikedh** [comment]
Closing in favor of upstream issue https://github.com/BerkeleyAutomation/python-fcl/issues/73
