### ISSUE TITLE
How to export a mesh as a ply file, with some customized attributes?

### ISSUE THREAD

**Issue by YAndrewL** [mikedh/trimesh#2089]
Hi, thanks for your great work!
I want to save the mesh as a ply file with some extra attributes, and I try to use the `export` methods in Trimesh.
For example:
```
mesh.export('output.ply', encoding='ascii')
```
But this line only save the coordinates  x, y and z, what can I do if I also want to save normals and some extra features?

**Comment by njpatter** [comment]
Hi YAndrewL,

Have you tried using the export_ply function directly?
[https://trimesh.org/trimesh.exchange.ply.html](url)

`trimesh.exchange.ply.export_ply(mesh, encoding='binary', vertex_normal: bool | None = None, include_attributes: bool = True)`

**Comment by YAndrewL** [comment]
Thanks for your reply!
