### ISSUE TITLE
Skip loading texture

### ISSUE THREAD

**Issue by xiaoxiae** [mikedh/trimesh#2093]
Loading a texture for certain models (e.g. generated by photogrammetry) can take quite a while when the texture is large (~hundreds of megabytes). It might be a good idea to add an argument for the loaders to not load the texture since we might only care about the mesh itself.

Would a PR that implements this for the mesh loaders be welcome?

**Comment by xiaoxiae** [comment]
It seems that certain formats have options that do this (e.g. obj's skip_materials) but certain don't (e.g. PLY, which is why I created this issue). I guess I could just implement it for PLY?

**Comment by mikedh** [comment]
Yeah PR's super welcome on this thanks for looking in to it!

**Comment by xiaoxiae** [comment]
Closing since it was merged.
