### ISSUE TITLE
Why the rendered orientation of the mesh is different from orientation in the homogenous transformation matrix?

### ISSUE THREAD

**Issue by amdshameer** [mikedh/trimesh#2095]
My trimesh version is: 3.23.5 and it cannot be upgraded due to other dependencies in the project. When the mesh is visualized either through ax.plot_trisurf() or scene.show(), it has the correct the orientation. However, when I get the homogeneous transformation matrix of the mesh, it is not correct.

Expected rotation matrix for 45 deg along z-axis:
[  0.7071068, -0.7071068,  0.0000000
   0.7071068,  0.7071068,  0.0000000
   0.0000000,  0.0000000,  1.0000000 ]

bounding_box_oriented.transform[:3, :3]:
[[-0.70711, -0.,      -0.70711]
 [-0.70711,  0.,       0.70711]
 [ 0.,       1.,       0.     ]]

Perhaps, I should get the homogeneous transformation matrix by other methods, instead of using bounding_box_oriented.transform. And, could it be due to the mismatch between left-handed and right-handed coordinate system convention used by trimesh.

```py
import trimesh
from shapely.geometry import Polygon
from shapely import affinity

## polygon is rotated 45.0 deg along z-axis in the center using: affinity.rotate(polygon, 45.0, origin='centroid')
rotated_irregular_polygon = Polygon([(0.01945921121197126, 0.06471404520791033), 
(0.04774348245943317, 0.09299831645537222), (0.104312024954357, 0.06471404520791031), 
(0.06188561808316411, 0.02228763833671747), (0.01945921121197126, 0.06471404520791033)])
extruded_shapely_mesh = trimesh.primitives.Extrusion(polygon=rotated_irregular_polygon, height=0.06).to_mesh()
print extruded_shapely_mesh.bounding_box_oriented.transform

ax.plot_trisurf(extruded_shapely_mesh.vertices[:, 0], extruded_shapely_mesh.vertices[:, 1], extruded_shapely_mesh.vertices[:, 2], triangles=extruded_shapely_mesh.faces, color='yellow', edgecolor='none', linestyle='-', alpha=1.0)
scene = trimesh.Scene(extruded_shapely_mesh)
#scene.show()
plt.show()
```

**Comment by mikedh** [comment]
Hey, yeah `bounding_box_oriented` is a computed property from the surface of the mesh convex hull. For example with a cube, there are 6 possible equally correct "clockings" of the oriented bounding box, and there is no information generally which of those is correct. 

If your mesh has symmetry you could try `mesh.principal_inertia_transform`, possibly comparing it to the oriented bounding box. But you'll probably have to do additional calculations with additional information to confirm the clocking of the OBB transform against what you want.

```
In [3]: m = trimesh.creation.cylinder(radius=1, height=10).permutate.transform()

In [4]: m
Out[4]: <trimesh.Trimesh(vertices.shape=(66, 3), faces.shape=(128, 3))>

In [5]: m.bounding_box_oriented
Out[5]: <trimesh.primitives.Box>

In [6]: m.bounding_box_oriented.primitive.transform
Out[6]: 
TrackedArray([[ 4.72224329e-01,  8.80185054e-01,  4.77331607e-02,
               -3.82703725e+02],
              [ 7.14086656e-01, -3.50239818e-01, -6.06145458e-01,
                1.03502273e+02],
              [-5.16802119e-01,  3.20322245e-01, -7.93920165e-01,
               -2.35176707e+02],
              [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
                1.00000000e+00]])

In [7]: m.principal_inertia_transform
Out[7]: 
array([[ 6.39019992e-01, -5.92359309e-01,  4.90676980e-01,
         4.21261663e+02],
       [ 7.67707623e-01,  5.30752421e-01, -3.59063884e-01,
         1.54427023e+02],
       [-4.77331607e-02,  6.06145459e-01,  7.93920165e-01,
         1.05706438e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

```
