### ISSUE TITLE
Path2D offset() functionality

### ISSUE THREAD

**Issue by mrmoss** [mikedh/trimesh#210]
Openscad has a neat function that can grow/shrink all sides of 2d shapes:
[https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#offset](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#offset)

I'm trying to implement this now, but figured I'd mention it in an issue.

**Comment by mikedh** [comment]
Hey, if you are OK with discrete (polygonal) areas, the Shapely offset works very reliably:

```
In [1]: import trimesh

In [2]: d = trimesh.load('models/2D/wrench.dxf')

In [3]: d.polygons_full
Out[3]: 
array([<shapely.geometry.polygon.Polygon object at 0x7fa7e268fcf8>],
      dtype=object)

In [4]: polygon = d.polygons_full[0]

In [5]: polygon.area
Out[5]: 1.6668888517447935

In [6]: offset = polygon.buffer(-.025)

In [7]: offset.area
Out[7]: 1.3802619495395194

```

**Comment by mrmoss** [comment]
Is there a simple way to update the Path2D with the updated polygons? I'm guessing just setting them with something like below is not the "right way" to do this?
```
d.polygons_full[0]=d.polygons_full[0].buffer(-1)
```

**Comment by mikedh** [comment]
Hey, I think you probably want to create a new `Path2D` rather than mutating the original. The polygons_full are a generated property from `path.vertices` and `path.entities`

```
In [1]: import trimesh

In [2]: d = trimesh.load('models/2D/wrench.dxf')

In [3]: polygon = d.polygons_full[0].buffer(-.06)

In [4]: trimesh.load_path(polygon)
Out[4]: <trimesh.path.path.Path2D at 0x7f9b3d3bf978>

```

**Comment by mrmoss** [comment]
That seems to work. This might be a separate issue, but I'm noticing that `.extrude()` isn't outputting what I expect. At first I thought it might be `.buffer()`, but I took it out and it is still happening.

I load this stl via `test_stl=trimesh.load('hollow_cylinder.stl')`:
![section_teststl](https://user-images.githubusercontent.com/1828563/44926811-90851680-ad20-11e8-9442-da6b72427bc3.png)

Then I take a section with `section_3d=test_stl.section(plane_normal=[0,0,1],plane_origin=[0,0,5])`:
![section_3d](https://user-images.githubusercontent.com/1828563/44926913-db069300-ad20-11e8-9d3e-781af38e74d6.png)

Convert to 2d with `section_2d,section_2d_trans=section_3d.to_planar()`:
![section_2d](https://user-images.githubusercontent.com/1828563/44926954-f1145380-ad20-11e8-9ea9-e7a8292f0c31.png)

Extrude and save stl `section_2d.extrude(5).export('output.stl')`:
![section_2d_extruded](https://user-images.githubusercontent.com/1828563/44927233-b5c65480-ad21-11e8-9956-a7963249fcc8.png)

Do I need to do something else to access all polygons in the 2d section (I'm guessing the green lines indicate something)?

**Comment by mikedh** [comment]
Ah yeah- the colors indicate detected interiors vs detected exteriors, and it's weird because of the multiple bodies. 

I might suggest splitting the source mesh into individual bodies (`mesh.split`) before running the section on each body individually. If you extrude each of those polygons it should result in that source mesh if you concatenate after extruding.

**Comment by mrmoss** [comment]
That doesn't always work.

For instance: Say we use a single hollow cylinder where the walls are along the [0,0,1] normal. If we section across a normal to one of the exterior wall faces (say [1,0,0]), the majority of sections will have more than one body, even though the original model doesn't have multiple bodies.

I think I might be able to do this in a similar way though:
1. section
2. split 2d sections into contiguous groups
3. extrude each 2d contiguous group
4. join 3d contiguous groupss

I'll go give it a shot!

**Comment by mikedh** [comment]
I think the core issue is the `enclosure_tree` logic (which turns a jumble of boundaries into actual polygons with exteriors/interiors) doesn't support regions contained in the interiors of other regions. 

I added some logic and a test in https://github.com/mikedh/trimesh/commit/9b970bfd27c30881803a43a6b7615e22ca055559, I think your example should work now. It will return two extrusions, which you can concatenate into one mesh with something like `np.sum(path.extrude(1.0))`

**Comment by mrmoss** [comment]
You're awesome! On a few of the test pieces I've run I'm getting the following:
```
Traceback (most recent call last):
  ...
    print_red(section_2d.extrude(3))
  File "/usr/local/lib/python3.5/dist-packages/trimesh/path/path.py", line 1033, in extrude
    for i in self.polygons_full]
  File "/usr/local/lib/python3.5/dist-packages/trimesh/path/path.py", line 1033, in <listcomp>
    for i in self.polygons_full]
  File "/usr/local/lib/python3.5/dist-packages/trimesh/primitives.py", line 547, in __init__
    kwargs)
  File "/usr/local/lib/python3.5/dist-packages/trimesh/primitives.py", line 130, in __init__
    self._data[key] = util.convert_like(value, defaults[key])
  File "/usr/local/lib/python3.5/dist-packages/trimesh/util.py", line 1403, in convert_like
    item = like.__class__(item)
  File "/usr/local/lib/python3.5/dist-packages/shapely/geometry/polygon.py", line 240, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/usr/local/lib/python3.5/dist-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 234, in shapely.speedups._speedups.geos_linearring_from_py
  File "/usr/local/lib/python3.5/dist-packages/shapely/geometry/base.py", line 794, in __array_interface__
    raise NotImplementedError("Multi-part geometries do not themselves "
NotImplementedError: Multi-part geometries do not themselves provide the array interface
```
I looked into this a bit - and it looks to me that this is because polygons in polygons_full are sometimes instances of MultiPolygon instead of Polygon?

**Comment by mikedh** [comment]
No worries! Hmm, `polygons_full` should definitely be a regular `Polygon` object. Would you be able to mail me the model and script that produced this traceback at mikedh@kerfed.com?

Thanks!
Mike

**Comment by mrmoss** [comment]
Nevermind - I didn't realize that buffer() can return multipolygons, so I just had to turn each of those into a Path2d, extrude, and join into a single mesh.

Thanks a ton!

**Comment by mikedh** [comment]
Sounds good, glad it's working for you!

**Comment by elrapha** [comment]
I have a follow up question. How does one get the transformation matrix that is needed  When you call .to_planar() 
For the to_2d parameter. I am guessing so that the values of the vertices do not change in the 2d dimension.
