### ISSUE TITLE
Unable to load small GLB model

### ISSUE THREAD

**Issue by elionet-igonogo** [mikedh/trimesh#2101]
Hi,

I'm trying to load the vertices and faces information of a "small" GLB model (whose vertices coordinates are between [-1;1], but I'm unable to get its correct coordinates.

The model doesn't seem to have issue as I'm able to load it in a viewer and it is displayed correctly : 
![image](https://github.com/mikedh/trimesh/assets/121807053/ec0acae7-57c9-41be-a8aa-0c82c3e47a2c)

This is how 'm trying to load the file :
[ModelB.glb.zip](https://github.com/mikedh/trimesh/files/13739669/ModelB.glb.zip)

```
import trimesh

obj = trimesh.load('ModelB.glb', force='mesh', process=False)

print(obj.vertices)
```

Unfortunately, all given vertices coordinates seems to be the same : 
```
[[-0.3007412  -0.90367654  0.07108393]
 [-0.3007412  -0.90367654  0.07108393]
 [-0.3007412  -0.90367654  0.07108393]
 ...
 [-0.3007412  -0.90367654  0.07108393]
 [-0.3007412  -0.90367654  0.07108393]
 [-0.3007412  -0.90367654  0.07108393]]
```

(Setting `process=True` will remove all duplicated vertices and only keep 1)

I'm using Python 3.9.6 and Trimesh 4.0.7

Is it possible load such file using trimesh ?

**Comment by eliphatfs** [comment]
The GLB has the `KHR_draco_mesh_compression` extension, which is not supported by trimesh loader.

**Comment by eliphatfs** [comment]
See #1975

**Comment by elionet-igonogo** [comment]
Thank you @eliphatfs, the issue seems indeed to come from the `KHR_draco_mesh_compression` extension.
I have been able to retrieve the original file (without draco), and have been able to load the file correctly.
