### ISSUE TITLE
GLB is not exported correctly

### ISSUE THREAD

**Issue by NatKov** [mikedh/trimesh#2111]
This code works as expected in versions 3... but exports glb with white color only in latest 4.0.8 version

 ```

mesh = trimesh.Trimesh(vertices, tris)
mesh.visual.face_colors = .... #setting rgb color per face
unique_colors = np.unique(mesh.visual.face_colors, axis=0)

scene = trimesh.Scene()
    for c in unique_colors:
        tri_mask = (mesh.visual.face_colors == c).all(axis=1)
        tmp_mesh = trimesh.Trimesh(vertices)
        tmp_mesh.faces = mesh.faces[tri_mask]
        tmp_mesh.remove_unreferenced_vertices()
        tmp_mesh.visual = trimesh.visual.TextureVisuals(
            material=trimesh.visual.material.PBRMaterial(
                baseColorFactor=c, main_color=c, metallicFactor=0.5, roughnessFactor=0.1
            )
        )
        scene.add_geometry(tmp_mesh)

    # this is uploadable to cesiun ion
    with open("check.glb"), "wb") as f:
        f.write(trimesh.exchange.gltf.export_glb(scene))
```

**Comment by njpatter** [comment]
I believe this is actually related to either (1) how you are setting up the texture visuals, or (2) an issue with texture visuals.  The following code creates a scene with just a grey sphere, when there are actually many different and unique colors added via the TextureVisuals call:

`mesh = trimesh.load("SmoothSphere.STL")

for facet in mesh.facets:
  mesh.visual.face_colors[facet] = trimesh.visual.random_color() 
unique_colors = np.unique(mesh.visual.face_colors, axis=0)

scene = trimesh.Scene()
for c in unique_colors: 
    tri_mask = (mesh.visual.face_colors == c).all(axis=1)
    tmp_mesh = trimesh.Trimesh(mesh.vertices)
    tmp_mesh.faces = mesh.faces[tri_mask]
    tmp_mesh.remove_unreferenced_vertices()
    tmp_mesh.visual = trimesh.visual.TextureVisuals(
        material=trimesh.visual.material.PBRMaterial(
            baseColorFactor=c, main_color=c, metallicFactor=0.5, roughnessFactor=0.1
        )
    )
    scene.add_geometry(tmp_mesh) 
scene.show()`

**Comment by jburns-spatialreality** [comment]
I am having the same issue with PBR Materials being imported from another glb exporter, and during export the settings around buffer View are modified per the glTF validation tool.

            {
                "code": "BUFFER_VIEW_TARGET_MISSING",
                "message": "bufferView.target should be set for vertex or index data.",
                "severity": 3,
                "pointer": "/meshes/0/primitives/0/attributes/POSITION"
            },
            {
                "code": "BUFFER_VIEW_TARGET_MISSING",
                "message": "bufferView.target should be set for vertex or index data.",
                "severity": 3,
                "pointer": "/meshes/0/primitives/0/attributes/NORMAL"
            },
            {
                "code": "BUFFER_VIEW_TARGET_MISSING",
                "message": "bufferView.target should be set for vertex or index data.",
                "severity": 3,
                "pointer": "/meshes/0/primitives/0/indices"
            },

This is recurring during the process. The original glb is valid.
