### ISSUE TITLE
Please tag releases on GitHub

### ISSUE THREAD

**Issue by hroncok** [mikedh/trimesh#212]
There are releases on PyPI but the sdist tarballs lack extras (tests etc.) - I'd like to download appropriate tarballs form GitHub, but there are no tags.

Thanks.

**Comment by mikedh** [comment]
Good idea, and it looks like [Travis supports it](https://docs.travis-ci.com/user/deployment/releases/) as a deployment, I'll add it when I get a chance.

**Comment by mikedh** [comment]
Travis is [now releasing](https://github.com/mikedh/trimesh/releases) version- tagged tarballs, which include tests/models.

**Comment by hroncok** [comment]
Thanks. Github does the tarballs for you, so if it's just a git checkout, I think it might be unnecessary.
