### ISSUE TITLE
trimesh.boolean.intersection returning both meshes together

### ISSUE THREAD

**Issue by Erkhembayaar** [mikedh/trimesh#2120]
trimesh.boolean.intersection([clip_ply, clipper_ply], engine="blender")
The mesh I want to return is highlighted in red below
![image](https://github.com/mikedh/trimesh/assets/71809096/de74808b-c9b3-4633-b085-248174824bbd)

why could this happen?

**Comment by mikedh** [comment]
Hey, the blender booleans are not particularly reliable, have you tried `pip install manifold3d` and using that as the boolean backend?

**Comment by Erkhembayaar** [comment]
I tried manifold3d 
trimesh.boolean.intersection([clip_ply, clipper_ply], engine="manifold") returns empty meshes where blender engine somewhat worked

**Comment by mikedh** [comment]
Are both meshes watertight positive volumes, i.e. does `assert mesh.is_volume` pass for both inputs?

**Comment by Erkhembayaar** [comment]
manifold output seem to change vertices and faces
![image](https://github.com/mikedh/trimesh/assets/71809096/16a2daf6-f89f-46c1-8f32-01fb547d84a0)
is there any way to prevent it?

**Comment by Erkhembayaar** [comment]
Closing this as I raised PR to resolve this: https://github.com/mikedh/trimesh/pull/2145
