### ISSUE TITLE
Returning contact normals

### ISSUE THREAD

**Issue by paperstiger** [mikedh/trimesh#214]
Hi Mike,

I am having problem returning contact normals for collision data from pcl. I see that you are only returning contact points and IDs in your code, but I need to have contact normal data returned as well.

I changed your file collision.py in disk packages to add:
`

    def normal(self):
        """
        Normal for this contact.

        Returns
        -------
        point: (3,) float, the contact normal.
        """
        return self._normal`

But the result returned is a class instance rather than the numpy vector I was hoping for. Please let me know what I did wrong here. Thank you for your advice in advance!

**Comment by mikedh** [comment]
It seems like the easiest thing to do would be to use the triangle ID to pull the face normal from `mesh.face_normals`

**Comment by paperstiger** [comment]
Thanks, that works too
