### ISSUE TITLE
Mojo supported version?

### ISSUE THREAD

**Issue by juanZaragozaChichell** [mikedh/trimesh#2146]
Hi! I was wondering if there is a future projection of adapting this wonderful project into the Mojo language. I work with trimesh every day and I think that it could really benefit from the speed up that Mojo provides (or so I think). Thank you for your time!!

**Comment by mikedh** [comment]
Hi! There are no plans to do so natively, at the moment mojo [doesn't support classes](https://docs.modular.com/mojo/roadmap.html#classes) or list/dict comprehensions which is most of the library 😄. Maybe in the future when they support more of the language and it has clear performance wins we can look at it. It seems like there's no reason [mojo.import_module](https://docs.modular.com/mojo/manual/python/) wouldn't work?
