### ISSUE TITLE
Bug in local_voxelize

### ISSUE THREAD

**Issue by marvinsxtr** [mikedh/trimesh#215]
Hi!
We might have discovered a bug with the local_voxelize function.
This is what the error looks like:
```
Traceback (most recent call last):
  File "./preprocessing.py", line 63, in <module>
    voxel = trimesh.voxel.local_voxelize(mesh, (16, 16, 16), 1, 32, fill=True)
  File "/home/marvin/.local/lib/python2.7/site-packages/trimesh/voxel.py", line 381, in local_voxelize
    local.apply_translation(-point)
AttributeError: 'list' object has no attribute 'apply_translation'
```
We've used this codesnippet to produce it:
```python
# Voxelize the mesh using trimesh
mesh = trimesh.load_mesh(args.path)
voxel = trimesh.voxel.local_voxelize(mesh, (16, 16, 16), 1, 32, fill=True)
print(voxel)
```

**Comment by mikedh** [comment]
Thanks for the report! This was happening when the function was called and no triangle was within `radius * pitch` of the center point. It should be fixed in master and pypi via https://github.com/mikedh/trimesh/commit/a0696267557ac03da8be55a3cc34a7c2d65990a3
