### ISSUE TITLE
Shortest path between vertices on a mesh surface

### ISSUE THREAD

**Issue by imaginary-unit** [mikedh/trimesh#216]
Hi!
I wonder if there is a function in trimesh to compute the shortest path between 2 vertices on a mesh surface? (i.e. we can only move from vertex to vertex using edges as shown on [this image](https://image.ibb.co/mb1kqK/Screenshot_20180907_145909.png) ). Can't find anything relevant in the examples.

If there isn't such a function, do you think it's worth adding to the lib? I believe it can be implemented using Dijkstra or A-star algorithm, or similar.

**Comment by mikedh** [comment]
Hey, I recently added an example that is pretty close to this: https://github.com/mikedh/trimesh/blob/master/examples/shortest.py

**Comment by imaginary-unit** [comment]
Cool, this looks like what I need. Thanks! :)

**Comment by mikedh** [comment]
Great! I added a notebook version as well: https://trimsh.org/examples/shortest.html
