### ISSUE TITLE
unexpected zero-degree adjacency_face_angles

### ISSUE THREAD

**Issue by qinyuzhuang** [mikedh/trimesh#2167]
[tube_885_2.stl.zip](https://github.com/mikedh/trimesh/files/14421162/tube_885_2.stl.zip)
Hi,

I loaded an STL file (see uploaded) with trimesh and wanted to get the face adjacency angles from it. When I checked the angles, I found some of them are zero degree (with np.where(mesh.face_adjacency_angles==0). However, when I visualized these pairs of adjacent faces, I found they were just coplanar instead of overlapping. Could you please give me some hints where the problems could be? Thanks a lot!

**Comment by Kiord** [comment]
The face adjacency angle is computed from the face normals : 

https://github.com/mikedh/trimesh/blob/3966450f9baf1a013c6f37b067c858748f78034a/trimesh/base.py#L1437-L1441

This means that coplanar neighbor faces typically have a null adjacency angle.

**Comment by mikedh** [comment]
Yeah as @Kiord  said `face_adjacency_angles` is the angle between the normal vectors of the pair of faces at the same index of `face_adjacency`, so coplanar faces will have zero angle.
