### ISSUE TITLE
loading partial textured obj file

### ISSUE THREAD

**Issue by yscoffee** [mikedh/trimesh#217]
Hi
is it possible to support loading partial textured obj files?
I have looked io\wavefront.py but not sure the vertex order part can be easily modified. (since now texture is smaller than vertices)

example obj file:
https://paste.ofcode.org/4nbuRAWyQN2v8hrVBFjzSk

**Comment by mikedh** [comment]
Texture isn't currently supported, but hopefully will be soon: https://github.com/mikedh/trimesh/issues/218

**Comment by mikedh** [comment]
Closing to consolidate into #218
