### ISSUE TITLE
AttributeError: module 'trimesh' has no attribute 'util'

### ISSUE THREAD

**Issue by postnubilaphoebus** [mikedh/trimesh#2175]
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trimesh
>>> trimesh.util.attach_to_log()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'trimesh' has no attribute 'util'
>>> trimesh.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'trimesh' has no attribute '__version__'
>>> import sys
>>> if "trimesh" in sys.modules:
...     print("trimesh installed")
... 
trimesh installed
System: Ubuntu 22.04.4 LTS

**Comment by mikedh** [comment]
Hey, how did you install trimesh? Have you tried running `pip install --upgrade trimesh`, or on a local checkout `pip install -e .`?

**Comment by mikedh** [comment]
This can also happen if you run your script next to a folder named `trimesh` that doesn't contain the `trimesh` library.

**Comment by postnubilaphoebus** [comment]
@mikedh 
Hi, thank you for the quick reply. I first tried `pip install trimesh`, and after that didn't work, I uninstalled it, and used `pip install trimesh[easy]`. The problem was fixed by rebooting my machine, which is odd.
