### ISSUE TITLE
Fail to open ctm file in 4.1.8

### ISSUE THREAD

**Issue by Discipe** [mikedh/trimesh#2178]
File "/usr/local/lib/python3.8/dist-packages/trimesh/exchange/load.py", line 139, in load
    raise ValueError("File type: %s not supported" % file_type)
ValueError: File type: ctm not supported

Working fine in 4.1.7 when loading CTM files.

**Comment by mikedh** [comment]
Ah yeah `trimesh.exchange.openctm` was deprecated as the packaging was pretty busted for most platforms. I just did a quick re-packing as wheels which I'd love some testing on if you want to give it a shot:

[pip install openctm](https://github.com/trimesh/openctm)
``` 
In [1]: import trimesh

In [2]: import openctm

In [8]: trimesh.exchange.load.mesh_loaders['ctm'] = openctm.load_ctm

In [9]: m = trimesh.load('headless.ctm')
```
