### ISSUE TITLE
obj mtl not loading as PBR material

### ISSUE THREAD

**Issue by frnsys** [mikedh/trimesh#2181]
I have a relatively straightforward obj+mtl (attached) that I'm trying to load and then export via trimesh. However I notice in the exported file there is only the base color texture, and the normal and occlusion textures aren't there.

After investigating it seems like the mtl is not read as a PBR material:

```
import trimesh

mesh = trimesh.load("3DBread003_LQ-1K-JPG.obj")
print(mesh.visual.material)
# <trimesh.visual.material.SimpleMaterial object at 0x7f76369b9ed0>
```

The mtl file:

```
newmtl 3DBread003_LQ-1K-JPG
Ns 50
Ka 1 1 1
Kd 1 1 1
Ks 0.1 0.1 0.1
Ke 0 0 0
Ni 1.45
d 1.000000
illum 2
map_Kd 3DBread003_LQ-1K-JPG_Color.jpg
map_bump -bm 1 3DBread003_LQ-1K-JPG_NormalGL.jpg
map_Ka 3DBread003_LQ-1K-JPG_AmbientOcclusion.jpg
```

is this the intended behavior? 

[3DBread003.zip](https://github.com/mikedh/trimesh/files/14556510/3DBread003.zip)

Thanks!

**Comment by mikedh** [comment]
Yeah, OBJ materials are loaded as a `SimpleMaterial`. This is the [typical MTL file](https://github.com/mikedh/trimesh/blob/main/models/fuze.obj.mtl) I've seen which doesn't have the additional parameters. Was that exported using the Blender PBR extension?

**Comment by frnsys** [comment]
It was actually from an obj I downloaded from sketchfab, but after reading a bit and trying some other libraries I understand now that PBR texture support is not standard for MTLs, so I'll close this issue. I appreciate the response all the same!
