### ISSUE TITLE
Add rtree to library dependencies

### ISSUE THREAD

**Issue by Metcoler** [mikedh/trimesh#2182]
When using trimesh.ray.ray_triangle.RayMeshIntersector, I got an error that rtree module doesn't exist. Just a simple pip install fix ... But maybe rtree could be added to library dependencies

**Comment by mikedh** [comment]
Hey, yeah the default install is a minimal numpy-only install, you probably want `pip install trimesh[easy]` as described in the [README](https://github.com/mikedh/trimesh?tab=readme-ov-file#basic-installation)
