### ISSUE TITLE
issues installing pyembree

### ISSUE THREAD

**Issue by juanZaragozaChichell** [mikedh/trimesh#2183]
Hi there! I have a similar issue as the one in [this issue](https://github.com/mikedh/trimesh/issues/875) . However, it seems like my issue is a bit different, not being able to install embreex itself. Any suggestions? Thank you very much!

I am using macOS Sonoma 14.2.1 on an M1 chip, if this is worth of anything.

**Comment by mikedh** [comment]
Hey, yeah trimesh switched to a fork of pyembree [embreex](https://github.com/trimesh/embreex) for maintenance reasons (i.e. wheels). It has wheels for most platforms but not ARM macs, and it might take a little work to get there:

- I think we'd have to finally update major versions of embree as I don't think 2.X supports macos.arm64? If someone wants to look into it this abandoned PR might be a good place to start: https://github.com/trimesh/embreex/pull/1
- then we add the arm64 package for embree, enable the `macos-14` actions runners, and wheels should be generated just fine.
