### ISSUE TITLE
find non occluded vertices

### ISSUE THREAD

**Issue by kk1153** [mikedh/trimesh#219]
If we have camera projection parameters K (intrinsic), R and T (extrinsic) (pose of the object with respect to the mesh), is there a way to find out which vertices of the mesh will be self occluded in the 2d image after the projection?

**Comment by mikedh** [comment]
Yeah, you probably want to do that with ray queries (`mesh.ray.intersects_any`) for every vertex. You could reduce the number of ray queries by first doing backface culling (dot product of mesh faces with direction vector). 

Although if you have `pyembree` installed it has it's own internal culling and does something like 600K rays/second so you probably are best off doing the straight ray queries for every vertex.

**Comment by mikedh** [comment]
Closing, though feel free to re- open if you have a problem with ray queries.

**Comment by kk1153** [comment]
Thanks. I have not tried ray tracing. But I see it requires me to set the rays myself by giving origin of 'm' rays and direction of 'm' rays. To my understanding, all the directions would be same as the direction along camera's optical axis and origin be pixel of coordinates of my image. Can you please help me if i am wrong?

**Comment by mikedh** [comment]
I think the easiest way is to probably check a ray from each vertex to the camera origin, and see if it hits anything:
```

In [57]: mesh = trimesh.primitives.Sphere()

In [58]: mesh.apply_translation([0,0,10])

In [59]: camera_origin = [0.0, 0.0, 0.0]

In [60]: ray_vectors = trimesh.unitize(camera_origin - mesh.vertices)

# offset origin slightly so ray doesn't self- hit
In [61]: ray_origins = mesh.vertices.copy() + ray_vectors * .01

In [62]: occluded = mesh.ray.intersects_any(ray_origins=ray_origins, ray_directions=ray_vectors)
```
