### ISSUE TITLE
Support for embree 4

### ISSUE THREAD

**Issue by alisoufali** [mikedh/trimesh#2191]
I have a python based project in which we use embree package as a backend for ray tracing with trimesh. Its been a while since Intel has released their stable versions of the embree 4 package. I tried to get it working with the trimesh and embreex packages but I wasn't successful.

I wanted to ask you to add this feature to the library since it performs really fast on CPUs.

**Comment by mikedh** [comment]
Hey, I've had pretty good performance with Embree 2.X on [trimesh/embreex](https://github.com/trimesh/embreex), although yeah it would be nice to update at some point. If someone wants to finish [this PR](https://github.com/trimesh/embreex/pull/1) it would be much appreciated! I don't currently have the cycles to work on it however. I'm going to close this issue in favor of issues on `embreex` or `pyembree`.
