### ISSUE TITLE
error in oriented bounding box

### ISSUE THREAD

**Issue by lorinma** [mikedh/trimesh#22]
Thanks for this nice work.

I've used it in several models, but for one object, I got an error when I try to get the oriented bounding box:
**Error in `python': free(): invalid pointer:** 

**data**:
'Faces': [[0, 1, 2],
   [0, 2, 3],
   [5, 2, 4],
   [4, 2, 1],
   [4, 6, 5],
   [6, 7, 5],
   [6, 0, 3],
   [7, 6, 3],
   [2, 5, 3],
   [3, 5, 7],
   [4, 1, 0],
   [4, 0, 6]],
  'Vertices': [[-1.8189894000000002e-12, 152.4, 0.0],
   [-8.1854523e-11, 152.4, 2438.4],
   [4572.0, 152.4, 2438.4],
   [4572.0, 152.4, 0.0],
   [185.32131, -152.4, 2438.4],
   [4572.0, -152.4, 2438.4],
   [185.32131, -152.4, 0.0],
   [4572.0, -152.4, 0.0]],

**Comment by mikedh** [comment]
Hey, it looks like this was from qhull crashing on duplicate 2D points in certain cases, specifically this case:

```    
array([[    0.     ,  -152.4    ],
       [    0.     ,  -152.4    ],
       [-4572.     ,   152.4    ],
       [-4572.     ,   152.4    ],
       [-4572.     ,  -152.4    ],
       [-4572.     ,  -152.4    ],
       [ -185.32131,   152.4    ],
       [ -185.32131,   152.4    ]])
```        
 Previously oriented_bounds_2D (which is ran on every facet of a 3D hull for the 3D OBB) did this:
    `c = ConvexHull(np.asanyarray(points))`

Removing duplicate points before hulling resolves the case you sent over:
```
points = np.asanyarray(points)
points_unique = points[grouping.unique_rows(points)[0]]
c = ConvexHull(points_unique)
```
 
The time hit is noticeable, but worth it given how hard qhull was crashing. Timing both the new and old behavior on a large set of meshes:

With pre merging before 2D hull (new behavior):
```   
In [1]: tic[-1] - tic[0]
Out[1]: 166.44400000572205

 In [2]: np.mean(np.diff(tic))
Out[2]: 0.5642169491719391
```

Old behaviour:
```
In [1]: tic[-1] - tic[0]
Out[1]: 147.22000002861023

In [2]: np.mean(np.diff(tic))
Out[2]: 0.49905084755461093
```

I added the mesh you sent over to the test_bounds checks. The fix and test are in commit https://github.com/mikedh/trimesh/commit/a66c535d213da4ed2682c18c15127cbd2cd826ea, and the build succeeded so you should be able to do a `pip install --upgrade trimesh` to get it. Thanks for the report!

**Comment by lorinma** [comment]
Thanks so much.
This works like a charm
Cheers
