### ISSUE TITLE
point sampling on the surface of mesh

### ISSUE THREAD

**Issue by kk1153** [mikedh/trimesh#220]
I am currently using trimesh.sample.sample_surface_even to find out some 'n' vertices evenly placed on the mesh but when i visualise them, they are not evenly placed and some vertices are lying alone on the surface of whereas some vertices lie forming a cluster around some area. Is there any suggestion to what can i do to get such evenly spread 'n' points on the surface of the mesh?

**Comment by mikedh** [comment]
I think the answer depends a lot on how you define "even." `sample_surface_even` is randomly sampling the surface then removing points closer than a radius, and is quick but not exact. If you want every point on the surface to have the same distance to every other point it is not trivial, the answer is probably some form of [mesh parameterization](http://www.cs.ubc.ca/~sheffa/papers/CGV011-journal.pdf), maybe 'periodic global parameterization.' 

That being said, `sample_surface_even` probably shouldn't have visible clusters, would you mind sending the mesh over so I could take a look? mikedh@kerfed.com

Oh also, `trimesh.remesh.subdivide_to_size` might be another option.

**Comment by mikedh** [comment]
Closing for now; feel free to re- open.
