### ISSUE TITLE
preventing merging of vertices on load

### ISSUE THREAD

**Issue by wtholliday** [mikedh/trimesh#221]
Is there a way I can prevent the geometric merging of vertices on load?

I have a sphere expressed as triangle soup, and I'd like each triangle to be a separate component.

It seems to merge the redundant vertices:

```
>>> sphere = trimesh.load('Desktop/sphere-soup.obj')
>>> sphere.is_watertight
True
>>> len(sphere.split())
1
```

I suppose I could perturb each vertex by a unique (small) value, but wondering if there's an easier way.

Thanks!

**Comment by mikedh** [comment]
Hey, if you pass `process=False` to load it should skip the merge:

```
In [1]: import trimesh

In [2]: a = trimesh.load('models/unit_cube.STL')

In [3]: a.vertices.shape
Out[3]: (8, 3)

In [4]: b = trimesh.load('models/unit_cube.STL', process=False)

In [5]: b.vertices.shape
Out[5]: (36, 3)
```

**Comment by wtholliday** [comment]
Thanks!
