### ISSUE TITLE
Obtaining the area of a mesh section

### ISSUE THREAD

**Issue by omaralvarez** [mikedh/trimesh#2214]
I am trying to get the area of the intersection of a mesh with a plane. Right now I am using the following code to get the section:

``` python
slice = mesh.section(
                plane_normal=n,
                plane_origin=p,
            )
```

Is it possible to get instead of the outline of the section a filled polygon? Is it possible to get a mesh from a Path3D?

**Comment by mikedh** [comment]
Hey, I think you want `slice.polygons_full[0].area` or `sum(p.area for p in slice.polygons_full)`

**Comment by omaralvarez** [comment]
Amazing, I will test it out and see if it works!! Thanks a lot!

**Comment by omaralvarez** [comment]
I'm getting the following error:

```
AttributeError: 'Path3D' object has no attribute 'polygons_full'
```

**Comment by omaralvarez** [comment]
Works like a charm, just for refererence I ended up with:

``` python
slice = mesh.section(
    plane_normal=n,
    plane_origin=p,
)
if slice is not None:
    area = sum(p.area for p in slice.to_planar()[0].polygons_full)
else:
    area = 0.0
```

If plane does not intersect you get None and it errors out.

Thanks a lot for the help!
