### ISSUE TITLE
should processing on load preserve watertightness?

### ISSUE THREAD

**Issue by wtholliday** [mikedh/trimesh#222]
My own code is telling me that my mesh is watertight, but when I load it with trimesh, I get:

```
>>> chas = trimesh.load('Desktop/chas.obj')
>>> chas.is_watertight
False
```

But then I noticed:

```
>>> chas = trimesh.load('Desktop/chas.obj', process=False)
>>> chas.is_watertight
True
```

The mesh is generated using marching cubes and may have zero-area triangles.

**Comment by mikedh** [comment]
Closing for now; feel free to re- open.

**Comment by LMescheder** [comment]
I also had some problems with this behavior and it took me a while to figure it out. Passing `validate=True` does not solve the problem for me, but I can set `process=False` which solves it.
I think it would indeed be much more intuitive to preserve watertightness by default and make the user request additional processing steps that break it deliberately.

**Comment by LMescheder** [comment]
Thanks for making this great package by the way. It's extremely helpful for my purposes.
