### ISSUE TITLE
Fkt: save_image stores a black image

### ISSUE THREAD

**Issue by uneidel** [mikedh/trimesh#223]
iam running the offrender sample and the function save_image leads to an png  which contains only black. (The header of png is valid). 

png = scene.save_image(resolution=[1080, 1080], visible=True)

mesh.show() shows the mesh 

thanks

**Comment by mikedh** [comment]
What version of Python and OS are you on? Have you updated pyglet recently?

**Comment by uneidel** [comment]
py27 on win10 with pyglet 1.3.2/0.16 thanks

**Comment by mikedh** [comment]
Hmm I was unable to reproduce this on Windows 10 with Python 2.7 and pyglet 1.3.2.

Is this with the latest version of `trimesh`?

**Comment by mikedh** [comment]
No worries- any idea what was going on with this? It's unfortunate offscreen rendering is so squirrely, though I don't have a good sense of how the blame is distributed between trimesh/pyglet/graphics drivers/OS.
