### ISSUE TITLE
set face colors based on their labels does not work properly

### ISSUE THREAD

**Issue by xuefeng7** [mikedh/trimesh#225]
I was trying to color each face based on its label. By checking mesh.visual.face_colors, color has been updated successfully; however, when viz it, only one color for all faces.

**Comment by mikedh** [comment]
I added face/vertex color support to GLTF/jupyter notebooks in https://github.com/mikedh/trimesh/commit/a40d9e2cab5951a8c5df1a7b9c2727f781ae0eab, if you do a `pip install --upgrade trimesh` you should be able to get it. I also added [an example](https://trimsh.org/examples/colors.html) with colors in the jupyter viewer.

It should show in both viewers (jupyter or pyglet) now.

**Comment by mikedh** [comment]
Closing for now- feel free to re-open if this isn't solved by the update. 

Thanks for the report!
