### ISSUE TITLE
extrude_polygon not creating watertight mesh

### ISSUE THREAD

**Issue by kgulmer** [mikedh/trimesh#2266]
I am trying to create a watertight mesh from a series of points to be used in the [boolean module](https://trimesh.org/trimesh.boolean.html) functions, which fail when the body does not meet the criteria for [is_volume](https://trimesh.org/trimesh.base.html#trimesh.base.Trimesh.is_volume).

[extrude_polygon](https://trimesh.org/trimesh.creation.html#trimesh.creation.extrude_polygon) is not returning the mesh as a watertight body as it should.

```
import trimesh
import shapely

coords = ((0., 0.), (0., 1.), (1., 1.), (1., 0.), (0., 0.))
polygon = shapely.geometry.Polygon(coords)

extrude = trimesh.creation.extrude_polygon(polygon,1)

print('is_watertight',extrude.is_watertight)
print('is_volume',extrude.is_volume)
```

**Comment by mikedh** [comment]
Hey, yeah results depends a lot on which [triangulation backend](https://github.com/mikedh/triangulator_benchmarks/) it's using, after `pip install manifold3d triangle mapbox-earcut`:

```
In [1]: import shapely, trimesh

In [2]: coords = ((0., 0.), (0., 1.), (1., 1.), (1., 0.), (0., 0.))
   ...: polygon = shapely.geometry.Polygon(coords)

In [3]: trimesh.creation.extrude_polygon(polygon,1, engine='triangle').is_volume
Out[3]: True

In [4]: trimesh.creation.extrude_polygon(polygon,1, engine='manifold').is_volume
Out[4]: False

In [5]: trimesh.creation.extrude_polygon(polygon,1, engine='earcut').is_volume
Out[5]: True


```

**Comment by mikedh** [comment]
It looks like manifold doesn't like the duplicated first-and-last vertex, and produces a watertight result when we clip it off. Thanks for the report!

**Comment by kgulmer** [comment]
Thanks! Yes, I am using manifold.

I also found just now that you can re-process the mesh with the validate flag and it resolves the issue.

```extrude.process(validate=True)```
