### ISSUE TITLE
mesh and plane intersection: how to map 2d back to 3d

### ISSUE THREAD

**Issue by xuefeng7** [mikedh/trimesh#227]
so by using

`lines2d, trans3d, _ = trimesh.intersections.mesh_multiplane(mesh, origin, direction, heights)`

we will get line segmentations (m, n, 2, 2) and transform matrices (m, 4, 4)

to map a point back, we first extend its 2d-coordination [x, y] to [x, y, z, 1], get transformation matrix T (4x4) for the current plane, and then 

`np.matmul(T, [x, y, z ,1])`

this will give us a [X, Y, Z, 1], and we can get rid of the last 1 (homogeneous transformation) and get the 3d-coordination. However, my question is what should I put as the z(lower case)?

Thanks for some explanations.

**Comment by mikedh** [comment]
Hey, if you set the 2D Z to 0.0 and then apply the transform, it should be back in the original frame (IIRC). Also `trimesh.transform_points` might be helpful, I always screw up the order when I do it manually 😁

**Comment by xuefeng7** [comment]
thank you
