### ISSUE TITLE
adding Robust Tetrahedral Meshing

### ISSUE THREAD

**Issue by hoosha** [mikedh/trimesh#228]
It would be great to integrate [this Robust Tetrahedral Meshing](https://github.com/Yixin-Hu/TetWild) to trimesh.

**Comment by mikedh** [comment]
Yeah that looks pretty cool! Looks like the have a command line version one could call via subprocess.

**Comment by mikedh** [comment]
Happy to accept PR's, but don't have the cycles to do this myself. I'll add it to the enhancement list. Thanks for the report!

**Comment by bbarroqueiro** [comment]
I have a very basic code (the communication between gmsh and trimesh is via file) that uses gmsh python api in order to generate tet meshes and extract the skin of finite element analysis (Nastran, Abaqus ... )...

If by any change some one finds it useful and can share...

The best regards
