### ISSUE TITLE
possible implementation of overlapping and touching test?

### ISSUE THREAD

**Issue by lorinma** [mikedh/trimesh#23]
Hi, I have a model consists of a list of 3D mesh shapes. I'm trying to find all the pairs of objects that are overlapping or touching.
The way I'm using trimesh now is to choose one mesh, traverse all the other meshes, use rtree find potential intersecting triangles, then do point contain tests to check if they are overlapping. There are three problems:
1. very slow
2. sometime the mesh has defect - not water tight, then the point contain test may fail
3. the objects touching test is not reliable

Do you have any advise on it?

Thanks!

**Comment by mikedh** [comment]
Yeah, the point contains test is quite slow, and without watertight meshes not going to tell you very much. Some ideas:

1) If you have 2 watertight meshes you can use boolean intersection methods of the Trimesh objects (which uses blender or openSCAD as a backend). This is always going to be a bit slow as well, and can give wonky results from precision issues.

2) You probably want an actual collision detection library- FCL is very popular and this python binding looks pretty interesting: https://github.com/jf---/python-fcl

**Comment by lorinma** [comment]
Thanks! 
The python-fcl, which uses bvh, does the work very well.
It seems most of the collision test libs like bullet3 all use bvh.

**Comment by lorinma** [comment]
Btw, I've built a conda package for python-fcl.

If you use [conda](http://conda.pydata.org/docs/)

you can easily install the python-fcl through:

conda config --add channels http://conda.anaconda.org/lorinma
conda install python-fcl=0.4.1

perhaps you can incorporate fcl into trimesh in this way.
