### ISSUE TITLE
How to get vertex attributes from a ply file?`

### ISSUE THREAD

**Issue by amaysaxena** [mikedh/trimesh#230]
I have a .ply mesh where each vertex is given R, G, B attributes along with an additional "label" attribute. When I load it into a mesh object, I see no method for querying these additional attributes; the vertices in the TriMesh object seem to store just the x-y-z locations of the vertices. What am I missing? Is there a way for me to access additional attributes from a loaded ply mesh?

**Comment by mikedh** [comment]
`mesh.visual.vertex_colors` should be populated if colors were loaded successfully. As far as custom vertex attributes, I think the loader probably discards them at the moment (though you may want to take a look [at the loader](https://github.com/mikedh/trimesh/blob/master/trimesh/io/ply.py) and see what it's doing.)

Best,
Mike

**Comment by amaysaxena** [comment]
Thanks for the response. Adding support for other attributes present in a mesh would be a good enhancement.

Also, I see that there is no way to sample a pointcloud from the surface of a mesh while also sampling rgb values for each point. What would be the best way to do this?

**Comment by mikedh** [comment]
I think the easiest thing to do for that would be barycentric interpolation of vertex colors, something like:

```
In [1]: import trimesh

In [2]: m = trimesh.load('scan_colored.ply')

In [3]: m.visual.kind
Out[3]: 'vertex'

In [4]: m.sample?
Signature: m.sample(count, return_index=False)
Docstring:
Return random samples distributed normally across the
surface of the mesh

Parameters
---------
count : int
  Number of points to sample
return_index : bool
  If True will also return the index of which face each
  sample was taken from.

Returns
---------
samples : (count, 3) float
  Points on surface of mesh
face_index : (count, ) int
  Index of self.faces
File:      ~/trimesh/trimesh/base.py
Type:      method

In [5]: points, index = m.sample(1000, return_index=True)

In [6]: points
Out[6]: 
array([[   15.31516868,  1021.58581583, -1113.3711676 ],
       [  -24.79543021,  1015.6714917 , -1066.41195113],
       [  -24.75460586,   997.48243622, -1064.56491206],
       ...,
       [  -17.87361083,  1116.61291232, -1141.4266736 ],
       [   25.32636975,  1090.06896245, -1169.94625487],
       [   23.12591318,  1104.03465446, -1128.25953031]])

In [9]: trimesh.triangles.points_to_barycentric?
Signature: trimesh.triangles.points_to_barycentric(triangles, points, method='cramer')
Docstring:
Find the barycentric coordinates of points relative to triangles.

The Cramer's rule solution implements:
    http://blackpawn.com/texts/pointinpoly

The cross product solution implements:
    https://www.cs.ubc.ca/~heidrich/Papers/JGT.05.pdf


Parameters
-----------
triangles: (n,3,3) float, triangles in space
points:    (n,3) float, point in space associated with a triangle
method:    str, which method to compute the barycentric coordinates with. Options:
           -'cross': uses a method using cross products, roughly 2x slower but
                     different numerical robustness properties
           -anything else: uses a cramer's rule solution

Returns
-----------
barycentric: (n,3) float, barycentric
File:      ~/trimesh/trimesh/triangles.py
Type:      function

In [10]: bary = trimesh.triangles.points_to_barycentric(m.triangles[index], points)

In [11]: bary
Out[11]: 
array([[0.45757542, 0.33504995, 0.20737463],
       [0.14558848, 0.83881582, 0.0155957 ],
       [0.00556909, 0.67700657, 0.31742435],
       ...,
       [0.01974312, 0.39138791, 0.58886897],
       [0.02254759, 0.22921391, 0.7482385 ],
       [0.02188417, 0.69873739, 0.27937844]])

In [16]: import numpy as np

In [17]: (m.visual.vertex_colors[m.faces[index]] *  
             bary.reshape((-1,3,1))).sum(axis=1).reshape((-1,4)).astype(np.uint8)
Out[17]: 
TrackedArray([[ 51, 202,   0, 254],
              [ 32, 221,   0, 255],
              [118, 135,   0, 254],
              ...,
              [  7, 246,   0, 255],
              [ 18, 235,   0, 255],
              [ 38, 215,   0, 255]], dtype=uint8)

```

**Comment by amaysaxena** [comment]
Aah, I didn't realize there was a points to barycentric method. I was going to just make a copy of the sampling function and do the barycentric interpolation in there. Although that might be more efficient since you would only compute the barycentric co-ordinates once rather than sampling and then recomputing the co-ordinates later.

**Comment by mikedh** [comment]
Haha yeah, it would definitely be more efficient to convert the random vectors used inside `sample` to barycentric than fully recalculating them like the above example.

**Comment by mikedh** [comment]
Closing for now-  though if you end up adding custom attribute loading to the PLY loader (maybe loaded in to `mesh.metadata`) a PR would be great!

**Comment by cy94** [comment]
@amaysaxena I'm trying to load the ground truth PLY files from ScanNet which have the 'label' properties, similar to your case. Did you find a solution using trimesh for this?

**Comment by cy94** [comment]
Found a solution with the trimesh API
```
from trimesh.exchange.ply import parse_header, ply_binary

with open(file_path, 'rb') as f:
    elements, is_ascii, image_name = parse_header(f)
    ply_binary(elements, f)
vertex_labels = elements['vertex']['data']['label']
```

**Comment by Drvanon** [comment]
I have a lot of data per vertex that I get from a ply file. Right now I am just handling that using the metadata, but that feels very ugly. Is there a "trimesh native" way to handle this type of data? Particularly because I would like to call `mesh.process()` on the mesh containing the data, but I have no way of telling what is going to happen to the vertices (other than copying your exact code and applying it to the vertex data, but that feels wrong), so I can not apply that to the data.
