### ISSUE TITLE
wrong uv values

### ISSUE THREAD

**Issue by l1346792580123** [mikedh/trimesh#2307]
Hi, Thanks for your great work! When I load this [mesh](https://drive.google.com/file/d/1cTHsUkMDNzknqWc7iq8cBPv_znOy11Zz/view?usp=sharing), I found there are some problems with the uv values.

![image](https://github.com/user-attachments/assets/da975105-f6cb-48a1-a177-e1ed08eefb38)

Many verties have the same uv values. When I open the obj in txt format, it looks like this
![image](https://github.com/user-attachments/assets/480c72b7-caaf-4a49-acac-25f2481e1c89)

The mesh is wrapped by blender smart project. Is it a bug?

**Comment by Kiord** [comment]
`<trimesh.Trimesh(vertices.shape=(4425304, 3), faces.shape=(1477200, 3), name="001.obj")>`
Your mesh is very dense, so slight variations in neighboring UV coordinates are completely normal.

**Comment by l1346792580123** [comment]
If there are slight variations in neighboring uv coordinates, the slight variations should not cause the neighboring uv coordinates to become the same. I remesh the obj and the uv coordinates become normal now.
