### ISSUE TITLE
How to get index of merged vertex when loading an obj

### ISSUE THREAD

**Issue by czpcf** [mikedh/trimesh#2329]
According to issue [2078](https://github.com/mikedh/trimesh/issues/2078), vertices may be merged if `process` is set True. Is it possible to get indices of merged vertices in the original obj file when loading it? Thank you in advance.

**Comment by Kiord** [comment]
The function `trimesh.grouping.merge_vertices` is responsible for the merging of close vertices, based on `trimesh.constants.tol.merge`.
The variable `mask` used at the end should be what you describe.

https://github.com/mikedh/trimesh/blob/2fcb2b2ea8085d253e692ecd4f71b8f450890d51/trimesh/grouping.py#L24-L110

**Comment by czpcf** [comment]
> The function `trimesh.grouping.merge_vertices` is responsible for the merging of close vertices, based on `trimesh.constants.tol.merge`. The variable `mask` used at the end should be what you describe.
> 
> https://github.com/mikedh/trimesh/blob/2fcb2b2ea8085d253e692ecd4f71b8f450890d51/trimesh/grouping.py#L24-L110

That's what I'm looking for, thank you for your response!
