### ISSUE TITLE
Thickness of part with color bar

### ISSUE THREAD

**Issue by AtinAngrish** [mikedh/trimesh#233]
Hi Mike,

Thanks for the amazing library! This is a lifesaver for people like me who are completely reliant on python. 

Just wanted to know if you could suggest a simple way to get a heat map of thicknesses overlayed on the mesh? Basically I want to color the triangles which lie in some threshold of thicknesses. Do you think I will be able to use the ray object used in the proximity.py file to get the triangle indices which I could color based on the distance histogram?

Thanks.

**Comment by mikedh** [comment]
Glad it's helpful! I think there are some methods in `trimesh.proximity` that might be helpful. Here's an example of setting colors based on maximum tangent sphere thickness:

```
    import trimesh

    # create a box with noise                                       
    m = trimesh.creation.box([10,2,1]).permutate.noise(.4)

    # will be triangle soup, not nice watertight mesh               
    # but will ensure no edge is longer than some                   
    # fraction of the overall mesh size                             
    sub = trimesh.Trimesh(*trimesh.remesh.subdivide_to_size(
        vertices=m.vertices,
        faces=m.faces,
        max_edge=m.scale / 5))

    # center of each subdivided face offset inwards                 
    points = sub.triangles_center + (sub.face_normals * -1e-4)

    # use the original mesh for thickness as it is well constructed
    thick = trimesh.proximity.thickness(mesh=m,
					points=points)

    # create RGBA colors for each subdivided face               
    # this was just added so you may need to update trimesh when build finishes    
    sub.visual.face_colors = trimesh.visual.interpolate(thick)

```

**Comment by AtinAngrish** [comment]
@mikedh  apologies for the late reply. I was just trying to run your code and it gave me an error regarding absense of some functions for visual.py. Can you tell me how to update the trimesh library? can I just use pip install trimesh to reinstall the updated visual.py or do I replace the visual.py file manually?
Thanks.

**Comment by mikedh** [comment]
No worries, that function was recently added. If you do a ‘pip install —upgrade trimesh’ it should work.

**Comment by mikedh** [comment]
Closing for now, though feel free to re-open if it still doesn't work after an upgrade!

**Comment by AtinAngrish** [comment]
It worked! Sorry for the late reply. I had completely forgotten to check back on this. Thanks!

**Comment by Parth527** [comment]
Hi,
Proximity thickness gives attribute error regarding facenormals. I am using numpy stl to read the stl file.

Thank you in advance
