### ISSUE TITLE
trimesh.load() is trying to load a binary stl file as an ascii stl file

### ISSUE THREAD

**Issue by amirs71** [mikedh/trimesh#236]
Hello,
I am trying to load a binary stl file but,

mesh = trimesh.load('L:\\Thesis\\3d structure\\raw data\\Mehr 2\\C720-c-stack\\untitled.stl')
 
  File "E:\Anaconda\lib\site-packages\trimesh\io\stl.py", line 154, in load_stl_ascii
    text = text.decode('utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 1: invalid start byte
what is the problem?
I should say that it seems like this error only happens for largeer files
Meshes are created by the bonej plugin of imagej
Thanks.

**Comment by mikedh** [comment]
Hey, it's probably failing the header length check (i.e. the length of the file listed in the header is different than the actual length of the file) and then falling back to ASCII, which then also fails haha. Would you mind sending me the file ([mikedh@kerfed.com](mailto:mikedh@kerfed.com)), I'll see if I can come up with a more graceful recovery.

Thanks for the report!

**Comment by amirs71** [comment]
Oh boy do I feel stupid!!!
Larger files take exponentially longer times to be saved and I did not take that into account. I habitually close fiji instantly after saving a file which is why files couldn’t be saved properly hence the difference between the size in header and the actual size.
That’s what happens when you burn your candle at both ends.
Thank you @mikedh for the swift response.
