### ISSUE TITLE
Vertex and face order not preserved by Wavefront loader

### ISSUE THREAD

**Issue by mmatl** [mikedh/trimesh#238]
Basically, the wavefront loader seems to argsort the vertices for some reason. I wasn't sure why slash what the desired behavior is, but it does make it a bit tough to rely on using md5's to compare meshes after saving them to disk.

Here's a minimal example of the problem:

```python
import trimesh
import numpy as np

x = trimesh.creation.icosahedron()
x.export('./ico.obj')
y = trimesh.load_mesh('./ico.obj')

assert np.allclose(x.vertices, y.vertices)
```

https://github.com/mikedh/trimesh/blob/4e12d6abdf8aa4e893e9d029f3194b4ffe5a1735/trimesh/io/wavefront.py#L52

**Comment by mikedh** [comment]
Oh yeah, this looks related to the remapping in the "weird implicit face mode" of wavefront files. I was also trying to preserve order through sorting, but was sorting as strings not integers. Fix which hopefully passes CI in https://github.com/mikedh/trimesh/commit/e64fc9dc65923ef298efe9c9e9d68862421cd715

Thanks for the report and reproducible example!

**Comment by mmatl** [comment]
Woah, incredibly fast response! Thanks :) Feel free to close this issue whenever you're ready.
