### ISSUE TITLE
Help on dealing with Qhull error

### ISSUE THREAD

**Issue by lorinma** [mikedh/trimesh#24]
Hello, 

I got Qhull errors when I tried to generate the obb of the following meshes, do you have any suggestions?

Thanks in advance!

Vertices: [[19653.465921167503, 2901.982866568411, 22790.418736883457], [20611.665944905126, 2901.9828184502676, 22794.41878902774], [20612.93810257011, 2896.147085313453, 22489.677315260826], [19654.738078832495, 2896.1471334316, 22485.67726311654], [22372.26582808047, 6.382596408072594, 22857.21861265048], [22373.537985745457, 0.5468632712579691, 22552.47713888356], [21414.065752396516, 6.382729955398236, 22853.218558653392], [21415.337910061502, 0.5469968185836116, 22548.477084886475]]
Faces: [[2, 3, 1], [3, 0, 1], [1, 4, 5], [2, 1, 5], [7, 5, 6], [5, 4, 6], [6, 0, 7], [0, 3, 7], [3, 2, 7], [7, 2, 5], [6, 4, 1], [0, 6, 1]]
________
Vertices: [[18695.265921167505, 2901.982866568411, 22786.418736883457], [19653.46594490513, 2901.9828184502676, 22790.41878902774], [19654.738102570114, 2896.147085313453, 22485.677315260826], [18696.538078832495, 2896.1471334316, 22481.67726311654], [21414.065828080475, 6.382596408072594, 22853.21861265048], [21415.33798574546, 0.5468632712579691, 22548.47713888356], [20455.86575239652, 6.382729955398236, 22849.218558653396], [20457.137910061505, 0.5469968185836116, 22544.477084886475]]
Faces: [[2, 3, 1], [3, 0, 1], [1, 4, 5], [2, 1, 5], [7, 5, 6], [5, 4, 6], [6, 0, 7], [0, 3, 7], [3, 2, 7], [7, 2, 5], [6, 4, 1], [0, 6, 1]]
________
Vertices: [[17736.23126780341, 2901.4753593419673, 22780.023931916312], [18694.431251570077, 2901.475351664289, 22786.423959681106], [18696.466715963248, 2896.1036329803596, 22481.67809584849], [17738.266732196586, 2896.103640658043, 22475.278068083695], [20455.03128455919, 5.875370265509883, 22849.223785602746], [20457.066748952362, 0.503651581581277, 22544.477921770136]]
Faces: [[3, 1, 2], [0, 1, 3], [1, 4, 2], [4, 5, 2], [3, 4, 0], [3, 5, 4], [3, 2, 5], [0, 4, 1]]
________
Vertices: [[17736.50949556136, 2901.736576776612, 22780.02057682472], [20455.30942843662, 6.136314895439643, 22849.220251703195], [20457.0904373139, 0.525761342222264, 22544.477098053758], [17738.290504438646, 2896.1260232233985, 22475.27742317528], [19497.109334775803, 6.136461474350874, 22843.620245025544], [19498.890343653078, 0.5259079211334949, 22538.877091376104]]
Faces: [[0, 1, 3], [1, 2, 3], [1, 4, 5], [1, 5, 2], [3, 4, 0], [3, 5, 4], [5, 3, 2], [4, 1, 0]]

**Comment by mikedh** [comment]
Looks like this was precision issues in qhull because of the large meshes. Adding the 'QbB' option to qhull has it scale to a unit cube for the convex hull then scale the result back, which resolved at least one of your test cases. The precision tradeoffs of doing that are discussed in http://www.qhull.org/html/qh-impre.htm but it seems like an OK compromise. An alternative solution would be to try to get the convex hull without the scaling option, then on failure add it in. 

Anyway, I added the QbB option in https://github.com/mikedh/trimesh/commit/42c0c9ba1cd1e94c19a564b7b7b207d09fc8d6ee

Thanks for the report!


The full qhull error:
```
ConvexHull(m.vertices)
qhull precision warning:
The initial hull is narrow (cosine of min. angle is 1.0000000000000004).
Is the input lower dimensional (e.g., on a plane in 3-d)?  Qhull may
produce a wide facet.  Options 'QbB' (scale to unit box) or 'Qbb' (scale
last coordinate) may remove this warning.  Use 'Pp' to skip this warning.
See 'Limitations' in qh-impre.htm.
QH6114 qhull precision error: initial simplex is not convex. Distance=-9.1e-12

While executing:  | qhull i Qt
Options selected for Qhull 2012.1 2012/02/18:
  run-id 222140417  incidence  Qtriangulate  _pre-merge  _zero-centrum
  _max-width 2.9e+03  Error-roundoff 3.2e-11  _one-merge 2.2e-10
  _near-inside 1.1e-09  Visible-distance 6.3e-11  U-coplanar-distance 6.3e-11
  Width-outside 1.3e-10  _wide-facet 3.8e-10  _narrow-hull -4.4e-16

precision problems (corrected unless 'Q0' or an error)
      1 flipped facets

The input to qhull appears to be less than 3 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p0(v3): 2e+04 2.9e+03 2.2e+04
- p1(v2): 2.2e+04   6.4 2.3e+04
- p6(v1): 2.2e+04  0.55 2.3e+04
- p4(v0): 2e+04 2.9e+03 2.3e+04

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 3.2e-11.  The center point, facets and distances
to the center point are as follows:

center point 2.101e+04     1451 2.267e+04

facet p1 p6 p4 distance= -2.2e-12
facet p0 p6 p4 distance= -2.6e-12
facet p0 p1 p4 distance= -1.3e-12
facet p0 p1 p6 distance= -1.6e-12

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:  1.965e+04  2.237e+04  difference= 2720
  1:    0.5469      2902  difference= 2901
  2:  2.249e+04  2.286e+04  difference= 371.5

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 3.2e-11.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.
---------------------------------------------------------------------------
QhullError                                Traceback (most recent call last)
<ipython-input-5-d01eddb48409> in <module>()
----> 1 ConvexHull(m.vertices)

scipy/spatial/qhull.pyx in scipy.spatial.qhull.ConvexHull.__init__ (scipy\spatial\qhull.c:21663)()

scipy/spatial/qhull.pyx in scipy.spatial.qhull._Qhull.__init__ (scipy\spatial\qhull.c:3879)()

QhullError: Qhull error
```

**Comment by mikedh** [comment]
I added one of these models to the tests- if you see this again feel free to reopen.
