### ISSUE TITLE
trimesh proximity: ValueError: points must be (n,3)!

### ISSUE THREAD

**Issue by biga123** [mikedh/trimesh#241]
Hello,
i am very new in working with python and i don't understand how the input format for Points is supposed to be.
My aim is to use the trimesh proximity closest_point function to find the closest point of a given mesh surface to a Point P.
If i try to define the point as 
`mesh = trimesh.load('test2.stl')`
`P = [1,2,3]`
`print(trimesh.proximity.closest_point(mesh,P))`
i get an error like:
`...trimesh\proximity.py", line 123, in closest_point
    raise ValueError('points must be (n,3)!')
ValueError: points must be (n,3)!`

Could you please give me an example off how to define my point or a list of points properly?
Thank you

**Comment by mikedh** [comment]
Hey, `closest_point` needs a list of points, rather than a single point. It should work if you change it to:

```
P = [[1,2,3]] # note shape is now (1, 3)
print(trimesh.proximity.closest_point(mesh,P))
```
