### ISSUE TITLE
join/merge meshes

### ISSUE THREAD

**Issue by avlonder** [mikedh/trimesh#245]
Hi, 

I was wondering if there exists a join or merge function that does the exact opposite of split().
I have several mesh objects and for reasons of bookkeeping and efficiency, it would be better if I could merge them into one single trimesh object. 

BR, 
Arne

**Comment by mikedh** [comment]
Hey, `trimesh.util.concatenate` is probably the best way to join multiple meshes. You could also do `np.sum(meshes)` but it does a lot more work through a bunch of `__add__` calls.

```
In [1]: import trimesh

In [3]: meshes = [trimesh.creation.box() for i in range(10)]

In [4]: for i, m in enumerate(meshes): m.vertices[:,0] += i * 2.0

In [6]: combined = trimesh.util.concatenate(meshes)

In [7]: combined.volume
Out[7]: 10.0

In [8]: sum(m.volume for m in meshes)
Out[8]: 10.0

```

**Comment by mikedh** [comment]
Closing for now, though feel free to re-open if that doesn't work for you.

**Comment by martinruenz** [comment]
Similarly, I am trying to merge all meshes in a scene `trimesh.util.concatenate(trimesh.load(<path>).dump())` but run into the exception:
```
failed to combine visuals
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.6/site-packages/trimesh/util.py", line 1338, in concatenate
    visual = meshes[0].visual.concatenate(
AttributeError: 'TextureVisuals' object has no attribute 'concatenate'
```
Any idea what could go wrong here?

**Comment by mikedh** [comment]
Yeah currently textured mesh concatenation isn't supported. I think that's a warning, not an exception though? It should still return a concatenated result mesh, just without a visual:

```
In [10]: m.visual                                                    
Out[10]: <trimesh.visual.texture.TextureVisuals at 0x7fc78cac8e50>

In [11]: a.visual                                                    
Out[11]: <trimesh.visual.color.ColorVisuals at 0x7fc788250b10>

In [12]: a + m                                                       
Out[12]: <trimesh.base.Trimesh at 0x7fc77be09350>

In [13]: trimesh.util.concatenate(a, m)                              
Out[13]: <trimesh.base.Trimesh at 0x7fc7a4e8f0d0>

In [14]: trimesh.util.concatenate(m, a)                              
WARNING            util.py:1342  failed to combine visuals
Traceback (most recent call last):
  File "/media/psf/Dropbox/robotics/trimesh/trimesh/util.py", line 1338, in concatenate
    visual = meshes[0].visual.concatenate(
AttributeError: 'TextureVisuals' object has no attribute 'concatenate'
Out[14]: <trimesh.base.Trimesh at 0x7fc77bb29790>

In [15]: m + a                                                       
WARNING            util.py:1342  failed to combine visuals
Traceback (most recent call last):
  File "/media/psf/Dropbox/robotics/trimesh/trimesh/util.py", line 1338, in concatenate
    visual = meshes[0].visual.concatenate(
AttributeError: 'TextureVisuals' object has no attribute 'concatenate'
Out[15]: <trimesh.base.Trimesh at 0x7fc77beae4d0>

```

**Comment by martinruenz** [comment]
You are right! Great, that works for me, thanks a lot :-)

**Comment by 1234shel** [comment]
Is there a way to connect two meshes using specific faces?

**Comment by Guptajakala** [comment]
@mikedh Is there any plan to support merging meshes with correct texture?

**Comment by mikedh** [comment]
Hey, yeah merging meshes with correct texture is in `main` and is [decently well tested](https://github.com/mikedh/trimesh/blob/2ca2927622a43bb1db063de0cd241b7f7c726cbc/tests/test_texture.py#L150-L187) although there are probably still bugs (fixes and tests welcome!) For what it's worth this works:
```
In [1]: import trimesh

In [2]: trimesh.load('bigmodel/airplane/models/model_normalized.obj')
Out[2]: <trimesh.Scene(len(geometry)=29)>

In [3]: s = trimesh.load('bigmodel/airplane/models/model_normalized.obj')

In [4]: a = s.dump(concatenate=True)

In [5]: b = trimesh.load('bigmodel/airplane/models/model_normalized.obj', force='mesh')

```
![Screenshot from 2023-06-12 23-44-12](https://github.com/mikedh/trimesh/assets/1403074/27f954bd-9d36-494e-b802-3af55955010e)

**Comment by lioryariv** [comment]
Hi when I try to use to merging option I facing the following issue:
This is how the mesh looks when I load it using trimesh.load(mesh_path).show() [it is a trimesh.Scene object]: 
<img width="386" alt="image" src="https://github.com/mikedh/trimesh/assets/37273500/0a323622-ca89-45ef-a973-44bcdabd215e">

However, when I try to do either:
trimesh.util.concatenate(trimesh.load(mesh_path).dump()).show()
or - 
trimesh.load(mesh_path, force='mesh').show()
I get the following: 
<img width="362" alt="image" src="https://github.com/mikedh/trimesh/assets/37273500/0fc7a945-8292-4eea-864e-29ea934db584">

Any idea why is that and how can I fix this please? Thanks in advance!
