### ISSUE TITLE
test_loaded.py::LoaderTest::test_remote requires Internet connection

### ISSUE THREAD

**Issue by hroncok** [mikedh/trimesh#247]
In Fedora, we build packages without internet access for reproducibility and security.

I have skipped the `test_loaded.py::LoaderTest::test_remote` test for now, however I'd very uch like the test to work even offline.

Would you accept a PR that creates a simple fixture that serves the file in question via localhost?

**Comment by mikedh** [comment]
That would be great! I am also happy to check network connectivity and make that test optional, though the fixture would probably be cleaner.

Best,
Mike

**Comment by hroncok** [comment]
I have it working on Python 3.7, porting it to Python 2 as well now.

**Comment by hroncok** [comment]
Ready for review in https://github.com/mikedh/trimesh/pull/248

**Comment by hroncok** [comment]
Thanks for the swift communication.
