### ISSUE TITLE
Generating zigzag toolpath within sections for G-code conversion

### ISSUE THREAD

**Issue by liushuya7** [mikedh/trimesh#251]
I read [https://trimsh.org/examples/section.html](url), and I was able to generate section view on a part.
Is there an easy way to fill in a section with zigzag toolpath so that it can be converted into G-code to run on a cnc machine or a 3D printer? 
![Toolpath](https://upload.wikimedia.org/wikipedia/commons/d/d9/Zig-zag_tool_path.jpg)

**Comment by mikedh** [comment]
Hey, there's nothing baked in to trimesh to do this, but you can do some of this pretty easily. The linking of the segments is not so easy, though some combination of scipy.spatial.cKDTree and graph traversals, or possibly using `polygon.project`/`polygon.interpolate` (making link segments out of 
geometry ensures they aren't obviously in collision) is pretty doable. 

Here's a [blog post](https://www.freesteel.co.uk/wpblog/2006/06/24/the-structure-of-a-cam-system/) from somone in the industry on this. Also I haven't checked in to the state of them lately but the following packages might be helpful for pocketing tool paths: pyactp, libarea, [openvoroni](http://www.anderswallin.net/cam/) opencamlib

Here's a quick example which solves the easiest part of the problem with just geometry operations 😁 

![zig](https://user-images.githubusercontent.com/1403074/48368615-3e4a6500-e682-11e8-8d36-9622328c5a4e.png)


```
import numpy as np

import trimesh

from shapely.geometry import LineString
from shapely.ops import linemerge


if __name__ == '__main__':
    ### Loading and parameters
    # load a 2D drawing with a asingle closed region
    path = trimesh.load('models/2D/wrench.dxf')

    # what is the radius of the tool
    tool_radius = (1.0 / 32.0)
    # how far should each cutting pass step over the next
    tool_step = tool_radius / 1.5


    ### Finding the intersecting axis aligned line segments
    
    # a single shapely.geometry.Polygon object
    # has correct interiors
    original = path.polygons_full[0]
    # offset tool from geometry
    polygon = original.buffer(-tool_radius)
    # get polygon bounds as [[min], [max]]
    bounds = np.reshape(polygon.bounds, (2, 2))
    # stack lines inside the bounding box of the polygon
    x_values = np.arange(*bounds[:,0], step=tool_step)
    y_values = np.ones((len(x_values), 2)) * bounds[:,1]
    # line segments as an (n, 2, 2) numpy array
    lines = np.column_stack((x_values,
                             y_values[:,0],
                             x_values,
                             y_values[:,1])).reshape((-1, 2, 2))
    # line segments as a shapely.geometry.MultiLineString
    multiline = linemerge(lines)
    # get parts of the lines that are inside the Polygon
    overlap = polygon.intersection(multiline)
    # turn shapely objects back into (n, 2, 2) segments
    over = np.array([np.array(i)[[0,-1]]
                     for i in overlap
                     if isinstance(i, LineString)])
    # flatten in to single points
    over_flat = over.reshape((-1, 2))
    # index to reconstruct segments
    over_idx = np.arange(len(over_flat)).reshape((-1,2))

    ### Linking Segments
    # Now the hardest part: linking segments into the smallest
    # number of connected tool paths that don't interfere

    # show the unlinked segments
    trimesh.load_path(over).plot_entities(show=False)
    path.show()
    
```

**Comment by liushuya7** [comment]
Thank you so much for your detailed explanation and the demo code. Wish more toolpath functions can be added into Trimesh in the future to make a powerful open-source CAD/CAM system out of it. That would be really thrilling.

**Comment by mikedh** [comment]
No worries! I actually have a bunch of pretty ugly old code doing stuff like this, I lightly cleaned it and put it up as a new project here: https://github.com/mikedh/pypocketing . The contour- parallel stuff always seemed the most reliable method. 

If it ever reaches the "late beta" quality level I think trimesh mostly meets and doesn't add  dependencies, we might be able to eventually add it as `trimesh.path.pocketing` or something.

**Comment by liushuya7** [comment]
That's awesome! Thanks, look forward for it appearing in **trimesh**! (My programming is kind limited, wish I could also contribute)
Another question: is there a way to generate 3D path on a part and store in `trimesh.path.Path3D`? (for instance, parallel / scallop finishing)
![parallelfinishing](https://user-images.githubusercontent.com/6867028/48495061-3236e280-e7fd-11e8-84f4-dc75d6f61cdb.png)![scallopfinishing](https://user-images.githubusercontent.com/6867028/48495521-2ac40900-e7fe-11e8-91bb-f213980bf5a8.png)

**Comment by mikedh** [comment]
Hey, for those patterns you could do them with some combination of region splitting (`mesh.smoothed`), cross sections (`mesh.section`), and ray tests (i.e. generate a pattern in 2D then project it onto the surface via rays). I'm going to close this for now, but feel free to reopen in `pypocketing`. Thanks for the report!
