### ISSUE TITLE
Are there some idioms to use camera intrinsic parameter to get rendered image?

### ISSUE THREAD

**Issue by wkentaro** [mikedh/trimesh#253]
I'd like to use intrinsic parameter `K` to get rendered image. Does anyone have some idiom to do this?

**Comment by mikedh** [comment]
Hey, I think this would require some wangling of ‘gl_init’ in viewer, this article looks pretty good: http://ksimek.github.io/2013/06/03/calibrated_cameras_in_opengl/

If you wanted to add it cleanly to ‘trimesh’ It would be pretty cool to have ‘Camera’ objects which pass their intrinsic matrix to the pyglet code in ‘scene.viewer’. 

Oh it’s also possible https://github.com/BerkeleyAutomation/meshrender does this or has something you could use as a starting point.

**Comment by wkentaro** [comment]
Thank you for the nice feedback.
I sent PR here https://github.com/mikedh/trimesh/pull/254, which supports fx, fy to get correct fov but does not support cx, cy and skew.

**Comment by wkentaro** [comment]
Closed via #254
