### ISSUE TITLE
NameError: name 'load_path' is not defined

### ISSUE THREAD

**Issue by yw5aj** [mikedh/trimesh#26]
Update 2016-08-16:

Hmm... I tried Python 2.7 but the problem remains.

--

Hi Michael,

First of all - thank you for the excellent package!

I think that it is because I am using Python 3.5 (Anaconda Python 3.5 64 bit in 64 bit Windows 10), I have this error (potentially due to the relative import mechanism).

When I do the following code snippet:

```python
import numpy as np
import trimesh

if __name__ == '__main__':
    mesh = trimesh.load_mesh(test.stl')
    section = mesh.section(plane_origin=[0, 0, 0],
                           plane_normal=[0, 0, 1])
```

I see the following error info:

```python
runfile('C:/ProjectFolder/MaterialFEA/geometry/Export/test.py', wdir='C:/ProjectFolder/MaterialFEA/geometry/Export')
Traceback (most recent call last):

  File "<ipython-input-14-a216ee98491b>", line 1, in <module>
    runfile('C:/ProjectFolder/MaterialFEA/geometry/Export/test.py', wdir='C:/ProjectFolder/MaterialFEA/geometry/Export')

  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/ProjectFolder/MaterialFEA/geometry/Export/test.py", line 15, in <module>
    plane_normal=[0, 0, 1])

  File "C:\Anaconda3\lib\site-packages\trimesh\base.py", line 945, in section
    path = load_path(lines)

NameError: name 'load_path' is not defined
```

Do you think it is the python 2 vs 3 compatibility issue due to the relative imports? Any ideas on whether there is a quick fix available?

Thank you!

Shawn

PS: The stl file is just a simple cube for testing and I don't think that is the issue.

**Comment by yw5aj** [comment]
Solved!

After half an hour of debugging, I realized that I should install `shapely` and `rtree`. Then the code snippet above ran smoothly.

Michael - do you think that we should add `shapely` and `rtree` to the dependencies? Or, when they are missing, prompt an error message that says we need `shapely` and `rtree`?

Shawn

**Comment by mikedh** [comment]
Glad its useful! Actually these are in setup.py as an extra, so if you do (as per readme)
`pip install trimesh[all]

You will get rtree and shapely. I think the main issue here is the crappy error message, I'll move  the import into the function (so it complains about shapely and rtree immediately).

**Comment by mikedh** [comment]
Better error message in https://github.com/mikedh/trimesh/commit/1517907d943085e5ce095f793b07b48a6d1ff3ce

**Comment by yw5aj** [comment]
Oh I see - I didn't use the [all] option. That's why... Thanks for answering!

**Comment by yw5aj** [comment]
Just in case it helps...

In Windows, simply doing `pip install trimesh[all]` will show `Failed building wheel for XXX` because it's typical Python + Windows combination :(

Therefore, I guess most people actually use `conda`, and then has to know the list of packages so they can install manually. :)
