### ISSUE TITLE
tolerenca strip around triangles

### ISSUE THREAD

**Issue by avlonder** [mikedh/trimesh#263]
Hello again, 

I would like to have some kind of tolerance strip around the triangles for the ray casting. 
Is this already present in trimesh / pyembree / embree?
It doesn't seem to be the case because some rays that should hit an edge of a simple cube are not hitting it. 

I looked into ray_pyembree.py. 
Maybe _ray_offset_factor does the trick? 

BR, 
Arne

**Comment by mikedh** [comment]
Hey, yeah unfortunately our logic to collect every hit using embree is a bit cheesy (more info on why it is required in https://github.com/embree/embree/issues/188). Trimesh's native raytracer is a LOT slower (50x or so) but does collect every hit robustly as far as I've seen. If you load meshes with `use_embree=False` it will use the native one:

```
In [1]: import trimesh

In [2]: m = trimesh.load('trimesh/models/featuretype.STL')

In [3]: b = trimesh.load('trimesh/models/featuretype.STL', use_embree=False)

In [4]: m.ray
Out[4]: <trimesh.ray.ray_pyembree.RayMeshIntersector at 0x7f4bba344eb8>

In [5]: b.ray
Out[5]: <trimesh.ray.ray_triangle.RayMeshIntersector at 0x7f4b96449438>
```

**Comment by mikedh** [comment]
This is actually the same problem seen as https://github.com/mikedh/trimesh/issues/242. Consolidating to that issue for now, thanks for the report!
