### ISSUE TITLE
Bug with concave meshes

### ISSUE THREAD

**Issue by cedricjeanty** [mikedh/trimesh#269]
I was building out a unit test for some code using trimesh, when I encountered some strange behavior. I am loading a unit cube with a notch taken out of the origin corner like so:

![image](https://user-images.githubusercontent.com/6004495/49691986-9c445e00-fb03-11e8-89ec-f7b4cc560227.png)

The file is:
[Unit Cube w Notch.STL.zip](https://github.com/mikedh/trimesh/files/2660143/Unit.Cube.w.Notch.STL.zip)

The origin is the bottom left "corner" which is missing. When I do mesh.contains([[0.1,0.1,0.1]]) I get True, which is not expected, as this point is in the "notched" part of the cube. I get similarly incorrect results for signed_distance.

Am I misunderstanding something, or is this a bug with concave meshes?
Thanks!

**Comment by cedricjeanty** [comment]
My mistake, the coordinate system of the STL got changed during the save. This is not a bug.

**Comment by mikedh** [comment]
No worries, glad you figured it out! There is a rather [unfortunate bug](https://github.com/mikedh/trimesh/issues/242) with contains tests and pyembree, but if you have well constructed meshes it shouldn't be a problem.
