### ISSUE TITLE
Question - would the solid name be available after loading an STL file?

### ISSUE THREAD

**Issue by yw5aj** [mikedh/trimesh#27]
Hi Michael,

Quick question - would the solid name be stored somewhere after the STL file got loaded?

Thanks!

Shawn

**Comment by mikedh** [comment]
Yeah, np I already do this in tests and it is pretty useful. I'll add it to the metadata when I get a chance, so it will be:

mesh.metadata['file_name']

**Comment by yw5aj** [comment]
Sweet - thank you so much Michael! I really look forward to it.

Shawn

**Comment by mikedh** [comment]
np, available in https://github.com/mikedh/trimesh/commit/0e0cd58011c74e1695a8484474ba3736623cb746
