### ISSUE TITLE
What are the directions of XYZ in camera frame and world frame ?

### ISSUE THREAD

**Issue by zy871125746** [mikedh/trimesh#270]
I have got some unexpect result from scene.save_image and I think it might cause by different directions of frames. Can you tell me what are the directions of XYZ in the camera frame and the world frame ?

**Comment by mikedh** [comment]
Not sure exactly, but have you tried rotating 180 degrees around X or Y to see if Z is backwards? What happens if you call `mesh.show`?

**Comment by zy871125746** [comment]
Thank you for you advice,I have achieve my expected result by rotate 180 degree along x axis. And here is another little problem, I passed a camera with camera.transform from camera frame to world frame to scene.set_camera(camera=camera), should it be a transfrom from camera frame to world frame ?https://github.com/mikedh/trimesh/blob/283df23feea3a6de50e804a8bd303f28f17ddb2f/trimesh/scene/camera.py#L96
I also would like to know is there any function can change the color of backgroud of scene?

**Comment by mikedh** [comment]
Glad you figured it out, I'm not sure about the transforms- I'd have to check both ways haha. 

With regards to background color, when [`texture`](https://github.com/mikedh/trimesh/tree/texture) is merged in a few weeks, you'll be able to run: `mesh.show(background=[255,0,0,255])`

**Comment by zy871125746** [comment]
That will be great. Will the scene.save_image() have the same background paramater ? I would like to output the result to an image.

**Comment by mikedh** [comment]
Yeah save_image passes kwargs to the viewer so it should pass through. Thanks for the report! Closing for now but feel free to reopen.
