### ISSUE TITLE
access points inside pointcloud - error no module rtree

### ISSUE THREAD

**Issue by chrysmun** [mikedh/trimesh#271]
hey! [updated]

great library! i'm trying to combine meshes and pointclouds and ran into this issue:
how do i use the pts of a pointcloud in a query to a mesh operation, e.g. signed distance?

pts = trimesh.load('pointcloud.ply')
mesh = trimesh.load('mesh.ply')

mesh.nearest.signed_distance(pts.points)
AttributeError("'PointCloud' object has no attribute 'points'",)

mesh.nearest.signed_distance(pts.vertices)
ModuleNotFoundError("No module named 'rtree'",)

so i found the other issue related to the rtree, and after

apt install libspatialindex-dev
pip install rtree

the status log simply changes to:
mesh.nearest.signed_distance(pts.vertices)
"not available"

cheers
hayko

ps: using latest repository update and viewing mesh+pts works fine.

**Comment by mikedh** [comment]
Hey, `PointCloud` objects have `pts.vertices`, not `pts.points`. 

Also you probably need to install rtree: try `pip install trimesh[easy]` should get it, though you'll probably also need to install libspatialindex (on ubuntu 16.04 `sudo apt-get install libgeos-dev libspatialindex-c4v5`). The conda install would get them automatically.

**Comment by mikedh** [comment]
Closing for now, though feel free to reopen. Thanks for the report!
