### ISSUE TITLE
Cork Boolean Ops

### ISSUE THREAD

**Issue by mrlukeparry** [mikedh/trimesh#274]
Hi Mike,

I have been having troubles with the boolean ops with Trimesh (2.35.47) using Blender 2.79 Windows - which does not appear to be reliable on meshes I am using. Also OpenSCAD fails to launch on windows with a process error. 

There are really a limited number options which I can understand for boolean ops.  For now, I am having to resort to the Cork Library, which seems reasonable quick compromise for prototyping ideas with trimesh e.g. for reference see below.

```
    myPart.geometry.export('a.off')
    myPartB.export('b.off')
    subprocess.call('wincork.exe -isct a.off b.off c.off')
    myPartC  = trimesh.load_mesh('c.off')
```

**Comment by mikedh** [comment]
Hey, yeah the Blender booleans are quite unreliable, but extremely fast. I've had very mixed reliability out of cork in testing too.

OpenSCAD is definitely the most robust option by a long shot, I think it'd probably be worth a little time messing with your install if you can (uninstall and reinstall? maybe use a portable EXE?).

**Comment by mikedh** [comment]
Closing for now, though feel free to reopen. Thanks for the report!
