### ISSUE TITLE
Do you have an example for mesh.submesh?

### ISSUE THREAD

**Issue by zy871125746** [mikedh/trimesh#278]
I got some triangle_id from :
`closest_points,distances,triangle_id = mesh.nearest.on_surface(pc.vertices)`. 

And I would like to extract a submesh from mesh using :+1: 
`sub_mesh = mesh.submesh(triangle_id)` but got an error on: https://github.com/mikedh/trimesh/blob/0f30d5d8cff35c593d0f772be2b95e4f533b8dbd/trimesh/util.py#L127 
Is it the right function for my purpose or Is it the right way to use submesh function?

**Comment by zy871125746** [comment]
Hello, I have tried `sub_mesh = mesh.submesh([triangle_id])` and get an error like this:
  `File "/media/joey/Office/AI/github/trimesh/trimesh/visual.py", line 171, in face_colors
    colors = to_rgba(values)
  File "/media/joey/Office/AI/github/trimesh/trimesh/visual.py", line 515, in to_rgba
    raise ValueError('Colors not of appropriate shape!')
ValueError: Colors not of appropriate shape!`
I check the code then I guess this may because the color format of the original mesh is already rgba. So it raises the ValueError. What should I do?

**Comment by zy871125746** [comment]
Hello, I think that the submesh function may have a small bug. After I digged into the code, I found the line 1331 will turn the `result` into numpy array, not a trimesh object. https://github.com/mikedh/trimesh/blob/0f30d5d8cff35c593d0f772be2b95e4f533b8dbd/trimesh/util.py#L1331

**Comment by mikedh** [comment]
Hey, according to the docstring `mesh.submesh` is supposed to return a list of Trimesh objects the same length as `faces_sequence`, unless `append=True` in which case it returns a single mesh:

```
    """                                                             
    Return a subset of a mesh.                                      
                                                                    
    Parameters                                                      
    ----------                                                      
    mesh : Trimesh                                                  
       Source mesh to take geometry from                            
    faces_sequence : sequence (p,) int                              
        Indexes of mesh.faces                                       
    only_watertight : bool                                          
        Only return submeshes which are watertight.                 
    append : bool                                                   
        Return a single mesh which has the faces appended,          
        if this flag is set, only_watertight is ignored             
                                                                    
    Returns                                                         
    ---------                                                       
    if append : Trimesh object                                      
    else        list of Trimesh objects                             
    """

```

**Comment by zy871125746** [comment]
Yeah docstring does so. But I think that `result = np.array(result)` will make `result` into a numpy array and the final return of submesh function is now a list of numpy array, not a list of trimesh objects 
https://github.com/mikedh/trimesh/blob/0f30d5d8cff35c593d0f772be2b95e4f533b8dbd/trimesh/util.py#L1331-L1340

**Comment by mikedh** [comment]
No worries- glad it's working!
