### ISSUE TITLE
Extrude a Path2D?

### ISSUE THREAD

**Issue by yw5aj** [mikedh/trimesh#28]
Hi Mike,

Thanks again for the excellent package :)

I was trying to extrude a 2D path today, so I did `extruded = section2d.extrude(height=1)`, which returned 2 primitives. However, when I tried to export the primitives using `extruded[0].export('test.stl')`, an error shows up saying `ValueError: extrude polygon not specified!`. The complete code is below:

```python
type(section2d)
Out[13]: trimesh.path.path.Path2D

extruded = section2d.extrude(height=1)

extruded[0].export('test.stl')
Traceback (most recent call last):

  File "<ipython-input-15-4ddd38bd4376>", line 1, in <module>
    extruded[0].export('test.stl')

  File "C:\Anaconda3\lib\site-packages\trimesh\base.py", line 1244, in export
    file_type = file_type)

  File "C:\Anaconda3\lib\site-packages\trimesh\io\export.py", line 31, in export_mesh
    log.info('Exporting %d faces as %s', len(mesh.faces), file_type.upper())

  File "C:\Anaconda3\lib\site-packages\trimesh\primitives.py", line 26, in faces
    self._create_mesh()

  File "C:\Anaconda3\lib\site-packages\trimesh\primitives.py", line 268, in _create_mesh
    mesh = creation.extrude_polygon(self.extrude_polygon,

  File "C:\Anaconda3\lib\site-packages\trimesh\primitives.py", line 244, in extrude_polygon
    raise ValueError('extrude polygon not specified!')

ValueError: extrude polygon not specified!
```

I do have `meshpy` installed. Any thoughts?

Thanks!

Shawn

PS: My end goal is to output a Path2D into an STL file with a single surface, so I was thinking about extrude with `height=0`. I'd really appreciate it if you think there is a less a hack-ish way as well!

**Comment by mikedh** [comment]
Ah, yeah this may have been a bug that got fixed in the primitive API change, try doing a `pip --upgrade trimesh` and see if that fixes it.

As for the single surface option you can use `creation.triangulate_polygon`:

```
In [1]: w = trimesh.load('models/2D/wrench.dxf')

In [2]: w.polygons_full
Out[2]: [<shapely.geometry.polygon.Polygon at 0x7f3cd873a790>]

In [3]: vertices, faces = trimesh.creation.triangulate_polygon(w.polygons_full[0])

In [4]: vertices.shape
Out[4]: (204, 2)

In [5]: vertices = np.column_stack((vertices, np.zeros(len(vertices))))

In [6]: surface = trimesh.Trimesh(vertices=vertices, faces=faces)
DEBUG              util.py:513   is_empty was not in cache, executed in 0.000056
DEBUG              base.py:255   Generating face normals as shape was incorrect
DEBUG              util.py:513   triangles was not in cache, executed in 0.000116

In [7]: surface.area
DEBUG              util.py:513   triangles was not in cache, executed in 0.000296
DEBUG              util.py:513   area_faces was not in cache, executed in 0.000947
DEBUG              util.py:513   area was not in cache, executed in 0.001358
Out[7]: 1.666888851744794

In [8]: w.area
Out[8]: 1.6668888517447926

```

Best,
Mike

**Comment by yw5aj** [comment]
Dear Mike,

Thank you so much! It worked like a charm. :)

Potential pitfalls for others who may see this:

If you are using Windows, it may be hard to find a working copy of `meshpy`. I used the version compiled by Christopher Gholke (there're no `conda` packages yet), and I had to downgrade from Python 3.5 to Python 3.4 to get it working.

Shawn
