### ISSUE TITLE
trimesh.Scene.save_image does show a window shortly

### ISSUE THREAD

**Issue by wkentaro** [mikedh/trimesh#287]
Do anyone have idea how to fix this?

**Comment by bolofili** [comment]
How can I reproduce that?

**Comment by wkentaro** [comment]
With `python examples/offscreen_render.py`. There is an option `visible=True/False`, which should control the window visibleness, however, `visible=False` usually creates black image like this issue: https://github.com/mikedh/trimesh/issues/115.

**Comment by bolofili** [comment]
Runnig the example I get this error. Do you know how to fix it?

`unable to save image No module named 'trimesh.scene.viewer'`

**Comment by mikedh** [comment]
Hey, yeah if you pass `visible=False` it will show the window briefly which avoids some of the platform specific problems getting an OpenGL context to render things. @wkentaro just fixed the reference to viewer in `scene.save_image` (from things getting moved around in #281) and it should finish the build/release in 20 minutes or so.

Thanks for the report/PR!

**Comment by wkentaro** [comment]
@mikedh Thanks. So that means it is difficult to pass `visible=False` in some platforms to get correct output? I'm using ubuntu 16.04, and if I pass `visible=False`, I get black image.

**Comment by mikedh** [comment]
Yeah, certain platforms don't render things into non- visible windows. I'm not sure exactly where it comes from (X11, hardware driver, pyglet, etc).

**Comment by wkentaro** [comment]
Ok, I see. Thanks!

**Comment by mikedh** [comment]
Note that it DOES work in Docker containers, if you are OK with CPU rendering. The [LLVMpipe rasterizer](https://www.phoronix.com/scan.php?page=article&item=llvmpipe-swr-xeon&num=1) is actually surprisingly fast, and you can use it in cheapo cloud instances.

To use you just need to run your script with supervisor + XVFB as well. An example Dockerfile:

```
FROM mikedh/trimesh:latest

# create a simple supervisor file which has your script in it
COPY myapp.supervisor.conf /etc/supervisor/conf.d/

# we've copied all our configs into /etc/supervisor/conf.d/
# run our scripts AND xvfb (already in conf.d) using supervisord
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
```


myapp.supervisor.conf:
```

[supervisord]
nodaemon=true ;

[program:myapp]
command=/home/user/conda/bin/python -u /home/user/myapp/myapp.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=user
environment=HOME="/home/user",USER="user"
```

**Comment by wkentaro** [comment]
Thanks. I will check it out!
