### ISSUE TITLE
Screen shots are blank under MacOS

### ISSUE THREAD

**Issue by KazNX** [mikedh/trimesh#29]
It seems the MacOS implementation of the window doesn't render with visible=false. This affects both the following ways of generating an image:

`mesh.scene().save_image('image.png')`
and
`mesh.show(save_image='image.png')`

As a work around, could you please add the option to set the `visible` flag to `True` even when using `save_image`?

Otherwise the workaround is to duplicate much of SceneViewer() to force `visible` to `True`

**Comment by mikedh** [comment]
Ah, windows does the same thing, hidden windows appear to only render in Linux. Fix which forces visible for non- posix in https://github.com/mikedh/trimesh/commit/73d64d5ad7e9b00acd248506ba81501e29daa8da

**Comment by KazNX** [comment]
Thanks for the speedy update. It's not quite right though.

OSX reports os.name as 'posix', so the behaviour is unchanged under MacOS.

You may want to try `platform.system()` instead. For MacOS this reports `'Darwin'`, while the API documentation highlights it will be `'Linux'` under..., well, Linux.

> platform.system()
Returns the system/OS name, e.g. 'Linux', 'Windows', or 'Java'. An empty string is returned if the value cannot be determined.

**Comment by mikedh** [comment]
Ah, TIL os.name on macs is posix. Changed to platform.system() in https://github.com/mikedh/trimesh/commit/a5e0cefd0d0129eb8744ce56e4280ce7e1eea940, thanks for the report!

**Comment by KazNX** [comment]
Looks good. Thanks.
