### ISSUE TITLE
Combine/merge 2 Voxels

### ISSUE THREAD

**Issue by DanielFPerez** [mikedh/trimesh#294]
Hi, 
first of all thanks for the library, up to now has proven to be better than other alternatives. 
I was wondering if the library had a mehotd implemented to combine 2 voxels? Like a function similar to trimesh.util.concatenate, for voxels.
Thanks!

**Comment by Marviel** [comment]
AFAICT, this doesn't exist natively. If the two voxellizations were created with the same transformation, then this shouldn't be very bad at all if you converted to a 3d numpy array.

On the other hand, if the two different voxellizations were at different voxellization resolutions, or one of them was offset from the other such that the voxels were not "aligned", the result of a voxel1 + voxel2 operation would be unclear. There are different strategies which could be used, and formalized into a set of functions, which would be cool!

Another step further would be to override the addition operator as you suggest... that could get tricky in the (likely?) event of voxel misalignment / resolution differences.

**Comment by mikedh** [comment]
Yeah, as @Marviel mentioned it's currently not a default method. Though if the pitch is the same it's pretty easy:
```In [1]: import trimesh

In [2]: a = trimesh.load('models/ballA.off')

In [3]: b = trimesh.load('models/ballB.off')

In [4]: pitch = 0.25

In [5]: va = a.voxelized(pitch)

In [6]: vb = b.voxelized(pitch)

In [7]: va.sparse_surface
Out[7]: 
TrackedArray([[27, 31, 56],
              [28, 31, 56],
              [29, 31, 56],
              ...,
              [27, 25, 56],
              [28, 25, 56],
              [29, 25, 56]])

In [8]: va.origin
Out[8]: TrackedArray([-11.,  -7.,  -7.])

In [9]: vb.origin
Out[9]: TrackedArray([-3., -7., -7.])

In [20]: combined = np.vstack(((va.sparse_surface - va.origin), (vb.sparse_surface - vb.origin))).astype(np.int64)

In [21]: origin = combined.min(axis=0)

In [22]: origin
Out[22]: array([3, 7, 7])

In [23]: matrix = trimesh.voxel.sparse_to_matrix(combined - origin)

In [24]: vox = trimesh.voxel.Voxel(matrix=matrix, origin=origin, pitch=pitch)

In [25]: vox.show()

```

**Comment by DanielFPerez** [comment]
Sorry for not answering before! 
Thanks both for your help, they were very useful
