### ISSUE TITLE
Error: faces_unique_edges

### ISSUE THREAD

**Issue by jrdkr** [mikedh/trimesh#295]
Found an error in base.py, faces_unique_edges:
result = self._cache[**'edges_unique_inverse'**].reshape((-1, 3)) instead of
result = self._cache['edges_unique_inv'].reshape((-1, 3))
`
def faces_unique_edges(self):
        """
        For each face return which indexes in mesh.unique_edges constructs
        that face.

        Returns
        ---------
        faces_unique_edges : (len(self.faces), 3) int
          Indexes of self.edges_unique that
          construct self.faces

        Examples
        ---------
        In [0]: mesh.faces[0:2]
        Out[0]:
        TrackedArray([[    1,  6946, 24224],
                      [ 6946,  1727, 24225]])

        In [1]: mesh.edges_unique[mesh.faces_unique_edges[0:2]]
        Out[1]:
        array([[[    1,  6946],
                [ 6946, 24224],
                [    1, 24224]],
               [[ 1727,  6946],
                [ 1727, 24225],
                [ 6946, 24225]]])
        """
        # make sure we have populated unique edges
        populate = self.edges_unique
        # we are relying on the fact that edges are stacked in triplets
        result = self._cache['edges_unique_inv'].reshape((-1, 3))
        return result`

**Comment by mikedh** [comment]
Yikes, I should have noticed that haha. I added a fix and test which should catch this and similar errors in the future.

Thanks for the report!

**Comment by mikedh** [comment]
This should be fixed and released, though feel free to re- open.

**Comment by jrdkr** [comment]
Thank you!
