### ISSUE TITLE
Bug in merge_points

### ISSUE THREAD

**Issue by schneitz** [mikedh/trimesh#3]
Hi Michael,

yesterday I came across your code because I have to merge a lot of points of a surface triangulation. After some testing I came across a bug in the "merge_vertices()" function of your code.
Here is a minimal example:

import numpy as np
import trimesh
nds2 = np.array([[ 1.        ,  1.60994057,  2.07798185],
                 [ 1.        ,  0.60994057,  2.07798184],
                 [ 1.        ,  0.60994057,  2.07798185]])
ele2 = np.array([[0,1,2]])
mesh = trimesh.Trimesh(vertices=nds2, faces=ele2,process=True)
mesh.merge_vertices()
print mesh.vertices
print np.linalg.norm(mesh.vertices[1]-mesh.vertices[2])

Best,
Konrad

**Comment by mikedh** [comment]
Hey Konrad, so the distance between the last two points in your example is 9.99999993923e-09     
                                                                                          
Vertices will be merged if they are closer* than trimesh.constants.tol.merge, which is set by default to 1e-8 (which is the same default value Solidworks uses).                   
                                                                                          
9.99999993923e-09 is within floating point weirdness of tol.merge, so I think what you want to do here is just set a larger tol.merge. I just committed a change and did a release (get with pip install trimesh --upgrade) which allows you to monkey patch tol.merge:

```
trimesh.constants.tol.merge = 1e-7                                                        
```

I may add an additional kwarg back to merge_vertices to override the default value in the future, for clarity. Also note that in your example the one face is degenerate or zero area and will be removed by process(). If you just want the points merged you can do: 
```                                                                  
unique, inverse = trimesh.grouping.unique_rows(v)
v_unique = v[unique] 
```                                                                                      

Here's your original code block with monkeypatching:
```
import numpy as np
import trimesh
v = np.array([[ 1. , 1.60994057, 2.07798185],
              [ 1. , 0.60994057, 2.07798184],
              [ 1. , 0.60994057, 2.07798185]])
f = np.array([[0,1,2]])

trimesh.constants.tol.merge = 1e-7

# note that process will merge vertices and remove degenerate faces                       
mesh = trimesh.Trimesh(vertices=v, faces=f, process=True)
print mesh.vertices
```

*closer: any single value doesn't exceed tol.merge, which means the points can have norms
up to 1.73*tol.merge (aka 3**.5)
