### ISSUE TITLE
Voxelisation is susceptible to rounding error

### ISSUE THREAD

**Issue by KazNX** [mikedh/trimesh#30]
Hi,

I have an edge case where voxelising a mesh is incorrectly calculating the number of voxels required due to rounding error. The issue is on line 68 in `voxel.py`, specifically:

`raw_shape   = np.ptp(bounds/pitch, axis=0).astype(int)`

One of the axes is coming out at `14.99999999999999822364`, which is converted to `14` as an integer. This later results in out of range indexing in `run_to_raw()` (`voxel.py line 43`).

The following change is one viable solution:
`raw_shape = (np.ptp(bounds/pitch, axis=0) + (0.5, 0.5, 0.5)).astype(int)`

Thanks.

**Comment by mikedh** [comment]
Cool, did the np.ceil wrap in https://github.com/mikedh/trimesh/commit/a5e0cefd0d0129eb8744ce56e4280ce7e1eea940 fix this for you? 

The voxel module needs a lot of work and isn't something I use regularly. If you're able to coax it into doing anything useful PR's would be gladly accepted haha.

**Comment by KazNX** [comment]
run_to_raw() is now missing from voxel.py, which means Voxel.raw (property) throws an exception.

**Comment by mikedh** [comment]
Really fixed the heck out of that bug. https://github.com/mikedh/trimesh/commit/c69aeb6554f1ec37601a4a6845987bb02727b5f5 adds back function, and a test.

**Comment by KazNX** [comment]
Looks good for my use-case. Thanks.
