### ISSUE TITLE
intersects_location appears to return differing results

### ISSUE THREAD

**Issue by chriscorrea14** [mikedh/trimesh#306]
I ran a tests on the mesh intersections.  I took a bunch of points on the mesh and created a ray some set distance away, and used the ray.intersects_location method.  When I passed in a single ray, it appears to work correctly, but when I pass in multiple rays, then it returns different results.  Here is what I ran:
```python
vertices_copied = deepcopy(vertices)
ray_origins = vertices + .01 * normals
vertices, _, face_ind = mesh.ray.intersects_location(ray_origins, -normals, multiple_hits=False)
print 'multiple rays', vertices_copied[0], vertices[0]

single_ray_vertex, _, _ = mesh.ray.intersects_location([ray_origins[0]], [-normals[0]], multiple_hits=False)
print 'single ray', vertices_copied[0], single_ray_vertex[0]
```

The intersection point should be the same as the original vertex, since I just back up the origin and then intersect it in the same direction.  As you can see, the first test fails, but the second one succeeds:
![image](https://user-images.githubusercontent.com/8335725/51571981-c86c3200-1e58-11e9-90a2-5124b1fe88f6.png)

Am I using the method wrong, or is there something else going on?

Thank you so much!

**Comment by chriscorrea14** [comment]
I just realized I changed the print statement to say "single_ray" and "multiple_ray", but forgot to change the screenshot, but the numbers are the same.  Sorry about that!

**Comment by mikedh** [comment]
Thanks for the report! I was able to reproduce, and it looks like `embree` sees this, but our slow native raytracer does not, so as a temporary fix try loading meshes with `trimesh.load(file_name, use_embree=False)`. 

It's a tough one because `embree` is very close to 50x faster, but is written for graphics purposes and doesn't really do exact checks. #242 is related to this. I'm not sure what the right answer is... if our vectorized numpy ray checks were within 50% of embree I'd be tempted to make them the default but they are SO much slower. 

My code to reproduce:
```                   
import trimesh
import numpy as np

from copy import deepcopy

trimesh.util.attach_to_log()

if __name__ == '__main__':

    mesh = trimesh.load_mesh('part1.STL', use_embree=True)


    normals = mesh.vertex_normals
    vertices_copied = deepcopy(mesh.vertices)
    ray_origins = mesh.vertices + .01 * normals

    loc_multi, _, face_ind = mesh.ray.intersects_location(ray_origi\
ns, -normals, multiple_hits=False)
    print('multiple rays', vertices_copied[0], loc_multi[0])

    assert np.allclose(loc_multi, vertices_copied)

    for	i in range(len(mesh.vertices)):

        loc_single = mesh.ray.intersects_location(
            [ray_origins[i]],
            [-normals[i]],
            multiple_hits=False)[0]
        print('single ray', vertices_copied[i], loc_single[0])

        assert np.allclose(loc_single[0], vertices_copied[i])

```

**Comment by mikedh** [comment]
Consolidating into #242 as it is the same basic issue (no exact results from pyembree). Thanks for the report!
