### ISSUE TITLE
Exception: ascii ply not supported 

### ISSUE THREAD

**Issue by autosquid** [mikedh/trimesh#31]
Hi, can you support models in ascii ply format?

Here is what I got when trying to load a ply file.

'''
    51         if 'ascii' in encoding:
---> 52             raise ValueError('ASCII PLY not supported!')
     53
     54         endian   = ['<', '>']['big' in encoding]
'''

**Comment by mikedh** [comment]
Sure, I added ASCII PLY support in https://github.com/mikedh/trimesh/commit/9dd98740b1fe0277bcd559f49b6a0a5995fde85e. Try it with a pip --upgrade trimesh

**Comment by autosquid** [comment]
@mikedh  thanks! works like a charm! Also, I can tell related code is very clean. 

I think it's ok to close the issue now.

**Comment by autosquid** [comment]
Hi, I am now trying to load a mesh with uv texture coordinates in ply format, which seems impossible by trimesh now.

I checked the trimesh/io/ply.py, and found properties other than 'xyz' for vertex are dropped. 

I am wondering the reasons behind, and wanna make sure if it's possible way to keep them and other customized elements and properties. 

 (I have read a lot about ply (ascii format), and I a glad to help to contribute implementations if needed.)

**Comment by mikedh** [comment]
Yeah, textures aren't a thing thats supported. As a bandaid I exposed the intermediate data structure which has the rough PLY data as a kwarg, which gets saved:

`m._kwargs['ply_data']`

This is quite cheesy as its not a unified solution which would work for different formats. The best thing to do would be to re-write https://github.com/mikedh/trimesh/blob/master/trimesh/visual.py to have an overall more sensible and clearer model that cleanly supported vertex color, face color, and texture. Then the importer could dump the PLY UV data into that structure easily. Visual properties are pretty far down my priority list however. Feel free to take a go at it though, it would be much appreciated!

**Comment by autosquid** [comment]
@mikedh  Thanks for your quick reply.  I'll take a go whenever possible.


Yet I met with another problem.

In trimesh/io/ply.py, you have the following dict to map a type to numpy data type string:

```
    dtypes = {'char'  : 'i1',
              'uchar' : 'u1',
              'short' : 'i2',
              'ushort': 'u2',
              'int'   : 'i4',
              'uint'  : 'u4',
              'float' : 'f4',
              'double': 'f8'}
```

However, I came across  ply files which uses `int32`, `float32` etc, and thus, loading error occurs.
The following is an example:

```
element vertex 14904
property float32 x
property float32 y
property float32 z
property float32 nx
property float32 ny
property float32 nz
property float32 s
property float32 t
element face 4968
property list uint8 uint32 vertex_indices
end_header
```

**Comment by mikedh** [comment]
Heh didn't see those in the spec 😎 . Did I get em all in https://github.com/mikedh/trimesh/commit/4e273a5c5285d789e1a79e04370688a0b86fa1d1?

**Comment by autosquid** [comment]
Perfect. 👍
