### ISSUE TITLE
displaying a scale

### ISSUE THREAD

**Issue by ifermion** [mikedh/trimesh#311]
Hi again,

I followed up on your comments on a previous issue (#280 - being unable to reopen it, I thought of posting it here.) I created and ended up stacking cylinders to make a scale. However there are several issues I'd like to clarify.

1. I'd like the scalebar made of cylinders to stay fixed on the scene, as I rotate / interact with the mesh (sphere in this case). Is there such a possibility ?

2. Or is it possible to fix a scalebar from outside the scene but still appearing on the pyglet window in some way, so that it stays intact irrespective of the user-driven rotations in the scene.

3. I've checked on the issues here, to figure out if was possible to change the direction of the illumination source/ lighting so that there would not be a specular reflection off the surface of the mesh. From what I gathered the lighting is hard-coded to the pyglet and hence it seems not possible to change its orientation.
 In this case, I wonder whether it would be possible to change the location of the camera, such that the scene is in front of the lighting source, or in other words the lighting source is right behind the camera.

Thank you in advance again !

![sphere_scale](https://user-images.githubusercontent.com/24443359/52179755-690a0c80-27de-11e9-8ef4-3dda088725f9.png)

```
import trimesh
import numpy as np

sp = trimesh.creation.icosphere(radius=0.5,subdivisions=5)

nf = len(sp.faces)

n = np.arange(nf)

colors = trimesh.visual.interpolate(n,color_map='jet')
sp.visual.face_colors = [100,100,100,0]

for i, color in zip(n,colors):
	sp.visual.face_colors[i] = color
	#print(i)
	
#stacking cylinders to make a scalebar

z_minus = min(sp.vertices[:,2])
z_plus = max(sp.vertices[:,2])
H = abs(z_plus)+abs(z_minus)

n_cy =100  # number of cylinders  to stack
h= H/n_cy

cylinders = [trimesh.creation.cylinder(0.05,h,400,smooth=True) for i in range(n_cy)]
cyl_colors = trimesh.visual.interpolate(np.arange(n_cy),color_map='jet')

for i,c in enumerate(cylinders):
	c.vertices[:,2] += i*h -abs(z_minus)
	c.vertices[:,0] += 0.9
	c.visual.face_colors = cyl_colors[i]
	
scene = trimesh.Scene([sp,cylinders])

scene.show(smooth=False)

**Comment by mikedh** [comment]
Cylinders look cool! I played around briefly with fixing the mesh transform to the camera, but I think to keep it fixed, the `on_draw` would also need to skip applying the view transform on certain nodes. 

Here's an example of making one mesh camera- relative.
```
import trimesh
import numpy as np

if __name__ == '__main__':
    s = trimesh.Scene({'a': trimesh.creation.cylinder(), 'b': trimesh.creation.cylinder()})

    s.set_camera()

    node_fix = s.graph.nodes_geometry[0]
    geom_fix = s.graph[node_fix][1]

    s.graph.transforms.remove_edge(s.graph.base_frame, node_fix)
    s.graph.update('camera',  node_fix, matrix=np.eye(4), geometry=geom_fix)

```

**Comment by ifermion** [comment]
Thanks a lot for the prompt reply.  I tried your code, I'm not sure if I understood correctly how the fixing works.

I wonder also how to call the original parameters initiated by init_gl() at https://github.com/mikedh/trimesh/blob/master/trimesh/viewer/windowed.py and alter them, so that I could control the illumination settings. Any ideas ?

**Comment by mikedh** [comment]
Hey, I think the changes from #322 and the quick patch in https://github.com/mikedh/trimesh/commit/14044fdd525a7bf3daa4640f1c5c62b1766e237d let you do this now: 

```
In [1]: import trimesh

In [2]: s = trimesh.Scene({'a': trimesh.primitives.Cylinder(),
                           'b': trimesh.primitives.Cylinder()})

In [3]: s.lights
Out[3]: 
[<trimesh.scene.lighting.PointLight at 0x7f9aff3c2668>,
 <trimesh.scene.lighting.PointLight at 0x7f9aff3c2978>]

In [4]: s.lights[0].color
Out[4]: array([ 60,  60,  60, 255], dtype=uint8)

In [5]: s.lights[0].color = [20,20,20,255]

In [6]: s.geometry
Out[6]: 
OrderedDict([('a', <trimesh.primitives.Cylinder at 0x7f9aff3d7b70>),
             ('b', <trimesh.primitives.Cylinder at 0x7f9aff3d7c88>)])

In [7]: s.show(fixed=['a'])
Out[7]: SceneViewer(width=900, height=675)
```
