### ISSUE TITLE
Quick question - path of a hole?

### ISSUE THREAD

**Issue by yw5aj** [mikedh/trimesh#312]
Hi Mike,

Sorry for the bother again. A quick question - I know that we have functions to find the path around a hole to fix it. Is there a method to just return the path for the hole? In other words, I wonder whether we already have a method to return all the edges that only belongs to one face. I can do that if there is no such existing functions, but just figured if you could help with a pointer if there already is :)

Thank you!

Shawn

**Comment by mikedh** [comment]
Hey Shawn, no worries- I think `mesh.outline` does what you want in this case:

```

In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [3]: m.is_watertight
Out[3]: True

In [4]: m.faces = m.faces[1:]

In [5]: m.is_watertight
Out[5]: False

In [6]: o = m.outline()

In [7]: o
Out[7]: <trimesh.path.path.Path3D at 0x1a36a8d9c88>

In [9]: m.outline?
Signature: m.outline(face_ids=None, **kwargs)
Docstring:
Given a set of face ids, find the outline of the faces,
and return it as a Path3D.

The outline is defined here as every edge which is only
included by a single triangle.

Note that this implies a non-watertight section,
and the 'outline' of a watertight mesh is an empty path.

Parameters
----------
face_ids : (n) int
  Indices to compute the outline of.
  If None, outline of full mesh will be computed.
**kwargs: passed to Path3D constructor

Returns
----------
path : Path3D
  Curve in 3D of the outline
File:      c:\users\mik3d\dropbox\robotics\trimesh\trimesh\base.py
Type:      method

In [10]: trimesh.Scene([m, o]).show()
```

![image](https://user-images.githubusercontent.com/1403074/52180767-6e546080-27b8-11e9-9fae-baa671c61071.png)

**Comment by yw5aj** [comment]
Exactly what I needed! Thank you so much again @mikedh .

Have a great week! :)
