### ISSUE TITLE
import formats

### ISSUE THREAD

**Issue by e3dEF** [mikedh/trimesh#319]
Hi,

as demonstrated in the source code, possible input mesh data formats are 'stl', 'stl_ascii', 'off', 'dict', 'dict64', 'json', 'msgpack', 'ply', 'obj', 'glb', 'zip', 'tar.bz2' and 'tar.gz'.
But is it possible to load meshes from RAM, e.g. using lists of vertices and triangles without faking a file format?

Kind regards

**Comment by mikedh** [comment]
Hey, yeah absolutely, just use the `trimesh.Trimesh` constructor:

```
In [1]: import trimesh

In [2]: import numpy as np

In [3]: vertices = np.random.random((300, 3))

In [4]: faces = np.arange(300).reshape((-1, 3))

In [5]: trimesh.Trimesh?
Init signature: trimesh.Trimesh(vertices=None, faces=None, face_normals=None, vertex_normals=None, face_colors=None, vertex_colors=None, metadata=None, process=True, validate=False, use_embree=True, initial_cache={}, visual=None, **kwargs)
Docstring:     
Parent of geometry classes.

The `Geometry` object is the parent object of geometry classes, including:
Trimesh, PointCloud, and Scene objects.

By decorating a method with `abc.abstractmethod` it just means the objects
that inherit from `Geometry` MUST implement those methods.
Init docstring:
A Trimesh object contains a triangular 3D mesh.

Parameters
----------
vertices : (n, 3) float
  Array of vertex locations
faces : (m, 3) or (m, 4) int
  Array of triangular or quad faces (triangulated on load)
face_normals : (m, 3) float
  Array of normal vectors corresponding to faces
vertex_normals : (n, 3) float
  Array of normal vectors for vertices
metadata : dict
  Any metadata about the mesh
process : bool
  if True, Nan and Inf values will be removed
  immediately and vertices will be merged
validate : bool
  If True, degenerate and duplicate faces will be
  removed immediately, and some functions will alter
  the mesh to ensure consistent results.
use_embree : bool
  If True try to use pyembree raytracer.
  If pyembree is not available it will automatically fall
  back to a much slower rtree/numpy implementation
initial_cache : dict
  A way to pass things to the cache in case expensive
  things were calculated before creating the mesh object.
visual : ColorVisuals or TextureVisuals
  Assigned to self.visual
File:           /dropbox/drop/Dropbox/robotics/trimesh/trimesh/base.py
Type:           ABCMeta

In [6]: mesh = trimesh.Trimesh(vertices=vertices, faces=faces)

In [7]: mesh.faces.shape
Out[7]: (100, 3)

In [8]: mesh.vertices.shape
Out[8]: (300, 3)
```

**Comment by e3dEF** [comment]
Hey Mike,

thank you for the quick response. Does that mean, that vertices have to occur redunant in the vertices list? I tried to create an array of 4 vertices and an array of two faces ( (1,2,3) and (1,2,4)), but it didnt work.

Best

**Comment by mikedh** [comment]
Nah multiple faces can reference the same vertex indices. The reason `[[1, 2, 3], [1, 2, 4]]` didn't work with an array of 4 vertices is that in python lists are 0- indexed, so the maximum index for a 4- length list is 3. `[[0, 1, 2], [0, 1, 3]]` would work for four vertices.

**Comment by e3dEF** [comment]
Thats what i did. What I did wrong was not to press c to show all faces. I have a last question. What is the correct order of vertices that should be given as argument to trimesh.Trimesh(), if I want to retain face normals. Counter clock wise?

Thank you for your help 
Best

**Comment by mmatl** [comment]
@e3dEF Yep, it's counter-clockwise (right-handed coordinate system).
