### ISSUE TITLE
Path3D via mesh.section should reference incomplete sections

### ISSUE THREAD

**Issue by Zoodinger** [mikedh/trimesh#32]
I'm using the mesh.section function to detect intersections. The problem is that a lot of our data is incorrect geometry (missing faces), and the library discards those segments completely. Having that data is essential when dealing with bad files.

**Comment by mikedh** [comment]
Section doesn't discard the bad line segments- did you check the actual section.entities? It won't generate paths automatically as there wouldn't be cycles on the vertex graph. If paths are what your after I might suggest creating a repair function which checks `section.vertex_graph.degree()` and fixing vertices which only have degree 1 (AKA not connected to anything.)  Oh also are you sure the plane intersects the model? 

As a quick check I sectioned random polygon soup, which found the intersections fine:

```
import numpy as np
import trimesh

if __name__ == '__main__':
    trimesh.util.attach_to_log(log_level=trimesh.util.logging.DEBUG)

    count = 100
    vertices = np.random.random((count*3,3))
    faces    = np.arange(count*3).reshape((-1,3))

    mesh = trimesh.Trimesh(vertices=vertices, faces=faces)
    section = mesh.section(plane_normal=[0,0,1], plane_origin=mesh.centroid)

    print(section.entities)
```

**Comment by mikedh** [comment]
Closing for now- feel free to reopen with an example that demonstrates the behavior.
