### ISSUE TITLE
Link for "here are some tips..." does not work

### ISSUE THREAD

**Issue by scoppiare99** [mikedh/trimesh#320]
The link for "tips to write mesh code in Python" as mentioned in the documentation: https://github.com/mikedh/trimesh/blob/master/trimesh/io/README.md gives error 404 when clicked.

**Comment by mikedh** [comment]
Thanks for the report! Fixed by https://github.com/mikedh/trimesh/commit/b64f9763e48f09efbd1d4195bc34bf2cb7eb9c71
