### ISSUE TITLE
Getting faces associated to vertices...

### ISSUE THREAD

**Issue by bbarroqueiro** [mikedh/trimesh#323]
Hello, now i'm working in a new weighting function... 

At a given vertices and its neighbor (that forms an edge), i need to know the area of the two triangles that forms the edge...
My current solution quite slow, i'm checking all nearby_faces of all vertices and then i intersect the nearby faces of vertice and nearby_face of its neighbour. Thus, i get the wanted two elements and then their area... 

Any better ideas?

Regards

**Comment by Marviel** [comment]
`edges_face` seems to be what you're looking for.
https://github.com/mikedh/trimesh/blob/e0533c397ac584351f4b5ec7d8a06a80a0a0adcb/trimesh/base.py#L795

**Comment by bbarroqueiro** [comment]
Thanks Marviel...

**Comment by mikedh** [comment]
Hey, I would probably get it through grouping edges then referencing `edges_face` as @Marviel suggested:

```
In [7]: groups = trimesh.grouping.group_rows(m.edges_sorted, require_count=2)

In [8]: groups
Out[8]: 
array([[ 2,  4],
       [ 8, 11],
       [ 1,  6],
       [ 0, 14],
       [ 7, 23],
       [ 5, 10],
       [ 3, 16],
       [ 9, 25],
       [15, 20],
       [31, 17],
       [26, 29],
       [24, 32],
       [34, 30],
       [12, 19],
       [22, 27],
       [21, 13],
       [18, 33],
       [28, 35]])

In [9]: edges = m.edges_sorted[groups[:,0]]

In [10]: edges
Out[10]: 
array([[0, 1],
       [0, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [1, 5],
       [4, 5],
       [2, 6],
       [4, 6],
       [5, 6],
       [1, 7],
       [2, 7],
       [3, 7],
       [5, 7],
       [6, 7]])

In [11]: face_index = m.edges_face[groups]

In [12]: m.faces[face_index[0]]
Out[12]: 
TrackedArray([[1, 3, 0],
              [4, 1, 0]])

In [13]: edges[0]
Out[13]: array([0, 1])

In [14]: edge_area = m.area_faces[face_index].sum(axis=1)

```

**Comment by bbarroqueiro** [comment]
Hello, thanks for the answer. In the meanwhile i was working in other topic...

**Comment by mikedh** [comment]
Heh cool, which other topic?

**Comment by bbarroqueiro** [comment]
It is a really specific topic, it is the characterization of ti6al4v titanium alloy in terms of linear and non-linear responses… 
It is a task of much larger framework, it is all about designing structures… The current approach follows the line of Topology optimization, smoothing the resultant geometry and structural analysis (black box for me).  
The material response is needed for the topology optimization and the structural analysis
