### ISSUE TITLE
Build mesh from numpy ndarray

### ISSUE THREAD

**Issue by carshadi** [mikedh/trimesh#328]
Hello, how can I build a mesh using an array of 3d points? Do I need to perform a triangulation first? I am having a hard time understanding how to create mesh other than load from file.

Thank you,
Cameron

**Comment by mikedh** [comment]
Hey Cameron, yeah you'd need to triangulate points to create a mesh. You could also use them as a `PointCloud` object, which includes an automatically generated convex hull triangulation as a mesh object:
```
In [1]: import numpy as np

In [2]: import trimesh

In [3]: points = np.random.random((100, 3))

In [4]: cloud = trimesh.PointCloud(points)

In [5]: cloud
Out[5]: <trimesh.points.PointCloud at 0x7f21b8e1f518>

In [6]: cloud.convex_hull
Out[6]: <trimesh.base.Trimesh at 0x7f21b8de14a8>

```

**Comment by carshadi** [comment]
very good thanks!
