### ISSUE TITLE
`mesh.split()` fails for a tetrahedron

### ISSUE THREAD

**Issue by ydawei** [mikedh/trimesh#330]
To reproduce:
```
import trimesh
import numpy as np

vertices = np.array([
	[0, -1, 1],
	[0, 1, 1],
	[-1, 0, -1],
	[1, 0, -1]
])

faces = np.array([
	[2, 1, 3],
	[2, 3, 0],
	[2, 0, 1],
	[3, 1, 0]
])

mesh = trimesh.Trimesh(vertices, faces)
print(mesh.split())
```
Result : `[]`
Expected: a trimesh object

Potential causes:
1. It seems that [here](https://github.com/mikedh/trimesh/blob/a62de53f676b2a1e0f1c758d024f59874bfa259b/trimesh/util.py#L1313) it should be `len(face_sequences[0])`, because this check fails;
2. [Here](https://github.com/mikedh/trimesh/blob/a62de53f676b2a1e0f1c758d024f59874bfa259b/trimesh/util.py#L1380) it assumes the number of faces of a mesh should be greater than 4, but it is not true for a tetrahedron.

**Comment by mikedh** [comment]
Good catch! Test and fix in https://github.com/mikedh/trimesh/commit/1565c701f9cf42cf06553e0a04b6bc4bb33f5916. 

Thanks for the report!
