### ISSUE TITLE
What's the epsilon that is used by the RayMeshIntersector to define a hit?

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#331]
I cannot find any parameter on this. The constants module contains some tolerances but none related to checking intersections. Any hint?

**Comment by mikedh** [comment]
The non- embree one `trimesh.ray.RayMeshIntersector`? It looks like it's checking barycentric coordinates against `tol.zero`: https://github.com/mikedh/trimesh/blob/a6b31e6f7ca1e72d9e5044493b5209ce301c5289/trimesh/ray/ray_triangle.py#L207-L208

**Comment by clemense** [comment]
Ah, right, thanks!

I'm actually using the pyembree one, but it doesn't look like it's being exposed in the wrapper. I'll take a look at pyembree, maybe I'll find something there.

FYI: The reason is that if I'm doing a ray-mesh intersection call, with the ray origin being the result of mesh.sample(1) and the ray direction the associated normal, I sometimes get the origin itself as a collision and sometimes not. It's not consistent.

**Comment by mikedh** [comment]
Consolidating into #242 as they are both related to the precision/exactness issues in embree. If you have any good ideas on how to solve this let me know hahah, I sure don't. 

Thanks for the report!
