### ISSUE TITLE
Boolean intersection error

### ISSUE THREAD

**Issue by minjcha** [mikedh/trimesh#333]
Hello, 

I wanted to use the boolean operation to find the intersection of two meshes, using following code.
bo1 = list([mesh_sphere, mesh_box1])
bool1_mesh = trimesh.boolean.intersection(bo1, engine=None)

However, there was an error and I copied below. 
Could you provide any instruction on boolean function? 

Thanks!
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-59-5582ad2f96bc> in <module>
----> 1 bool1_mesh = trimesh.boolean.intersection(bo1, engine=None)

/usr/local/miniconda3/lib/python3.7/site-packages/trimesh/boolean.py in intersection(meshes, engine)
     53                     volume that is contained by all meshes
     54     """
---> 55     result = _engines[engine](meshes, operation='intersection')
     56     return result
     57 

/usr/local/miniconda3/lib/python3.7/site-packages/trimesh/boolean.py in boolean_automatic(meshes, operation)
     63         result = interfaces.scad.boolean(meshes, operation)
     64     else:
---> 65         raise ValueError('No backends available for boolean operations!')
     66     return result
     67 

ValueError: No backends available for boolean operations!

**Comment by mikedh** [comment]
Hey, trimesh doesn't implement booleans internally, it uses either `blender` or `openscad`. If you install one or both of those packages you can then use them for boolean operations.

**Comment by mkeshavarzi** [comment]
Hey - I've installed and imported both packages but still have the same problem. Is there any specific version of the backend engines I would need to use?

**Comment by mikedh** [comment]
Hey, if you have them installed it may be a search path issue, you can do some debugging with

```
In [1]: import trimesh

In [2]: trimesh.interfaces.blender.exists
Out[2]: True

In [3]: trimesh.interfaces.scad.exists
Out[3]: True

In [4]: trimesh.interfaces.blender._search_path
Out[4]: '/opt/ros/melodic/bin:/home/mikedh/google-cloud-sdk/bin:/home/mikedh/.nvm/versions/node/v10.17.0/bin:/home/mikedh/.yarn/bin:/home/mikedh/miniconda/bin:/home/mikedh/miniconda/condabin:/home/mikedh/.poetry/bin:/home/mikedh/bin:/home/mikedh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

In [5]: trimesh.interfaces.blender._blender_executable
Out[5]: '/usr/bin/blender'

```

**Comment by derekvanloon** [comment]
Hi! I have also a question about this. I did install Blender and OpenSCAD, but both can't be found. What does it exactly search for? Does it search in every subdirectory stated from `trimesh.interfaces.blender._search_path`? And can I change the _search_path manually?

Thanks in advance.

**Comment by andreaskra** [comment]
Add the path to the blender executable to your Path variable.

**Comment by Mandelbr0t** [comment]
+1, same issue 
tried trimesh 3.9.1 and 3.9.19
