### ISSUE TITLE
scene.save_image error from pyglet

### ISSUE THREAD

**Issue by umyta** [mikedh/trimesh#335]
Hi, I'm trying to save camera view of the rendering scene, but I got  the following name error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-43-e3826cc37929> in <module>
      1 scene = mesh.scene()
----> 2 data = scene.save_image(resolution=[256,256], visible=True)

~/.conda/envs/test/lib/python3.6/site-packages/trimesh/scene/scene.py in save_image(self, resolution, **kwargs)
    591         png: bytes, render of scene in PNG form
    592         """
--> 593         from .viewer import render_scene
    594         png = render_scene(scene=self,
    595                            resolution=resolution,

~/.conda/envs/test/lib/python3.6/site-packages/trimesh/scene/viewer.py in <module>
      1 import pyglet
----> 2 import pyglet.gl as gl
      3 
      4 import numpy as np
      5 

~/.conda/envs/test/lib/python3.6/site-packages/pyglet/gl/__init__.py in <module>
    225     else:
    226         from .carbon import CarbonConfig as Config
--> 227 del base
    228 
    229 # XXX remove

NameError: name 'base' is not defined
```

I am working on a remote linux machine with jupyter notebook. The error can be reproduced by running:
```
import trimesh
mesh = trimesh.primitives.Sphere()
scene = mesh.scene()
data = scene.save_image(resolution=[256,256], visible=True)
```
I was wondering if I can get some suggestions on how to solve this problem.

**Comment by mikedh** [comment]
Hey, it's trying to open an OpenGL context but isn't able to. Being able to do that is system specific, a long story and not easy. Some options:

- run the jupyter notebook locally
- ssh to the remote machine with `-X` to enable X11 forwarding, and see if that does anything
- ssh to the remote machine and start `xvfb` with a `$DISPLAY` set, and try to get jupyter to use that
- create a docker image `FROM mikedh/trimesh`, make a supervisord config for the jupyter server, and in the dockerfile copy that to `/etc/supervisor/conf.d` and then create a `RUN jupyter notebook` or whatever. The docker images are configured for software rendering via LLVMPipe and XvFB.
- check out [pyrender](https://github.com/mmatl/pyrender)

**Comment by umyta** [comment]
Thank you so much for the quick reply! You are right, when I did it locally it works. I'll close this issue now.
