### ISSUE TITLE
save_image stores black image on mac

### ISSUE THREAD

**Issue by umyta** [mikedh/trimesh#337]
Hi, I know this has been asked before, but I noticed that #223 was closed without a followup. I was wondering if anybody knows how to overcome this issue. I was trying to save the output of scene.save_image() on a macbook. During saving, there is a view that looks fine, but the saved images are red blank images for some reason. Adding flag visible=True did not help. Any advice would be much appreciated. Thanks!

**Comment by Marviel** [comment]
I've had a similar issue in the past and did not end up resolving it, unfortunately.

**Comment by mikedh** [comment]
I've had very inconsistent success with this too, it is quite system configuration dependent and hard to resolve at the library level. I use the docker/llvmpipe/xvfb approach in my applications, as once you've suffered through the setup it works quite reliably.  Other related issues: https://github.com/mikedh/trimesh/issues/287 https://github.com/mikedh/trimesh/issues/115

**Comment by umyta** [comment]
Thank you for the information!
