### ISSUE TITLE
mesh load: reorder the data?

### ISSUE THREAD

**Issue by amlucas** [mikedh/trimesh#338]
Hello,
I want to load 2 meshes (both are in off file, but it can be any other format).
These 2 meshes have the same connectivity but different vertices.
The faces are listed in the same order in the off file.
I want that trimesh loads the 2 files such that mesh1.faces == mesh2.faces, but I can see that trimesh is reordering the faces. 
Is there a flag to avoid this issue?
Thanks in advance!

**Comment by mikedh** [comment]
Hey, yeah it's merging vertices on load. To skip that step:
`mesh = trimesh.load('model.off', process=False)`

**Comment by amlucas** [comment]
Great, it works now. 
It would be perfect to see those flags in the documentation (or did I miss it?)
Thank you!
