### ISSUE TITLE
MemoryError for mesh.contains on large number of points 

### ISSUE THREAD

**Issue by andreanicastro** [mikedh/trimesh#339]
Hi, I am trying to obtain an occupancy grid for a mesh. I am calling the mesh for a grid of 256^3. I am running trimesh on archlinux with python3.
The method called is the one below

```
def mesh_occupancy(meshfilename, sample_points, transformation=np.eye(4)):
    mesh = trimesh.load(meshfilename)
    mesh.apply_transform(transformation)
    return mesh.contains(sample_points).astype(np.bool)
```

Unfortunately I seem to hit a memory limit, but my ram usage seems to be under 10GB out of 32GB.
Any insights on how to solve the issue? 
The full error is listed below:

> Traceback (most recent call last):
>   File "/home/an4915/research/object_reconstruction/src/thickness_network/ycbvideo_occupancy_map.py", line 92, in <module>
>     main()
>   File "/home/an4915/research/object_reconstruction/src/thickness_network/ycbvideo_occupancy_map.py", line 68, in main
>     occ = np.logical_or(occ, mesh_occupancy(filename, pts, np.dot(trans_tw_pcnnw, pose_pcnnw)))
>   File "/home/an4915/research/object_reconstruction/src/thickness_network/ycbvideo_occupancy_map.py", line 16, in mesh_occupancy
>     return mesh.contains(sample_points).astype(np.bool)
>   File "/usr/lib/python3.7/site-packages/trimesh/base.py", line 2506, in contains
>     contains = self.ray.contains_points(points)
>   File "/usr/lib/python3.7/site-packages/trimesh/ray/ray_triangle.py", line 134, in contains_points
>     return contains_points(self, points)
>   File "/usr/lib/python3.7/site-packages/trimesh/constants.py", line 128, in timed
>     result = method(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/trimesh/ray/ray_util.py", line 68, in contains_points
>     -ray_directions)))
>   File "/usr/lib/python3.7/site-packages/trimesh/ray/ray_triangle.py", line 92, in intersects_location
>     **kwargs)
>   File "/usr/lib/python3.7/site-packages/trimesh/ray/ray_triangle.py", line 57, in intersects_id
>     triangles_normal=self.mesh.face_normals)
>   File "/usr/lib/python3.7/site-packages/trimesh/ray/ray_triangle.py", line 176, in ray_triangle_id
>     triangle_candidates = triangles[ray_candidates]
> MemoryError

**Comment by mikedh** [comment]
Hey, I would guess the ray candidates mask is pretty giant, and then when it tried to use it as an index in the (n, 3, 3) that pushed it over the memory limit. 

For the occupancy grid have you tried computing it in chunks? Maybe one contains call per Z-layer?

**Comment by andreanicastro** [comment]
Hi, thanks for the incredibly fast response. I am going to do that actually, I was just wondering why that happened since I had plenty of free RAM on my machine.

**Comment by mikedh** [comment]
Sounds good! My interpretation of the traceback is that if `ray_candidates` is on the order of 10gb, `triangles[ray_candidates]` is on the order of 30gb.

**Comment by andreanicastro** [comment]
I see! Thanks for the explanation!
