### ISSUE TITLE
Possible to export ASCII STL? 

### ISSUE THREAD

**Issue by petebachant** [mikedh/trimesh#34]
Looks like the STLs generated are only binary, without any option for ASCII.

**Comment by mikedh** [comment]
Sure, added in https://github.com/mikedh/trimesh/commit/418bdfd635122279b3a6cfcd33a836f3e98f442f

**Comment by petebachant** [comment]
Awesome, and thanks for creating this library!

**Comment by mikedh** [comment]
Glad it's useful! I also just pushed a change so you can force the file type like this:

```
import trimesh

if __name__ == '__main__':
    trimesh.util.attach_to_log()
    m = trimesh.load('models/featuretype.STL')
    m.export(file_obj='out.stl', file_type='stl_ascii')
```
