### ISSUE TITLE
depth map

### ISSUE THREAD

**Issue by umyta** [mikedh/trimesh#340]
Hi, this is more of an inquiry than an issue. Is there a way to save a depth map of the rendered object? Any help would be much appreciated!

**Comment by mikedh** [comment]
Hey, there's probably a way to do this via pyglet, although I might suggest checking out [pyrender](https://github.com/mmatl/pyrender), it's a much more complete rendering endpoint than `trimesh.viewer.windowed`.

That being said, you can also do this using ray tests, and with `pyembree` installed it's not even that slow (600K+ rays per second). I added an [example](https://github.com/mikedh/trimesh/blob/master/examples/raytrace.py) which produces images that look like this:

![depth](https://user-images.githubusercontent.com/1403074/54165657-156f8c00-4438-11e9-946e-12e382905e9f.png)

**Comment by umyta** [comment]
Thank you so much for the answer. This is very helpful!
