### ISSUE TITLE
export list of mesh to obj file

### ISSUE THREAD

**Issue by yanghtr** [mikedh/trimesh#341]
Thank you for the great library.

When I use `trimesh.load_mesh` to load an .obj file, I get a list of mesh.
```
In   [1]: mesh_list = trimesh.load_mesh(obj_path)  # obj_path is the path to the 3D model (.obj file)
```
And from the model I get a list of mesh:
```
In   [2]: mesh_list
Out[2]: 
[<trimesh.base.Trimesh at 0x7fbffc751dd0>,
 <trimesh.base.Trimesh at 0x7fbffc751350>,
 <trimesh.base.Trimesh at 0x7fbffc751490>,
 <trimesh.base.Trimesh at 0x7fbffc751590>]
```

After some operation of `mesh_list`, I want to export the newly modified model to .obj file. However,  using
```
trimesh.exchange.wavefront.export_wavefront(mesh_list)
```
is wrong because `trimesh.exchange.wavefront.export_wavefront()` only accept ` Trimesh object`. Is there any way to export the newly modified model to a single obj file? Or related features?

Thanks!

**Comment by mikedh** [comment]
Hey, you can actually use `np.sum` or `trimesh.util.concatenate` to put it back into a single mesh:

`mesh = trimesh.util.concatenate(mesh_list)`

**Comment by yanghtr** [comment]
Thank you very much!!!
