### ISSUE TITLE
Reference for adding to a publication

### ISSUE THREAD

**Issue by adityabalu** [mikedh/trimesh#346]
Hi! I was using your package for performing voxelization of several models and to perform distance computations etc. I would like to cite your package. Is there any DOI for this?

**Comment by mikedh** [comment]
Heh we should probably write a systems paper to make this easier :smile:. An [APA guide](https://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html) suggests the following:

Example Reference:
`Trimesh [Computer software]. (2019). Retrieved from https://github.com/mikedh/trimesh`

Example Text Citation:
`“We used Version 2.37.13 of Trimesh (2019) to complete our work."`
