### ISSUE TITLE
MTL file without texture

### ISSUE THREAD

**Issue by umyta** [mikedh/trimesh#350]
This is a follow up of #332. I have an obj file that only has mtl file with colors but not textures, when I call trimesh.load or trimesh.load_mesh, information from mtl file does seem to be loaded, my mesh.visual seems to have nothing loaded. Can I have some help with this? I just want to get the vertex or face color loaded to the mesh if possible from obj and mtl files.

**Comment by mikedh** [comment]
Hey, it's currently not supported. I'm actually in the middle of an OBJ re-write, and have added this to the scope. Hopefully I can get the new version released in the next few weeks.

**Comment by umyta** [comment]
Thank you for the followup. Looking forward to it!

**Comment by mikedh** [comment]
Combining into #391. Thanks for the report!
