### ISSUE TITLE
Capturing helical paths

### ISSUE THREAD

**Issue by AtinAngrish** [mikedh/trimesh#355]
Hi Mike!

Thanks for the hard work on the library!

Now, this is a fairly open ended question, so feel free to close it if you think it is out of scope of this library:

I often have mechanical parts with threaded structures (think bolts with threading or nuts with internal threads tapped into them). I was wondering if there is a way to use trimesh library to identify the path3D elements attached to those threads, extract and compare them?

I will be happy to share more details if needed. 

Regards.

AA

**Comment by mikedh** [comment]
Oh that sounds fun. I'd probably use the `mesh.symmetry_axis` and `mesh.center_mass` and look for edges with the same radius and helical pitch, and then do connected components on those edges. `mesh.face_adjacency_angles` and `mesh.face_adjacency_edges` might also be useful for refining the list of edges. Then pass the result to `trimesh.path.exchange.misc.edges_to_path`.
