### ISSUE TITLE
Geometry colors and line widths in Scene

### ISSUE THREAD

**Issue by Styxny** [mikedh/trimesh#356]
Hey Mike, 

I was wondering if there was a way to adjust the color and widths of the lines of a mesh/path in a scene?  I have been searching the docs for a while and I am wondering if this is even an option?

-Thanks

**Comment by mikedh** [comment]
Hey, right now it's not supported in `trimesh.viewer.windowed` and there is no entity color attribute in path objects, though PR's are welcome!

If I were doing this I'd probably create a `Path.entities_color` field that was `(len(entities), 4)`, and then add a `line_width` parameter to the viewer that was passed to [glLineWidth](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glLineWidth.xhtml) in `init_gl`.

**Comment by mikedh** [comment]
Added to enhancements list. Thanks for the suggestion!

**Comment by johanjohan** [comment]
@mikedh Hey Mike, I enjoy trimeshing..., has the linewidth in scene ever been added since? Or a way to set the opengl attribute glLineWidth?
