### ISSUE TITLE
No module named 'pyglet'

### ISSUE THREAD

**Issue by garynobles** [mikedh/trimesh#357]
trimesh works as expected with the following:
```
import numpy as np
import trimesh
mesh = trimesh.load(somefile)
value = mesh.is_watertight
print(value)
volume = mesh.volume
print(volume)
```

However when calling `mesh.show()`  I get `No module named 'pyglet'`

pyglet is installed for python 3.x I tested it using the piglet hello world example.

**Comment by mikedh** [comment]
Hey, can you add `import pyglet` to the top of that script and run?

**Comment by garynobles** [comment]
ok, now it worked, I restarted my computer, may be there was a glitch in the install, sorry for troubling you. Please mark this as resolved!

**Comment by mikedh** [comment]
Cool, glad it's fixed! With regards to PostGIS it looks like that would be easiest to do by writing a `trimesh.Trimesh` to WKT exporter, using `PolyhedralSurface` or something. This WKT document might help: http://www.opengeospatial.org/standards/sfa
