### ISSUE TITLE
Minimum bounding sphere not minimal?

### ISSUE THREAD

**Issue by jackd** [mikedh/trimesh#358]
Hi, loving the package. One issue: I might be misunderstanding the intent of the function, but is `nsphere.minimum_nsphere` supposed to return the center/radius that results in the 'exact' minimum sphere (to within numerical precision)? Or just an approximation?

[This gist](https://gist.github.com/jackd/22dfc19984443469e117a091e11d9e2b) illustrates my issue. After recentering/scaling according to `minimum_nsphere` outputs, a naive shift to the midpoint of the axis-aligned bounding box results in all points being in a smaller bounding sphere.

It certainly doesn't happen all the time - most of the time the naive shift increases the bounding sphere. I'm just curious as to why it sometimes fails though.

**Comment by mikedh** [comment]
Oh that's interesting. `minimum_nsphere` is using the `scipy.spatial.Voronoi` furthest site voronoi diagram of the convex hull of the point cloud. Allegedly, the minimum n- sphere lies on one of the vertices of that diagram, and our function is really just checking the output of that voronoi diagram.

Something interesting, I tried your data set with `scipy.optimize.minimize` to find the minball, and it didn't converge either. Not sure what the answer here is, but I think it involves numerical precision issues haha.

You might check out https://github.com/hbf/miniball as well.

**Comment by jackd** [comment]
Interesting. Not to worry, just thought it was worth checking out. Thanks again for the package :)
