### ISSUE TITLE
Obtain the corresponding 3D locations for a rendered mesh image

### ISSUE THREAD

**Issue by s0972456** [mikedh/trimesh#359]
I wonder if there is a quick way to obtain the 3D location of a pixel (corresponding to a point on the mesh while the point is not necessarily a vertice) in a rendered mesh image, assume that I obtained the rendered image using:
`scene = mesh.scene()`
`scene.set_camera(distance = 0.3, center = mesh.centroid)`
`file_name = 'rendered_images/' + meshname[:-4] + str(index) + '.png'`
`png = scene.save_image(resolution=[640, 480], visible=False)`

While I understand there is no singular 3D location for a pixel in the white region, there should be a 3D location for a pixel on the rendered mesh. I gave some thoughts on how to do that but I am still pretty confused ...

Any help will be greatly appreciated!

**Comment by mikedh** [comment]
Hey, I think the easiest way to do that is probably ray tests: https://github.com/mikedh/trimesh/blob/master/examples/raytrace.py
