### ISSUE TITLE
trimesh/ section.py

### ISSUE THREAD

**Issue by Hansalena** [mikedh/trimesh#36]
Hi Michael,
my name is Johann from Germany and I did found trimesh very interesting.
The main purpose is cutting a mesh with a plane.
Therefore I did tested section.py and it works well well also if I did cutted featuretype.STL also in the y or x direction changing the code 
 y_extents = mesh.bounds[:,1]
                      
       
    # slice every .125 model units (eg, inches)
    y_levels  = np.arange(*y_extents, step=0.25)
    print (y_levels)
    # create an array to hold the section objects
    sections  = [None] * len(y_levels)

    for i, y in enumerate(y_levels):
        print (i, y)
        # this will return a Path3D object, each of which will 
        # have curves in 3D space
        sections[i] = mesh.section(plane_origin = [0,y,0],                                                
                                   plane_normal = [0,1,0])

Everything is working fine until I did used a different mesh-file skinabdomen.STL ( body surface generated from dicom CT files)
The script is working for this file for the Z cut as described below:

 mesh = trimesh.load_mesh('/home/medinex/trimesh-master/models/skinabdomen.STL')
    #mesh = trimesh.load_mesh('/home/medinex/trimesh-master/models/featuretype.STL')
    mesh.show()
    print (mesh.bounding_box_oriented.primitive.extents)
    # we're going to slice the mesh into evenly spaced chunks along z
    # this takes the (2,3) bounding box and slices it into [minz, maxz]
    z_extents = mesh.bounds[:,2]
    
    # slice every .125 model units (eg, inches)
    z_levels  = np.arange(*z_extents, step=10)
    print (z_levels)
    # create an array to hold the section objects
    sections  = [None] * len(z_levels)

    for i, z in enumerate(z_levels):
        print (i,z)
        # this will return a Path3D object, each of which will 
        # have curves in 3D space
        sections[i] = mesh.section(plane_origin = [0,0,z],
                                   plane_normal = [-0.001,0,1])

In case of Y direction cut 
 mesh = trimesh.load_mesh('/home/medinex/trimesh-master/models/skinabdomen.STL')
    #mesh = trimesh.load_mesh('/home/medinex/trimesh-master/models/featuretype.STL')
    mesh.show()
    print (mesh.bounding_box_oriented.primitive.extents)
    # we're going to slice the mesh into evenly spaced chunks along z
    # this takes the (2,3) bounding box and slices it into [minz, maxz]
    y_extents = mesh.bounds[:,1]
  
   
    # slice every .125 model units (eg, inches)
    y_levels  = np.arange(*y_extents, step=30)
    print (y_levels)
    # create an array to hold the section objects
    sections = [None]*len(y_levels)
    print (len(y_levels))
    for j, y in enumerate(y_levels):
        print (j,y)
        # this will return a Path3D object, each of which will 
        # have curves in 3D space
        sections[j] = mesh.section(plane_origin = [0,y,0],
                                   plane_normal = [0,1,0])

The error is displayed:

Traceback (most recent call last):
  File "/home/medinex/trimesh-master/trimesh/section-skinabdomeny.py", line 43, in <module>
    plane_normal = [0,1,0])
  File "/usr/local/lib/python2.7/dist-packages/trimesh/base.py", line 998, in section
    raise ValueError('Specified plane doesn\'t intersect mesh!')
ValueError: Specified plane doesn't intersect mesh!

I looked to the base.py, trying to detect the error and I have seen that in your original code and your original line below it is :  from .io.load      import load_path
Should it maybe be : from .path.io.load import load_path because load path is only there.

   your code :    
        from .io.load      import load_path
        lines = intersections.mesh_plane(mesh = self, 
                                         plane_normal = plane_normal, 
                                         plane_origin = plane_origin)
        if len(lines) == 0:
            raise ValueError('Specified plane doesn\'t intersect mesh!')
        path = load_path(lines)
        return path
trying to detect the error. 

Please let me know if maybe you see a reason !!
The y direction cut is working without problem for the featuretype.STL file.

Do you have maybe a more detailed description how to use intersections.py  from trimesh ?
Thank you in advance 
Best regards
Johann

**Comment by mikedh** [comment]
Hey- the error you're getting is because the plane doesn't intersect the mesh. Rather than returning an empty Path3D object, a ValueError is raised. You can catch and ignore it by wrapping the section call in a try/except block:

```
    sections  = []

    for z in np.append(z_levels, 1000):
        # this will return a Path3D object, each of which will                    
        # have curves in 3D space                                                 
	try:
            sections.append(mesh.section(plane_origin = [0,0,z],
                                         plane_normal = [0,0,1]))
	except ValueError:
            print('Plane doesn\'t intersect mesh at {}'.format(z))

```

**Comment by Hansalena** [comment]
Dear Michael,

thank you so much !

section.py  works now for all the three direction ( x, y, z) .


I'm still in trouble to  use correctly *trimesh/intersections.py .
*

Do you have an example how to use intersections.py.

Thank you very much.

Best regards

Johann*
*

**


Johann Kindlein MSc

Dorfstr. 145 a
21365 Adendorf
Germany

Tel: +4941317572040
Fax: +4941317574293

Am 13.10.2016 um 02:47 schrieb Michael Dawson-Haggerty:

**Comment by mikedh** [comment]
Hey Johann, glad its working for you. trimesh.intersections is just the module where the actual function doing the cross section lives, so using that would be exactly the same as doing mesh.section. I'm going to update the example and close this for now.

**Comment by Hansalena** [comment]
Dear Michael,

please see attached the intersection lines for a anatomical surface.

The mesh lines at one intersection level are composed from multiple 
lines ( with the end points).

Could you please help still with one point.

How I can get access to the points ( endpoints ) of the multiple lines 
of a section.

I tryid different ways without success.

Thank you in advance.

Best regards

Johann



Johann Kindlein MSc

Dorfstr. 145 a
21365 Adendorf
Germany

Tel: +4941317572040
Fax: +4941317574293

Am 14.10.2016 um 04:48 schrieb Michael Dawson-Haggerty:
