### ISSUE TITLE
Mesh and primitive transform differently

### ISSUE THREAD

**Issue by s0972456** [mikedh/trimesh#361]
Hi Mike, 

I realize that the primitive and mesh transform differently using the apply_transform function (i.e., if I apply the same transform to a mesh and a primitive their relative position after the transform will change, while if I convert the primitive to a mesh via the to_mesh function and apply a transform to both of them, their relative position will remain the same)

I didn't see comments in the primitive class that this will happen. is this by design or could this be a bug in the code?

Thanks!

**Comment by mikedh** [comment]
Hey, yeah `apply_transform` has a different mechanism for primitive objects, but relative positions should stay the same given the same transform. Do you have a reproducible example you could send over?

As a quick check:
```
    p = trimesh.primitives.Cylinder()
    m = p.to_mesh()

    mat = np.dot(
        trimesh.transformations.random_rotation_matrix(),
        trimesh.transformations.translation_matrix(
            np.random.random(3)*10))

    p.apply_transform(mat)
    m.apply_transform(mat)
    print(np.array([
        p.center_mass,
        p.to_mesh().center_mass,
	m.center_mass]))
```
Outputs the same values, as expected:
```
[[ 4.74881  8.57582 -2.02437]
 [ 4.74881  8.57582 -2.02437]
 [ 4.74881  8.57582 -2.02437]]
```

**Comment by s0972456** [comment]
Hi Mike,

I tried various ways to reproduce the error (the original code is too long), and I cannot reproduce it with a simple case, I think it must be something wrong with my other part of code ...

If I later found out the cause of the issue and that's indeed related to trimesh, I will reopen the issue.

Thank you very much for your help!
