### ISSUE TITLE
How to save a mesh as an stl file in trimesh?

### ISSUE THREAD

**Issue by MohamadZohoori** [mikedh/trimesh#365]
Hi,

My question might be a bit simple but I haven't found a solution after searching the documentation.
I loaded a mesh and scaled it using trimesh library by the following codes:

import trimesh

mesh1 = trimesh.load_mesh('smoothed.stl')
mesh2 = trimesh.parent.Geometry.apply_scale(mesh1,1.1)

But I have no idea how to save mesh2 as an stl file... I have tried some codes of this library such as:

trimesh.exchange.stl.export_stl(mesh2)

but the I faced this Error:

  File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\exchange\stl.py", line 202, in export_stl
    header['face_count'] = len(mesh.faces)

AttributeError: 'NoneType' object has no attribute 'faces'

Please help me find the best way to save the mesh.

Thanks in advance for your help.

**Comment by mikedh** [comment]
Hey, I think you want:
```
mesh1 = trimesh.load_mesh('smoothed.stl')
mesh2 = mesh1.copy()
mesh2.apply_scale(1.1)
mesh2.export('stuff.stl')
```
`apply_scale` doesn't return a new mesh, rather it transforms the current mesh. If you use an `ipython` terminal, you can access the docstrings to see what arguments the various functions take:

```
mikedh@orbital:~$ ipython -i
Python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:10:56) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import trimesh

In [2]: mesh1 = trimesh.creation.box()

In [3]: mesh1
Out[3]: <trimesh.base.Trimesh at 0x7f41ef151a20>

In [4]: mesh1.apply_scale?
Signature: mesh1.apply_scale(scaling)
Docstring:
Scale the mesh equally on all axis.

Parameters
----------
scaling : float
  Scale factor to apply to the mesh
File:      ~/trimesh/trimesh/parent.py
Type:      method

In [5]: mesh1.export?
Signature: mesh1.export(file_obj=None, file_type=None, **kwargs)
Docstring:
Export the current mesh to a file object.
If file_obj is a filename, file will be written there.

Supported formats are stl, off, ply, collada, json, dict, glb,
dict64, msgpack.

Parameters
---------
file_obj: open writeable file object
  str, file name where to save the mesh
  None, if you would like this function to return the export blob
file_type: str
  Which file type to export as.
  If file name is passed this is not required
File:      ~/trimesh/trimesh/base.py
Type:      method

```

**Comment by MohamadZohoori** [comment]
Thanks, that worked pretty well !
