### ISSUE TITLE
Loading ply files 

### ISSUE THREAD

**Issue by KillianPremel** [mikedh/trimesh#374]
Hi, 
I try to load a ply file but it doesn't work : 
_KeyError: 'float64'_
I don't understand why it may cause an error.

Thanks in advance

**Comment by mikedh** [comment]
Ah, I guess some exporters have started adding fields with 64 bit floats. I added the additional data types, which should be released now. Also, if you have a file with this property you wouldn't mind sharing for unit tests it would be much appreciated!

Thanks for the report!

**Comment by KillianPremel** [comment]
Yes I create the ply file from a las file, using the librairy pdal ( https://pdal.io/stages/filters.poisson.html):
An exemple of this file is in this link : https://filex.mines-albi.fr/get?k=y4HlGpeZqtiZWu5sJXX

**Comment by mikedh** [comment]
Cool, that file loaded without issues. Unfortunately the file looks too large and proprietary to include in unit tests, but the issue is pretty straightforward and should be resolved.

Thanks for the report!
