### ISSUE TITLE
Why trimesh.scene.Camera.transform always return identity without scene?

### ISSUE THREAD

**Issue by wkentaro** [mikedh/trimesh#376]
I'm just wondering why. It doesn't use `self.transform` at all, right?

https://github.com/mikedh/trimesh/blob/f439e705957283ffea257dc00283c33562fb4220/trimesh/scene/cameras.py#L66

https://github.com/mikedh/trimesh/blob/f439e705957283ffea257dc00283c33562fb4220/trimesh/scene/cameras.py#L96-L132

The real problem is I can't use the camera object to use `trimesh.creation.camera_marker` without using a scene at the same time.

**Comment by mikedh** [comment]
Ah yeah, we should probably do a thing which allows it to be set without a scene. Does the logic in https://github.com/mikedh/trimesh/commit/745756dfa8d2cbc1c08850f1291a19ad43d2d312 look ok?

- if nothing set return identity
- if no scene reference, save transform to camera locally
- if scene reference set later, move the transform to the scene graph

**Comment by wkentaro** [comment]
Looks good thanks!
