### ISSUE TITLE
Vertex order not preserved by Wavefront loader？

### ISSUE THREAD

**Issue by tuqubao** [mikedh/trimesh#380]
import numpy as np
import trimesh
p = r'C:\Users\admin\Desktop\test\test_02.obj'
mesh = trimesh.load( p, process = False )
print(mesh.vertices)
the vertex order is not preserved. how to do that?
I has upgraded trimesh, with pip install --upgrade trimesh, the problem is still existe.
this is ouput:
[[-2.5 -2.5 2.5]
[-2.5 -2.5 2.5]
[-2.5 -2.5 2.5]
[ 2.5 -2.5 2.5]
[ 2.5 -2.5 2.5]
[ 2.5 -2.5 2.5]
[-2.5 2.5 2.5]
[-2.5 2.5 2.5]
[-2.5 2.5 2.5]
[ 2.5 2.5 2.5]
[ 2.5 2.5 2.5]
[ 2.5 2.5 2.5]
[-2.5 2.5 -2.5]
[-2.5 2.5 -2.5]
[-2.5 2.5 -2.5]
[ 2.5 2.5 -2.5]
[ 2.5 2.5 -2.5]
[ 2.5 2.5 -2.5]
[-2.5 -2.5 -2.5]
[-2.5 -2.5 -2.5]
[-2.5 -2.5 -2.5]
[ 2.5 -2.5 -2.5]
[ 2.5 -2.5 -2.5]
[ 2.5 -2.5 -2.5]]

the answer should be:
[[-2.5, -2.5, 2.5]
[2.5, -2.5, 2.5]
[-2.5, 2.5, 2.5]
[ 2.5, 2.5, 2.5]
[-2.5, 2.5, -2.5]
[ 2.5, 2.5, -2.5]
[-2.5, -2.5, -2.5]
[ 2.5, -2.5, -2.5]]
the number of vertex and order is wrong.
how to fix the problem?

**Comment by tuqubao** [comment]
the obj file is a cub make by maya. I see your test code, is work, but the obj too simple is't an good answer.

**Comment by tuqubao** [comment]
> 1. 
> 2. def test_obj_order():
> 3. 
> 4. 	"""
> 5. 	Make sure simple round trips through Wavefront don't
> 6. 	reorder vertices.
> 7. 	"""
> 8. 	# get a writeable temp file location
> 9. 
> 10. 	p = r'C:\Users\admin\Desktop\test\test_03.obj'
> 11. 
> 12. 	x = trimesh.creation.icosahedron()
> 13. 
> 14. 	x.export( p )
> 15. 
> 16. 	y = trimesh.load_mesh(p, process=False)
> 17. 
> 18. 	# vertices should be same shape and order
> 19. 
> 20. 	#assert np.allclose(x.vertices, y.vertices)
> 21. 
> 22. 	# faces should be same
> 23. 
> 24. 	#assert np.allclose(x.faces, y.faces)
> 25. 
> 26. 	#x.show()
> 27. 
> 28. 	#print(x.vertices)
> 29. 	#print(y.vertices)

this code from your test code. it seem work ok. but when I test a obj make from maya, will get a wrong answer.

**Comment by mikedh** [comment]
Hey, yeah this will hopefully (but not definitely, the OBJ implicit- vertex thing makes this hard to promise) will be addressed in the re- write.

**Comment by mikedh** [comment]
Consolidating into #391
