### ISSUE TITLE
Self-intersections

### ISSUE THREAD

**Issue by bbarroqueiro** [mikedh/trimesh#382]
Hi,

Any idea on i can detect Self-intersections and how to fix them?

Regards

**Comment by Marviel** [comment]
I've got more thoughts on the topic but there are some techniques discussed here that i've been itching to try out in numpy when I get the time:
https://arxiv.org/abs/1605.07829

**Comment by mikedh** [comment]
Oh, interesting paper. 

It's a pretty gnarly problem, probably the easiest thing to do is call `meshlab` or `meshmixer` with subprocess on a temp file. If you just need things to be watertight and are OK with a very rough solution, you could always use marching cubes:

```
import trimesh
import numpy as	np

if __name__ == '__main__':

    m = trimesh.creation.random_soup(100)

    points = m.sample(1000)
    pitch = m.extents.min() / 100

    origin = points.min(axis=0)
    index = ((points-origin) / pitch).round().astype(np.int64)

    matrix = trimesh.voxel.sparse_to_matrix(index)
    cubes = trimesh.voxel.matrix_to_marching_cubes(matrix, pitch, origin=[0,0,0])
```

**Comment by bbarroqueiro** [comment]
Hello... 
Thanks for the paper Luke...

Regarding the proposed solution doesn't work for me... I need precise and smooth solutions

**Comment by bbarroqueiro** [comment]
but meshlab might do the job or using some python bindings of CGAL or something... I don´t know yet...

**Comment by steersteer** [comment]
Did you ever find a solutution?

**Comment by Sea421** [comment]
Hi @bbarroqueiro ,
I am facing with same problem. Did you find the solution? If you get, please advice me.

Thanks

**Comment by bbarroqueiro** [comment]
@Sea421 during mesh smoothing some algorithms were generating mesh entanglement... so work i worked on the algorithm of smoothing in order to avoid it (mutable diffusion - i did a PR).

Regarding the self intersections, i stopped looking... Sorry for not proving much help...
