### ISSUE TITLE
mesh.copy() segfaults, can't deep copy rtree.index.Index??

### ISSUE THREAD

**Issue by payne92** [mikedh/trimesh#39]
The following code segfaults for me after 15-20 iterations:

```
import trimesh
from copy import deepcopy

mesh = trimesh.primitives.Sphere()
mesh.triangles_tree()

print type(mesh._cache.cache['_triangles_tree'])

for i in range(0,30):
    print i
    deepcopy(mesh)

print "done"
```

(This was distilled for a much larger failing example that was originally calling mesh.copy(), which is implemented with deepcopy()).

Because mesh.copy() breaks, so do all of the functions that depend on it for their implementation.

I suspect the problem is the rtree.index.Index object stored in the mesh cache in the slot '_triangles_tree' -- it doesn't look like it supports deepcopy.

Consider:  clearing the cache before copying (seems to work in a simple example), OR, to implement __copy__ / __deepcopy__ in the util.Cache object to do the right thing.

**Comment by mikedh** [comment]
Wow, the multiple copy operations sure exposes all sorts of exciting segfaults. After I added a unit test which demonstrates this behavior, I noticed the hard faulting was pretty platform specific and intermittent. In addition to the rtree I noticed some instances where the cached convex hull crashed it as well.

Anyway, I updated mesh.copy to only copy the mesh data and not the cache, and that appears to fix it (so maybe I *could* cache that freaking r-tree). 

Thanks for the report!

**Comment by payne92** [comment]
Yes, I suspect this is a Heisenbug -- under a deecopy(), somebody somewhere is smashing memory and the failure is totally dependent on context and stack. 

Thanks for the quick followup!   I'll take a look at your changes and report any problems.

**Comment by mikedh** [comment]
Heh yeah, caching those ctypes objects is a recipe for random pain. In additional testing + the unit test added in https://github.com/mikedh/trimesh/commit/b9ec0b11446dbd6bea91d1854e8ad3f406605529 I think this is "fixed" though feel free to re-open if you see it again.
