### ISSUE TITLE
OBJ Rewrite

### ISSUE THREAD

**Issue by mikedh** [mikedh/trimesh#391]
I've stalled a little bit on the OBJ rewrite due to other projects. It's decently close however, and if anyone is interested in working on it, it would be appreciated!

The [`feature/obj`](https://github.com/mikedh/trimesh/tree/feature/obj) branch includes a mostly fresh pass at an OBJ loader. In my testing on large files, it was roughly 3x faster than the previous loader. Most of the gains are from doing string preprocessing operations, and processing only relevant substrings as much as possible, through `str.find` and `str.rfind`, and then loading data with `np.fromstring`. For small meshes, it has basically the same performance as the old loader.

It also handles multiple textures by splitting at every `usemtl` or `o` tag, which become a *new mesh*, which the current loader doesn't handle well (or at all).

Developing
----------------
If you run `ipython -i obj.py` in the root directory, it will load, profile, and compare performance to the old loader, which hasn't been touched. When this is further along we'll jettison the old loader and replace it with `obj.py`. I recommend doing it on a large- ish mesh (as small meshes load so quickly they are dominated by things like PIL image loading). 

Scope
-------------
- [x] Load vertices (`v`)
- [x] Vertex colors (on the same line as `v`)
- [x] Vertex normals (`vn`)
- [x] Vertex texture coordinates (`vt`)
- [x] Triangular and quad faces
- [ ] Find an OBJ with mixed tri/quad to test against
- [x] Multiple materials
- [x] Multiple objects (`o`)
- [ ] Materials with color information but no image render in `viewer.windowed` (maybe these should be converted to `face_colors`?
- [ ] Keep track of face groups `g`
- [ ] Keep track of smoothing groups `s`
- [x] Useable kwargs 
- [x] Usable kwargs with texture

**Comment by mikedh** [comment]
Should address #332 #350 #380

**Comment by paulmelnikow** [comment]
Hi Mike, wanted to say this is an awesome project!

I've been maintaining [lace](https://github.com/metabolize/lace) which needs a rewrite, and a question I have is about your goals for trimesh, and how moving forward, they do / don't overlap with the goals for lace. It may make sense to combine forces with trimesh, or else get really clear about what needs to go in lacecore.

The OBJ rewrite task is something I might be interested in helping with, particularly if I can write it in a way that's portable!

Would you be up for a call sometime?

**Comment by tuqubao** [comment]
Hi Mike, current trimesh to load obj have problem, vertex order is miss,  do you rewrite one?https://github.com/mikedh/trimesh/issues/380

**Comment by mikedh** [comment]
Hey Paul, definitely! How about sometime tomorrow afternoon? My Skype username is `mik3dh`

**Comment by paulmelnikow** [comment]
Sounds great! How about 2 p.m.? I'm **paulmelnikow** on Skype.

**Comment by mikedh** [comment]
Sounds good! Talk to you tomorrow @ 2

**Comment by staubda** [comment]
@mikedh any progress/plans for this work? I tried out the `obj.py` script but wasn't able to successfully load the `kwargs` results into a `Trimesh`. From loading `fuze.obj`:

>/usr/local/lib/python3.7/site-packages/trimesh/grouping.py in merge_vertices(mesh, digits, textured, uv_digits)
     54         stacked = np.column_stack((
     55             mesh.vertices * (10 ** digits),
---> 56             mesh.visual.uv * (10 ** uv_digits))).round().astype(np.int64)
     57         # Merge vertices with identical positions and UVs
     58         # we don't merge vertices just based on position
>
> ValueError: all the input array dimensions except for the concatenation axis must match exactly

Looking into `kwargs` this happens because

`vertices.shape = (502, 3)`
while
`visual.uv.shape = (1000, 3)`

Would love to be able to use this cool library once the new obj loader is operational!

**Comment by mikedh** [comment]
Hey, I made a few updates yesterday to support textured meshes, including multiple objects and materials which actually was working pretty nicely. Still not ready for prime time but closer. 

`feature/obj` may be better than the one in `master` at this point, though there are still a few things that may induce complaints (no face or smoothing groups is probably the biggest remaining one).

**Comment by staubda** [comment]
Great! I'll pull the latest and give it a shot.

**Comment by staubda** [comment]
@mikedh Just tested the new loader, seems to be working! I do have an obj thats triggering the 

>     if True or trimesh.tol.strict:
>         assert np.allclose(v[faces], v[mask_v][new_faces])

check in `unmerge()`. Not sure if I have a corrupt file or there's a bug somewhere.

Also, quick question about visualization (sorry if this is the wrong place to ask). When I visualize in a jupyter notebook (using `scene.show(viewer=notebook)`) I'm seeing darker, blurrier looking textures than when I visualize in a pyglet window (happens with fuze.obj). However, sometimes when visualizing in a pyglet window the mesh has a bunch of holes that don't appear when I'm displaying in the notebook (doesn't happen with fuze, does happen with my own mesh objs). Any thoughts on why this would happen?

**Comment by mikedh** [comment]
Glad it's loading! Yeah if that assert is failing it's either a bug in that logic (extremely possible, it's fiddly index stuff) or a corrupt file- are you able to email me the file to take a look mikedh@kerfed.com?

With regards to the jupyter notebook viewer, it doesn't actually support texture at the moment as the [GLTF exporter the notebook viewer uses](https://github.com/mikedh/trimesh/blob/761713142331194ffbde80e5ffc842a652d801c8/trimesh/exchange/gltf.py#L489-L527) is converting texture to vertex color as a cheesy hack at the moment. PR's always welcome 😄! The pyglet viewer does use the actual materials: `mesh.show(viewer='gl')` should look better.

**Comment by staubda** [comment]
Ah gotcha, makes sense. Not sure why the holes are appearing when rendering with the pyglet viewer, seems to look ok using `pyrender`, although it's super slow and laggy. I think the `assert` getting triggered was actually a bug in my code (turning the `obj.py` script into a `load_obj` function).

**Comment by jackd** [comment]
@mikedh thanks for this, my models are looking great! Couple of things I picked up in testing:
* might want to throw `text = file_obj.read()` into `load_obj` - it currently doesn't use the `file_obj` passed in, but uses the global `text` instead.
* concatenating returned meshes fails when attempting to merge texture visuals. I tried replacing the offending `texture_visuals.concatenate` line with `visuals.concatenate` but this didn't resolve much...

Demo [here](https://gist.github.com/jackd/4fed392bb28621f9d8d18c36e4f9f423)

**Comment by mikedh** [comment]
Ah good catch, I fixed the file object thing to be closer to usable. Yeah textured visual concatenation is not implemented at all, the cheesy way to do it would be to convert them all to color (`visual.to_color`) in lieu of implementing texture concatenation.

There's still something wonky with UV normalization or something, but in general it's looking pretty decent! I'm still not sure the best way to do face group correlation (`\ng `) without it being incredibly slow.

**Comment by mikedh** [comment]
Moving conversation to the PR: #436
