### ISSUE TITLE
Run viewer in a thread

### ISSUE THREAD

**Issue by wkentaro** [mikedh/trimesh#392]
It seems the viewers in `trimesh` and `pyrender` have different strategy to change the scene object online. `trimesh` uses `pyglet.clock.schedule_interval` while `pyrender` uses `threading.Thread`.

For my experience, the approach of using `threading.Thread` seems more flexible.
For example, below is examples of `pyrender`, `trimesh` with callback, `trimesh` with `threading` (actually the last one doesn't work. maybe proper modification to `SceneViewer` is necessary).

```python
import threading
import time

import numpy as np
import trimesh
import trimesh.viewer
import pyglet
import pyrender


# use = 'pyrender'
# use = 'trimesh_callback'
use = 'trimesh_thread'

if use == 'pyrender':
    scene = pyrender.Scene()
    scene.add(
        pyrender.Mesh.from_trimesh(trimesh.creation.axis(0.01), smooth=False))
    viewer = pyrender.Viewer(
        scene, use_direct_lighting=True, run_in_thread=True)
    while viewer.is_active:
        with viewer.render_lock:
            geom = trimesh.creation.axis(0.01)
            geom.apply_translation(np.random.uniform(-0.3, 0.3, (3,)))
            scene.add(pyrender.Mesh.from_trimesh(geom, smooth=False))
        time.sleep(0.01)

if use == 'trimesh_callback':
    scene = trimesh.Scene()
    scene.add_geometry(trimesh.creation.axis(0.01))

    def callback(dt, viewer):
        geom = trimesh.creation.axis(0.01)
        geom.apply_translation(np.random.uniform(-0.3, 0.3, (3,)))
        scene.add_geometry(geom)

        viewer._update_vertex_list()
        viewer.on_resize(viewer.width, viewer.height)  # to adjust far

    viewer = trimesh.viewer.SceneViewer(scene, start_loop=False)
    pyglet.clock.schedule_interval(callback, 1. / 30, viewer)
    pyglet.app.run()

if use == 'trimesh_thread':
    scene = trimesh.Scene()
    scene.add_geometry(trimesh.creation.axis(0.01))

    viewer = trimesh.viewer.SceneViewer(scene, start_loop=False)
    thread = threading.Thread(target=pyglet.app.run)
    thread.start()

    while True:
        viewer.on_draw()
        time.sleep(0.01)
```

**`pyrender`**
![image](https://user-images.githubusercontent.com/4310419/56610930-880f8200-6608-11e9-902f-e7c5c7a4f573.png)

**`trimesh_callback`**
![image](https://user-images.githubusercontent.com/4310419/56610951-91005380-6608-11e9-8ebf-c20512101a77.png)

**`trimesh_thread`**
![image](https://user-images.githubusercontent.com/4310419/56610982-a2496000-6608-11e9-9471-1febf7744f46.png)

Do you have any idea what is the right way to go?
I think we can use `pyrender.Viewer` when needed (with `pyrender.Scene.from_trimesh_scene`), but I think it's worth to think about the design properly since `SceneWidget` will also have the same problem.

**Comment by wkentaro** [comment]
I've found that below works.

```
if use == 'trimesh_thread':
    scene = trimesh.Scene()
    scene.add_geometry(trimesh.creation.axis(0.01))

    thread = threading.Thread(
        target=trimesh.viewer.SceneViewer(scene, start_loop=True))
    thread.start()

    while True:
        time.sleep(0.01)
```

![image](https://user-images.githubusercontent.com/4310419/56611966-05d48d00-660b-11e9-8642-f45e5bf32dae.png)

**Comment by mikedh** [comment]
Oh interesting, I played around with windows in a thread a while back, and it was very finicky for reasons that weren't clear. The schedule_interval callback thing is definitely less flexible, but it does appear pretty reliable.

 [This thread](https://stackoverflow.com/questions/27071801/can-pyglet-run-in-new-thread) mentions threads and OpenGL interacting in "strange ways" haha.

**Comment by wkentaro** [comment]
I agree. I also played around a bit, but it was hard to use it stable.
