### ISSUE TITLE
Do boolean under windows

### ISSUE THREAD

**Issue by yw5aj** [mikedh/trimesh#40]
Hi Mike,

A quick question - I noticed that the backends of `blender` or `scad` are used for boolean operations. While it is trivial to install them in Linux, are you aware that whether there would be a way to get them working in windows?

Thanks!

Shawn

**Comment by mikedh** [comment]
Hey Shawn, I haven't actually tested booleans on windows, but the interface is using distutils.spawn.find_executable('blender'). I think that if you add blender to your windows PATH (control panel -> system -> advanced settings -> environment variables) it should be able to find it, you can check to see if trimesh.interfaces.blender.exist is True. If 'blender' from a cmd finds it it seems like distutils probably can too. 

I'm not sure if the windows version has the same command line options. I'll try verify it works then add it to the appveyor Windows tests at some point.

**Comment by yw5aj** [comment]
Thank you Mike for the quick reply!

I did try to add `C:\Program Files\Blender Foundation\Blender` to the path and in cmd if I do `where blender` it showed up; but still, when I try to do boolean, it says:

```python
  File "<ipython-input-5-3a440a9b7264>", line 1, in <module>
    cmesh = trimesh.boolean.union([tmesh, amesh], 'blender')

  File "C:\Anaconda3\envs\py34\lib\site-packages\trimesh\boolean.py", line 36, in union
    result = _engines[engine](meshes, operation='union')

  File "C:\Anaconda3\envs\py34\lib\site-packages\trimesh\interfaces\blender.py", line 14, in boolean
    raise ValueError('No blender available!')

ValueError: No blender available!
```

I'll dig into the code base a bit later. 

Thanks again!

Shawn

**Comment by mikedh** [comment]
Hey Shawn- amongst other things, I added some additional search paths in https://github.com/mikedh/trimesh/commit/954c9f09d4bd4fe5055ecfe5bb5b3bbf68c4399b, and boolean ops work for me in windows with it.

Best,
Mike

**Comment by yw5aj** [comment]
Hi Mike,

Thank you for your response!

I tried it, and initially it was still not working. I then checked my `_search_path` in `trimesh.interfaces.blender`, and it shows
```python
ipdb> _search_path
'C:\\Anaconda3\\envs\\py34\\Library\\bin;C:\\Anaconda3\\envs\\py34\\Library\\bin;C:\\Anaconda3\\envs\\py34;C:\\Anaconda3\\envs\\py34\\Library\\mingw-w64\\bin;C:\\Anaconda3\\envs\\py34\\Library\\usr\\bin;C:\\Anaconda3\\envs\\py34\\Library\\bin;C:\\Anaconda3\\envs\\py34\\Scripts;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\SIMULIA\\Commands;C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Git\\cmd;C:\\Program Files (x86)\\GitExtensions\\;C:\\Program Files\\MATLAB\\R2016b\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\MATLAB\\MATLAB Compiler Runtime\\v82\\runtime\\win64;C:\\SIMULIA\\Abaqus\\Commands;C:\\Program Files\\MATLAB\\R2013b\\bin;C:\\WINDOWS\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Anaconda3;C:\\Anaconda3\\Scripts;C:\\Anaconda3\\Library\\bin;C:\\cygwin64\\bin;C:\\cygwin64\\lib;C:\\Users\\shwang\\AppData\\Local\\atom\\bin;C:\\Program Files\\Blender Foundation\\BlenderC:\\Program Files\\Blender Foundation\\Blender;C:\\Program Files (x86)\\Blender Foundation\\Blender;'
```

Notice that it has:
```
;C:\\Program Files\\Blender Foundation\\BlenderC:\\Program Files\\Blender Foundation\\Blender;
```

So when appending the search path, it is missing a ';'. 

A quick and dirty fix that I did is to change https://github.com/mikedh/trimesh/blob/master/trimesh/interfaces/blender.py#L11

to

```python
    _search_path += ';C:\Program Files\Blender Foundation\Blender;'
```

This might be dirty... I'd be interested in knowing a neater way :)

**Comment by mikedh** [comment]
Ah my bad, thanks for the find! I fixed the search path issue in https://github.com/mikedh/trimesh/commit/423cca9a05cb2ce6fd999794e91db579a8497178 and added blender to the windows appveyor tests in https://github.com/mikedh/trimesh/commit/8d11d815abff847218bc3d323a5ade73e876abf0, which should yell at me if it breaks again.

**Comment by mikedh** [comment]
Oh as to the returning a Trimesh object, if you use the `mesh.union(other)` member function instead of `trimesh.boolean.union` you'll get a Trimesh object (function in [base](https://github.com/mikedh/trimesh/blob/954c9f09d4bd4fe5055ecfe5bb5b3bbf68c4399b/trimesh/base.py#L1397-L1411)).

**Comment by yw5aj** [comment]
@mikedh Great! Thank you so much. And thanks for having the split-and-join method  - it is nice and clean! :)
