### ISSUE TITLE
Convex decomposition CalledProcessError

### ISSUE THREAD

**Issue by frk1993** [mikedh/trimesh#409]
Hello,
I get following trimesh ERROR: problem with convex decomposition, using hull
Traceback. And it is defined as CalledProccessError (see attached screenshot), I get also a qhull warning Maybe someone can help further.

<img width="1140" alt="Bildschirmfoto 2019-05-01 um 23 48 36" src="https://user-images.githubusercontent.com/45715708/57044738-db6a7b80-6c6b-11e9-9a77-707f26dc8842.png">

<img width="900" alt="Bildschirmfoto 2019-05-02 um 00 01 48" src="https://user-images.githubusercontent.com/45715708/57045333-8d567780-6c6d-11e9-90b0-9d54c454cca5.png">

Best Regards

**Comment by mikedh** [comment]
Not to read too much in to the traceback, but it looks like it's trying to take a convex decomposition / convex hull of a plane? If that's the case, a plane has no volume, so both attempts to generate a convex volume would fail.

**Comment by frk1993** [comment]
Exactly you are right, its a plane. I am using following code: https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/master/tools/generate_mask_dataset.py

They had also no idea about this error.
Whats about the qhull error:```
 qhull input error: 2'th dimension's new bounds [-0.5, 0.5] too wide for
existing bounds [ 0,  0]

```

**Comment by mikedh** [comment]
Probably the easiest thing to do would be to represent planes as thin boxes, or to skip meshes where `mesh.is_volume` isn't true.

**Comment by mikedh** [comment]
Closing for now- PR's addressing this in a more general way are definitely welcome too!
