### ISSUE TITLE
Decimate a mesh

### ISSUE THREAD

**Issue by yw5aj** [mikedh/trimesh#41]
Hi Mike,

(I assume this would be a simple question :)

Would there be any simple way to decimate a mesh? Say, simplify the geometry from 10,000 faces to 1,000 faces?

Thanks!

Shawn

**Comment by mikedh** [comment]
Hey Shawn- at the moment Trimesh doesn't implement any simplification algorithms- I've been meaning to implement [quadratic edge collapse decimation](http://www-inst.cs.berkeley.edu/~cs283/sp12/lectures/06-MeshSimplification.pdf) for a while, but never had time. If you want to implement it PR's would be accepted gladly :). In the meantime you're probably best off calling meshlabserver with subprocess.check_call or something.

**Comment by yw5aj** [comment]
Hi Mike,

Thanks for your response! And the quadratic edge collapse decimation looks really interesting. I'll read more into it - I'm not sure whether the complexity is within my coding capabilities :P

And thank you also for your suggestion to use meshlabserver! I noticed that blender also has a decimate modifier, so I can try to see whether that's callable via command line. 

Shawn

**Comment by Marviel** [comment]
This code sample looks like it does the meshlabserver trick: https://gist.github.com/awesomebytes/a3bc8729d0c1d0a9499172b9a77d2622

**Comment by mikedh** [comment]
It would be neat to make a nice cython wrapper then set up cibuildwheel on: https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification

**Comment by xuefeng7** [comment]
thanks for the information, one question is: is there anyway to keep track of which faces are merged into one face? like if you have a labeled mesh, after decimating, how could you know the label for each new face？
Thanks!

**Comment by mikedh** [comment]
@xuefeng7: I think that would be pretty easy in a native numpy implementation but might be tough with a wrapper. 

I referenced and consolidated this into the enhancements list and would be as always mega- happy if someone wants to PR this 😄 . Thanks for the report!

**Comment by jonnymaserati** [comment]
I'm doing this via open3d pretty simply, I can pass on that code if it helps?

**Comment by mikedh** [comment]
Oh yeah actually the `open3d` implementation of this is pretty good, and they appear to be distributing through wheels now. I added a thin wrapper to open3d in https://github.com/mikedh/trimesh/pull/1015/commits/8b9daf22520aad0c04dd88a60da5b1f36910cc0d that seems to work well.
