### ISSUE TITLE
How to make STL from X Y Z coordinates with Vertex -- faces from Trimesh?How to generate 3dFaces automatically from Vertex[ x y z]? for STL Creation ?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#417]
How to make STL from X Y Z coordinates with Vertex -- faces from Trimesh?How to generate 3dFaces automatically from Vertex[ x y z]? for STL Creation ?

**Comment by mikedh** [comment]
Triangulating 3D points isn't a particularly well defined problem, but the easiest way to get "some" faces would be to take the convex hull of the points;

```
In [1]: import trimesh
 
In [2]: import numpy as np

In [3]: points = np.random.random((100, 3))

In [4]: hull = trimesh.convex.convex_hull(points)

In [5]: hull
Out[5]: <trimesh.base.Trimesh at 0x7f4646825780>

In [6]: hull.show()
Out[6]: SceneViewer(width=900, height=675)

In [7]: hull.export('hull.stl')

```

**Comment by selvakarna** [comment]
Thanks mikedh, i will update you...

**Comment by selvakarna** [comment]
Hi mikedh... I Got STL. but shape is not perfect, its totally different. here i have share input dicom 3d view and trimesh output hull STL view..

**Comment by selvakarna** [comment]
Input Pelvis my 3D image:

/home/hp/Desktop/selva/SK_QUIR/Pelvis_image.png

Trimesh ouput Hull-STL View:

/home/hp/Desktop/selva/SK_QUIR/Pelvis_hull.png

**Comment by selvakarna** [comment]
Hi mikedh, here i have share trimesh result please check ?

Input Dicom Image:
https://github.com/selvakarna/HULL-STL/blob/master/Pelvis_image.png

Hull STL view from Trimesh:

https://github.com/selvakarna/HULL-STL/blob/master/Pelvis_hull.png

@mikedh

**Comment by selvakarna** [comment]
how to get perfect shape  from trimesh hull -stl? @mikedh

**Comment by mikedh** [comment]
Hey, you're never going to get a "perfect" triangulation, as a point cloud is not a mesh. The convex hull is the bounding volume of the points, you can get closer something like [marching cubes](https://en.wikipedia.org/wiki/Marching_cubes). If you `pip install --upgrade scikit-image trimesh` you can use the helper method I just added:

```
    # get some points on an icosahedron
    points = trimesh.creation.icosahedron().sample(10000)

    # the pitch is the size of a discrete chunk, here we're making it scale relevant
    pitch = points.ptp(axis=0).min() / 10

    # run marching cubes to create a mesh
    m = trimesh.voxel.points_to_marching_cubes(points, pitch=pitch)
```

**Comment by selvakarna** [comment]
@mikedh , i will check and apply.
