### ISSUE TITLE
How to get smooth STL results from Trimesh? which components,need to  tuning part for STL smoothed results?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#425]
How to get smooth STL results from Trimesh? which components need to  tuning part STL smoothed results? @mikedh

**Comment by mikedh** [comment]
Hey, there are two kinds of 'smoothing' in trimesh:

- smooth shading from `mesh.smooth()`, which doesn't move any vertices but may merge vertices so OpenGL shades it nicely.
- [trimesh.smoothing](https://github.com/mikedh/trimesh/blob/master/trimesh/smoothing.py) which runs actual filters on the mesh, moving vertices.

Note that STL files don't reference vertices by index, so only the second kind will have any effect.

**Comment by selvakarna** [comment]
Okay thanks @mikedh .

**Comment by selvakarna** [comment]
Hi @mikedh , i have Error ,while convert smoothed STL from Trimesh. 

Error was:
'Trimesh' object has no attribute 'mesh'
