### ISSUE TITLE
Parsing '.mtl' files with multiple materials or a material with no `map_Kd` fails inelegantly

### ISSUE THREAD

**Issue by jackd** [mikedh/trimesh#428]
Missing `map_Kd` references cause issues with the obj loader. I'm not a graphics person and I'm not very familiar with .obj format, so it's entirely possible I'm working with malformed `.mtl` files - but other tools (meshlab, blender) achieve somewhat satisfactory results on the same files, so I imagine a more graceful fallback in situations like this is at least possible, and if not a more helpful error message would be great.

Demo [here](https://gist.github.com/jackd/4fed392bb28621f9d8d18c36e4f9f423). The problem seems to stem from `filename==None` [here](https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/wavefront.py#L167).

Awesome project though - looking forward to getting rid of my blender dependencies.

**Comment by jackd** [comment]
Did some more digging and I suspect the issue might actually be related to [this](https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/wavefront.py#L174): `loaded['visuals']` are overwritten for each material, meaning the vertex update fails for multi-material meshes and results in all visuals being popped. Is there a way to concatenate `TextureVisuals`?

**Comment by mikedh** [comment]
Yeah, this is not handled well at the moment, although it is likely the moderately stalled [obj rewrite](https://github.com/mikedh/trimesh/issues/391) would help with this. 

Right now there is no way of concatenating `TextureVisuals`, although using [`pack_rectangles`](https://github.com/mikedh/trimesh/blob/f42f7a6c4838e9d18815028718acff070c275866/trimesh/path/packing.py#L125-L175) to combine a bunch of images into one large texture would be pretty straightforward to implement and cool to have.

**Comment by jackd** [comment]
Ah - I'd seen that branch but was still looking at `wavefront.py`, my bad. I had a stab packing rectangles, and while creating the packed image isn't hard from what I can tell `vt`s themselves aren't associated with a particular material in `obj`s, so that would have to be tracked in face lines... and I'm currently so deep in a rabbit hole I think I'm going to find an easier work-around. I might come back to this if I get a chance in the future (but I won't be upset if somebody else beats me to it....)

Packing code is below if you/anyone decides it's useful.

```python
def pack_texture_visuals(*textures):
    # NOTE: uv are (x, y) ordered while images are (y, x) ordered
    from PIL import Image
    if len(textures) == 0:
        return None
    elif len(textures) == 1:
        return textures[0]

    def fix_tiling(image, diffuse, uv):
        # UVs outside the range [0, 1] imply tiling
        # https://gamedev.stackexchange.com/questions/148594/how-to-deal-with-texture-coordinates-without-range
        uv = uv[:, :2].copy()  # ignore w channel...
        minv = np.min(uv, axis=0)
        lower = np.floor(minv)
        uv -= lower
        maxv = np.max(uv, axis=0)
        repeats = np.ceil(maxv)
        mask = repeats != 0
        uv[:, mask] /= repeats[mask]
        if image is None:
            # create a dummy image
            image = np.reshape(diffuse, (1, 1, -1))
        else:
            repeats = tuple(repeats.astype(np.int32)[2::-1]) + (1,)
            image = np.tile(image, repeats)
        return image, uv

    images, uvs = zip(*(
        fix_tiling(t.material.image, t.material.diffuse, t.uv)
        for t in textures))
    rectangles = [image.shape[:2] for image in images]
    rectangles = np.array(rectangles)
    sheet_size = np.sum(rectangles, axis=0)  # max possible size
    _, offset, inserted, consumed_box = packing.pack_rectangles(
        rectangles, sheet_size, shuffle=False)
    consumed_box = np.ceil(consumed_box).astype(np.int32)
    offset = offset.astype(np.int32)
    assert(all(inserted))
    out_image = np.zeros(tuple(consumed_box) + (3,), dtype=np.uint8)
    out_uv = []
    for image, rect, uv, off in zip(images, rectangles, uvs, offset):
        uv *= rect[-1::-1]
        uv += off[-1::-1]
        uv /= consumed_box[-1::-1]
        out_uv.append(uv)
        y, x = off
        dy, dx = rect
        out_image[y:y+dy, x:x+dx] = image
    out_uv = np.concatenate(out_uv, axis=0)
    out_uv = np.concatenate([out_uv, np.ones_like(out_uv[:, :1])], axis=-1)  # add in w channel
    out_image = Image.fromarray(out_image)
    return TextureVisuals(uv=out_uv, image=out_image)
```
