### ISSUE TITLE
Problem with mesh.show()

### ISSUE THREAD

**Issue by MichalisLazarou** [mikedh/trimesh#429]
Hey,

I am kind of new to 3Dmeshes but I am trying to run the python jupyter quick_start and it seems to be working perfectly except instruction mesh.show(). When the command mesh.show() is issued the only thing that is seen is a large blank space under the instruction in jupyter notebook where it was supposed to be the 3D object. I am trying for the last week to understand what is causing it but I don't seem to manage, also pyglet library seems to be working fine with it. 

Regards,
Michalis

**Comment by mikedh** [comment]
Couple quick things to try:
- try to non-inline viewer `scene.show(viewer='gl')`
- check the web console in your browser to see if anything obvious is wrong
- see if the mesh actually loaded anything by printing `mesh.faces.shape`, also check to see if `mesh.bounds` is super large or super small

**Comment by mikedh** [comment]
It's also very possible the mesh is out of view of the camera. Closing for now, feel free to re-open if you have more information.

**Comment by MichalisLazarou** [comment]
Hey sorry again to bother, I get some issues that i don't really understand for example when I simply just run this code:


inputmesh = trimesh.load('whateverfile.obj')
inputmesh.show(viewer='gl') (if I run just show() it does not show anything)

I get a white blank window, saying not-responding and basically the code fails. Now I was wondering since I am having a lot of trouble with the graphics libraries as well such as pyrender, could this be because I use windows?

**Comment by mikedh** [comment]
Hey, it sounds like your machine is having trouble creating an OpenGL context, you might try running some tools like [dxdiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) and see if there's anything obvious going on with your graphics drivers, OpenGL, etc. Can you play 3D games using OpenGL on your machine? In general things should work on Windows, but it is likely to be a bit finicky.

**Comment by MichalisLazarou** [comment]
I am pretty new to openGL so i do not know very well the problems behind it. However what I come to realize is there is something that is not compatible with the specific meshes we use in the lab and my PC. I get this error and I am not sure why it arises, for other meshes that I do not get it they can be viewed properly.

SVG path loading unavailable!
Traceback (most recent call last):
  File "C:\Users\Michalis\Anaconda3\envs\tf\lib\site-packages\trimesh\path\exchange\svg_io.py", line 18, in <module>
    from svg.path import parse_path
ModuleNotFoundError: No module named 'svg'

**Comment by mikedh** [comment]
Hey, I think you're missing a dependency. You can get it with `pip install trimesh[easy]` or `pip install svg.path`

**Comment by MichalisLazarou** [comment]
Hey, thanks for the help I do not get any errors now but still the mesh does not look normal. First it taks a couple of minutes for a blank window to load and then after zooming in you can see a mesh but not looking right. I am really sorry to keep bothering if you have no idea what might be causing this then let's try and keep it here perhaps is a problem with my PC.
 
![meshlabMesh](https://user-images.githubusercontent.com/20433890/58663375-46b77400-8324-11e9-8d92-de4f8b22b0e9.JPG)
![meshwrong](https://user-images.githubusercontent.com/20433890/58663423-62227f00-8324-11e9-88c6-e851f95dd0a8.JPG)

**Comment by MichalisLazarou** [comment]
so as you see in the second mesh the texture seems all wrong and by zooming in and out parts of the mesh disappear
