### ISSUE TITLE
do you know what layers polygons are from when loading DXF?

### ISSUE THREAD

**Issue by rmamba** [mikedh/trimesh#43]
If you load dxf file that has objects on different layers.
When loaded, do you know what layer it came from?

**Comment by mikedh** [comment]
Sure, I added the layer info to metadata in https://github.com/mikedh/trimesh/commit/a9d0785d14b0b22ccf47f02a8f5af7004e7c291e

Example:
```
In [1]: import trimesh

In [2]: p = trimesh.load('models/2D/125_cycloidal.DXF')

In [3]: p.metadata
Out[3]: 
{'file_name': '125_cycloidal.DXF',
 'file_path': 'models/2D/125_cycloidal.DXF',
 'layers': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'units': 'inches'}

In [4]: len(p.entities)
Out[4]: 46

In [5]: len(p.metadata['layers'])
Out[5]: 46
```

**Comment by rmamba** [comment]
@mikedh this is great!

But when I get a list of polygons_full I still don't know what layer it came from. 

What I'm trying to do is go through objects on layers and extrude them. Once I have meshes from objects I can do boolean operations on them. For example I have an object on layer `0`, but I have holes on layer `holes`. So I can union all the holes and substract them from primary solid.

After that I will save it into an STL file.

I'm doing this because I have a DXF plans for 3D printer and I'm trying to automate the process of generating 3D model parts to check how they fit together :)

**Comment by mikedh** [comment]
Ah gotcha. Only thing thats tricky is polygons_full consists of multiple entities which can be on different layers- you could grab the layer name of all entities in the 'shell' of each item in polygons_full, and then either take the first one, or do a check to see if they're all the same, or something.

Example:

```
In [1]: import trimesh

In [2]: p = trimesh.load('models/2D/wrench.dxf')

In [3]: p.root
Out[3]: [0]

In [4]: p.polygons_full
Out[4]: [<shapely.geometry.polygon.Polygon at 0x7f44050fdf28>]

In [5]: p.paths
Out[5]: 
array([ array([ 2, 14,  1,  0, 38, 35, 36, 37,  6,  7, 18, 17, 19,  8,  9, 16, 10,
       11, 12,  5,  4, 15,  3]),
       array([13, 20, 21, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22])], dtype=object)

In [6]: p.paths?
Type:        property
String form: <property object at 0x7f4406cba048>
Docstring:  
Sequence of closed paths, encoded by entity index.

Returns
---------
paths: (n,) sequence of (*,) int referencing self.entities 

In [7]: layers = [p.metadata['layers'][p.paths[root]] for root in p.root]

In [8]: layers
Out[8]: 
[array(['SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)', 'SKETCHGEOMETRY(ANSI)',
        'SKETCHGEOMETRY(ANSI)'], 
       dtype='<U20')]
```

**Comment by Mambix** [comment]
@mikedh Thanks for looking into this!!!

I'm making progress. So what I did is this:
```Python
paths = [dxf.paths[root] for root in dxf.root]
layers = [dxf.metadata['layers'][dxf.paths[root]] for root in dxf.root]
```

When I go through paths I can construct Path2D objects, which is great, because now I know what layer they belong too. And I can extrude them and then do boolean operations on them.

But what I noticed is that on one layer I have a single closed polyline which is not in the results.

My DXF drawn with dxf.show() once opened with trimesh:
![image](https://cloud.githubusercontent.com/assets/6792150/23342932/fb5d78b2-fc5a-11e6-9167-9abf414b0b65.png)

Notice top left there is an error in geometry, because in my DXF it looks like this:
![image](https://cloud.githubusercontent.com/assets/6792150/23342943/255f4636-fc5b-11e6-9c75-99431461bf97.png)

Could this be the reason why it's not present in results?
[my DXF](https://s3-eu-west-1.amazonaws.com/backup.red-mamba.com/6mm_les_izrez_dol+-+LM8UU.dxf)

**Comment by mikedh** [comment]
NP, looks like your getting closer! That particular DXF exposed a dopey bug in Path objects- try https://github.com/mikedh/trimesh/commit/3e10bc2ac9909da82c9b0f167fa915d68ccc3bfa

**Comment by Mambix** [comment]
I see that the polyline has two paths at that position. So now it works but if prints warning in the console.

However if I remove second path and create polyline again and run my script it again does not return the line from IZREZ layer. And now the segment is missing in the view too.

![image](https://cloud.githubusercontent.com/assets/6792150/23354167/c4be62e0-fcc7-11e6-9746-42b1e5dfec3b.png)

**Comment by Mambix** [comment]
I UL a second dxf which does not give any warning of double paths. But still ignores the polyline from IZREZ layer.

[DXF2](https://s3-eu-west-1.amazonaws.com/backup.red-mamba.com/6mm_les_izrez_gor+-+LM8UU.dxf)

**Comment by mikedh** [comment]
Cool- I think 90% of the problem with that file was that polylines didn't support the 'closed' flag (which I added support for in https://github.com/mikedh/trimesh/commit/52ff20b5c78ab526983eec3c27cc532e04af2ef4). 

So now DXF2 shows up with everything closed (no gaps). It does however turn the slots into square holes, as they use the 'bulge' flag which apparently indicates an arc. I may add support for this in the future, but not now (though PR's are welcome!). 

If your still having problems, I also added an 'explode' method for paths (which decomposes a path containing multi-segment entities into a bunch of single- segment entities) and the 'fill_gaps' method which looks for dangling (degree 1, a vertex only contained in one entity) vertices and tries to connect it with other nearby dangling vertices.

I also added your DXF2 to the unit tests, it has all the weird polyline flags imaginable haha. Thanks for the report!

**Comment by Mambix** [comment]
@mikedh if you point me to the file where the bulge logic needs to be implemented I'm happy to do it as I need it :)

**Comment by Mambix** [comment]
@mikedh think you have bug. Now I only get one layer back. Everything else is ignored. and dxf.root only returns one record. I'll have a look and will try to fix it on my own. I'll create a PR once I have it fixed.

**Comment by mikedh** [comment]
Interesting, can you send over a code block that demonstrates the layer behavior so I can look at it tonight? I definitely got multiple layers on both of the DXF's you sent, but will add it to the unit tests to make sure.

Supporting bulge would be great! The feature would go here: https://github.com/mikedh/trimesh/blob/master/trimesh/path/io/dxf_load.py#L105-L110

It would ideally just add multiple Line and Arc entities in that function. You may have to also modify multi_dict to remember the overall insertion order (as they weave the bulge flag in between vertices).

**Comment by Mambix** [comment]
```Python
import trimesh

dxf = trimesh.load('../dxf/blocks/6mm_les_izrez_dol - LM8UU.dxf')
# print dxf.metadata
print len(dxf.vertices)
print len(dxf.entities)
print len(dxf.root)
print len(dxf.paths)

paths = [dxf.paths[root] for root in dxf.root]
layers = [dxf.metadata['layers'][dxf.paths[root]] for root in dxf.root]
print layers
print paths

elements = {}

for i in range(0, len(paths)):
    E = []
    lay = layers[i][0]
    if lay not in elements:
        elements[lay] = []
    for e in paths[i]:
        E.append(dxf.entities[e])
    p = trimesh.path.path.Path2D(entities = E, vertices=dxf.vertices)
    elements[lay].append(p)
    # p.show()

print elements.keys()
# elements['GRAVIRANJE'][0].show()
dxf.show()
```

Results:
```
817
197
2
138
[array(['IZREZ'], 
      dtype='|S10'), array(['GRAVIRANJE', 'GRAVIRANJE', 'GRAVIRANJE', 'GRAVIRANJE'], 
      dtype='|S10')]
[array([196]), array([15, 16, 17, 14])]
['GRAVIRANJE', 'IZREZ']

Process finished with exit code 0
```

Note only two root objects. One on IZREZ layer and only one large box on GRAVIRANJE layer.

**Comment by mikedh** [comment]
Hey- I don't think you want to split by the connected components of root objects as you are then making a whole bunch of assumptions which aren't true. The root objects only make sense if the drawing is sane, no overlaps, etc. I think you want to split by layer first. Layers appear correctly for me in both 2.7 and 3.x.

Try doing:
```
import numpy as np
import collections
import copy

if __name__ == '__main__':
    dxf = trimesh.load('LM8UU.dxf')

    split = collections.deque()
    for layer in np.unique(dxf.metadata['layers']):
        print('splitting layer {}'.format(layer))
        entities = copy.deepcopy(dxf.entities[dxf.metadata['layers'] == layer])
        split.append(trimesh.path.Path2D(entities=entities,
                                         vertices=dxf.vertices.copy()))
```

Which outputs:

```
splitting layer GRAVIRANJE
splitting layer HOLES
splitting layer IZREZ

In [1]: split
Out[1]: 
deque([<trimesh.path.path.Path2D at 0x7f5a79783ac8>,
       <trimesh.path.path.Path2D at 0x7f5a79771668>,
       <trimesh.path.path.Path2D at 0x7f5a797716d8>])

```

**Comment by dlednik** [comment]
exactly what I need 👍

**Comment by mikedh** [comment]
Great, glad its working for you.
