### ISSUE TITLE
Loader does not load texture images?

### ISSUE THREAD

**Issue by YLJALDC** [mikedh/trimesh#431]
It seems like the mesh.load() method fails to load .obj with texture images. It gives the following image when I delete all meshes in the obj file but the one with texture image (map_Kd ../images/some_texture.png in the mtl file). It is noticeable that this error only reports the first mesh if there is a mesh with texture image at all. I.e. material_5_24 does not have the texture image but the following one does. I am leaving only two meshes here to show the error. If only the actual mesh with texture image is present, then there is no error.

![Capture](https://user-images.githubusercontent.com/28548224/57876817-2687a100-77cb-11e9-8407-6f3594edb9dd.PNG)

Did I do something wrong or this feature is not supported? Thanks!

**Comment by mikedh** [comment]
Ah could you send me the file to look at? Does the file open successfully in meshlab?

**Comment by YLJALDC** [comment]
Yes, I just tried and it opens in meshlab. Should I send it to you via email?

**Comment by YLJALDC** [comment]
Or should I do different things instead of just using trimesh.load() to load obj with multuple texture images?

**Comment by mikedh** [comment]
Yeah feel free to email it to me, mikedh@kerfed.com

**Comment by massimo-tech3d** [comment]
I'd like to add a related issue. When opening a textured obj file, with a single texture, it loads fine but calling  mesh.show() (with or without viewer='gl') it initially opens a black windows and eventually crashes with the following stack trace:

Traceback (most recent call last):
  File "./prova.py", line 45, in <module>
    mesh.show(viewer='gl')
  File "/home/max/.virtualenvs/mesh/local/lib/python2.7/site-packages/trimesh/base.py", line 2317, in show
    return scene.show(**kwargs)
  File "/home/max/.virtualenvs/mesh/local/lib/python2.7/site-packages/trimesh/scene/scene.py", line 882, in show
    return SceneViewer(self, **kwargs)
  File "/home/max/.virtualenvs/mesh/local/lib/python2.7/site-packages/trimesh/viewer/windowed.py", line 131, in __init__
    self._update_vertex_list()
  File "/home/max/.virtualenvs/mesh/local/lib/python2.7/site-packages/trimesh/viewer/windowed.py", line 163, in _update_vertex_list
    smooth=bool(self._smooth))
  File "/home/max/.virtualenvs/mesh/local/lib/python2.7/site-packages/trimesh/viewer/windowed.py", line 198, in add_geometry
    tex = rendering.material_to_texture(geometry.visual.material)
  File "/home/max/.virtualenvs/mesh/local/lib/python2.7/site-packages/trimesh/rendering.py", line 282, in material_to_texture
    with util.BytesIO() as f:
AttributeError: StringIO instance has no attribute '__exit__'

this is somewhat related to the OP but is a different issue than the OP. Do you prefer I open a brand new issue ?

great library, by the way :-)

**Comment by massimo-tech3d** [comment]
Hi, this "StringIO instance has no attribute 'exit'" only occurs with python2. with python3 the textured mesh is shown with no errors

**Comment by mikedh** [comment]
@massimo-tech3d yeah that Python 2 issue should be resolved and tested in https://github.com/mikedh/trimesh/commit/4c9ab1e9906acaece421fb189437c8f4947a9c5a

I have `feature/obj` loading the mesh from @YLJALDC pretty nicely so I'm going to consolidate this yet again into #391 :smile:. Hopefully we can get that merged in the next month or two.
