### ISSUE TITLE
DecompressionBombWarning by PIL while loading .obj with many vertices?

### ISSUE THREAD

**Issue by xiumingzhang** [mikedh/trimesh#432]
Thanks for the great project!

Recently, I was thrown the PIL's `DecompressionBombWarning` while loading a .obj model with many vertices.
```
import trimesh as tm

model = tm.exchange.load.load(in_f)

/Anaconda3-4.3.1-Linux-x86_64/envs/myenv/lib/python3.6/site-packages/PIL/Image.py:2546: DecompressionBombWarning: Image size (169869312 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
```

Wondering what might be the cause, and if there's a simple way to fix this?

Thanks!

**Comment by mikedh** [comment]
Is it referencing a giant texture image maybe? 169869312 pixels is only ~13000x13000. You might be able to resize the image if that is the case.

**Comment by xiumingzhang** [comment]
Ah, spot on! I was fixated on the model itself and forgot it was referencing a large texture map. Closing. Thanks Mike!
