### ISSUE TITLE
Any way to reserve mesh correspondence?

### ISSUE THREAD

**Issue by soaroc** [mikedh/trimesh#435]
I have two models (.obj type), and one is deformed from other without violating vertex connections. I need to obtain the vertex-wise displacement between the two models. When I loaded two models, and found faces of the two models are not the same. 

The mesh_loader may have optimizations on mesh. Could i skip the operations to keep the  topology (index and face orders) unchanged?

**Comment by mikedh** [comment]
As a first pass I'd try loading the mesh with `trimesh.load(file_name, process=False)`, which will skip the initial vertex merging. OBJ has a vertex referencing scheme which makes this a little unreliable, PLY or STL would probably be more consistent.

**Comment by soaroc** [comment]
Thank you. It works for me.

**Comment by soaroc** [comment]
Hi, I'm still a little confused about the behavior of the load API. Setting process to false fixed the problem of vertex and face disorder, but vertex # is much larger than the model it has (e.g., loaded mesh has 19974 while it shows only 3780 in model creation tool and meslab viewer, in both .obj and .stl format).  Is there any way to keep the vertex number unchanged? 

Tks.

**Comment by mikedh** [comment]
Hey, not sure what's going on there. I actually re-wrote the OBJ loader in #436 which should be merged soon-ish, and I'll see if it is also exhibiting this behavior. It probably has new, but different bugs 😄

**Comment by mikedh** [comment]
Closing for now as new OBJ loader is merged (#436) and presumably has different, exciting problems. Feel free to re-open!
