### ISSUE TITLE
Binary STL colors

### ISSUE THREAD

**Issue by mjd3** [mikedh/trimesh#438]
Hi @mikedh, 

I was wondering if there is an easy way to load colored binary STL files. Right now, it seems that color isn't supported; is it due to this issue: https://en.wikipedia.org/wiki/STL_(file_format)#Color_in_binary_STL? For now, I am converting to .ply, which works. I could also write it in later if you decide it's something you would want!

Thanks,
Mike

**Comment by mikedh** [comment]
Hey, I added the face attribute bytes to metadata:
```
In [1]: import trimesh

In [2]: m = trimesh.load('models/featuretype.STL')

In [3]: m.metadata
Out[3]: 
{'face_attributes': array([0, 0, 0, ..., 0, 0, 0], dtype=uint16),
 'file_name': 'featuretype.STL',
 'file_path': '/dropbox/drop/Dropbox/robotics/trimesh/models/featuretype.STL',
 'header': 'ddlid featuretype',
 'processed': True}

In [5]: m.metadata['face_attributes'].shape
Out[5]: (3476,)

In [6]: m.faces.shape
Out[6]: (3476, 3)
```

It doesn't seem like the scheme for encoding colors is standard or all that common, so I'm a little hesitant to *always* turn those bytes into color, as it seems like they could be representing anything.

**Comment by mjd3** [comment]
Awesome! Yeah I was reading more on it and it's non-standard apparently so this is probably the best way to handle it.

**Comment by mikedh** [comment]
Sounds good! Sorry to change the API up on you, but I thought about it and `mesh.metadata` is kind of where information goes to die: before the API gets entrenched, I moved this to `mesh.face_attributes['stl']`, in https://github.com/mikedh/trimesh/pull/444. That way `mesh.update_faces` calls will also update this property to keep the face correlation.
