### ISSUE TITLE
dae format not supported

### ISSUE THREAD

**Issue by pmayostendorp** [mikedh/trimesh#439]
I recently upgraded my python install to 3.6 in a new virtual environment and installed `trimesh` via`conda` to this environment. Under my previous environment (2.7) and its version of `trimesh` (2.37.7), I have always been able to load Collada files with a .dae extension using `trimesh.exchange.load.load`. Collada files are explicitly listed as a supported file type. E.g.:
```
>>> trimesh.exchange.load.available_formats()
['dict64', 'dae', 'msgpack', 'off', 'stl', '3dxml', 'xaml', 'zae', 'json', 'ply', 'stl_ascii', 'dict', '3mf', 'obj', 'glb', 'svg', 'dxf', 'tar.gz', 'tar.bz2', 'zip']
```

However, in my new python 3.6 environment (`trimesh` 2.38.19), I see the following:
```
>>> trimesh.exchange.load.available_formats()
['stl', 'stl_ascii', 'off', 'dict', 'dict64', 'json', 'msgpack', 'ply', 'xaml', '3dxml', 'obj', 'glb', 'gltf', '3mf', 'zip', 'tar.bz2', 'tar.gz']
```

More importantly, attempts to load .dae files fail. Is this a bug, user error, or has support for this file type been dropped? Thanks.

**Comment by mikedh** [comment]
Hey, we switched our `dae` loader from our homebrew one to [pycollada](https://github.com/pycollada/pycollada) in #317 as it is quite a light dependency and supports many more COLLADA features than we have cycles to implement. If you install via pip it should work with trimesh automatically:

`pip install --upgrade pycollada`

**Comment by pmayostendorp** [comment]
Thanks, saved me a ton of searching. Somehow this was not super clear as a dependency, but good to know.
