### ISSUE TITLE
Segfault on import

### ISSUE THREAD

**Issue by jenom** [mikedh/trimesh#440]
When I have `gmsh-sdk` installed via pip `import trimesh` results in an immediate segfault of the interpreter. The gmsh sdk itself seems to work. I can import it and initialize it. Uninstalling `gmsh-sdk` remedies the problem.

**Comment by mikedh** [comment]
Ah, I guess `gmsh` doesn't always import cleanly. I moved the import into the function in https://github.com/mikedh/trimesh/commit/70ecc8870663216a2f6fa6f6f42b317d0e00b8ee, hopefully that helps.

**Comment by jenom** [comment]
Thanks a lot. I will try to test it soon.

**Comment by mikedh** [comment]
Closing for now, although if the fix didn't help feel free to re-open.
