### ISSUE TITLE
Shortest path

### ISSUE THREAD

**Issue by MarcGondran** [mikedh/trimesh#441]
Hi Mike,

I've checked out the function shortest path which allows given two vertices of the mesh to find the shortest path in between. I was wondering if there was a way to find the shortest path between two particular points which are not vertices of the mesh.

Thank you very much. I really appreciate your work

Marc

**Comment by mikedh** [comment]
Hey Marc, that's a less well defined problem, but what you could do for an approximate solution is subdivide the mesh a number of times (i.e. until both of your two points are within a small distance of a vertex, check with `scipy.Spatial.cKDTree`) and then run the shortest path on the subdivided mesh.

**Comment by mikedh** [comment]
Closing for now, though feel free to re-open!
