### ISSUE TITLE
How to change the background color?

### ISSUE THREAD

**Issue by dclcs** [mikedh/trimesh#443]
![2019-06-02 22-44-06 的屏幕截图](https://user-images.githubusercontent.com/43787815/58762971-2687ef00-8588-11e9-9fe2-2d96790bd6cc.png)
Change the background color

**Comment by mikedh** [comment]
Hey, there could be better docstrings on this, but I think `scene.show(background=[200,200,0,255])` will do what you're looking for:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/teapot.ply')

In [3]: points = m.sample(1000)

In [4]: points.shape
Out[4]: (1000, 3)

In [5]: cloud = trimesh.PointCloud(points)

In [8]: cloud.show(background=[200,200,0,255])

```
![Screenshot from 2019-06-02 14-30-03](https://user-images.githubusercontent.com/1403074/58765626-f1a57900-8542-11e9-866b-051472841656.png)

**Comment by dclcs** [comment]
Thank you

**Comment by hoosha** [comment]
What about background in scene_to_html(scene)? How do we do that?

**Comment by Cristianobam** [comment]
I was asking myself the same thing. Is it possible to change the background color or make it transparent in the resulting html from of scene_to_html?

**Comment by Cristianobam** [comment]
Actually, I founded a way. Even those it is not the most pretty way to do, we can replace the color hex code inside the html for what we wish. It follows the code that worked for me:

```python
HEX_CODE = '9b9b9b'
scene_to_html(mesh.scene()).replace('scene.background=new THREE.Color(0xffffff)', f'scene.background=new THREE.Color(0x{HEX_CODE})')
```

**Comment by jloganolson** [comment]
Hello, I tried this in a jupyter notebook and the background remains white - any help/ideas are appreciated:
```trimesh.Scene(objects).show(background=[200,200,0,255])```

**Comment by Kramer84** [comment]
@jloganolson 
The same approach than for html can be used in a jupyter notebook:

```python
notebook_scene = trview.notebook.scene_to_notebook(mesh.scene())
HEX_CODE = 'e8e8e8'
notebook_scene.data = notebook_scene.data.replace('scene.background=new THREE.Color(0xffffff)', f'scene.background=new THREE.Color(0x{HEX_CODE})')
notebook_scene  #To actually view it
```

(sorry for replying on a closed issue, but it makes sense having this information here)
