### ISSUE TITLE
cite trimesh

### ISSUE THREAD

**Issue by bbarroqueiro** [mikedh/trimesh#445]
Hi Michael...

Is there any particular way i should cite trimesh?

Uniformization would be good i guess!

**Comment by mikedh** [comment]
Heh I keep meaning to write a systems paper on it to make this easier, but for now all we have is this previous discussion: https://github.com/mikedh/trimesh/issues/346

**Comment by bbarroqueiro** [comment]
thanks

**Comment by bbarroqueiro** [comment]
btw if you think you should include something about laplacian smoothing... let me i know i can help with that section...
