### ISSUE TITLE
possible misbehavior after successive transformation and difference operations

### ISSUE THREAD

**Issue by friedrichaugust** [mikedh/trimesh#45]
i tried to apply some boolean difference operation to a mesh. from a loaded model, i create a bounding cylinder and place a sphere within the scene. then i cut the sphere from the cylinder and rotate the cylinder.
after a couple a iterations, the mesh is surprisingly empty. and nearly all faces are away. 

this test i did on ubuntu 16.10 with Python 2.7.12+ with blender and openscad

[example.zip](https://github.com/mikedh/trimesh/files/880479/example.zip)

**Comment by mikedh** [comment]
Hey- boolean operations are often kind of unstable. Trimesh is using one of two different backends- openSCAD or Blender. The openSCAD one is a bit more stable, have you tried:

`cylinder = cylinder.apply_transform(r).difference(kugel, engine='scad')`

That being said, the example you sent worked for me (output was watertight at the end) even with the default Blender backend, you may want to try updating your version of Blender to the latest.

**Comment by mikedh** [comment]
Hey, I'm going to close this for now. If you have more info feel free to re-open.
