### ISSUE TITLE
mesh.show() causes segmentation fault on OSX

### ISSUE THREAD

**Issue by andre-meyer** [mikedh/trimesh#450]
I'd really love to use this library as it is _perfect_ for my usecase, but I'm having a lot of trouble getting it to display my meshes. I'm calling `mesh.show()` and I'll receive an empty window. Touching this window results in a segmentation fault crash, like so:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 755, in __call__
    result = f(objc_id, self.selector, *args)
ctypes.ArgumentError: argument 1: <class 'RecursionError'>: maximum recursion depth exceeded in __instancecheck__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1121, in objc_method
    result = f(py_self, *args)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 25, in nextEventMatchingMask_untilDate_inMode_dequeue_
    if self.inLiveResize():
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 785, in __call__
    return self.method(self.objc_id, *args)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 764, in __call__
    error.args += ('selector = ' + self.name,
TypeError: can only concatenate str (not "bytes") to str
[1]    21219 segmentation fault
```

Here's how my window looks like:
![image](https://user-images.githubusercontent.com/969493/59115653-066e7c00-894a-11e9-8779-f39fb2406f95.png)

**Python Version:** 3.7.2 (Installed via `brew install python`)
**Virtualenv** setup using `venv` (`python3 -m venv .`)
**Max OSX:** 10.14 Mojave

I've installed trimesh via `pip install trimesh[easy]` with no errors.

Is this an issue I have to file in pyglet or cocoapy? I've found solutions online that point to using a `fix-osx-virtualenv` package to generate a `pythonw` executeable but seems to be no longer maintained and deprecated.

**Comment by mikedh** [comment]
Hey, yeah that looks like a `pyglet` issue, here's the [thread you probably found](https://bitbucket.org/pyglet/pyglet/issues/199/attempting-to-resize-or-close-pyglet) where they punt it even further upstream haha. Unfortunately not much we can do from the `trimesh` side on that one.

**Comment by mikedh** [comment]
Hey, maybe the fork of `pyglet` described here would help: https://pyrender.readthedocs.io/en/latest/install/index.html#python-installation

**Comment by andre-meyer** [comment]
Thanks! I'll try 🙏

**Comment by andre-meyer** [comment]
Now only one quarter is visible. The near and far plane are also messed up. I’ll further investigate into pyrender issues that might help with this issue

**Comment by mikedh** [comment]
Closer! FWIW (very little) I run an Ubuntu 16.04 VM in Parallels on my Mac and have been very happy with the performance/dev experience in full screen mode (just three finger swipe back to Mac-land).

**Comment by andre-meyer** [comment]
Thanks for the advice. I've now also tested with `pythonw` from anacondas python 3.7 installation but no luck. If anyone else stumbles across this, just use what @mikedh suggested and try it on a ubuntu machine/VM, until pyglet supports the weird OpenGL from OSX 10.14

**Comment by andre-meyer** [comment]
I'll also close this because this is definitely not a trimesh problem. Again, thanks so much for your help. 🙏

**Comment by andre-meyer** [comment]
Oh I just found out about an issue in my meshes, which is why I thought my later tests also failed, but they do actually work. What I did that finally made my meshes appear (atleast those from the examples) was to use anaconda to install python.app:
```
conda install python.app
```

and then while using the conda CLI tools, install everything and run `pythonw app.py` and it actually does show up. Still crashes on close but it seems the graphical stuff atleast works when using pythonw
![image](https://user-images.githubusercontent.com/969493/59283484-ee10a100-8c6a-11e9-908a-8b175dbfb0d7.png)

**Comment by mikedh** [comment]
Whoa nice! At least until the [10.15 hammer falls](https://www.reddit.com/r/emulation/comments/8okgz2/apple_will_remove_opengl_from_future_macos/) haha. They don't make it easy 😁
