### ISSUE TITLE
scene.save_image renders differently on 2 local linux computers

### ISSUE THREAD

**Issue by F2Wang** [mikedh/trimesh#452]
I am using scene.save_image on 2 different local computers (ubuntu 16.04) using the same code (except that I set visible = True on one computer and visible = False on the other so that it would not save blank images).

The rendered result looks different (one looks a lot more zoomed in) Is there anyway to make them look consistent?

![1](https://user-images.githubusercontent.com/20426426/59217142-50927000-8b8b-11e9-8b55-9db0e2935e1f.png)
![9](https://user-images.githubusercontent.com/20426426/59217191-6142e600-8b8b-11e9-908a-3a17eafe4174.png)

**Comment by mikedh** [comment]
Hmm, can you print out `scene.camera.transform`, `scene.camera.focal`, `scene.camera.fov` `scene.camera.resolution` before the `save_image` call and see if they're all the same? 

Are you explicitly setting the camera transform? If the transform isn't set, it may be calling `look_at` (i.e. "automatically try to get everything in the scene in view of the camera") before rendering and then the behavior would not necessarily be deterministic.

**Comment by F2Wang** [comment]
Solved, thank you!
