### ISSUE TITLE
Mesh loses vertex color when exported as .obj file

### ISSUE THREAD

**Issue by F2Wang** [mikedh/trimesh#456]
Hi,

I have been trying to export a textured mesh to .obj file but loses the vertex color with the saved ,obj file. Are there any options to conserve color during the process?

The code I am using now is:
`          export = trimesh.exchange.obj.export_obj(mesh)
            file_obj = open("temp/"+str(index)+str(kk) + ".obj", 'wb')
            result = trimesh.util.write_encoded(file_obj, export)`

Thanks

**Comment by mikedh** [comment]
Hey, this is fixed and tested in the `release/major` branch, which is scheduled  to be released 7/15/2019. Thanks for the report!
