### ISSUE TITLE
Missing triangles using pyembree intersector

### ISSUE THREAD

**Issue by e3dEF** [mikedh/trimesh#457]
Hi,

I think there is some error in the pyembree implementation. I made ray intersections on a mesh using intersects_id with multiple_hits=False.
When pyembree is used, there are triangles "missing" in the index_triangle list, that should clearly be intersected. In the viewer you can see, that pyembree detected a hit, because the triangles behind are not intersected. When I use the trimesh numpy ray intersection everything seems fine. So maybe there is some mistake in the transformation back to trimesh? I made a picture:
[](https://i.ibb.co/TYyTxD3/ray.png)
https://i.ibb.co/TYyTxD3/ray.png

Number of elements in index_triangle list
Using pyembree: 55019       Without: 56052
Latest Version of Trimesh, Python 3.6, Linux

**Comment by mikedh** [comment]
Hey, yeah `pyembree` is much faster than the other options, but only returns the first hit so we have to do slightly janky ray-offset-requery logic to get all hits, which is probably what is the issue this case. I believe this is the same issue as #242 

The built-in raytracer to `trimesh` is a lot slower, but doesn't have this issue. You can use it by loading meshes with `mesh = trimesh.load('file.stl', use_embree=False)`
