### ISSUE TITLE
error caught in embree.

### ISSUE THREAD

**Issue by IvKor** [mikedh/trimesh#46]
Hi, 

Very simple piece of code leads to the following error warning, although it does not break the code execution. I am not 100% sure it is trimesh related, however, any clarification would be helpful.

The issue is following.
I load a mesh from an 'obj' file and execute ray.inersects_any function by using a single ray origin and unit vector. Since there is no single intersection the function returns 'False'. In the next line I load again the same 'obj' file (assigning a different variable name) and execute again a ray.inersects_any function. The following three lines of error warnings appears before the output of the function (which is again 'False'):

ERROR CAUGHT IN EMBREE
ERROR: Invalid operation
ERROR MESSAGE: b'already initialized'

The code is:

```
import trimesh

ray_origin = [[5, -0.001, 2.5]]
vector = [[0, -1, 0]]

mesh = trimesh.load_mesh('./test_mesh.obj')
intersect = mesh.ray.intersects_any(ray_origin, vector)
print(intersect)

mesh1 = trimesh.load_mesh('./test_mesh.obj')
intersect = mesh1.ray.intersects_any(ray_origin, vector)
print(intersect)
```

While the 'test_mesh.obj' is:

```
v 0 0 5
v 0 0 0
v 10 0 5
v 10 0 0
v 10 10 5
v 10 10 0
v 0 10 5
v 0 10 0
f 1 2 3
f 3 2 4
f 3 4 5
f 5 4 6
f 5 6 7
f 7 6 8
f 7 8 1
f 1 8 2
```

Best regards

**Comment by mikedh** [comment]
Hey, thanks for the report! I think this is just a case of aggressive warning messages in pyembree. Pyembree has still returned the correct answer for me in every case I've checked. I opened an issue (linked above) on the pyembree repo as the warning can be reproduced by just creating two scenes in the same program. I'm going to close this issue as I think the one in pyembree is the source.
