### ISSUE TITLE
ray_triangle.RayMeshIntersector.intersects_location returns list when no rays intersect

### ISSUE THREAD

**Issue by HDictus** [mikedh/trimesh#460]
When the arrays returned by ray_triangle.RayMeshIntersector.intersects_location are empty, it seems that they come out not as an array, but as a list. Was trying the get its .shape, and it suddenly didn't work while it had for lots of previous shapes. Its pretty minor, but it is unintuitive and caused some confusing errors, so I thought I'd let you know.
the best I think would be to get a (0, 3) array back for the intersection positions, and a (0,) array for the others.

**Comment by mikedh** [comment]
Yeah, that is janky for sure. Fix and test in https://github.com/mikedh/trimesh/commit/3d42312a3155862d90af148fd0bf6f82ce1c01ae

Thanks for the report!

**Comment by mikedh** [comment]
Closing for now, let me know if fix didn't help!

**Comment by HDictus** [comment]
It did indeed help, thanks for the quick action!

I did notice that the positions come out as a (0,) array, rather than (0, 3) array, which is leading to some broadcasting issues when there are no intersections.
