### ISSUE TITLE
Result of discrete_mean_curvature_measure

### ISSUE THREAD

**Issue by yoda0612** [mikedh/trimesh#461]
Hi @mikedh ,

I have try to use discrete_mean_curvature_measure to obtain the mean curvature for a 3D object. However, I found the result was very different from the expected ones. 
Suppose, if I used a sphere as an input, the value of 0.5*summation(2*mean curvature) should be  
approaching the volume of sphere.
I may misunderstand...

**Comment by mikedh** [comment]
Heh not sure what's going on there. As a first pass reading through [the PR that added curvature](https://github.com/mikedh/trimesh/pull/175) might be helpful.

**Comment by yoda0612** [comment]
Hi @mikedh ,

Thank you a lot. I will try to understand your code as well.

**Comment by mikedh** [comment]
Closing for now, though if you have a minimal reproducible example feel free to re-open!
