### ISSUE TITLE
Texture not aligned when reading obj

### ISSUE THREAD

**Issue by ricshaw** [mikedh/trimesh#462]
There seems to be an issue when loading a mesh as an obj or ply. The texture is not aligned with the mesh, it looks shifted and/or scaled (see first image). However in Meshlab the texture is correct (second image).

![Screenshot from 2019-06-14 13-23-14](https://user-images.githubusercontent.com/9107279/59509067-e4c04800-8ea7-11e9-8126-0233577df8af.png)

![Screenshot from 2019-06-14 13-24-09](https://user-images.githubusercontent.com/9107279/59509120-0d484200-8ea8-11e9-9f69-f7a93b593028.png)

**Comment by mikedh** [comment]
I think this was probably related to the "texture size not a power of 2" problem, which was fixed in the release. 

Closing for now as new OBJ loader is merged (#436) and presumably has different, exciting problems. Feel free to re-open!
