### ISSUE TITLE
Questions about unique edges and faces when a mesh being converted to graph

### ISSUE THREAD

**Issue by LYHTHU** [mikedh/trimesh#465]
I load a 3D model from ShapeNetCore.v2. And I print some information about it.
However, something strange happens. There are 4688 faces in this model, 1250 vertices, but only 3559 unique edges.
It doesn't make sense.

**Comment by mikedh** [comment]
Hey, `edges_unique` is the de-duplicated list of edges, which depends on topology. If your model had a lot of duplicated faces I could see `mesh.edges_unique` being smaller than the number of faces. You could try calling `mesh.remove_duplicate_faces` and see what the number look like. 

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/featuretype.STL')

In [3]: m.vertices.shape
Out[3]: (1722, 3)

In [4]: m.faces.shape
Out[4]: (3476, 3)

In [5]: m.edges?
Type:        property
String form: <property object at 0x7f054d949ae8>
Docstring:  
Edges of the mesh (derived from faces).

Returns
---------
edges : (n, 2) int
  List of vertex indices making up edges

In [6]: m.edges.shape
Out[6]: (10428, 2)

In [7]: 3476 * 3
Out[7]: 10428

In [8]: m.edges_unique?
Type:        property
String form: <property object at 0x7f054d949b88>
Docstring:  
The unique edges of the mesh.

Returns
----------
edges_unique : (n, 2) int
  Vertex indices for unique edges

In [9]: m.edges_unique.shape
Out[9]: (5214, 2)
```

**Comment by LYHTHU** [comment]
> Hey, `edges_unique` is the de-duplicated list of edges, which depends on topology. If your model had a lot of duplicated faces I could see `mesh.edges_unique` being smaller than the number of faces. You could try calling `mesh.remove_duplicate_faces` and see what the number look like.
> 
> ```
> In [1]: import trimesh
> 
> In [2]: m = trimesh.load('models/featuretype.STL')
> 
> In [3]: m.vertices.shape
> Out[3]: (1722, 3)
> 
> In [4]: m.faces.shape
> Out[4]: (3476, 3)
> 
> In [5]: m.edges?
> Type:        property
> String form: <property object at 0x7f054d949ae8>
> Docstring:  
> Edges of the mesh (derived from faces).
> 
> Returns
> ---------
> edges : (n, 2) int
>   List of vertex indices making up edges
> 
> In [6]: m.edges.shape
> Out[6]: (10428, 2)
> 
> In [7]: 3476 * 3
> Out[7]: 10428
> 
> In [8]: m.edges_unique?
> Type:        property
> String form: <property object at 0x7f054d949b88>
> Docstring:  
> The unique edges of the mesh.
> 
> Returns
> ----------
> edges_unique : (n, 2) int
>   Vertex indices for unique edges
> 
> In [9]: m.edges_unique.shape
> Out[9]: (5214, 2)
> ```

Thanks for your reply. Yes it is because in many meshes models the spiral direction matters. That's why the edges are much fewer.
When I use digrpah, the result seems to be good.

By the way, is there any support in trimesh or networkx that can reconvert a graph back to mesh (faces)?
Thank you again.

**Comment by mikedh** [comment]
You could look for length 3 cycles. There's definitely a faster way to do this, but as a first pass:

```
    import trimesh
    import networkx as nx

    m =	trimesh.load('models/featuretype.STL')

    edges = m.edges_unique
    g =	nx.from_edgelist(edges)

    # collect faces as set to avoid duplication                          
    f =	set()
    for e in edges:
        overlap = set(g[e[0]].keys()).intersection(g[e[1]].keys())
        for o in overlap:
            f.add(tuple(np.sort(np.append(e, o))))

    # convert set of tuples to numpy array                               
    faces = np.array(list(f))
    r = trimesh.Trimesh(m.vertices, faces)

    # face winding will be totally incorrect                             
    r.fix_normals()

```
