### ISSUE TITLE
Rotation stops working after resetting the view with 'z'

### ISSUE THREAD

**Issue by patrikhuber** [mikedh/trimesh#47]
Hi!

When I display a mesh with `mesh.show()`, rotating it with the left mouse works, until I press 'z' to reset the view - then, it only rotates around the z-axis (roll-angle), and not around the other two axes anymore. It's 100% reproducible.

This is on Win 10 in a virtualenv with python-3.6.1 (64-bit), numpy+mkl, scipy and Shapely from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/), and `pip install trimesh[easy]`.

**Comment by mikedh** [comment]
Thanks for the report! This was pretty dumb, and fixed in https://github.com/mikedh/trimesh/commit/80d43eaed7efbb25d609b405b8ff87f61e5f7ca0

**Comment by mikedh** [comment]
Closing for now, feel free to reopen if not fixed by https://github.com/mikedh/trimesh/commit/80d43eaed7efbb25d609b405b8ff87f61e5f7ca0

**Comment by patrikhuber** [comment]
I can confirm it's fixed for me as well, great :-)
