### ISSUE TITLE
Problem met when loading .obj file in ShapeNet

### ISSUE THREAD

**Issue by LYHTHU** [mikedh/trimesh#472]
Hi, I am really sorry to bother you.
I have encountered some problems when I tried to load .obj file from ShapeNet. I want to load just the mesh of the surface of the obj, ignoring the mtl file. However, I don't find a method. Also, because the default value of resolver is None, it will always raise an error when running. Is there some way to resolve it?
Really thanks!

Regards

**Comment by mikedh** [comment]
No worries! The OBJ loader is actually undergoing a complete re-write and we're expecting to merge [7/15/2019](https://github.com/mikedh/trimesh/pull/467). I'm not sure if it solves this exact problem, but I am testing against ShapeNet and anecdotally, the reliability is better than the current loader.

**Comment by LYHTHU** [comment]
> No worries! The OBJ loader is actually undergoing a complete re-write and we're expecting to merge [7/15/2019](https://github.com/mikedh/trimesh/pull/467). I'm not sure if it solves this exact problem, but I am testing against ShapeNet and anecdotally, the reliability is better than the current loader.

Alright. Really thanks.

This issue(load .obj file without .mtl file) actually doesn't affect the mesh loading, however, it will raise an error and print out error messages, which slow down the program. 

You can easily reproduce this issue by, calling `trimesh.load` or `trimesh.load_mesh` to load the file "tube.obj" which is provided in this github repo.

If you don't mind, could you please help me to solve it? Or just make the loading procedure quiet. I am so sorry to bother you, but I really need to use it right now. Trimesh is the most convenient tools I can find.

**Comment by mikedh** [comment]
Hey, I switched it from error to debug in https://github.com/mikedh/trimesh/commit/9363b6ead375555b03416f639847a480c18670a3 which should be quieter.

**Comment by LYHTHU** [comment]
When I comment the lines in the .obj file that are related to MTL file, there will be no error. Actually I don't need MTL in my project. 
Are there any arguments or settings when call load or load_mesh to explicitly ignore MTL?
