### ISSUE TITLE
Collision Package: Tolerances

### ISSUE THREAD

**Issue by e3dEF** [mikedh/trimesh#474]
Hello,

I wanted to know if there are constants and arguments to set when using in_collision_internal.
I'm interested in two specific things.
At the moment result of the function is a pairwise list of meshes that touch each other in one or more points. Is it possible to expand the query to objects that are only close to each other (min_distance e.g. 1e-2). On the other hand, is it possible to check if objects are "more than" touching? This would be the case when they share a volume. I know, for this Boolean operations can be used, but they are slow and only work for 100% watertight meshes.

Thank you in advance

**Comment by mikedh** [comment]
Hey, not sure, though I'd try playing around directly with the [python-fcl](https://github.com/BerkeleyAutomation/python-fcl) bindings and see if there was anything obvious.

**Comment by Moult** [comment]
Ping @e3dEF did you find a solution to your problem? I'm facing the same issue. I looked in the bindings as @mikedh but didn't find anything.

**Comment by e3dEF** [comment]
Unfortunately no.
