### ISSUE TITLE
How to solve ValueError: negative dimensions are not allowed? when export STL from Points ?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#480]
How to solve ValueError: negative dimensions are not allowed? when export STL from Points ?
   matrix = np.zeros(np.product(shape), dtype=np.bool)
ValueError: negative dimensions are not allowed

**Comment by mikedh** [comment]
Hey, this is a more of a numpy question than a trimesh question. Probably in this case `shape` is negative, and you can't create an array with `-20` or whatever elements.
