### ISSUE TITLE
OBJ writer does not write texture UV coordinates

### ISSUE THREAD

**Issue by pocketpixels** [mikedh/trimesh#487]
It appears that the UVs are currently stored under `metadata['visual']`, but the `export_wavefront()` implementation is looking for them in  `metadata[''vertex_texture'']`?
Because of this when loading and then saving an OBJ file, the texture coordinates are lost.

**Comment by mikedh** [comment]
Yeah, currently texture exports aren't supported, though PR's are super welcome! The OBJ loader is undergoing a re-write, which will be released in https://github.com/mikedh/trimesh/pull/467

**Comment by pocketpixels** [comment]
This is just about the texture coordinates (the "vt" entries in obj files) not being written. There is code in the OBJ exporter for writing those, but it appears to be looking for those UV coordinates in the wrong place.

**Comment by mikedh** [comment]
Closing for now as new OBJ loader is merged (#436) and presumably has different, exciting problems. Feel free to re-open!

**Comment by pocketpixels** [comment]
The issue still very much exists. The `export_obj()` method still looks for the uv data in `mesh.metadata['vertex_texture']`. And if you [search the repo for `vertex_texture`](https://github.com/mikedh/trimesh/search?q=vertex_texture&unscoped_q=vertex_texture) you will see that the only use to that term is in this `export_obj()` method.
