### ISSUE TITLE
ModuleNotFoundError shapely.vectorized._vectorized

### ISSUE THREAD

**Issue by mm1234mm1234** [mikedh/trimesh#492]
Hi,
I don't know if it is a Trimesh or a Shapely problem.

- Widows 7 64bit
- Python 3.7.3
- Cython 0.29.12
- Trimesh 2.38.42
- Shapely: tryed with 1.7a2 or 1.6.4.post2 or 1.6.4

Traceback (most recent call last):
  File "[OMISSIS].py", line 2, in <module>
    from trimesh.path.polygons import medial_axis
  File "[OMISSIS]\lib\site-packages\trimesh\path\__init__.py", line 1, in <module>
    from .path import Path2D, Path3D
  File "[OMISSIS]\lib\site-packages\trimesh\path\path.py", line 34, in <module>
    from . import polygons
  File [OMISSIS]\lib\site-packages\trimesh\path\polygons.py", line 5, in <module>
    from shapely import vectorized
  File "[OMISSIS]\lib\site-packages\shapely\vectorized\__init__.py", line 3, in <module>
    from ._vectorized import (contains, touches)
**ModuleNotFoundError: No module named 'shapely.vectorized._vectorized'**

The file _[OMISSIS]\Lib\site-packages\shapely\vectorized\_vectorized.pyx_ exist

**Comment by jackd** [comment]
Are you able to run `from shapely import vectorized` (i.e. without trimesh at all)? If not it sounds like an issue with your shapely version (works for me with 1.6.4.post2 on ubuntu 18.04, but I don't have a windows box to test on).

**Comment by mikedh** [comment]
Hey, yeah this looks like a shapely issue, I'd try installing again (they require third party libraries to be installed, I might try using conda on windows). 

If @jackd's suggestion doesn't crash feel free to re-open, try running a file containing *only*:
```
from shapely import vectorized
```
