### ISSUE TITLE
New Stuff

### ISSUE THREAD

**Issue by bbarroqueiro** [mikedh/trimesh#494]
Hello

I’m considering starting a new project which would be based on Trimesh mostly, but I would need help.

The idea is to include topology optimization solver (see https://i.imgur.com/tD3m6CG.gif ) as a trimesh module. The user would able to pick a primitive (i.e. cube or some other domain in step file ) perform the topolopy optimization a get a new geometry that needs smoothing and have it ready to 3D printing. 

The main issue that I have is related with graphics and GitHub integration, and without help I will not start it.  

I need to be able to pick vertices in a mesh.show() window but I have not clue how to do it! Would you be interested in helping? Or you already have to much on your plate?

All the mechanics, finite element method and solvers (optimization and mechanical) would be on me! The code would use some modules of wrapped fortran code for python, since I need to reuse some old fortran code.

If you are interested let me know... 

Regards

**Comment by mikedh** [comment]
Hey, yeah that could be awesome! I might be able to add a vertex picker to the viewer, or to @wkentaro's `widget` perhaps. I'll try to look in to it this week.

Best,
Mike

**Comment by bbarroqueiro** [comment]
Hi Mike any news about vertex picker?

**Comment by bbarroqueiro** [comment]
I was trying to use the voxelized but it appears the the lists of elements with vertex connectivity as well as the vertices coords is not generate right? But how could i do that?

**Comment by mikedh** [comment]
Hey, for vertex picker I would subclass `SceneViewer` and then it [looks like there's a `GL_SELECT` mode](https://community.khronos.org/t/selection-in-3d/27125) which I'll try to investigate, although I'm away this weekend. 

Here's a simple subclass example without the actual selection bit:

```
import trimesh

from trimesh.viewer.windowed import SceneViewer

class ClickViewer(SceneViewer):
    def on_mouse_press(self, x, y, button, modifiers):
        # call the parent method in SceneViewer
        super(self.__class__, self).on_mouse_press(
            x, y, button, modifiers)

        # do our custom actions
        print('mouse', x, y)


if __name__ == '__main__':
    m = trimesh.creation.icosphere()


    ClickViewer(m.scene())
```

**Comment by bbarroqueiro** [comment]
Hi Mike

Sorry to bother again, but any news about vertex?

Regards
BB

**Comment by bbarroqueiro** [comment]
Hi..

I have been working on the algorithm. An example bellow in 2D for visualization purposes only, the code is 3D

![movie](https://user-images.githubusercontent.com/47561761/63282286-6b2d4780-c2a6-11e9-9ad0-2be190cf4f60.gif)

But at this point i'm kind of stuck with vertex picker...  

I was trying to get transformation matrix of the current scene in order to project all points and get the closest one with a similar orientation. But i'm not familiar with graphics computation and i becomes quite daunting...

**Comment by bbarroqueiro** [comment]
Hi Mike, the picker is done... Thanks for the subclass suggestion... I would like to speak with you (via skype?) about the new project about the new project if you are interested. But let me know either way... please

import trimesh, time
import pyglet
from pyglet.gl import *
from trimesh.viewer.windowed import SceneViewer
from scipy.spatial import KDTree
import numpy as np
class ClickViewer(SceneViewer):
    def on_mouse_press(self, x, y, button, modifiers):
        # call the parent method in SceneViewer
        super(self.__class__, self).on_mouse_press(x, y, button, modifiers)
        if hasattr(self, 'last_mouse_release'):
            if (x, y, button) == self.last_mouse_release[:-1]:
                """Same place, same button"""
                if time.time() - self.last_mouse_release[-1] < 0.8:
                    # On Double click
                    #height=self.scene.camera.resolution[1]
                    #width=self.scene.camera.resolution[0]
                    x = int(x)
                    y = int(y) 
                    z0 = (GLfloat *1)()
                    glReadPixels(x, y, 1, 1, GL_DEPTH_COMPONENT, GL_FLOAT, z0)
                    pmat = (GLdouble * 16)()
                    mvmat = (GLdouble * 16)()
                    viewport = (GLint * 4)()
                    px = (GLdouble)()
                    py = (GLdouble)()
                    pz = (GLdouble)()
                    glGetIntegerv(GL_VIEWPORT, viewport)
                    glGetDoublev(GL_PROJECTION_MATRIX, pmat)
                    glGetDoublev(GL_MODELVIEW_MATRIX, mvmat)
                    gluUnProject(x, y, z0[0], mvmat, pmat, viewport, px, py, pz)                  
                    coord=[px.value, py.value, pz.value]
                    try:
                        self.bc += coord
                    except:
                        self.bc = coord
                    print("Vertex added")
    def on_mouse_release(self, x, y, button, modifiers):
        #super(self.__class__, self).on_mouse_release(x, y, button, modifiers)
        #height=self.scene.camera.resolution[1]
        x = int(x)
        y = int(y) #height - int(y)
        self.last_mouse_release = (x, y, button, time.time())

**Comment by mikedh** [comment]
Hey that looks awesome! Sorry I've been unresponsive, yeah definitely up for a Skype chat! When works for you?

**Comment by bbarroqueiro** [comment]
hello, from Monday to Thursday something from my 11:00 to13:00 or 14:00 to 19:30... but in work local time i think it less 5 hours so see what it is more convenient to you...

Regards

**Comment by bbarroqueiro** [comment]
It can be no problem... The time zone is Lisbon... just let me know which time is more convenient for you...
