### ISSUE TITLE
Issue using mikedh/trimesh Dockerfile as a base image

### ISSUE THREAD

**Issue by oortlieb** [mikedh/trimesh#496]
I'm using `mikedh/trimesh` as a base for one of our Dockerfiles that needs trimesh. It looks like the `latest` tag was updated yesterday, and that it uses a new version of `trimesh` which does not work with the code we've written. Would it be possible to add the previous version of the Dockerfile as a tagged version to DockerHub?

**Comment by mikedh** [comment]
Ah definitely, I didn't realize anyone but me used the docker images 😄. Sorry about that! What do you think of the following:

`mikedh/trimesh:stretch` : trimesh 2.x.x, debian stretch-slim, Python 3.6
`mikedh/trimesh:buster`: trimesh 3.x.x, debian buster-slim, Python 3.7
`mikedh/trimesh:latest`: buster, for now.

**Comment by oortlieb** [comment]
I tend to like to include the software version of the package in the tag name, similar to the way node does it: https://hub.docker.com/_/node/, but whatever you think makes sense. I understand if you don't want to commit to distributing a bunch of different versions.

Whatever the tagging scheme, I think we will pull the version that works for us and host it in our own registry so we don't have to bug you in the future -- if you could let me know which tag corresponds to the pre-update version, that would be fantastic.

Thanks for all your hard work, Trimesh has been awesome for us.

**Comment by oortlieb** [comment]
I tried `mikedh/trimesh:2.38.39-stretch`, but it's not working for us, either. I ran python to check which version of trimesh it's using and saw the following:

```
user@cb4e2e86e3df:/$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trimesh
trimesh>>> trimesh.__version__
'3.0.9'
>>> 
```

The image tag suggests that it should be version `2.38.39` (which I believe should work for us). Is there something I'm doing incorrectly? All I've done is update our Dockerfile to use `mikedh/trimesh:2.38.39-stretch` instead of just `mikedh/trimesh`.

**Comment by oortlieb** [comment]
I was able to fix this on my end by finding a version of the `mikedh/timesh` image that works for us in my history. No rush to figure this out anymore. Thanks for your help!

**Comment by mikedh** [comment]
Glad you figured it out! In that version the dockerfile installed from pypi rather than the local repo (fixed in newer images). I'll push a fixed image shortly, and possibly push the fixed code to a branch.

**Comment by mikedh** [comment]
`2.38.39-stretch` now up to date. I also pushed a `2.X` branch to github, with the last 2.x.x version of trimesh with the minor fixes that were required to generate the correct docker image.

**Comment by mikedh** [comment]
Closing for now. I didn't have it do a tagged image release on every single patch release, although I might do it on every minor.
