### ISSUE TITLE
Example "Offscreen_renderer" generates black images

### ISSUE THREAD

**Issue by wofsauge** [mikedh/trimesh#498]
Hi,
I tried out the "Offscreen_renderer.py" example (https://github.com/mikedh/trimesh/blob/master/examples/offscreen_render.py) and it seems that it only outputs image files that are completely black. I tried loading other Objectfiles besides the default one, but still the same issue. I also tried to display the mesh/scene after every command and the resulting 3D-view was fine. setting the "visibility" term from the "scene.save_image" to False didnt change the result either.
How do i get this example to work?

My Specs are:
CPU - Intel core i7-4800mq 2.70GHz
GPU - Nvidia quadro K1100M
RAM -  32gb DDR3
OS - Windows 10 64bit

**Comment by mikedh** [comment]
Unfortunately I've had [very mixed luck](https://github.com/mikedh/trimesh/issues?q=is%3Aissue+blank+is%3Aclosed) with diagnosing variants of this issue, though maybe there are some ideas in the previous threads.

That being said, if I were having this issue myself I would probably try [every version of pyglet](https://pypi.org/project/pyglet/#history) and see if any of them worked differently haha

**Comment by wofsauge** [comment]
Sorry for the late response. 
Ive looked into all the issues you mentioned and no solution seemed to fix this issue for me. I also tested out nearly all the pyglet versions till 2015 but everyone produced the same result (black image).
What i noticed tho is, that in the window that pops up when saving the image (visibility=True), there is clearly the current scene with the object visible. It seems for me, that the issue lies in either the memory access of the framebuffer, or the graphicscard itself. But i dont really know that much about the code and python that i would be able to fix that issue myself.
Thanks anyways for your help

**Comment by mikedh** [comment]
I made some changes recently, do you still see this? 

Also if all else fails, the [dockerRender](https://github.com/mikedh/trimesh/tree/master/examples/dockerRender) example should (:crossed_fingers:) work decently reliably on different platforms since it's containerized and using software rasterization.

**Comment by mikedh** [comment]
Closing for now, though let me know if the changes made any difference!
