### ISSUE TITLE
Blender CSG

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#5]
Not an issue, just a question:

Is there any plan to implement CSG using blender instead of OpenSCAD? I've outsourced the CSG I've been doing to Blender, and it's been performing better for me.

I'm not sure if the speedup is just due to the opening time of OpenSCAD, or the actual speed of the CSG operation within it.

**Comment by mikedh** [comment]
Oh nice, I was looking for a faster boolean op backend. Got a code snippet you wouldn't mind sharing? The openSCAD operations are an interface to CGAL (http://doc.cgal.org/latest/Nef_3/index.html), and anecdotelly I've found them to be a lot more stable than other things I've tried. When I profiled it it looked like the slowness was the actual nef polehedra constructor/boolean operation, the intermediate tempfiles are pretty quick. 

What could be nice is an engine flag so you could switch between blender/SCAD for speed vs stability:

def union(self, other, engine='blender'):
    #stuff

**Comment by Marviel** [comment]
I do, I'll clean it up and post it when I can.

**Comment by mikedh** [comment]
Awesome thanks. No need for much cleanup, just a starting point would be helpful.

**Comment by Marviel** [comment]
@mikedh email sent

**Comment by mikedh** [comment]
Cool got it. Man that bpy API is kind of a dumpster fire, thanks for the example to start from. You should be able to do this with the latest version of trimesh now:

>a.union(b, engine='blender')

Blender was like 10x faster on some examples I tried, thanks for the idea! Let me know if it works for you.
