### ISSUE TITLE
Update a mesh while it's being displayed

### ISSUE THREAD

**Issue by patrikhuber** [mikedh/trimesh#50]
Hi,

Is it possible to update a mesh, specifically its vertex colours, while it's being shown with `mesh.show()`? 
I found a `mesh.visual.update_vertices(mask=...)` method but I don't think it does what I'm looking for.

Specifically, if I wanted to add a slider to the viewer that changes vertex colour and position values of the mesh, and the mesh should update in real-time in the viewer. Do you think that's feasible with trimesh and pyglets? Would I probably best start by copying [viewer.py](https://github.com/mikedh/trimesh/blob/master/trimesh/scene/viewer.py)? 

Any advice welcome - I'm looking for a simple tool that would allow me to achieve this. I've also been thinking about using Blender's Python interface for this.

**Comment by mikedh** [comment]
I started looking in to this briefly. I think what I ran into was that pyglet windows really don't like being separate threads/processes. The viewer code will should update a display vertex list if the [source mesh changed](https://github.com/mikedh/trimesh/blob/master/trimesh/scene/viewer.py#L73-L76), but without a different thread this isn't very useful. I'd try doing your thing inside the pyglet event loop and just using trimesh for loading/processing.

**Comment by patrikhuber** [comment]
Thank you very much for your reply! I found the Blender way is not ideal either because Blender comes with its own Python and it's a hassle to install packages there (you can delete it and it will use the system Python but this also doesn't work without problems). I'll have to see how to go on with this - sounds like it's also not trivial with trimesh.

In any case this seems out of scope for trimesh and not a trimesh issue so I'll close it - thanks again for your comments, it's very much appreciated.
