### ISSUE TITLE
Face Visibility

### ISSUE THREAD

**Issue by swarmt** [mikedh/trimesh#500]
Hi Mike!

Great library. Just wondering if it is possible to display both sides of the mesh faces in the renderer in a non watertight mesh?

**Comment by mikedh** [comment]
Thanks! Have you tried pressing `c` in the viewer window to toggle backface culling?

**Comment by swarmt** [comment]
That was easy.
Thanks Mike!

**Comment by bizonpatrycja** [comment]
Hi!

Is there a way to control the face visibility from both sides programmatically? Meaning to set it on/off before showing the window.

**Comment by Mandelbr0t** [comment]
@mikedh setting `obj.is_watertight = True` does not work because `obj` needs to fill a volume and if `obj` is a surface this won't work. How can I still toggle visibility of a surface with trimesh?

**Comment by RolandZhu** [comment]
I think you can feed flags to `.show()` function. I used `.show(flags={'cull': False})` to enforce both side visilibility.

**Comment by Sentient07** [comment]
Hi @mikedh , I'm wondering if this can be used when displaying meshes on notebook? I see most of the options available for 'gl' plotting are disabled for notebook: https://github.com/mikedh/trimesh/blob/main/trimesh/viewer/notebook.py#L47-L81. I think it would be very useful to have identical shading for backfaces. Could you please suggest a way to do this?
