### ISSUE TITLE
blender boolean union does not work anymore.

### ISSUE THREAD

**Issue by MohamadZohoori** [mikedh/trimesh#501]
Hi,

The boolean union in blender used to work for me but not anymore.
I can't figure out what the problem is. 

Here is my code:

meshes = [0 for i in range(NOL-1)]
for i in range (NOL-1):
    meshes[i] = trimesh.load_mesh('lower_hand_Mesh%d.stl'%i)
mesh3 = trimesh.boolean.union(meshes, engine='blender')
mesh3.export('myArm.stl')
   
And here is the error:

face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
face_normals didn't match triangles, ignoring!
Traceback (most recent call last):

  File "<ipython-input-28-e89d56e9fd6d>", line 1, in <module>
    runfile('C:/python/stepbystep.py', wdir='C:/python')

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/python/stepbystep.py", line 606, in <module>
    mesh3 = trimesh.boolean.union(meshes, engine='blender')

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\trimesh\boolean.py", line 44, in union
    result = _engines[engine](meshes, operation='union')

  File "C:\Users\lenovo\Anaconda3\lib\site-packages\trimesh\interfaces\blender.py", line 47, in boolean
    ' --background --python $script')
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\trimesh\interfaces\generic.py", line 70, in run
    stderr=subprocess.STDOUT)

  File "C:\Users\lenovo\Anaconda3\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['C:\\Program', 'Files\\Blender', 'Foundation\\Blender\\blender.exe', '--background', '--python', 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\tmpg9xfyq95']' returned non-zero exit status 11.

Please help me find the problem.
Thanks in advance for your help.

**Comment by MohamadZohoori** [comment]
BTW, I have reinstalled blender. Is it possible that the problem has to do with its installation?

**Comment by mikedh** [comment]
Blender just did a big release, I suspect this is related to that. What version of blender did you install?

**Comment by MohamadZohoori** [comment]
2.79

BTW, blender doesn't launch because of this error:

found bundled python...

Which is I think the reason for the error. But let's not close this issue until I fix Blender and make sure that is the main problem.

If you have had the same problem with blender, I will be grateful if you help me.

Thanks.

**Comment by MohamadZohoori** [comment]
I downloaded blender 2.80rc portable and it launches very well.
The problem is the same error with boolean union still exists.
should I copy any of the files of portable blender anywhere in anaconda location?

**Comment by MohamadZohoori** [comment]
a friend of mine installed blender successfully and ran my code. He got the desired output, but the very same error still existed. Any ideas about that?

**Comment by dbukenberger** [comment]
In my experience, the boolean-operations in Blender are kind of an issue on their own.
Even when used in Blender they often tend to produce invalid geometry and therefore also when used over the trimesh-interface.

I just recently worked with the boolean-interface of trimesh and the only things that caused problems were my shapes and Blender itself.

What you could do for debugging:
- Export your meshes manually to `stl`.
- Take the [Blender-Template](https://github.com/mikedh/trimesh/blob/master/trimesh/resources/blender.py.template).
- Execute the shell command, assembled as in the [Blender-Interface](https://github.com/mikedh/trimesh/blob/master/trimesh/interfaces/blender.py).
- Then you will see the error messages from Blender, which hopefully will tell you what went wrong.

Or switch to the OpenSCAD engine which appears to be more robust and a lot faster.

**Comment by MohamadZohoori** [comment]
Using OpenSCAD worked for me.
thanks.
