### ISSUE TITLE
Proposition of new feature: curvature estimation

### ISSUE THREAD

**Issue by aymanesouani** [mikedh/trimesh#503]
Hi,

I've implemented a method of curvature estimation on triangular mesh where I use trimesh.
This method has been published in '10.1109/TDPVT.2004.1335277'.

This method estimates curvature on each vertice.
Here's the repository with corresponding code : 
https://github.com/aymanesouani/curvature_estimation_Rusinkiewicz

Let me know if you want me to do a PR implementing this new feature in trimesh.

**Comment by mikedh** [comment]
Yeah that would be awesome! Sorry for the delay. 

Currently, there is curvature estimation in [curvature.py](https://github.com/mikedh/trimesh/blob/master/trimesh/curvature.py), how does this compare? You can read the previous discussion when that was added in the PR: #175
