### ISSUE TITLE
AttributeError: 'Scene' object has no attribute 'area'

### ISSUE THREAD

**Issue by LYHTHU** [mikedh/trimesh#504]
```
File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\sample.py", line 152, in sample_surface_even
    radius = np.sqrt(mesh.area / (2 * count))
AttributeError: 'Scene' object has no attribute 'area'.
```

It occurs when calling sample_surface_even function. Already the lastest version.
However, this bug doesn't occur when running on Ubuntu 18.04.2.

**Comment by jackd** [comment]
How did you generate your mesh? If you loaded it from an obj, the returned object is now either a mesh or scene. I'm unsure why this would be different under different versions of ubuntu, but if you're creating the obj via some other means it may be being created differently.

If you're only interested in the area, try the following:

```python
def as_mesh(scene_or_mesh):
    if isinstance(scene_or_mesh, trimesh.Scene):
        mesh = trimesh.util.concatenate([
            trimesh.Trimesh(vertices=m.vertices, faces=m.faces)
            for m in scene_or_mesh.geometry.values()])
    else:
        mesh = scene_or_mesh
    return mesh

radius = np.sqrt(as_mesh(mesh).area / (2 * count))
```

**Comment by LYHTHU** [comment]
> How did you generate your mesh? If you loaded it from an obj, the returned object is now either a mesh or scene. I'm unsure why this would be different under different versions of ubuntu, but if you're creating the obj via some other means it may be being created differently.
> 
> If you're only interested in the area, try the following:
> 
> ```python
> def as_mesh(scene_or_mesh):
>     if isinstance(scene_or_mesh, trimesh.Scene):
>         mesh = trimesh.util.concatenate([
>             trimesh.Trimesh(vertices=m.vertices, faces=m.faces)
>             for m in scene_or_mesh.geometry.values()])
>     else:
>         mesh = scene_or_mesh
>     return mesh
> 
> radius = np.sqrt(as_mesh(mesh).area / (2 * count))
> ```

Yes, it is loaded from a .obj file.
However, it runs well in Linux.

**Comment by jackd** [comment]
I'm guessing it's exactly the same obj file in each case? Are you using different trimesh versions? There was a recent 3.0 release which has slightly differing behaviour from 2.x in this regard.

**Comment by LYHTHU** [comment]
> I'm guessing it's exactly the same obj file in each case? Are you using different trimesh versions? There was a recent 3.0 release which has slightly differing behaviour from 2.x in this regard.

Sorry, my bad. It also crashed on Linux. When I use meshlab to convert it to .off, it works.
Thanks for your help.

**Comment by ucalyptus** [comment]
@LYHTHU should I convert it to .off for it to work?

**Comment by mikedh** [comment]
Some formats are describing "scenes" (i.e. multiple meshes with transforms), if you want it to always be a "baked" `Trimesh` object in newer versions I would recommend using the `force` kwarg when loading:

`mesh = trimesh.load('stuff.obj', force='mesh')`

**Comment by Zakeri68** [comment]
set the force mode to ''mesh like this and it will work : mesh = trimesh.load(mesh_file, force='mesh')

**Comment by ForrestPi** [comment]
@mikedh it doesn't work
average_edge=np.mean(trimesh.load_mesh(src_obj, force='mesh').edges_unique_length)
AttributeError: 'Scene' object has no attribute 'edges_unique_length'
