### ISSUE TITLE
scene.save_image() does not work

### ISSUE THREAD

**Issue by infosisio** [mikedh/trimesh#508]
Hi, I know this has been asked before, but I noticed that #223 was closed without a followup. I was wondering if anybody knows how to overcome this issue. I was trying to save the output of scene.save_image() on Windows. During saving, there is a view that looks fine, but the saved images are blank black images for some reason. Adding flag visible=True did not help. Any advice would be much appreciated. Thanks!

**Comment by mikedh** [comment]
Hey, yeah unfortunately this comes up a bunch, and I no longer have a windows machine to debug this which makes it hard to help. What I said in #498:

>>Unfortunately I've had very mixed luck with diagnosing variants of this issue, though maybe there are some ideas in the previous threads.
That being said, if I were having this issue myself I would probably try every version of pyglet and see if any of them worked differently haha

I'll leave #498 open, and close this one.
