### ISSUE TITLE
misordering of the vertex indices from the return of TriMesh.faces

### ISSUE THREAD

**Issue by sw-gong** [mikedh/trimesh#511]
1. Load .ply with `trimesh.load` (`mesh`) and `plyfile.PlyData.read` (`data`) respectively.

2. Got triangles with `mesh.faces`, and `data['face']['vertex_indices']` respectively.

![image](https://user-images.githubusercontent.com/39670256/61978468-46b4b700-afe9-11e9-9726-4b66d2541aa6.png)

Generated faces are different as above. 

If I look at the neighboring vertices of node `0`, they do not contain vertices `1`, `2`, `3`, which shown in faces from `Data`.
![image](https://user-images.githubusercontent.com/39670256/61978561-75cb2880-afe9-11e9-9e43-a617516536cc.png)

Could anyone explain the difference to me? Additionally, I have tried other library like openmesh, which gives the same faces (triangles) like `PlyData`. Therefore, I think `trimesh` may reorder the mesh indices. Is that correct?

**Comment by mikedh** [comment]
Hey, yeah by default on load it will run vertex merging. You can disable it via `trimesh.load(file_name, process=False)`.

See other issues: https://github.com/mikedh/trimesh/issues/484

**Comment by sw-gong** [comment]
I see. Thanks!
