### ISSUE TITLE
python-blender version conflict

### ISSUE THREAD

**Issue by KEERTHANAUDAY** [mikedh/trimesh#513]
Hi, 
I use windows 10 and from the anaconda cloud used **conda install -c kitsune.one python-blender** (https://anaconda.org/kitsune.one/python-blender) to install a blender engine for the boolean operations but this seems to work only for python 3.7 (no lower version available for windows) but i get a **DLL load failed: The specified module could not be found.** error when i run trimesh on python 3.7. 
How can i get the blender engine active on windows in a compatible version for trimesh and python

**Comment by mikedh** [comment]
Hey, I would not use conda to install Blender, just use their regular install instructions: https://www.blender.org/download/

**Comment by KEERTHANAUDAY** [comment]
many thanks you for your response. Just to be clear, i could just install the software in a regular way and the engine will be identified in my script ?

**Comment by mikedh** [comment]
Yeah, it calls Blender using subprocess and it looks for the executable in your `PATH`, as well as some [search locations](https://github.com/mikedh/trimesh/blob/bb6389f785893733655ff6aae5a1ba0f789474c6/trimesh/interfaces/blender.py#L12-L27).

**Comment by KEERTHANAUDAY** [comment]
Thank you it works like a charm

**Comment by mikedh** [comment]
Great!
