### ISSUE TITLE
boolean operation failure in specific cases 

### ISSUE THREAD

**Issue by KEERTHANAUDAY** [mikedh/trimesh#519]
Hi,
I'm performing boolean operations using trimesh. 
My boolean fails in cases where the geometries have flushed ends. (please see image)
It is successful when negative geometry does not have overlapping  faces.
Is there any way I can have a clean boolean with overlapping meshes? 
![screenshot_2](https://user-images.githubusercontent.com/43433132/62249731-608c3a80-b3eb-11e9-95cc-c4c00422575e.jpg)

below is the code 
#================
#Mesh boolean in trimesh 
#================
boolean_1 = trimesh.Trimesh(vertices=vertices_1 , faces=face_1, process=False)
boolean_2 = trimesh.Trimesh(vertices=vertices_2 , faces=face_2, process=False)
boolean_sub = boolean_1 .difference(boolean_2, 'blender')

**Comment by mikedh** [comment]
Yeah mesh booleans are pretty unreliable in general, and the blender ones in particular. I would install OpenSCAD and give that a try, it is usually quite a bit more stable:
`boolean_sub = boolean_1 .difference(boolean_2, engine='scad')`

**Comment by molkoback** [comment]
Which Blender version are you using? 2.80 broke all the booleans in my software and I had to downgrade back to 2.79.

**Comment by KEERTHANAUDAY** [comment]
Thank you for your suggestions on making the boolean operation work better. 
I am using blender version 2.79
