### ISSUE TITLE
One-ring neighbourhood

### ISSUE THREAD

**Issue by Victordmdb** [mikedh/trimesh#52]
How would one go by getting an the [1 ring neighbhourhood ](https://bluntobject.wordpress.com/2007/03/13/mesh-data-structures-vol-2-vertex-one-rings/) for all vertices? I can see trimesh has functions for adjacent faces, but not for adjacent vertices.

**Comment by mikedh** [comment]
Ah, you probably want to create graph from edges_unique, like so:

```

In [1]: import trimesh

In [2]: m = trimesh.primitives.Sphere()

In [3]: m.edges_unique
Out[3]:
array([[  0, 538],
       [  0, 316],
       [  0, 317],
       ...,
       [255, 355],
       [255, 427],
       [511, 552]], dtype=int64)

In [4]: import networkx as nx

In [5]: g = nx.from_edgelist(m.edges_unique)

In [6]: m.edges_unique?
Type:        property
String form: <property object at 0x000001E7B61903B8>
Docstring:
The unique edges of the mesh.

Returns
----------
edges_unique: (n,2) int, set of vertex indices for unique edges

In [7]: g[0]
Out[7]: {248: {}, 249: {}, 316: {}, 317: {}, 538: {}}

In [8]: one_ring = [list(g[i].keys()) for i in range(len(m.vertices))]

In [9]: one_ring
Out[9]:
[[248, 249, 538, 316, 317],
 [572, 508, 284, 573, 509],
 [315, 314, 539, 250, 251],
 [506, 507, 285, 574, 575],
 [176, 412, 404, 589, 233],
 [410, 235, 418, 166, 591],
 [232, 177, 588, 405, 413],
 [234, 411, 419, 590, 167],
...
```

**Comment by Victordmdb** [comment]
Great, thanks! Then I guess I can use `radial_sort` to access them CW?

**Comment by mikedh** [comment]
Yeah, that should probably work using the vertex normal. I would probably try to find cycles in the graph to get an ordered list, and then do a check against the vertex normal to see if they need to be reversed or not:

```
one_ordered = [nx.cycle_basis(g.subgraph(i))[0] for i in one_ring]
```

**Comment by Victordmdb** [comment]
Awesome, thanks for your help

**Comment by nam-usth** [comment]
Thanks for your wonderful answer. May I ask about how to create a two-ring neighborhood since it's much more complicated than the one-ring version?
