### ISSUE TITLE
weighted vertex normal calculation produces NaNs

### ISSUE THREAD

**Issue by staubda** [mikedh/trimesh#522]
The new weighting scheme for calculating vertex normals is producing NaNs for a lot of my meshes. The source is the `summed_loop()` function in `trimesh/geometry.py`:

```
    def summed_loop():
        summed = np.zeros((vertex_count, 3), np.float64)
        for vertex_idx in np.arange(vertex_count):
            # loop over all vertices
            # compute normal contributions from surrounding faces
            # obviously slower than with the sparse matrix 
            face_idxs, inface_idxs = np.where(faces == vertex_idx)
            surrounding_angles = face_angles[face_idxs, inface_idxs]        
            summed[vertex_idx] = np.dot(surrounding_angles/surrounding_angles.sum(), face_normals[face_idxs])
        return summed
``` 

I'm encountering situations where `surrounding_angles.sum() = 0` due to vertices belonging to a single face, and that face having 2 identical vertices as corners. Not sure why such faces are in my data, but there seem to be a decent amount of them. 

Could we add something like:
```
        if surrounding_angles.sum() == 0:
            summed[vertex_idx] = np.mean(face_normals[face_idxs])
        else:
            summed[vertex_idx] = np.dot(surrounding_angles/surrounding_angles.sum(), face_normals[face_idxs])
```
to guard against this issue? @dbukenberger @mikedh

**Comment by mikedh** [comment]
Thanks for the report and tracing down the cause! I was seeing this intermittently as well, and I was able to minimally reproduce with:
```
m = g.trimesh.creation.box()
m.faces[0][0] = m.faces[0][1]
norm = m.vertex_normals
```

Those sparse matrices are a little finicky, after trying a few things it looked like the easiest thing to do was just filter out degenerate faces which I did by magnitude of normal. I should probably also add a  `face_ok = np.logical_and(face_ok, (face_angles > tol.merge).all(axis=1))`, the zero magnitude angles are really what kills the computation.

The face filtering and tests should be released shortly:
https://github.com/mikedh/trimesh/commit/55834e7add839a92fafb6ebcc672bb45267eb6ba

**Comment by staubda** [comment]
Thanks for the quick turnaround on this issue! 

Will this fix handle the situation I'm encountering, where a vertex belongs to only a single face, and that face has an invalid normal? Will that vertex be pruned somehow? If not will the size of the `vertices` and `vertex_normals` arrays be guaranteed to have a size mismatch?

**Comment by mikedh** [comment]
No worries! Hmm well if the face has an invalid normal it shouldn't be considered, and so the sum at that vertex should be zeros. 

Though if you have a minimal example (on a box or something) I can play with it and verify that.

**Comment by staubda** [comment]
Ah never mind, just tried your latest commits and everything looks good!
