### ISSUE TITLE
scene.show() used with kwargs causes segmentation fault

### ISSUE THREAD

**Issue by ssavary** [mikedh/trimesh#524]
I want to change the default flags by using the kwargs input of the show() function, but I'm getting a segmentation fault. 

The fault occurs in the update_flags() function, at the gl.glPolygonMode(gl.GL_FRONT_AND_BACK, gl.GL_FILL) call, which is the default case.

My code and kwarg structure are the following:

```
args = {'flags': {'cull': True, 'axis': True},}
scene.show('gl', **args)
```

*Note that setting the default flag values (False, False) also crashes.

Also, using scene.show() without arguments works fine.

I'm using Trimesh 1.3.11 and pyglet 1.4.1 on python 3.7.4 and OS X 10.14.4

**Comment by mikedh** [comment]
Hmm, maybe this is related to [this upstream pyglet issue](https://bitbucket.org/pyglet/pyglet/issues/199/attempting-to-resize-or-close-pyglet)? Closing as I'm not sure what we can do on the trimesh side to fix this.
