### ISSUE TITLE
Detect Unit of Length

### ISSUE THREAD

**Issue by infosisio** [mikedh/trimesh#525]
Would that be possible? If so, how?

**Comment by mikedh** [comment]
Hey, it depends a lot on whether the input format supports the concept of units. If the loader was able to extract them, they will be available as `mesh.units`. Which format are you working with? The only major mesh formats I can think of that support units are `3DXML` (from Solidworks, implicit mm), and `GLB` (implicit meters).

**Comment by infosisio** [comment]
@mikedh Mostly GLB, thanks mikedh.
