### ISSUE TITLE
how to color vertices on meshes and how to visualize several meshes in a row with some background?

### ISSUE THREAD

**Issue by sw-gong** [mikedh/trimesh#526]
Hi, 

Thanks for the good library.

May I ask how to color vertices on meshes and how to visualize several meshes in a row with a specific background?

**Comment by marcomusy** [comment]
possible solution with [vtkplotter](https://github.com/marcomusy/vtkplotter):
```python
import trimesh

mesh = trimesh.creation.icosphere()
mesh.visual.face_colors = [200, 200, 250, 100]


from vtkplotter import *

n = mesh.vertices.shape[0]

pc1 = Points(mesh.vertices, r=10)
#Assign a color to each vertex individually, 
# format can be integer, tuple, string name:
# (method name will change in future release)
pc1.colorVerticesByArray(range(n)) 

#Assign a color based on a scalar and a color map
pc2 = Points(mesh.vertices, r=10)
pc2.pointColors(mesh.vertices[:,2], cmap='viridis')

# Draw result on N=2 sync'd renderers, white background
show([(mesh,pc1), (mesh,pc2)], N=2, bg="white", axes=1)
```
![Screenshot from 2019-08-05 21-59-52](https://user-images.githubusercontent.com/32848391/62491594-ab7fc680-b7cc-11e9-8bfa-f7249bc9691f.png)

**Comment by sw-gong** [comment]
> possible solution with [vtkplotter](https://github.com/marcomusy/vtkplotter):
> 
> ```python
> import trimesh
> 
> mesh = trimesh.creation.icosphere()
> mesh.visual.face_colors = [200, 200, 250, 100]
> 
> 
> from vtkplotter import *
> 
> n = mesh.vertices.shape[0]
> 
> pc1 = Points(mesh.vertices, r=10)
> #Assign a color to each vertex individually, 
> # format can be integer, tuple, string name:
> # (method name will change in future release)
> pc1.colorVerticesByArray(range(n)) 
> 
> #Assign a color based on a scalar and a color map
> pc2 = Points(mesh.vertices, r=10)
> pc2.pointColors(mesh.vertices[:,2], cmap='viridis')
> 
> # Draw result on N=2 sync'd renderers, white background
> show([(mesh,pc1), (mesh,pc2)], N=2, bg="white", axes=1)
> ```
> 
> ![Screenshot from 2019-08-05 21-59-52](https://user-images.githubusercontent.com/32848391/62491594-ab7fc680-b7cc-11e9-8bfa-f7249bc9691f.png)

I have tried your code and it shows the below error:
![image](https://user-images.githubusercontent.com/39670256/62492713-3bbb0d00-b7c7-11e9-901f-96db62c68e2a.png)

Do you know the reason?

**Comment by sw-gong** [comment]
![image](https://user-images.githubusercontent.com/39670256/62493345-c3ede200-b7c8-11e9-962f-1d0fb6b4f40b.png)

Do you know how to draw 3d shapes like this? It includes drawing meshes in a row with a white background and color each vertex with some consistent values

**Comment by mikedh** [comment]
You could also use a `trimesh.Scene` object (or check out the `widget` example for something more advanced):
```
mikedh@cue:~$ ipython -i
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import trimesh

In [2]: meshes = [trimesh.creation.uv_sphere() for i in range(10)]

In [3]: for i, m in enumerate(meshes):
   ...:     m.apply_translation([0,0, i*2])
   ...:     m.visual.vertex_colors = trimesh.visual.random_color()
   ...:     

In [6]: trimesh.Scene(meshes).show()

```
![balls](https://user-images.githubusercontent.com/1403074/62493522-57122200-b79f-11e9-8020-6e291f568bae.png)

**Comment by sw-gong** [comment]
> You could also use a `trimesh.Scene` object (or check out the `widget` example for something more advanced):
> 
> ```
> mikedh@cue:~$ ipython -i
> Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import trimesh
> 
> In [2]: meshes = [trimesh.creation.uv_sphere() for i in range(10)]
> 
> In [3]: for i, m in enumerate(meshes):
>    ...:     m.apply_translation([0,0, i*2])
>    ...:     m.visual.vertex_colors = trimesh.visual.random_color()
>    ...:     
> 
> In [6]: trimesh.Scene(meshes).show()
> ```
> 
> ![balls](https://user-images.githubusercontent.com/1403074/62493522-57122200-b79f-11e9-8020-6e291f568bae.png)

Awesome! One more question, If I know each vertex is related to some value, I want to color vertices based on these values (ideally, values from low to high are related to a color map). Do you know how to draw like this way?

**Comment by mikedh** [comment]
Hey, yeah you could use `trimesh.visual.interpolate` for that:
```
In [1]: import trimesh

In [2]: import numpy as np

In [3]: meshes = [trimesh.creation.uv_sphere() for i in range(10)]

In [4]: trimesh.visual.interpolate?
Signature: trimesh.visual.interpolate(values, color_map=None, dtype=<class 'numpy.uint8'>)
Docstring:
Given a 1D list of values, return interpolated colors
for the range.

Parameters
---------------
values : (n, ) float
  Values to be interpolated over
color_map : None, or str
  Key to a colormap contained in:
  matplotlib.pyplot.colormaps()
  e.g: 'viridis'

Returns
-------------
interpolated : (n, 4) dtype
  Interpolated RGBA colors
File:      ~/trimesh/trimesh/visual/color.py
Type:      function

In [5]: for i, m in enumerate(meshes):
   ...:     m.vertices *= (np.random.random(3) + 1 ) * 2
   ...:     m.apply_translation([0,0, i*6])
   ...:     
   ...:     radii = np.linalg.norm(m.vertices - m.center_mass, axis=1)
   ...:     m.visual.vertex_colors = trimesh.visual.interpolate(radii, color_map='viridis')
   ...:     

In [6]: trimesh.Scene(meshes).show()
```
![balls](https://user-images.githubusercontent.com/1403074/62499585-410d5d00-b7b1-11e9-901e-6b426f6e70d4.png)

**Comment by marcomusy** [comment]
> I have tried your code and it shows the below error:
> ![image](https://user-images.githubusercontent.com/39670256/62492713-3bbb0d00-b7c7-11e9-901f-96db62c68e2a.png)
> 
> Do you know the reason?

Oh, that's because jupyter notebook rendering does not support more than one rendering window (I will add a more meaningful error message)..
You need to add `embedWindow(False)` in that case. Otherwise try:
(this should also work in jupyter)
```python
import trimesh

meshes = [trimesh.creation.uv_sphere().apply_translation([0,0,i*2]) for i in range(3)]


from vtkplotter import trimesh2vtk, show

vtkmeshes = [trimesh2vtk(m) for m in meshes]

for i in range(3):
	scals = vtkmeshes[i].coordinates()[:,i] # define some dummy point scalar
	vtkmeshes[i].pointColors(scals, cmap='jet')

show(vtkmeshes, bg='w', axes=1)
```
![Screenshot from 2019-08-06 12-51-23](https://user-images.githubusercontent.com/32848391/62534426-6c438b00-b849-11e9-86fb-c8623fb385cf.png)

**Comment by sw-gong** [comment]
> Hey, yeah you could use `trimesh.visual.interpolate` for that:
> 
> ```
> In [1]: import trimesh
> 
> In [2]: import numpy as np
> 
> In [3]: meshes = [trimesh.creation.uv_sphere() for i in range(10)]
> 
> In [4]: trimesh.visual.interpolate?
> Signature: trimesh.visual.interpolate(values, color_map=None, dtype=<class 'numpy.uint8'>)
> Docstring:
> Given a 1D list of values, return interpolated colors
> for the range.
> 
> Parameters
> ---------------
> values : (n, ) float
>   Values to be interpolated over
> color_map : None, or str
>   Key to a colormap contained in:
>   matplotlib.pyplot.colormaps()
>   e.g: 'viridis'
> 
> Returns
> -------------
> interpolated : (n, 4) dtype
>   Interpolated RGBA colors
> File:      ~/trimesh/trimesh/visual/color.py
> Type:      function
> 
> In [5]: for i, m in enumerate(meshes):
>    ...:     m.vertices *= (np.random.random(3) + 1 ) * 2
>    ...:     m.apply_translation([0,0, i*6])
>    ...:     
>    ...:     radii = np.linalg.norm(m.vertices - m.center_mass, axis=1)
>    ...:     m.visual.vertex_colors = trimesh.visual.interpolate(radii, color_map='viridis')
>    ...:     
> 
> In [6]: trimesh.Scene(meshes).show()
> ```
> 
> ![balls](https://user-images.githubusercontent.com/1403074/62499585-410d5d00-b7b1-11e9-901e-6b426f6e70d4.png)

Hi,

I still have a few questions:
- Is it possible to plot the color map bar on the below of meshes as the picture I attached before?
- Is it possible to export this `trimesh.scene` (multiple meshes) to `.ply` or other files or save a screen shot of it to `png`?
- Do I need to mannually find a _correct_ translation value within meshes (as you set `m.apply_translation([0,0, i*6])`, but for other meshes, this may not be true)? Or is there any convenient way to set it?

**Comment by jrdkr** [comment]
Hey,
first of all thank you for this awesome library!!!
I am also very interested in a visualiziation of the colorbar.

**Comment by gauzias** [comment]
Hi,
here is a function to plot a separate figure with the colormap before showing the pyglet figure.
It would clearly be better to plot the colorbar within the same figure, but I don't know how to do that.

Hope it helps


import trimesh
import numpy as np
import matplotlib.pyplot as plt

def pyglet_plot(mesh, values=None, color_map=None,
                plot_colormap=False, caption=None):
    """
    Visualize a trimesh object using pyglet as proposed in trimesh
    the added value is for texture visualization
    :param mesh: trimesh object
    :param values: numpy array of a texture to be visualized on the mesh
    :param color_map: str, matplotlib colormap, default is 'jet'
    :param plot_colormap: Boolean, if True use matplotlib to plot the colorbar
     of the map on a separate figure
    :param caption: Title of window
    :return:
    """

    if values is not None:
        smooth = True
        if color_map is None:
            color_map = 'jet'

        vect_col_map = \
            trimesh.visual.color.interpolate(values, color_map=color_map)

        if values.shape[0] == mesh.vertices.shape[0]:
            mesh.visual.vertex_colors = vect_col_map
        elif values.shape[0] == mesh.faces.shape[0]:
            mesh.visual.face_colors = vect_col_map
            smooth = False

        if plot_colormap:
            gradient = np.linspace(0, 1, 256)
            gradient = np.vstack((gradient, gradient))
            fig, ax = plt.subplots(1, 1)
            # fig.subplots_adjust(top=0.95, bottom=0.05, left=0.01, right=0.99)

            ax.set_title(caption)
            ax.imshow(gradient, aspect='auto', cmap=plt.get_cmap(color_map))
            pos = list(ax.get_position().bounds)
            y_text = pos[1] + pos[3] / 2.
            fig.text(pos[0] - 0.01, y_text,
                     '{:0.0000009f}'.format(np.min(values)),
                     va='center', ha='right', fontsize=15, color='k')
            fig.text(pos[2] + pos[0] + 0.01, y_text,
                     '{:0.0000009f}'.format(np.max(values)),
                     va='center', fontsize=15, color='k')
            ax.set_axis_off()
            plt.show()

    # call the default trimesh visualization tool using pyglet
    mesh.show(caption=caption, smooth=smooth)

**Comment by jrdkr** [comment]
Hey Gauzias,
Thank you!
I also noticed the tutorials for the vtkplotter library e.g. : https://github.com/marcomusy/vtkplotter/blob/master/examples/advanced/moving_least_squares3D.py that helped a lot!
Greetings, Julian

**Comment by marcomusy** [comment]
> Hey Gauzias,
> Thank you!
> I also noticed the tutorials for the vtkplotter library e.g. : https://github.com/marcomusy/vtkplotter/blob/master/examples/advanced/moving_least_squares3D.py that helped a lot!
> Greetings, Julian

you can add a 2D scalarbar with e.g.:
```python
import trimesh

meshes = [trimesh.creation.uv_sphere().apply_translation([0,0,i*2]) for i in range(3)]


from vtkplotter import trimesh2vtk, show

vtkmeshes = [trimesh2vtk(m) for m in meshes]

for i in range(3):
	scals = vtkmeshes[i].coordinates()[:,i] # define some dummy point scalar
	vtkmeshes[i].pointColors(scals, cmap='jet')

vtkmeshes[0].addScalarBar(title="my scalarbar")

show(vtkmeshes, bg='w', axes=1)
```
![Screenshot from 2019-08-09 15-38-54](https://user-images.githubusercontent.com/32848391/62783116-03177e00-babc-11e9-8c32-eda97fe4c258.png)

**Comment by sw-gong** [comment]
> > Hey Gauzias,
> > Thank you!
> > I also noticed the tutorials for the vtkplotter library e.g. : https://github.com/marcomusy/vtkplotter/blob/master/examples/advanced/moving_least_squares3D.py that helped a lot!
> > Greetings, Julian
> 
> you can add a 2D scalarbar with e.g.:
> 
> ```python
> import trimesh
> 
> meshes = [trimesh.creation.uv_sphere().apply_translation([0,0,i*2]) for i in range(3)]
> 
> 
> from vtkplotter import trimesh2vtk, show
> 
> vtkmeshes = [trimesh2vtk(m) for m in meshes]
> 
> for i in range(3):
> 	scals = vtkmeshes[i].coordinates()[:,i] # define some dummy point scalar
> 	vtkmeshes[i].pointColors(scals, cmap='jet')
> 
> vtkmeshes[0].addScalarBar(title="my scalarbar")
> 
> show(vtkmeshes, bg='w', axes=1)
> ```
> 
> ![Screenshot from 2019-08-09 15-38-54](https://user-images.githubusercontent.com/32848391/62783116-03177e00-babc-11e9-8c32-eda97fe4c258.png)

Hi @marcomusy ,

I installed vtkplotter with `pip install vtkplotter`, but it shows the error `ImportError: cannot import name 'trimesh2vtk'`. Do you know why it is? Additionally, can you plot things without the background (only white) if using your library?

**Comment by marcomusy** [comment]
sorry, can you try:
```python
from vtkplotter import show
from vtkplotter.trimesh import trimesh2vtk

# to eliminate axes
show(vtkmeshes, bg='white', axes=0)
```

**Comment by jrdkr** [comment]
> > > Hey Gauzias,
> > > Thank you!
> > > I also noticed the tutorials for the vtkplotter library e.g. : https://github.com/marcomusy/vtkplotter/blob/master/examples/advanced/moving_least_squares3D.py that helped a lot!
> > > Greetings, Julian
> > 
> > 
> > you can add a 2D scalarbar with e.g.:
> > ```python
> > import trimesh
> > 
> > meshes = [trimesh.creation.uv_sphere().apply_translation([0,0,i*2]) for i in range(3)]
> > 
> > 
> > from vtkplotter import trimesh2vtk, show
> > 
> > vtkmeshes = [trimesh2vtk(m) for m in meshes]
> > 
> > for i in range(3):
> > 	scals = vtkmeshes[i].coordinates()[:,i] # define some dummy point scalar
> > 	vtkmeshes[i].pointColors(scals, cmap='jet')
> > 
> > vtkmeshes[0].addScalarBar(title="my scalarbar")
> > 
> > show(vtkmeshes, bg='w', axes=1)
> > ```
> > 
> > 
> > ![Screenshot from 2019-08-09 15-38-54](https://user-images.githubusercontent.com/32848391/62783116-03177e00-babc-11e9-8c32-eda97fe4c258.png)
> 
> Hi @marcomusy ,
> 
> I installed vtkplotter with `pip install vtkplotter`, but it shows the error `ImportError: cannot import name 'trimesh2vtk'`. Do you know why it is? Additionally, can you plot things without the background (only white) if using your library?

Had the same problem. You have to clone the current release here from github. in the version of pip these file are missing yet. And it is possible to set a white background. See the following tutorial:

https://github.com/marcomusy/vtkplotter/blob/master/examples/advanced/fitspheres1.py

**Comment by sw-gong** [comment]
> sorry, can you try:
> 
> ```python
> from vtkplotter import show
> from vtkplotter.trimesh import trimesh2vtk
> 
> # to eliminate axes
> show(vtkmeshes, bg='white', axes=0)
> ```

Thanks!

![image](https://user-images.githubusercontent.com/39670256/62789918-df573680-bac1-11e9-8861-bc0897003c24.png)

It works and looks really nice! 

Does the viewer support actions like the viewer used in trimesh like below?
![image](https://user-images.githubusercontent.com/39670256/62790081-352bde80-bac2-11e9-8965-9ac86f16759d.png)

How to export this mesh or this view?

Addtionally, when view from jupyter notebook, I set `embedWindow(False)`, the kernel died every time.

**Comment by marcomusy** [comment]
@sw-gong 
> Does the viewer support actions like the viewer used in trimesh like below?

Yes, press `h` in window and it will show (in terminal) a helper message with all different options

> How to export this mesh or this view?

Press `S` to a png screenshot or `E` to export all meshes to a single numpy file (this is still experimental, different color mappings are not yet supported). Or can save individual meshes in various formats with e.g. `actor.write('mesh.ply')`

>Addtionally, when view from jupyter notebook, I set embedWindow(False), the kernel died every time.

Thanks I will investigate the issue..

**Comment by sw-gong** [comment]
Hi @marcomusy,

Is that possible to export mesh (.ply) with vertices color?

**Comment by mikedh** [comment]
Hey, if the colors are set in `mesh.visual.vertex_colors` they should export when you save it as `ply`. If they are set, `mesh.visual.kind == 'vertex'` should be true.

**Comment by marcomusy** [comment]
@sw-gong sorry for the late reply, 
yes - you should be able to do it with the latest version:
`pip install --upgrade vtkplotter`

then
```python
from trimesh.creation import uv_sphere

meshes = [uv_sphere().apply_translation([0,i*2.1,0]) for i in range(3)]

###############################################
from vtkplotter import trimesh2vtk, show

vtkmeshes = trimesh2vtk(meshes)

cmaps = ('jet', 'PuOr', 'viridis')
for i in range(3):
    scals = vtkmeshes[i].coordinates()[:,i] # define some dummy point scalar
    vtkmeshes[i].pointColors(scals, cmap=cmaps[i]).lighting('plastic')

# add a 2D scalar bar to a mesh
vtkmeshes[0].addScalarBar(title="my scalarbar\nnumber #0", c='k')
         
# add 3D scalar bars
vtkmeshes[1].addScalarBar3D(pos=(1.2,2.1,-1.0), c='k')
vtkmeshes[2].addScalarBar3D(pos=(1.4,4.2,-0.5), c='k',
                            title='A viridis\nscalarbar to play with',
                            titleXOffset=-2,
                            titleSize=1.5)

show(vtkmeshes, bg='white', axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/62945621-6157a000-bddf-11e9-9b1b-fe727ef7b0e2.png)
note that 
- you should now import `trimesh2vtk` directly as shown above.
- you don't need to iterate over the meshes to be converted.
- can save `ply` files with color info. (see [example](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/scalarbars.py)), but some some reason that doesnt work for the above example, so better follow the suggestion from mikedh.

> Addtionally, when view from jupyter notebook, I set embedWindow(False), the kernel died every time.

If the problem persists in the latest version please open a issue at
https://github.com/marcomusy/vtkplotter/issues

Thanks for reporting and for your feedback,
Best

**Comment by sw-gong** [comment]
Thanks! @marcomusy  @mikedh

**Comment by ZENGYIMING-EAMON** [comment]
Hey guys! Your images are so great! Is it possible to show them screenless (as folder/xxx.png) when using a remote server without x11 or screen? (instead of a pop-up window every time)

**Comment by marcomusy** [comment]
@ZENGYIMING-EAMON yes check out https://github.com/marcomusy/vedo/issues/64

**Comment by miaoYuanyuan** [comment]
> 
how can i calculate the error? np.linalg.norm(mesh.vertices-label.vertices,axis=1)?

**Comment by Nibenitez** [comment]
@sw-gong Do you have the script to create the face heatmap? I am working on a 3d face reconstruction project, so I am wonder how I can have my error distances results calculated and displayed as a heatmap.

![image](https://github.com/mikedh/trimesh/assets/51408311/26bafc03-94d4-4f8b-8cb5-2ccdc0bf7d8e)

**Comment by FarzanehJafari1987** [comment]
> ```python
> from vtkplotter import show
> from vtkplotter.trimesh import trimesh2vtk
> 
> # to eliminate axes
> show(vtkmeshes, bg='white', axes=0)
> ```


> @sw-gong Do you have the script to create the face heatmap? I am working on a 3d face reconstruction project, so I am wonder how I can have my error distances results calculated and displayed as a heatmap.
> 
> ![image](https://private-user-images.githubusercontent.com/51408311/259128771-26bafc03-94d4-4f8b-8cb5-2ccdc0bf7d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMTcwNzUsIm5iZiI6MTcyMjExNjc3NSwicGF0aCI6Ii81MTQwODMxMS8yNTkxMjg3NzEtMjZiYWZjMDMtOTRkNC00ZjhiLThjYjUtMmNjZGMwYmY3ZDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDIxNDYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MWI5ZGY5NDU5ODMxYjg1Y2M4YTExNjkxN2FhMTQwN2U4NzZlOTJkMWVmYzFhNGY3NmI4NjExZjFlNzgxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w9N0i8TCY_EsUjnAvZ-lY0NO5hak7fTjEhuHpSVdl3E)

I have the same issue. Could find a way to visualize the distance results?

**Comment by marcomusy** [comment]
> I have the same issue. Could find a way to visualize the distance results?

Try:
```py
import numpy as np
from trimesh.creation import uv_sphere
from vedo import Mesh, show

tmsh = uv_sphere() # trimesh object
vmsh = Mesh(tmsh)  # vedo object

# Add a scalar field to the mesh 
scalar_field = np.random.randn(vmsh.npoints)
vmsh.cmap("viridis", scalar_field)
vmsh.add_scalarbar3d(title="residuals")

show(vmsh, axes=1)
```

![image](https://github.com/user-attachments/assets/0d56103e-ed9d-40db-a2e5-ba4cb34a8e49)
