### ISSUE TITLE
Killed by system when running signed_distance() on ShapeNet data.

### ISSUE THREAD

**Issue by LYHTHU** [mikedh/trimesh#527]
Hi,
I am using trimesh to process shapenet. And I use sample_surface and signed_distance to sampling vertices near surfaces. However, the program is killed by system somewhere. 

I guess it is due to memory issues. But I cannot make sure. 

Thanks.

**Comment by JeremyFisher** [comment]
I had similar problems. Just run htop to see how much memory signed_distance is eating, it can be 
quite a lot. Increasing your SWAP might help.

Also, you can split your grid into smaller batches. If I want to use 128^3 resolution for instance, I 
usually split my grid into batches of size 128. It takes a lot of time to generate SDFs, but thats 
a different story...

**Comment by mikedh** [comment]
Yeah, `signed_distance` isn't particularly fast or efficient, I would reduce the point count as Jeremy suggested. Performance PR's welcome!
