### ISSUE TITLE
blend meshes

### ISSUE THREAD

**Issue by oarriaga** [mikedh/trimesh#532]
Hi,
I was wondering if someone knows if it would be possible to blend or extend meshes as seen in the image below?

![image](https://user-images.githubusercontent.com/5577137/63010387-9965ee00-be86-11e9-8ae4-e105df14b082.png)

thank you! :)

**Comment by mikedh** [comment]
Hey, you could make up a transform function for the vertices for simple cases (i.e. translate vertex as a function of distance from cylinder axis or something), or probably a better way would be to to [rig it in blender](https://www.youtube.com/watch?v=Ke1tiWBKx28).

**Comment by oarriaga** [comment]
Hi thank you for answering so fast!
yes I am trying to avoid blender/blender-API in replacement of trimesh/pyrender :)
I will try and post here any results.

**Comment by mikedh** [comment]
One approach to solve this that would be pretty cool (PR's super welcome :wink:) would be to add skeleton support. 

- check out the [GLTF](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0) data structure for skeletons and skins as a starting point
- implement a `KinematicTree` class, `Skeleton` class, or something, which transforms mesh vertices based on link transforms
- create a simple skeleton for your mesh, and then move the skeleton around.


Here's some old prototype code I started on a while back but never finished for a kinematic tree.  It seems like skeleton forward kinematics is probably pretty similar (although I really have no idea haha):
[kinematic.py](https://www.dropbox.com/s/dgqkhv844h8xs4u/kinematic.py?dl=0)
[irb140.zip](https://www.dropbox.com/s/0i1u43z9ff8yctt/irb140.zip?dl=0)
