### ISSUE TITLE
suppress openscad message and hanging process

### ISSUE THREAD

**Issue by pmayostendorp** [mikedh/trimesh#533]
I see the following log message when I import `trimesh`.

```
searching for scad in: PATH IN MY VIRTUAL ENVIRONMENT...
```

This also appears to spawn a process with a GUI (when run on macOS this is very conspicuous due to a dock icon). I've had some difficulty tracing down the spawned process with a `ps -ef | grep` call, but I assume it relates to scad. Is there a way to suppress either one of these behaviors without much hassle?

**Comment by pmayostendorp** [comment]
Environment is:
Python 3.7.3
trimesh 3.1.11

**Comment by mikedh** [comment]
Hey, yeah that message should be `log.debug`, not `log.warning`, I'll fix it. 

I just imported on OSX for the first time in a while, and I don't see any GUI icons on trimesh import, what does the icon look like? My guess would be not SCAD but something trying to get X11.

Thanks for the report!

**Comment by pmayostendorp** [comment]
Ah great, makes sense re: the message.

On the icon, I see the following. The OS seems to treat it as a hung process. It's name is simply "python":
![image](https://user-images.githubusercontent.com/4366484/63040304-6a4d7d80-be82-11e9-9cd9-5494ecf39878.png)

**Comment by mikedh** [comment]
Hmm, if you run `python` from the command line, it only shows up when you manually type `import trimesh`? i.e.:

```
cue-4:images mikedh$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import trimesh
```

**Comment by pmayostendorp** [comment]
Yes, that's how I generated this one. I also see this from imports in our main scripts/applications as well as from Jupyter notebooks.

**Comment by mikedh** [comment]
Ah, maybe try importing our soft dependencies one by one at the REPL to see if it's something upstream or us:

https://github.com/mikedh/trimesh/blob/fc09589ee7e52553c0d0ad53a75d0a1b9c1aba1f/setup.py#L22-L37

**Comment by pmayostendorp** [comment]
Alas, can't reproduce with those imports. Looks like I'm missing pillow, but as a soft dependency it isn't giving me problems in our current use cases.

**Comment by pmayostendorp** [comment]
I'm going to close this one out. Yes, this behavior is present, but I'm not seeing any adverse effects like hung processes that are chewing up cycles. It's just odd.
