### ISSUE TITLE
Non watertight convex hull

### ISSUE THREAD

**Issue by kajah3** [mikedh/trimesh#535]
While working on some non-watertight meshes I stumbled upon some cases where the convex hull of the mesh is itself not watertight. This seemed like an impossibility to me given the definition of a convex hull, but I might be mistaken.

Here is a toy mesh showing the problem. The mesh is a box with midpoint vertices on two opposite faces that mess up the triangulation. Note the problem seem to be numerically sensitive as I could not reproduce it without creating the vertices with full precision.

vertices = [
[ 1.1401425700290290e-17, -4.3315263802832816e-18, 2.3684443826293873e-15],
[-1.6848384175192468e-04,  6.4008854840728831e-05, -3.4999535940647392e-02],
[ 5.0082117119665175e-05,  3.0000347599799793e+00, 5.4863685178368022e-03],
[-1.1840172468925323e-04,  3.0000987688348197e+00, -2.9513167422819793e-02],
[-7.9999073067404058e-01,  6.3121913840662180e-06, 3.8510772244859681e-03],
[-8.0015921451588723e-01,  7.0321046452193308e-05, -3.1148458716165287e-02],
[-7.9994064855697788e-01,  3.0000410721711361e+00, 9.3374457423202589e-03],
[-8.0010913239879633e-01,  3.0001050810262040e+00, -2.5662090198352451e-02],
[-4.1516367537904036e-01,  6.7283304121837183e-05, -3.3001789630778537e-02],
[-4.1511359326192082e-01,  3.0001020432843286e+00, -2.7515421112965007e-02],
[-3.8516402297873481e-01,  6.7046596944979594e-05, -3.3146205026725502e-02],
[-3.8511394086161543e-01,  3.0001018065771512e+00, -2.7659836508911968e-02]]

faces = [
 [ 6,  4,  0],
 [ 2,  3, 11],
 [ 6,  2,  9],
 [ 9,  7,  6],
 [11,  9,  2],
 [ 4,  5,  8],
 [ 0,  8, 10],
 [ 8,  0,  4],
 [10,  1,  0],
 [ 3,  2,  0],
 [ 7,  3,  1],
 [ 6,  7,  5],
 [ 1,  5,  7],
 [ 5,  4,  6],
 [ 0,  1,  3],
 [ 0,  2,  6]]

toy_mesh = trimesh.base.Trimesh(faces=faces, vertices=vertices)
print(toy_mesh.is_watertight)
print(toy_mesh.convex_hull.is_watertight)

**Comment by mikedh** [comment]
Ah yeah, the output from scipy/qhull is somewhat sensitive to numerical precision issues and doesn't necessarily make hard guarantees here.
