### ISSUE TITLE
Get colors from a voxelized mesh

### ISSUE THREAD

**Issue by kerighan** [mikedh/trimesh#536]
I use the Trimesh package as a way to handle obj files. I use the voxelized() function from a mesh and use the matrix property to get every cube position. But I would like to get the main color of each cube as well (maybe as an average of the colors of the faces there). I couldn't find any way to do this, and I think it is not implemented.

Does anyone have an idea how to get from a regular voxelized mesh the color of the cubes ? Thank you very much for your help.

```python
import trimesh

mesh = trimesh.load("filename.obj")
mesh_voxelized = mesh.voxelized(.1).hollow()
mesh_voxelized.matrix  # here to get the cube's existence / position
# Ideally I would need something like `mesh_voxelized.colors` in the same format
```

**Comment by jackd** [comment]
As far as I'm aware there's no straight forward way of doing this implemented as is. If you're meshes/voxel grids are sufficiently small, you could try:

* getting the coordinates of each voxel (`mesh_voxelized.points`)
* use `np.argmin` and `trimesh.points.point_plane_distance` looping of `mesh.faces` and `mesh.face_normals` to find the closest face to each point (you could probably vectorize `point_plane_distance` to do it in one shot - though memory might be an issue for a large number of points/faces).
* extract the color from the closest face (depending on how it's stored - I haven't looked into `visuals` all that much.

Alternatively, it may be faster to sample a point cloud from the surface of the mesh, color that cloud somehow and use a KDTree to find nearest neighbors. It wouldn't be -quite- as "exact" (though that's not all that well defined in this context), but for a large number of points/faces KDTrees should blitz it performance-wise.
