### ISSUE TITLE
Extended functionality of trimesh.creation.sweep_polygon() method

### ISSUE THREAD

**Issue by jciskey** [mikedh/trimesh#537]
Would there be interest in including an extended implementation of the sweep_polygon method that handles holes inside the initial polygon being extruded? I've found it to be useful for producing models that have "tunnels" inside.

I've uploaded an example model of a swept triangular polygon with multiple holes inside, producing a mesh with tunnels inside, to show what this sort of output can look like.

https://inceptive-public-shared-files.s3-us-west-2.amazonaws.com/github/test_sweep_with_multiple_tunnels_and_multiple_turns_scaled.glb

**Comment by mikedh** [comment]
Oh neat, that worked pretty well on your example mesh! Yeah PR's would be super welcome, let me know if I can help with anything!
