### ISSUE TITLE
mesh.contains issue ?

### ISSUE THREAD

**Issue by oliverstefanov** [mikedh/trimesh#545]
Hi,

How robust is the mesh.contains/signed_distance function?
It works reasonably well most of the time but I'll occasionally have a few points that are considered to be inside instead of outside the watertight mesh whereas the rest of the points are correctly evaluated.

I'm using trimesh 3.2.12 installed via conda on Win7. I installed pyembree for improved raytracing just in case but it did not make a difference.

I know my description is pretty vague, but do you have any idea as to why this could be ? It seems that i am not the only one having issues with this (cf. #242). 

Any other alternatives ?

**Comment by benoitrosa** [comment]
Hi,

Having the same issue here. Even with an STL containing a simple sphere, the signed_distance function gives all negative results. 

The python/cython method in your referenced bug report (242) is more robust and solved my problem !

**Comment by mikedh** [comment]
Hey, yeah it is squirrely in some instances but  it should probably be OK on a sphere. Did you load the mesh with `trimesh.load(file_name, use_embree=False)`?

I'm going to close to combine this issue with the other one.
