### ISSUE TITLE
Segmentation fault when loading mesh several times

### ISSUE THREAD

**Issue by benoitrosa** [mikedh/trimesh#550]
Hi,

The following code produces a segfault on my system (Ubuntu 16.04): 

`import trimesh
import numpy as np

mesh = trimesh.load('dummy.stl')

prox = trimesh.proximity.ProximityQuery(mesh)

print prox.signed_distance(np.array([[0,0,0],[200,200,200]]))

mesh = trimesh.load('dummy.stl')
prox = trimesh.proximity.ProximityQuery(mesh)`

I'm not sure where it comes from, but a few observations : 

- The signed distance call can be moved before or after the new mesh loading, it doesn't change much (but sometimes it does not segfault)

- When loading the mesh a second time, if that's not the same mesh but another one it doesn''t change anything

- If the newly loaded mesh variable is called "mesh2" it does not segfault

- If we still load the second mesh into the "mesh" variable, but create another instance of ProximityQuery called "prox2", the segfault disappears

To me all of this makes it look like the problem is a memory management problem somewhere in the ProximityQuery class

**Comment by mikedh** [comment]
Hmm, I suspect `rtree`, but I am unable to reproduce with my install. Could you get a backtrace with gdb or [faulthandler](https://blog.richard.do/2018/03/18/how-to-debug-segmentation-fault-in-python/)?

**Comment by benoitrosa** [comment]
I attached a text file with a backtrace. A few more pointers : 

- When I run the above code after a fresh restart, it does NOT produce a segfault

- If I add a few queries of "print prox.signed_distance(np.array([[0,0,0],[200,200,200]]))" at the end of the file and re-run the program, it does now segfault

- After that, the original script also segfaults

- Adding `use_embree = False` in the mesh loading removes all segfaults



[backtrace_gdb.txt](https://github.com/mikedh/trimesh/files/3624958/backtrace_gdb.txt)

**Comment by mikedh** [comment]
Thanks for the backtrace! Looks like it's in the `pyembree` destructor.

**Comment by mikedh** [comment]
I think this is an upstream issue which is tough to address at the trimesh level, so I'm going to close for now.
