### ISSUE TITLE
How to debug trimesh?

### ISSUE THREAD

**Issue by zhangxiaodi** [mikedh/trimesh#551]
when i load a mesh model and invoke scence.show(), the segment fault is coming and the screen is run a second then close. So i don't know how to find this error. So who can give me some advice?

**Comment by mikedh** [comment]
I'd suggest trying to get a backtrace with gdb or [faulthandler](https://blog.richard.do/2018/03/18/how-to-debug-segmentation-fault-in-python/) to debug.
