### ISSUE TITLE
Mesh reordered silently

### ISSUE THREAD

**Issue by pimdh** [mikedh/trimesh#552]
Hi,

Thanks for making this package. It's very helpful. However, the ordering of meshes is changed silently all the time, which is very inconvenient, as vertex indices are meaningful in my application.

Maybe this can be clarified in docs?

Vertex indices are re-ordered when:
- `trimesh.Trimesh(vertices=..., faces=..., process=True)`, this is to be expected
- export to ply binary, this unexpected [no reordering for export to ascii]
- `load_mesh(path)` from ply ascii. `load_mesh(path, process=False)` does not reorder. This is unclear from docs.

Maybe some of these can be addressed by setting `process=False` as default?

**Comment by mikedh** [comment]
Hey, yeah we've run in to this a number of times, I wrote an explanation of my [thinking here](https://github.com/mikedh/trimesh/issues/484#issuecomment-508835694). In the README, this line was meant to make this clear, although perhaps it needs some text containing the phrase "re-order":
```
# by default, Trimesh will do a light processing, which will
# remove any NaN values and merge vertices that share position
# if you want to not do this on load, you can pass `process=False`
mesh = trimesh.Trimesh(vertices=[[0, 0, 0], [0, 0, 1], [0, 1, 0]],
                       faces=[[0, 1, 2]],
                       process=False)
```

With regards to binary PLY exports re-ordering, I took a quick look and it [wasn't obviously](https://github.com/mikedh/trimesh/blob/2b1d3fabe955f41df0a4605cc043844d62b41e00/trimesh/exchange/ply.py#L150-L153) doing that. How were you verifying that the order changed?

Thanks for the report!

**Comment by pimdh** [comment]
Ah, apologies. Binary export didn't actually cause re-ordering, but it was
the unexpected `process=True` of `load_mesh`.

>
