### ISSUE TITLE
Reduce number of triangles/vertices

### ISSUE THREAD

**Issue by ShenkieRuben** [mikedh/trimesh#554]
I have a basic question. I have shape meshes containing around 50,000 faces and/or vertices and I would like to 'downsample' the number of faces and/or vertices. I found the function trimesh.base.merge_vertices() right now but I am not sure if that is the correct way to downsample in trimesh. There is a parameter digits which reindex faces to reference same index for both vertices, but if I set this value to 1, it will result in too few vertices (around 100) and if i set it to 2 it will result in around 1800 vertices. However, if i set the value to a higher number, the number of vertices will remain the same. I also use trimesh.base.remove_degenerate_faces() and trimesh.base.remove_duplicate_faces() to remove the faces after the vertices have been merged.

I was wondering if there are functions that give more of a fine-grained control to downsample the mesh, such that I can downsample it to around 8000 vertices/faces. I was also wondering if this is the correct to do this.

**Comment by bbarroqueiro** [comment]
if i understood correctly, you want some quadratic edge collapse algorithm to simplify your mesh, but it not available...

but if you have gmsh-sdk installed you can remesh your part....

''
import sys, gmsh
gmsh.initialize(sys.argv)
gmsh.option.setNumber("General.Terminal", 1)
gmsh.model.add('Remesh_stl')
gmsh.merge("Mesh2.stl")
gmsh.model.mesh.createGeometry()
gmsh.model.geo.synchronize()
gmsh.model.mesh.generate(2)
gmsh.write("remeshed_mesh.stl")
''

**Comment by mikedh** [comment]
@bbarroqueiro oh nice I didn't realize gmsh could remesh! 

@ShenkieRuben yeah `merge_vertices` is just crudely connecting vertices, it's really intended for making sure indexes of two points in the same position are the same rather than nicely simplifying a mesh. You probably want remeshing as suggested above, or quadratic edge collapse decimation which isn't currently implemented in trimesh. A few more details are in this issue: https://github.com/mikedh/trimesh/issues/41

**Comment by bbarroqueiro** [comment]
@mikedh at the time i didn't give much importance to this gmsh feature but maybe it could be interesting to had this option to trimesh...

**Comment by bbarroqueiro** [comment]
@ShenkieRuben it could be more interesting to control mesh refinement via curvature instead of lenght

**Comment by ShenkieRuben** [comment]
Thanks for the replies guys. For now I made use of the quadratic edge collapse decimation algorithm from open3d. It works great!
