### ISSUE TITLE
Return list of visible triangles

### ISSUE THREAD

**Issue by andreanicastro** [mikedh/trimesh#555]
Hi, 
I am trying to find an efficient way to find the list of visible triangles from a camera. I have seen that there is a set of ray intersection functions, but that is too computational expensive. Is there a set of functionality based on rasterization that can be used for the scope? 
Cheers,
Andrea

**Comment by mikedh** [comment]
Yeah I think ray tests are probably the easiest way of handling this but yeah are kinda slow. Did you install pyembree? It does like 600K rays per second (vs 12K R/S with the built in ray checks)

You could do backface culling which is super fast (just a dot product of face normals) but will not handle triangles covered by other triangles. 

With regards to raster solutions, you run into the challenge of making sure the camera matrix matches exactly, which might be a little tough though people in issue https://github.com/mikedh/trimesh/issues/447 have had some luck.

**Comment by andreanicastro** [comment]
Hi @mikedh,
thank you very much for the quick response. I have tried the ray intersection with pyembree and I can successfully retrieve th triangles intersections
![image](https://user-images.githubusercontent.com/15173536/65600201-971fa500-df97-11e9-847f-0d8ac3ff60cb.png)
However, in the case of a 192x256 image I would have to generate at least 30K+  rays just to find triangles that project at the centre of the pixels. So the bottleneck of 600K is a bit tight.
Something like this is what I was thinking about, 
https://www.scratchapixel.com/lessons/3d-basic-rendering/rasterization-practical-implementation/visibility-problem-depth-buffer-depth-interpolation
If I can manage to write it myself I will likely open a PR

**Comment by mikedh** [comment]
Sounds good! With such a small image I'd at least try the pyembree solution before implementing fancier methods, at 600KRPS it would take 0.05 seconds which isn't bad.
