### ISSUE TITLE
Calling super with self.__class__ in SceneViewer.flip()

### ISSUE THREAD

**Issue by rmcgregor1990** [mikedh/trimesh#56]
Hey,

You're calling super with self.__class__ in trimesh.scene.viewer.SceneViewer.flip() rather than SceneViewer. This means if I inherit from SceneViewer I'm forced to override flip to avoid the infinite recursion when it is called (as self.__class__ is always going to be my inherited class).

Your package is generally awesome and you have called super correctly elsewhere within file so I'm sure its just an oversight.

Cheers,
Rob

**Comment by mikedh** [comment]
Good catch, thanks! Fix in https://github.com/mikedh/trimesh/commit/9a117188424f36db403bfa4f2935b6013ebe50bf
