### ISSUE TITLE
Number of Connected Meshes

### ISSUE THREAD

**Issue by LogWell** [mikedh/trimesh#562]
In meshlab (or OpenFlipper), the [mesh](http://rec.ustc.edu.cn/share/e66cee80-e4dd-11e9-a034-af670d8a4610) can be splited into 34 small components.

> Filters->Mesh Layer->Split in connected components

As you answered in [here](https://github.com/mikedh/trimesh/issues/76#issuecomment-326761707), I notice that the number is 20.

So, how to get the result of meshlab?

PS: The number of components is 34 in [pymesh](https://pymesh.readthedocs.io/en/latest/api_local_mesh_cleanup.html?highlight=connect#separate-mesh-into-disconnected-components).

**Comment by mikedh** [comment]
Just looking at it quickly, the input is an OBJ file which trimesh loads as a scene with multiple meshes. If you can use a non-OBJ format results are likely to be more consistent.

It's possible the other packages are considering vertex adjacency, where trimesh is splitting by face adjacency. It could also be the vertex merging somewhere. 

If I export your OBJ as a PLY from meshlab, then I can get it to 37 😆 

```
In [5]: len(m.split(only_watertight=False))]
Out[5]: 37
```

That being said, I don't necessarily see this as a bug, rather as different packages doing things differently. If you find an instance where `mesh.split` outputs drops faces, or something explicit like that then feel free to re-open.

Thanks for the report!
