### ISSUE TITLE
Path3D export/load type not consistent

### ISSUE THREAD

**Issue by ChrisWu1997** [mikedh/trimesh#563]
Thanks for this great tool first! I met a problem when using the `Path3D` class. When I load the saved `Path3D` object, its type becomes `Path2D`. The follow sample code should reproduce the error:
```python
import trimesh
from trimesh.path.creation import box_outline
a = box_outline()
print(type(a))  # <class 'trimesh.path.path.Path3D'>

a.export('box.dxf')
b = trimesh.load('box.dxf') 
# DXF doesn't have units specified!
print(type(b)) # <class 'trimesh.path.path.Path2D'>
```
Am I wrong? Or this is a bug?

**Comment by mikedh** [comment]
Hey, yeah there's no 3D path support at the moment in the DXF importer or exporter, so it's just collapsing it to 2D. DXF files *do* include a Z group code for most entities, but it seems like most of the time the format is used for 2D-ish stuff and it's usually ignored. 

Not sure what the right approach is, though PR's welcome!

**Comment by ChrisWu1997** [comment]
I see, I'll try another way for my use. Thanks though!
