### ISSUE TITLE
Load from string rather than file

### ISSUE THREAD

**Issue by jnyjxn** [mikedh/trimesh#564]
Hello,

Thank you very much for this brilliant library, which I am using in conjunction with PyRender.

I'm integrating a meshing process into a broader pipeline so my mesh-format data (e.g. PLY and STL) is not written to the disk. As I will be running my pipeline tens of thousands of times, I'd prefer to avoid having to write the mesh data to a file on the disk, only to load it up again.

Is there any functionality similar to `trimesh.load(filename)`, that allows a raw data string to be passed directly instead, e.g. `trimesh.load(data_string)`?

**Comment by mikedh** [comment]
Hey, yeah definitely just wrap the data as a `StringIO` or `BytesIO`, I usually use the util method:

```
mesh = trimesh.load(file_obj = trimesh.util.wrap_as_stream(data), file_type='ply')
```
Note that you need to explicitly specify the file type as there is no filename to infer the format from.

**Comment by jnyjxn** [comment]
That's awesome, thanks for your incredibly quick reply!
