### ISSUE TITLE
How to save Surf as STEP using Trimesh ?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#567]
How to save Surf as STEP using Trimesh ? Can you share sample code Using Trimesh ? 

@mikedh

**Comment by mikedh** [comment]
Same answer as #559 and #560, STEP export from meshes is not a thing that really makes sense, and trimesh is not quite the right tool for this. The only real open source option for STEP files and BREP CAD is [OpenCASCADE](https://dev.opencascade.org/
