### ISSUE TITLE
Bounding box corner question

### ISSUE THREAD

**Issue by jml17** [mikedh/trimesh#57]
Hi Mike,

I came across your Trimesh library for Python after trialling several other tools for generating signed distance functions from STL files. I’ve found yours to be by far the best for what I need, but I have a simple question that I couldn’t quite figure out from looking at the source:

Essentially what I want to do is to fill the bounding box with a 3D rectangular grid of points, and compute the SDF from these. I am able to generate points and calculate the SDF with no problems, but I don’t know how to get the coordinates of the corners of the bounding box. If I use:

 `box = mesh.bounding_box_oriented.primitive.extents` 

I get the half-lengths of each side of the bounding box, but if I use these to plot the 8 corners they form a box the same size and shape as the bounding box, but seemingly randomly oriented in space. How can I correctly get the coordinates of the corners so I can construct my meshgrid within the bounding box?
I see that in `bounds.py` there is a function `corners` that seems to do what I want, but I don't know where to get the `bounds` argument from.

Thank you for your time,
Joel

**Comment by mikedh** [comment]
Hey, I think you may want to use `mesh.bounding_box` which is the axis aligned bounding box rather than `mesh.bounding_box_oriented` which is the oriented bounding box. Although in order to get the 8 corners of the OBB you could do:
`trimesh.bounds.corners(m.bounding_box_oriented.bounds)`

The mesh.bounds property is computed and always axis- aligned, where the .primitive.extents is pre-transform (by .primitive.transform)

One thing you might consider, is that the oriented bounding box you're using will probably have a lot less volume. You could generate the grid (axis aligned) the size of the OBB extents, and then transform the grid of query points using the OBB's transform.

Some ipython noodling:
```

In [14]: trimesh.util.attach_to_log()

In [15]: m.bounding_box_oriented.primitive.transform
Out[15]:
TrackedArray([[   0.75983,   -0.49294,    0.42387,  831.14091],
       [   0.61234,    0.76166,   -0.21193,  437.48365],
       [  -0.21838,    0.42058,    0.88058,  636.10072],
       [   0.     ,    0.     ,    0.     ,    1.     ]])

In [16]: m.bounding_box.primitive.transform
Out[16]:
TrackedArray([[   1.     ,    0.     ,    0.     ,  831.14091],
       [   0.     ,    1.     ,    0.     ,  437.48365],
       [   0.     ,    0.     ,    1.     ,  636.10072],
       [   0.     ,    0.     ,    0.     ,    1.     ]])

In [17]: trimesh.bounds.corners?
Signature: trimesh.bounds.corners(bounds)
Docstring:
Given a pair of axis aligned bounds, return all
8 corners of the bounding box.

Parameters
----------
bounds: (2,3) or (2,2) float, axis aligned bounds

Returns
----------
corners: (8,3) float, corner vertices of the cube
File:      x:\trimesh\trimesh\bounds.py
Type:      function

In [18]: trimesh.bounds.corners(m.bounding_box.bounds)
[2017-05-12 18:21:23] DEBUG   (primitives.py:329) Creating mesh for box Primitive
[2017-05-12 18:21:23] DEBUG   (base.py:1212) Mesh transformed by matrix, normals restored
to cache
[2017-05-12 18:21:23] DEBUG   (util.py:686) triangles was not in cache, executed in 0.025009
[2017-05-12 18:21:23] DEBUG   (util.py:686) bounds was not in cache, executed in 0.025009
Out[18]:
array([[ 830.14391,  436.48424,  635.10141],
       [ 832.13792,  436.48424,  635.10141],
       [ 832.13792,  438.48306,  635.10141],
       [ 830.14391,  438.48306,  635.10141],
       [ 830.14391,  436.48424,  637.10002],
       [ 832.13792,  436.48424,  637.10002],
       [ 832.13792,  438.48306,  637.10002],
       [ 830.14391,  438.48306,  637.10002]])
```

**Comment by jml17** [comment]
This works perfectly. Thank you for your quick and detailed response!

**Comment by mikedh** [comment]
NP. I also added a sample_grid method to Box primitives the other day to make this a little easier, so you could also do something like:

```

In [22]: mesh.bounding_box.sample_grid?
Signature: mesh.bounding_box.sample_grid(count=None, step=None)
Docstring:
Return a 3D grid which is contained by the box.
Samples are either 'step' distance apart, or there are
'count' samples per box side.

Parameters
-----------
count: int   or (3,) int,   if specified samples are spaced with np.linspace
step:  float or (3,) float, if specified samples are spaced with np.arange

Returns
-----------
grid: (n,3) float, points inside the box
File:      x:\trimesh\trimesh\primitives.py
Type:      method

In [23]: grid = mesh.bounding_box.sample_grid(count=10)

In [24]: grid_obb = mesh.bounding_box_oriented.sample_grid(count=10)
```

**Comment by jml17** [comment]
A nice feature, may use this instead of my cruder method.

**Comment by Emnaa12** [comment]
Hi,
If I use the command `trimesh.bounds.corners(m.bounding_box.bounds)` I don't get the same corners as those of the oriented bounding box
Here is an example:
Ps: I sampled a point cloud because I'm working on them in real case
       import trimesh

       mesh=trimesh.creation.icosphere(subdivisions=10, radius=3.0)
       points,indexes = trimesh.sample.sample_surface(mesh, 50000)
       pcd_mesh = trimesh.PointCloud(points)
       pcd_mesh.visual.face_colors= [0, 0.5, 1., 0.5]

       axis = trimesh.creation.axis(axis_length=5)

       bb=pcd_mesh.bounding_box_oriented
       bb.visual.face_colors= [0, 0.5, 1., 0.5]

       corners=trimesh.bounds.corners(pcd_mesh.bounding_box.bounds)

       pcd_bb=trimesh.points.PointCloud(corners)

       trimesh.Scene([axis, pcd_mesh, pcd_bb, bb]).show()



Any help on how to get correct corners coordinates?

**Comment by mikedh** [comment]
Hey, `trimesh.bounds.corners(m.bounding_box.bounds)` is the *axis-aligned* bounds, probably the easiest way to get the OBB corner coordinates is `m.bounding_box_oriented.vertices` (or you can reconstruct them from `m.bounding_box_oriented.primitive.transform` and m.bounding_box_oriented.extents`).

**Comment by Emnaa12** [comment]
`m.bounding_box_oriented.vertices` works correctly, thank you !

**Comment by Gaoxinyigithub** [comment]
> `m.bounding_box_oriented.vertices` works correctly, thank you !

"trimesh.bounds.oriented_bounds(mesh)"can direct get the length,width and height of obb
