### ISSUE TITLE
Support pathlib.Path filenames

### ISSUE THREAD

**Issue by EpicWink** [mikedh/trimesh#570]
Currently, attempting to load an object by passing a `pathlib.Path` object to `trimesh.load` is unsupported. Attempting this yields:
```
  File "~/.local/lib/python3.7/site-packages/trimesh/exchange/load.py", line 211, in load_mesh
    results = mesh_loaders[file_type](file_obj,
KeyError: 'posixpath'
```

A quick solution is to simply check if the object is a `pathlib.Path` instance (eg with a new `util.is_pathlib` function), then if so convert it to string, before the string checks [in loading](https://github.com/mikedh/trimesh/blob/3.2.23/trimesh/exchange/load.py#L514) and [in saving](https://github.com/mikedh/trimesh/blob/3.2.23/trimesh/exchange/export.py#L36)

### Environment
* Python: 3.7.3
* trimesh: 3.2.23

**Comment by mikedh** [comment]
Sure, added in https://github.com/mikedh/trimesh/commit/c1dd6aa135424b8abf4feed258d00b7b9d4501c5
