### ISSUE TITLE
mesh.show() show blank white image

### ISSUE THREAD

**Issue by hanamizukigakki** [mikedh/trimesh#571]
here is the code I used to show the Mesh, but got an blank white image, what's wrong with the code ?
mesh = trimesh.Trimesh(vertices=vertices[:, :3], faces=faces)
mesh.visual.vertex_colors = color
mesh.show()

**Comment by mikedh** [comment]
Hard to say without seeing the values of `vertices`, `faces`, and `color`. What is the output of:

`print(mesh.vertices.shape, mesh.faces.shape, mesh.triangles.shape, mesh.bounds)`

**Comment by hanamizukigakki** [comment]
HI, thanks for your replay, the output is:
```
(4970, 3) (6471, 3) (6471, 3, 3) [[-135.58817623  -14.81498019 -173.11376589]
 [1921.31922023 2074.92569936 1939.52063176]]
```

**Comment by mikedh** [comment]
Hmm, it's pretty big, could be a clipping issue. Also could be alpha: what is `color`? Colors are RGBA uint8, try setting: 

`mesh.visual.face_colors = [100, 100, 100, 255]`

**Comment by hanamizukigakki** [comment]
OK, Thanks. Thanks for reminding me of the scale problem, it works after scaled with 1/32. I set the color with [103, 120, 232, 200]

**Comment by mikedh** [comment]
Oh yeah you might be able to set the clipping planes with the camera object to be larger too:
```
In [13]: scene = mesh.scene()

In [15]: scene.camera.z_far
Out[15]: 1000.0

```

**Comment by hanamizukigakki** [comment]
OK，Thank you

**Comment by jinfagang** [comment]
@mikedh Hi, I got same issue too, my values and bounds are like this:

<img width="411" alt="image" src="https://user-images.githubusercontent.com/21303438/156514664-09913b93-cb56-4a9e-b4b3-812589d0539c.png">


how should I set the z_far values?

**Comment by emirusahin** [comment]
Hey! I getthe same issue but for a different reason. 
my code: 
import trimesh
scene = trimesh.load(r"data1.glb")
mesh = scene.to_mesh()
print(mesh)
print(mesh.vertices.shape, mesh.faces.shape, mesh.triangles.shape, mesh.bounds)
the output:
<trimesh.Trimesh(vertices.shape=(1464, 3), faces.shape=(488, 3))>
(1464, 3) (488, 3) (488, 3, 3) [[0. 0. 0.]
 [0. 0. 0.]]   
 
 So from what I understand the mesh is basically extremely small to not be able to seen? However, when I upload it to a online glb viewer it automatically returns the image with the grey background. And when I try to just 
 scene = trimesh.load(file)
 scene.show() it only shows a white screen. Could you help out? 

![Screenshot 2024-12-29 013851](https://github.com/user-attachments/assets/ded80e70-fbe6-4c3f-850e-931637563f70)
