### ISSUE TITLE
what is the default behavior for interpenetrating meshes in collision?

### ISSUE THREAD

**Issue by tbarton16** [mikedh/trimesh#572]
What is the point of collision in the collisiondata, and what face is identified?

**Comment by mikedh** [comment]
Not sure exactly what it's doing, it's just pulling it from [python-fcl](https://github.com/BerkeleyAutomation/python-fcl/blob/master/fcl/fcl.pyx#L745):

```
        self._inds = {
            names[0]: contact.b1,
            names[1]: contact.b2
        }
        self._point = contact.pos
```
Looks like there is also a penetration depth that is being populated in there as well.
