### ISSUE TITLE
Denser JSON in GLB exporter

### ISSUE THREAD

**Issue by ouroborus** [mikedh/trimesh#574]
https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/gltf.py#L162

Could you update this line from:

    content = json.dumps(tree)

to:

    content = json.dumps(tree, separators=(',',':'))

This would remove some extraneous characters in the output.

**Comment by mikedh** [comment]
Sure np, looks like that syntax hasn't changed in a while. Kind of a bummer they don't have a `dense=True` kwarg in `json.dumps`.

**Comment by mikedh** [comment]
In master and released from https://github.com/mikedh/trimesh/commit/a194dd586c84f6717898b509fdbfcc868aa1bc8a

Thanks for the suggestion!
