### ISSUE TITLE
issues freezing trimesh

### ISSUE THREAD

**Issue by pauldmccarthy** [mikedh/trimesh#575]
Hi @mikedh,

Unfortunately, the recent removal of `pkg_resources` (32116bb283a1e0d6bb4064f7e4ac53dbf2d2f220) has caused issues with frozen instances of trimesh (applications created with e.g. [pyinstaller](https://pyinstaller.readthedocs.io/en/stable/)). The new approach of using `inspect.getfile(inspect.currentframe())` returns the path to `trimesh` at the time that it was frozen, rather than its actual path.

The `__file__` attribute should work in both source and frozen environments, however. I'm going to follow this issue up with a PR which replaces the use of `inspect` with `__file__`.

I'm not sure of your reasons for dropping `pkg_resources` and using `inspect`, so please feel free to ignore this issue and the associated PR - I'm happy to patch trimesh in my own application if you'd prefer to keep things they way they are :)

More info on accessing resources in frozen environments using pyinstaller can be found at https://pythonhosted.org/PyInstaller/runtime-information.html

Thanks!

**Comment by mikedh** [comment]
Thanks for the PR! Is there a minimal way of creating a unit test for pyinstaller? I tried:

    pyinstaller basic.py --exclude-module="`python ../../setup.py --list-all\`"

Which I though should just install `numpy` and `trimesh`, but it was doing a lot of things before hitting a recursion limit.

**Comment by pauldmccarthy** [comment]
This works for me, running from the `trimesh` project root. Using this entry point:

```python
#!/usr/bin/env python

import numpy as np
import trimesh.resources as r

print('Got it:', r.get_resource('units_to_inches.json'))
```

And invoking `pyinstaller` like so (I'm adding the entire `trimesh` package as additional "data" out of laziness, rather than adding just the resource files):

```sh
(venv) ➜  trimesh git:(master) ✗ pyinstaller entrypt.py --add-data=trimesh:trimesh
```

```sh
(venv) ➜  trimesh git:(master) ✗ ./dist/entrypt/entrypt
Got it: {
  "microinches": 0.001,
  "mils": 0.001,
  "inches": 1.0,
  ...
  "gigameter": 39370078740.15748,
  "light year": 3.72461748e+17,
  "parsec": 1.21483369e+18
}
(venv) ➜  trimesh git:(master) ✗

I'm happy to add this as a test, but I'm not sure how I would go about writing a non-python test with additional dependencies.

We could solve the first issue by calling pyinstaller programmatically, e.g.:

```python
#!/usr/bin/env python


import os
import shutil
import tempfile
import contextlib
import os.path as op
import subprocess as sp

import trimesh


@contextlib.contextmanager
def tempdir():

    tmp = tempfile.mkdtemp()
    prevdir = os.getcwd()

    try:
        os.chdir(tmp)
        print('Changed to tmp', tmp)
        print(os.getcwd())
        yield tmp

    finally:
        os.chdir(prevdir)
        shutil.rmtree(tmp)


entrypt = """
#!/usr/bin/env python

import numpy as np
import trimesh.resources as r

print('Got it:', r.get_resource('units_to_inches.json'))
"""


def test_freeze():

    tmdir = op.dirname(trimesh.__file__)
    binary = op.join('dist', 'entrypt', 'entrypt')

    with tempdir():

        # this import uses the cwd, so we have
        # to import it once we're inside the
        # temp dir.
        from PyInstaller.__main__ import run as pyinstaller

        with open('entrypt.py', 'wt') as f:
            f.write(entrypt)

        pyinstaller(('entrypt.py', '--add-data={}:trimesh'.format(tmdir)))

        print(os.listdir())
        print(os.listdir('dist'))
        assert sp.run(binary).returncode == 0

test_freeze()
```

**Comment by mikedh** [comment]
Thanks for the test! Unfortunately for reasons I don't understand `pyinstaller` always dies with the same `RecursionError` no matter how I run it.

**Comment by pauldmccarthy** [comment]
Sorry for the silence, I've had family stuff come up. Happy to sit on this for the time being.
