### ISSUE TITLE
update_vertices does not update the faces

### ISSUE THREAD

**Issue by panangam** [mikedh/trimesh#577]
I want to cut a mesh by a vertical plane, say the YZ plane, so I am using `update_vertices` to select only the vertices with x-coordinate > 0. For example

```python
mesh = trimesh.load_mesh('featuretype.STL')
vertices = mesh.vertices
vertices_mask = vertices[:,0] > 0
mesh.update_vertices(vertices_mask)
mesh.show()
```

This is what I got. 
<img width="629" alt="Screen Shot 2019-10-23 at 11 16 47 AM" src="https://user-images.githubusercontent.com/17264683/67422331-1e583c80-f587-11e9-9e43-656aa4c921b4.png">
<img width="403" alt="Screen Shot 2019-10-23 at 11 17 36 AM" src="https://user-images.githubusercontent.com/17264683/67422332-1e583c80-f587-11e9-9195-ea0b047cb4b6.png">

There seems to be extra edges created, linking to the same point, creating a pointy corner. 

I looked at the source code and in base.py > update_vertices I think this is the cause:

```python
inverse = np.zeros(len(self.vertices), dtype=np.int64)
```

So the faces are updated with the deleted vertices replaced by 0. But this causes unwanted edges to the original 0th vertex. 

Shouldn't the faces involving the deleted vertex just be deleted? Or is this an intended behavior? What, if there is one, is the proper solution to what I'm trying to do?

**Comment by mikedh** [comment]
Hey, `update_vertices` is most useful for removing/merging vertices and is probably not what you want to do here. I think you probably want to mask faces, or use `mesh.slice_plane` which will cut the mesh nicely at a plane and return the result from one side:

```
In [1]: import trimesh

In [2]: m = trimesh.load('~/trimesh/models/featuretype.STL')

In [3]: m.center_mass
Out[3]: array([-7.84284692e-03,  6.18175313e-05,  5.44578555e-01])

In [4]: mask = m.vertices[:,2] > m.center_mass[2]

In [6]: face_mask = mask[m.faces].all(axis=1)

In [7]: face_mask
Out[7]: TrackedArray([ True,  True,  True, ...,  True,  True,  True])

In [8]: face_mask.sum()
Out[8]: TrackedArray(2374)

In [9]: face_mask.size
Out[9]: 3476

In [10]: m.update_faces(face_mask)

In [11]: m.show()
Out[11]: SceneViewer(width=1800, height=1350)
```

![mask](https://user-images.githubusercontent.com/1403074/67432450-4ca04100-f5b4-11e9-9457-afd126b75b1e.png)

```

In [12]: m = trimesh.load('~/trimesh/models/featuretype.STL')

In [13]: m.slice_plane?
Signature: m.slice_plane(plane_origin, plane_normal, **kwargs)
Docstring:
Returns another mesh that is the current mesh
sliced by the plane defined by origin and normal.

Parameters
------------
plane_normal: (3) vector for plane normal
  Normal vector of slicing plane
plane_origin : (3,) float
  Point on the slicing plane

Returns
---------
new_mesh: trimesh.Trimesh or None
  Subset of current mesh sliced by plane
File:      /media/psf/Dropbox/robotics/trimesh/trimesh/base.py
Type:      method

In [14]: s = m.slice_plane(m.center_mass, [0,0,1])

In [15]: s.show()
```

![slice](https://user-images.githubusercontent.com/1403074/67432492-588c0300-f5b4-11e9-8ec1-f8096eaa01d1.png)

**Comment by panangam** [comment]
Thank you for the super quick reply! This definitely looks like what I want to do. 

I'm gonna go ahead and close this issue. Though I think the docstring can be a bit clearer. For example, "returns the subset of the mesh that intersects with the half plane in the direction the normal vector points to."

I've never contributed to an open source project before, but I'll try making a pull request for that.

**Comment by thachdo** [comment]
@mikedh the function `mesh.update_faces` doesn't update its normals. Also, I cannot assign new values to `mesh.face_normals` as well. Is there built-in function to solve that?

**Comment by Kiord** [comment]
@mikedh sorry but I don't understand why `update_vertices` should not remove the affected faces as well. 
Also, it is strange that the default value of `inverse` array is 0. Zero can (will) be the index of the first vertex. And this explains why we have "deleted" faces snapped into the first vertex like that.

If the current behavior is desired (why?), maybe we should add an option `remove_faces`. Else, we should directly reindex the faces.

**Comment by pengHTYX** [comment]
Hi, @mikedh , is there any way to remove specific vertices but not add new edges (or faces)? I just want to remove some vertices and related faces. ```update_vertices``` will introduce new faces.
