### ISSUE TITLE
Outdated docstring

### ISSUE THREAD

**Issue by sanguinariojoe** [mikedh/trimesh#58]
In `trimesh/ray/ray_triangle.py`, function `intersects_location`.

`rays` parameter is not used anymore, but `ray_origins` and `ray_directions`

**Comment by mikedh** [comment]
Good find. Fixed in https://github.com/mikedh/trimesh/commit/21054adce72a1745d6709c5f75b698ba6cbf4973?

**Comment by sanguinariojoe** [comment]
Sorry for the delay! Yes, now is perfect! Thank you
