### ISSUE TITLE
obj mesh to glb

### ISSUE THREAD

**Issue by sariug** [mikedh/trimesh#580]
Hello,

Im new to this.

I have an obj file, which contains multiple mesh(just mesh)

I want to have it as glb(to have less file size)

The error I get is : `ValueError: Matrix must be specified!`

My code is simply : 

`mesh = trimesh.load_mesh("../step_files/67b1f6d8-07a7-4c54-bf3d-bed6470d05ac.obj", split_object=True)`
`mesh.export("s.glb")`

What would be wrong here ?

**Comment by sariug** [comment]
Also the multiple mesh is merged automatically. Is there a way to keep them separate ?

**Comment by mikedh** [comment]
I think it depends a lot on the geometry. This works for me:
```
m = trimesh.load('bigmodel/airplane/models/model_normalized.obj', process=False)
m.export('err.glb')
```
Could you send me a copy of the OBJ file?

**Comment by sariug** [comment]
Im out of office now. I will try in 10 hours !

**Comment by sariug** [comment]
Here the part is for example. A cube with 6 face. I want to be able pick the faces separately later so these should not be merged. however they do merge...


```
o facemesh[000]

v -50.000000 -50.000000 -50.000000
v -50.000000 -50.000000 50.000000
v -50.000000 50.000000 -50.000000
v -50.000000 50.000000 50.000000
vn -1.000000 0.000000 0.000000
vn -1.000000 0.000000 0.000000
f 1//1 2//1 3//1
f 3//2 2//2 4//2

o facemesh[001]

v 50.000000 -50.000000 50.000000
v 50.000000 -50.000000 -50.000000
v 50.000000 50.000000 -50.000000
v 50.000000 50.000000 50.000000
vn 1.000000 0.000000 0.000000
vn 1.000000 -0.000000 0.000000
f 5//3 6//3 7//3
f 5//4 7//4 8//4

o facemesh[002]

v 50.000000 -50.000000 -50.000000
v 50.000000 -50.000000 50.000000
v -50.000000 -50.000000 -50.000000
v -50.000000 -50.000000 50.000000
vn 0.000000 -1.000000 0.000000
vn 0.000000 -1.000000 0.000000
f 9//5 10//5 11//5
f 11//6 10//6 12//6

o facemesh[003]

v 50.000000 50.000000 50.000000
v 50.000000 50.000000 -50.000000
v -50.000000 50.000000 -50.000000
v -50.000000 50.000000 50.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 1.000000 0.000000
f 13//7 14//7 15//7
f 13//8 15//8 16//8

o facemesh[004]

v -50.000000 50.000000 -50.000000
v 50.000000 50.000000 -50.000000
v -50.000000 -50.000000 -50.000000
v 50.000000 -50.000000 -50.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 0.000000 -1.000000
f 17//9 18//9 19//9
f 19//10 18//10 20//10

o facemesh[005]

v 50.000000 50.000000 50.000000
v -50.000000 50.000000 50.000000
v -50.000000 -50.000000 50.000000
v 50.000000 -50.000000 50.000000
vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 1.000000
f 21//11 22//11 23//11
f 21//12 23//12 24//12

```

**Comment by mikedh** [comment]
The `group_material` kwarg is combining the sections after splitting, if you load with:
`m = trimesh.load('mesh.obj', split_object=True, group_material=False, process=False)` 

It will return a scene. The `group_material` functionality combines faces that have the same materials in different groups, which on large meshes with multiple materials can improve performance dramatically.

**Comment by sariug** [comment]
Oh yes now it works. Great thanks !
