### ISSUE TITLE
nice __repr__ for Trimesh object?

### ISSUE THREAD

**Issue by jjnurminen** [mikedh/trimesh#582]
Hi,
I noticed that `base.Trimesh` does not implement `__repr__`. It would be useful to have one that would print out basic mesh info.

**Comment by jjnurminen** [comment]
I can also submit a PR if desired

**Comment by mikedh** [comment]
Sure sounds great! What were you thinking of including? Maybe something like:
- `mesh.faces.shape`
- `mesh.vertices.shape`
- `mesh.visual.kind`

**Comment by mikedh** [comment]
Added! Heh not sure if I really gained all that much by adding it to the parent class with a bunch of checks. If you want to pretty it up a little PR's welcome! 

It is super nice seeing the face/vertex shape quickly, thanks for the report!

**Comment by jjnurminen** [comment]
Thanks for the enhancement!
