### ISSUE TITLE
Error when loading file .ply

### ISSUE THREAD

**Issue by TruongKhang** [mikedh/trimesh#583]
I have a file mesh .ply [here](https://drive.google.com/file/d/1s2WglrMEhV3Hq2JjH2TTyfVIdzf0eN-w/view?usp=sharing). Everything is fine when I open this file in Meshlab:
![meshlab](https://user-images.githubusercontent.com/18275776/67863643-a0d49380-fb67-11e9-9025-ea5b266d2928.png)

However, when I use trimesh.load() and show the mesh. The result is displayed like this:
![trimesh](https://user-images.githubusercontent.com/18275776/67863657-a6ca7480-fb67-11e9-85ec-0eee79385fd8.png)

There are some invisible areas. Are there any problems with trimesh? How can I fix this?

**Comment by mikedh** [comment]
That's big enough that I can't check on my ancient laptop until I get home tonight, but it looks like a lighting or znear/zfar clipping issue in the viewer. For rendering you might also check out [pyrender](https://github.com/mmatl/pyrender), which has much more thorough lighting and rendering than the trimesh viewer.

**Comment by TruongKhang** [comment]
@mikedh , my original program aim to render 2D depth map from this mesh by pyrender. It face the similar problem because it loaded the mesh above by using trimesh. So I think the problem is from loading the mesh. Can you show me a sample code for viewing the mesh correctly?

**Comment by mikedh** [comment]
I checked, and both Meshlab and trimesh load the exact same number of faces. I think a lot of the faces on that mesh are backwards, if you press `c` in the viewer to turn off backface culling it looks the same in a trimesh viewer window as the meshlab output:

![ignatious](https://user-images.githubusercontent.com/1403074/67912497-7cc18400-fb60-11e9-8692-239d625880b6.png)

You can also call `mesh.invert()` to flip every triangle, which you may want to do before passing to pyrender.

**Comment by TruongKhang** [comment]
Yeah, it works! Thank you so much

**Comment by mikedh** [comment]
No problem!

**Comment by TruongKhang** [comment]
Hi @mikedh , can you help me? I'm trying with another mesh object and I find that the command `mesh.inverter()` and the pressed button `c` when viewing the object don't act the same, right? That leads to my rendering results is not good. Are there any other commands which work exactly as same as the function of button `c`.
