### ISSUE TITLE
Access Triangles in meshes 

### ISSUE THREAD

**Issue by wissalsayhi** [mikedh/trimesh#584]
Hi, 
I have a triangular mesh of a human body.
Is it possible to access specific triangles, change their color or apply a texture without changing the mesh?
I already tried to crop it change it but i wasn't able to put it back to its plae. 

Thank you

**Comment by mikedh** [comment]
You can edit the `mesh.visual` object to change things like face colors, vertex colors, or texture:

```
In [2]: m                                                            
Out[2]: <trimesh.base.Trimesh at 0x7f70181371d0>

In [3]: m.visual.face_colors                                         
Out[3]: 
TrackedArray([[102, 102, 102, 255],
              [102, 102, 102, 255],
              [102, 102, 102, 255],
              ...,
              [102, 102, 102, 255],
              [102, 102, 102, 255],
              [102, 102, 102, 255]], dtype=uint8)

In [4]: m.visual.face_colors[0] = [200,0,0,255]                      

In [5]: m.show()
```

**Comment by wissalsayhi** [comment]
Hey, 
Thanks for the reply. 
Is it possible to insert an image in a particular face?

**Comment by mikedh** [comment]
Hey, you could set up a `TextureVisuals` object and then mess around with the UV coordinates and image. Try loading `models/fuze.obj` to see what a simple textured mesh looks like.

Closing for now, though feel free to re-open!
