### ISSUE TITLE
Origin

### ISSUE THREAD

**Issue by pepperonimax** [mikedh/trimesh#585]
Hello,

is it possible to get the origin of a mesh? I created a mesh out of a volume model and would like to check (and if necessary ) adjust the origin to have a coinciding model.

Thank you very much!

**Comment by mikedh** [comment]
Hey, it depends what you mean by 'origin'. The origin is `[0,0,0]` almost by definition. You can look at `mesh.center_mass` for mesh-relevant coordinates, or you can try to use `mesh.register` to align (aka "register") the mesh to another mesh or 3D points:

```
In [1]: import trimesh                                               

In [2]: m = trimesh.creation.box(extents=[1,10,5])                   

In [3]: m.register?                                                  
Signature: m.register(other, **kwargs)
Docstring:
Align a mesh with another mesh or a PointCloud using
the principal axes of inertia as a starting point which
is refined by iterative closest point.

Parameters
------------
mesh : trimesh.Trimesh object
  Mesh to align with other
other : trimesh.Trimesh or (n, 3) float
  Mesh or points in space
samples : int
  Number of samples from mesh surface to align
icp_first : int
  How many ICP iterations for the 9 possible
  combinations of
icp_final : int
  How many ICP itertations for the closest
  candidate from the wider search

Returns
-----------
mesh_to_other : (4, 4) float
  Transform to align mesh to the other object
cost : float
  Average square distance per point

```

**Comment by mikedh** [comment]
Closing for now, though feel free to re-open!

**Comment by pepperonimax** [comment]
Thank you! trimesh .register helped me with my problem!

**Comment by airwarriorg91** [comment]
@mikedh @pepperonimax  I am facing a similar problem. LIke I want to shift a geometry with its centroid at (0.5,0.5,3) to (0,0,3). First i was using register method with the geometry and a set of points. But it is taking a long time to complete. Any other method to do the shifting ?

**Comment by mikedh** [comment]
If you already know the translation you can just run `mesh.apply_translation(-0.5, -0.5, -3.0)` or `mesh.apply_translation(-mesh.center_mass)`or whatever.

**Comment by airwarriorg91** [comment]
yeah that also works. Thanks !
