### ISSUE TITLE
TrackedArray vs numpy array

### ISSUE THREAD

**Issue by jjnurminen** [mikedh/trimesh#587]
Hi,

I did some processing for a Trimesh object and then got the new vertices via`myverts = mesh.vertices`. I then did some subsequent computations on `myverts` which went fine. However at some point I happened to notice that `myverts` is actually of type `TrackedArray`. Converting it to a simple numpy array I got a speedup by a factor of 4.

This is not really a big issue, but I was wondering if there should be a method to return the vertices as a simple numpy array, or maybe at least the docs should mention that using the property will yield a `TrackedArray`.

**Comment by mikedh** [comment]
Oh interesting. The `TrackedArray` is the thing that enables caching, which provides huge speedups in applications accessing properties multiple times  so it's kind of necessary for vertices and faces. If this turns into an ongoing issue, I wonder if we could make it so copies of a `TrackedArray` revert to `ndarray` type.

That being said, in some quick and dirty profiling I couldn't see any speed difference:
```
In [1]: import numpy as np                                                                                                                 

In [2]: import trimesh                                                                                                                     

In [3]: m = trimesh.creation.icosphere()                                                                                                   

In [5]: v = m.vertices                                                                                                                     

In [6]: n = m.vertices.view(np.ndarray)                                                                                                    

In [7]: n                                                                                                                                  
Out[7]: 
array([[-0.52573111,  0.85065081,  0.        ],
       [ 0.52573111,  0.85065081,  0.        ],
       [-0.52573111, -0.85065081,  0.        ],
       ...,
       [ 0.91298249, -0.39960705, -0.08232358],
       [ 0.91298249,  0.39960705,  0.08232358],
       [ 0.91298249,  0.39960705, -0.08232358]])

In [8]: v                                                                                                                                  
Out[8]: 
TrackedArray([[-0.52573111,  0.85065081,  0.        ],
              [ 0.52573111,  0.85065081,  0.        ],
              [-0.52573111, -0.85065081,  0.        ],
              ...,
              [ 0.91298249, -0.39960705, -0.08232358],
              [ 0.91298249,  0.39960705,  0.08232358],
              [ 0.91298249,  0.39960705, -0.08232358]])

In [9]: %timeit np.linalg.norm(v, axis=1)                                                                                                  
31.6 µs ± 978 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [10]: %timeit np.linalg.norm(n, axis=1)                                                                                                 
30.7 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [11]: %timeit np.dot(n, n.T)                                                                                                            
1.81 ms ± 43.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: %timeit np.dot(v, v.T)                                                                                                            
1.84 ms ± 32.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

```

**Comment by jjnurminen** [comment]
Ok, thanks for the info. I'll try to benchmark and see which part actually was slower with TrackedArray.

**Comment by jjnurminen** [comment]
Hi! I don't have time for a really careful investigation right now, but I think I managed to isolate the slowdown a bit. The code below loads a `Trimesh` I created and accesses its vertices as either `TrackedArray` or a numpy array. The loop also touches `vertex_neighbors`. The `TrackedArray` version runs 100 times slower on my machine. Can you reproduce this?


```
with open('trimesh.dat', 'rb') as f:
    tm = pickle.load(f)

t0 = time.perf_counter()
verts = np.array(tm.vertices)
for ind in np.arange(5000):
    verts[ind, :]
    tm.vertex_neighbors[ind]
t1 = time.perf_counter()
print('with numpy array: %.2f ms' % (1e3*(t1-t0)))

with open('trimesh.dat', 'rb') as f:
    tm = pickle.load(f)

t0 = time.perf_counter()
verts = tm.vertices
for ind in np.arange(5000):
    verts[ind, :]
    tm.vertex_neighbors[ind]
t1 = time.perf_counter()
print('with TrackedArray: %.2f ms' % (1e3*(t1-t0)))
```

**Comment by mikedh** [comment]
Ah yeah that makes sense as it is looping through every vertex and slicing which sets a dirty flag, and the requesting of a cached property (`vertex_neighbors`) would trigger a CRC of the entire vertex array on every single loop iteration.

The caching system works quite well, but in tight loops it can benefit from a few things (which certainly could be documented better):
- Could you avoid looping through vertices at all with vectorized operations somehow?
- If you have to loop, you should move cached properties into local variable outside the loop so it doesn't hit the cache on every iteration
- You can also move vertices into a local `ndarray` before looping. 

e.g this should be fine: 
```
neighbors = tm.vertex_neighbors
vertices = tm.vertices.view(np.ndarray)
for i in np.arange(5000)
    vertices[i, :]
    neighbors[i]
```

**Comment by jjnurminen** [comment]
Ok. It's not really a problem for me - just wanted to make sure there wasn't a bug or something. I think my use case is kind of uncommon anyway, since I'm looping through a subset of vertices and modifying it in iterative fashion.

Thanks for the package BTW - it already saved me a lot of time.
