### ISSUE TITLE
question in voxel.local_voxelize

### ISSUE THREAD

**Issue by qiminchen** [mikedh/trimesh#598]
Hi, I'm using the following code to generate the 128x128x128 voxel in numpy array, it worked few months ago but fail today. For a given mesh, how can I turn it into a 128x128x128 voxel in form of numpy array?
```
mesh = trimesh.load('xxx.obj')
voxel = trimesh.voxel.local_voxelize(mesh, mesh.centroid, 1, 64, fill=False)
voxel = v[0][:-1, :-1, :-1].astype('int')
```
By saying failed in voxelization I mean when visualizing the voxel, it looks completely wrong. However, it worked perfectly few months ago.

Thanks in advance

**Comment by mikedh** [comment]
Is `local_voxelize` preferable over just `mesh.voxelized(pitch=mesh.extents.max() / 128)`? 

Also `local_voxelize` moved a while ago, you may just need to update your call to `trimesh.voxel.creation.local_voxelize`:

```
In [8]: trimesh.voxel.creation.local_voxelize?
Signature: trimesh.voxel.creation.local_voxelize(mesh, point, pitch, radius, fill=True, **kwargs)
Docstring:
Voxelize a mesh in the region of a cube around a point. When fill=True,
uses proximity.contains to fill the resulting voxels so may be meaningless
for non-watertight meshes. Useful to reduce memory cost for small values of
pitch as opposed to global voxelization.

Parameters
-----------
mesh : trimesh.Trimesh
  Source geometry
point : (3, ) float
  Point in space to voxelize around
pitch :  float
  Side length of a single voxel cube
radius : int
  Number of voxel cubes to return in each direction.
kwargs : parameters to pass to voxelize_subdivide

Returns
-----------
voxels : VoxelGrid instance with resolution (m, m, m) where m=2*radius+1

```

**Comment by yingzhang1109** [comment]
> Is `local_voxelize` preferable over just `mesh.voxelized(pitch=mesh.extents.max() / 128)`?
> 
> Also `local_voxelize` moved a while ago, you may just need to update your call to `trimesh.voxel.creation.local_voxelize`:
> 
> ```
> In [8]: trimesh.voxel.creation.local_voxelize?
> Signature: trimesh.voxel.creation.local_voxelize(mesh, point, pitch, radius, fill=True, **kwargs)
> Docstring:
> Voxelize a mesh in the region of a cube around a point. When fill=True,
> uses proximity.contains to fill the resulting voxels so may be meaningless
> for non-watertight meshes. Useful to reduce memory cost for small values of
> pitch as opposed to global voxelization.
> 
> Parameters
> -----------
> mesh : trimesh.Trimesh
>   Source geometry
> point : (3, ) float
>   Point in space to voxelize around
> pitch :  float
>   Side length of a single voxel cube
> radius : int
>   Number of voxel cubes to return in each direction.
> kwargs : parameters to pass to voxelize_subdivide
> 
> Returns
> -----------
> voxels : VoxelGrid instance with resolution (m, m, m) where m=2*radius+1
> ```

Hi, @mikedh is it possible to define fill = True when I use mesh.voxelized(pitch=mesh.extents.max() / 128)? I want my part to be solid.

**Comment by tianyilt** [comment]
Hi, how do you get 128 voxel numpy array. Due to `VoxelGrid instance with resolution (m, m, m) where m=2*radius+1` and radus had to be int, I can only get （129,129,129） shape ndarray
here is code:
```python

source = obj_reconstruction_path_list[idx]
mesh = trimesh.load(source)
mesh = scale_to_unit_sphere(mesh)
voxel_grid=trimesh.voxel.creation.local_voxelize(mesh,mesh.centroid, mesh.extents.max() / 128, 64, fill=True)
tmp_raw=voxel_grid.encoding.data

```
