### ISSUE TITLE
cyassimp missing?

### ISSUE THREAD

**Issue by rebcabin** [mikedh/trimesh#60]
Been having all kinds of trouble installing cyassimp. I've tried many permutations and guesses, pyassimp, assimp, etc. None of them seem to work.

```
$ conda install -n my-fave-env -c menpo/label/master cyassimp
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Dependency missing in current osx-64 channels: 
  - cyassimp -> assimp 3.0.1270

Close matches found; did you mean one of these?

    assimp: cyassimp
```

**Comment by mikedh** [comment]
Hey, I've never tried installing cyassimp on OSX. Their anaconda page is here: https://anaconda.org/menpo/cyassimp 

One thing to note is that cyassimp is a soft dependency, and everything except the extra assimp formats works fine without it.

**Comment by rebcabin** [comment]
Ahh, yes, but i _really_ needed the importers too :)  I found another workaround, so I'll close the issue. I didn't try the anaconda page yet, but it would seem a bit more kosher.

I adapted [the instructions on stackoverflow here](https://stackoverflow.com/questions/22312665/install-python-packages-to-correct-anaconda-environment). Specifically, I [downloaded trimesh-2.13.11 from this page](https://pypi.python.org/pypi/trimesh) and did the following:

pushd ~/Downloads/trimesh-2.13.11
source activate ~/anaconda/envs/Ops-rsimcon-viz
pip install .

**Comment by mikedh** [comment]
Hahah cool. Though did that install cyassimp or just trimesh?

Another thing you could do is build the pyassimp bindings, I used to use this script:
`pip install git+https://github.com/robotics/assimp_latest.git`

They're not as nice as the cyassimp ones though.
