### ISSUE TITLE
Does voxels of two different mesh aligned in default?

### ISSUE THREAD

**Issue by soaroc** [mikedh/trimesh#607]
I have two objects and voxelized them into voxels individually (w/ the same pitch). Do the two voxels set aligned with the same 'virtual grid'?  Saying, if the two objects overlap with each other partially, so do the voxels in the overlapping region align with each other exactly?

What I'm doing is to try some fluid simulation. I have two objects as obstacles and the background grids on which the flow is simulated. I tried to voxelized the objects as hard boundaries but was not sure how to align the voxels with each other and also the background grids

PS: Does the voxelization run in objects' local frames or in the same world frame? 

Tks~

**Comment by mikedh** [comment]
I *think* they should be aligned, but I wouldn't bet my life on it. It's just calling `(vertices/pitch).round().astype(int)` which should be the same given the same vertices and pitch.
