### ISSUE TITLE
trimesh.geometry.align_vectors returns invalid rigid transform

### ISSUE THREAD

**Issue by mjd3** [mikedh/trimesh#608]
Related to #540, it seems like there is still an issue where the method returns an invalid rigid transform when passed input that is close to the reverse vector. An example:
```python
In [1]: import trimesh
In [2]: import numpy as np
In [3]: a = trimesh.geometry.align_vectors([0,0,-1], [0,0,1])
In [4]: b = trimesh.geometry.align_vectors([0,0,-1], [-1e-17, 1e-17, 1])
In [5]: np.linalg.det(a)
Out[5]: 1.0
In [6]: np.linalg.det(b)
Out[6]: -1.0
```
Note that this still occurs with inputs that aren't quite as small (like 1e-4):
```python
In [7]: b = trimesh.geometry.align_vectors([0,0,-1], [-1e-4, 1e-4, 1])
In [8]: np.linalg.det(b)
Out[8]: -0.9999999999999999
```
It does work for the case in #540 though (the same one in the unit tests):
```python
In [9]: v1 = np.array([ 7.12106798e-07, -7.43194705e-08,  1.00000000e+00])
In [10]: c = trimesh.geometry.align_vectors([0,0,-1], v1)
In [11]: np.linalg.det(c)
Out[11]: 1.0000000000000002
```
Any thoughts on this? I'm not sure that I 100% understand the SVD trick.

**Comment by mikedh** [comment]
Well shoot, that's what I get for merging fancy things I don't understand. The SVD trick *does* get better precision in many cases but does sometimes produces non-rigid transforms as you point out.

I added your cases to the tests in #609, thanks for the report!

**Comment by mjd3** [comment]
Great! Thanks for the super quick fix!
