### ISSUE TITLE
SceneViewer has _nswindow = None

### ISSUE THREAD

**Issue by rebcabin** [mikedh/trimesh#61]
I've successfully loaded a little mesh and checked it for watertightness, etc., and I'm trying to 'show' it in a pyglet window using some code I cribbed from trimesh's examples. I know my pyglet / pygame / opengl installation is (at least somewhat) correct because I can run their samples standalone, e.g., [THIS ONE](http://pyglet-current.readthedocs.io/en/latest/programming_guide/quickstart.html). The trimesh code is shown below.
```
import numpy as np
import trimesh

mesh = trimesh.load_mesh('../models/j39binary.fbx')
mesh.is_watertight # ~~> True
mesh.euler_number # ~~> 2
np.divide(mesh.volume, mesh.convex_hull.volume) # ~~> works as expected
mesh.vertices -= mesh.center_mass # ditto
mesh.moment_inertia # ~~> results look reasonable
mesh.split() # ~~> ok
for facet in mesh.facets:
    mesh.visual.face_colors[facet] = trimesh.visual.random_color()

mesh.show() # ~~> throws inside here
# omitting the rest
```

The stack trace is below. The symptom is that _nswindow in the SceneViewer is None. I've stepped through a ton of pyglet code. The problem seems to be that a correctly created _nswindow is thrown away on line 209 of gl/__init__py with a call of `app.windows.remove`. Later on, SceneViewer tries to use _nswindow, but it's gone. This appears to be due to some multithreading issues or some tricks for creating windows in the face of circular imports, it's hard to say from the code I stepped through.

I just don't know enough about pyglet and its Cocoa implementation to figure out a workaround, so I thought I'd bring this to you. Simple things like trying to create a new window right inside trimesh's viewer.py and assigning it to _nswindow caused more problems and the exercise is becoming a classic rabbit hole. I'm sure it's something simple, but I'm not sure it's my problem because I copy-pasted the calling code from trimesh samples. Also, I am not the only one with the problem: please see [THIS STACKOVERFLOW QUESTION](https://stackoverflow.com/questions/44329039/trimesh-show-method-returns-attributeerror). I'd be grateful for any advice.

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/bbeckman/Documents/trimesh/examples/debugio.py", line 43, in <module>
    mesh.show()
  File "/Users/bbeckman/Documents/trimesh/trimesh/base.py", line 1373, in show
    scene.show(**kwargs)
  File "/Users/bbeckman/Documents/trimesh/trimesh/scene/scene.py", line 388, in show
    viewer()
  File "/Users/bbeckman/Documents/trimesh/trimesh/scene/scene.py", line 385, in viewer
    SceneViewer(self, **kwargs)
  File "/Users/bbeckman/Documents/trimesh/trimesh/scene/viewer.py", line 31, in __init__
    self.reset_view(flags=flags)
  File "/Users/bbeckman/Documents/trimesh/trimesh/scene/viewer.py", line 129, in reset_view
    if (self.width is not None and
  File "/Users/bbeckman/anaconda/envs/rsimcon-pyassimp-minimal/lib/python2.7/site-packages/pyglet/window/__init__.py", line 850, in <lambda>
    width = property(lambda self: self.get_size()[0],
  File "/Users/bbeckman/anaconda/envs/rsimcon-pyassimp-minimal/lib/python2.7/site-packages/pyglet/window/cocoa/__init__.py", line 398, in get_size
    window_frame = self._nswindow.frame()
AttributeError: 'NoneType' object has no attribute 'frame'
```

**Comment by mikedh** [comment]
Ah, should be fixed in https://github.com/mikedh/trimesh/commit/756822c7c4fe4137f86a4a2f0674e3366294ee9e . Looks like on OSX they don't wrap the width parameter when the event loops not running. Build just finished, you can probably `pip install --upgrade trimesh` to get it.

**Comment by rebcabin** [comment]
Great!  working now and i'm unblocked :)  TYVM
