### ISSUE TITLE
Obj import/GLB export - Reuse materials and textures

### ISSUE THREAD

**Issue by kristiansvenssonsweco** [mikedh/trimesh#613]
Thank you sharing trimesh, its a great library!

I have an obj file containing two meshes, ObjectA and ObjectB. They both use the same material.
I want to convert this obj file to a GLB-file which should contain the two objects and they should still share the same material.

However in my GLB output I get the two objects but I also get two materials, one for each mesh. Each of this materials links to a copy of the same texture. This is unessary both for the size of the GLB file but also for loading copies of the same material and texture.

When loading the obj file I use the split_object = True and group_material = False

If I set group_material = True I get a single material but now the objects have been merged to one object.

For my case, is it possible to override so that the GLB output get a single material which is being used for both objects?

I'm attaching my files for debugging.
[trimesh_obj.zip](https://github.com/mikedh/trimesh/files/3851474/trimesh_obj.zip)

**Comment by mikedh** [comment]
Yeah that would be cool. I think the way I'd probably do it is make materials hashable, and then check an `{hash : material index}` dict in the GLTF export to not include the same material multiple times.
