### ISSUE TITLE
how to save high resolution png from trimesh.Scene

### ISSUE THREAD

**Issue by sw-gong** [mikedh/trimesh#614]
![image](https://user-images.githubusercontent.com/39670256/68962527-b7682500-07cc-11ea-96cb-28b5435c238e.png)

Hi, May I ask how to save high resolution png from trimesh.Scene()? There are several meshes.

**Comment by mikedh** [comment]
Hey, you might take a look at this render example, which you can run in Docker or just locally:
https://github.com/mikedh/trimesh/blob/master/examples/dockerRender/render.py

**Comment by sw-gong** [comment]
It does only allow to save one mesh to png but I hope to save multiple meshes into a png. Is that possible to do this?

![image](https://user-images.githubusercontent.com/39670256/69432892-7757f380-0d32-11ea-832e-3266f3e849ba.png)

**Comment by ganjbakhshali** [comment]
What should we do if we want to save without opening the window?
