### ISSUE TITLE
error when calling mesh.vertex_faces

### ISSUE THREAD

**Issue by reuvenlivn** [mikedh/trimesh#615]
Since two days ago, when calling vertex_faces = mesh.vertex_faces. I got this messages:

C:\ProgramData\Anaconda3\lib\site-packages\trimesh\base.py:390: RuntimeWarning: invalid value encountered in greater
  nonzero = np.logical_or(values > tol.merge,
C:\ProgramData\Anaconda3\lib\site-packages\trimesh\base.py:391: RuntimeWarning: invalid value encountered in less
  values < -tol.merge)
Traceback (most recent call last):
  File "model_analysis_v2.py", line 569, in <module>
    main()
  File "model_analysis_v2.py", line 522, in main
    vertex_faces =  mesh.vertex_faces
  File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\caching.py", line 105, in get_cached
    value = function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\base.py", line 504, in vertex_faces
    sparse=self.faces_sparse)
  File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\geometry.py", line 270, in vertex_face_indices
    vertex_faces[vertex_faces == 0] = sorted_faces[1]
ValueError: NumPy boolean array indexing assignment cannot assign 298405 input values to the 304986 output values where the mask is true

when trying to go back to trimesh 3.4.0 the same is happened

**Comment by mikedh** [comment]
Hey, I think there is probably bad data somewhere in the mesh. Can you send me a reproducible example? 

The additional checks I just added in https://github.com/mikedh/trimesh/pull/618 might help.

**Comment by reuvenlivn** [comment]
https://drive.google.com/file/d/15cYX2VMqFGtLcU-IiYZ5SSi-gW9_CP9u/view?usp=sharing

**Comment by reuvenlivn** [comment]
I do not understand. I sent you an example file and somehow the issue is closed. I still has it in my code and do not know what to do to slove it

**Comment by reuvenlivn** [comment]
please look here to find stl file that shows this bug
https://drive.google.com/file/d/1tchjXNZiyhY9Lkl0W4KFakScJIje4kb_/view?usp=sharing
reuven

**Comment by mikedh** [comment]
Oh interesting, the face_normals being wrong was a red herring, the issue was that mesh had degenerate faces that messed up the indexing from the sparse dot product. I just merged a preliminary fix in #618. 

Thanks for the report and reproducible example!
