### ISSUE TITLE
I can't find information on trimesh.voxel.VoxelGrid() metadata input option.

### ISSUE THREAD

**Issue by joaco18** [mikedh/trimesh#616]
Hi! First of all, amazing library.

I'm actually generating a mesh from a 3D binary medical image in format .nii. I've managed to do it by using just the 3d pixel array, but I'd like to use the information of the spatial localization of each voxel (which is contained in the .nii image metadata) while generating the mesh. By doing it, I can then corregister my mesh and my 3d image in other medical image viewers.

The class `trimesh.voxel.VoxelGrid(encoding, transform=None, metadata=None)`, has this metadata input option, but I can't find which data it can take or how to use it. It'd be very nice if someone could help me :)
Thanks!

**Comment by mikedh** [comment]
Hey, metadata is a `dict` where you can store unstructured extra information, and which will then be available as `obj.metadata`. You could do something like:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/featuretype.STL')

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(1722, 3), faces.shape=(3476, 3))>

In [4]: v = m.voxelized(pitch=m.scale/25)

In [6]: v
Out[6]: <trimesh.VoxelGrid(23, 11, 7)>

In [7]: v.metadata
Out[7]: {}

In [8]: m.metadata
Out[8]: 
{'header': 'ddlid featuretype',
 'processed': True,
 'file_path': '/media/psf/Dropbox/robotics/trimesh/models/featuretype.STL',
 'file_name': 'featuretype.STL'}

In [9]: v.metadata.update(m.metadata)

```
