### ISSUE TITLE
Boolean operations with Blender 2.8

### ISSUE THREAD

**Issue by BenjaminVerdier** [mikedh/trimesh#617]
Hi!

I came back to a previous project of mine using trimesh recently, and boolean differences where not working anymore, returning an empty mesh.
After some investigating, I found out the issue was related to the blender version: it doesn't work with Blender 2.8. I resolved the issue by going back to 2.79.

I can't really provide any detail on the error since it doesn't display anything and just returns an empty mesh.

Would it be possible to find a fix for this?

Thanks!

**Comment by mikedh** [comment]
Oh, looks like Blender 2.8 [changed their API significantly](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API).

I wasn't able to "solve" it but made minor progress and added a debug mode in [this branch](https://github.com/mikedh/trimesh/tree/fix/b28), which I was testing with:

```
import trimesh
import numpy as np

if __name__ == '__main__':
    a = trimesh.creation.uv_sphere()
    b = trimesh.creation.uv_sphere()
    b.apply_translation([0,0,1.0])
    r = a.union(b, debug=True)
    print(r, r.is_volume, r.volume, r.body_count)
```

I probably don't have time to fix it this weekend, but if you have some cycles I'm happy to take PR's!

**Comment by jjmontesl** [comment]
Hi, I also got bitten by this but also didn't want to spawn an external process. I'm using `pycsg` (https://github.com/timknip/pycsg) library as a replacement for boolean operations. I can share code for this or try to implement a provider and submit a PR.

(However, I have no mesh simplification option for the same reason and I have no alternative for that, although a builtin solution would be much welcome).

**Comment by jjmontesl** [comment]
Here is my CSG operation code using `pycsg` in case someone is interested in the alternative. Code comes from another app and will require a bit of adaptation (mainly, meshes are members of objects):

```
def _csg(self, other, operation):
        
        pols1 = []
        for f in self.mesh.faces:
            verts = [self.mesh.vertices[f[0]], self.mesh.vertices[f[1]], self.mesh.vertices[f[2]]]
            pols1.append(csggeom.Polygon([csggeom.Vertex(verts[0]), csggeom.Vertex(verts[1]), csggeom.Vertex(verts[2])]))

        pols2 = []
        for f in other.mesh.faces:
            verts = [other.mesh.vertices[f[0]], other.mesh.vertices[f[1]], other.mesh.vertices[f[2]]]
            pols2.append(csggeom.Polygon([csggeom.Vertex(verts[0]), csggeom.Vertex(verts[1]), csggeom.Vertex(verts[2])]))
        
        csg1 = CSG.fromPolygons(pols1)
        csg2 = CSG.fromPolygons(pols2)

        if operation == 'subtract':
            pols = csg1.subtract(csg2).toPolygons()
        elif operation == 'union':
            pols = csg1.union(csg2).toPolygons()
        else:
            raise AssertionError()
        
        #mesh = boolean.difference([self.mesh, other.mesh], 'blender')
        v = []
        f = []
        i = 0
        for p in pols:
            for vi in range(len(p.vertices) - 2):
                v.extend([[p.vertices[0].pos[0], p.vertices[0].pos[1], p.vertices[0].pos[2]], 
                          [p.vertices[vi + 1].pos[0], p.vertices[vi + 1].pos[1], p.vertices[vi + 1].pos[2]], 
                          [p.vertices[vi + 2].pos[0], p.vertices[vi + 2].pos[1], p.vertices[vi + 2].pos[2]]])
                f.append([i, i+1, i+2])
                i += 3
        
        mesh = Trimesh(v, f)
        mesh.fix_normals()
        mesh.merge_vertices()
        
        return mesh

```

**Comment by YassinWalid** [comment]
Is this issue still existent? Because I was just trying to do boolean operations using blender and it returns empty meshes.

**Comment by panallax** [comment]
> Is this issue still existent? Because I was just trying to do boolean operations using blender and it returns empty meshes.

Still happening, recommended to change the engine to manifold3d
