### ISSUE TITLE
 'trimesh.voxel' has no attribute 'points_to_marching_cubes' How to solve?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#619]
Error below:

m=trimesh.voxel.points_to_marching_cubes(points,pitch=pitch)
AttributeError: module 'trimesh.voxel' has no attribute 'points_to_marching_cubes' ?

@mikedh

**Comment by mikedh** [comment]
Hey, it moved into the `ops` submodule, `trimesh.voxel.ops.points_to_marching_cubes`

**Comment by ikhblo** [comment]
When I added ops, it showed TypeError: matrix_to_marching_cubes() got an unexpected keyword argument 'origin'
![a](https://user-images.githubusercontent.com/67190477/119226054-fdc4df80-bb39-11eb-8ec8-b54d51e35d00.png)
@mikedh

**Comment by mikedh** [comment]
Hey, the only keyword arguments for `matrix_to_marching_cubes` are `matrix` and `pitch`, just remove the `origin` from your call:

https://trimsh.org/trimesh.voxel.ops.html#trimesh.voxel.ops.matrix_to_marching_cubes

**Comment by ikhblo** [comment]
The problem was solved, thank you very much.
