### ISSUE TITLE
Differences in Pyassimp FBX and STL results

### ISSUE THREAD

**Issue by rebcabin** [mikedh/trimesh#62]
I'm exercising trimesh on some FBX models. I backed off to Pyassimp after having bad luck with Cyassimp (unexplained IO failures in the C code), looking for ways to make quicker progress (I may one day get back to Cyassimp, but I need to move quickly now). I am having good luck with Pyassimp, but I noticed some differences in the shape of results returned to trimesh from Pyassimp when Pyassimp imports FBX models and when Pyassimp imports STL models. I worked around the differences at the trimesh level, but my workarounds aren't sufficiently well thought-out (by a very long margin) to submit as a pull request.  In fact, this entire issue may be better addressed as an assimp issue, and I will be digging in there as time allows. In the meantime, I thought I'd bring it to your attention. Perhaps the following code snippet from near line 120 in load.py is self-explanatory. This is what I did to get trimesh to work.

```
    # make sure we keep passed kwargs to loader
    # but also make sure loader keys override passed keys
    loader_keys = mesh_loaders[file_type](file_obj, file_type)
    # [bbeckman: introduce the variable above to track in the debugger.
    # Apparently, the fbx loader produces a list of dictionaries, whereas the
    # STL loader, used in all the examples in trimesh, produces a dictionary.
    # That trips up kwargs.update. We'll just work around it for our cases.]
    if isinstance(loader_keys, list):
        kwargs.update(loader_keys[0])
    else:
        kwargs.update(loader_keys)

    # [bbeckman: The fbx loader returns a vertex_colors key whose value is
    # the empty list, []. That apparently causes some downstream methods to
    # silently fail. The failure occurs in the ColorVisuals call at the end
    # of visual.create_visual, which is called on line 105 of base.py. We'll
    # work around it for our cases.]
    if 'vertex_colors' in kwargs and \
            not kwargs["vertex_colors"]: # idiom for empty
        kwargs.pop("vertex_colors")
```

**Comment by mikedh** [comment]
Thanks for the report! Do you have a sample file that exhibits this behavior that you could share?

**Comment by rebcabin** [comment]
Here is a tiny FBX file with one small mesh named j3-09. The mesh represents a cylindrical drum, each head of which is a 32-gon. The FBX file comes from Blender and has many duplicated vertices (that's OK, I know how to dedupe the file using trimesh :) Trimesh, after deduping, reports the expected number of 64 vertices and the wireframe display and bounding box look great.

I pasted the binary FBX file here https://filebin.ca/3RtL5GJx1qpa/j3-9-binary.fbx. Assimp (not pyassimp) tokenizes, parses, and dumps this in an assxml file, pasted here https://filebin.ca/3RtM8CgVtYyE/j3-9-binary.assxml. There is a discrepancy between the number of vertices reported by assimp and the number of vertices reported by FBX SDK. It may not be related to the trimesh issue with shape-of-data, then again, it may be! I opened  an issue at assimp's site https://github.com/assimp/assimp/issues/1331. 

I have an ASCII dump of the file (pasted here https://filebin.ca/3RtRth2lxqPc/j3-9.fbx). It has 396 vertex coordinates. I presume that these must be partitioned into triplets, which would give me 132 vertices. When I partition the 396 coordinates into triples (with a Python program and with another Clojure program to cross check), and then manually dedupe (e.g., with Pandas group_by).

Trimesh reports 124 vertex triples. This is suspiciously 372 div 3. I suspect that trimesh gets the 372 vertex triples from assimp, then erroneously assumes that there are 372 scalar coordinates. The mystery is deep, however, because the output of trimesh looks just like the drum, so trimesh and assimp are somehow correct and potentially incorrect at the same time.

I tried reading the ASCII dump with assimp, but the version in the ASCII dump is too high and assimp refuses to read it.

Assimp also does a very interesting and consistent revision of the PolygonVertexIndex (PVI) data. In the original FBX file, the indices in the PVI data range from 0 to 131, as one would expect if the true vertex count were 132 == 396 coordinates. Assimp reports 372 vertex normals (the "Normals" tag in the assxml file). So assimp is behaving consistently internally.

This whole issue is most likely just lack of understanding on my part! But I need the numbers to make sense to me to move ahead confidently.

**Comment by rebcabin** [comment]
I figured out the assimp code and closed the issue with them. Their code (in FbxMeshGeometry) is reasonable. They create a new vertex for every index in the original FBX PolygonVertexIndex. This issue is still open because I am moving next to FBX files that contain multiple meshes and would like to use trimesh.

**Comment by mikedh** [comment]
Gotcha- unfortunately neither my install of pyassimp or cyassimp are able to load that FBX file at all so I don't know how much help I can be on this one. 

Yeah for multiple models its possible the right behavior for trimesh is to return a trimesh.Scene object (like the 3DXML loader does) rather than a list of meshes.

**Comment by rebcabin** [comment]
ok, that's a good clue (trimesh.Scene for multiple models).  I'll leave this issue open while I'm actively pursuing (that is, if you don't mind) and add info as I come across it.

**Comment by mikedh** [comment]
No worries, fine with me! Any luck with this issue?

**Comment by mikedh** [comment]
Closing for now, as I have no plans or ability to debug FBX. Feel free to re-open.
