### ISSUE TITLE
Depth map to point cloud 

### ISSUE THREAD

**Issue by jsaisagar** [mikedh/trimesh#620]
Hi,

Is there a way to convert depth map given intrinsics to point cloud?

Thanks,

**Comment by mikedh** [comment]
Hey, yeah it's pretty straightforward with some straight numpy code, check out this issue: https://github.com/mmatl/pyrender/issues/14

**Comment by jsaisagar** [comment]
Hi mike,

Thanks for the help.
I have tried the numpy code. I am reading the same image stored and using same fov. However, I am losing the depth dimension. May I know where is the issue?
I have attached the images of reconstructed point clouds.

Thanks,

Code: 
"""
raytrace.py
----------------

A very simple example of using scene cameras to generate
rays for image reasons.

Install `pyembree` for a speedup (600k+ rays per second)
"""
from __future__ import division

import PIL.Image

import trimesh
import numpy as np
import cv2

def pointcloud(depth, fov):
        fy = fx = 0.5 / np.tan(fov * 0.5) # assume aspectRatio is one.
        height = depth.shape[0]
        width = depth.shape[1]

        mask = np.where(depth > 0)

        x = mask[1]
        y = mask[0]

        normalized_x = (x.astype(np.float32) - width * 0.5) / width
        normalized_y = (y.astype(np.float32) - height * 0.5) / height

        world_x = normalized_x * depth[y, x] / fx
        world_y = normalized_y * depth[y, x] / fy
        world_z = depth[y, x]
        ones = np.ones(world_z.shape[0], dtype=np.float32)

        return np.vstack((world_x, world_y, world_z)).T

if __name__ == '__main__':

    # test on a simple mesh
    mesh = trimesh.load('../models/featuretype.STL')

    # scene will have automatically generated camera and lights
    scene = mesh.scene()

    # any of the automatically generated values can be overridden
    # set resolution, in pixels
    scene.camera.resolution = [480, 480]
    # set field of view, in degrees
    # make it relative to resolution so pixels per degree is same
    #scene.camera.fov = 60 * (scene.camera.resolution /
    #                         scene.camera.resolution.max())

    # convert the camera to rays with one ray per pixel
    origin, vectors = scene.camera_rays()

    # intersects_location requires origins to be the same shape as vectors
    origins = np.tile(np.expand_dims(origin, 0), (len(vectors), 1))

    # do the actual ray- mesh queries
    points, index_ray, index_tri = mesh.ray.intersects_location(
        origins, vectors, multiple_hits=False)
    #points, index_ray, index_tri = mesh.ray.intersects_id(
    #    origins, vectors, multiple_hits=True, return_locations=True)

    print(points[0])
    print(index_ray.shape)
    print(index_tri.shape)
    # for each hit, find the distance along its vector
    # you could also do this against the single camera Z vector
    depth = trimesh.util.diagonal_dot(points - origin,
                                      vectors[index_ray])
    # find the angular resolution, in pixels per radian
    ppr = scene.camera.resolution / np.radians(scene.camera.fov)
    # convert rays to pixel locations
    angles = scene.camera.angles()
    print('angles ',ppr)
    pixel = (angles * ppr).round().astype(np.int64)
    # make sure we are in the first quadrant
    pixel -= pixel.min(axis=0)
    # find pixel locations of actual hits
    pixel_ray = pixel[index_ray]

    # create a numpy array we can turn into an image
    # doing it with uint8 creates an `L` mode greyscale image
    a = np.zeros(scene.camera.resolution, dtype=np.uint8)

    # scale depth against range (0.0 - 1.0)
    depth_float = ((depth - depth.min()) / depth.ptp())
    print('Depth shape ', depth_float.shape)

    # convert depth into 0 - 255 uint8
    depth_int = (depth_float * 255).astype(np.uint8)
    # assign depth to correct pixel locations
    a[pixel_ray[:, 0], pixel_ray[:, 1]] = depth_int

    # create a PIL image from the depth queries
    img = PIL.Image.fromarray(a)

    img.show()
    img.save("feature.png")

    depth_img = cv2.imread('feature.png',0)
    pcl = pointcloud(depth_img, 60)
    np.savetxt('recon.
![Screenshot from 2019-11-22 06-14-08](https://user-images.githubusercontent.com/6646353/69388774-042d8d80-0cf0-11ea-897e-870fb79a2c60.png)
![Screenshot from 2019-11-22 06-14-12](https://user-images.githubusercontent.com/6646353/69388775-042d8d80-0cf0-11ea-9104-f05239147805.png)

xyz', pcl)

**Comment by mikedh** [comment]
Hey, I think it is probably how you are scaling the unsigned 8 bit depth back to a float, it needs to be multiplied by the original z-range.

This line scaled it down:
`depth_float = ((depth - depth.min()) / depth.ptp())`

So you need to scale it back rather than just using the int value, using something like:
`reconstructed_depth = (image_value * depth.ptp()) + depth.min()`

I believe this line is where you should be scaling and aren't:
`world_z = depth[y, x]`
