### ISSUE TITLE
Add UV to Trimesh

### ISSUE THREAD

**Issue by kristiansvenssonsweco** [mikedh/trimesh#621]
Hi!

I have successfully created a Trimesh using:
`mesh = trimesh.Trimesh(vertices=pointsarray,faces=trianglesarray)`

I have an array with UV coordinates as well. How do I add the UV-coordinates to my mesh?

Example of how my UV array looks like:
```
[[0.9672828815961166, 0.9883784023401689, 0.5], 
[0.9699707324392943, 0.9795670448628443, 0.5], 
[0.9690897147662995, 0.9732014867976551, 0.5], 
[0.9763618445706598, 0.977744843160596, 0.5], 
[0.9699707324392943, 0.9795670448628443, 0.5]]
```

**Comment by mikedh** [comment]
Hey, if you have UV's and a corresponding image you can create a `TextureVisuals` object, and then assign it to the mesh with `mesh.visual = TextureVisuals(**kwargs)`:

```
In [4]: trimesh.visual.TextureVisuals?
Init signature: trimesh.visual.TextureVisuals(uv=None, material=None, image=None)
Docstring:      <no docstring>
Init docstring:
Store a single material and per-vertex UV coordinates
for a mesh.

If passed UV coordinates and a single image it will
create a SimpleMaterial for the image.

Parameters
--------------
uv : (n, 2) float
  UV coordinates for the mesh
material : Material
  Store images and properties
image : PIL.Image
  Can be passed to automatically create material

```

**Comment by xubaixinxbx** [comment]
> Can be passed to automatically create material

hi, is it possible to export the texture image, given the vertex colors and each vertex uv
