### ISSUE TITLE
Help on dealing with Qhull error

### ISSUE THREAD

**Issue by Da-Rudi** [mikedh/trimesh#624]
Hey, i get an Qhull error when I try to access the bounding sphere of my mesh. When loading the mesh from the stl file the bounding sphere will not be initialized. When I try to access it the following error occurs. Interesting to mention is that the same file does not create any error when using macOS instead of ubuntu with the same version of trimesh scipy etc. installed..

`1 Exception no bounding sphere Mesh - get bounding box sphere

  | QH6271 qhull precision error (qh_check_dupridge): wide merge (510772416 times wider) due to duplicate ridge with nearly coincident points (0.087) between f2779 and f2795, merge dist 0.00021, while processing p730

  | - Ignore error with option 'Q12'
  | - To be fixed in a later version of Qhull
  | - A bounding box for the input sites may alleviate this error.
  | - Vertex distance 0.087 is greater than 100 times maximum distance 4.1e-13
  |   Please report to bradb@shore.net with steps to reproduce and all output

  | ERRONEOUS FACET:
  | - f2779
  |     - flags: bottom new dupridge mergeridge2
  |     - normal:    0.3868  0.06681  0.06681  -0.9173
  |     - offset: -0.5705895
  |     - vertices: p730(v142) p737(v49) p744(v26) p368(v2)
  |     - neighboring facets: f1734 f2783 f2780 f2795
  |     - ridges:
  |      - r1152
  |            vertices: p737(v49) p744(v26) p368(v2)
  |            between f1734 and f2779
  |      - r1153
  |            vertices: p730(v142) p744(v26) p368(v2)
  |            between f2779 and f2783
  |      - r1154
  |            vertices: p730(v142) p737(v49) p368(v2)
  |            between f2780 and f2779
  |      - r1155
  |            vertices: p730(v142) p737(v49) p744(v26)
  |            between f2779 and f2795
  | ERRONEOUS OTHER FACET:
  | - f2795
  |     - flags: top new dupridge mergeridge1
  |     - normal:    0.4306  0.06539  0.06539  -0.8978
  |     - offset: -0.7321693
  |     - vertices: p730(v142) p95(v88) p737(v49) p744(v26)
  |     - neighboring facets: f1565 f2791 f2789 f2779
  |     - ridges:
  |      - r1149
  |            vertices: p95(v88) p737(v49) p744(v26)
  |            between f2795 and f1565
  |      - r1151
  |            vertices: p730(v142) p95(v88) p737(v49)
  |            between f2791 and f2795
  |      - r1150
  |            vertices: p730(v142) p95(v88) p744(v26)
  |            between f2795 and f2789
  |      - r1155
  |            vertices: p730(v142) p737(v49) p744(v26)
  |            between f2779 and f2795
  | 
  | While executing:  | qhull v Qc Qu Qbb
  | Options selected for Qhull 2015.2.r 2016/01/18:
  |   run-id 623018080  voronoi  Qcoplanar-keep  QupperDelaunay  Qbbound-last
  |   _pre-merge  _zero-centrum  Qinterior-keep  Pgood  _max-width 14
  |   Error-roundoff 2.8e-14  _one-merge 2.5e-13  Visible-distance 1.7e-13
  |   U-coplanar-distance 1.7e-13  Width-outside 3.3e-13  _wide-facet 9.9e-13
  | Last point added to hull was p730.  Last merge was #352.
  | 
  | At error exit:
  | 
  | Furthest-site Voronoi vertices by the convex hull of 871 points in 4-d:
  | 
  |   Number of Voronoi regions: 142
  |   Total number of nearly incident points: 729
  |   Number of Voronoi vertices: 0
  |   Number of non-simplicial Voronoi vertices: 53
  | 
  | Statistics for:  | qhull v Qc Qu Qbb
  | 
  |   Number of points processed: 142
  |   Number of hyperplanes created: 2609
  |   Number of facets in hull: 779
  |   Number of distance tests for qhull: 29825
  |   Number of distance tests for merging: 22207
  |   Number of distance tests for checking: 0
  |   Number of merged facets: 359
  |   Maximum distance of merged point above facet: 4.1e-13 (1.5x)
  |   Maximum distance of merged vertex below facet: -4.6e-13 (1.7x)
  | 
  | 
  | precision problems (corrected unless 'Q0' or an error)
  |       5 flipped facets
  |     136 coplanar horizon facets for new vertices
  |      30 degenerate hyperplanes recomputed with gaussian elimination
  |      30 nearly singular or axis-parallel hyperplanes
  |       1 ridges with multiple neighbors`

**Comment by mikedh** [comment]
Hey, this is probably more of a qhull/scipy issue than a trimesh issue. That being said, I'd try removing degenerate faces, either with `mesh.remove_degenerate_faces()` or by loading the mesh with validation to remove degenerate/duplicate faces on load: `trimesh.load('file.stl', validate=True)`.
