### ISSUE TITLE
Import trimesh data in blender

### ISSUE THREAD

**Issue by ibozhilov** [mikedh/trimesh#626]
I was wondering if there is a way to load trimesh data into blender. If there is no straight forward way, I will also love any suggestions on how to do it. I am aware of the possibility to export to some 3D format and then import the file in Blender, but I am looking for a way to do it directly using the bpy module. Sorry if this question is already asked or there is some info in the documentation, but I was not able to find it. 

Thanks in advance.

**Comment by mikedh** [comment]
Hey, if trimesh is in your `PYTHONPATH`, you can actually import `trimesh` into the blender terminal. Then you could transfer the `mesh.vertices` objects using the `bpy` API: https://blender.stackexchange.com/questions/61879/create-mesh-then-add-vertices-to-it-in-python/61893
