### ISSUE TITLE
Test if 2D point is inside triangle

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#627]
Is it possible to check whether a point is inside a triangle (all in 2D) with trimesh?
I have an implementation but it is a bit naive, and thus not very fast.

Thanks for any hint!

**Comment by mikedh** [comment]
Hey, there's no specifically 2D optimized version, but you *could* make a mesh with zero Z, and then just call `trimesh.proximity.closest_point`.

**Comment by clemense** [comment]
Thanks!   I finally built an 2d rtree using the uv triangles; followed by a point-triangle intersection check.
