### ISSUE TITLE
SVG import vertices order not preserved

### ISSUE THREAD

**Issue by panangam** [mikedh/trimesh#631]
I am trying to use Trimesh to read SVG file containing only a polygonal path into Path2D before using the Shapely Polygons that came with it. However, I find that when checking the vertices using

```python
saved_path = trimesh.load_path('test.svg')
list(saved_path.polygons_closed[0].exterior.coords)
```

I find that the ordering of vertices have changed, being cycled. For my use case, correct ordering of the vertices is crucial. I tried `saved_path = trimesh.load_path('test.svg', process=False)`, but that did not work, as the entities seemed to be messed up.

I also know that my curve is a closed polygon. Is there a solution to this? Or maybe Trimesh is not the right tool for it?

**Comment by mikedh** [comment]
Yeah, the automatic cycle generation makes this a little tricky. In #636 it should combine strictly polygonal segments into a single entity, so if you load with `path = trimesh.load('polygon.svg', process=False)` the order should be preserved inside the entity.
