### ISSUE TITLE
GLTF node name round trip

### ISSUE THREAD

**Issue by FreakTheMighty** [mikedh/trimesh#633]
I noticed that the node names I write out using GLTF do not import with the same names. What is the reason for this line? Would you consider removing it, so that the node names are preserved upon export?

https://github.com/mikedh/trimesh/blob/ee43dc3e77b85606e37683307ef12e5cea4e0338/trimesh/exchange/gltf.py#L995-L998

**Comment by FreakTheMighty** [comment]
@mikedh thank you! That seems to have done the trick.

**Comment by mikedh** [comment]
Great! I noticed some of the meshes in the `gltf-samples` corpus didn't always have `child['name']` populated and didn't have time to investigate further, but it seems like in the large majority of cases #636 helps.

And yeah as a higher level point I totally agree a GLTF roundtrip should keep as much information as possible the same. Thanks for the report!
