### ISSUE TITLE
grid structures in depth image

### ISSUE THREAD

**Issue by RohanChacko** [mikedh/trimesh#635]
Hi,

I am trying to create a depth image using [raytrace.py](https://github.com/mikedh/trimesh/blob/master/examples/raytrace.py) and I appear to get this image as output unlike the one shown in  #340 . 
![image](https://user-images.githubusercontent.com/8079868/69787209-05742400-11e2-11ea-83e2-1516cd277a1d.png)

Is there some package/backend config I am missing?

Thanks

**Comment by mikedh** [comment]
Ah, this is a ray-pixel conversion error that materialized somehow. I have a fix working locally, I'll PR it after the holiday. Thanks for the report!
