### ISSUE TITLE
How to extract features from mesh and how to train the features using trimesh ?

### ISSUE THREAD

**Issue by selvakarna** [mikedh/trimesh#639]
How to extract features from mesh and how to train the features using trimesh ?

@mikedh

**Comment by mikedh** [comment]
I think this is probably out of scope for `trimesh`, you might check out [kaolin](https://github.com/NVIDIAGameWorks/kaolin) or look at what people have done in other 3D learning projects:

https://github.com/TimoBolkart/voca
https://github.com/nkolot/SPIN
https://github.com/soubhiksanyal/RingNet
