### ISSUE TITLE
Coloring specific vertices

### ISSUE THREAD

**Issue by roaasoloh** [mikedh/trimesh#642]
Thanks for this amazing library,
I was able to read my mesh and apply some factors on it in order to extract interest points, now what I'm tending to do, is to color these interest points differently and visualize them then save the new mesh.
So, my interest points are like this:
 `[513 549 647 244 304 450  40 475 633  10 200 212 702 238 216 185 315 152
 665 787 688   6 790 437 201  83 584 855 306 717 750 320 287 428 168 550
 776 321 578   5  33 645  32 720  58  30 271 374 187 632 597 555 583  55
 302  36  92 862 671 207 835 372 286 454 192 332  64 351 294  66 598 522
  34 567 296 743 501 322  77 365 356 660 267  54 851 254]`
How this could be done using trimesh? I don't want to color all the object, instead just these vertices for example like what is shown in the image
![points](https://user-images.githubusercontent.com/29208631/70046347-29f74400-15c6-11ea-9f1f-f193427f23c6.png)

**Comment by roaasoloh** [comment]
I tried using this: 
`    for color in interest_points:
        mesh.visual.vertex_colors[color] = trimesh.visual.random_color()
`
But it didn't color exactly the vertex as well coloring randomly, How to specify specific color?
![apple](https://user-images.githubusercontent.com/29208631/70049061-1e0e8080-15cc-11ea-8770-b473f35c9c44.png)

Also if I applied a feature descriptor on these points like for example fourier transform, which output like the following:
`[ 3.30420000e+04   +0.j         -6.09423261e+01-1112.67840561j
 -9.27545907e+02+1200.76205493j  2.82110276e+03+1346.92962041j
 -3.88349175e+02 +152.10763418j  7.07352268e+02 -802.77406158j
  5.05176074e+02-2103.59375803j  1.94453177e+03 +580.2696864j
 -1.27087979e+03+2484.97622413j  2.42122584e+03-1457.29825746j
  1.11365782e+03 -565.65437694j -3.85338312e+03 +242.68175108j
  2.66779039e+03 +395.06521406j -9.93426796e+02 -366.20512407j
  1.61902982e+03-1352.75800064j  1.51039457e+03-2778.92816676j
  2.85919541e+02 +210.10805825j -4.85195173e+02 -729.19326039j
 -5.41518455e+02+3105.84424457j -4.57711475e+02+1442.99981975j
 -1.07324375e+03 -150.94437677j -1.25523997e+03 +309.11020857j
  5.05304798e+02+1824.96305357j  1.79448137e+03-2007.7777326j
 -5.52170800e+02-2255.62667232j -4.91252392e+03 +426.44770627j
 -4.32135770e+02-1431.76999557j  5.63207702e+02-1149.59724725j
 -2.06202613e+03 +611.61967562j -1.70508624e+03 +271.36876193j
 -5.33252532e+02-1716.48173374j -2.52572189e+03+2462.66463454j
  1.53789484e+03-4659.60343839j  1.25201644e+03+1279.10680515j
  1.73267218e+03+1395.87766865j  3.10441697e+01 -224.69538578j
  2.27164388e+03-2278.99770794j -8.08449191e+02-1618.07458402j
  2.52476058e+03 +412.07740089j  4.11670217e+02-1762.7175352j
  1.65597313e+03 -180.27615783j -1.16884700e+03+2256.14611555j
  1.34979927e+03+1957.5273874j   6.38000000e+02   +0.j
  1.34979927e+03-1957.5273874j  -1.16884700e+03-2256.14611555j
  1.65597313e+03 +180.27615783j  4.11670217e+02+1762.7175352j
  2.52476058e+03 -412.07740089j -8.08449191e+02+1618.07458402j
  2.27164388e+03+2278.99770794j  3.10441697e+01 +224.69538578j
  1.73267218e+03-1395.87766865j  1.25201644e+03-1279.10680515j
  1.53789484e+03+4659.60343839j -2.52572189e+03-2462.66463454j
 -5.33252532e+02+1716.48173374j -1.70508624e+03 -271.36876193j
 -2.06202613e+03 -611.61967562j  5.63207702e+02+1149.59724725j
 -4.32135770e+02+1431.76999557j -4.91252392e+03 -426.44770627j
 -5.52170800e+02+2255.62667232j  1.79448137e+03+2007.7777326j
  5.05304798e+02-1824.96305357j -1.25523997e+03 -309.11020857j
 -1.07324375e+03 +150.94437677j -4.57711475e+02-1442.99981975j
 -5.41518455e+02-3105.84424457j -4.85195173e+02 +729.19326039j
  2.85919541e+02 -210.10805825j  1.51039457e+03+2778.92816676j
  1.61902982e+03+1352.75800064j -9.93426796e+02 +366.20512407j
  2.66779039e+03 -395.06521406j -3.85338312e+03 -242.68175108j
  1.11365782e+03 +565.65437694j  2.42122584e+03+1457.29825746j
 -1.27087979e+03-2484.97622413j  1.94453177e+03 -580.2696864j
  5.05176074e+02+2103.59375803j  7.07352268e+02 +802.77406158j
 -3.88349175e+02 -152.10763418j  2.82110276e+03-1346.92962041j
 -9.27545907e+02-1200.76205493j -6.09423261e+01+1112.67840561j]
` 
How these values could be visualized depending on the points we obtained from.

**Comment by mikedh** [comment]
Hey, `vertex_colors` are going to color one of the three vertices and then blend it across the face. You might want to use a `PointCloud`:

```
In [3]: m = trimesh.load('models/featuretype.STL')

In [4]: m
Out[4]: <trimesh.Trimesh(vertices.shape=(1722, 3), faces.shape=(3476, 3))>

In [5]: p = trimesh.PointCloud(m.vertices[:10])

In [6]: p
Out[6]: <trimesh.PointCloud(vertices.shape=(10, 3), 10, 3)>

In [7]: trimesh.Scene([m, p]).show()
Out[7]: SceneViewer(width=1800, height=1350)

In [8]: p = trimesh.PointCloud(m.vertices[:100])
```

**Comment by roaasoloh** [comment]
Ok, great thank you,
but kindly what about the second case(mentioned in the comment)? I mean when extracting descriptors from these obtained points and I want to visualize them? the case will be somehow similar to that mentioned [Here](https://user-images.githubusercontent.com/39670256/62493345-c3ede200-b7c8-11e9-962f-1d0fb6b4f40b.png), How much the solution given [Here](https://github.com/mikedh/trimesh/issues/526) is applicable.

**Comment by mikedh** [comment]
Hey, check out [this article on vertex color](https://gamedev.stackexchange.com/questions/139059/what-is-a-vertex-color). To get a result like the example you linked, you will need to create some function which calculates color of *every* vertex, otherwise you end up with the patchy color like your image.
