### ISSUE TITLE
Preserve entire graph during glTF export

### ISSUE THREAD

**Issue by FreakTheMighty** [mikedh/trimesh#643]
This is vaguely related to #633, but seems like it will be a bigger project. It would be great to preserve the scene graph constructed in trimesh during export to glTF. At the moment the scene graph is flattened, so intermediate nodes between `world` and each mesh are lost.

I can see the value of simplifying the scene graph, but if a user wishes to do so, they can create a new scene with flattened transforms.

https://github.com/mikedh/trimesh/blob/1d2334535c1845ffab2439b0d55a3e7de85617a9/trimesh/scene/transforms.py#L126-L168

**Comment by mikedh** [comment]
Yeah this would be great, and PR's super welcome!

**Comment by FreakTheMighty** [comment]
Sounds good. It’s not super high priority for me, but wanted to capture it. If it becomes more critical I’ll work on a pull request.
