### ISSUE TITLE
Moment of Inertia of a 1-2-3 cuboid

### ISSUE THREAD

**Issue by rebcabin** [mikedh/trimesh#65]
Hi Mike -- I produced a 1-2-3 scaled cuboid in Blender, then triangularized it in MeshMixer. I will paste the raw Blender model and the triangularized MeshMixer model in OBJ format below, but the rest of this issue concerns only the MeshMixer model (trimesh found the original Blender model to be not watertight, so I stopped analyzing it). 

My hand calculation of the principal moments of inertia finds $4\ast{(1+4)}/12=5/3$, $4\ast{(4+9)}/12=5$, and $4\ast{(1+9)}/12=10/3$, which I spot-checked with a couple of online engineering calculators. Trimesh finds $208$, $80$, and $160$ (around line 184 of triangles.py). I can't reconcile these with my hand calculation by a constant factor (48, the volume of the cuboid, suffices to correct two of them, namely 10/3 ~~> 160 and 5/3 ~~> 80, but not the third, which would be 240 and not 208). I hypothesize a bug in the geotools formulas in the cited paper (bless you for citing your references in comments: if only I could get my other professional engineers to do just that one little thing!)

First the Blender .OBJ, then the MeshMixer .OBJ:

```
# Blender v2.78 (sub 0) OBJ File: 'one_two_three_cuboid.blend'
# www.blender.org
mtllib one_two_three_cuboid.mtl
o Cube
v 1.000000 -3.000000 -2.000000
v 1.000000 -3.000000 2.000000
v -1.000000 -3.000000 2.000000
v -1.000000 -3.000000 -2.000001
v 1.000000 3.000000 -1.999999
v 0.999999 3.000000 2.000001
v -1.000000 3.000000 1.999999
v -1.000000 3.000000 -2.000000
vn 0.0000 -1.0000 0.0000
vn 0.0000 1.0000 0.0000
vn 1.0000 0.0000 0.0000
vn -0.0000 -0.0000 1.0000
vn -1.0000 -0.0000 -0.0000
vn 0.0000 0.0000 -1.0000
usemtl Material
s off
f 1//1 2//1 3//1 4//1
f 5//2 8//2 7//2 6//2
f 1//3 5//3 6//3 2//3
f 2//4 6//4 7//4 3//4
f 3//5 7//5 8//5 4//5
f 5//6 1//6 4//6 8//6
```

```
v 1 -3 -2
vn 0.9230769873 -0.3076921999 -0.2307690978
v 1 -3 2
vn 0.6882471442 -0.2294157147 0.6882472634
v -1 -3 2
vn -0.9230769277 -0.3076923192 0.2307692319
v -1 -3 -2.000000954
vn -0.6882471442 -0.2294157296 -0.6882472634
v 1 3 -1.999999046
vn 0.6396024227 0.4264013469 -0.6396019459
v 0.9999989271 3 2.000000954
vn 0.957704246 0.1596173793 0.2394261211
v -1 3 1.999999046
vn -0.6396023631 0.4264013469 0.6396020055
v -1 3 -2
vn -0.957704246 0.1596173942 -0.2394260913
# mm_gid 0
g mmGroup0
f 1//1 2//2 3//3 
f 1//1 3//3 4//4 
f 5//5 8//8 7//7 
f 5//5 7//7 6//6 
f 1//1 5//5 6//6 
f 1//1 6//6 2//2 
f 2//2 6//6 7//7 
f 2//2 7//7 3//3 
f 3//3 7//7 8//8 
f 3//3 8//8 4//4 
f 5//5 1//1 4//4 
f 5//5 4//4 8//8 
```

**Comment by mikedh** [comment]
Hey, thanks for the report! I did some checks on the second model you sent, and it looked like the trimesh implementation matched the formula on Wikipedia. It also matched a mass report from Solidworks  (my 'ground truth' on the theory that airplanes would fall out of the sky if they screwed up their inertia calculations).

When I manually calculate the cuboid PCI using the formula [on wikipedia](https://en.wikipedia.org/wiki/List_of_moments_of_inertia) I get:

```
In [37]: m.extents
Out[37]: array([ 2.,  6.,  4.])

In [38]: density = 1.0

In [39]: mass = np.product(m.extents) * density

In [40]: mass
Out[40]: 48.000022895999997

In [41]: PCI = [mass*(np.roll(m.extents, 3-i)[1:]**2).sum()/12.0 for i in range(3)]

In [42]: PCI
Out[42]: [208.00016027204367, 80.000099216043679, 160.00007631999998]

In [43]: m.moment_inertia
Out[43]:
array([[ 207.99996,   -0.     ,    0.     ],
       [  -0.     ,   79.99997,    0.00001],
       [   0.     ,    0.00001,  159.99996]])

In [44]: m.principal_inertia_components
Out[44]: array([ 207.99996,   79.99997,  159.99996])
```



This also matches the mass report of the model when imported into SolidWorks:

```
Mass properties of cuboid
     Configuration: Default
     Coordinate system: -- default --

Mass (user-overridden) = 48.00000000 kilograms

Volume = 47.99998951 cubic meters

Surface area = 87.99999464 square meters

Center of mass: ( meters )
	X = 0.00000000
	Y = 0.00000000
	Z = 0.00000000

Principal axes of inertia and principal moments of inertia: ( kilograms * square meters )
Taken at the center of mass.
	 Ix = ( 0.00000000,  1.00000000,  0.00000000)   	Px = 79.99999059
	 Iy = ( 0.00000000,  0.00000000,  1.00000000)   	Py = 159.99999940
	 Iz = ( 1.00000000,  0.00000000,  0.00000000)   	Pz = 208.00000092

Moments of inertia: ( kilograms * square meters )
Taken at the center of mass and aligned with the output coordinate system.
	Lxx = 208.00000092	Lxy = -0.00000415	Lxz = 0.00000334
	Lyx = -0.00000415	Lyy = 79.99999059	Lyz = 0.00000629
	Lzx = 0.00000334	Lzy = 0.00000629	Lzz = 159.99999940

Moments of inertia: ( kilograms * square meters )
Taken at the output coordinate system.
	Ixx = 208.00000092	Ixy = -0.00000415	Ixz = 0.00000334
	Iyx = -0.00000415	Iyy = 79.99999059	Iyz = 0.00000629
	Izx = 0.00000334	Izy = 0.00000629	Izz = 159.99999940
```

**Comment by rebcabin** [comment]
My hand calc of $4\ast{(4+9)}/12=5$ was wrong; it's 4+1/3, which is 208/48, so we're back in synch. I strongly appreciate your taking the time to cross-check my arithmetic; this goes a long way in increasing my confidence in trimesh.
