### ISSUE TITLE
Mesh export is not exporting the uv map for compressed archives

### ISSUE THREAD

**Issue by tbarton16** [mikedh/trimesh#651]
`   mesh = trimesh.exchange.load.load_compressed(os.path.join(inputpath_, p),mixed = False)`
        `meshes = mesh.dump()`
       ` count = len(meshes)`
     `   for mesh in meshes:`
        `    z = str(zips)`
          `  z = to_string(z)`
           ` mesh.export(os.path.join(unable, z))`
But the resulting file has no uv map

**Comment by mikedh** [comment]
Is it only on compressed archives? Currently the only format where we support texture exporting is `GLTF`, OBJ currently doesn't have it implemented, though PR's are welcome!

**Comment by mikedh** [comment]
Added OBJ texture exports to enhancements list, thanks for the report! Also PR's are as always super welcome!
