### ISSUE TITLE
Segmentation fault with non-blocking Scene.show() call

### ISSUE THREAD

**Issue by warpedgeoid** [mikedh/trimesh#66]
I am attempting to call Scene.show(block=False) to open a view of meshes being manipulated by user interaction, but the call always causes a segfault. I can replace the call with a blocking call and everything works, except I must wait for the user to close the viewer before continuing.

I am working with the most recent version of trimesh installed via pip on macOS 10.12.5

**Comment by mikedh** [comment]
I've never had much luck with nonblocking shows doing anything useful, as pyglet isn't really designed for it. I've seen that segfault in windows as well, but it does 'work' in Ubuntu. 

That being said I just came across [this issue](https://groups.google.com/forum/#!topic/pyglet-users/qUj7JeQhLgQ), I'll try moving the import into the viewer `__init__` and see if it helps.

**Comment by warpedgeoid** [comment]
Thanks for the update! This isn't really a showstopper for me, just wanted to make sure you knew about the issue.

**Comment by mikedh** [comment]
Cool, glad your able to work around it. Maybe the right thing to do is to remove the option, as it is flaky and rarely does anything useful.

**Comment by warpedgeoid** [comment]
Removing the option may be the course of action, if the problem is upstream and unlikely to be resolved.

**Comment by mikedh** [comment]
Removed the option in https://github.com/mikedh/trimesh/commit/541b5a1af4e8e7dadd945a6080e2bcab997e5625, closing for now. Thanks for the report!
