### ISSUE TITLE
triangles_tree gets messed up using deepcopy

### ISSUE THREAD

**Issue by gregstarr** [mikedh/trimesh#664]
Hi mikedh, great job on trimesh! 

Here is my issue:

I have a class which contains a trimesh.Trimesh object. When I use deepcopy on my class, the Trimesh in the copy has its triangles_tree with crazy bounds, on the order of 10^300 or something. I have tried deleting 'triangles_tree' from the new Trimesh's cache before using it (the error was happening when I was using ray intersection) and this seemed to work. This seems a little hacky though, and I was wondering if you had ever encountered this before and if you had a better way of handling this situation.

Thanks!

**Comment by mikedh** [comment]
Yeah, deepcopy including c-objects like `triangles_tree` or `kdtree` does unpredictable things, including segfaulting. It looks like we can overload the `mesh.__deepcopy__` function to use our safer `mesh.copy` function, which I just added in #665.

Thanks for the report!

**Comment by gregstarr** [comment]
Thanks for addressing this so quickly!
