### ISSUE TITLE
mesh.section error

### ISSUE THREAD

**Issue by datased2019** [mikedh/trimesh#667]
Just give a test on 
slice = mesh.section(plane_origin=mesh.centroid, plane_normal=[0,1,0])

and get DLL error:
from shapely import vectorized
  File "C:\Users\jerry\AppData\Local\Programs\Python\Python37\lib\site-packages\shapely\vectorized\__init__.py", line 3, in <module>
    from ._vectorized import (contains, touches)
ImportError: DLL load failed:

Any comment ? Thx.

**Comment by mikedh** [comment]
Hey, I think that's an issue with shapely, you probably need to reinstall it using a different install method, check out their install guide for windows: https://shapely.readthedocs.io/en/latest/project.html#installing-shapely-1-6

**Comment by datased2019** [comment]
I just follow the method and use the wheels at https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

**Comment by datased2019** [comment]
Clear all the env and libs and try it again. It works. @mikedh 
Thx Mike.
