### ISSUE TITLE
Selecting vertex/faces with certain color and deleting them

### ISSUE THREAD

**Issue by skallagrimmson** [mikedh/trimesh#668]
Hi!

I really enjoy using trimesh thusfar, and was able to load a series of files, split it into different bodies and save the bodies individually. 

I would now like to add a step to that which is deleting all faces/vertices with a specific colour (red, 255/0/0/255). I checked the documentation, but could not figure it out (i'm quite new to python). 

Many thanks in advance!

**Comment by mikedh** [comment]
Hey, you probably want to use `mesh.update_faces` or `mesh.update_vertices` with a boolean mask:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/machinist.XAML')

In [4]: m.visual.face_colors
Out[4]: 
TrackedArray([[  0,   0, 255, 255],
              [  0,   0, 255, 255],
              [  0,   0, 255, 255],
              ...,
              [  0,   0, 255, 255],
              [  0,   0, 255, 255],
              [  0,   0, 255, 255]], dtype=uint8)

In [5]: m.visual.face_colors.ptp(axis=0)
Out[5]: TrackedArray([255, 255, 255,   0], dtype=uint8)

In [6]: face_mask = (m.visual.face_colors == [0,0,255,255]).all(axis=1)

In [7]: m.faces.shape
Out[7]: (2990, 3)

In [8]: face_mask.shape
Out[8]: (2990,)

In [9]: m.update_faces(face_mask)

In [10]: m.faces.shape
Out[10]: (2259, 3)

```

**Comment by skallagrimmson** [comment]
Excellent! 

I managed to invert the mask `face_mask = (m.visual.face_colors == [0,0,255,255]).all(axis=1)` using
 `face_mask_invert = np.where(np.invert(face_mask))[0]` to all the faces that are not red, but i'm not sure if this is the most elegant way. I also tried replacing `==` with `!=`, but that did not work either. 

Also, there is one step after this that is keeping me from combining it with the rest of my workflow... The delete action leaves a lot of isolated (non-connecting) components. When I apply `m.split(only_watertight=False)`, i get a memory error. When I remove these small components first (i.e. in meshlab) and run split it does work. Is it possible to remove these components _before_ i perform the split? 

Thanks so much much!

**Comment by mikedh** [comment]
Yeah, for the `!=` logic you need to change `all` to `any`: `face_mask = (m.visual.face_colors != [0,0,255,255]).any(axis=1)`

For the bunch of tiny components, I'd probably filter them out before doing a full split with something like:

```
# create a mesh with some small junk
In [8]: m = trimesh.creation.box() + trimesh.creation.random_soup(10)
In [10]: m.faces = np.vstack((m.faces, m.faces[-10:]))
In [11]: m
Out[11]: <trimesh.Trimesh(vertices.shape=(38, 3), faces.shape=(32, 3))>

# create a face mask from component size
In [15]: face_ok = np.hstack([c for c in trimesh.graph.connected_components(m.face_adjacency) if len(c) > 3])

In [16]: face_ok
Out[16]: array([ 0, 11, 10,  8,  7,  6,  9,  4,  3,  2,  1,  5])

In [17]: m.update_faces(face_ok)

In [20]: m
Out[20]: <trimesh.Trimesh(vertices.shape=(38, 3), faces.shape=(12, 3))>

```

**Comment by skallagrimmson** [comment]
I would like to add to this discussion that the memory issues mentioned above re-emerged with larger meshes. Even though the above suggestion was very helpful to get rid of unwanted small components, the actual memory error was solved by using the 64 bit version of Python (most likely because allows more ram to be used).

**Comment by mikedh** [comment]
Oh yeah, 32 bit Python is super limited (3gb max IIRC), and one of the ways numpy/trimesh manage to be fast is by using a lot of memory haha.
