### ISSUE TITLE
Problems finding section for big meshes

### ISSUE THREAD

**Issue by matheusfillipe** [mikedh/trimesh#669]
[mesh.zip](https://github.com/mikedh/trimesh/files/3975858/mesh.zip)

 I am trying to cut a mesh as follows:

```
  import trimesh
  import numpy as np  
  mesh = trimesh.load_mesh('/home/matheus/Downloads/mesh.stl')
  z_extents = mesh.bounds[:,2]
  z_levels  = np.arange(*z_extents, step=1)
  sections = mesh.section_multiplane(plane_origin=mesh.bounds[0],
                                    plane_normal=[0,0,1],
                                    heights=z_levels)
  combined = np.sum([s for s in sections if not s is None])

```

But combined returns 0.0 (numpy.float64), and sections is a list of only Nones. Seems to be a bug since my mesh has a height bigger than 1. I tried with other meshes like this and sometime work and sometimes not.  I even tried changing step to 0.01 and still nothing.

My mesh is in the attached zip file.

**Comment by mikedh** [comment]
`heights` is the distance offset from the plane so you probably want something more like:
`heights=np.linspace(mesh.extents[2], 10)`

**Comment by matheusfillipe** [comment]
Thanks! That was really a misunderstanding of mine!
