### ISSUE TITLE
AttributeError: 'PointCloud' object has no attribute 'apply_obb'

### ISSUE THREAD

**Issue by kunkunli** [mikedh/trimesh#673]
When i use 
“mesh = trimesh.load(folder + "registeredScene.ply")
Tform = mesh.apply_obb()”
 Statement，system hint AttributeError: 'PointCloud' object has no attribute 'apply_obb'，How can i modify it？Thanks。

**Comment by mikedh** [comment]
Hey, PLY files without faces defined load as a `PointCloud` rather than `Trimesh` object. Though there's no reason we couldn't move the `apply_obb` function up to the base class.
