### ISSUE TITLE
Export vertex_attributes to gltf

### ISSUE THREAD

**Issue by FreakTheMighty** [mikedh/trimesh#675]
I'm not sure if there is enough information stored with a mesh's `vertex_attributes`, but I'd like to include that data in a GLTF export. For example, if I were to set

```python
mesh.vertex_attributes['_CustomAttribute] = np.array([1,2,3,4])
```
I would like the GLTF export to include the attribute and create an accessor like it does for the standard attributes

https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/gltf.py#L498-L519

Thoughts?

**Comment by mikedh** [comment]
Yeah that would be awesome, especially if it was bidirectional. Happy to take PR's!

**Comment by mikedh** [comment]
Added to enhancements list, good idea!
