### ISSUE TITLE
Can a non-flat GLTF node hierarchy be exported?

### ISSUE THREAD

**Issue by jjmontesl** [mikedh/trimesh#679]
I'm using Scenes and `append_scenes`, but it seems it's not possible to append a scene to another scene. 

I would like to export a full scene tree while maintaining node hierarchy and relative transforms.

Is this possible? if not, what would be a suitable approach to implement this? (I'm thinking of adding a 'children' property to Scenes, Scenes should allow an "add_children" method or accept other scenes in the `add_geometry` method, etc...?)

Side note:  I'd also need to maintain and export metadata at scene/node level (extras).

**Comment by mikedh** [comment]
Hey, with recent versions (after https://github.com/mikedh/trimesh/pull/653) the full graph should export.

**Comment by jjmontesl** [comment]
Thank you for the answer.  don't know how I missed those PR. I am now using trimesh from the master branch.

I'm sorry to ask but I'm struggling to understand how a scene graph should be prepared. I have several trimesh objects and I'd like to combine them in a hierarchy :/. I was first trying to combine scenes but it seems I have to manipulate the `graph` property of the scene. Could you maybe point to an example please?

Am I correct to assume that by adding the same mesh to different nodes in such graph, I'd get shared geometries?

Ideally I'd like to also include empty nodes only with transformations and  `extras` fields. If this is missing I'd be happy to contribute a PR once I grasp trimesh and scenes better.

**Comment by jjmontesl** [comment]
I'm sorry to bump but I'm struggling to understand how node hierarchies should be composed. 

I'm failing to export or visualize nested scenes.

```
from trimesh import primitives
from trimesh.scene import scene

sphere = primitives.Sphere(radius=1.0)
scene1 = scene.Scene(sphere)
scene2 = scene.Scene(scene1)

scene1.export("scene1.glb")  # Works
scene1.show() # Works

scene2.export("scene2.glb")  # Provides an invalid file
scene2.show()  # Throws: ValueError: Geometry passed is not a viewable type!
```

I have also read the note in the `Scene` documentation: "Meshes are added by name, which can then be moved by updating transform in the transform tree.", and thus I've tried several approaches creating or manipulating TransformForest and graph. I keep going through the source code but I feel I'm missing part of othe philosophy behind these objects.

Can the documentation or examples be improved in this regard? 

(If this issue tracker is not an appropriate place to ask I'll move to StackOverflow. I can also submit a PR with updates to documentation if someone gives me some guidance.)
