### ISSUE TITLE
inverted z-axis with section_multiplane

### ISSUE THREAD

**Issue by pmberkeley** [mikedh/trimesh#688]
The same plane_normal and plane_origin, when given to the section method, will produce the expected orientation for my mesh. When these same origins and normals are given to the section_mulitplane method, I'm getting an inverted z-axis result. It should also be noted that the section methods don't work unless the mesh is in the positive quadrant. (They produce a null result if any part of the section cuts through a negative quadrant). 

2x2x2 cm simple stl cube downloaded from here: https://www.ozeki.hu/index.php?owpn=1116

### Import relevant packages
import numpy as np
from shapely.geometry import LineString
import trimesh
import matplotlib as mpl
import matplotlib.pyplot as plt

### Load scan data
mymesh = trimesh.load_mesh('../Cube_3d_printing_sample.stl')

### Move mesh to positive quadrant to avoid errors with section methods
T = [[1,0,0,-mymesh.bounds[0,0]],[0,1,0,-mymesh.bounds[0,1]],[0,0,1,-mymesh.bounds[0,2]],[0,0,0,1]]
mymesh.vertices = trimesh.transform_points(mymesh.vertices,T,translate=True)

### Acquire cross sections using section_multiplane method
y_extents = [mymesh.bounds[0,1],mymesh.bounds[1,1]] 
y_levels = np.arange(*y_extents, step=2)
cross_sections = mymesh.section_multiplane(plane_origin=mymesh.bounds[0],plane_normal=[0,1,0],heights=y_levels)

### Find an arbitrary cross section for demonstration using section method
n = 10
cross_section_n = mymesh.section(plane_normal = [0,1,0], plane_origin = mymesh.bounds[0]+[0,n,0])

### Observe through plot that the section_multiplane results are the negative of the expected orientation, as given by section method
nc = 5 ### 5x2 = 10 and therefore the height for section_multiplane is the same as the height of the section method
figtest = plt.figure()
axtest = figtest.add_axes([0,0,1,1])
axtest.scatter(cross_sections[nc].vertices[:,0],-1*cross_sections[nc].vertices[:,1])
axtest.scatter(cross_section_n.vertices[:,0],cross_section_n.vertices[:,2])

plt.show()

**Comment by mikedh** [comment]
Hey, I'm not totally sure what's happening in your example, but a common issue is that heights are *along the plane normal*, is it possible that's what you are seeing?

```                                                  
import trimesh
import numpy as np

if __name__ == '__main__':
    trimesh.util.attach_to_log()

    m = trimesh.creation.box()
    s = m.section_multiplane(plane_origin=[0,0,0.5],
                             plane_normal=[0,0,-1],
                             heights=np.linspace(0.0, 1.0, 10))

    sr = [m.section(plane_origin=[0,0,0.5 - h],
                    plane_normal=[0,0,-1])
	  for h	in np.linspace(0.0, 1.0, 10.0)]
```

The two methods give the same (correct) result:
```
In [1]: sr
Out[1]: 
[<trimesh.Path3D(vertices.shape=(4, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 <trimesh.Path3D(vertices.shape=(8, 3), len(entities)=1)>,
 None]

In [2]: s
Out[2]: 
[<trimesh.Path2D(vertices.shape=(4, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 <trimesh.Path2D(vertices.shape=(8, 2), len(entities)=1)>,
 None]


```

**Comment by mikedh** [comment]
Feel free to re-open if that isn't what's happening!

**Comment by pmberkeley** [comment]
I did some more digging and testing, and the method you used (with the section multiplane along the z axis) is the only one that doesn't invert the results. If I create an asymmetrical object centered on the z axis, and this is the pseduocode and results: 

**First apparent mode of failure**
_(not really sure what's going on with this, but it isn't difficult for me to bypass, just including it for completeness)_
m = (asymmetrical trimesh object in all 4 positive z axis quadrants)

x_extents = [m.bounds[0,0], m.bounds[1,0]] 
x_levels = np.arange(*x_extents, step=1)
x_cross_sections = m.section_multiplane(plane_origin=m.bounds[0],plane_normal=[1,0,0],heights=x_levels)

This produces "None" for all cross sections in the negative portion of the x axis. The same goes for y axis results. (It isn't located in the negative z quadrants, so I haven't checked this). Therefore, I move the object to the all-positive quadrant as follows: 

T = [[1,0,0,-m.bounds[0,0]],[0,1,0,-m.bounds[0,1]],[0,0,1,-m.bounds[0,2]],[0,0,0,1]]
m.vertices = trimesh.transform_points(m.vertices,T,translate=True)

**Second, and more confusing mode of failure**

After the above transformation, I do the following and get the following results:

**x axis cross sections**
x_extents = [m.bounds[0,0], m.bounds[1,0]] 
x_levels = np.arange(*x_extents, step=1)
x_cross_sections = m.section_multiplane(plane_origin=m.bounds[0],plane_normal=[1,0,0],heights=x_levels)

**x axis results:** 
Negative z axis
Positive y axis

**y axis cross sections**
y_extents = [m.bounds[0,1],m.bounds[1,1]]
y_levels = np.arange(*y_extents, step=1)
y_cross_sections = m.section_multiplane(plane_origin=m.bounds[0],plane_normal=[0,1,0],heights=y_levels)

**x axis results:** 
Negative z axis
Positive x axis

**z axis cross sections**
z_extents = [m.bounds[0,2],m.bounds[1,2]]
z_levels = np.arange(*z_extents, step=1)
sections = m.section_multiplane(plane_origin=m.bounds[0],plane_normal=[0,0,1],heights=z_levels)

**x axis results:** 
Positive x axis
Positive y axis

I tried it with your example, and it doesn't seem to produce the negative axis results, so I'm not sure whether it's a problem associated with how I initially transposed the object? It's also perplexing because it's only inverting the z axis (making the z axis negative), not the x and y, when I use identical plane normals (positive, starting at the lower bound on the object).
