### ISSUE TITLE
How to sample points from .obj files?

### ISSUE THREAD

**Issue by zeal-github** [mikedh/trimesh#689]
I recently load_mesh(xx.obj) file, and want to sample points from this mesh. But the load_mesh return a scene instance, so it has no sampling method. What should I do to transform a Scene instance to a Mesh instance and apply the sampling method to sample points from it?

**Comment by jjmontesl** [comment]
The geometries in a scene (can be `Trimesh` or `Path` objects) are in the `scene.geometries` property.

You can access it by name if you know it: 

`mymesh = scene.geometry['node_name']`

Or you can use `scene.dump()` which gives you an array of all the geometries:

```
geometries = scene.dump()
mymesh = geometries[0]
```

**Comment by zeal-github** [comment]
@jjmontesl Thanks! But what's the node_name refer to? I just load a .obj file and do nothing. 
If I use scene.dump(), does it returns all geometries separately? I want to represent all geometrics in one Trimesh object since I want to sampling for this 3D object.

**Comment by mikedh** [comment]
You probably want to dump (every mesh gets transform baked in) and then concatenate into a single mesh which you can then sample:

```
In [1]: import trimesh

In [2]: s = trimesh.load('models/cycloidal.3DXML')

In [3]: s
Out[3]: <trimesh.Scene(len(geometry)=13)>

In [4]: s.dump()
Out[4]: 
array([<trimesh.Trimesh(vertices.shape=(22719, 3), faces.shape=(42294, 3))>,
       <trimesh.Trimesh(vertices.shape=(320, 3), faces.shape=(320, 3))>,
        ...
       <trimesh.Trimesh(vertices.shape=(96, 3), faces.shape=(92, 3))>,
       <trimesh.Trimesh(vertices.shape=(3704, 3), faces.shape=(4036, 3))>],
      dtype=object)

In [5]: m = trimesh.util.concatenate(s.dump())

In [6]: m
Out[6]: <trimesh.Trimesh(vertices.shape=(219070, 3), faces.shape=(376520, 3))>

```
