### ISSUE TITLE
Unexpected results from union when using Blender backend.

### ISSUE THREAD

**Issue by warpedgeoid** [mikedh/trimesh#69]
I've encountered an odd behavior when performing a union on a set of rectangle using the Blender backend. The rectangles are rotated 90° to each other about the Z axis and when combined should produce a simple cross shape.

![screen shot 2017-07-27 at 11 27 20 am](https://user-images.githubusercontent.com/7670504/28678516-98e9ab26-72be-11e7-83cf-66858e3d0a80.png)

Instead, the resultant shape is truncated on the along the +X direction where the two shape intersect.

![screen shot 2017-07-27 at 11 24 58 am](https://user-images.githubusercontent.com/7670504/28678388-418d05e4-72be-11e7-97c9-4dacf3e62c73.png)

When the same operation is performed using the SCAD backend, the returned shape is a cross, as expected.

![screen shot 2017-07-27 at 11 26 05 am](https://user-images.githubusercontent.com/7670504/28678436-673a9b12-72be-11e7-9ae0-d16e9860415d.png)

Sorry that I haven't had the time to debug this further.

**Comment by mikedh** [comment]
Hey, I think this is probably a result of the Blender boolean ops being wildly less robust (but much faster) than the SCAD/CGAL ones.

**Comment by warpedgeoid** [comment]
Indeed, I think you are correct. Blender tends to ignore some of my errors while SCAD fails with a CGAL error. I'm currently mixing the backends to get my script to run, but eventually, I want to ensure that everything works with both backends. That will require some care on my part to insure that all of my operations are valid.

Quick question, though. Have you ever thought of writing a direct CGAL backend for trimesh?

**Comment by mikedh** [comment]
Cool, I'm going to close this as it appears to be blenders fault :grin: 

Yeah I thought about writing a CGAL backend, but that definitely comes with its own set of challenges- its hard to keep the install process easy and the API simple. I guess I could do one which directly substitutes and then falls back to blender/SCAD (like I did for the pyembree vs homebrew ray tracer).

Also, you might check out pymesh that does that: https://github.com/qnzhou/PyMesh

**Comment by clemense** [comment]
The result of `trimesh.boolean.union([a, b, c])`always ignores the third list element (i only have the Blender backend).   It works with `trimesh.boolean.union([trimesh.boolean.union([a, b]), c])`.
Is this also a Blender issue?

**Comment by mikedh** [comment]
Ah, no idea- I'll try to look in to this.

**Comment by mikedh** [comment]
@clemense this should be fixed by https://github.com/mikedh/trimesh/commit/f1a033040a690ea8743b9e8cb48e0513e28cc701

The deployment finished so you should be able to get it with:
`pip install --upgrade trimesh`

Thanks for the report!
