### ISSUE TITLE
Memory issue during surface sampling

### ISSUE THREAD

**Issue by lejafar** [mikedh/trimesh#691]
Hi Mike!

I bumped into the following issue, when I run the following script my memory usage keeps inreasing with `n` while I would expect it to be approximately constant, for `n=5` I get 500 MB, for `n=100` I get 2.2 GB, for `n=500` I get 3.2 GB as `maximum resident set size` using `/usr/bin/time -l`

```python
import trimesh

n= 100
for i in range(n):
    mesh = trimesh.load('foo.stl') # some part with ~ 300000 faces
    points, face_index = trimesh.sample.sample_surface(mesh, 1000)
    print(i, points.shape)
```
Could this be some kind of memory leak?

**Comment by mikedh** [comment]
Hey, for long-running processes it definitely does increase memory usage over time. I think my conclusion last time was that it was a wider python issue, and to avoid it you kinda have to use a `multiprocessing.Process` per-call or use `supervisord` to restart the job now and then:
https://github.com/mikedh/trimesh/issues/171

I know that's not very satisfying answer haha, if you have a better idea let me know!

**Comment by mikedh** [comment]
Closing for now as I think this "upstream."  Although if you discover a way to avoid this at the trimesh level definitely interested!
