### ISSUE TITLE
Unable to load textures for an obj mesh

### ISSUE THREAD

**Issue by priyankamandikal** [mikedh/trimesh#695]
Hi, I am trying to load an obj mesh with textures using trimesh. However, only the mesh geometry gets loaded without the textures. When I view the mesh in Meshlab, texture is present.  Here is a doc with the images and meshes:
https://docs.google.com/document/d/1y0TXMEXeCSHjjgSHOjS19i0KFK5NU12t0wFH18Sn96g/edit?usp=sharing

What could be the issue here? I am using trimesh version 3.5.9.

Thanks!

**Comment by mikedh** [comment]
Hey, the reason trimesh isn't displaying texture is because that file includes a material library, but doesn't have any `usemtl` directives. If you add one to that file it displays the same as meshlab:
```                                                        
mtllib textured.mtl
usemtl texture_textured.png
v 0.0202016 -0.0936779 0.0123594
v 0.0202016 -0.0869235 0.00513217
```

Not sure why meshlab is showing the texture, maybe they added a rule like 'given one loaded material and no usemtl directive, assume it uses the one material'

**Comment by priyankamandikal** [comment]
Ah didn't catch that, thanks!
One more question. I want to decompose this mesh into a bunch of convex meshes, and then transfer the texture onto the convex pieces. I have used the vhacd extension available from trimesh.exchange.vhacd for convex decomposition of the geometry. I can't seem to find any functions for transferring the original textures onto the convex pieces. It would be great if you could provide some pointers on how I can do that if there aren't any functions already.
P.S. I know this example mesh is already almost convex, but I have other concave meshes where this feature would be super useful.

Thanks a lot!

**Comment by mikedh** [comment]
You could do that in a "mildly jacked up but easy" way by querying for the UV coordinate of the nearest original vertex. On a single convex hull or the output of `mesh.convex_decomposition`:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/fuze.obj')

In [10]: hull = m.convex_hull

In [11]: m.kdtree
Out[11]: <scipy.spatial.ckdtree.cKDTree at 0x7f620ed4fad0>

In [12]: distance, index = m.kdtree.query(hull.vertices)

In [13]: index
Out[13]: 
array([  0,   8,  10,  12,  15,  17,  20,  22,  23,  25,  30,  34,  36,
        37,  38,  41,  45,  50,  53,  59,  61,  63,  65,  70,  71,  74,
        76,  81,  83,  87,  90,  92,  96,  97, 103, 104, 105, 106, 113,
       116, 119, 121, 123, 126, 130, 133, 134, 137, 140, 142, 144, 149,
       155, 156, 160, 162, 163, 166, 169, 175, 176, 179, 183, 186, 187,
       198, 202, 203, 204, 206, 212, 213, 214, 217, 218, 220, 228, 234,
       236, 240, 241, 245, 246, 248, 251, 258, 261, 265, 268, 271, 278,
       281, 282, 286, 288, 289, 292, 294, 298, 300, 301, 302, 308, 309,
       318, 321, 322, 323, 326, 329, 332, 334, 336, 339, 340, 343, 344,
       345, 348, 349, 351, 357, 362, 367, 369, 372, 375, 385, 388, 391,
       392, 396, 397, 402, 403, 406, 417, 418, 422, 424, 425, 428, 432,
       435, 440, 443, 444, 445, 447, 448, 453, 455, 457, 461, 462, 463,
       464, 466, 469, 471, 472, 473, 477, 479, 485, 487, 495, 496, 497,
       499, 504, 506, 507, 512, 514, 516, 517, 524, 526, 528, 533, 537,
       539, 542, 543, 547, 548, 549, 552, 553, 555, 557, 560, 575, 578,
       585, 589, 593, 594, 595, 596, 597, 598, 599, 608, 609, 612, 613,
       618, 622, 624, 629, 633, 636, 640, 642, 645, 647, 654, 656, 657,
       661])

In [14]: hull
Out[14]: <trimesh.Trimesh(vertices.shape=(222, 3), faces.shape=(440, 3))>

In [15]: hull.visual = m.visual.copy()

In [16]: hull.visual.uv
Out[16]: 
TrackedArray([[0.605251, 0.729508],
              [0.773803, 0.770875],
              [0.524785, 0.413303],
              ...,
              [0.05001 , 0.663559],
              [0.403304, 0.419965],
              [0.061527, 0.871682]])

In [17]: hull.visual.uv = m.visual.uv[index]
```

**Comment by SLTK1** [comment]
> Hey, the reason trimesh isn't displaying texture is because that file includes a material library, but doesn't have any `usemtl` directives. If you add one to that file it displays the same as meshlab:
> 
> ```
> mtllib textured.mtl
> usemtl texture_textured.png
> v 0.0202016 -0.0936779 0.0123594
> v 0.0202016 -0.0869235 0.00513217
> ```
> 
> Not sure why meshlab is showing the texture, maybe they added a rule like 'given one loaded material and no usemtl directive, assume it uses the one material'

thx, this answer is very helpful.

**Comment by maazkhan97** [comment]
Hello, I am trying to use the trimesh library to display my .obj file with materials. But I am only able to display the colour of the material and not the actual texture. Can anyone please help here.....
