### ISSUE TITLE
Cloth simulation

### ISSUE THREAD

**Issue by Rama144** [mikedh/trimesh#696]
I need to know whether there is any cloth simulation method to make a mesh into a cloth .Could any one help me pointing out one. And I was not sure whether this is the right spot to ask questions. If not please direct me to the right place.

**Comment by mikedh** [comment]
Hey, you could implement cloth simulations using trimesh for loading/exporting/analyzing/viewing, but trimesh is more of a backend library than an application or simulator. [Blender](https://docs.blender.org/manual/en/latest/physics/cloth/index.html) has cloth simulation implemented that might be useful.

**Comment by Rama144** [comment]
Hey thanks for your response but  I need to implemet that using python libraries so I can explicitly render them in my trimesh/pyrender window . 
If I make a 3d garment into cloth simualtion in blender could it be used in the same way in pyrender window when I use it on different 3d models.

Any small help or reference for the below problem would be of great help.

I have a 3d garment model I need to place that on different 3d human models . It will be time consuming to make size adjustments for each and every size human models . Is there any way to acheive this .

I either need a way to feature match fit the 3d model

![p2-01](https://user-images.githubusercontent.com/50174542/72934409-8cc8b880-3d89-11ea-83b1-5f212c5ec8d7.jpg)

or Place the 3d garment as it is by merging both meshes .

![penetration](https://user-images.githubusercontent.com/50174542/72934440-9b16d480-3d89-11ea-8404-a8d4ef0bcd5b.jpg)

But I do get penetration of body mesh over cloth mesh .
Is there a way to make the human mesh as a collision target as non-penetrable
or move the cloth mesh point over the body model only in those penetrating places.

![hqdefault](https://user-images.githubusercontent.com/50174542/72934461-a8cc5a00-3d89-11ea-8e45-296dbf91e554.jpg)

Could you please help me with this any small help or reference would be of great use ...
