### ISSUE TITLE
Discrepency in finding Principal curvature

### ISSUE THREAD

**Issue by anupkhalam** [mikedh/trimesh#698]
Hi:
I am using the method mentioned in following link to find the principal curvature.

http://mathworld.wolfram.com/PrincipalCurvatures.html

I am using trimesh to find the Gaussian and mean curvature.

`g = trimesh.curvature.discrete_gaussian_curvature_measure(mesh_, [VPos_[1000]], 1)

m = trimesh.curvature.discrete_mean_curvature_measure(mesh_, [VPos_[1000]], 1)`

where VPos_ is the array of vertices.
However, I am getting following values.
g = array([2112.22130409])
m = array([7.74428421])

Based on the above values, there will not be any real values for the principal curvatures (as per the method described in the above link). I can send the mesh, if needed.
Any help would be appreciated.

Regards,
Anup.

**Comment by mikedh** [comment]
Hey, not sure what's going on there, but checking out the PR adding curvature might be helpful:

https://github.com/mikedh/trimesh/pull/175
