### ISSUE TITLE
Applying Transformations

### ISSUE THREAD

**Issue by roaasoloh** [mikedh/trimesh#699]
Hello!

Please I'm wondering about transformations, what are the implemented concepts? I saw this : 

`
mesh.apply_transform(trimesh.transformations.random_rotation_matrix())
`

But what other than rotation? How I know them like is there scaling, translation, adding noise!!
And as well after performing such action, how I may export the mesh to a new file?

Thank you!

**Comment by mikedh** [comment]
Hey, there are `mesh.apply_scale` and `mesh.apply_translation` methods in addition to homogeneous transformations with a matrix:
https://trimsh.org/trimesh.parent.html#trimesh.parent.Geometry

You can also chain the operations and then export if that's what you need:

```
ipython -i

In [1]: import trimesh

In [2]: trimesh.creation.box().apply_scale(2.25).apply_translation([20,0,1]).apply_transform(trimesh.transformations.random_rotation_matrix()).export('box.ply')


In [3]: m = trimesh.load('box.ply')

In [4]: m.bounds
Out[4]: 
array([[-12.01807022, -10.8816185 ,  13.09101963],
       [ -8.2169075 ,  -7.02244902,  16.47230339]])

```

**Comment by ClementRolinat** [comment]
Hello, it may be a trivial question, but does `apply_transform` behave nicely with shearing transform ? That is, matrix of the form:
```
[[1 s1 s2 0]
 [0  1 s3 0]
 [0  0  1 0]
 [0  0  0 1]]
```
Thank you!
