### ISSUE TITLE
How to show a Path3D and a Trimesh?

### ISSUE THREAD

**Issue by PaulDebus** [mikedh/trimesh#70]
Hey,

first of all thanks for the great module. It is a pleasure to use.

I am trying to show a Path3D and a Trimesh in the same scene. Both alone work well if a call `show()` on them. For this I use the following code:
```python
scene = path3d.scene()
scene.add_geometry(mesh)
scene.show()
```
which results in a `KeyError: 'geometry_1'` in Line 75 in viewer.py in the function _update_meshes

`(mesh + path3d).show()` does not work since Path3D does not subclass Trimesh.

Am I using this correctly or is there a better way?

Thank you for your time!

**Comment by mikedh** [comment]
Hmm... I'll take a look tonight, I've seen that error before too. Did you try:

`scene = trimesh.Scene([mesh, path3d])`

**Comment by PaulDebus** [comment]
No I had not tried this. But it works. Pretty good actually ;) Thank you.

I will use trimesh a little more over the next time for an university project. Is there any way I could contribute a little during that time?

Cheers

**Comment by mikedh** [comment]
Glad the ugly call works! I'm actually unable to reproduce with this example:
```
    import trimesh
    m = trimesh.primitives.Cylinder()
    p = m.section(plane_normal=[1,0,0],
                  plane_origin=m.centroid)

    s = p.scene()
    s.add_geometry(m)

    s.show()

```

Does that work for you? Would you mind posting a full traceback when you see the error?

As for contributions, they would be very welcome! If you find yourself implementing an algorithm that isn't project- specific that could be a good place to start. Also editing docs/unit tests/docstrings would definitely be appreciated.

**Comment by PaulDebus** [comment]
Ok, now I am a bit confused. Your code does work and after a (not related) reboot of my computer, also the originally not working code does work. So I am sorry for taking your time with this....

I will talk to my professor, if I can for example provide the jupyter notebook I am working with as an example. Else I would look into editing the docs. I was a bit lost when reading the [](url)
