### ISSUE TITLE
keeping color after smoothing

### ISSUE THREAD

**Issue by youssefmys** [mikedh/trimesh#702]
Hi there, 
I am trying to smooth a mesh object result from the summation of several `obj` files.
```
total_mesh = trimesh(vertices=[], faces=[])
for f in glob(os.path.join("/path/to/files", "*.obj")):
    sub_mesh = trimesh.load(f)
    total_mesh += sub_mesh
smooth_mesh = trimesh.smoothing.filter_laplacian(total_mesh, iterations=30, lamb=1)
smooth_mesh.show(viewer="gl", background=[0,0,0])
```
Meshes are overlapped, and mesh `obj` files are kept with `mtl` files with color information. Summation of meshes leads to color loss. Showing meshes with scene object can sucessfully keep colors. However,  the position of meshes is missy.
 
```
meshes = []
for f in glob(os.path.join("/path/to/files", "*.obj")):
    sub_mesh = trimesh.load(f)
    smooth_mesh = trimesh.smoothing.filter_laplacian(sub_mesh, iterations=30, lamb=1)
    meshes.append(smooth_mesh)
trimesh.Scene(meshes).show(viewer="gl", background=[0,0,0])
```
So how can I smooth meshes and keep their relative positions intact? Is that possible? 
Thanks

**Comment by mikedh** [comment]
Hey, that would probably take some work in `filter_laplacian` as that function currently doesn't look at visuals. `trimesh.util.concatenate` does look at visual information but may drop them if they don't align or different types are passed. Happy to take PR's!
