### ISSUE TITLE
Delete registered geometry from SceneViewer

### ISSUE THREAD

**Issue by iory** [mikedh/trimesh#704]
I'm visualizing objects by `SceneViewer`, this library.
The class has `add_geometry` and there is no `delete_geometry` function.
Is there are a way to delete objects from `Scene`?

**Comment by mikedh** [comment]
Hey, not currently. You'd have to pop the geometry (`scene.geometry.pop(geometry_key)`) and then clean up the graph (maybe something like `scene.graph.transforms.remove_node(node)`). 

Happy to take PR's!

**Comment by iory** [comment]
Thank you!

I created the PR related to this topic.

**Comment by mikedh** [comment]
Thanks for the PR! Merged and released.
