### ISSUE TITLE
Indexing Error in remesh.subdivide when using face_index

### ISSUE THREAD

**Issue by anttimc** [mikedh/trimesh#705]
faces are re-indexed in the beginning of the function
https://github.com/mikedh/trimesh/blob/82a2acda892e82e9c727ea8ba81c301bbfca5d70/trimesh/remesh.py#L50

which causes indexing error here
https://github.com/mikedh/trimesh/blob/82a2acda892e82e9c727ea8ba81c301bbfca5d70/trimesh/remesh.py#L81-L83

This is because new_faces are made of faces corresponding to face_index instead of the original faces

I think having reference to the original array would fix this, i.e., on L50
faces_old = faces
faces = faces[face_index]

and on the line linked on L81
new_faces = np.vstack((faces_old, f[len(face_index):]))

BTW. having face_index is a very useful feature especially for adaptive subdivision in visualization.

**Comment by ricshaw** [comment]
I have the same issue with subdivide

**Comment by mikedh** [comment]
Thanks for the report! Let me know if #706 doesn't fix it.
