### ISSUE TITLE
IndexError when loading an OBJ file with multiple 'f' formats

### ISSUE THREAD

**Issue by Emrys-Lee** [mikedh/trimesh#71]
Hi Mike,
There is a problem when loading an OBJ file.
Lines in an OBJ file starting with 'f' have many formats, such as
`f  1 2 3`
`f 1/1 2/2 3/3`
When loading a file with multiple formats, there is an IndexError:

> IndexError: too many indices for array

The problem lies in file trimesh/io/misc.py line 72:
`faces = np.array([i.split('/') for i in data[fid].reshape(-1)])[:, 0].reshape((-1, 3))`
Instead of generating a two dimension array,  `np.array()` returns a one dimension array, whose elements are lists.

Thank you.

Emrys-Lee

**Comment by mikedh** [comment]
Thanks for the report! Would you mind sharing an example file for tests? I'll look in to making that loader less brittle.

**Comment by Emrys-Lee** [comment]
You may try this one. 
[chair_model.zip](https://github.com/mikedh/trimesh/files/1199020/chair_model.zip)
And here is an [introduction](https://en.wikipedia.org/wiki/Wavefront_.obj_file) from wiki.

**Comment by mikedh** [comment]
Added chair to tests, and fixed in https://github.com/mikedh/trimesh/commit/c4c70766d962685fe9c9f925cd755f34b38f0ba8. 

In the future I would like to get rid of that list comprehension and replace it with faster native string or numpy array ops, as well as storing that additional face information.

**Comment by Emrys-Lee** [comment]
Thank you!
