### ISSUE TITLE
Exporting some kind of object name for wavefront

### ISSUE THREAD

**Issue by adrianroth10** [mikedh/trimesh#720]
From what I understand, the wavefront exporter does not export any kind of name as [wikipedia](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Referencing_materials) suggests you can do with 
```
o [object name]
```
This would come in handy for me when importing the file into different rendering software such as blender that use it. I was thinking that one could simply do something similar to the naming convention for add_geometry meshes that search for the `name` (and `file_name`) key in the `metadata` attribute of the mesh.

If you think it is of interest I can write a PR.

**Comment by mikedh** [comment]
Yeah that would be cool! How were you thinking of splitting up into `objects`? Something like a face label attribute? Or using scenes where different geometries are different objects?

**Comment by adrianroth10** [comment]
Sorry for the delay.
First I thought that since the wavefront exporter only accepts single meshes (from my understanding) I was thinking of just adding a few lines of code in the exporter to add a top line with a possible name. But I guess it can be expanded into using the concepts of group structures etc similar to a scene. So to answer your question it can be expanded to exporting a scene as a wavefront file. Though I have not used the group concept yet and I guess there are some challenges with this approach.

**Comment by adrianroth10** [comment]
I maybe have misunderstood the concept of groups in wavefront, not sure if you can use nesting as I was thinking. Maybe all meshes in a scene can be exported as a "flattened" scene.

**Comment by adrianroth10** [comment]
From how I understand blender does it when exporting multiple objects to a single wavefront file it applies all transforms to the children of the parent objects and exports them in the ´o [object name]` way. Not sure how materials come into play here but maybe they can be ignored for now.

**Comment by mikedh** [comment]
Thanks for the PR! Yeah I don't think OBJ has any concept of a hierarchy. You could have the exporter accept scenes, and then do the scene flattening (with `scene.dump`) and then make each of those meshes a separate object too.

**Comment by adrianroth10** [comment]
That's sounds like a good plan, I will try this though I am quite busy at the moment so do I not promise any date. 

Thanks for the nice welcome by the way, I think you are doing a really good job together will all other contributors to improve the repo!

**Comment by mikedh** [comment]
Thanks for the PR! In the `actions` branch I implemented a rough version of this for scenes too, which I can hopefully merge soon-ish.
