### ISSUE TITLE
Sample from visble surfaces.

### ISSUE THREAD

**Issue by zeal-github** [mikedh/trimesh#721]
Hi, I recently use this package to maintain pointcloud from a mesh.
However, my mesh is made up of several parts. I passed a example below:
![image](https://user-images.githubusercontent.com/40826585/74639092-3c862000-51a8-11ea-83fb-bd2acaeaaca4.png)
Each part of this chair is a dependent mesh. So if I sample by
```
mesh = trimesh.util.concatenate(mesh.dump())
pc = mesh.sample()
```
The pointcloud will contain points inside the chair, but I only want to sample from the visible surface.
Can you tell me how to do this, I think this package is powerful enough to achieve this.
Very very appreciative!

**Comment by mikedh** [comment]
Hey, I think you're looking for boolean unions before sampling:

```
In [1]: import trimesh

In [2]: a = trimesh.primitives.Sphere(center=[0,0,0])

In [3]: b = trimesh.primitives.Sphere(center=[1.5,0,0])

In [6]: scene = trimesh.Scene([a, b])

In [7]: unioned = trimesh.boolean.union(scene.dump())

In [8]: unioned
Out[8]: <trimesh.Trimesh(vertices.shape=(1174, 3), faces.shape=(2344, 3))>

In [9]: unioned.show()
Out[9]: SceneViewer(width=1800, height=1350)

In [10]: cloud = trimesh.PointCloud(unioned.sample(1000))

```

Note that trimesh uses blender or openSCAD as a backend for boolean operations, so you'll need one of those installed.

**Comment by zeal-github** [comment]
Thank you for your prompt reply! I will try it today.
Trimesh is a powerful and practical package for me, and it's easy to use. But I cannot find the detailed user documentation. I have to post an issue when I encounter a problem. I think a Api documentation will be really helpful.
Thanks for your work, it help me a lot!

**Comment by zeal-github** [comment]
@mikedh Sorry to bother you again. I think the boolean.union() method will return what I want. ( the outer surface of the two intersecting sphere). However, 'scene.show()' give me two intersecting spheres but `unioned.show()` only give me one sphere.
My backend is blender.

**Comment by mikedh** [comment]
Ah, unfortunately this may be related to Blender 2.8: #617
