### ISSUE TITLE
Applying a transformation to a particular Trimesh makes Trimesh.edges_face a NoneType

### ISSUE THREAD

**Issue by ngffy** [mikedh/trimesh#722]
I've been using this library to transform convex hulls created from point clouds. Everything works fine except for one particular point cloud. When I create a hull from it and then apply a transformation matrix, the mesh's `edges_face` member becomes `None`. This consequently breaks other things, such as displaying a `Scene` with this object.

Unfortunately, I only have one instance of this occurring, and its a large number of points (5292). I have it in a `.npy` file, but I don't know how I should share it online.

Here is some code that displays the issue.
```python
import numpy as np
import trimesh

node_locations = np.load('1610.npy')
hull = trimesh.PointCloud(node_locations).convex_hull

# Matrix that translates x coordinate by one
mat = np.eye(4)
mat[0][3] = 1

hull.apply_transform(mat)

# This raises an AssertionError
assert hull.edges_face is not None
```

**Comment by mikedh** [comment]
That's weird! Is the convex hull actually well constructed (has faces / vertices)? Hulls can fail on degenerate geometry, though failing *after* the hull operation would be kind of odd. Feel free to email me the file and I can take a look: mikedh@kerfed.com

**Comment by ngffy** [comment]
It looks like the hull has the same number of faces and vertices before and after the transformation, and it looks how I would expect it when I run `Trimesh.show()` (a thin rectangular prism).

**Comment by mikedh** [comment]
Got it, thanks! Looks like a caching issue: `apply_transform` tries to not dump topological stuff that won't change in a transform (i.e. edges, edges_face) and it looks like I missed some dependent keys. I'll think about a more general way to test for this type of issue, as they do lead to hard-to-debug errors like this one. But in the meantime I piggybacked a fix and test onto my current PR: https://github.com/mikedh/trimesh/pull/719/commits/9fe1c35f56db92ecc377bf7fd101f6254f739f7e 

Thanks for the report!
