### ISSUE TITLE
extrude_polygon extrude on the y-axis instead of the z-axis

### ISSUE THREAD

**Issue by hetsch** [mikedh/trimesh#723]
Hi,

first thank you for this very useful library! 

I'm currently running into a problem where I have to batch-extrude multiple 2D  `shapely` polygons into `glTF` meshes which are then imported into `Unity3d`. After importing to `Unity3d` the mesh looks smooth but the y- and z-axes are swapped. In `Unity3d` the vertical axis is the y-axis, whereas the `extrude_polygon` function extrudes the z-axis. Is there a way to modify the extrusion axis before exporting to `glTF` file?

Many thanks!

**Comment by mikedh** [comment]
Hey, you can probably just use `mesh.apply_transform`:
```
In [1]: import trimesh

In [2]: p = trimesh.path.polygons.random_polygon()

In [3]: p
Out[3]: <shapely.geometry.polygon.Polygon at 0x7fef2511ff28>

In [4]: trimesh.creation.extrude_polygon?
Signature: trimesh.creation.extrude_polygon(polygon, height, transform=None, triangle_args=None, **kwargs)
Docstring:
Extrude a 2D shapely polygon into a 3D mesh

Parameters
----------
polygon : shapely.geometry.Polygon
  2D geometry to extrude
height : float
  Distance to extrude polygon along Z
triangle_args : str or None
  Passed to triangle
**kwargs:
    passed to Trimesh

Returns
----------
mesh : trimesh.Trimesh
  Resulting extrusion as watertight body
File:      ~/trimesh/trimesh/creation.py
Type:      function

In [5]: m = trimesh.creation.extrude_polygon(p, height=5)

In [6]: m
Out[6]: <trimesh.Trimesh(vertices.shape=(16, 3), faces.shape=(28, 3))>

In [9]: T = trimesh.geometry.align_vectors([0,0,1], [0,1,0])

In [10]: T
Out[10]: 
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [11]: m.apply_transform(T)
Out[11]: <trimesh.Trimesh(vertices.shape=(16, 3), faces.shape=(28, 3))>

In [12]: m.show()
```
Here is the result of that in the viewer (green indicates the Y-axis):
![axis](https://user-images.githubusercontent.com/1403074/74758555-807b3280-5245-11ea-9ccb-9d20d721d7e4.png)

**Comment by hetsch** [comment]
@mikedh Thank you so much! This works perfectly and saved me a lot of time!
