### ISSUE TITLE
Speed up voxelization

### ISSUE THREAD

**Issue by claell** [mikedh/trimesh#727]
I did a short test for the voxelization and it seems to be rather slow when it comes to larger grid sizes like 128. Are there any plans to improve the performance for that operation?

**Comment by mikedh** [comment]
Yeah voxels are quite slow in general. There are multiple construction methods, by far the fastest (although not particularly robust) is `method=ray` which uses pyembree for queries. I don't use voxels very often so optimizations from me are pretty unlikely, but happy to take PR's!

```
In [6]: m = trimesh.creation.icosphere()

In [7]: m.voxelized?
Signature: m.voxelized(pitch, method='subdivide', **kwargs)
Docstring:
Return a VoxelGrid object representing the current mesh
discretized into voxels at the specified pitch

Parameters
------------
pitch : float
  The edge length of a single voxel
method: implementation key. See `trimesh.voxel.creation.voxelizers`
**kwargs: additional kwargs passed to the specified implementation.

Returns
----------
voxelized : VoxelGrid object
  Representing the current mesh
File:      /media/psf/Dropbox/robotics/trimesh/trimesh/base.py
Type:      method

In [8]: %timeit m.voxelized(method='ray', pitch=2/128)
154 ms ± 11.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]: %timeit m.voxelized(method='subdivide', pitch=2/128)
2.41 s ± 198 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [10]: %timeit m.voxelized(method='binvox', pitch=2/128)
1.42 s ± 51.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by claell** [comment]
Unfortuntely ray did not work on my test machine because a required package could not be installed. But as you stated, it is also not that robust?

For now I will use binvox standalone without trimesh, since it seems to be the best method currently for what I want to achieve.
