### ISSUE TITLE
Exception when export obj with include_texture=True

### ISSUE THREAD

**Issue by stanleytangerror** [mikedh/trimesh#729]
[Here](https://github.com/mikedh/trimesh/blob/dca5750c61c59ab537232188263e3a247c124342/trimesh/exchange/obj.py#L806) in function `export_obj` return a tuple rather than a str when `include_texture=True`, causing [here](https://github.com/mikedh/trimesh/blob/dca5750c61c59ab537232188263e3a247c124342/trimesh/util.py#L1953) in function `write_encoded` throw an exception: **TypeError: write() argument must be str, not tuple**

**Comment by mikedh** [comment]
Gotcha, how are you calling `export_obj`? Unfortunatly OBJ for textured meshes returns multiple files, so I haven't figured out a great way of handling it from some calls. I might add a `FilePathResolver.write` function so if you pass a file path to `export_obj` it does the right thing, but that isn't currently implemented. 

If it's helpful, the way we call exporting OBJ files with texture in unit tests is:
```
	m = g.get_mesh('fuze.obj')
        # export the mesh including data                             
        obj, data = g.trimesh.exchange.export.export_obj(
            m, include_texture=True)
	with g.trimesh.util.TemporaryDirectory() as path:
            # where is the OBJ file going to be saved                
            obj_path = g.os.path.join(path, 'test.obj')
            with open(obj_path, 'w') as f:
                f.write(obj)
            # save the MTL and images                                
            for k, v in data.items():
                with open(g.os.path.join(path, k), 'wb') as f:
                    f.write(v)
            # reload the mesh from the export                        
            rec = g.trimesh.load(obj_path)

```

**Comment by stanleytangerror** [comment]
This sample is helpful, I will use this way to export obj files.

I used to export obj directly in this way, and expecting the mesh with generate mtl and images to the target directory. The `file_type='obj'` argument sounds reasonable and delegate to `export_obj` successfully.
```
filename = r'dump/geometry_196.obj'
with open(filename, 'w', encoding='utf-8') as f:
    mesh.export(f, file_type='obj', include_texture=True)
```
