### ISSUE TITLE
Signed Distance produces zero result on certain edge cases.

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#73]
REPRODUCEABLE CODE
```
#cuboid is a trimesh object representing a cube, with correct normals, and bounds as follows
print(cuboid.bounds) # >>> [[0,0,0],[2,2,2]]
points = np.array([[3,2,2]]) #should be 1 mm away
ret = trimesh.proximity.signed_distance(cuboid, points)
assert np.allclose(ret, [-1])  # should be true, but is false. ret ends up being [0]
```

REASON FOR FAILURE:
in trimesh.proximity.signed_distance, the "closest" triangle to the point is found, and its normal is used to get the sign. If this closest triangle is actually in the same plane as the point, then the found sign is 0. This is okay if the point is "on" the triangle, but consider the case wherein a cuboid is sitting on a table, and the point is a point somewhere on the flat surface of the table, but not under the cuboid. The current closest face / point algorithm could choose one of the triangles defining the part of the cuboid that is sitting face down on the table. In this case, even though the distance from the point is not zero, the signed distance will be returned as zero.

I'm not sure I stated this clearly, but the above test case, if run, will make sense of it.

**Comment by Marviel** [comment]
I think the solution here is to make a closest_point function that only returns faces that are not coplanar to the point, if the point is not "on" the triangle

**Comment by mikedh** [comment]
Good catch! I made zero magnitude projections fall back to a ray containment test as I wanted to always return a signed distance. It handles both the coplanar nearest face inside and outside.There's probably a way to do it without ray tests but I couldn't think of any. Fix and test are in https://github.com/mikedh/trimesh/commit/c89ddd64371a205a3ee99a3f1664cc8904796e17

**Comment by Marviel** [comment]
LGTM
