### ISSUE TITLE
trimesh.intersections .slice_mesh_plane returns non watertight mesh

### ISSUE THREAD

**Issue by amitoved** [mikedh/trimesh#731]
hello, 
under the  **slice_mesh_plane** documentation, exists a **cap** parameter which is supposed to seal the opening created by the mesh slicing but this parameter isn't used by the function or by **slice_faces_plane** which accepts **kwargs by  **slice_mesh_plane**.  
Has this capability been removed?
Is there another function which does that separately?
Thank you.

**Comment by mikedh** [comment]
Hey, looks like I added the kwarg but never implemented it. Happy to take PR's to fill it in, or I can remove the errant kwarg on next release.

Thanks for the report!

**Comment by mjd3** [comment]
@mikedh I think we got pretty close to this in #235, maybe that code was just never pushed? If there's still some work to be done, I might have time to submit a PR for this as well.

**Comment by mikedh** [comment]
Ah yeah, looks like `cap` was implemented in the comments but never merged hahah. If you have cycles a PR would be awesome thanks!

**Comment by mjd3** [comment]
@amitoved This should be addressed by #800 which got merged in about a week ago!

**Comment by donno** [comment]
Using 3.8.18, I am experiencing `slice_mesh_plane()` failing to return a watertight mesh.

I was alerted to the problem as I was cutting by two planes. The capping algorithm checks after the first cap is made from the first slice that the resulting mesh is watertight before it attempts to apply the cap on the new side and that check failed.
