### ISSUE TITLE
Sending ray from the center of triangle/planes of my mesh

### ISSUE THREAD

**Issue by osvaldo14** [mikedh/trimesh#732]
Here is my situation : I have a mesh (ply file) of an human body and I want to send rays from the center of each triangle of the mesh with all the same direction and store every triangle_id that doesn't hit anything. I saw the ray_pyembree doc, but I still miss how to use the classe's function. And how can I get the center of each triangle of my mesh..

 Have anyone use it or have a link of a simple exemple that I can try ?

Thanks a lot !

**Comment by osvaldo14** [comment]
I was thinking about doing it that way :

loop on ply file where i = triangle coordinates : 

- c = find_center(i)

- hit = intersects_first(c,dir)

- if !hit then add i_index to an array

Do you think this can be a way of solving my situation ?

**Comment by mikedh** [comment]
I'd probably do that with `mesh.triangles_center` and `mesh.ray.intersects_any`. You really want to avoid loops:

```
In [12]: m = trimesh.load('models/bunny.ply')
DEBUG              load.py:230   loaded <trimesh.Trimesh(vertices.shape=(8146, 3), faces.shape=(16301, 3))> using load_ply
DEBUG         constants.py:137   load_mesh executed in 0.1059 seconds.

In [13]: m
Out[13]: <trimesh.Trimesh(vertices.shape=(8146, 3), faces.shape=(16301, 3))>

In [14]: normals = m.face_normals

In [16]: origins = m.triangles_center + normals * 1e-3

In [17]: hitany = m.ray.intersects_any(ray_origins=origins, ray_directions=normals)

In [18]: hitany
Out[18]: array([False,  True, False, ..., False, False, False])

In [20]: face_nohit = np.nonzero(~hitany)[0]

In [21]: face_nohit
Out[21]: array([    0,     2,     3, ..., 16298, 16299, 16300])

In [22]: face_nohit.shape
Out[22]: (15783,)

In [23]: m.faces.shape
Out[23]: (16301, 3)

```

**Comment by mm-89** [comment]
@mikedh 
A question: are you sure that your normal vectors are orientated in the right direction? You multiply for 1e-3 to avoid that triangles are hit themselves (right?) but maybe this distance is the opposite one. Would it be enough maybe to use "fix_normals"?

**Comment by ttsesm** [comment]
@mm-89 yes multiplying by `1e-3` you avoid hitting the origin triangle. Of course you need to be sure that your `normals` are correct otherwise as you say your rays will go on the opposite direction I am not sure whether `fix_normals` could help though.

Also in case that your `normals` are not provided as unit vectors you could just get and use the `numpy.sign()` output instead, this is what I am using:

```
# get the centroid of the face/patch and shift them with a small offset so that rays do not stop at the self face thrown from
mesh = mesh = trimesh.Trimesh(...) # load/create your mesh
start_points = mesh.triangles_center  # the face/patch center points
offset = numpy.sign(mesh.face_normals)
offset = offset * 1e-5
origins = start_points + offset
```

**Comment by mikedh** [comment]
Hey, `mesh.face_normals` are automatically computed and validated and should always be unit vectors. `np.sign(mesh.face_normals)` is going to create a mildly odd result (i.e magnitude ranging from `sqrt(3)` to `1`).
