### ISSUE TITLE
Problem centroid calculation

### ISSUE THREAD

**Issue by pepperonimax** [mikedh/trimesh#733]
I have noticed irregularities in the calculation of the centroid of a mesh. For testing purposes, I calculated the centroid outside the centroid function and surprisingly got different results.

`res = np.mean(mesh_proj.bounds, axis=0)
print('res mean: ', res)
print('centroid mesh python: ', mesh_proj.centroid)`

![image](https://user-images.githubusercontent.com/55702390/75988520-04921300-5ef2-11ea-8775-1c620d8d37a9.png)

![image](https://user-images.githubusercontent.com/55702390/75988623-29868600-5ef2-11ea-8957-63da763d29b4.png)

I guess that I use the centroid function in the wrong way. Does anybody have an idea?

Thank you very much!

**Comment by mikedh** [comment]
Hey, is that a `Trimesh` or a `Path`? Meshes have centroids which are:
```
In [10]: m.centroid?
Type:        property
String form: <property object at 0x7f6e688ce950>
Docstring:  
The point in space which is the average of the triangle
centroids weighted by the area of each triangle.

This will be valid even for non-watertight meshes,
unlike self.center_mass

Returns
----------
centroid : (3, ) float
  The average vertex weighted by face area
```

Though keep in mind for watertight meshes the `center_mass` is much more accurate:
```
In [11]: m.center_mass?
Type:        property
String form: <property object at 0x7f6e688cea10>
Docstring:  
The point in space which is the center of mass/volume.

If the current mesh is not watertight this is meaningless
garbage unless it was explicitly set.

Returns
-----------
center_mass : (3, ) float
   Volumetric center of mass of the mesh

```

**Comment by pepperonimax** [comment]
Hej,
mesh_proj is a Trimesh. Do you have a guess if I use it the wrong way or what the problem is?

**Comment by mikedh** [comment]
Yeah for meshes the centroid is the area-weighted mean of vertices, not the center of `mesh.bounds`, so it makes sense that they are different.

**Comment by pepperonimax** [comment]
Of course. Thank you.
