### ISSUE TITLE
Document not correctly build

### ISSUE THREAD

**Issue by bertrandhaut** [mikedh/trimesh#737]
At time of writing, the documention seems incorrectly built. Many page contents are missing.

For example, nothing is listed in  https://trimsh.org/trimesh.base.html
![Capture](https://user-images.githubusercontent.com/6848040/76405653-bf099600-6388-11ea-8c50-60cd386f3a39.PNG)

**Comment by mikedh** [comment]
Thanks for the report! I just switched the docs build to github actions and probably goofed something, I'll investigate.

**Comment by mikedh** [comment]
These should be building correctly now, and look OK to me on [the website](https://trimsh.org). Closing for now, if you see it again please re-open. Thanks for the report!

**Comment by bertrandhaut** [comment]
Indeed, it worked.

By the way, thanks for the library.
