### ISSUE TITLE
OBJ file loading support

### ISSUE THREAD

**Issue by oortlieb** [mikedh/trimesh#74]
I'm using `trimesh.load_mesh` to load in files of different types and export them to stl. Right now we're only interested in converting .OBJ files.

It seems that OBJ files are not correctly loaded in all cases. It looks to me like the OBJ loader may not be correctly loading OBJ files that contain faces with more than 3 vertices (I haven't been able to verify this in the trimesh source code). I've attached a file that reflects this issue -- loading it with `trimesh.load_mesh` and then exporting it as an STL gives the following results. The viewer I'm using is Makerbot Desktop.

The OBJ:
![image](https://user-images.githubusercontent.com/3278489/29681973-6c0bfe36-88d7-11e7-88bc-61821f0aee15.png)

![image](https://user-images.githubusercontent.com/3278489/29681920-48ee7104-88d7-11e7-99c6-b4522484ea13.png)

Converting the file to STL before loading it into trimesh fixes the issue, but that's the functionality we're hoping to get from trimesh.

**Comment by oortlieb** [comment]
I ran the mesh through `assimp info` and got some new clues:

Memory consumption: 2376704 B
Nodes:              95
Maximum depth       2
Meshes:             94
Animations:         0
Textures (embed.):  0
Materials:          1
Cameras:            0
Lights:             0
Vertices:           19932
Faces:              33942
Bones:              0
Animation Channels: 0
Primitive Types:    triangles
Average faces/mesh  361
Average verts/mesh  212
Minimum point      (-87.639748 -0.144633 -16.867111)
Maximum point      (87.640060 185.275253 21.341709)
Center point       (0.000156 92.565308 2.237299)

Named Materials:
    'DefaultMaterial'

Node hierarchy:
'MALE3D low.OBJ', meshes: 0
-- 'Group19193', meshes: 1
-- 'Group19208', meshes: 1
-- 'Group19253', meshes: 1
-- 'Group19268', meshes: 1
-- 'Group19283', meshes: 1
-- 'Group19298', meshes: 1
-- 'Group19313', meshes: 1
-- 'Group19253', meshes: 1
-- 'Group19358', meshes: 1
-- 'Group19373', meshes: 1
-- 'Group19253', meshes: 1
-- 'Group19958', meshes: 1
-- 'Group19973', meshes: 1
-- 'Group19988', meshes: 1
-- 'Group20003', meshes: 1
-- 'Group20018', meshes: 1
-- 'Group19958', meshes: 1
-- 'Group19973', meshes: 1
-- 'Group19988', meshes: 1
-- 'Group20003', meshes: 1
-- 'Group20018', meshes: 1
-- 'Group20033', meshes: 1
-- 'Group20048', meshes: 1
-- 'Group20063', meshes: 1
-- 'Group20078', meshes: 1
-- 'Group20093', meshes: 1
-- 'Group20033', meshes: 1
-- 'Group20048', meshes: 1
-- 'Group20063', meshes: 1
-- 'Group20078', meshes: 1
-- 'Group20093', meshes: 1
-- 'Group20108', meshes: 1
-- 'Group20123', meshes: 1
-- 'Group20138', meshes: 1
-- 'Group20153', meshes: 1
-- 'Group20108', meshes: 1
-- 'Group20138', meshes: 1
-- 'Group20123', meshes: 1
-- 'Group20168', meshes: 1
-- 'Group20183', meshes: 1
-- 'Group20198', meshes: 1
-- 'Group20213', meshes: 1
-- 'Group20228', meshes: 1
-- 'Group20183', meshes: 1
-- 'Group20213', meshes: 1
-- 'Group20198', meshes: 1
-- 'Group20243', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20273', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20288', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20303', meshes: 1
-- 'Group20318', meshes: 1
-- 'Group20303', meshes: 1
-- 'Group20318', meshes: 1
-- 'Group20258', meshes: 1
-- 'Group20303', meshes: 1
-- 'Group20318', meshes: 1
-- 'Group19193', meshes: 1
-- 'Group19208', meshes: 1
-- 'Group20468', meshes: 1
<--

assimp is able to correctly convert the file, even though it has a number of groups defined.

**Comment by mikedh** [comment]
Thanks for the report! The OBJ loader probably only supports triangular faces at the moment- if you send me a copy of the mesh I can look in to supporting quad faces tonight.

**Comment by mikedh** [comment]
I added support for quad faces in https://github.com/mikedh/trimesh/commit/c56fe2e2a06e66765cca70535d5cb8fb33782127 - feel free to reopen if your file is still having trouble.

**Comment by HakuG** [comment]
I'm still having this issue. Importing a .obj file and exporting the .stl file creates an incomplete stl file? It still renders fine, but once I slice the outputted stl file, I get something completely different.

**Comment by HakuG** [comment]
Here's the STL file rendered on three.js
![image](https://user-images.githubusercontent.com/5514073/49831519-11ad6a00-fd62-11e8-844c-1c5c439527ba.png)
Here's the Gcode that's outputted from this. 
![image](https://user-images.githubusercontent.com/5514073/49831558-2689fd80-fd62-11e8-97d3-71e72486ea3f.png)
