### ISSUE TITLE
feature request improve error behavior in proximity closest_point RTreeError

### ISSUE THREAD

**Issue by AndrewAnnex** [mikedh/trimesh#741]
I am occasionally running into an issue with proximity.closest_point where I get a RTree error after calling closest_point with the error message "Coordinates must not have minimums more than maximums" related to the call to nearby_faces. I am not sure why I get this error yet but it would be nice if there was a nicer way for closest point to not yield failing points or to do some sanity checks for the user to provide a clear cause from the input mesh and point data

**Comment by mikedh** [comment]
Gotcha haven’t seen that one! Do you have a reproducible example I could
use to test?

Thanks for the report!
Mike

**Comment by AndrewAnnex** [comment]
I haven't quite narrowed it down yet but will try to get something to you in a few days

**Comment by mikedh** [comment]
Oh reading this again I suspect this is for zero-sized degenerate triangles. I haven't seen this personally but if you can isolate and test a PR would be great!
