### ISSUE TITLE
ValueError: File type: 3mf not supported

### ISSUE THREAD

**Issue by ChrisCarragher** [mikedh/trimesh#742]
Hi,

Maybe I am making a silly mistake but when I try to load .3mf files I get an error saying the file type isn't supported.

```
import trimesh
mesh = trimesh.load('holder.3mf')
```

I am using trimesh==3.6.4 and Python 3.7.7

Thanks for your help.

**Comment by mikedh** [comment]
So 3MF requires lxml which isn’t part of the minimal install, does
installing that help? ‘pip install lxml’

**Comment by ChrisCarragher** [comment]
Hi Mikedh,

Yes, that worked thank you very much.
