### ISSUE TITLE
trimesh.proximity.signed_distance produces incorrect positive result

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#75]
# TRIMESH VERSION: 2.14.13
# STL FILE
https://drive.google.com/open?id=0B18jNduc8kjlSERxX0U1bEdNSkU
# REPRODUCIBLE STEPS
<img width="567" alt="screen shot 2017-08-27 at 2 11 59 pm" src="https://user-images.githubusercontent.com/2037165/29752759-c72d554c-8b31-11e7-8ee3-50d6b0e717cb.png">
another point that causes same result: [-51,4.7,-20.6]

**Comment by Marviel** [comment]
easier to debug result with same effect [[-51,4.7,-20.6]]

**Comment by Marviel** [comment]
this case seems to have been fixed by: https://github.com/mikedh/trimesh/commit/55605ed4f8cf5f0c1aea785bd2a2edeac99eb7cd

**Comment by mikedh** [comment]
Good to hear its fixed, thanks for the report. I added your example to tests in https://github.com/mikedh/trimesh/commit/c56fe2e2a06e66765cca70535d5cb8fb33782127 and just made all distance signs derived from ray tests- they seem much more reliable than checking the normal.
