### ISSUE TITLE
Missing uv data after load

### ISSUE THREAD

**Issue by lvjiahui** [mikedh/trimesh#752]
Hi,
Thanks for your Libary!

I have a .obj file with **vt** data.
After loading, I can'f find UV data anywhere.
By the way, I don't have texture image (maybe that is the reason?), but I just need UV only.
Could you tell me how to get UV data simply?

**Comment by tomasdrinovsky** [comment]
Same problem here. If I'am loading mesh with texture coordinates and without texture the trimesh.visuals.uv is None. Do you offer some solution? Perhaps some flag when loading? 

Thanks in advance
