### ISSUE TITLE
Saving many rendered scenes as images freezes the application!

### ISSUE THREAD

**Issue by pridi** [mikedh/trimesh#754]
Hello, 

I need to save many images of many STL models in different angles (12 images at different orientation for 2500 3D models). I started to write my code from the tutorial "offscreen_render.py".
When I reach about 1000 saved images I start to see a slowing down of the application. After some time the process is so slow that I cannot continue.
I've tried to comment out the writing of the file but the problems persists; only if I remove the function "save.save_image(...)" the process continues smoothly. 
It seems to me that the showing of the screen is appending something in memory that cannot be emptied. 

Could please help?

**Comment by mikedh** [comment]
Hey, yeah this is a Python issue with long-running jobs that isn't specific to trimesh. Check out https://github.com/mikedh/trimesh/issues/171 for some discussion.

The short answer is, for long-running tasks either run the function in a subprocess or monitor/restart the main loop with something like `supervisord`.

**Comment by pridi** [comment]
thanks!
