### ISSUE TITLE
Unfolding 3D CAD model

### ISSUE THREAD

**Issue by ors101** [mikedh/trimesh#755]
Does anyone has an idea if there is a handy trimesh function to unfold a 3D CAD model? I would like to import the 3D CAD as .stl and export it as a 2D CMYK .tiff with the same dimensions as the original image. Thank you in advance for your help :)

**Comment by mikedh** [comment]
Hey, there aren't currently any methods already implemented in trimesh to do this. There are a lot of ways to define "unfold," this type of operation is usually called [mesh parameterization](https://www.cs.ubc.ca/~sheffa/papers/CGV011-journal.pdf). Happy to take PR's if you implement any of those methods though!
