### ISSUE TITLE
pixel out of range in [scene.camera_rays()]

### ISSUE THREAD

**Issue by lvjiahui** [mikedh/trimesh#758]
```
scene.camera.resolution = [512, 512]
origins, vectors, pixels = scene.camera_rays()
print(pixels[:3])
```
**output**
```
[[  0 512]
 [  0 510]
 [  0 509]]
```

the **512** should be **511**

I think that's because in `cameras.ray_pixel_coords` method:

```
    pixels = util.grid_linspace(
        bounds=[[0, res[1]], [res[0], 0]],
        count=res).astype(np.int64)
```
should change to
`bounds=[[0, res[1]-1], [res[0]-1, 0]]`

But I am not sure it's consistent with other code somewhere I don't know

**Comment by mikedh** [comment]
Thanks for the report! Fix and test added in #793
