### ISSUE TITLE
"sort array is read-only" when traversing edges

### ISSUE THREAD

**Issue by pmayostendorp** [mikedh/trimesh#759]
I am attempting to generate a directed graph of vertices for facets in a mesh. This has worked well for thousands of models (imported from Collada), but I'm starting to encounter issues in a new batch of models. The basic procedure looks something like this.

```python
mesh = trimesh.load(file_obj=collada_file, file_type='dae')
mesh_list = mesh.dump()
mesh = trimesh.util.concatenate(mesh_list)

for i, facet in enumerate(mesh.facets):
    edge_ids = mesh.facets_boundary[i]

    # add vertices as a directed graph so we get vertex ordering
    vertex_graph = trimesh.graph.traversals(edge_ids, 'dfs')[0]
    wall_vertices = np.round(mesh.vertices[vertex_graph], 4) # cm precision
```

The code often fails with the call to `trimesh.graph.traversals` and produces something like the following:

```
", line 274, in write_geometry_to_xml
    vertex_graph = trimesh.graph.traversals(edge_ids, 'dfs')[0]
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/graph.py", line 695, in traversals
    edges.sort(axis=1)
ValueError: sort array is read-only
```

I've attached a couple Collada files
[troubleshoot.zip](https://github.com/mikedh/trimesh/files/4394699/troubleshoot.zip)
 for reproducing this error. I have tried with my current version of trimesh (3.5.20) as well as the latest release with the same results. I'm having trouble determining if the issue resides in my models at this point or trimesh. Seems like it could be related to [this issue](https://github.com/mikedh/trimesh/issues/371) but that PR didn't seem to address this exactly. Thanks!

**Comment by pmayostendorp** [comment]
Since the underlying error seems to be thrown by `numpy.sort`, just confirming that my current numpy is 1.18.1.

**Comment by mikedh** [comment]
Ah yeah `trimesh.graph.traversals` is using `np.asanyarray` which won't copy numpy array inputs. However that function is also mutating the input (that `edges.sort` call), and the autogenerated `mesh.edges` values are immutable. Since that seems wrong I switched `np.asanyarray` to `np.array` (which will copy immutable numpy arrays to a new mutable array) in #760, let me know if that fixes it.

Thanks for the report!

**Comment by pmayostendorp** [comment]
I think that latest PR did it. The switch to `np.array` did the trick. 👍

**Comment by pmayostendorp** [comment]
THANK YOU!
