### ISSUE TITLE
How to obtain mesh geometry and scale in scene

### ISSUE THREAD

**Issue by you214** [mikedh/trimesh#764]
Hi, I'm beginner in Python. I want to control a mesh movement or scale every time scene updated.
I supposed I have to obtain geometry of a mesh and control it.
Could you teach me how can I do it?

**Comment by mikedh** [comment]
Probably the easiest way to start is by running through some of the examples and see if you can get similar logic running in your environment, and then go from there: https://trimsh.org/examples/quick_start.html
