### ISSUE TITLE
extracting vertices and faces from loaded stl

### ISSUE THREAD

**Issue by steersteer** [mikedh/trimesh#765]
Hi, 
I'm trying to extract the vertices and faces of a loaded stl so that I can feed it into a Tetgen interface. 
How can I do this?

I've loaded my stl using:
`stl_mesh = trimesh.load(file_obj='Output\\Meshes\\{}_surface_mesh.stl'.format(name), file_type='stl')`

**Comment by mikedh** [comment]
You should be able to access both properties directly from the mesh object:

```
# an (n, 3) float numpy array
stl_mesh.vertices
# an (n ,3) int numpy array
stl_mesh.faces
````

**Comment by steersteer** [comment]
Thanks!
