### ISSUE TITLE
Making default rotation of a mesh to zero.

### ISSUE THREAD

**Issue by mjm522** [mikedh/trimesh#767]
I have been really impressed by this library. It is immensely useful for me in my project. At present I want to do the following.

I have a mesh which on running 
```bash
mesh.bounding_box_oriented.primitive.transform
``` 
produces
```
array([[ 0.33, -0.94, -0.  ,  0.  ],
       [-0.94, -0.33, -0.  , -0.  ],
       [ 0.  ,  0.  , -1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])
```
I want to make this transformation
```
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
```
is this possible?. I tried applying the inverse transformation using `mesh.apply_transform` and tried to register this mesh another mesh of this orientation. None of them produced the right result. I want to make this the default transformation and save it as a new mesh file.

It would be really helpful if you could suggest a way to do this. Thanks a lot for your time.

**Comment by mikedh** [comment]
Yeah, it's tough to get something fully reversible. The OBB transform probably has ambiguity for which of the 6 faces of the bounding box it picks. Also, meshes with axial (i.e. a cylinder) or point (i.e. a sphere) symmetry will have arbitrary oriented bounding boxes so will probably never be reversible. 

Some quick checks look like it is doing something somewhat reasonable here, although it is consistently picking a flipped result:

```
In [1]: m = trimesh.creation.cylinder(radius=1.0, height=5.0).permutate.transform()

In [2]: m.bounding_box_oriented.primitive.transform

Out[2]: 
TrackedArray([[ -0.62557,  -0.59791,  -0.50117, 307.40154],
              [  0.67566,  -0.73637,   0.03513,  94.91224],
              [ -0.39005,  -0.31664,   0.86464, 493.51233],
              [  0.     ,   0.     ,   0.     ,   1.     ]])

In [3]: m.apply_transform(np.linalg.inv(m.bounding_box_oriented.primitive.transform))

In [4]: m.bounding_box_oriented.primitive.transform

Out[4]: 
TrackedArray([[-1.,  0.,  0., -0.],
              [ 0.,  1., -0.,  0.],
              [-0., -0., -1.,  0.],
              [ 0.,  0.,  0.,  1.]])

In [5]: m = trimesh.creation.box(extents=[1,2,3]).permutate.transform()

In [6]: m.bounding_box_oriented.primitive.transform

Out[6]: 
TrackedArray([[  -0.64   ,    0.76604,    0.0598 ,  222.302  ],
              [   0.23502,    0.26926,   -0.93395,  -58.44453],
              [  -0.73155,   -0.58368,   -0.35236, -335.2014 ],
              [   0.     ,    0.     ,    0.     ,    1.     ]])

In [7]: m.apply_transform(np.linalg.inv(m.bounding_box_oriented.primitive.transform))

Out[7]: <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>

In [8]: m.bounding_box_oriented.primitive.transform

Out[8]: 
TrackedArray([[-1.,  0.,  0., -0.],
              [ 0.,  1.,  0.,  0.],
              [-0.,  0., -1.,  0.],
              [ 0.,  0.,  0.,  1.]])
```

Happy to take PR's to make this less ambiguous!
