### ISSUE TITLE
ModuleNotFoundError: No module named 'triangle'

### ISSUE THREAD

**Issue by theo258** [mikedh/trimesh#770]
Hello,
today I installed trimesh on a Windows x64 using:
```conda install -c conda-forge trimesh```
With:
```trimesh.__version__```
I get: 3.6.20.

I wanted to extrude a shapely polygon using the following:
```import trimesh```
```my_mesh = trimesh.creation.extrude_polygon(my_poly, 12, transform=None, triangle_args=None)```
This results in the following error:
```ModuleNotFoundError: No module named 'triangle'```

I thought that with using conda all dependencies would be installed.

The exact location where the error is occuring is:
```
  File "C:\Anaconda3\envs\my_env\lib\site-packages\trimesh\creation.py", line 187, in extrude_polygon
    polygon, triangle_args=triangle_args, **kwargs)

  File "C:\Anaconda3\envs\my_env\lib\site-packages\trimesh\creation.py", line 435, in triangulate_polygon
    from triangle import triangulate
```

**Comment by mikedh** [comment]
Yeah, that's a great point. The `trimesh-feedstock` `requirements_constrained` were out of sync with the actual requirements in `trimesh/setup.py`. I just added a script to sync the requirements, which should hopefully be up to date now.

Thanks for the report!

**Comment by feromes** [comment]
Hello for all,

Same issue persists here:

```
import trimesh
p = trimesh.path.polygons.random_polygon()
trimesh.creation.extrude_polygon(p, 50)
```

Results in ..

```---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-41-bc92864e8bb6> in <module>
      1 p = trimesh.path.polygons.random_polygon()
----> 2 trimesh.creation.extrude_polygon(p, 50)

~/miniconda3/envs/pcp-env/lib/python3.7/site-packages/trimesh/creation.py in extrude_polygon(polygon, height, transform, triangle_args, **kwargs)
    187     # create a triangulation from the polygon
    188     vertices, faces = triangulate_polygon(
--> 189         polygon, triangle_args=triangle_args, **kwargs)
    190     # extrude that triangulation along Z
    191     mesh = extrude_triangulation(vertices=vertices,

~/miniconda3/envs/pcp-env/lib/python3.7/site-packages/trimesh/creation.py in triangulate_polygon(polygon, triangle_args, engine, **kwargs)
    455 
    456     # do the import here for soft requirement
--> 457     from triangle import triangulate
    458     # set default triangulation arguments if not specified
    459     if triangle_args is None:

ModuleNotFoundError: No module named 'triangle'
```

I am gonna try manual installation and tell here later

Thanks,

**Comment by mikedh** [comment]
Hey, looks like you’re missing the soft dependency triangle, try running:
pip install triangle

**Comment by feromes** [comment]
Done!!!

Actually I've created a new conda environment and then:

```
conda install -c conda-forge scikit-image shapely rtree pyembree
pip install trimesh[all]
```

and now ... 

![image](https://user-images.githubusercontent.com/31536/88399755-bea0f300-cd9d-11ea-8873-13ece365ca5e.png)

Uhuuuu!!!!!!

Thanks a lot @mikedh

**Comment by brunohs1993** [comment]
Hey, first of all awesome library!

I've had a problem like this when trying to cut the mesh using planes. I have a conda environment with trimesh and triangle installed, but apparently the triangle library wasn't being found by trimesh _unless_ I installed triangle with pip on the main python in my machine, _outside_ the environment. Basically:

- `conda install triangle` didn't work (installed, but couldn't be found);
- `conda run -m python pip install triangle` didn't work (also installed, but couldn't be found);
- `pip install triangle` worked just fine.

Should it be like this? I'm running it on Windows 11, by the way.

Cheers!

**Comment by Nosenzor** [comment]
Unfortunately earcut is not as robust as triangle. I'm facing the same issue with all my attempt to setup triangle :-(

**Comment by mikedh** [comment]
Hey, triangle should install cleanly with `pip install triangle`? The have a full matrix of wheels available: https://pypi.org/project/triangle/20220202/#files

Yeah earcut isn't as robust or generating quality meshes for sure.
