### ISSUE TITLE
Exporting meshes does not save any changes made in the mesh

### ISSUE THREAD

**Issue by Sushanth-Kathirvelu** [mikedh/trimesh#771]
Hi, 

I am trying to color some faces and export my mesh to save it as a new mesh, but the exported mesh does not have the color.

My code:
mesh = trimesh.load('H1_mesh.off') 
mesh2 = mesh.copy()
for facet in range(410000,550700):
    mesh2.visual.face_colors[facet] = [200,0,0,255]  # RED
mesh2.export('colored.off')

Can anyone explain what i am doing wrong here?

**Comment by mikedh** [comment]
Ah, yeah the `off` file format only kinda has support for color. The importer uses vertex color hints if available but the exporter doesn't. You might try the `ply` format instead?
