### ISSUE TITLE
Unable to use intersect_first function

### ISSUE THREAD

**Issue by osvaldo14** [mikedh/trimesh#774]
I'm already using intersect_any function, but I want to improve the process speed by using pyembree package. So I installed trimesh with soft dependencies by using : `pip install trimesh[easy]` then I tried to use intersect first function : 

- `inf_pyembree = self.posture.get_posture.ray.ray_pyembree.intersects_first(ray_origins=self.ray_origins, 
												ray_directions=ray_direction)`

I just wanna try if the function works, but I get this error : 

- `inf_pyembree = self.posture.get_posture.ray.ray_pyembree.intersects_first(ray_origins=self.ray_origins, 
AttributeError: 'RayMeshIntersector' object has no attribute 'ray_pyembree'`

Do I need to make any changes or import something new to use pyembree module ? I already try `from pyembree import __version__ as _ver`, but it tell me that pyembree is an unresolved import.

Anyone face the same problems with using pyembree functions ?

**Comment by mikedh** [comment]
Hey, `trimesh[easy]` doesn't include `pyembree` as it's definitely not easy to install haha. Have you tried installing using their instructions:

https://github.com/scopatz/pyembree
