### ISSUE TITLE
point cloud export problem

### ISSUE THREAD

**Issue by Uio96** [mikedh/trimesh#778]
Hi  there,

Is there an easy way to export point cloud? I found there existed some support in the point cloud class. However, when I wanted to export my point cloud object as .ply, it showed " 'PointCloud' object has no attribute 'visual'".

My code is like:
```
mesh = trimesh.load('models/XX.obj')
cloud=trimesh.PointCloud(mesh.sample(10000))
cloud.export('demo.ply')
```

Do I miss anything here? Thanks a lot.

**Comment by mikedh** [comment]
No worries, point clouds weren't supported in PLY exports until #780 was merged just now. Try upgrading (`pip install --upgrade trimesh`) and that example should work. Thanks for the report!
