### ISSUE TITLE
[Bug] Voxellization produces totally inaccurate result

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#79]
# TRIMESH VERSION: 2.14.17

# STL FILE
https://drive.google.com/file/d/0B18jNduc8kjldzFuTVRaTFBsLTA/view?usp=sharing

# CODE TO REPRODUCE
```python
m = trimesh.load_mesh("the_above_mesh.stl")
vox = trimesh.voxel.Voxel(m,.25,size_max=1e10)
showin = vox.mesh + m
showin.show()
```
PRODUCES RESULT: 
<img width="422" alt="screen shot 2017-09-11 at 11 24 17 am" src="https://user-images.githubusercontent.com/2037165/30282828-6cc1e3ac-96e4-11e7-90ab-285287eb756a.png">
<img width="434" alt="screen shot 2017-09-11 at 11 24 12 am" src="https://user-images.githubusercontent.com/2037165/30282830-6cc5406a-96e4-11e7-9257-c61da6ef8e93.png">

# NOTES
The provided mesh is shown to have no problems that Netfabb can detect. Despite this, the underside of the funnel surface looks a little... fishy to me? I'm not sure what problem, if any, this corkscrew pattern of triangles could cause. But that's where I'm starting my search on this one.

**Comment by mikedh** [comment]
Ah yeah, the voxel module isn't very well thought out or particularly well implemented. My general though is that I'd like to switch to using something like openVDB and just do a thin wrapper. Unfortunately that is a royal PITA to install (although if you want to package it for conda-forge that would be sweet :). 

As a quick thing to try, slicing meshes using `mesh.section` and then rasterizing using `trimesh.path.polygons.rasterize_polygon` might do a better job then the ray thing there now.

The data structure is also not great. Maybe it would be better as an octree (pyoctree looked interesting) or as one of the scipy.sparse encodings.

**Comment by Marviel** [comment]
Cool! Thanks for the update -- I'll look over some of your suggestions this evening

**Comment by Marviel** [comment]
If it's cool I'll leave this open until solved

**Comment by mikedh** [comment]
Yeah definitely, its a problem child for sure. 

I was messing around with a couple ways to make this a little more reasonable, one approach is doing a per- triangle thing on the surface only, and treating the 'densification' as a different op. I added a subdivide_to_size method, which subdivides triangles until every edge is shorter than a specified length, which you can use for (better than the ray method anyway) voxelization:

```
    pitch=0.5
    max_edge = pitch / 2.0

    # get the same mesh sudivided so every edge is shorter than half our pitch              
    v,f = trimesh.remesh.subdivide_to_size(m.vertices, m.faces, max_edge)

    # convert the vertices to their voxel grid position                                     
    hit = (v / pitch)
    # get a conservative-ish wrapping                                                       
    hit = np.vstack((np.ceil(hit), np.floor(hit))).astype(int)

    # remove duplicates                                                                     
    u,i = trimesh.grouping.unique_rows(hit)

    # get the voxel centers in model space                                                  
    occupied = hit[u]*pitch

    m.visual.face_colors = [255,0,0,100]

    vox = trimesh.voxel.multibox(occupied, pitch)

    (vox+m).show()

```
Which produces this:
![screenshot from 2017-09-19 21-20-22](https://user-images.githubusercontent.com/1403074/30622575-74603eae-9d80-11e7-8b55-68006ae1cc07.png)


You definitely notice how n^2 or worse everything to do with voxelization is.

**Comment by AtinAngrish** [comment]
Hi!

Thank you for the excellent library and code. 

I used the voxelization code you suggested above and it works great! I have one question though:

It seems as if the code you wrote above fills the insides of the mesh as well. Do you have any suggestions so that it doesn't do that?

For example, I am trying to voxelize this cube into a NxNxN cube for which I adapted your code as follows:

```
def voxelize(mesh,R):
    # axis aligned bounding box is available
    volume = mesh.bounding_box.volume
    area = mesh.area
    if volume == 0:
        pitch = float((math.pow((area/(R*R)),1/2.))) #if a flat surface with 0 volume is encountered
    else:
        pitch = float((math.pow((volume/(R*R*R)),1/3.))) #otherwise

    max_edge = pitch / 2.0
    
    ## get the same mesh sudivided so every edge is shorter than half our pitch              
    v,f = trimesh.remesh.subdivide_to_size(mesh.vertices, mesh.faces, max_edge)
    # convert the vertices to their voxel grid position                                     
    hit = (v / pitch)
    # get a conservative-ish wrapping                                                       
    hit = np.vstack((np.ceil(hit), np.floor(hit))).astype(int)
    
    # remove duplicates                                                                     
    u,i = trimesh.grouping.unique_rows(hit)
    
    # get the voxel centers in model space                                                  
    occupied = hit[u]*pitch
    
    #mesh.visual.face_colors = [randint(0,255),randint(0,255),randint(0,255),randint(0,255)]
    
    vox = trimesh.voxel.multibox(occupied, pitch)
    return vox,occupied, pitch
```
While it does give me a voxelized mesh with each voxel's center (as "occupied") as follows:
![image](https://user-images.githubusercontent.com/15757067/31042692-9d4a1cb0-a57b-11e7-8bf6-57b3ae059250.png)
 the wireframe seems to indicate that the mesh insides have also been voxelized. 
![image](https://user-images.githubusercontent.com/15757067/31042652-dd6f8150-a57a-11e7-9786-4cfa66c639fe.png)

Do you recommend a way to solve this problem?

Thank you!

**Comment by mikedh** [comment]
Hey, the subdivide method will definitely not fill in the mesh (it doesn't have any information about the volume, only the surface). I think in your example you are just setting a very coarse voxel pitch and its hard to tell in the wire frame view. 

For example, here is a [4,4,4] box voxelized with a .25 pitch using the subdivide method, viewed from the inside:
![image](https://user-images.githubusercontent.com/1403074/31048868-fffffbc6-a5f4-11e7-916e-e35b1f64a5b8.png)

**Comment by mikedh** [comment]
Hey, since voxelization was switched to the subdivide method from the ray methods that produced these exciting artifacts I'm going to close this one for now. I'm sure exciting new voxel issues will take precedence 😄  (like the part where column filling went away).

**Comment by jonnymaserati** [comment]
I see that FCL implements octree and appears to initiate an octree object when creating a collision object. Is it possible to use this for creating voxels?

I'm interested since I'd like to get the node coordinates of the empty voxels in a scene but I'm after the sparsely sized voxels (i.e. large voxels where there's no occupancy). Is there a way of doing this already with trimesh?
