### ISSUE TITLE
Bug: trimesh.Trimesh(vertices, faces) reorders faces.

### ISSUE THREAD

**Issue by d-walsh** [mikedh/trimesh#790]
When I instantiate a Trimesh object using `mesh = trimesh.Trimesh(vertices, faces)` the resulting Trimesh does not have the same faces values as the original: 
```
faces[10] != mesh.faces[10]
```
Instead to workaround this I have to instantiate the Trimesh object not using the constructor:
```
mesh = trimesh.Trimesh()
mesh.vertices = vertices
mesh.faces = faces
```

**Comment by mikedh** [comment]
Have you tried with `trimesh.Trimesh(vertices, faces, process=False)`?

**Comment by d-walsh** [comment]
@mikedh I just tried that and it does stop the reordering of `faces`. Is that intended functionality?

**Comment by mikedh** [comment]
Yep! By default vertices are merged which reindexes faces, `process=False` disables that.

**Comment by d-walsh** [comment]
OK great, thanks for explaining @mikedh!
