### ISSUE TITLE
Question about watertight mesh?

### ISSUE THREAD

**Issue by ibrahimLearning** [mikedh/trimesh#791]
@hauptmech @mikedh 
I have a mesh. it has vertices and triangles/faces. From here, how can I make watertight mesh?
How can I make watertight mesh from non-watertight mesh?

**Comment by mikedh** [comment]
It depends a lot on the specifics. `mesh.fill_holes `will fill single-triangle and single-quad holes. For anything beyond that there isn't really a clear answer as the mesh doesn't have enough information. `mesh.convex_hull` will be watertight. You could also sample the triangles densely and then use marching cubes: 

```
In [3]: m = trimesh.creation.random_soup(10)

In [4]: m
Out[4]: <trimesh.Trimesh(vertices.shape=(30, 3), faces.shape=(10, 3))>

In [5]: m.sample(1000)
Out[5]: 
array([[-0.13584,  0.0007 ,  0.1245 ],
       [-0.22354,  0.15357, -0.03923],
       [-0.23936, -0.02946,  0.01717],
       ...,
       [-0.12456,  0.27132, -0.10581],
       [-0.04852, -0.21715, -0.0645 ],
       [-0.07637, -0.04984,  0.14937]])

In [7]: r = trimesh.voxel.ops.points_to_marching_cubes(m.sample(1000))

In [9]: r.show()

In [14]: r.is_watertight
Out[14]: True
```
![marching](https://user-images.githubusercontent.com/1403074/79264142-0e4c5600-7e62-11ea-8943-debe3e42020c.png)
