### ISSUE TITLE
Help on turning a graph into a mesh?

### ISSUE THREAD

**Issue by aluo-x** [mikedh/trimesh#792]
Not a problem strictly related to trimesh, but thought this might be the right place to ask this.

Currently I have an issue where the input is an undirected graph, given in an int array of shape (E, 2).

The graph may have edges which are not part of a face, and currently trying to figure out a performant way to turn this into a well behaved mesh. Ignoring problems with normals etc, which can be fixed in post. Is there a faster way to do this than finding the 3-cliques using networks?

**Comment by mikedh** [comment]
Oh yeah neat problem, and yeah I agree the networkx-cycle thing is going to be mega-slow. 2 ideas:

1) Figure out a way to do it with `scipy.sparse.csgraph` operations (i.e. `trimesh.graph.edges_to_coo(edges)`). If possible this is likely the fastest thing.
2) Every face can be represented by two edges. If you take all pairs of edges that share a vertex, you can check to see if the third implied edge was a part of your original edge-set. This can probably all be done by numpy operations with maybe the exception of the neighbors part. Here's one simple implementation of that:

```
def neighbors(edges, directed=False):
    """                                                                                              
    Find the neighbors for each node in an edgelist graph.                                            
                                                                                                     
    TODO : re-write this with sparse matrix operations                                               
                                                                                                     
    Parameters                                                                                       
    ------------                                                                                     
    edges : (n, 2) int                                                                               
      Connected nodes                                                                                
    directed : bool                                                                                  
      If True, only connect edges in one direction                                                   
                                                                                                     
    Returns                                                                                          
    ---------                                                                                        
    neighbors : dict                                                                                 
      Keyed by vertex index, values are a set of other vertex indeices                               
    """
    neighbors = collections.defaultdict(set)
    if directed:
        [neighbors[edge[0]].add(edge[1])
         for edge in edges]
    else:
        [(neighbors[edge[0]].add(edge[1]),
          neighbors[edge[1]].add(edge[0]))
         for edge in edges]

    return dict(neighbors)

```

**Comment by aluo-x** [comment]
Thanks for taking the time to reply!
I was not aware of the scipy sparse graph routines, will definitely take a look into this. For networkx, there is also the option of using `simple_cycles`, which still using a loop but might be faster.
There is also the option of [using this](https://graph-tool.skewed.de/static/doc/topology.html?highlight=cycle#graph_tool.topology.all_circuits). The problem of finding 3-cycles might be in general be better implemented than finding 3-cliques. 

Also looked into cuGraph, they have a function to return the number of triangles, but not the list of triangles. 
The gunrock library provides the "Advance Operator" which may also be what we want (if we use a bi-directionally connected directed graph), we could probably just call it three times. Unfortunately there is no real python interface. Although cuGraph is supposedly hoping to include gunrock in the future...

I'll keep thinking about this problem. Hoping to constrain this to sub 100ms for a graph with 10k edges. GPU execution would be ideal, but vectorized/parallel execution would be the next best. I can either close this problem or keep it open for people to pop ideas in.

**Comment by mikedh** [comment]
No worries! Yeah `graph-tool` was one of the optional engines for `trimesh.graph.connected_components` until a few months ago, when I removed it because it wasn't getting unit tested due to it's laborious install process. Also in benchmarking it wasn't that much faster than scipy, it was generally within 10% of `scipy.sparse.csgraph` at least for connected components. 

I'd probably focus on either numpy methods, or if that failed a simple compiled cython loop rather than other graph libs.
