### ISSUE TITLE
Missing inertial component

### ISSUE THREAD

**Issue by DMST1990** [mikedh/trimesh#8]
file: tirangle.py
   function: mass_properties
   problem: Missing value inertia[1,0]

    inertia = np.zeros((3,3))
    inertia[0,0] = integrated[5] + integrated[6] - (volume * (center_mass[[1,2]]**2).sum())
    inertia[1,1] = integrated[4] + integrated[6] - (volume * (center_mass[[0,2]]**2).sum())
    inertia[2,2] = integrated[4] + integrated[5] - (volume * (center_mass[[0,1]]**2).sum())
    inertia[0,1] = (integrated[7] - (volume * np.product(center_mass[[0,1]])))
    inertia[1,2] = (integrated[8] - (volume * np.product(center_mass[[1,2]])))
    inertia[0,2] = (integrated[9] - (volume * np.product(center_mass[[0,2]])))
    inertia[2,0] = inertia[0,2]
    inertia[2,1] = inertia[1,2] 
#-----------------
# Add the following line which is missing
#-----------------
  inertia[1,0] = inertia[0,1]

**Comment by mikedh** [comment]
Good catch, thanks! Fixed in f205ee2c8e767b0171202df1927d02e50ea48dc0
