### ISSUE TITLE
Landmarks support 

### ISSUE THREAD

**Issue by darfire** [mikedh/trimesh#80]
First of all, congrats for the great work on this project.

In various applications certain vertices have a special meaning (imagine a body scan, you might have an 'elbow', 'nose', 'thumb', etc.). It would be nice to have a way to mark these vertices with their role, show them when visualizing, save together with the mesh and load them back.

I am not sure which formats support this kind of metadata. PLY supports it as a separate element which has one integer property (the vertex index) for each landmark. JSON obviously supports it too. 

Cheers,
Doru

**Comment by Marviel** [comment]
Seems pretty simple... like a key-value mapping you could just store in the Trimesh object. The trick would be in cases where vertices are deleted or added, and the vertex index changes.

Exporting to .ply I'm not familiar with however.

**Comment by mikedh** [comment]
Thanks for the positive reinforcement 😉 

I think your best bet for additional metadata like that is to store it in `mesh.metadata`, and then use dict- derived importers/exporters, which will preserve the stuff in mesh.metadata through inport/export cycles. For example:

```
In [19]: j = mesh.export(file_type='json')

In [20]: json.loads(j).keys()
Out[20]: dict_keys(['faces', 'face_colors', 'vertices', 'metadata', 'face_normals'])
```

**Comment by mikedh** [comment]
Closing for now, happy to accept PR's if you add support for this in formats other than the JSON one above. Thanks for the report!
