### ISSUE TITLE
Question about how to show transparent objects

### ISSUE THREAD

**Issue by motikadosh** [mikedh/trimesh#804]
Hi,
I am not able to get an object to be transparent.
In the following snippet, I expected the blue ball to show behind the red one.
What am I doing wrong?
Thanks!

```
from trimesh import Scene
from trimesh.creation import icosphere

sphere1 = icosphere(radius=10.0)
sphere1.visual.face_colors[:] = np.array([255, 0, 0, 50])
sphere1.visual.vertex_colors[:] = np.array([255, 0, 0, 50])

print("transparency", sphere1.visual.transparency)
print("main_color", sphere1.visual.main_color)

sphere2 = icosphere(radius=30.0).apply_translation(np.array([0, 0, -50]))
sphere2.visual.face_colors[:] = np.array([0, 0, 255, 50])
sphere2.visual.vertex_colors[:] = np.array([0, 0, 255, 50])

scene = Scene([sphere1, sphere2])
scene.show()

**Comment by mikedh** [comment]
Hey, yeah alpha transparency is a bit unreliable as it [relies on draw order](https://github.com/mikedh/trimesh/blob/22e712d97baf8340f95da15f7a2446e54888b840/trimesh/viewer/windowed.py#L744-L755). The viewer logic currently draws all transparent things last, which works OK for one transparent thing and a bunch of opaque things, but works less well when all of the things are transparent. You could probably implement a Z-order thing that would work OK. 

![alpha](https://user-images.githubusercontent.com/1403074/79763768-7d0e3100-82f2-11ea-8a09-6aa539d173bd.png)

**Comment by motikadosh** [comment]
Thanks, I found that the problem is in the the Jupyter notebook show, when I run the code in console with pyglet viewer everything looks fine.
Are there any alternatives for viewing trimesh objects in jupyter notebook, other than using three.js?
Thanks

**Comment by zhenkirito123** [comment]
> Thanks, I found that the problem is in the the Jupyter notebook show, when I run the code in console with pyglet viewer everything looks fine. Are there any alternatives for viewing trimesh objects in jupyter notebook, other than using three.js? Thanks

I got the same question, thanks for your solution!
