### ISSUE TITLE
[Enhancement] Trimesh-Native Booleans

### ISSUE THREAD

**Issue by Marviel** [mikedh/trimesh#81]
It would be interesting to have -- either within trimesh, or within a C++ library that could optionally be shipped with trimesh -- an accessible version of the boolean operation algorithms described in this paper: 
https://arxiv.org/pdf/1605.01760.pdf

I would like to develop this myself at some point, but I'm putting it here to get others' opinions as to the value of choosing this particular algorithm.

The main reasons for thinking it would be good to do this is that CGAL is very slow, and Blender is known to fail with some ill-constructed meshes -- both of which this algorithm seems to address.

**Comment by Marviel** [comment]
The main reasons for thinking it would be good to do this is that CGAL is very slow, and Blender is known to fail with some ill-constructed meshes -- both of which this algorithm seems to address.

**Comment by mikedh** [comment]
Yeah that could be nice, though my experience playing around with different implementations of mesh booleans (lookin at you, cork) is that they are very difficult to implement robustly, and I definitely wouldn't be able to do a better job than existing implementations. Though happy to accept PR's!

For my projects lately I've generally been trying to architect around avoiding boolean operations completely, though admittedly that's not always possible.

**Comment by Marviel** [comment]
Yeah that totally makes sense!

I just know that this particular algorithm has been in production use for some time, and seems to be a bit faster than other current implementations.  Not looking to reinvent it myself... rather just for an implementation of it :)

Whatever the case, this algorithm does require a few functions that would be nice for trimesh to have anyway --- creating a polyline loop from triangle intersections, closing multi-triangle holes, etc...

I'll probably try to implement each of those separately, and then maybe when the time is found perform the boolean part of the operation

**Comment by mikedh** [comment]
Sounds good! I'll close this for now.
