### ISSUE TITLE
many attribution not support

### ISSUE THREAD

**Issue by Continue7777** [mikedh/trimesh#810]
1.accessor byteOffset parse wrong:
```
access[index] = np.frombuffer(data[start:start + length], dtype=dtype).reshape(shape) # can't deal with some conf
```

2.can't support node translation
3.basecolor parse wrong , something alpha is 0 
4.when alpha is 1 , it can't be render correctly
5.samplers may be not right.
 all in all,trimesh gltf-load has too many bugs,hope to fix!

**Comment by mikedh** [comment]
PR's welcome! I added a disclaimer to the README noting that there are plenty of parts of the spec not implemented.
