### ISSUE TITLE
Depth not correctly taken into account when showing scene.

### ISSUE THREAD

**Issue by bertrandhaut** [mikedh/trimesh#814]
1. Thanks for your library, very useful
2. I've a very stranger behavior related to an object not correctly shown as behind another object when calling SceneViewer.

Here is the code:
```
import trimesh.visual
from trimesh.scene import Scene
from trimesh.viewer.windowed import SceneViewer, render_scene
import trimesh.creation

import numpy as np

mesh1 = trimesh.creation.icosphere(subdivisions=3, radius=1.0)
mesh1.visual.face_colors = trimesh.visual.interpolate(values=mesh1.triangles_center[:, 2],
                                                      color_map='viridis')
mesh2 = trimesh.creation.icosphere(subdivisions=3, radius=1.0)
mesh2.vertices += np.array([10,0,0])
mesh2.visual.face_colors = trimesh.visual.interpolate(values=mesh2.triangles_center[:, 2],
                                                      color_map='viridis')

scene = Scene(geometry=[mesh1, mesh2])
SceneViewer(scene=scene)
```
On my windows machine it's good

On my Linux VM, I get an error. Screenshots of the outputs are in attachement
![Capture1](https://user-images.githubusercontent.com/6848040/80484575-3bb3fc00-8958-11ea-85a8-5c47291d317f.PNG)
![Capture2](https://user-images.githubusercontent.com/6848040/80484567-38b90b80-8958-11ea-8cd5-dce72be22b97.PNG)
![Capture3](https://user-images.githubusercontent.com/6848040/80484573-3b1b6580-8958-11ea-93f2-4f4ea58c9df3.PNG)

As you can see the ball which is the fartest away is plotted in front.

**Comment by bertrandhaut** [comment]
My python environment (conda & purely conda-forge).

name: trimesh_test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=openblas
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.2=h167e202_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.1=he06d7ca_0
  - future=0.18.2=py38h32f6830_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py38he6710b0_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - ncurses=6.2=he6710b0_0
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_0
  - numpy=1.18.1=py38h8854b6b_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.43=he6710b0_0
  - pip=20.0.2=py38_1
  - pyglet=1.5.4=py38h32f6830_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.2=hcf32534_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scipy=1.4.1=py38habc2bb6_0
  - setuptools=46.1.3=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py38h7b6447c_1
  - trimesh=3.6.34=pyh9f0ad1d_0
  - wheel=0.34.2=py38_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
prefix: /opt/conda/envs/trimesh_test

**Comment by bertrandhaut** [comment]
Any idea what is failing? 
I'm running this code in a VirtualBox machine (don't know if this could have an impact)

**Comment by mikedh** [comment]
Hey, not sure exactly why that's happening, but I'd bet the z-buffer is overflowing for some reason. Perhaps an OpenGL config issue?
