### ISSUE TITLE
Disable caching

### ISSUE THREAD

**Issue by adrian-delgado** [mikedh/trimesh#815]
Is there any way to disable or clear the global cache?

I'm running a big loop where I load some files and trimesh ends up eating the RAM. 

Sorry if it's documented, but I couldn't find it.

**Comment by mikedh** [comment]
Hey, you can clear it with:
```
In [1]: len(m._cache)
Out[1]: 17

In [2]: m._cache.clear()

In [3]: len(m._cache)
Out[3]: 0
```
We could add a cache mode to never store too potentially.

**Comment by adrian-delgado** [comment]
Hey, thanks for the quick reply!

I tried it but the memory still grows, even though `len(m._cache)` is 0 at the end of each iteration.

I does however make a difference when I run `gc.collect()` at the end of the loop, regardless of whether I used `m._cache.clear()` or not.

**Comment by mikedh** [comment]
NP! This may be the wider issue with long-running Python processes and memory: #17

**Comment by adrian-delgado** [comment]
Makes sense. The related issue is what I was looking for!

Thanks for your help.
