### ISSUE TITLE
Issue with option `merge_primitives=True`

### ISSUE THREAD

**Issue by fmannhardt** [mikedh/trimesh#818]
Thanks for this nice library. I am trying to load a GLTF file in which multiple primitives are used for one mesh. 

When loading the GLFT using the standard options only a part of the mesh gets loaded. It seems that the TransformForest only keeps a reference to the mesh data from the latest primitive loaded and discards the rest.

I saw the recent commit with the option `merge_primitives=True` that should solve this issue. Now more of the data is loaded an by debugging through the code I could confirm that all the primitives are merged. However, it seems that some faces are wrongly loaded. I have artefacts like the ones in the attached screenshot when using `.show()` (and the part of the models gets a different color):

![image](https://user-images.githubusercontent.com/3202998/81122714-cd5fd280-8f31-11ea-86a1-662f40e7f4aa.png)

It seems that the face indices are somehow not correct. Unfortunately, I cannot share the model files, but they load fine in other tools.

Is there anything I could do to give debug information without sharing the models?

**Comment by mikedh** [comment]
Yeah without sharing the mesh it's tough to debug. Happy to take PR's fixing this! FWIW the way I'd start debugging this is adding a `from IPython import embed; embed()` somewhere in this neighborhood: https://github.com/mikedh/trimesh/blob/master/trimesh/exchange/gltf.py#L952-L1023

One other option is if you could generate or find a similar but non-proprietary model to demonstrate the issue.

**Comment by fmannhardt** [comment]
Thanks. I already debugged there and confirmed that the primitives are merged correctly. At least this part is called correctly:
https://github.com/mikedh/trimesh/blob/b63a092ea2836ae810c41021f3371e2cf00c2866/trimesh/exchange/gltf.py#L1043
and I assume the function `append_faces` is correct.

So, the error must be somewhere beforehand when loading the vertices. I will try to see if I can somehow simplify the model while retaining the issue.

**Comment by fmannhardt** [comment]
I can confirm that it loads fine with `merge_primitives=False` now. When merging the same issue is still there, but at least I have a workaround now. 

Still did not find the time to prepare a minimal example that I could share. Very weird since the merging should not change anything.
