### ISSUE TITLE
Convert voxels to mesh object

### ISSUE THREAD

**Issue by Emrys-Lee** [mikedh/trimesh#82]
Hi, I have a 3d voxel matrix now. Is it possible to convert it to a mesh object so that I can generate a .ply file? Thank you!

**Comment by Marviel** [comment]
This is an existing function, but it may not perform as you'd wish.

try:
```python
vox = mesh.voxelized(pitch)
voxel_mesh = vox.mesh
voxel_mesh.show()
```
the difference between this and the ideal version is that each voxel column is essentially represented as a single cuboid, rather than the whole voxel volume being a unified single trimesh object.

**Comment by Marviel** [comment]
reference: https://github.com/mikedh/trimesh/blob/master/trimesh/voxel.py

**Comment by mikedh** [comment]
Yeah- that function does exist, and as Luke mentioned you probably don't want it. What you probably want is marching cubes.

**Comment by Marviel** [comment]
@mikedh on that note, I've found that the marching cubes algorithm in scikit's skimage.measure [1] does a pretty good job, once I convert the voxel runs to a binary numpy array.

I'm not sure if you'd be interested in including scikit as a dependency, but this has been working very well for me thus far.

[1] http://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.marching_cubes_lewiner

**Comment by Emrys-Lee** [comment]
Thank you. Maybe I'll try some other ways.
