### ISSUE TITLE
GLTF loader missing meshes with same name

### ISSUE THREAD

**Issue by jengvi** [mikedh/trimesh#824]
First of all - great library!

I am having a problem loading a GLTF scene that includes multiple meshes with the same name. The GLTF [here](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/www/TestScene/TestScene.gltf) has two meshes with the name `Cube`. Here is what this looks like in another GLTF viewer:
<img width="1227" alt="Screen Shot 2020-05-08 at 4 27 03 PM" src="https://user-images.githubusercontent.com/56892628/81447391-8a2c7c00-914a-11ea-85ff-8fdf82ffbebd.png">
This is what I see in Trimesh:
<img width="1912" alt="Screen Shot 2020-05-08 at 4 26 52 PM" src="https://user-images.githubusercontent.com/56892628/81447543-d24b9e80-914a-11ea-869c-25215582f0a9.png">
Note one missing cube in the right side of the scene. If I manually change the name of one of the cubes to another name like `Cube2`, I can get it to appear in Trimesh. I am using Trimesh 3.6.35 and loaded this scene with `merge_primitives=True`.  I'm looking through gltf.py now to see if I see anything obvious...

Thanks in advance!

**Comment by loudonicus** [comment]
Hi you've managed to get further than me in loading a gltf, I wonder if you could give me step for a hint? I am trying to load one of the examples from Khronos, Avocado.gltf in jupyter notebook. 

```
currResolver = trimesh.visual.resolvers.FilePathResolver("C:/Users/brian/Dropbox/Python/")
gltfname = "Avocado.gltf"
gltf_import = trimesh.exchange.gltf.load_gltf(open(gltfname,"rt"),currResolver)
gltfScene = trimesh.Scene(gltf_import)  
```

Jupyter notebook then reports 

unknown type (str) added to scene!
unknown type (str) added to scene!
unknown type (float32) added to scene!
unknown type (float32) added to scene!
unknown type (float32) added to scene!
unknown type (float32) added to scene!
unknown type (float32) added to scene!
unknown type (float32) added to scene!
....

and then gltfScene.show() gives a whole host of errors.

Sorry for the noob question, but have I missed a vital step?

**Comment by mikedh** [comment]
Hey, I don’t think all the instantiaton is necessary... have you tried just
‘trimesh.load(gltfname)’?

**Comment by loudonicus** [comment]
ah! embarassing... yup that works a treat! Guess I was just making life too difficult for myself!

**Comment by mikedh** [comment]
No worries glad it worked! @jengvi would you be able to send me a copy of that mesh? Would it be OK to add to unit tests?

**Comment by jengvi** [comment]
Absolutely - this mesh was supplied by Khronos here: [https://github.com/KhronosGroup/UnityGLTF/tree/master/UnityGLTF/www/TestScene](https://github.com/KhronosGroup/UnityGLTF/tree/master/UnityGLTF/www/TestScene)

**Comment by jengvi** [comment]
@mikedh here is a potential fix that addresses duplicate node names in gltf scenes. What do you think? I can submit a PR if that would be helpful.

```diff
--- a/trimesh/exchange/gltf.py
+++ b/trimesh/exchange/gltf.py
@@ -1064,7 +1064,10 @@ def _read_buffers(header, buffers, mesh_kwargs, merge_primitives=False, resolver
     names = {}
     for i, n in enumerate(nodes):
         if "name" in n:
-            names[i] = n["name"]
+            if n["name"] in names.values():
+                names[i] = n["name"] + "_{}".format(util.unique_id())
+            else:
+                names[i] = n["name"]
         else:
             names[i] = str(i)
 
@@ -1147,7 +1150,7 @@ def _read_buffers(header, buffers, mesh_kwargs, merge_primitives=False, resolver
             for name in geometries:
                 kwargs["geometry"] = name
                 if 'name' in child:
-                    kwargs['frame_to'] = child['name']
+                    kwargs['frame_to'] = names[b]
                 else:
                     kwargs["frame_to"] = "{}_{}".format(
                         name, util.unique_id(
```
Link to patch: [https://github.com/jengvi/trimesh/commit/aeefe89a27ae17c3f4d6286b9a2ba1623329a286](https://github.com/jengvi/trimesh/commit/aeefe89a27ae17c3f4d6286b9a2ba1623329a286)

**Comment by mikedh** [comment]
Awesome thanks for the fix! Yeah a PR would be great!
