### ISSUE TITLE
[minor enhancement] Ignoring comments in .obj (wavefront) files

### ISSUE THREAD

**Issue by jgolinkoff** [mikedh/trimesh#83]
First, I'd like to say thank you for making such a wonderful package! This has been really useful for me.  I've been trying to read in some .obj files I have and this continues to throw an error because the .obj files I have have some lines that are comments and start with a '#' symbol. 

I've hacked around with the load_wavefront() function and I've added the following line to deal with this:

```python
    # we add a space before every newline to make things easy on ourselves
    text = ' '.join(re.split('/\S* ', 
                             text_original.replace('\n', ' \n')))

    # remove all comment lines - this is the new line I've added.
    text = re.sub('#.*\n', '\n', text)
`

Thanks again.

**Comment by mikedh** [comment]
Glad its useful, and thanks for the fix! Included in https://github.com/mikedh/trimesh/commit/67447bf96fc1f62d689d3b69b7b48bb45e26d223
