### ISSUE TITLE
Fill Holes of largers Gaps.. 

### ISSUE THREAD

**Issue by popupdev** [mikedh/trimesh#832]
I am working with 2 meshes..
And I wanted to combine them seamlessly in variable of their dispropotions.. 
I used concatenate() to combine them But still there are some gaps in between them

Like the one image below
.. 

![images (3)](https://user-images.githubusercontent.com/56559624/81807709-30f28d00-953c-11ea-86b7-988911418fd4.jpeg)

I want to make the gap fill along its edges to make them perfectly combined.. 

I tried **fillholes(mesh)**
But as mentioned it only fills one triangle space. 
If needed we need to use any backend like blender.. 

But my question is can we do any moderations in the code to fillholes of different spacing.. 

Like in vtkpython they have fillholes for different spacing. But there it doesn't actually fillholes along edge to edge rather it fills with the closest points. 

Can any modifications be done in code to achieve complete seamless combination of them both..

Few examples of the situation is provided in the below images.. 

![images (4)](https://user-images.githubusercontent.com/56559624/81808119-dc9bdd00-953c-11ea-94e0-7042dd82ab78.jpeg)

And the last example case where a hand and arm is to be combined together... 

![images (5)](https://user-images.githubusercontent.com/56559624/81808170-f0dfda00-953c-11ea-98be-d6f17167475c.jpeg)

**Comment by mikedh** [comment]
Hey, i don't think there's an easy way to do this, it is quite a hard problem, and `trimesh` doesn't have any methods which can handle this kind of operation. You could look at `mesh.outline` and then try to do some logic which added faces between nearby unmatched faces, but it's probably going to be quite an uphill battle.

**Comment by popupdev** [comment]
@mikedh Thanks for the response . But is there any other 3rd party library to achieve this .

**Comment by aluo-x** [comment]
Why not find the boundary edges first (should be edges that are only used by one face). Find the vertices used by these edges, compute chamfer distance between distinct components, threshold by a certain value, and then add edges between these points?

**Comment by mikedh** [comment]
You could give [meshmixer](http://www.meshmixer.com/) a try, sometimes it gives surprisingly good results.
