### ISSUE TITLE
Load GLB Texture issue

### ISSUE THREAD

**Issue by MattSmillie** [mikedh/trimesh#833]
Hi again,

I've been taking my work a little further and am now wanting to get the texture information - I have loaded this model which has a jpeg as a texture:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb
with the following call:
```scene=trimesh.load(file_obj="CesiumMilkTruck.glb",file_type="glb",merge_primitives="true")```
When I then inspect the visuals of the geometry I see that `Cesium_Milk_Truck` has `visuals` of `kind=None`

Should I be using a resolver on load or is this a bug?  

Thanks again

**Comment by mikedh** [comment]
Hey, `merge_primitives` will lose the texture information, as concatenation-with-texture is hard and not currently supported. If you load it without that option it should be OK:
`scene=trimesh.load('CesiumMilkTruck.glb')`

**Comment by MattSmillie** [comment]
Aha!! ok then I shall experiment some more - I must say I'm enjoying playing with all this stuff. Thanks for making and maintaining it all. Great stuff!
