### ISSUE TITLE
How to show geometry with its underlying mesh grid?

### ISSUE THREAD

**Issue by evakrowarska** [mikedh/trimesh#837]
Hi, 

at the moment I am viewing geometry simple by calling e. g. mesh.show().
Is there a possibility to activate the visibility of the underlying mesh structure visually?
That way I can validate if my modifications to the mesh have been correct. 

Thank you in advance.

**Comment by mikedh** [comment]
Hey, if you press `w` in the default viewer it should show the wireframe.
