### ISSUE TITLE
Mesh with submesh but no nodes?

### ISSUE THREAD

**Issue by MattSmillie** [mikedh/trimesh#838]
Hi again,

I'm playing around with scenes and a few different files. I have a glb file with contains sub meshes from a parent mesh.

When inspecting the graph I see that none of the geometries are represented as node but are listed in the list of geometries. I'm assuming that I need to drill down from the parent mesh but not quite sure how. I also notice if I export the scene as a GLB then I'm only getting one of teh sub meshes in the export. 

When MergePrimitives=True then it all comes in as one but I lose texture so i've turn it off.

For now I have assumed that all sub meshes will be called `parentMesh_X` and I'm able to do what I want. Can I operate on that assumption or is there a proper way to drill down to these sub meshes

Thanks again for everything

**Comment by mmatl** [comment]
@mikedh I just ran into this issue as well. It causes the dump() function to fail to dump most of the geometry in hierarchical GLTF scenes. See the attached file for an example.
[base.glb.zip](https://github.com/mikedh/trimesh/files/4636975/base.glb.zip)

**Comment by mikedh** [comment]
Thanks for the report and model! I think this is fixed with the latest release, though feel free to re-open if not:

```
In [6]: m = trimesh.load('/home/mikedh/Downloads/base.glb')

In [7]: m.graph.nodes_geometry
Out[7]: ['BGI80S50_B3_S1_G38M_002_yGUsBv', 'BGI80S50_B3_S1_G38M_002_yGWslg']

In [8]: m.geometry
Out[8]: 
OrderedDict([('Piab_0',
              <trimesh.Trimesh(vertices.shape=(183411, 3), faces.shape=(62546, 3))>),
             ('Piab_1',
              <trimesh.Trimesh(vertices.shape=(105802, 3), faces.shape=(36124, 3))>)])

In [9]: m.graph.transforms.edges
Out[9]: OutEdgeView([('world', 'BGI80S50_B3_S1_G38M_002'), ('BGI80S50_B3_S1_G38M_002', 'BGI80S50_B3_S1_G38M_002_yGUsBv'), ('BGI80S50_B3_S1_G38M_002', 'BGI80S50_B3_S1_G38M_002_yGWslg')])
```

**Comment by MattSmillie** [comment]
Just wanted to share with you that this is now working and a big thank you again for everything you're doing here - what a legend!
