### ISSUE TITLE
GLTF normalTexture scale missing?

### ISSUE THREAD

**Issue by ibozhilov** [mikedh/trimesh#839]
I am trying to load GLTF file into trimesh. When I process the materials of the loaded GLTF I am unable to find the scale param of the normalTexture. In GLTF within the material the normalTexture is describe as follows:
`"normalTexture": {
                "scale": 2,
                "index": 3,
                "texCoord": 1
            }`
However, once loaded the scale param is nowhere to be found. There is just a PIL image for the normalTexture, but no additional params. Am I missing something? I will appreciate any help you could provide.

**Comment by mikedh** [comment]
That's not currently implemented, but PR's are welcome! I'll add a disclaimer to the README
