### ISSUE TITLE
[Enhancement] Animation

### ISSUE THREAD

**Issue by riegaz** [mikedh/trimesh#84]
Is there any way of creating an animation? I would be interested in changing colors while manipulating the object view.

**Comment by mikedh** [comment]
Hey, I looked into this a while ago where I was hoping to run the viewer in a separate thread, and then have transforms and mesh attributes update automatically. Unfortunately somewhere in the pyglet/opengl stack this doesn't really work, at all. 

I think what you'd have to do is either fork and add it to the main event loop in [viewer.py](https://github.com/mikedh/trimesh/blob/master/trimesh/scene/viewer.py), or do a better job of encapsulating the window object and arranging updates to be transferred through a queue or something.
