### ISSUE TITLE
Exported mesh as .obj appears as solid black color by default

### ISSUE THREAD

**Issue by SushmaDG** [mikedh/trimesh#843]
Hi, 

I am trying to export a mesh as .obj. The code looks like this:
`export, texture = trimesh.exchange.obj.export_obj(mesh, include_color=True, include_texture=True)`

`with trimesh.util.TemporaryDirectory() as path:`
    `obj_path = os.path.join('', 'file_name.obj')`
    `with open(obj_path, 'w') as f:`
        `f.write(export)`
    `for k, v in texture.items():`
        `with open(os.path.join('', k), 'wb') as f:`
            `f.write(v)`

When this obj is loaded again, the model appears in solid black color. As expected the mesh must conserve its color coordinates. I also tried to visualize it in blender API and it displays the mesh in black color by default (as seen in the below image). 

![mesh](https://user-images.githubusercontent.com/22175791/82459996-e8e1e600-9ab8-11ea-9fbe-bf585f2ae5d0.png)

I get the colored model only after changing the mode (display rendered preview in blender api). Could you please tell me how I can get the colored model by default when I load the exported mesh?

Used trimesh version: `3.6.38`

Thank you!

**Comment by mikedh** [comment]
Gotcha so the color *is* exporting from trimesh, it just doesn't show up by default in blender? If that's the case it is probably best resolved from the Blender side, I don't know how much we can do about that at export time. Although if you have an example of a file that behaves as you expect happy to take a look and tweak trimesh's export format!

**Comment by SushmaDG** [comment]
Hi,
Yes, I can share the obj files.
1. This is the original file that behaves as expected.
[file.zip](https://github.com/mikedh/trimesh/files/4672975/file.zip)

2. This is the exported .obj file. 
[file2.zip](https://github.com/mikedh/trimesh/files/4672978/file2.zip)

Thank you.

**Comment by SushmaDG** [comment]
Hi,

To resolve the issue with exported mesh,  I tried a few things:

(1) Loaded an .obj file, then added to pyrender scene and tried to visualize using pyrender.Viewer()

`mesh = trimesh.load('/path/to/original/file.obj')`
`pyrender_mesh = pyrender.Mesh.from_trimesh(mesh, smooth=False)`
`scene_ = pyrender.Scene()`
`scene_.add(pyrender_mesh)`
`pyrender.Viewer(scene_, use_raymond_lighting=True)`

I get this:
![original_obj](https://user-images.githubusercontent.com/22175791/82904714-233cfe80-9f63-11ea-9f49-d5ed3761ed0b.png)

(2.) Now I exported the same loaded mesh,

`export, texture = trimesh.exchange.obj.export_obj(mesh, include_color=True, include_texture=True)`

I loaded this exported mesh and did the same as in (1). I get this in pyrender.Viewer,
![new_obj](https://user-images.githubusercontent.com/22175791/82905169-cee64e80-9f63-11ea-83b1-d083f384fd4c.png)

Even here I get the same solid black object model. I hope this helps.

**Comment by mikedh** [comment]
Hey, I think this is probably related to the MTL/images not being written. There was a pretty recent change to try to simplify this when users export to a path. You might try upgrading to the latest version of trimesh (`pip install --upgrade trimesh`) and then export using a file path:

```
mesh.export('drill.obj') 
```

**Comment by SushmaDG** [comment]
Hi, 
I tried what you suggested, but the result is still the same. Could you suggest any other solution?
(trimesh version: 3.6.42)
Thank you.

**Comment by mikedh** [comment]
Ah, I think this is actually the `ambient` color set to all zeros in the MTL file due to a dtype issue, #851 should resolve this hopefully.
