### ISSUE TITLE
[Question] Triangulate concave polygon

### ISSUE THREAD

**Issue by FreakTheMighty** [mikedh/trimesh#844]
@mikedh I'm wondering if you're aware of a good way to triangulate a concave polygon path? 

![image](https://user-images.githubusercontent.com/247092/82676761-8437a000-9c0c-11ea-8a59-3186e1ec1b66.png)

This banana shaped thing is supposed to be a sort of bent rectangle, but triangulation leads to the two ends being connected.

**Comment by mikedh** [comment]
Oh huh triangle should be able to do this now.. do you have the latest version of `triangle` (`pip install --upgrade triangle`)? Or maybe there's some degeneracy in the polygon, or `triangle` [needs some args](https://rufat.be/triangle/)?

```
import trimesh
import numpy as np

import matplotlib.pyplot as plt
from shapely.geometry import Point

if __name__ == '__main__':

    # create a concave crescent polygon
    polygon = Point([0, 0]).buffer(1.0).difference(Point([.2, 0]).buffer(1.1))

    # triangulate polygon
    v, f = trimesh.creation.triangulate_polygon(polygon)

    # plot the exterior of the polygon
    plt.plot(*polygon.exterior.xy)
    # plot each triangle
    plottable = v[:, :2][np.hstack((f, f[:, :1]))]
    [plt.plot(*p.T) for p in plottable]
```
![crescent](https://user-images.githubusercontent.com/1403074/82682473-4ee77e00-9c1d-11ea-8242-1ee88eca1160.png)

**Comment by FreakTheMighty** [comment]
Thank you @mikedh! I had some success after playing with the parameters, but got clean reliable results by changing the engine: `triangulate(engine='meshpy')`

**Comment by mikedh** [comment]
Glad to hear you got it to work! Few quick followups:

- I actually removed the `engine` option a few months back, as the meshpy route wasn't being unit tested, and `triangle` was both easier to install (I actually just [set up wheels](https://github.com/drufat/triangle/pull/51) for it recently) and appeared to be exactly 2x faster than meshpy (meshpy may be running some operation twice or something).  
- `meshpy` is using the following default options: `pzjqQn`... does triangle just work if you use those options? I currently have the default options set to just `p` but can change it easily
- Could you provide a WKT version of the shapely polygon that sees this issue? It would be great add this to unit tests.

**Comment by FreakTheMighty** [comment]
Ah interesting. I didn't realize I was so far behind on versions. I will need to wind back my code a little to answer your questions. There were two issues though, one was proper triangulation, which I believe was improved when I messed with some options, and the other was that it froze entirely on some shapes.

Pretty sure the scenario where it froze was when the polygon path overlapped with itself.

I will try to get some clean test data. (:P should have done this when I bumped into the problem).

**Comment by FreakTheMighty** [comment]
@mikedh it looks like `pzjqQn` does give the correct results for the above shape. With that out of the way I've been bumping into other triangle related issues. I'm finding certain polygons segfault.

I've got hints that it doesn't like how I've formulated the path, mainly that the way I "close" my path is by feeding `load_path` a list of points, where the first and the last are the same. If I change this last point, I am less likely to get a segfault. This leads me to my question.

What is the right way to indicate that a Path is closed?

**Comment by FreakTheMighty** [comment]
@mikedh for what its worth I ended up switching to [mapbox_earcut_python](https://github.com/skogler/mapbox_earcut_python) for triangulation. I had a number of odd issues with triangle including hanging and segmentation faults.

Additionally, I found that while `triangle` the python wrapper has a permissive license, the underlying C code is restricted to academic use.
