### ISSUE TITLE
Marching cubes: Scaling

### ISSUE THREAD

**Issue by e3dEF** [mikedh/trimesh#845]
Hi, I tried your code from [https://github.com/mikedh/trimesh/issues/791](url)
The resulting mesh is somehow scaled in the wrong way. The scaling depends on the pitch, too.
![grafik](https://user-images.githubusercontent.com/41104642/82687251-5c215e80-9c57-11ea-8c3f-ea4b30e9033c.png)

Best

**Comment by mikedh** [comment]
Ah, looks like pitch wasn't passed when you used the function like that. Thanks for the report!
