### ISSUE TITLE
How to get changed RGB of mesh after adding light to the scene.

### ISSUE THREAD

**Issue by SnehithR** [mikedh/trimesh#846]
I've been trying to generate more data by adding light to the scene. Even after adding light to the scene I observed that rgb of  the mesh hasn't changed, the reason might be that here rendering  is being changed but not the actual rgb of mesh. Is there any way to get the changed rgb of the mesh using trimesh.
TIA

**Comment by mikedh** [comment]
Hey yeah that's a little complicated and definitely not default behavior (adding lights doesn't change the actual mesh color). 

Only easy-ish way I can think of is you could find the vector from each vertex to each light source and find the angle between that vector and the vertex normal (dot product), and then apply some light-dark scaling to the vertex color based on that angle. If you added a ray test you could exclude occluded lights
