### ISSUE TITLE
The normals seems to be flipped when using matrix_to_marching_cubes()

### ISSUE THREAD

**Issue by e4exp** [mikedh/trimesh#847]
I want to display a mesh from a `.mat` file.
When I load the `.mat` file by `scipy.io.loadmat()` and convert it by  `trimesh.voxel.ops.matrix_to_marching_cubes()`, I got strange looking of the mesh by `trimesh.Trimesh.show()` method.

```
import scipy.io as io
import numpy as np
import trimesh

path = "chair_000001965_3.mat"
vox = io.loadmat(path)['instance']
vox = np.pad(vox, (1, 1), 'constant', constant_values=(0, 0))
v = trimesh.voxel.ops.matrix_to_marching_cubes(vox)

#trimesh.repair.fix_normals(v)
#trimesh.repair.fix_inversion(v)
v.show()
```

the result looks like this:
![スクリーンショット 2020-05-25 0 40 35](https://user-images.githubusercontent.com/44970465/82758318-c46f6c00-9e20-11ea-9c51-eb4e2e271d9f.png)

when I save the mesh into `.stl` file and load it again, I can get better result

```
name = 'cube.stl'
v.export(name)
v_stl = trimesh.load(name)
v_stl.show()
```

![スクリーンショット 2020-05-25 0 40 53](https://user-images.githubusercontent.com/44970465/82758346-f41e7400-9e20-11ea-9393-3a92c2e7dfc4.png)

How can I solve this problem?
Thank you.

**Comment by mikedh** [comment]
Yeah the vertex normals are returned from `scikit-image.measure.marching_cubes` ([docs](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.marching_cubes), and when you roundtrip through `stl` it is throwing away the vertex normals (`stl` only includes *face* normals). Basically it's saying the face winding and normals are correct, but the vertex normals from skimage are reversed for whatever reason.

if you discard them with `mesh.vertex_normals = None` trimesh will regenerate them from face normals. 

I checked some sample data quickly, and it looked like the vertex normals were correct in my test data. It may be something to do with the specifics of the matrix, or maybe you have an older version of skimage? `pip install --upgrade scikit-image`

**Comment by e4exp** [comment]
Thank you for quick reply.
sorry, I forgot to mention that it was running on Google Colab.
I tried the same code above on my local macbook, then I got the desirable result.

On Google Colab, I tried your advises, but the result was the same.
Also I tried to use the same versions of packages to my local, but I couldn't get the same result.

versions on my local machine(anaconda3-5.3.1) are as follows:
* numpy==1.15.1
* scikit-image==0.14.0
* scipy==1.1.0
* trimesh==3.6.42

and that of Google Colab:
* numpy-1.18.4
* scikit-image==0.16.2 (upgraded to 0.17.2 later)
* scipy==1.4.1
* trimesh==3.6.42




below is zip file contains `.mat` files I used.
[mat_chairs.zip](https://github.com/mikedh/trimesh/files/4675091/mat_chairs.zip)

**Comment by mikedh** [comment]
Glad it worked locally! I think this is probably an google-colab skimage issue then. `mesh.vertex_normals = None` should work regardless of skimage though?

**Comment by alexcdot** [comment]
Doing this fixed it for me: https://trimsh.org/trimesh.repair.html#trimesh.repair.fix_inversion
