### ISSUE TITLE
Water tight meshes

### ISSUE THREAD

**Issue by jsaisagar** [mikedh/trimesh#852]
Hi all,

Trimesh offers test to whether a mesh is water tight or not. May I know if there is a way to make water tight meshes from non-water tight meshes in trimesh?

Thanks for the help,

**Comment by mikedh** [comment]
Hey, it depends on the mesh a lot, if the mesh is too far gone there isn't much we can do. If it's just single triangle or single quad holes `mesh.fill_holes` should be able to repair it.
