### ISSUE TITLE
Scene.save_image just saves a screenshot of size "resolution"

### ISSUE THREAD

**Issue by wwwslinger** [mikedh/trimesh#853]
I'm trying to save a nicely colored mesh to follow-up with image processing, but it seems trimesh simply saves a screenshot.  How can I just get a 2D image of my mesh?
![t](https://user-images.githubusercontent.com/377442/83221663-41555b00-a12b-11ea-893d-dfea15016a44.png)

Code is in Input cell with the asterisk (*).  Setting "visible=True" just pops up a window and saves a white png.

**Comment by wwwslinger** [comment]
Sorry, input 18 is the asterisk cell (*) since I guess it was processing when the screenshot was taken.

**Comment by mikedh** [comment]
Hey, unfortunately in the past this type of issue has depended a lot on platform details (pyglet, GL drivers, etc). Happy to take PR's fixing specific issues, but your best bet is probably either [rendering in docker using LLVMpipe](https://github.com/mikedh/trimesh/tree/master/examples/dockerRender) or [pyrender](https://github.com/mmatl/pyrender) which goes much more in-depth.

**Comment by wwwslinger** [comment]
Thanks @mikedh, I'll give those a try.
