### ISSUE TITLE
show coordinate axes during visualization of point clouds

### ISSUE THREAD

**Issue by chinmay5** [mikedh/trimesh#854]
I went through the documentation but could not figure out how to exactly show the coordinate axes while visualizing the point clouds. I am trying to see if my boxes are axis-aligned and hence it would be helpful if I could also plot bounding box on the scene similar to what is possible in Meshlab.

**Comment by mikedh** [comment]
Hey, have you tried pressing `a` in the viewer?

**Comment by chinmay5** [comment]
That was really stupid of me. Yes pressing `a` in the viewer does solve the issue. However, since I have your time, can you tell me if it is possible to load my signed distance values (stored as a numpy array) in a Voxel grid and then perform some rotations to it. I think it is easy with the Point Clouds but I could not find something similar with Voxel grids directly.
