### ISSUE TITLE
Ray Intersection on VoxelGrid

### ISSUE THREAD

**Issue by smonikantara** [mikedh/trimesh#863]
Hi,

Is it possible to perform a ray intersection test on a voxelized object? I believe one possible way is to convert the `VoxelGrid` to `Trimesh` object and then perform the ray intersection. However, I am looking to do this directly on the `VoxelGrid` object, if this is possible.

Thanks.

**Comment by mikedh** [comment]
Hey, that's not currently implemented but happy to take PR's!

**Comment by smonikantara** [comment]
Thank you for your reply!
