### ISSUE TITLE
Two sided surfaces

### ISSUE THREAD

**Issue by petavazohi** [mikedh/trimesh#864]
Hello, 
Thank you for the amazing package. 
I have a surface that is not closed and I wanted to face colors to apply to both sides. 
My lack of knowledge in the triangular meshes led me to the following solution, to duplicate the faces and invert the face_normals, so each face will have two normals.

Is there a smarter way of doing this?

Best,
Pedram

**Comment by mikedh** [comment]
I think that's the best way to visualize it, as the backs of faces are usually culled or rendered weirdly. I would probably do something similar with `np.fliplr` so the winding is correct and the normals will be generated automatically:

```
In [1]: import trimesh

In [2]: m = trimesh.creation.random_soup(10)

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(30, 3), faces.shape=(10, 3))>

In [4]: import numpy as np

In [5]: m.faces = np.vstack((m.faces, np.fliplr(m.faces)))

In [6]: m
Out[6]: <trimesh.Trimesh(vertices.shape=(30, 3), faces.shape=(20, 3))>

```

**Comment by petavazohi** [comment]
Thank you
