### ISSUE TITLE
Color / texture transfert

### ISSUE THREAD

**Issue by pvnieo** [mikedh/trimesh#865]
Hi, Thank you for the awesome library!
Actually, I'm not reporting a bug, but I'm asking for help.

I'm working on a shape matching problem, where I have two meshes, and I want to assign to each vertex in the first mesh, a vertex in the second meshes. A way to visualize if the correspondances are correct is to transfert color (or texture) from one shape to the other. (see example below)
![image](https://user-images.githubusercontent.com/22404728/83973402-6e053180-a8e6-11ea-90b6-2f08444b1899.png)
![image](https://user-images.githubusercontent.com/22404728/83973407-73fb1280-a8e6-11ea-8b22-00053fa1b9a8.png)

However, actually all this operation are done in matlab, and I want to perform this in python. Is it possible to do this in trimesh, I read the documentation, and I've done some tests, but I didn't succed.

I've created a small dataset to do some tests with:
https://drive.google.com/drive/folders/1ij6NdB1WuCnTXyK1SIolLSYIkfIMd6n2?usp=sharing

This link contains some `.off` files, which are shapes, a texture image that I want to apply to one shape and transfer it to another, and a file X_Y.mat which is a correspondance from X to Y. this file contains an array that has the shape: N x 1, where N is the number of vertices of X, and the value at row i is the vertex in Y to which the vertex i should correspond. To read the correspondance:

```
import scipy.io as sio
m1_m2 = sio.loadmat("067_071.mat")["matches_gt"] - 1
```
The - 1 is because indices starts at 1 (matlab style).

For the surreal shapes `surreal_0000.off` and `surreal_0001.off`, they have the same number of vertices, and we don't need a map ground truth like before, because the vertex 1 in shape 1 is mapped to vertex 1 in shape 2, vertex 2 is mapped to vertex 2, and so one.

Can you suggest a method to do this?
Thank you in advance.

**Comment by mikedh** [comment]
Hey, you could try copying the material and then query for the nearest UV. You could also do a nicer thing using `mesh.proximity.on_surface` to find the closest on-surface point and triangle index, and then weight the three UV coordinates using barycentric coordinates from ` trimesh.triangles.points_to_barycentric`. Simple example:


```
import trimesh
import numpy as np

if __name__ == '__main__':

    # load a textured model
    m = trimesh.load('models/fuze.obj')

    # create an example mesh which is just the bounding sphere of the model
    s = m.bounding_sphere.copy()

    # use the same material as the fuze bottle
    s.visual.material = m.visual.material

    # query the nearest vertex index from original mesh
    v_idx = m.kdtree.query(s.vertices.copy())[1]

    # set the UV coordinates on the new mesh to the UV
    # coordinates of the nearest point from the original
    s.visual.uv = m.visual.uv[v_idx]
```
Produces something like this:

![fuzeball](https://user-images.githubusercontent.com/1403074/84053609-27641580-a980-11ea-9ebd-e8a1e217924f.png)
