### ISSUE TITLE
is_convex returning wrong result?

### ISSUE THREAD

**Issue by clemense** [mikedh/trimesh#867]
Hi,
The following code:
```
x = trimesh.load('is_convex_example.obj')
print(x.is_convex)
```
outputs `true` although the mesh is not convex, it looks like this:
![Screenshot from 2020-06-08 12-04-39](https://user-images.githubusercontent.com/1800546/84070287-c1c45900-a980-11ea-834c-e475dac955d6.png)

The mesh file is attached.
Is this a problem of this particular mesh or a trimesh bug?

Thank you!

[is_convex_example.zip](https://github.com/mikedh/trimesh/files/4748040/is_convex_example.zip)

**Comment by mikedh** [comment]
Oh interesting, `mesh.is_convex` is checking every pair of *adjacent* faces to see if they're locally convex. That mesh isn't watertight so every adjacent pair of faces is indeed locally convex, but the overall mesh is not. I guess the fix here is to make `mesh.is_convex` exit early with False if the mesh isn't watertight?

Here's the non-watertight tessellation at the corner:
![convex](https://user-images.githubusercontent.com/1403074/84098589-a33c7d00-a9d5-11ea-92c3-6d7da700b77e.png)
