### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'resolution'?

### ISSUE THREAD

**Issue by vivekdhameliya** [mikedh/trimesh#868]
Hello, I am trying to create multiple virtual cameras with different viewpoints to create 12 multiview of 3D geometry. But I am stuck with an error that `AttributeError: 'NoneType' object has no attribute 'resolution'.` And after debugging the following code I see the error that  `camera={NoneType}None` .What should I do to rectify this error? And Did I implemented the correct method to create viewpoints to capture multiple 2D views of the 3D part?

    mesh = trimesh.load('C:/trainin/ls/A213/6/2/A20122_0012.001.stl')

    # set the mesh face colors to white
    mesh.visual.face_colors = [255, 255, 255, 255]
    scene = trimesh.Scene(mesh)

    # set the camera resolution
    scene.camera.resolution = (320, 320)
    # set the camera transform to look at the mesh
    scene.camera_transform = scene.camera.look_at(
        points=mesh.vertices,
        rotation=trimesh.transformations.euler_matrix(np.pi / 3, 0, np.pi / 5))

    # write a PNG of the render
    with open(os.path.join(output_directory, 'outlined.PNG'), 'wb') as f:
        f.write(scene.save_image())

**Comment by mikedh** [comment]
Hey, not sure what's going on. This minimal example runs with no errors for me:
```
import trimesh
import numpy as np

if __name__ == '__main__':

    mesh = trimesh.creation.icosphere()

    scene = mesh.scene()
    # set the camera resolution
    scene.camera.resolution = (320, 320)
    # set the camera transform to look at the mesh
    scene.camera_transform = scene.camera.look_at(
        points=mesh.vertices,
        rotation=trimesh.transformations.euler_matrix(np.pi / 3, 0, np.pi / 5))

    scene.show()
```
