### ISSUE TITLE
trimesh.voxel.transforms.Transform.pitch returns None

### ISSUE THREAD

**Issue by jkrenzer** [mikedh/trimesh#869]
Hi!

Trying to get the pitch of my voxelgrid, I always get none even though the pitch's effect can be clearly seen in the bounds of the VoxelGrid instance. I did not have a look at the decorator, but might it be we are simply missing a return statement in the property-member-function for this to work?

https://github.com/mikedh/trimesh/blob/82aa7484fcfcf9be4160bb91b2f84ace33aa1204/trimesh/voxel/transforms.py#L120-L130

Kind regards,

Jörn

**Comment by mikedh** [comment]
Haha yeah it *does* seem like that function should be returning something. Test and fix added in #872. Thanks for the report!
