### ISSUE TITLE
bounding box:extents vs primitive extents

### ISSUE THREAD

**Issue by piango** [mikedh/trimesh#871]
Hello

I am new to trimesh and also in general to mesh analysis.
I am trying to find how elongated an object(my mesh) is.
To do this, preliminary, I have doing a bounding_box_oriented and trying to measure the ratio between the Length:Width and Length:Height ratios.

I find that the:
mesh.bounding_box_oriented.extents
mesh.bounding_box_oriented.primitive.extents
-->gives different l,w,h

But for a test I also did:
mesh.bounding_box.extents
mesh.bounding_box.primitive.extents
-->these two gives the same results

Any advice or brief explanation on which one is better or wrong?

Any help is appreciated.

Thank you

**Comment by piango** [comment]
Hey

Thank you for the speedy reply
And for your help

:)

**Comment by csyhping** [comment]
> Hey, `mesh.extents` is always the size of the axis-aligned bounds, where `mesh.primitive.extents` is the pre-transform extents. For the oriented bounding box it would always be equal or smaller to the axis aligned bounds.

Hi @mikedh , I met this problem today and I'm glad to find your answer. as you said, `mesh.extents is always the size of the axis-aligned bounds`, so if I use `mesh.bounding_box_oriented.extents`, it actually measures the aabb of the obb? Is that correct?
