### ISSUE TITLE
Initial orientation seems off

### ISSUE THREAD

**Issue by wwwslinger** [mikedh/trimesh#879]
Hi Mike,
I'm thoroughly enjoying working with your library.  Awesome work!

I'm loading a mesh that should have a clear vertical orientation, but it loads up off by 30-40 degrees from the y axis.  Is this something that trimesh initially tries to establish, or more likely something with my scan's setup?  I've tried `process=False` with no affect.  I can do an estimated transformation to correct it, but I need to automate that across several scans and I'm not convinced the offset is consistently the same. I'm doing a lot of programmatic work after loading that relies on the proper alignment with the vertical, so any help is appreciated.

Initial load:
![initial_load](https://user-images.githubusercontent.com/377442/85215446-74a39800-b32d-11ea-9ad7-1bf3b0237731.png)

Proper orientation:
![oriented](https://user-images.githubusercontent.com/377442/85215449-7d946980-b32d-11ea-8fcc-945dfb457b83.png)

**Comment by mikedh** [comment]
Hey, on-load it shouldn't be moving vertices. When you are talking about orientation are you looking at the visual orientation or the actual position of the mesh? The camera transform in the viewer is arbitrary unless you set it. 

If the mesh represents a volume (watertight/winding correct, `mesh.is_volume`) you can look at `mesh.center_mass` and `mesh.principal_inertia_vectors`. If it isn't reliably watertight you can look at `mesh.bounding_box_oriented.primitive.transform` for a base pose.

**Comment by wwwslinger** [comment]
Thanks, Mike.  It is not a volume, and I'm only looking at the visual since I'm not clear how to understand the orientation without it.  Using `mesh.bounding_box_oriented.primitive.transform` I get:
```
TrackedArray([[ 2.17103123e-02, -9.57773544e-01,  2.86702808e-01,
                3.67666415e+01],
              [ 2.19028792e-02,  2.87157225e-01,  9.57633015e-01,
               -5.66447512e+00],
              [-9.99524350e-01, -1.45108949e-02,  2.72122713e-02,
                1.30506074e+01],
              [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
                1.00000000e+00]])
```
Viewing that box as an outline gives me the same offset from vertical:
![oriented_bb](https://user-images.githubusercontent.com/377442/85234915-c7309300-b3c5-11ea-8c95-41840860233e.png)

Applying the transform gives a different view of a side of the surface.

How do I utilize that base pose to get a view of the mesh that isn't angled?

**Comment by wwwslinger** [comment]
Not sure if this is the best way, but I first get the angle from vertical, then I get compose a rotation matrix about z with that angle, then I apply the transform:
```
# get the bounding box Path3D
bb = mesh.bounding_box_oriented.as_outline()
# get points to compare vectors from min y point and max x point
p1 = list(bb.vertices[np.argmin(bb.vertices[:,1])][0:2])
p2 = list(bb.vertices[np.argmax(bb.vertices[:,0])][0:2])
n2 = []
n2.append(p1[0])
n2.append(np.max(bb.vertices[:,1]))
# get the angle between the vectors, which should be the angle to "correct" for
theta = trimesh.transformations.angle_between_vectors([p1,p2], [p1,n2], axis=1)[1]
# get a rotation matrix about z for that angle
rmtx = trimesh.transformations.compose_matrix(angles=[0,0, theta])
print(rmtx)
# apply the rotation
mesh.apply_transform(rmtx)
```
which provides the orientation I was looking for.  Is there a faster/better way?

Also, I'm wondering if I actually needed to do this, since I still don't understand if my mesh itself has this initial pose.  I assume your comment about getting base pose means it did.

**Comment by mikedh** [comment]
Yeah the mesh is almost certainly coming in with that pose although it's always good to verify things like that (you could compare the AABB when loaded with meshlab). One thing that's pretty easy to do is you could also move the mesh to the origin with the OBB inverse:

`mesh.apply_transform(np.linalg.inv(mesh.bounding_box_oriented.primitive.transform))`

If your application is visual I might also check out [pyrender](https://github.com/mmatl/pyrender), which is much better at producing accurate renders.

**Comment by wwwslinger** [comment]
I actually had to do both -- ORB inverse followed by angle adjustment.  Thanks for the help!
