### ISSUE TITLE
Submesh from vertex IDs?

### ISSUE THREAD

**Issue by oliverstefanov** [mikedh/trimesh#881]
Hi,
How can you easily get a submesh from a set of vertex IDs that are contiguous ?
To use the submesh function I need the face ids. 
Im trying to use mesh.vertex_faces over the whole mesh (can't you select specific vertices?) and then find the face IDs that correspond to each vertex ID, but that is a bit cumbersome. 
I figure there must be an easy way to do this in a few lines of code but i can't figure it out so far. Any help appreciated, thanks!

**Comment by mikedh** [comment]
Hey, I would use a simple boolean mask. Depending on the behavior you want you could populate it with either `.any(axis=1)` or `.all(axis=1):

```
In [1]: import trimesh

In [2]: m = trimesh.creation.icosphere()

In [3]: vertex_id = [0,2,3,4,5]

In [4]: import numpy as np

In [5]: mask = np.zeros(len(m.vertices), dtype=np.bool)

In [6]: mask[vertex_id] = True

In [7]: faces = mask[m.faces].any(axis=1)

In [8]: faces
Out[8]: array([ True, False, False, ..., False, False, False])

In [9]: faces.shape
Out[9]: (1280,)

In [10]: m.faces.shape
Out[10]: (1280, 3)

In [11]: faces.sum()
Out[11]: 25

In [12]: submesh = m.submesh([faces])

In [13]: submesh
Out[13]: 
array([<trimesh.Trimesh(vertices.shape=(30, 3), faces.shape=(25, 3))>],
      dtype=object)

In [14]: submesh[0].show()
Out[14]: SceneViewer(width=1800, height=1350)

```

**Comment by oliverstefanov** [comment]
OK Mike this works, thanks a lot!
