### ISSUE TITLE
mesh_multiplane not generating face_index properly

### ISSUE THREAD

**Issue by lulyu** [mikedh/trimesh#882]
Hi all, first off thank you so much for providing and maintaining trimesh. While using the package for a project of mine, I came across the issue that the face_index returned by mesh_multiplane is not m by n in shape, and does not seem to contain the indexes properly.

So I did a bit digging in the code and found this possible bug here

https://github.com/mikedh/trimesh/blob/master/trimesh/intersections.py#L276

Instead of append index returned [here ](https://github.com/mikedh/trimesh/blob/master/trimesh/intersections.py#L250), it appends face_index to itself.

Let me know if this indeed looks like the problem to you, I'd be happy to create a PR for it.

**Comment by mikedh** [comment]
Thanks for the report! Should be fixed in #878

**Comment by lulyu** [comment]
Great! Thanks a lot @mikedh
