### ISSUE TITLE
backface culling after raycasting

### ISSUE THREAD

**Issue by ttsesm** [mikedh/trimesh#883]
Hi Mike,

I would like to apply backface culling after the raycasting procedure so that to eliminated the instances of the intersection points with faces intersected from the back. Is there any example available which I could have a look.

**Comment by mikedh** [comment]
You could do it by looking at the dot product of the face normals and the vector:

```
In [1]: import trimesh

In [2]: import numpy as np

In [3]: vector = [0,0,1]

In [4]: m = trimesh.creation.icosphere()

In [5]: dots = np.dot(m.face_normals, vector)

In [6]: front_facing = dots > 1e-5

In [7]: front_facing.shape
Out[7]: (1280,)

In [9]: front_facing.sum()
Out[9]: 624

In [10]: m.update_faces(front_facing)
```

**Comment by ttsesm** [comment]
Hi @mikedh thanks for the example, one issue that I see with your approach is that it does not take into account the ray origin in your case you consider that the rays coming from somewhere outside the icosphere with direction [0,0,1]. However, for example if the ray was cast from [0,0,0] with direction [0,0,1] then all faces should have been marked as backfaced since the ray is coming from the inner of the icosphere as illustrated in the figure below:

![image](https://user-images.githubusercontent.com/10189018/85782448-e19ca080-b726-11ea-90d4-d10e31e8b91e.png)
 
also I think in your example you have a typo where the `front_facing = dots > 1e-5` should be `front_facing = dots < 1e-5`.

**Comment by ttsesm** [comment]
actually a more correct way wouldn't be the following:

```
startpoint = np.array([0,0,-1.5]) # start point of ray
directional_dist= startpoint - m.triangles_center
dots = np.einsum("ij,ij->i", directional_dist, m.face_normals) / np.linalg.norm(directional_dist, axis=1)
front_facing = dots > 0
```

![image](https://user-images.githubusercontent.com/10189018/85797923-d3597f00-b73c-11ea-8b60-87f081cea4f5.png)


based on this http://www.leadinglesson.com/component-along-a-vector
