### ISSUE TITLE
Blender boolean returns wrong mesh

### ISSUE THREAD

**Issue by schlegelp** [mikedh/trimesh#887]
Hi! Great library, love it.

I think I found an error in the [template](https://github.com/mikedh/trimesh/blob/18f7bd77a94f5b7cb45f9c9fbc8a96e5716666c4/trimesh/resources/blender.py.template) for Blender boolean operations:

In the main part, objects are imported such that the `mesh` we operate on will be the first in the scene:
```Python
for filename in mesh_pre[::-1]:
    bpy.ops.import_mesh.stl(filepath=os.path.abspath(filename))

mesh = bpy.context.scene.objects[0]
```

But then during the `delete_nonresult()` clean-up, we remove everything but the **last** object in the scene:
```Python
        ob = objects[-1]
        ob.select_set(False)
        for other in objects[:-1]:
            other.select_set(True)
        bpy.ops.object.delete()
        objects[0].select_set(True)
```

Hope I got this right, still only on the first coffee this morning.

Best,
Philipp

Edit: Tested this with Blender `2.80` and `2.82`, and trimesh `3.7.4`

**Comment by schlegelp** [comment]
Another thing that came up:

`bpy.ops.object.modifier_apply(modifier=mod.name)` only works if the active object is the one with the modifier. For some reason that's not the case in my hands which in turn means the modifier not applied before clean-up.

Adding these lines should make sure we are operating on the correct mesh:
```Python
mesh = bpy.context.scene.objects[0]
try:
    # earlier than blender <2.8
    bpy.context.scene.objects.active = mesh
except AttributeError:
    # blender 2.8 changed this
    bpy.context.view_layer.objects.active = mesh
```

**Comment by schlegelp** [comment]
Sorry, this is turning into a incremental thread.

I believe there is something funny going on where, rather confusingly, the content is the same but the order of objects in `bpy.data.objects` and `bpy.context.scene.objects` can be different depending on whether you are running a script or are in an interactive session. Tested with Blender 2.79 and 2.8x

Bottom line: `bpy.data.objects` appears to be stable in my hands and preserve the order such that the first object is always the first one that was imported. 

This is what I ended up with (note inline comments indicating changes):
```Python
import os

def delete_nonresult(bpy):
    objects = bpy.data.objects  # use data.objects instead of context.scene.objects
    if len(objects) <= 1:
        return

    try:
        # earlier than blender <2.8
        objects[0].select = False  # keep the first object
        for other in objects[1:]:  # remove all other objects
            other.select = True
        bpy.ops.object.delete()
        objects[0].select = True
    except AttributeError:
        # blender 2.8 changed this
        objects[0].select_set(False)
        for other in objects[1:]:
            other.select_set(True)
        bpy.ops.object.delete()
        objects[0].select_set(True)


import bpy
# clear scene of default box
bpy.ops.wm.read_homefile() 
try:
    bpy.ops.object.mode_set(mode='OBJECT')
except BaseException:
    pass
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=True)

# get temporary files from templated locations
mesh_pre = $MESH_PRE
mesh_post = os.path.abspath(r'$MESH_POST')

for filename in mesh_pre:  # use data.objects instead of context.scene.objects
    bpy.ops.import_mesh.stl(filepath=os.path.abspath(filename))    

mesh = bpy.data.objects[0]
# Make sure mesh is the active object
try:
    # earlier than blender <2.8
    bpy.context.scene.objects.active = mesh
except AttributeError:
    # blender 2.8 changed this
    bpy.context.view_layer.objects.active = mesh

for other in bpy.data.objects[1:]:
    # add boolean modifier
    mod = mesh.modifiers.new('boolean', 'BOOLEAN')
    mod.object = other
    mod.operation = '$OPERATION'
    bpy.ops.object.modifier_apply(modifier=mod.name)  # used mod.name instead of hard-coded "boolean"

delete_nonresult(bpy)
bpy.ops.export_mesh.stl(
    filepath=mesh_post,
    use_mesh_modifiers=True)
```

**Comment by mikedh** [comment]
No worries thanks for the report and the fix!! Your updated snipped fixed `test_boolean` for me as well on both Blender 2.78 and 2.83, thanks! I'll PR and release it shortly.
