### ISSUE TITLE
Normal 2D plan of a mesh.

### ISSUE THREAD

**Issue by elrapha** [mikedh/trimesh#888]
What will be the best way to get the 2D plan of a mesh viewing from above?
I could use the cross section of the mesh at different heights....but this seems like overkill since i really just want the plan of the oriented bounding box, which should be a less complicated mesh. 
Is there a way to project the mesh onto the xy plane and get the resulting polygon?

**Comment by mikedh** [comment]
Yeah definitely, you could just apply the inverse OBB transform (i.e. something like `mesh.apply_transform(np.linalg.inv(mesh.bounding_box_oriented.primitive.transform)`) then project to the plane... the challenge is the projection will be very grody without a bunch of processing. The easiest thing to do is just project vertices to the plane then get the 2D convex hull. If you need non-convex features you have to do a bunch more work to get a nice polygon.

**Comment by mikedh** [comment]
This may also be what you want: https://github.com/mikedh/trimesh/issues/860
