### ISSUE TITLE
Deprecation warning on ndarray

### ISSUE THREAD

**Issue by yuvadm** [mikedh/trimesh#889]
Running some trimesh code on Python 3.6 and Numpy 1.19, the following deprecation warning appears:

```
/home/user/.local/share/virtualenvs/proj/lib/python3.6/site-packages/trimesh/graph.py:406: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.
If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```

**Comment by mikedh** [comment]
I just started seeing these yesterday as well.. numpy must have released or something. I'll see if there's a good alternative, thanks for the report!

**Comment by mikedh** [comment]
I *think* I got all of these... please re-open and post the line numbers if anyone still sees these on the latest trimesh :smile:

**Comment by azixMcAze** [comment]
Hi, I had a warning when loading a ply file with trimesh 3.8.19:
```
lib\site-packages\trimesh\exchange\ply.py:635: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 
'dtype=object' when creating the ndarray
  element_data[name] = np.array(element_data[name]).squeeze()
```

**Comment by aTamaz** [comment]
> I _think_ I got all of these... please re-open and post the line numbers if anyone still sees these on the latest trimesh smile

Hi @mikedh , I'm also getting a warning in (current) version 3.9.3 (cannot reopen this issue):

`<virtual_env>/lib/python3.7/site-packages/trimesh/exchange/ply.py:646: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  element_data[name] = np.array(element_data[name]).squeeze()
`

Seems to be the same line as in the comment above, it just moved further down.
