### ISSUE TITLE
Finding transformations for all faces against the z-axis

### ISSUE THREAD

**Issue by 1234shel** [mikedh/trimesh#892]
I recently came across the stable poses function which outputs transformation which allow for certain faces to be placed flat against the z-axis. I am looking for something similar but instead of just a few selected faces or poses (as done in stable poses function), I want a list of all faces and their transformations which will allow them to be placed flat against the z-axis. Is there any in-built function for this? Alternatively are there any simple ways to compute this?

**Comment by mikedh** [comment]
Hey, I think you may just want the faces of the [convex hull](https://en.wikipedia.org/wiki/Convex_hull) (`mesh.convex_hull.faces`), which generally has that property.
