### ISSUE TITLE
trimesh.viewer.windowed: geometry_hash does not take color of path into account

### ISSUE THREAD

**Issue by lericson** [mikedh/trimesh#897]
The `geometry_hash` function of the `trimesh.viewer.windowed` module does not hash the colors of path entities, this means that changing colors of path entities does not get reflected in the viewer.

The `md5` method of `trimesh.path.path.Path` also does not include the colors in its hash.

(As an aside, why use MD5 for this? It was designed to be cryptographically strong. There are surely better ways to do change detection.)

I guess the proper way to fix this is to let path entities have something `visual`-like.

**Comment by mikedh** [comment]
Thanks for the report! Yeah when trimesh first started it was 100% focused on manufacturing stuff (i.e. merge all vertices immediatly, no visual properties) and this is legacy from that. 

MD5 is there similar reasons, it could definitely be replaced with `trimesh.caching.crc32`, which is either `zlib.adler32 or `zlib.crc32` depending on which is faster on the current platform. 

Happy to take PR's switching out MD5 for `crc32` and adding colors to the hashes! If not no worries, I'll add it to the backlog :smile:

**Comment by lericson** [comment]
There is one entity that will still exhibit this issue: the `Text` objects.

**Comment by lericson** [comment]
From what I can gather, Text entities don't actually work in the viewer anyway. Is that correct?
