### ISSUE TITLE
Projected area calculation

### ISSUE THREAD

**Issue by titulebolide** [mikedh/trimesh#898]
Hello,

This is not an issue, but a suggestion for a unseen functionnality that could be interesting in trimesh.
It is the possibility to determine the projected area of a mesh on a certain plane; given its normal vector.
Here is the snippet I finally made to do so, using shapely :

```python
import trimesh
import copy
import shapely.ops
import shapely.geometry
import math

def projected_area(mesh, normal):
    normal = np.array(normal)
    normal = normal/np.linalg.norm(normal)
    m = copy.deepcopy(mesh)
    dir_rot = normal + np.array([1,0,0])
    if np.linalg.norm(dir_rot) < 1e-6:
        dir_rot = np.array([1,0,0])
    m.apply_transform(trimesh.transformations.rotation_matrix(math.pi, dir_rot))
    m.apply_transform(trimesh.transformations.projection_matrix((0,0,0),(1,0,0)))
    polygons = [
        shapely.geometry.Polygon(triangle[:,1:])
        for index_triangle, triangle in enumerate(m.triangles)
        if np.linalg.norm(m.face_normals[index_triangle] - np.array([1,0,0])) < 1e-6
    ]
    poly_merged = shapely.ops.unary_union(polygons)
    return poly_merged.area
```

I think it would be useful for those who like me are trying to calculate atmospherical drag coefficient over given meshes.

Also; thanks for your great work!

Best

**Comment by mikedh** [comment]
Yeah that would be cool! My main concern is that I've implemented similar functions and `ops.unary_union` can be *super* slow if used on every triangle like that. When I implemented it IIRC:

- remove back and on-edge faces with a dot product
- find patches of faces which are locally convex using `mesh.face_adjacency_convex` and `trimesh.graph.connected_components` and get the outline in 3D
- project all of those outlines onto the plane and then run `unary_union` on those.

It still explodes sometimes hahah.

**Comment by titulebolide** [comment]
I did implemented that, bar the patches of faces. Actually I project the mesh first and I keep only the faces that have the same normal that the projection plane, removing the side and back faces.
Too bad it explodes sometimes, but maybe it would be an interesting feature nonetheless? It would be worthy indicating it int the doc and trying to indentify the cases wher it explodes.

**Comment by mikedh** [comment]
I merged in a decent-performing implementation of the patch strategy, you can get area with:

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/rabbit.obj')
faces have mixed data, using slow fallback!

In [3]: trimesh.path.polygons.projected(m, normal=[1,1,0]).area
Out[3]: 6.651866579546423
```

Let me know if you see issues! For basic rigid geometry it performs quite well, but I could imagine issues odd topology.
