### ISSUE TITLE
convexify example

### ISSUE THREAD

**Issue by AlexLee** [mikedh/trimesh#9]
with the convexify example, i get an error message stating that "np float object does not support show method."

I'll post the code and the exact error message later. I am using a different stl file than box.stl 

convex_combined = np.sum(meshes_convex)
convex_combined.show()

**Comment by Marviel** [comment]
Can you post the .stl file you're using?

**Comment by mikedh** [comment]
Ah, it's because the arguments have changed slightly. I'll add the examples to the unit tests tonight to avoid wrong examples in the future. In the meantime if you replace two lines in that file with:

    meshes = mesh.split(only_watertight=False)

    # the convex hull of every component
    meshes_convex = [i.convex_hull for i in meshes]

**Comment by mikedh** [comment]
Fixed in https://github.com/mikedh/trimesh/commit/ab82b42932437f222d58610fded14b73daf819f3

**Comment by AlexLee** [comment]
i believe i did not install all of the dependencies, (specifically rtree). @Marviel I'll see if I can post the stl file but it is rather large (500mb and 5 million facets!)
