### ISSUE TITLE
IndexError: index out of bounds

### ISSUE THREAD

**Issue by w00zie** [mikedh/trimesh#902]
Hi,

first of all: thank you for your work!
I encountered the *index out of bounds* error while trying to load a mesh. I was provided a dataset with vertices and faces and I wanted to use `trimesh` to load, inspect and export them.

I loaded a vertices array, let's say `vert.npy`

```
vertices = np.load('vert.npy')
```

and the faces array

```
faces = np.load('faces.npy')
```

Their shapes are `(6704, 3)` and `(13279, 3)`, respectively. Executing
```
mesh = trimesh.Trimes(vertices=vertices, faces=faces)
```

leads to

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-3c54ecbf650d> in <module>
----> 1 mesh = trimesh.Trimesh(vertices=vertices, faces=faces)

~/cg3d/lib/python3.6/site-packages/trimesh/base.py in __init__(self, vertices, faces, face_normals, vertex_normals, face_colors, vertex_colors, face_attributes, vertex_attributes, metadata, process, validate, use_embree, initial_cache, visual, **kwargs)
    190         # if validate, will remove degenerate and duplicate faces
    191         if process or validate:
--> 192             self.process(validate=validate, **kwargs)
    193 
    194         # save reference to kwargs

~/cg3d/lib/python3.6/site-packages/trimesh/base.py in process(self, validate, **kwargs)
    224         with self._cache:
    225             self.remove_infinite_values()
--> 226             self.merge_vertices(**kwargs)
    227             # if we're cleaning remove duplicate
    228             # and degenerate faces

~/cg3d/lib/python3.6/site-packages/trimesh/base.py in merge_vertices(self, **kwargs)
   1113             log.warning(
   1114                 'merge_vertices depreciation: `not textured`->`merge_tex`')
-> 1115         grouping.merge_vertices(self, **kwargs)
   1116 
   1117     def update_vertices(self, mask, inverse=None):

~/cg3d/lib/python3.6/site-packages/trimesh/grouping.py in merge_vertices(mesh, merge_tex, merge_norm, digits_vertex, digits_norm, digits_uv, **kwargs)
     57     if hasattr(mesh, 'faces') and len(mesh.faces) > 0:
     58         referenced = np.zeros(len(mesh.vertices), dtype=np.bool)
---> 59         referenced[mesh.faces] = True
     60     else:
     61         # this is used for geometry without faces

IndexError: index 6704 is out of bounds for axis 0 with size 6704
```

If I load the file without processing, i.e.

```
mesh = trimesh.Trimes(vertices=vertices, faces=faces, process=False)
```

I am able to load the mesh but if I check ```mesh.is_watertight``` I get `False`.

Do you think that this problem comes from the data or it is caused by some bug in the code (it might be the first option).
I'll be happy to share with you these two numpy arrays but they come from a closed-source dataset and I cannot post them here.

Thank you!

**Comment by adamhall** [comment]
@w00zie, I'm having a similar issue. What was the issue with your files? It's odd because I was using trimesh 3.5 and it worked fine. When I updated to 3.8, I started getting this error.

**Comment by w00zie** [comment]
@adamhall very sorry for the late reply (I didn't see the notification). 

My issue was simple: my `faces` numpy array was coming from a matlab array and so every value contained in it was an index starting from 1 and not from 0. Subtracting one from every element of the array solved the issue.
Hope this could be of any help, excuse me again for being so late...
