### ISSUE TITLE
Applying texture from image to mesh

### ISSUE THREAD

**Issue by AlexDima17** [mikedh/trimesh#903]
Hello and thank you for the library! 
I 'm quite new to using trimesh (and Python in general), so please forgive my lack of knowledge.. I am creating some mesh objects through an adversarial network and I would like to apply custom textures to them. For now I am trying to do this with built-in objects, but I dont seem to get it right. So I load an image with PIL, create a SimpleMaterial with it and set the material to the mesh material. But all I get is a dark grey capsule, what am I doing wrong?

```
image = Image.open('test_textures/tile.jpg')
img = image.resize((40, 60))
mat = trimesh.visual.material.SimpleMaterial(image=img, diffuse = None, 
                                            ambient= None, specular=None, glossiness=None)
capsule = trimesh.creation.capsule(10,20)
capsule.visual.material = mat
capsule.show()
```

**Comment by mikedh** [comment]
Hey, I think you also need to set UV coordinates for each vertex (i.e. `mesh.visual.uv = np.zeros((len(mesh.vertices), 2)` and then put something in there)

**Comment by AlexDima17** [comment]
Thank you, I will try that!
