### ISSUE TITLE
Load PLY with vertex texture coordinates 

### ISSUE THREAD

**Issue by michele-arrival** [mikedh/trimesh#906]
Is there an option to load PLY files taking into account texture coordinates?

I'm working on using a blender interface MeshScript to run Blender's smart_unwrap operator, however when reading back the mesh, the texture coordinates are ignored.

The vertex entries in the ply file look like this:

```
ply
format ascii 1.0
comment Created by Blender 2.83.1 - www.blender.org, source file: ''
element vertex 133535
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float s
property float t
element face 53144
property list uchar uint vertex_indices
end_header
-3.233006 -26.805738 2.667741 -0.156436 -0.987676 0.004884 0.903415 0.209721
-5.208821 -26.492792 2.667808 -0.156436 -0.987676 0.004884 0.903415 0.205169
-5.059295 -26.521755 1.600000 -0.156436 -0.987676 0.004884 0.906191 0.205522
-2.236750 -26.907190 4.400000 -0.105654 -0.994400 0.002526 0.898912 0.211923
```

**Comment by mikedh** [comment]
Hey, looks like blender is using a different UV format which should be pretty easy to support. Trimesh loads `models/fuze.ply`, which was exported from meshlab and has a header that looks like:
```
ply
format binary_little_endian 1.0
comment VCGLIB generated
comment TextureFile fuze_uv.jpg
element vertex 502
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 1000
property list uchar int vertex_indices
property list uchar float texcoord
property uchar red
property uchar green
property uchar blue
property uchar alpha
end_header
```

It looks like blender is exporting them as the vertex properties `s` and `t`, which seems straightforward. But I don't see where/how blender is referencing the image ( `TextureFile`)?

**Comment by michele-arrival** [comment]
When I wrote this message i wondered why this way of expressing u/v wasn't supported. In the meanwhile I searched everywhere for a spec for this, and i realized then it must be an unusual format.

It's ok then, I'm modifying the trimesh ply importer for my needs, and have encountered other problems: i.e. the blender ply exporter modifies the vertex set to a much bigger one (i can only guess it has duplicates).

There is no image being exported at present. The exporter is not complaining, and also it seems the trimesh's obj importer is fine to import a mesh with uv coordinates but no image, so it seemed ok to me to work with this assumption.

**Comment by michele-arrival** [comment]
You can close this issue then, unless the uv unwrapping is something that would be useful to have as a mainline feature, in which case I'm happy to share the progress so far.

**Comment by michele-arrival** [comment]
as it turns out the ply format is not necessary. It was the only other option in the blender **mesh** exporters, other than stl which doesn't support uv coordinates so it would be usefule - however there are several **scene** exporters that work just fine.

For the record, the mesh unwrapping also works very well, unfortunately it changes the number of vertices when reimported as obj (my best guess is the texture wrapping around), so an "unwrapped" function would return a totally (but very much equivalent) scene/mesh.

**Comment by mikedh** [comment]
No worries, UV unwrapping would be cool to have and PR's super welcome! Are you doing it with a blender interface or implementing from scratch?

**Comment by michele-arrival** [comment]
I'm doing a blender interface. All i could find on the subject is relying on blender. Maybe i haven't looked in the right places, but I haven't bumped into any well known formulation. If it turned out that there is one, then I would certainly try and write it into numpy code.
