### ISSUE TITLE
How can I get color from texture image and show?

### ISSUE THREAD

**Issue by weileehh** [mikedh/trimesh#908]
Hi, I face a problem when show colored trimesh object:

I first construct an object mesh:
    m = load_mesh(source_img, target_mesh, target_scale, texture_mapping, out_path)
and m has set properties:  m.v, m.f, m.vt, m.ft, m.set_texture_image(). so when I call m.show(), I can get a colored view.

Then I build a trimesh object:
    tri_mesh = trimesh.Trimesh(vertices=m.v, faces=m.f)

So how can I get vertex colors and face colors to get a colored trimesh view?

Thanks!

**Comment by mikedh** [comment]
Hey, not sure what library this is using: `m = load_mesh(source_img, target_mesh, target_scale, texture_mapping, out_path)`

But if you pass vertex or face colors to the trimesh loader it will use and display them:
`tri_mesh = trimesh.Trimesh(vertices=m.v, faces=m.f, vertex_colors=m.vc)`
