### ISSUE TITLE
Center of mass lies outside of convex hull

### ISSUE THREAD

**Issue by michele-arrival** [mikedh/trimesh#909]
In some cases the centre of mass is calculated outside of the convex hull. As a consequence a lot of stuff fails, e.g. the stable pose calculation loops infinitely.

Is it normal?

![image](https://user-images.githubusercontent.com/54891577/86904459-a7f56d80-c108-11ea-8aae-6fe1bce9b29d.png)![image](https://user-images.githubusercontent.com/54891577/86904473-aaf05e00-c108-11ea-89e1-dbdfc2f70792.png)

```
import trimesh
from trimesh import proximity

mesh = trimesh.load("00000043_c7d977f326364e35bb5b5d27_trimesh_006.stl")

d = proximity.signed_distance(mesh.convex_hull, [mesh.center_mass])[0]
d
Out[8]: -0.2545718532356368
```

admittedly it's a weird shape, but the center of mass shouldn't require for it to be watertight, right?
anyway, here's the stl: 

[00000043_c7d977f326364e35bb5b5d27_trimesh_006.zip](https://github.com/mikedh/trimesh/files/4889898/00000043_c7d977f326364e35bb5b5d27_trimesh_006.zip)

**Comment by mikedh** [comment]
Yeah center of mass is evaluating a surface integral so it does require the mesh to be watertight... I'd suggest using `mesh.centroid` which is the area-weighted vertex average which is still valid on non-watertight geometry.
