### ISSUE TITLE
how to make vertex ids the same over multiple meshes

### ISSUE THREAD

**Issue by russoale** [mikedh/trimesh#910]
Hi, 

is there a way to make sure that the vertex ids of multiple meshes are the same. I use trimesh to load multiple person into a tool, e.g. 
![Screenshot 2020-07-09 at 13 13 58](https://user-images.githubusercontent.com/15835919/87060043-52a18500-c20a-11ea-9c7a-0c9b3a9fa9be.png)

After having marked every mesh with a new point (the black dot) I try to brute force find the closest point given the set of meshes and vertices. 

So far I am trying following: 

```
        joints = np.concatenate(scenes['joints'])
        search_candidate = True
        i = 3
        while search_candidate:
            vert_ids = []
            for mesh in scenes['meshes']:
                distances, ids = mesh.kdtree.query(joints, i)
                vert_ids.append(ids)

            vert_ids = np.concatenate(vert_ids)
            vert_id = self.search_common_vertex_id(vert_ids)
            if vert_id is not None:
                search_candidate = False

            i += 1

        for scene in self.scene_chache.values():
            mesh = scene.geometry['geometry_0']
            mesh.visual.vertex_colors[vert_id] = [0, 255, 255, 255]
```

But the resulting vertex id at the end sometimes marks the ear or the other knee. Is there a way to come around this? 

Edit: Currently I'm storing multiple scenes per mesh and point in a dictionary. So I think the more precise question would be how can I make sure the different scene objects are in the same coordinate system?

**Comment by russoale** [comment]
So basically my question can also be formulated as how to keep the topology? 

E.g. I have a predefined weight matrix which as a linear combination with the mesh vertices result in a set of points. 

![Screenshot 2020-07-10 at 12 59 38](https://user-images.githubusercontent.com/15835919/87147862-aadd9300-c2ad-11ea-913e-393b64a30d4a.png)
![Screenshot 2020-07-10 at 12 59 56](https://user-images.githubusercontent.com/15835919/87147864-ac0ec000-c2ad-11ea-99ce-bdc23f3acd78.png)
![Screenshot 2020-07-10 at 13 00 17](https://user-images.githubusercontent.com/15835919/87147866-ac0ec000-c2ad-11ea-8ce4-7e488f306a2b.png)

Am I missing something here?

**Comment by mikedh** [comment]
I'm a little confused here but I think the issue is that you are using the *same* vertex indices for *different* meshes, right? I think you need to do the search once for each mesh rather than concatenating them into one big array. I don't see why they would correspond unless all the meshes in `self.scene_chache` are 100% identical?
```
        for scene in self.scene_chache.values():
            mesh = scene.geometry['geometry_0']
            mesh.visual.vertex_colors[vert_id] = [0, 255, 255, 255]
```

Also sidenote, if `joints` are an `(n, 3)` point location in the same frame as the mesh, `mesh.kdtree.query(joints, 3))` will return the distance and index of three closest vertices: you could also do this with `point, distance, face_id = mesh.nearest.on_surface(joints)` for more accurate results.

**Comment by russoale** [comment]
Hi @mikedh thank you for the answer. I was using `mesh.nearest.on_surface(joints)` before but failed to solve my problem of getting the correct `vertex_id`.
I think the description of my problem is very poor so I will try to explain it in more understandable way. 
So yes I am using the same vertex indices for different meshes. The reason I do this is that the model I am using to generate these meshes is [SMPL](https://smpl.is.tue.mpg.de/) which has a fixed mesh topology.
Therefore the points you can see in the above meshes are defined by a weight matrix and should actually define joint locations like this for example: 
![Screenshot 2020-07-12 at 12 59 06](https://user-images.githubusercontent.com/15835919/87244778-2c652a80-c440-11ea-949f-bc68319c7ef5.png)

So my goal is to implement a tool to define a new weight matrix. Therefore, as you can see in the first image, the user can click on any triangle in the mesh. Once enough triangles were selected I'm simply defining the black point (the new joint location) by taking the mean barycentric coordinates of all selected triangles. Because the meshes are available in different poses and shapes I want to repeat that process at least 5 times. To keep it simple it should only be done for a single new joint. 

To define a new wight matrix now I have implemented a brute force algorithm which should calculate the 10 closest vertices to the point but also being the farthest away from each other. To make this as much accurate as possible I would like first to select the closest vertex averaged over all joints and meshes and then check that they are farthest away from each other if the algorithm already has solved for the first vertex. At the end of this to get the weight matrix I simply solve the linear equation using non-negative least squares given the selected vertices and joint of each mesh. 

For this overall approach it is crucial that I can keep the topology of the initially loaded vertices within the library. 
The second problem I have is that I keep all the meshes in their own scene and just switch the scenes in my tool by selecting them form a drop down. So I also need to be able to bring all scenes in the same coordinate system. 

I am actually not sure if I am over engineering this too some certain extend. It might be enough to solve for the vertex selection for every single mesh on its own. Nevertheless this would only be possible if I can guarantee all meshes have the same topology.

**Comment by russoale** [comment]
So the problem I have is best described with following code:
```
verts = self.smpl_loader.load_vertices(pose, shape, transform)
faces = self.smpl_loader.faces

mesh = trimesh.Trimesh(vertices=verts,
                        faces=faces,
                        vertex_colors=[200, 200, 200, 255],
                        face_colors=[0, 0, 0, 0],
                        use_embree=False)

x = np.matmul(self.smpl_loader.j_regressor, verts[:, 0])
y = np.matmul(self.smpl_loader.j_regressor, verts[:, 1])
z = np.matmul(self.smpl_loader.j_regressor, verts[:, 2])
joints = np.vstack((x, y, z)).T
joints = trimesh.PointCloud(joints, colors=trimesh.visual.random_color())

scene = mesh.scene()
scene.add_geometry(joints, geom_name='reg_joints')

scene.show()
```
resulting in 
![Screenshot 2020-07-12 at 15 10 38](https://user-images.githubusercontent.com/15835919/87247114-0a74a380-c452-11ea-96ad-550d20ede48c.png)

but when calculating vertices based on trimesh object 
```
x = np.matmul(self.smpl_loader.j_regressor, mesh.vertices[:, 0])
y = np.matmul(self.smpl_loader.j_regressor, mesh.vertices[:, 1])
z = np.matmul(self.smpl_loader.j_regressor, mesh.vertices[:, 2])
```
it results in different joint coordinates 
![Screenshot 2020-07-12 at 15 11 08](https://user-images.githubusercontent.com/15835919/87247145-43ad1380-c452-11ea-934e-ca863febef73.png)

**Comment by mikedh** [comment]
Oh you may just need to disable vertex merging with `process=False` passed to either the loader or constructor: `trimesh.Trimesh(**kwargs, process=False)`

**Comment by russoale** [comment]
Awesome, that did the fix! Thank you @mikedh
