### ISSUE TITLE
Calling create.cylinder() with parameter `segment=(p1, p2)` 

### ISSUE THREAD

**Issue by natsuwater** [mikedh/trimesh#911]
The calling signature of cylinder in trimesh/create.py always requires the second parameter `height` is passed, while if you use segment parameter, the `height` is overriden.  Maybe, giving any default value `height=1.0` or `height=None` would be nice.   

```
def cylinder(radius,
             height,
             sections=None,
             segment=None,
             transform=None,
             **kwargs):
```

Note also that line in 903 in creation.py `    return cylinder` seems to be never used.

**Comment by mikedh** [comment]
Makes sense, changed default kwarg to `height=None` in #912. Thanks for the report!
