### ISSUE TITLE
Preview mesh with pyrender/pyglet from notebook

### ISSUE THREAD

**Issue by Tokusei** [mikedh/trimesh#914]
Hi, I am using the Trimesh.show() command to preview the mash data in 3D, However when running in a notebook the 3js/WebGL previewer is missing key functions such as shading, wireframe, culling etc.

Is there some way to spawn an independent window from the notebook to preview the mesh?

**Comment by mikedh** [comment]
Hey yeah if you call `mesh.show(viewer='gl')` it'll force it to use the pyglet windowed viewer.

**Comment by Tokusei** [comment]
Hi Mike, Thanks for the reply, Ill try this out.
