### ISSUE TITLE
issue when using load_path

### ISSUE THREAD

**Issue by vivekbharadhwajsa** [mikedh/trimesh#915]
Hey mike, 
after creating a polygon offset and when using trimesh.load_path , An error occurs saying "tuple index out of range" relating to vertices.shape[1] == 2 in the load.py file in trimesh.path.exchange module. Can you tell me the workaround for this? or what is causing this error? 
![loadpatherror](https://user-images.githubusercontent.com/51442925/87280604-9f2ede00-c4f2-11ea-8463-0be8ca94ba87.png)

**Comment by mikedh** [comment]
Hey, I suspect that negative buffered polygon is empty (check with `imag_offset_of_slice.area`, it's probably zero).

**Comment by vivekbharadhwajsa** [comment]
Thanks. The imag_offset_of_slice.area was 0. It helped me. Thanks

**Comment by vivekbharadhwajsa** [comment]
Hey
i have another question. After calculating the medial axis using the ![pathpolymed](https://user-images.githubusercontent.com/51442925/87794323-b9e0ba00-c846-11ea-84e1-6a5d35e4be56.png) , when i see the coordinates of the medial axis, I'm getting zig-zag lines. Can you tell me why the medial axis is a zig-zag line instead of a straight line? 
Thanks

**Comment by mikedh** [comment]
Hey, depends a lot on the details. If you have a reproducible example of it giving the wrong result feel free to open a new issue!

**Comment by vivekbharadhwajsa** [comment]
Hey, 
in the pics attached below, 
![norskask](https://user-images.githubusercontent.com/51442925/88176420-85df0d80-cc27-11ea-898f-f8f505e288dd.png)
here is the medial axis
![norskmedold](https://user-images.githubusercontent.com/51442925/88176446-91323900-cc27-11ea-92d6-cb8d2133bf86.png)

in this particular slice, the medial axis is not a straight line but is comprised of points which form a zig-zag medial axis. Can you tell me why the trimesh.path.polygons.medial_axis yields a zig-zag medial axis like the one in this figure? 
Thanks
