### ISSUE TITLE
The default smoothing of the OpenGL widget

### ISSUE THREAD

**Issue by LorenzoDAsie** [mikedh/trimesh#917]
Hi,

While it's easy to remove smoothing on the trimesh.show() function, I am having a hard time figuring out how to remove smooting from trimesh.viewer.SceneWidget. There is no option to disable it and I cannot find the option when digging into the code.

It would be useful to expose the option on the widget, or perhaps implement the possibility at all. I am happy to help implementing the solution and contribute to the project, but I would need some help in where to look.

**Comment by mikedh** [comment]
Happy to take PR's! The place to figure out how to pass `smooth=False` would be the call to `rendering.convert_to_vertexlist`:

https://github.com/mikedh/trimesh/blob/master/trimesh/viewer/widget.py#L277

**Comment by LorenzoDAsie** [comment]
Perfect, I will work on it and let you know soon. Thanks!
