### ISSUE TITLE
Problem on generate an image from a mesh

### ISSUE THREAD

**Issue by freedomabcd** [mikedh/trimesh#92]
Hi:
I have a mesh and want to generate an image from a given pose.
I find the example/offscreen_render.py can generate the image. So I try it.
But some problems happen. 
It seems that scene.transformations are replaced by scene.graph.
So I fix this bug and try the following code:
`import sys
import numpy as np
import trimesh

if __name__ == '__main__':
    # print logged messages
    trimesh.util.attach_to_log()

    # load a mesh
    mesh  = trimesh.load('../models/featuretype.STL')

    # get a scene object containing the mesh, this is equivalent to:
    # scene = trimesh.scene.Scene(mesh)
    scene = mesh.scene()

    r = trimesh.transformations.rotation_matrix(np.radians(45.0), [0,1,0], 
                                                scene.centroid)    
    # print type(r)
    for i in range(4):
        trimesh.constants.log.info('Saving image %d', i)
        
        # rotate the camera view
        camera_new = np.dot(np.asarray(scene.graph.get('camera')[0]), r)
        scene.graph.update('camera', matrix=camera_new)

        file_name = 'render_' + str(i) + '.png'

        # saving an image requires an opengl context, so if -nw
        # is passed don't save the image
        if not '-nw' in sys.argv:
            # save a render of the object as a png
            scene.save_image(file_name,
                             resolution=np.array([1920,1080])*2)`

But the produced image is not right. Is any thing wrong?

Thanks!

**Comment by mikedh** [comment]
Ah good catch, I was reseting the camera transform in viewer's init. Example updated and I added a check to fix the nuking of the camera transform in https://github.com/mikedh/trimesh/commit/e78f313454e79402da56bcee6cdf5ea8504e6fae 

Thanks for the report!

**Comment by freedomabcd** [comment]
Hi, but the resulting image is also black. Is it right?
How to render an image from the given pose?

**Comment by mikedh** [comment]
Ah thats not the design intent, it should render a centered image of that model. What platform are you on, and does `mesh.show()` work? Is your pyglet/opengl install working?

**Comment by freedomabcd** [comment]
I use ubuntu 16.04 and mesh.show() runs well.
I want to render an image from a 3d mesh(.ply) at the given pose.
How can I do that?

**Comment by mikedh** [comment]
Hmm, there could be a bunch of things wrong. It's usually the transform- could you try running the exact fixed example and see if it works:
https://github.com/mikedh/trimesh/blob/master/examples/offscreen_render.py

Thanks!
Mike

**Comment by mikedh** [comment]
Hey, feel free to re- open if running the exact example doesn't produce the output you'd expect.
