### ISSUE TITLE
fix_normals() is always None 

### ISSUE THREAD

**Issue by aiyl** [mikedh/trimesh#920]
Hi, Mike! I need to check normals in obj. Can't understand how is fix normals working

**Comment by mikedh** [comment]
Hey, `mesh.fix_normals()` is an in-place operation so it doesn't return anything. You can see what it's doing: https://github.com/mikedh/trimesh/blob/9393fe3457f0df7c7a1f6289dd1dca2e274d9df3/trimesh/repair.py#L139-L164
