### ISSUE TITLE
Deleting internal faces after union

### ISSUE THREAD

**Issue by 1234shel** [mikedh/trimesh#928]
Hi,

I am trying to do a union between two meshes using scad as the engine. I read somewhere that scad deletes the internal geometry during the union operation. I just wanted to double check on this. Are the inward facing faces and vertices deleted in the union operation with scad?

**Comment by mikedh** [comment]
Hey, the best way to check is probably just to run it and see what happens
😆

**Comment by 1234shel** [comment]
I am evolving meshes and so I am potentially dealing with hundreds of thousands of meshes and I can’t verify for each one without a script which I thought I could save time on by just asking here. I wanted to be sure it works well for all cases but instead I am getting a smart ass answer. 

I think you find it cool to make fun of people for asking honest questions. If you don’t have anything useful to say maybe you shouldn’t say anything at all.

**Comment by psigen** [comment]
@1234shel: I tried it.  It seems like it does.

```
module example_union()
{
    union() {
        cube([30, 30, 30], center = true);
        difference() {
            cube([20, 20, 20], center = true);
            cube([10, 10, 10], center = true);
        }
    }
}

example_union();
```
![image](https://user-images.githubusercontent.com/2805291/88445424-84147600-cdf0-11ea-8b47-091bef046f43.png)

If you need a more precise answer, please consider asking your question on the OpenSCAD forum:
http://www.openscad.org/community.html

They might be more equipped to answer a technical question about the SCAD union operation than the OSS developer of a completely different library.

**Comment by 1234shel** [comment]
Thanks @psigen!
