### ISSUE TITLE
Orthographic camera

### ISSUE THREAD

**Issue by RohanChacko** [mikedh/trimesh#929]
Hi

Is it possible to simulate an orthographic camera in trimesh? I see the default one is perspective.

**Comment by mikedh** [comment]
Hey, it's not currently implemented in `trimesh`, but `pyrender` has implemented an `OrthographicCamera` object: https://github.com/mmatl/pyrender/blob/master/pyrender/camera.py

Happy to take PR's unifying trimesh-pyrender camera schemes or adding orthographic support to trimesh!
