### ISSUE TITLE
Raycast triangle index bug?

### ISSUE THREAD

**Issue by benjiebob** [mikedh/trimesh#93]
Hi Mikedh,
Firstly, fantastic library - I've been using this for a few weeks now and have been having a lot of fun. However, I've been having an issue with the raycast functions, even when applied to your own primitives and wonder if you can help me. 

I am trying to generate an image of triangle ids, created by sending rays of varying directions from the same camera origin. When doing this, it appears the 'hits' are correct (shown by the correct silhouette) but the image of triangle ids shows incorrect triangles (i.e. not the first hit) being returned.

Binary Image Showing Hits
![correct_hits](https://user-images.githubusercontent.com/17785299/31716590-7ff6dcc8-b400-11e7-8272-f98daac7fdcc.png)

Image Showing Triangle Ids
![incorrect_triangles](https://user-images.githubusercontent.com/17785299/31716591-80124076-b400-11e7-9b81-a05875717942.png)

The code below demonstrates the problem: (feel free to click on the 2nd figure when running the code to see information about the triangles).

```python
import trimesh
import numpy as np
import matplotlib.pyplot as plt

def main():
    # Generate a 1 x 1 x 1 cube using the trimesh box primitive
    cube_mesh = trimesh.primitives.Box(extents = [2, 2, 2]) 
`
    # Set camera focal length (in pixels)
    f = np.array([1000., 1000.])

    # Set up a list of ray directions - one for each pixel in our (256, 256) output image.
    ray_directions = []
    h, w = 256, 256
    for y in range(-h / 2, h / 2):
        for x in range(-w / 2, w / 2):
            ray_directions.append(np.array([x, y, f[0]]))
    ray_directions = np.array(ray_directions)

    # Initialize the camera origin to be somewhere behind the cube.
    cam_t = np.array([0, 0, -15.])
    # Duplicate to ensure we have an camera_origin per ray direction
    ray_origins = np.tile(cam_t, (ray_directions.shape[0], 1)) 


    # Perform 256 * 256 raycasts, one for each pixel on the image plane. We only want the 'first' hit.
    index_triangles, index_ray = cube_mesh.ray.intersects_id(
        ray_origins = ray_origins,
        ray_directions = ray_directions,
        multiple_hits = False
    )

    # Create a hit matrix, initialized with -1 values. Then associate hit pixels (i.e. those whose raycast direction hit the cube) 
    # with the 'corresponding hit triangles'. Unhit pixels remain as -1
    hit_matrix = np.ones((ray_directions.shape[0])) * -1
    hit_matrix[index_ray] = index_triangles

    # Turn this into an image
    hit_tri_img = hit_matrix.reshape((h, w), order = 'F')

    # First, forget about triangle ids and simply set hit pixels (i.e. those which are not -1) to 1.0. If working correctly, this should return a lovely
    # silhouette of a cube. 
    sil_img = np.zeros_like(hit_tri_img)
    sil_img[np.where(hit_tri_img != -1)] = 1.0

    # This correctly shows a silhouette of a cube. This shows the 'hits' are correct.
    plt.figure()
    plt.imshow(sil_img)
    plt.show()
    
    # This event handler allows you to click points on the figure and see information about the hit location
    def on_click(event):
        if event.xdata is not None and event.ydata is not None:
            x_co, y_co = int(round(event.xdata)), int(round(event.ydata))
            # Permute (x, y) to account for difference in matplotlib (column then row) vs. 
            # numpy (rows then columns) coordinate system.
            tri_id = hit_tri_img[y_co, x_co].astype(int)
            print ("({0}, {1}) = Tri_Id: {2}, Points: ({3}, {4}, {5})".format(
                y_co, # Row
                x_co, # Column
                tri_id, # Hit triangle id
                cube_mesh.faces[tri_id][0], # Triangle Vertex Id 0
                cube_mesh.faces[tri_id][1], # Triangle Vertex Id 1
                cube_mesh.faces[tri_id][2])) # Triangle Vertex Id 2

    # Show the figure. There are some artefacts on the figure with incorrect triangles returned.
    fig = plt.figure()
    plt.imshow(hit_tri_img)
    fig.canvas.mpl_connect('button_press_event', on_click)   
    plt.show()

    print ("Finished debugging")

if __name__ == '__main__':
    main()
```

**Comment by mmatl** [comment]
Hmm, it looks like the `multiple_hits` parameter for `intersects_id` is not supported in the native code (see [here](https://github.com/mikedh/trimesh/blob/master/trimesh/ray/ray_triangle.py)), although it looks like it's supported in the embree raytracing wrapper (see [here](https://github.com/mikedh/trimesh/blob/master/trimesh/ray/ray_pyembree.py)).

**Comment by mikedh** [comment]
Matt's right, it looks like the multiple_hits parameter isn't doing anything in the native raytracer, and pyembree would probably solve your immediate problem (as pyembree's default behavior is to only return the first face, and a bunch of logic is required to return multiple hits).

However, the design intent *was* to have matching API's for both ray engines, so people without pyembree would fall back to the numpy one. I'll try to add a fix and some unit tests that check to make sure both the embree/native functions return identical output. 

Thanks for the report!

**Comment by benjiebob** [comment]
Thank you both for your responses. I installed embree & pyembree from source and reran the example above. Image below shows it's all working properly!

![raycast_working](https://user-images.githubusercontent.com/17785299/31778313-3a16aa2e-b4e8-11e7-8604-7f4c1008fb96.png)

**Comment by mikedh** [comment]
Hey, I think I fixed this in https://github.com/mikedh/trimesh/commit/ed97b34d0a92bcd3742aec8d99fecddaad4d5514 and added your example to tests in https://github.com/mikedh/trimesh/commit/f12543e9b27106b234d1cc36d5c21aa905d76339. Thanks!
