### ISSUE TITLE
scene.save_image with visible=False save a black image 

### ISSUE THREAD

**Issue by HenriMir** [mikedh/trimesh#930]
hello, sorry if the question has already been posted before but I can't solve the issue.
the scene.save_image when visible=True works perfectly but when visible=False it saves a black image. 

I saw in https://github.com/mikedh/trimesh/issues/273 and https://github.com/mikedh/trimesh/issues/125
that the problem is mainly platform specific, but does someone has an exemple of platform and libraries versions that makes the save_image with visible=False works? 

Thanks!

**Comment by mikedh** [comment]
Hey, I just checked on Ubuntu 18.04 with Nvidia drivers and it wasn't working with `visible=False`. The last time I had it working with `visible=False` I was on an Ubuntu 16.04 Parallels desktop VM. It's a shame it's so flaky, happy to take PR's if you can figure out behavior making this more reliable! https://github.com/mikedh/trimesh/blob/2115c0d393bbb75443cdd42cc18ab0f99bf1d081/trimesh/viewer/windowed.py#L830-L877

**Comment by HenriMir** [comment]
Thanks for the answer!
Actually I got around the problem using pyrender which connects very well to trimesh to generate an image from a trimesh mesh.
I can give a reproducible pyrender based code to display a trimesh mesh if you want
