### ISSUE TITLE
"Segment" argument for annulus (as for cylinder)

### ISSUE THREAD

**Issue by AgileEnabler** [mikedh/trimesh#931]
trimesh.creation.cylinder allows use of "segment" as an input to define an axis along which the cylinder is created. For simplicity and consistency, the argument could be made available for trimesh.creation.annulus as well. Currently the simplest way to have something similar is, apparently, by using "trimesh.geometry.align_vectors", as pointed out in #325 , but that is not immediately apparent for users.

**Comment by mikedh** [comment]
Good idea! Added in #933, thanks for the report!
