### ISSUE TITLE
Finding adjacent unique cylinder elements

### ISSUE THREAD

**Issue by bigeyesung** [mikedh/trimesh#935]
Hi,
I am working on the construction industry. One of my work now is to find the adjacent pipe connections. (For example, see the picture attached). In 3D software, there are many pipe sections(cylinder shape) to make a long pipeline. Each section is a unique cylinder element and my goal is to find the connection of these sections.
Currently I use ray tracing to hit the meshes(intersects_location(ray_origins, ray_directions, **kwargs)). Judging the distance from the hit location to see if they are connected or not. Just wondering if there is any other solutions? 

![640x480-libreria-bim-abn](https://user-images.githubusercontent.com/17064093/88891171-9a7c6080-d23a-11ea-83b3-6415630f5c3d.jpg)

**Comment by mikedh** [comment]
Neat! Ray tests seem like a pretty good way of doing it, you might also check out using [collision checks](https://github.com/BerkeleyAutomation/python-fcl) which could be faster. You could find all pairs in collision, create a networkx graph, and then use traversals to build up an ordered list of pipe sections.

**Comment by bigeyesung** [comment]
@mikedh Thanks for this info. the collision class is really helpful and faster.
