### ISSUE TITLE
path rendering and wireframe rendering are inconsistent

### ISSUE THREAD

**Issue by soaroc** [mikedh/trimesh#940]
When I tried to render a triangle on wireframe mode and render the edge using path3d. I found the rendering results are not exactly coincident. I'm pretty sure the vertices are exactly the same. 

Below is a screenshot of a corner. The black corner is rendered with path3d and red one is rendered as a triangle on wireframe mode. 

![Screenshot from 2020-08-04 15-41-51](https://user-images.githubusercontent.com/4235760/89267567-f9dad600-d669-11ea-91c2-a266e49b6f69.png)

Is there any special for path3d rendering?

**Comment by mikedh** [comment]
Hey, yeah there is a mildly cheesy hack that offsets paths towards the camera, to avoid z-fighting on paths drawn over meshes:
https://github.com/mikedh/trimesh/blob/64a61ea8ee1695db81ebf9a36b1ed57c3e79e4c1/trimesh/viewer/windowed.py#L725-L733

We could probably make that optional if it's a problem.

**Comment by soaroc** [comment]
Thanks, and not a problem for me
