### ISSUE TITLE
"No module named rtree"

### ISSUE THREAD

**Issue by RobertKoenig1337** [mikedh/trimesh#941]
Hello, 
I want to check if a cube is inside (even partially) of a mesh. 
Right now I try to use mesh.contains(points), but I get the Error message 

in bounds_tree
    import rtree
ModuleNotFoundError: No module named 'rtree'

I installed trimesh via pip install and its the newest version. 

What can I do?

**Comment by mikedh** [comment]
Hey, looks like you're missing `rtree`. You can install via `pip install rtree` or `pip install trimesh[easy]` to get most of the soft runtime deps. `pip install trimesh` just installs the minimal requirements to import `trimesh` (i.e. `numpy`), to avoid a large mandatory dependency graph.

**Comment by vitsensei** [comment]
@mikedh not sure about other people here but I have never been able to install rtree through the official pip install, or through trimesh[easy]. It comes down to the fact that I'm missing some binaries that rtree depends on. I managed to resolve the issue by installing the unofficial wheel for rtree, which can be found here:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree

**Comment by mikedh** [comment]
Yeah `rtree` really needs wheels built in CI. I took a stab at it [here](https://github.com/mikedh/rtree/runs/947332354) but didn't finish, if it ever makes it over the finish line I'll PR it back to them. If anyone wants to take up the wheel-mantle that would be great!

**Comment by RobertKoenig1337** [comment]
Hi, thank you for your answers. I tried to install rtree and trimesh[easy] but as @vitsensei already said there are some error messages and it didnt install. 
I tried the wheel files but since I am quite new to programming I dont really know what to do with them. 
I downloaded the latest files (both versions 32 and 64) and ran pip install "directory" and pip install wheel "directory" for both of the files, it didnt work.  
The following error occures "'Directory to wheel file' is not a supported wheel on this platform.". 

Any tips on how I am able to install rtree or use the mesh.contains function without rtree?

**Comment by vitsensei** [comment]
@RobertKoenig1337 I think you are very close Robert. You just need to download the correct wheel for your Python. What is the current version of your Python? If you like me and using 3.7, you should be downloading Rtree‑0.9.4‑cp37‑cp37m‑win_amd64.whl (I'm using 64 bits machine).

**Comment by AymericFerreira** [comment]
Hello,
I had some trouble to use rtree on a server (because of restriction on sudo install and so on). So here is my notes and it should work on all Linux computer.
Rtree need some environnemental variables to work so you need to set them :

```
curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz
cd spatialindex-src-1.8.5
```

```
cmake -DCMAKE_INSTALL_PREFIX=path_to_spatialindex/spatialindex-src-1.8.5/ .
make && make install
export LD_LIBRARY_PATH=path_to_spatialindex/spatialindex-src-1.8.5/lib/
export SPATIALINDEX_C_LIBRARY=path_to_spatialindex/spatialindex-src-1.8.5/lib/libspatialindex_c.so
```
Then you should be able to do 

```
pip install rtree
python
```
```
import rtree
```

**Comment by RobertKoenig1337** [comment]
> 
> 
> @RobertKoenig1337 I think you are very close Robert. You just need to download the correct wheel for your Python. What is the current version of your Python? If you like me and using 3.7, you should be downloading Rtree‑0.9.4‑cp37‑cp37m‑win_amd64.whl (I'm using 64 bits machine).

Thank you for your help. It worked with the right .whl file :D
