### ISSUE TITLE
save mesh as an image

### ISSUE THREAD

**Issue by pvnieo** [mikedh/trimesh#942]
Hi,

Thank you for the great library.

Is there a way to save the current mesh as an image, but to return a numpy array (or other type of arrays) instead. I know that `data = scene.save_image(resolution=(1080,1080))` return an image, but in bytes :(

Thank you in advance!

**Comment by pvnieo** [comment]
I found this method
```
import numpy as np
import io
from PIL import Image

data = scene.save_image(resolution=(1080,1080))
image = np.array(Image.open(io.BytesIO(data))) 
```
but if there is an official method, I'm open!
Thanks!

**Comment by mikedh** [comment]
Yeah I think that's the best way! It's actually `pyglet` returning the PNG so I don't know if you can skip the encode/decode step.

**Comment by pvnieo** [comment]
@mikedh thank you for your response. Actually, when doing `data = scene.save_image(resolution=(1080,1080))`, an image is shown for a short amount of time.
Is there a way to disable this?

**Comment by mikedh** [comment]
Yeah if you pass `visible=False` to `save_image` it will hide the window... but 90% (it seems) of platforms/drivers/etc will skip the rendering (search for "black screen save image" in issues here haha) if you do that so I made the default `visible=True`.

**Comment by pvnieo** [comment]
Yeah, I tried it, and it gives black images :(

**Comment by pvnieo** [comment]
@mikedh what does `window_conf` in `SceneViewer` do?
I couldn't find it in the documentation.

**Comment by mikedh** [comment]
Hey, it's a way to override the default pyglet configuration:
https://github.com/mikedh/trimesh/blob/2115c0d393bbb75443cdd42cc18ab0f99bf1d081/trimesh/viewer/windowed.py#L137-L168

**Comment by pvnieo** [comment]
@mikedh Ok thank you.
So if I understand correctly, there is no way at the moment to save a mesh as an image, without the screen poping up?

**Comment by mikedh** [comment]
If your platform/os/drivers aren't rendering non-visible windows it's kind of a rabbit hole... you could check out [pyrender/egl](https://github.com/mmatl/pyrender/issues/7). You could also use the base trimesh docker images with the surprisingly fast software LLVMpipe rendering: https://github.com/mikedh/trimesh/tree/master/examples/dockerRender

**Comment by pvnieo** [comment]
Hi @mikedh , 
Thanks for you replay.
I tried the suggestion in the first issue you mentioned, by installing `PyOpenGL`, and adding
```import os
os.environ["PYOPENGL_PLATFORM"] = "egl"
```
to my script, but it still render black images. I'm doing something wrong?

**Comment by mikedh** [comment]
Hey, from what I understand getting EGL for headless rendering to work is quite a journey (I've never gotten it to work), although some pyrender users have reported success.

**Comment by pvnieo** [comment]
Hi @mikedh 
I succeeded to headless render using [Xvfb](https://pypi.org/project/xvfbwrapper/), but the images I got has this weird half transparence in some place, that make us see through the object (see photo in the hand). Is there a way to remove this behavior?

Thanks in advane!
![image](https://user-images.githubusercontent.com/22404728/90088994-995e2f80-dd20-11ea-928f-70d2f0c3de5c.png)

**Comment by mikedh** [comment]
Ah yeah the depth buffer in XVFB is a bit odd, example is fixed in the upcoming release, check related issue https://github.com/mikedh/trimesh/issues/943 and fix:
https://github.com/mikedh/trimesh/blob/e35693f22fb2af0769e1f220328ff8922c44b50f/examples/dockerRender/render.py#L17-L19

**Comment by pvnieo** [comment]
@mikedh Thank you for your response. The proposed solution solves my problem.
closing the issue.

**Comment by INF800** [comment]
@mikedh I have tried using 

```python
import trimesh
import argparse
from pyglet import gl


window_conf = gl.Config(double_buffer=True, depth_size=6)
scene = trimesh.load('/content/CesiumMilkTruck.glb',force='scene')
# run the actual render call                                                             
png = scene.save_image(resolution=[1920, 1080], visible=True, window_conf=window_conf)
```

as mentioned above. But it is not working.

Getting the same exemption `NoSuchDisplayException: Cannot connect to "None"`

Exemption reproduced in this colab notebook: https://colab.research.google.com/drive/1YQBenD33r6X80G3G04X6YiA1C7dx0gk8?usp=sharing


Error:
```
---------------------------------------------------------------------------
NoSuchDisplayException                    Traceback (most recent call last)
<ipython-input-49-9d490cee1dce> in <module>()
      8 scene = trimesh.load('/content/CesiumMilkTruck.glb',force='scene')
      9 # run the actual render call
---> 10 png = scene.save_image(resolution=[1920, 1080], visible=True, window_conf=window_conf)
     11 
     12 png

/usr/local/lib/python3.7/dist-packages/trimesh/scene/scene.py in save_image(self, resolution, **kwargs)
    864         from ..viewer.windowed import render_scene
    865         png = render_scene(
--> 866             scene=self, resolution=resolution, **kwargs)
    867         return png
    868 

/usr/local/lib/python3.7/dist-packages/trimesh/viewer/windowed.py in render_scene(scene, resolution, visible, **kwargs)
    900     window = SceneViewer(
    901         scene, start_loop=False, visible=visible,
--> 902         resolution=resolution, **kwargs)
    903 
    904     from ..util import BytesIO

/usr/local/lib/python3.7/dist-packages/trimesh/viewer/windowed.py in __init__(self, scene, smooth, flags, visible, resolution, start_loop, callback, callback_period, caption, fixed, offset_lines, line_settings, background, window_conf, profile, record, **kwargs)
    187                                               width=resolution[0],
    188                                               height=resolution[1],
--> 189                                               caption=caption)
    190 
    191         # add scene geometry to viewer geometry

/usr/local/lib/python3.7/dist-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    163                     self._event_handlers[message] = func
    164 
--> 165         super(XlibWindow, self).__init__(*args, **kwargs)
    166 
    167         global _can_detect_autorepeat

/usr/local/lib/python3.7/dist-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    568 
    569         if not display:
--> 570             display = pyglet.canvas.get_display()
    571 
    572         if not screen:

/usr/local/lib/python3.7/dist-packages/pyglet/canvas/__init__.py in get_display()
     92 
     93     # Otherwise, create a new display and return it.
---> 94     return Display()
     95 
     96 

/usr/local/lib/python3.7/dist-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
    121         self._display = xlib.XOpenDisplay(name)
    122         if not self._display:
--> 123             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
    124 
    125         screen_count = xlib.XScreenCount(self._display)
```

**Comment by Sxx1995** [comment]
> but the images I got has this weird half tra

Hi, I also meet the same problem. Can you share me some reference that how to use xvfb? 

Thanks a lot.
