### ISSUE TITLE
offscreen save_image still broken (even using the docker)

### ISSUE THREAD

**Issue by massich** [mikedh/trimesh#943]
This is a reopen issue from #337, #287 (and others)

I'm using this `try_offscreen.py` MWE:
```py
#!/usr/bin/env python

import trimesh
import argparse

parser = argparse.ArgumentParser(description="MWE for Offscreen rendering")
parser.add_argument("--input", type=str, help="mesh filename", default=None)
parser.add_argument("--output", type=str, help="png filename", default=None)
args = parser.parse_args()

in_fname = args.input
out_fname = args.output

mesh = trimesh.load_mesh(in_fname, process=False)
scene = trimesh.Scene(mesh)
# scene.show()
with open(out_fname, 'wb') as f:
    f.write(scene.save_image())
```
When I run it using `$ ./try_offscreen.py --input /tmp/trimesh/models/cycloidal.ply --output regular.png` it creates a proper render but it opens a window.
![out](https://user-images.githubusercontent.com/7044835/89324941-5d73fc00-d688-11ea-8c26-1cdf9dd65e8b.png)

However when I use `$ xvfb-run ./try_offscreen.py --input /tmp/trimesh/models/cycloidal.ply --output xvfb.png`, the model seems to get collapsed in one dimension:
![xvfb](https://user-images.githubusercontent.com/7044835/89325111-a1670100-d688-11ea-814b-fb61d4bc216e.png)

(or at least that's what it seems, when moving around the model)
![regular](https://user-images.githubusercontent.com/7044835/89325176-b5aafe00-d688-11ea-8696-e09af806d538.png)

I tried to run it in the docker as suggested in  https://github.com/mikedh/trimesh/issues/287#issuecomment-453165613
1 - I've created `/tmp/offscreen`
2 - copyied `/tmp/offscreen/Dockerfile` and `/tmp/offscreen/myapp.supervisor.conf` content from the comment. (and `try_offscreen.py` )
3 - `docker build -t offscreen .`
4 - `docker run -ti -v .:/tmp/offscreen offscreen /bin/bash`
and inside docker I called:
```
user@0a49ce774b84:/$ cd /tmp/offscreen/ && xvfb-run ./try_offscreen.py --input /opt/trimesh/models/cycloidal.ply --output docker_xvfb.png
```
and I get the same broken results
![docker_xvfb](https://user-images.githubusercontent.com/7044835/89326008-ec354880-d689-11ea-9510-995227d2bc79.png)

**Comment by mikedh** [comment]
Oh yeah the default `depth_size` is wonky in docker, if you manually pass a `window_conf` it does the right thing:
```
    from pyglet import gl
    root = '/trimesh/models'
    window_conf = gl.Config(double_buffer=True, depth_size=24)
    for file_name in os.listdir(root):
        scene = trimesh.load(os.path.join(root, file_name),
                             force='scene')
        # run the actual render call                                                             
        png = scene.save_image(resolution=[1920, 1080], visible=True, window_conf=window_conf)
```
I'll update the `dockerRender` example, thanks for the report!

**Comment by massich** [comment]
great. Thx, I tried in the docker file (debian) and it works. I also tried in an Ubuntu 18.4 machine and everything is fine aswell.

closing.
