### ISSUE TITLE
How to import STP STEP files?

### ISSUE THREAD

**Issue by marcofariasmx** [mikedh/trimesh#945]
Hello, thank you for the amazing work of the library. I am just curious on how to import STP / STEP files sucessfully, I've already installed the GMSH library but I cannot find a way to make it work properly.

Could you please help me out on this one? Thanks!

**Comment by drlukeparry** [comment]
I would suggest you need to use OpenCASDCADE - Python OCC libraries, which would give you what you desire.

**Comment by mikedh** [comment]
If you've installed gmsh with `pip install gmsh` you can also use the `gmsh` interface (which I belive is using OpenCASCADE under the hood IIRC):
```
In [1]: import trimesh

In [2]: r = trimesh.Trimesh(**trimesh.interfaces.gmsh.load_gmsh('orn.stp'))

In [3]: r
Out[3]: <trimesh.Trimesh(vertices.shape=(1382, 3), faces.shape=(2852, 3))>
```

**Comment by marcofariasmx** [comment]
Sorry for late replying, haven't had the chance to check it out. It worked like a charm, thank you very much @mikedh!
