### ISSUE TITLE
Is there a simple way to detect reflective symmetry in trimesh?

### ISSUE THREAD

**Issue by CDWJustin** [mikedh/trimesh#947]
Hi there,

Just want to check if there is an easy way to detect reflection symmetry using trimesh?

Thanks!

**Comment by mikedh** [comment]
Oh interesting... you probably looked at the `mesh.principal_inertia_components` already? For radial symmetry 2/3 are the same, for spherical 3/3 of them are the same. I suppose not all that helpful for reflection, nothing super easy or clean comes to mind. The center of mass is (probably) on the plane of reflection, so one really crude way of doing it would be to sample a large number of points on the surface, and then check them against candidate planes (and possibly refine with `scipy.optimize`). 

One thing I noticed in my example geometry was that there were a LOT of valid planes of reflection in my simple geometry:

```
import trimesh
import numpy as np

from shapely.geometry import Polygon

if __name__ == '__main__':
    trimesh.util.attach_to_log()

    m = trimesh.creation.extrude_polygon(
        polygon=Polygon([[0, 0], [2, 0], [2, 1], [1, 0.5], [0, 1], [0, 0]]),
        height=1.0)

    # sample points on the surface of the mesh
    # this avoids tesselation biases
    samples = m.sample(10000) - m.center_mass

    # get a bunch of unit vectors on a hemisphere
    hemisphere = trimesh.util.spherical_to_vector((
        trimesh.util.grid_linspace([[0, 0], [np.pi, np.pi]], 100)))

    # find the sum number of points on each side of the plane
    # if there are an *equal* number of points on both sides it is
    # likely a plane of reflection although this is pretty crude
    u = np.abs([np.sign(np.dot(samples, v)).sum() for v in hemisphere])

    # show the best candidate vector
    viz = trimesh.Scene(
        [trimesh.load_path([[0, 0, 0], hemisphere[u.argmin()]]),
         trimesh.PointCloud(samples)]).show()
```
![samples](https://user-images.githubusercontent.com/1403074/89483617-7c4abf00-d76a-11ea-82ad-4bc8d149fd41.png)
