### ISSUE TITLE
path.arc.arc_center fails

### ISSUE THREAD

**Issue by AgileEnabler** [mikedh/trimesh#949]
trimesh.path.arc.arc_center([[30156.18,  1673.64, -2914.56], [30152.91,  1780.09, -2885.51], [30148.3,   1875.81, -2857.79]]) fails, but I do not see why it should (they're not colinear...). I get good results following the process in:
https://stackoverflow.com/questions/20314306/find-arc-circle-equation-given-three-points-in-space-3d

**Comment by mikedh** [comment]
Ah, it's comparing a unit vector with a large magnitude vector. In `path.intersections` if we unitize the vector `w` it works, I pushed a fix to a branch and added your example as a test. Thanks for the report!
