### ISSUE TITLE
Error loading "empty" ASCII STL file

### ISSUE THREAD

**Issue by sanguinariojoe** [mikedh/trimesh#95]
If you build an "empty" ASCII STL file,
```
f = open('empty.stl', 'w')
f.write('solid Empty\n')
f.write('endsolid Empty')
f.close()
```
the mesh loader is crashing because the whole file has not 84 bytes. i.e. `load_stl_binary` is raising a `ValueError` exception in the following line:

```
header = np.fromstring(file_obj.read(84), dtype=_stl_dtype_header)
```

instead of `HeaderError`, which redirects to `load_stl_ascii`.

I suggest to simply add a try and except to the conflicting numpy parsing line

**Comment by mikedh** [comment]
Ah, good catch. Fixed (probably) in https://github.com/mikedh/trimesh/commit/bcb5a057dfd4a731707695c1d60fdf63e1d3aad6

Thanks for the report!
