### ISSUE TITLE
Geodesic distance

### ISSUE THREAD

**Issue by pvnieo** [mikedh/trimesh#955]
Hi, 

Thank you for the great library.

Is there a way to compute the geodesic distance between a vertex, and all the other vertices using trimesh?  I looked in the documentation, and I couldn't find anything related with geodesic.

Thank you in advance!

**Comment by mikedh** [comment]
Hey, there's definitely better ways to do it haha, but you might check out the shortest path example:
https://trimsh.org/examples/shortest.html

If you need more precision you can run `subdivide` or `subdivide_to_size` on the mesh first.

**Comment by pvnieo** [comment]
This answer the question.

Thank you! closing the issue.
