### ISSUE TITLE
How to ignore the warning during loading the mesh.

### ISSUE THREAD

**Issue by zshyang** [mikedh/trimesh#963]
```
unable to load materials from: model.mtl
specified material (material_0_24)  not loaded!
unable to load materials from: model.mtl
```

I keep get warnings like the above. This warning could make me not able to see my other prints because it is too much.

Is there any way that I could not see the warning above during loading meshes.

Best regards,
zshyang

**Comment by maxkw** [comment]
I am able to turn the warnings off with the following: 

```
import logging
logger = logging.getLogger("trimesh")
logger.setLevel(logging.ERROR)
```
