### ISSUE TITLE
No module named 'scipy'

### ISSUE THREAD

**Issue by yingzhang1109** [mikedh/trimesh#965]
I tried to run the cross section example, but I got this, 

 File "C:\ProgramData\Anaconda3\envs\grad4\lib\site-packages\trimesh\path\repair.py", line 11, in <module>
    from scipy.spatial import cKDTree

ModuleNotFoundError: No module named 'scipy'

Any suggestion?

**Comment by mikedh** [comment]
Hey, you probably need to install scipy (`pip install scipy`) or trimesh with extra packages: `pip install trimesh[easy]`.
