### ISSUE TITLE
Is there any way to clean up the cross section profile?

### ISSUE THREAD

**Issue by yingzhang1109** [mikedh/trimesh#972]
Hi, I generated all the coordinates for the cross-section profile, but I noticed that there are many segments. even for a short line, it breaks into several segments. I am wondering if there is any way to clean up those coordinates? Any suggestion? Thanks a lot!

**Comment by mikedh** [comment]
Yeah the segments will match the original tesselation with one segment per triangle. The easiest way to reduce that is probably [shapely.simplify](https://shapely.readthedocs.io/en/latest/manual.html#object.simplify):

```
In [1]: import trimesh

In [2]: m = trimesh.creation.box().subdivide()

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(26, 3), faces.shape=(48, 3))>

In [4]: s = m.section(plane_origin=[0,0,0], plane_normal=[1,1,1])

In [5]: s
Out[5]: <trimesh.Path3D(vertices.shape=(9, 3), len(entities)=1)>

In [6]: p, T = s.to_planar()

In [7]: p
Out[7]: <trimesh.Path2D(vertices.shape=(9, 2), len(entities)=1)>

In [8]: p.polygons_full
Out[8]: 
array([<shapely.geometry.polygon.Polygon object at 0x7f24f2433080>],
      dtype=object)

In [9]: polygon = p.polygons_full[0]

In [12]: len(polygon.exterior.coords)
Out[12]: 10

In [14]: len(polygon.simplify(0.01).exterior.coords)
Out[14]: 7
```

**Comment by yingzhang1109** [comment]
> Yeah the segments will match the original tesselation with one segment per triangle. The easiest way to reduce that is probably [shapely.simplify](https://shapely.readthedocs.io/en/latest/manual.html#object.simplify):
> 
> ```
> In [1]: import trimesh
> 
> In [2]: m = trimesh.creation.box().subdivide()
> 
> In [3]: m
> Out[3]: <trimesh.Trimesh(vertices.shape=(26, 3), faces.shape=(48, 3))>
> 
> In [4]: s = m.section(plane_origin=[0,0,0], plane_normal=[1,1,1])
> 
> In [5]: s
> Out[5]: <trimesh.Path3D(vertices.shape=(9, 3), len(entities)=1)>
> 
> In [6]: p, T = s.to_planar()
> 
> In [7]: p
> Out[7]: <trimesh.Path2D(vertices.shape=(9, 2), len(entities)=1)>
> 
> In [8]: p.polygons_full
> Out[8]: 
> array([<shapely.geometry.polygon.Polygon object at 0x7f24f2433080>],
>       dtype=object)
> 
> In [9]: polygon = p.polygons_full[0]
> 
> In [12]: len(polygon.exterior.coords)
> Out[12]: 10
> 
> In [14]: len(polygon.simplify(0.01).exterior.coords)
> Out[14]: 7
> ```

That really helps! Thank you!
