### ISSUE TITLE
VoxelMesh Object no attribute 'raw'

### ISSUE THREAD

**Issue by gbalatz** [mikedh/trimesh#98]
Hello @mikedh ,

I hate to bother you again, but since the update of the library today i get following error Stacktrace.
>Traceback (most recent call last):
  File "script.py", line 55, in <module>
  np = numpy.array(voxel_mesh.raw)
AttributeError: 'VoxelMesh' object has no attribute 'raw'

My Code looks like this:

```python
my_mesh = trimesh.load_mesh(stuff.stl)
voxel_mesh = my_mesh.voxelized(someInteger)
np = numpy.array(voxel_mesh.raw)
```

What am i doing wrong?

**Comment by mikedh** [comment]
Hey, I think you're looking for `voxel_mesh.matrix`: I changed the name of `voxel_mesh.raw` when I did a minor refactor of the voxel module a few weeks ago.
