### ISSUE TITLE
slice_mesh_plane: `use_embree=False` ignored

### ISSUE THREAD

**Issue by mur6** [mikedh/trimesh#980]
Hello!
I install pyembree in my environment, and use trimesh with setting `use_embree=False`, like this.
```
>>> import trimesh
>>> mesh = trimesh.Trimesh(vertices=[[0, 0, 0], [0, 0, 1], [0, 1, 0]], faces=[[0, 1, 2]], use_embree=False)
>>> mesh.ray
<trimesh.ray.ray_triangle.RayMeshIntersector object at 0x7f63c7a67f90>
```
`mesh.ray` is an instance of `trimesh.ray.ray_triangle.RayMeshIntersector`, which makes sense.

Next, I use `slice_mesh_plane` method with setting `use_embree=False`, like this.
```
>>> mesh2 = trimesh.intersections.slice_mesh_plane(
...                    mesh,
...                    plane_origin=[0, 0, 0],
...                    plane_normal=[0, 0, 1],
...                    use_embree=False)
>>> mesh2.ray
<trimesh.ray.ray_pyembree.RayMeshIntersector object at 0x7f63c69d0350>
```
`mesh2.ray` is an instance of `trimesh.ray.ray_pyembree.RayMeshIntersector` despite `use_embree=False`.
Is that ok?

**Comment by mikedh** [comment]
Yeah true it would be reasonable to pass the `kwargs` passed to the slice function to the new mesh, https://github.com/mikedh/trimesh/commit/1a4129de46028b093a6c9d3d8dde4faec486dc2c should allow your current logic to do what you want.

**Comment by mur6** [comment]
Thank you very much! It really helps!

**Comment by mikedh** [comment]
No worries, thanks for the report!
