### ISSUE TITLE
Support for loading PCD file format

### ISSUE THREAD

**Issue by dhirajsuvarna** [mikedh/trimesh#992]
Hi,

When I try to load a `pcd` file using `trimesh.load(iPCDFilePath)` it fails with the error `pcd file is not supported`

Am I doing this right or is there any other method of loading a `.pcd` file?

**Comment by mikedh** [comment]
Hey, yeah PCD isn't currently implemented in trimesh, you might check this out however: https://github.com/dimatura/pypcd
