### ISSUE TITLE
Export OBJ file, but cannot get the MTL file

### ISSUE THREAD

**Issue by yingzhang1109** [mikedh/trimesh#996]
Hey, I am trying to export a colored mesh to an obj file with 

with open('test.obj', 'w', encoding='utf-8') as f:
    scene.export(f, file_type='obj')

In this way, there is no MTL file generated. I am wondering how can I export the MTL file to show the color? Any suggestion is welcomed. Thanks a lot!

**Comment by mikedh** [comment]
Hey, the exporter in this instance needs a `trimesh.resolvers.Resolver` to be passed so it is able to write additional files (i.e. the MTL/PNG). If you pass export a filename it is supposed to automatically create the resolver (although this exposed another bug, which I just opened a fix for):

```
In [1]: import trimesh

In [2]: s = trimesh.load('/home/mikedh/trimesh/models/duck.zae')

In [3]: ls

In [4]: s
Out[4]: <trimesh.Scene(len(geometry)=1)>

In [5]: _ = s.export('duck.obj')

In [6]: ls
duck.obj  material0.mtl  material0.png


```

**Comment by yingzhang1109** [comment]
Got it! Thanks a lot!
