### ISSUE TITLE
Detect a solid hole or a bulge on the mesh surface

### ISSUE THREAD

**Issue by mstimpfl** [mikedh/trimesh#998]
Hi!

Thank you very much for this library, it's just great! Currently I have a problem and I'm not able to find a fast and stable solution. Maybe somebody has an idea and can share it with me...

Given is a point p on the surface of an object and the area within the radius r around this point (the area within a circle perpendicular to the points normal n projected onto the objects surface). I want to know if there is a hole or a bulge within this area. In other words: Given a cylinder (with radius r, origin on the point p and aligned with the points normal n), the surface of the object should only intersect with the outer surface of the cylinder, and not with its base or top surface.

Valid:
![image](https://user-images.githubusercontent.com/70201694/93449866-8ddcc600-f8d5-11ea-8584-58962c90ad9d.png)

Invalid:
![image](https://user-images.githubusercontent.com/70201694/93449886-96350100-f8d5-11ea-8558-16550e64a281.png)

I implemented it by analyzing the boolean intersection of object and cylinder, but it is very slow and the generated mesh often is kind of messy. As I can get the points and faces of intersection with the objects surface and the outer surface of the cylinder, I was thinking about searching adjacent faces and analyzing them. Could you or somebody help me out with a faster and more stable method?

Any suggestions will be highly appreciated. 
Thank you!

**Comment by mikedh** [comment]
Interesting! It seems like you might also be able to do it with a cross section with a plane both slightly above and slightly below the query plane? Or possibly `python-fcl` based collisions?

**Comment by mstimpfl** [comment]
Thank you @mikedh ! I implemented the test using the method with the cross section you suggested, following the example in https://trimsh.org/examples/section.html.
